<div class="top-pad"></div>

<div class="content-padding" ng-show="ready">

	<h1 class="title left"><i class="fa fa-smile-o"></i><span>Customer</span></h1>

	<div class="divider"></div>

	<h2 class="title"></i> Reward</h2>
	<ul class="link-list">
		<li>
			<span class="title link" ng-click="reward_settings()">Settings</span>
		</li>
	</ul>

</div>

<spinner-loading></spinner-loading>
<hack-expand-content></hack-expand-content>