<div class="status">

</div>

<div class="header">
	<div class="restaurant-name"><?=$this->order->restaurant()->name?></div>
	<div class="order-id">#<?=$this->order->id_order?></div>
	<div class="divider"></div>
</div>

<div class="order">
	<div class="order-item-block">
		<div class="order-icon"><i class="icon-<?=$this->order->delivery_type == 'delivery' ? 'delivery' : 'takeout'?>"></i></div>
		<div class="order-info">
			<?=$this->order->delivery_type == 'delivery' ? 'Delivery' : 'Takeout'?>
		</div>
	</div>

	<div class="order-item-block">	
		<div class="order-icon"><i class="icon-<?=$this->order->pay_type == 'card' ? 'card' : 'cash'?>"></i></div>
		<div class="order-info">
			<?=$this->order->pay_type == 'card' ? 'Card' : 'Cash'?>
		</div>
	</div>
	
	<div class="order-item-block">
		<div class="order-icon"><i class="icon-clock"></i></div>
		<div class="order-info">
			<?=$this->order->date()->format('h:i A')?>
		</div>
	</div>
	
	<div class="order-item-block">
		<div class="order-icon"><i class="icon-timer"></i></div>
		<div class="order-info">
			<?php 
			if( $this->order->restaurant()->delivery_estimated_time ){
				$this->order->date()->modify('+'.$this->order->restaurant()->delivery_estimated_time.' minutes')->format('h:i A');	
			}
			 ?>
		</div>
	</div>
	
	<div class="divider"></div>

	<div class="divider dots"></div>
	<br><br>
	
	<div class="order-icon"><i class="icon-user"></i></div>
	<div class="order-info">
		<?=$this->order->name?>
		<br><a href="tel:+1<?=$this->order->phone?>"><?=preg_replace('/^(\d{3})(\d{3})(\d{4})$/i', '$1-$2-$3', $this->order->phone)?></a>
	</div>

	<? if ($this->order->notes) : ?>
		<div class="order-comment-arrow"></div>
		<div class="order-comment">
			<p><?=nl2br($this->order->notes)?></p>
		</div>
	<? else : ?>
		<br>
	<? endif ; ?>

	<a href="http://maps.apple.com/?daddr=<?=$this->order->address?>&saddr=<?=$this->order->restaurant()->address?>"><div class="order-map" style="background: url('https://maps.googleapis.com/maps/api/staticmap?size=640x300&markers=color:green%7Clabel:A%7C<?=str_replace("\n",' ',str_replace('#','',$this->order->address))?>&markers=color:red%7Clabel:B%7C<?=$this->order->restaurant()->loc_lat?>,<?=$this->order->restaurant()->loc_long?>&sensor=false&visual_refresh=true');"></div></a>
			
	<br>
	
	<div class="order-item-block order-map-block">
		<div class="order-icon"><i class="icon-map-home"></i></div>
		<div class="order-info">
			<p class="order-info-address"><a href="http://maps.apple.com/?q=<?=$this->order->address?>"><?=nl2br($this->order->address)?></a></p>
		</div>
	</div>

	<div class="order-item-block order-map-block">
		<div class="order-icon"><i class="icon-map-restaurant"></i></div>
		<div class="order-info">
			<p class="order-info-address"><a href="http://maps.apple.com/?q=<?=$this->order->restaurant()->address?>"><?=nl2br($this->order->restaurant()->address)?></a></p>
		</div>
	</div>
	
	
	
	
	<br><br>
	<div class="divider dots"></div>
	<br><br>
<?php 
$isDriverCockpit = true; 
$delivery_service_markup = ( $this->order->delivery_service_markup ) ? $this->order->delivery_service_markup : 0;
$order = $this->order;
?>
<table width="100%" celpadding="0" cellspacing="0" class="detail">
	<thead style="font-weight:bold">
		<td class="topitem">Qty</td>
		<td class="topitem">Item</td>
		<?php if( $isDriverCockpit ) { ?>
		<td class="topitem" nowrap="nowrap">Customer Price</td>
		<td class="topitem" style="width:80px;font-size:12px;color:#666;">Store Price</td>
		<?php } else { ?>
			<td class="topitem">Price</td>
		<?php } ?>
	</thead>
	<? foreach ($order->dishes() as $dish) : ?>
		<tr>
			<td class="fooditem">1</td>
			<td class="fooditem"><?
				$food = $dish->dish()->name;
				$price = $dish->dish()->price;
				$regular_price = $dish->dish()->price;
				// add the delivery markup 
				if( $delivery_service_markup > 0 && $price > 0 ){
					$price = $price + number_format( ( $dish->dish()->price * $delivery_service_markup / 100 ), 2 );
					$price = number_format( $price, 2 );
				}
				$regular_price = number_format( $regular_price, 2 );

				$options = $dish->options();

				if (gettype($options) == 'array') {
					$options = i::o($options);
				}

				$withOptions = '';

				$selectOptions = '';

				if ($options->count()) {					

					foreach ($dish->options() as $option) {
						if ($option->option()->type == 'select') {
							continue;
						}
						$price += $option->option()->price;
						$regular_price += $option->option()->price;
						// add the delivery markup 
						if( $delivery_service_markup > 0 && $price > 0 ){
							if( $option->option()->price > 0 ){
								$option_price = number_format( ( $option->option()->price * $delivery_service_markup / 100 ), 2 );	
								$price = $price + $option_price;
							}
						}
						if($option->option()->id_option_parent) {
							$optionGroup = Crunchbutton_Option::o($option->option()->id_option_parent);
							// $withOptions .= "$optionGroup->name: ";
							if( $selectOptions == '' ){
								$selectOptions .= '&nbsp;&nbsp;';
							}
							$selectOptions .= '<i style="font-weight:600;">' . $optionGroup->name . ': ';
							$selectOptions .= $option->option()->name.', ';
						} else {
							if( $withOptions == '' ){
								$withOptions .= '<i style="font-weight:600;">&nbsp;&nbsp;With:&nbsp;';
							}
							$withOptions .= $option->option()->name.', ';
						}
						$regular_price = number_format( $regular_price, 2 );
					}
					$withOptions = substr($withOptions, 0, -2);
					$selectOptions = substr($selectOptions, 0, -2);
					if( $withOptions != '' ){
						$withOptions .= '</i>';
					}
				}

				$withoutDefaultOptions = '';
				if( $dish->id_order_dish && $dish->id_dish ){ 
					$optionsNotChoosen = $dish->optionsDefaultNotChoosen();
					$commas = ' ';
					if( $optionsNotChoosen->count() ){
						foreach( $optionsNotChoosen as $dish_option ){
							$withoutDefaultOptions .= $commas . '<i style="font-weight:600;">&nbsp;No ' . $dish_option->option()->name . '</i>';
							$commas = ', ';
						}
					}
				}

				if ( $withOptions == '' && $withoutDefaultOptions == '' && $selectOptions == '' ) {
					$food .= '.';
				} else {
					$food .= ': ';
				}

				if( $withOptions != '' ){
					$withOptions .= '.';
				}

				if( $withoutDefaultOptions != '' ){
					$withoutDefaultOptions .= '.';
				}

				if( $selectOptions != '' ){
					
					$selectOptions .= '.';
				}

				$food .= $withoutDefaultOptions;
				$food .= $withOptions;
				$food .= $selectOptions;
				?>
				<?=$food?>
			</td>
			<td style="width: 1%;" class="fooditem">
				$<?php 
				if( $isRestaurant ){
					echo number_format( $regular_price, 2 );
				} else {
					echo number_format( $price, 2 );	
				}
				?>
			</td>
			<?php if( $isDriverCockpit ) { ?>
			<td class="fooditem" style="font-size:12px;color:#666;">
				$<?php echo number_format( $regular_price, 2 ); ?>
			</td>
			<?php } ?>
		</tr>
	<? endforeach ; ?>

	<tr class="class">
		<td></td>
		<td style="text-align:right">Subtotal</td>
		<td>
		$<?php 
		if( $isRestaurant ){
			// legacy
			if( intval( $delivery_service_markup ) > 0 && !$order->price_plus_delivery_markup ){
				echo number_format( $order->price - $order->delivery_service_markup_value, 2);
			} else {
				echo number_format( $order->price, 2 );
			}	
		} else {
			if( $order->price_plus_delivery_markup ){
				echo number_format( $order->price_plus_delivery_markup, 2 );		
			} else {
				echo number_format( $order->price, 2 );
			}
		}
		?>
		</td>
		<?php if( $isDriverCockpit ) { ?>
		<td style="font-size:12px;color:#666;">
		$<?php
		// legacy
		if( intval( $delivery_service_markup ) > 0 && !$order->price_plus_delivery_markup ){
			echo number_format( $order->price - $order->delivery_service_markup_value, 2);
		} else {
			echo number_format( $order->price, 2 );
		}
		?>
		</td>
		<?php } ?>
	</tr>
	<? if ( $order->pay_type == 'card' && $order->tip ) : ?>
		<tr>
			<td></td>
			<td style="text-align:right">Tip <?php if( $order->tip_type != Crunchbutton_Order::TIP_NUMBER ) { echo $order->tip . '%'; } ?></td>
			<td>$<?=$order->tip()?></td>
			<?php if( $isDriverCockpit ) { ?>
			<td style="font-size:12px;color:#666;">
				$<?=$order->tip()?>
			</td>
			<?php } ?>
		</tr>
	<? endif ; ?>
	<? if ( $order->restaurant()->delivery_fee ) : ?>
		<tr>
			<td></td>
			<td style="text-align:right">Delivery Fee</td>
			<td>$<?=$order->deliveryFee()?></td>
			<?php if( $isDriverCockpit ) { ?>
			<td style="font-size:12px;color:#666;">
				$<?=$order->deliveryFee()?>
			</td>
			<?php } ?>
		</tr>
	<? endif ; ?>

	<? if ( $order->restaurant()->fee_customer ) : ?>
		<tr>
			<td></td>
			<td style="text-align:right">Service Fee</td>
			<td>$<?=$order->serviceFee()?></td>
			<?php if( $isDriverCockpit ) { ?>
			<td style="font-size:12px;color:#666;">
				$$<?=$order->serviceFee()?>
			</td>
			<?php } ?>
		</tr>
	<? endif ; ?>
	
	<tr>
		<td></td>
		<td style="text-align:right">Tax</td>
		<td>
		$<?php 
		$tax = $order->tax();
		if( $isRestaurant ){
			echo number_format( $tax, 2 );
		} else {
			echo number_format( $tax, 2 );	
		}
		?>
		</td>
		<?php if( $isDriverCockpit ) { ?>
		<td style="font-size:12px;color:#666;">
			$<?php echo number_format( $tax, 2 ); ?>
		</td>
		<?php } ?>
	</tr>

	<tr style="font-weight:bold;">
		<td></td>
		<td style="text-align:right">Total</td>
		<td>
		$<?php 
		if( $isRestaurant ){
			// legacy
			if( intval( $delivery_service_markup ) > 0 && !$order->final_price_plus_delivery_markup ){
				echo number_format( $order->final_price - $order->delivery_service_markup_value, 2);
			} else {
				echo number_format( $order->final_price, 2 );
			}
		} else {
			if( $order->final_price_plus_delivery_markup ){
				echo number_format( $order->final_price_plus_delivery_markup, 2 );
			} else {
				echo number_format( $order->final_price, 2 );
			}
		}
		?>
		</td>
		<?php if( $isDriverCockpit ) { ?>
		<td style="font-size:12px;color:#666;">
		$<?php
		// legacy
		if( intval( $delivery_service_markup ) > 0 && !$order->final_price_plus_delivery_markup ){
			echo number_format( $order->final_price - $order->delivery_service_markup_value, 2);
		} else {
			echo number_format( $order->final_price, 2 );
		}
		?>
		</td>
		<?php } ?>
	</tr>
	
	<?php /* Just the user and CB will see this info about gift card. See #1006. */ ?>
	<?php if( $user && $order->chargedByCredit() > 0 ) { ?>
	<tr style="font-weight:bold;">
		<td></td>
		<td style="text-align:right"><?php if( $order->pay_type == 'card' ) { ?>Gift Card <?php } else { ?> Already Paid by Gift Card <?php } ?></td>
		<td>$<?=number_format($order->chargedByCredit(),2)?></td>
	</tr>

	<tr style="font-weight:bold;">
		<td></td>
		<td style="text-align:right"><?php if( $order->pay_type == 'card' ) { ?>Total Charged <?php } else { ?> Total Owed <?php } ?></td>
		<td>$<?=number_format($order->charged(),2)?></td>
	</tr>
	<?php } ?>

	<? if ($order->pay_type == 'card' && $order->tip == 0) : ?>
		<tr>
			<td colspan="3" style="text-align:left">Customer is tipping with cash</td>
		</tr>
	<? endif ; ?>
</table>

</div>