<div class="top-pad"></div>

<div class="content-padding">
	<div class="box-content2 box-content-table box-search-bar table-sticky-dependant">
		<table>
			<tr>
				<td colspan="4"><i class="fa fa-search"></i>&nbsp;&nbsp;<input type="text" ng-model="query.search" id="search" tabindex="1" placeholder="Search suggestions"></td>
			</tr>
			<tr>
				<th>Type</th>
				<td>
					<select ng-model="query.type" id="type" ng-options="opt.value as opt.label for opt in _types" tabindex="2" class="cart-customize-select"></select>
				</td>
				<th>Status</th>
				<td>
					<select ng-model="query.status" id="type" ng-options="opt.value as opt.label for opt in _statuses" tabindex="3" class="cart-customize-select">
				</td>
			</tr>
		</table>
	</div>

	<div class="bar-loader bar-loader-search" ng-class="{'bar-loader-loading': loading}"></div>
	<ng-include src="'assets/view/listview-suggestions.html'"></ng-include>
	<div sticky-bottom="47" class="table-sticky-dependant" ng-show="pages > 1 || more || query.page > 1">
		<div class="no-box-content-color">
			<ng-include src="'assets/view/listview-paging.html'"></ng-include>
		</div>
	</div>

</div>
