<div class="top-pad"></div>

<div class="content-padding">
	<div class="box-content2 box-content-table box-search-bar table-sticky-dependant">
		<table>
			<tr>
				<td><i class="fa fa-search"></i>&nbsp;&nbsp;<input type="text" ng-model="query.search" id="search" tabindex="1" placeholder="Search Customers"></td>
			</tr>
		</table>
	</div>

	<div class="bar-loader bar-loader-search" ng-class="{'bar-loader-loading': loading}"></div>

	<ng-include src="'/assets/view/listview-customers.html'"></ng-include>
	<div sticky-bottom="47" class="table-sticky-dependant">
		<div class="no-box-content-color">
			<ng-include src="'/assets/view/listview-paging.html'"></ng-include>
		</div>
	</div>
</div>
