<div class="top-pad"></div>

<div class="content-padding">
	<h1 class="title"><i class="fa fa-smile-o"></i>Customers<div class="title-loader" ng-if="loading"><i class="fa fa-refresh fa-spin"></i></div></h1>

	<div class="box-content2 box-content-table">
		<table>
			<tr>
				<td><i class="fa fa-search"></i>&nbsp;&nbsp;<input type="text" ng-model="query.search" id="search"></td>
			</tr>
		</table>
	</div>
	
	<div class="bar-loader bar-loader-search" ng-class="{'bar-loader-loading': loading}"></div>

	<div class="box-content2 box-content-table">
		<table class="tb-zebra">
			<tr>
				<th></th>
				<th>ID</th>
				<th>Name</th>
				<th>Phone</th>
				<th>Address</th>
				<th>Orders</th>
				<th>Last&nbsp;Order</th>
			</tr>
			<tr ng-repeat="customer in customers">
				<td><a href="/customer/{{customer.id_user}}">
					<div class="customer-image-crop">
						<img ng-if="customer.image" class="customer-image" src="{{customer.image}}"></img>
						<div ng-if="!customer.image" class="customer-image customer-image-null"></div>
					</div>
				</a></td>
				<td><a href="/customer/{{customer.id_user}}">{{customer.id_user}}</a></td>
				<td>{{customer.name}}</td>
				<td><a href ng-click="callText(customer.phone)">{{customer.phone | formatPhone}}</a></td>
				<td>{{customer.address}}</td>
				<td>{{customer.orders}}</td>
				<td><span ng-if="customer._order_date"><span am-time-ago="customer._order_date"></span></span></td>
			</tr>
		</table>
	</div>
	
	<table class="tb-pagination right" ng-if="pages > 1" page-key>
		<tbody>
			<tr>
				<td class="td-prev"><button class="button orange" ng-if="query.page > 1" ng-click="setPage(query.page-1)">prev</button></td>
				<td class="td-info">Page {{query.page}} of {{pages}}</td>
				<td class="td-next"><button class="button orange" ng-if="query.page < pages" ng-click="setPage(query.page+1)">next</button></td>
			</tr>
		</tbody>
	</table>
	
	<div class="divider"></div>

</div>
