<div class="top-pad"></div>

<div class="content-padding">


	<div class="support-boxes">

		<div class="support-box-wrap box-content2" style="-webkit-column-width: 20%;">
			<br>
			<div class="no-box-content-color customer-content-box">
				<div class="customer-image-crop customer-image-crop-large">
					<img ng-if="customer.image" class="customer-image-large" src="{{customer.image}}"></img>
					<div ng-if="!customer.image" class="customer-image-large customer-image-null"></div>
				</div>
				<h1 class="customer-name-large">{{customer.name}}</h1>

				<div class="field-container">

					<div class="field-row">
						<div class="field-key">Phone</div>
						<div class="field-value"><a href ng-click="callText(customer.phone)">{{customer.phone | formatPhone}}</a></div>
					</div>
					<div class="field-row">
						<div class="field-key">Address</div>
						<div class="field-value"><a href ng-click="routeAddress(customer.address)"><span ng-bind-html-unsafe="customer.address | nl2br"></span></a></div>
					</div>
				</div>
				<br><br>
				<div class="double-cols">

					<button ng-click="creditDialog( customer.id_user );" ng-if="customer.id_user" class="button button-empty button-border button-orange"><i class="fa fa-gift"></i>&nbsp;&nbsp;Gift Card</button>

					<button ng-click="" class="button button-empty button-border button-blue" ng-class="{'button-disabled': true}"><i class="fa fa-close"></i>&nbsp;&nbsp;Deactive</button>
				</div>
			</div>
		</div>

		<div class="support-box-wrap support-widget-box-wrap">
			<a href="/orders?user={{customer.id_user}}" class="column-50 support-box-widget support-box-widget-green">
				<i class="fa fa-user support-box-widget-icon"></i>
				<div class="support-box-widget-label">Orders from this number</div>
				<div class="support-box-widget-content">{{customer.orders_from_this_customer}}</div>
			</a>

			<a href="/orders?phone={{customer.phone}}" class="column-50 support-box-widget support-box-widget-blue">
				<i class="fa fa-phone support-box-widget-icon"></i>
				<div class="support-box-widget-label">Orders from this customer</div>
				<div class="support-box-widget-content">{{customer.orders_from_this_phone}}</div>
			</a>
		</div>

		<div class="support-box-wrap box-content2" style="-webkit-column-width: 80%;">
			<div class="support-box-wrap-header">
				<h1>Credits</h1>
				<div class="support-box-header-actions-wrap">
					<div class="support-box-header-actions">
						<a href="" ng-click="creditDialog( customer.id_user );"><button class="button button-small button-small button-empty button-green"><i class="fa fa-plus"></i>&nbsp;&nbsp;Add Gift Card</button></a>
					</div>
				</div>
				<div class="divider"></div>
			</div>
			<div class="support-box-wrap support-widget-box-wrap">
				<ng-include src="'assets/view/listview-credit.html'"></ng-include>
			</div>
		</div>

	</div>

	<br><br>
	<h1 class="title"><i class="fa fa-car"></i>Orders</h1>
	<div class="bar-loader bar-loader-title" ng-class="{'bar-loader-loading': loadingOrders}"></div>
	<ng-include src="'assets/view/listview-orders.html'"></ng-include>

</div>

