
<p>
	Get new customers to put your code below in the Notes section of their first order for <b>${{account.user.referral_customer_credit|formatPrice}} off</b> and <b>earn ${{account.user.referral_admin_credit|formatPrice}}</b> yourself for every new customer you refer.
	<br>
</p>
<div class="invite-code allow-select">{{account.user.invite_code}}</div>
<p>
	<br>
	You can share this code online and in person around your community. You should have received some promo cards in your new driver Welcome Kit. You can give them to friends, put them on posters, canvas local parking lots, put them on windshields, or do whatever you think would be most effective to recruit new users in your community.
	<br>
	<br>

	Request more marketing materials
	<a href="https://docs.google.com/forms/d/1y-LOTy88YJ0tqkc2J4l3x9oBb-jF6Of9MNPVnfJUW3Y/viewform" target="_blank">here!</a>
	We'll have them to your door in 3-5 business days.
</p>