
<p>
	Get new customers to put your code below in the Notes section of their first delivery FREE
	<br>
	Plus, <strong>earn ${{account.user.referral_admin_credit|formatPrice}} yourself</strong> for every new customer you refer!
	<br>
</p>
<div class="invite-code allow-select">{{account.user.invite_code}}</div>
<p>
	<br>
	You can share this code online and in person around your community. You should have received some promo cards in your new driver Welcome Kit. You can give them to friends, put them on posters, canvas local parking lots, put them on windshields, or do whatever you think would be most effective to recruit new users in your community.
	<br>
	<br>

	Request more marketing materials
	<a href="https://docs.google.com/forms/d/1y-LOTy88YJ0tqkc2J4l3x9oBb-jF6Of9MNPVnfJUW3Y/viewform" target="_blank">here!</a>
	We'll have them at your door in 7-10 business days.

	<br>
	<br>
	Don't want to wait? Download marketing materials <a href="https://www.dropbox.com/sh/trk2i7wl4234z3j/AADmDMzJC4nKWrDbHOsUX46ya?dl=0" target="_blank">here</a>

	<br>
	<br>
	You can still drive if you’re not scheduled! Cockpit will route orders to scheduled drivers first, and if they’re not accepted within 5 minutes, unscheduled drivers will be able to accept them.

</p>