<div class="drivers-welcome">
	<div class="top-pad"></div>
	<div class="content-padding">
		<h1 class="welcome-title">Update Required</h1>

		<div class="welcome-icon"><i class="fa fa-cloud-download"></i></div>
		<p>Your App is out of date. Please download the latest version from <span ng-if="ios">The App Store</span><span ng-if="!ios">Google Play</span>.</p>
		<div class="welcome-button"><a href="{{url}}" target="_system"><button class="ladda-button button orange" data-color="orange" data-style="zoom-in"><span class="ladda-label">Download</span></button></a></div>
	</div>
</div>