<div class="login-wrap" ng-controller="LoginCtrl" ng-class="{'logged-in': account.loggedin, 'logged-out': !account.loggedin}">
	<div class="login-content hide-before-init fade-in-enter">
		<div class="logo" ng-switch="welcome">

			<span class="item" ng-switch-when="1">well, <span class="green">hello</span> there<span class="dot">!</span></span>
			<span class="item" ng-switch-when="2">aren't you looking <span class="green">lovely</span> today<span class="dot">!</span></span>
			<span class="item" ng-switch-when="3">hey, <span class="green">friend</span><span class="dot">!</span></span>
			<span class="item" ng-switch-when="4"><span class="green">welcome</span><span class="dot">!</span></span>
			<span class="item" ng-switch-when="5">you are <span class="green">beautiful</span><span class="dot">.</span></span>
			<span class="item" ng-switch-when="6">i believe in <span class="green">you</span><span class="dot">.</span></span>
			<span class="item" ng-switch-when="7"><span class="green">you</span> can do it<span class="dot">!</span></span>
			<span class="item" ng-switch-when="8">smile &nbsp;&nbsp;<span class="green">:)</span></span>
			<span class="item" ng-switch-when="9">follow your <span class="green">dreams</span><span class="dot">.</span></span>
			<span ng-switch-default>cockpit<span class="dot">.</span><span class="green">la</span></span>
		</div>

		<div class="dialog-message dialog-message-error" ng-show="error">
			Invalid username or password
		</div>
	
		<form ng-submit="login()">
			<div class="input-wrap">
				<span class="label">Username:</span>
				<span class="field"><input type="text" name="username" ng-model="username" <? if (!$this->export) : ?>autofocus="autofocus"<? endif ; ?> autocorrect="off" autocapitalize="off"></span>
			</div>
			
			<div class="input-wrap">
				<span class="label">Password:</span>
				<span class="field"><input type="password" name="password" ng-model="password" autocorrect="off" autocapitalize="off"></span>
			</div>
			
			<div class="find-restaurants button-login">
				<button class="button orange">
					Sign In
				</button>
			</div>
		</form>
		
		<div class="info">

			<a href="/onboarding">
				<div class="login-option login-option-user">
					<div class="circle"><i class="fa fa-user"></i></div>
					<br>
					New User
				</div>
			</a>

			<a href="/legal">
				<div class="login-option login-option-terms">
					<div class="circle"><i class="fa fa-info"></i></div>
					<br>
					Terms of Use
				</div>
			</a>

		</div>
	</div>
</div>
