<div class="login-wrap" ng-controller="LoginCtrl" ng-class="{'logged-in': account.loggedin, 'logged-out': !account.loggedin}">
	<div class="login-content hide-before-init">
		<div class="logo">cockpit<span class="dot">.</span><span class="green">la</span></div>

		<div class="dialog-message dialog-message-error" ng-show="error">
			Invalid username or password
		</div>
	
		<form ng-submit="login()">
			<div class="input-wrap">
				<span class="label">Username:</span>
				<span class="field"><input type="text" name="username" ng-model="username" <? if (!$this->export) : ?>autofocus="autofocus"<? endif ; ?> autocorrect="off" autocapitalize="off"></span>
			</div>
			
			<div class="input-wrap">
				<span class="label">Password:</span>
				<span class="field"><input type="password" name="password" ng-model="password" autocorrect="off" autocapitalize="off"></span>
			</div>
			
			<div class="button-pushable find-restaurants button-login">
				<button class="button orange">
					Sign In
				</button>
			</div>
		</form>
		
		<div class="info">
			Cockpit is Crunchbutton's tool of awesomeness. Looking for delivery food? Head over to <a href="http://crunchbutton.com/app" target="_blank">crunchbutton.com</a>
		</div>
	</div>
</div>
