<div class="top-pad"></div>

<div class="content-padding" ng-show="ready">

	<h1 class="subltitle"><span>Profile</span></h1>

	<ul class="ul-info box-content2">
		<li class="li-info">
			<div class="label">Name:</div>
			<div class="data">{{account.user.name}}</div>
		</li>
		<li class="li-info">
			<div class="label">Login:</div>
			<div class="data">{{account.user.login}}</div>
		</li>
		<li class="li-info" ng-if="account.user.phone">
			<div class="label">Phone:</div>
			<div class="data">{{account.user.phone | formatPhone}}</div>
		</li>
		<li class="li-info" ng-if="account.user.email">
			<div class="label">Email:</div>
			<div class="data">{{account.user.email}}</div>
		</li>
		<li class="li-info" ng-if="account.user.timezone">
			<div class="label">Timezone:</div>
			<div class="data">{{account.user.timezone}}</div>
		</li>
	</ul>
	
	<div ng-if="account.user.invite_code">
		<h1 class="subltitle"><span>Free money!</span></h1>
		<ul class="ul-info box-content2">
	
			<li class="li-info">
				<p>
					Get new customers to put this code in the Notes section of their first order for <b>${{customer_get_referred_amt|formatPrice}} off</b> and <b>earn ${{admin_refer_user_amt|formatPrice}}</b> yourself for every new customer your refer
				</p>
				<div class="invite-code allow-select">{{account.user.invite_code}}</div>
			</li>
		</ul>
	</div>
	
	<div ng-if="account.user.permissions.GLOBAL">
		<h1 class="subltitle"><span>Preferences</span></h1>

		<div class="tb-info box-content2">
			<div profile-preference class="tb-info-item" content="Notify on all support tickets" type="bool" key="notification-desktop-support-all"></div>
			<div profile-preference class="tb-info-item" content="Display demo orders" type="bool" key="demo"></div>
		</div>
	</div>

</div>

<spinner-loading></spinner-loading>
<hack-expand-content></hack-expand-content>