
<p>
	Get new customers to put this code in the Notes section of their first order for <b>${{account.user.referral_customer_credit|formatPrice}} off</b> and <b>earn ${{account.user.referral_admin_credit|formatPrice}}</b> yourself for every new customer you refer.
	<br><br>
	Copy, send email, or send text message, or maybe Facebook message.
</p>
<div class="invite-code allow-select">{{account.user.invite_code}}</div>
<p>
	<br>&nbsp;
</p>