<div class="top-pad"></div>
<div class="content-padding">

	<h1 class="title driver-title"><i class="fa fa-truck"></i></h1>

	<div class="divider"></div>
		<p>
			Crunchbutton serves as a marketplace to facilitate the ordering of food through the Crunchbutton app to customers delivered by independent delivery professionals.
			<br><br>
			The Cockpit App serves as an interface to drivers for accepting and managing orders to deliver to customers.
			<br><br>
			Ready to become an awesome driver?
		</p>
		<br><br><br>
		<a href="/onboarding">
			<button class="button green">Apply Now</button>
		</a>

	</div>
</div>
