<div class="home-top">
	<div class="menu"></div>
	<div class="logo"></div>
	<div class="pushabutton"></div>
	<div class="home-inputs">
		<table cellpadding="0" cellspacing="0" class="home-location">
			<tr>
				<td style="width: 100%;"><input class="enter-location" placeholder="Enter your location"></td>
				<td><button class="find-location"><span class="icon icon-location-arrow "></span></button></td>
			</tr>
		</table>
		<button class="button pushable orange find-restaurants">Find Restaurants</button>
	</div>
</div>

<div class="divider-orange-food divider-circle"></div>


<div class="home-white content-padding">
	<div class="logo-finger"></div>
</div>

<script>
	$(function(){
		$('.animated').autosize({append: "\n"});
	});
</script>