<div class="home-top">
	<div class="logo"></div>
	<div class="pushabutton"></div>
	<br><br>
</div>

<div class="divider-white-food divider-circle"></div>

<div class="home-orange content-padding">
	<br><br><br>
	<div class="cart-items">
		<div class="cart-item">
			<div class="icon-delete"></div>
			<div class="cart-text">
				<span class="cart-count">1</span>
				<span class="cart-name">Wenzel</span>
				<span class="cart-label">w/ standard toppings</span>
			</div>
		</div>
	</div>
	<br><br><br><br><br><br><br><br><br>
</div>

<div class="divider-orange-food divider-circle"></div>

<div class="home-white content-padding">
	<br><br><br>
	<div class="detail-form">
		<table cellpadding="0" cellspacing="0" width="100%">
			<tr>
				<td class="form-icon"><span class="icon icon-user"></span></td>
				<td><div class="input-wrap"><input type="text" placeholder="Name"></div></td>
			</tr>
			<tr>
				<td class="form-icon"><span class="icon icon-cell"></span></td>
				<td><div class="input-wrap"><input type="text" placeholder="Phone"></div></td>
			</tr>
			<tr>
				<td class="form-icon"><span class="icon icon-map"></span></td>
				<td><div class="input-wrap"><textarea placeholder="Address" class="animated"></textarea></div></td>
			</tr>
			<tr>
				<td class="form-icon"><span class="icon icon-note"></span></td>
				<td><div class="input-wrap"><textarea placeholder="Notes" class="animated"></textarea></div></td>
			</tr>
		</table>
	</div>
</div>



<div class="home-white content-padding">
	<div class="logo-finger"></div>
</div>

<script>
	$(function(){
		$('.animated').autosize({append: "\n"});
	});
</script>