<center>


<img src="/assets/images/landing-logo.png" class="logo">
<br />
<img src="/assets/images/landing-tagline.png" class="tagline">
<br />
<p class="desc">
We choose the best food that local customers love. We make your restaurant cemented as a local favorite, drive additional business, and make you and your customers happier.
</p>
<!-- img src="/assets/images/landing-cake.png" class="cake" -->

<div class="divider"></div>
<br /><br />
<div class="info-block-container">
	<div class="info-block">
		<div class="info-block-icon"><img src="/assets/images/icon-cash.png"></div>
		<div class="info-block-subwrapper">
			<div class="info-block-tag">No upfront costs.</div>
			<div class="info-block-info">There is a percentage fee, but any or all of it	can be passed to customers -- this includes credit card fees.</div>
		</div>
		<div class="divider"></div>
	</div>
	
	<div class="info-block">
		<div class="info-block-icon"><img src="/assets/images/icon-heart.png"></div>
		<div class="info-block-subwrapper">
			<div class="info-block-tag">Customers love us.</div>
			<div class="info-block-info">Simply put, we're the easiest to use online ordering out there. Customers make repeat orders with the click of a button. We make it easy for customers to view and order their favorite items, and if you qualify, we label you as a favorite for them.</div>
		</div>
		<div class="divider"></div>
	</div>
	
	<div class="info-block">
		<div class="info-block-icon"><img src="/assets/images/icon-check.png"></div>
		<div class="info-block-subwrapper">
			<div class="info-block-tag">We're streamlined.</div>
			<div class="info-block-info">Getting you up and running is as simple as collecting a few pieces of info. We can notify you of orders by fax, phone, text message, email, and/or online system. We pay you by check or bank deposit.</div>
		</div>
		<div class="divider"></div>
	</div>
	
	<div class="info-block">
		<div class="info-block-icon"><img src="/assets/images/icon-star.png"></div>
		<div class="info-block-subwrapper">
			<div class="info-block-tag">It's great for business.</div>
			<div class="info-block-info">Your popular items are promoted as user favorites. Case study: a week after our launch in New Haven, we were driving $9K in orders per month to early adopter restaurants.</div>
		</div>
		<div class="divider"></div>
	</div>
</div>
<div class="divider"></div>

<br /><br />
<div class="dotted"></div>


<p class="desc">
	Give us a call at <b>800-351-4161</b>
</p>
</center>