<div class="top-pad"></div>

<div class="content-padding">


	<h1 class="title left" ng-style="{true: {width: '100%'}, false: {}}[loading]"><i class="fa fa-bank"></i>Payments<div class="title-loader" ng-if="loading"><i class="fa fa-refresh fa-spin"></i></div></h1>
	
	<div class="box-filter right" ng-if="summary.payments">
		<button class="button green" ng-class="{ 'inactive' : $parent.filter }" ng-click="$parent.filter = false">All</button>
		<button class="button button-big green" ng-class="{ 'inactive' : $parent.filter != 'Reimbursement' }" ng-click="$parent.filter = 'Reimbursement'">Reimbursement</button>
		<button class="button button-big green" ng-class="{ 'inactive' : $parent.filter != 'Payment' }" ng-click="$parent.filter = 'Payment'">Payments</button>
	</div>
	
	<div class="divider"></div>

	<div class="box-content2 box-content-table" ng-if="summary.payments">
		<table class="tb-zebra">
			<tr>
				<th>Type</th>
				<th>Period</th>
				<th>Amount</th>
				<th>Status</th>
				<th>Transfer Initiated</th>
				<th>Est. In Account</th>
			</tr>
			<tr ng-repeat="payment in summary.payments" ng-show="!filter || filter == payment.type">
				<td>
					<a href="/drivers/payment/{{payment.id_payment_schedule}}">{{payment.type}}</a>
					<span ng-if="payment.total_cash_orders" class="note">
						<br>
						Already received in cash: ${{payment.total_received_cash | formatPrice}} + Cash Tips ({{payment.total_cash_orders}} orders)
					</span>
				</td>
				<td>{{payment.range_date}}</td>
				<td positive-or-negative-color="{{payment.amount}}">
					${{payment.amount | formatPrice}}
				</td>
				<td>
					<span ng-class="{
						'span-driver-summary-paid': payment.status == 'Paid',
						'span-driver-summary-pending': payment.status == 'Pending',
						'span-driver-summary-processing': payment.status == 'Processing'
					}">
					<span ng-switch="payment.status">
						<span ng-switch-when="Pending">Not Yet Paid</span>
						<span ng-switch-default>{{payment.status}}</span>
					</span>
				</td>
				<td>{{payment.send_date}}</td>
				<td>{{payment.paid_date}}</td>
			</tr>
		</table>
	</div>

	
	<div ng-if="!summary.payments && !loading" class="box-content2">
		<p>Not payments yet. Go deliver some food!</p>
	</div>

	<h1 class="title" ng-if="!loading"><i class="fa fa-users"></i>Customer Referrals</h1>
	<div class="box-content2 box-content-table" ng-if="summary.referral.invites">
		<table class="tb-zebra">
			<tr>
				<th>Name</th>
				<th>Date</th>
				<th>Amount</th>
			</tr>
			<tr ng-repeat="invite in summary.referral.invites">
				<td>{{invite.user.name}}</td>
				<td>{{invite.date}}</td>
				<td>${{summary.referral.amount_per_user | formatPrice}}</td>
			</tr>
			<tr>
				<td></td>
				<td><strong>Total</strong></td>
				<td>${{summary.referral.invites_total_payment | formatPrice}}</td>
			</tr>
		</table>
	</div>

	<div ng-if="!summary.referral.invites && !loading">
		<div ng-include="'assets/view/general-profile-referal.html'"></div>
	</div>

</div>


<? /*
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
		<div ng-if="summary.earnings">

			<br><br>

			<table class="tb-grid tb-zebra">
				<tbody>
					<tr ng-if="summary.earnings.current">
						<td>Payment Earned Since Monday</td>
						<td positive-or-negative-color="{{summary.earnings.current.total_payment}}">
							${{summary.earnings.current.total_payment | formatPrice}}
						</td>
					</tr>
					<tr ng-if="summary.earnings.current">
						<td>Reimbursement Earned Since Monday</td>
						<td positive-or-negative-color="{{summary.earnings.current.total_reimburse}}">
							${{summary.earnings.current.total_reimburse | formatPrice}}
						</td>
					</tr>
					<tr ng-if="summary.earnings.previous">
						<td>Last week's earnings</td>
						<td positive-or-negative-color="{{summary.earnings.previous.total_payment}}">
							${{summary.earnings.previous.total_payment | formatPrice}}
						</td>
					</tr>
					<tr ng-if="summary.earnings.previous">
						<td>Last week's reimbursement</td>
						<td positive-or-negative-color="{{summary.earnings.previous.total_reimburse}}">
							${{summary.earnings.previous.total_reimburse | formatPrice}}
						</td>
					</tr>
					<tr ng-if="summary.last_shift.date">
						<td>Earned for Most Recent Shift ({{summary.last_shift.date}})</td>
						<td positive-or-negative-color="{{summary.last_shift.total_payment}}">
							${{summary.last_shift.total_payment | formatPrice}}
						</td>
					</tr>
					<tr ng-if="summary.last_shift.date">
						<td>Reimbursement for Most Recent Shift ({{summary.last_shift.date}})</td>
						<td positive-or-negative-color="{{summary.last_shift.total_reimburse}}">
							${{summary.last_shift.total_reimburse | formatPrice}}
						</td>
					</tr>
				</tbody>
			</table>
			<p class="note">
				<strong>Earnings</strong> are the money you made: delivery fees and non-cash tips (and you'll make more from cash tips).
				<br />
				<strong>Reimbursement</strong> is us paying you back for the money you spent in the restaurants that require drivers to pay in the restaurant.
			</p>
			<br />
			<br />
		</div>
	</div>
!-->

	<div ng-if="summary.weeks" class="driver-summary">
<!--
		<h2 class="title">View Details</h2>

		<table class="tb-grid tb-zebra-summary">
			<thead>
				<tr>
					<td style="max-width: 15px"></td>
					<td>Period</td>
					<td>Payment</td>
					<td>Reimbursement</td>
					<tr>
			</thead>
			<tbody ng-repeat="week in summary.weeks">
				<tr>
					<td>
						<div class="link expand-collapse" ng-click="week.show_week = !week.show_week">
							<i class="orange fa fa-plus-square-o" ng-show="!week.show_week"></i>
							<i class="fa fa-minus-square-o" ng-show="week.show_week"></i>
						</div>
					</td>
					<td>{{week.period}}</td>
					<td positive-or-negative-color="{{week.total_payment}}">
						${{week.total_payment | formatPrice}}
					</td>
					<td positive-or-negative-color="{{week.total_payment}}">
						${{week.total_reimburse | formatPrice}}
					</td>
				</tr>
				<tr ng-show="week.show_week">
					<td colspan="4">
						<table class="tb-grid tb-zebra-summary">
							<thead>
								<td style="max-width: 15px"></td>
								<td>Day</td>
								<td>Payment</td>
								<td>Reimbursement</td>
							</thead>
							<tbody ng-repeat="day in week.days">
								<tr>
									<td>
										<div class="link expand-collapse" ng-click="day.show_day = !day.show_day">
											<i class="orange fa fa-plus-square-o" ng-show="!day.show_day"></i>
											<i class="fa fa-minus-square-o" ng-show="day.show_day"></i>
										</div>
									</td>
									<td>{{day.day}}</td>
									<td positive-or-negative-color="{{day.total_payment}}">
										${{day.total_payment | formatPrice}}
									</td>
									<td positive-or-negative-color="{{day.total_reimburse}}">
										${{day.total_reimburse | formatPrice}}
									</td>
								</tr>
								<tr ng-show="day.show_day">
									<td colspan="4">
										<table class="tb-grid tb-zebra tb-zebra-summary" ng-if="day.shifts">
											<thead>
												<tr>
													<td>Shift Started At</td>
													<td>Shift Ended At</td>
													<td>Hours</td>
													<td>Pay</td>
													<td></td>
												</tr>
											</thead>
											<tbody ng-repeat="shift in day.shifts">
												<tr>
													<td>
														{{shift.date_start}}
													</td>
													<td>
														{{shift.date_end}}
													</td>
													<td>
														{{shift.hours}}
													</td>
													<td positive-or-negative-color="{{shift.total_payment}}">
														${{shift.total_payment | formatPrice}}
													</td>
													<td>
														<span ng-class="{ 'span-driver-summary-paid': shift.payment.status == 'Paid',
																							'span-driver-summary-pending': shift.payment.status == 'Pending',
																							'span-driver-summary-processing': shift.payment.status == 'Processing' }">
															{{shift.payment.status}}
														</span>
													</td>
												</tr>
											</tbody>
										</table>
										<table class="tb-grid tb-zebra tb-zebra-summary" ng-if="day.orders">
											<thead>
												<tr>
													<td class="hide-tiny-screen">Order</td>
													<td>
														<span class="hide-tiny-screen">Customer</span>
														<span class="show-tiny-screen">Order #/<br>Customer</span>
													</td>
													<td>Tip</td>
													<td>Delivery Fee</td>
													<td>Minus Crunchbutton Fees You Collected in Cash</td>
													<td>Pay</td>
													<td class="hide-tiny-screen">&nbsp;</td>
													<td>Reimbursement</td>
													<td class="hide-tiny-screen">&nbsp;</td>
												</tr>
											</thead>
											<tbody ng-repeat="order in day.orders">
												<tr>
													<td class="hide-tiny-screen">{{order.id_order}}</td>
													<td>
														<span class="hide-tiny-screen">{{order.name}}</span>
														<span class="show-tiny-screen">#{{order.id_order}}<br>{{order.name}}</span>
													</td>
													<td positive-or-negative-color="{{order.tip}}">
														<span ng-if="order.tip == 0">
															paid in cash
														</span>
														<span ng-if="order.tip > 0">
															${{order.tip | formatPrice}}
														</span>
													</td>
													<td positive-or-negative-color="{{order.delivery_fee}}">
														${{order.delivery_fee | formatPrice}}
													</td>
													<td positive-or-negative-color="{{order.markup}}">
														${{order.markup | formatPrice}}
													</td>
													<td positive-or-negative-color="{{order.total_payment}}">
														${{order.total_payment | formatPrice}}
														<span class="show-tiny-screen" ng-class="{ 'span-driver-summary-paid': order.payment.status == 'Paid',
																							'span-driver-summary-pending': order.payment.status == 'Pending',
																							'span-driver-summary-processing': order.payment.status == 'Processing' }">
															{{order.payment.status}}
														</span>
													</td>
													<td class="hide-tiny-screen">
														<span ng-class="{ 'span-driver-summary-paid': order.payment.status == 'Paid',
																							'span-driver-summary-pending': order.payment.status == 'Pending',
																							'span-driver-summary-processing': order.payment.status == 'Processing' }">
															{{order.payment.status}}
														</span>
													</td>
													<td positive-or-negative-color="{{order.total_reimburse}}">
														${{order.total_reimburse | formatPrice}}
														<span class="show-tiny-screen" ng-class="{ 'span-driver-summary-paid': order.reimburse.status == 'Paid',
																							'span-driver-summary-pending': order.reimburse.status == 'Pending',
																							'span-driver-summary-processing': order.reimburse.status == 'Processing' }">
															{{order.reimburse.status}}
														</span>
													</td>
													<td class="hide-tiny-screen">
														<span ng-class="{ 'span-driver-summary-paid': order.reimburse.status == 'Paid',
																							'span-driver-summary-pending': order.reimburse.status == 'Pending',
																							'span-driver-summary-processing': order.reimburse.status == 'Processing' }">
															{{order.reimburse.status}}
														</span>
													</td>
												</tr>
											</tbody>
										</table>
									</td>
								</tr>
							</tbody>
						</table>
					</td>
				</tr>
			</tbody>
		</table>
*/ ?>
