<div class="top-pad"></div>

<div class="content-padding">

<h1 class="title left"><i class="fa fa-support"></i><span>Help</span></h1>

	<div class="divider"></div>

	<p>
		<b>Have questions during a delivery?</b><br>
		TXT us at <a href="sms:646-783-1444" target="_system">646-783-1444</a>
		<br><br>
		<b>When do I fill out my schedule for the next week?</b><br>
		Make sure to fill out your schedule by Monday at 8PM EDT at the latest.
		<br><br>
		<b>Can I earn cash back for money spent during my shifts at restaurants?</b><br>
		Why Yes! If you are interested in getting extra cash back during your shifts, here are links to apply for the cards we'd recommend: they're specifically for college students and many have extra cash back for food purchases.
			<br/>
			<a href="/drivers/help/credit-card" class="link orange">Credit Cards for Crunchbutton Student Deliverers</a>
		<br><br>
		<b>Payment:</b><br>
		At the end of each week, you will be reimbursed for your credit/debit card spendings plus what you earned. You get to keep all cash received from cash orders. If there are discrepancies between what you paid for the order versus what the customer was charged (not including taxes, delivery fee, etc), email team@crunchbutton.com so we can fix prices online.
		<br><br>
		<b>Insurance:</b><br>
		Youbeo, Inc has an insurance policy that will protect Youbeo and its drivers from liability claims arising from a motor vehicle collision during the course of business. The protection is up to $1,000,000 liability insurance policy that protects you against claims to third parties for injuries and property damage. This protection does not cover physical damage to any vehicle being used by a driver associated with Youbeo. Physical damage to any employee or subcontract’s vehicle must be done through the individual's primary insurance company.
	</p>

	<br><br>
	<p>
		<a target="_system" href="https://s3.amazonaws.com/uploads.hipchat.com/41812/283752/nmB3Y2yH2HkjWLM/DeliveryDriverGuidelines.pdf">Download the Delivery Driver Guidelines</a>
	</p>

</div>