<div class="top-pad"></div>

<div class="content-padding" ng-show="ready">

	<h1 class="title left"><i class="fa fa-thumbs-up"></i><span>Shift Preferences</span></h1>

	<div class="divider"></div>

	<h1 class="title">{{period}}</h1>

	<div class="divider"></div>

	<div class="drivers-shifts-list">

		<div ng-if="shifts.length">

			<div class="drivers-shift drivers-schedule">

		<div class="dialog-message dialog-message-error">
			<b><i class="fa fa-hand-o-right"></i> Don't forget: You must save your changes below!</b>
		</div>


			<div>
				<ul class="ul-inputs box-content2">
					<li class="li-input">
						<div class="label">How many shifts would you like to work?</div>
						<select name="shiftsAvailableToWork" ng-model="shiftsAvailableToWork" ng-change="updateShiftsAvailable(this.shiftsAvailableToWork)" ng-options="shift as shift for shift in availableToWork"></select>
					</li>
				</ul>
			</div>

			<div ng-if="available > 0" class="shifts-available">

				<h2 class="title">All shifts</h2>

				<div class="box-content2">
					<table class="tb-grid">
						<tr ng-repeat="shift in shifts" ng-if="!shift.ranking && shift.ranking != 0">
							<td>
								<div class="schedule-day">{{shift.day}} - {{shift.community}}</div>
								<div class="schedule-period">
									{{shift.period}} <span class="schedule-tz">{{shift.tz}}</span>
								</div>
							</td>
							<td class="td-large schedule-buttons">
								<button class="button schedule-action-yes" ng-if="!shift.assigned" ng-click="wantToWork( shift.id_community_shift )">
									<i class="fa fa-thumbs-o-up"></i>
								</button>
								<button class="button schedule-action-not" ng-if="!shift.assigned" ng-click="dontWantToWork( shift.id_community_shift )">
									<i class="fa fa-thumbs-o-down"></i>
								</button>
							</td>
						</tr>
					</table>

				</div>

			</div>

			<div ng-if="yes > 0" class="shifts-yes">

				<h2 class="title">Shifts you could work</h2>
				<h3 class="title">Ranked from most to least preferred</h3>

				<div class="box-content2">

					<table class="tb-grid">
						<tbody ng-repeat="shift in shifts" ng-if="shift.ranking > 0" >
							<tr>
								<td>
									<div class="schedule-day">{{shift.day}} - {{shift.community}}</div>
									<div class="schedule-period">
										{{shift.period}} <span class="schedule-tz">{{shift.tz}}</span>
									</div>
								</td>
								<td class="td-larger schedule-buttons">
									<button class="button schedule-action-down" ng-if="shift.ranking_next" ng-click="rankingChange( shift.id_community_shift,  shift.ranking_next )">
										<i class="fa fa-sort-desc"></i>
									</button>
									<button class="button schedule-action-up" ng-if="shift.ranking_prev" ng-click="rankingChange( shift.id_community_shift, shift.ranking_prev )">
										<i class="fa fa-sort-asc"></i>
									</button>
									<button class="button schedule-action-not" ng-if="!shift.assigned" ng-click="dontWantToWork( shift.id_community_shift )">
										<i class="fa fa-thumbs-o-down"></i>
									</button>
									<button class="button schedule-action-lock" ng-if="shift.assigned">
										<i class="fa fa-lock"></i>
									</button>
								</td>
							</tr>
						</tbody>
					</table>
					<div class="divider"></div>
				</div>

			</div>


			<div ng-if="not > 0" class="shifts-not">

				<h2 class="title">Shifts you CANNOT work</h2>

				<div class="box-content2">

					<table class="tb-grid">
						<tr ng-repeat="shift in shifts" ng-if="shift.ranking == 0">
							<td>
								<div class="schedule-day">{{shift.day}} - {{shift.community}}</div>
								<div class="schedule-period">
									{{shift.period}} <span class="schedule-tz">{{shift.tz}}</span>
								</div>
							</td>
							<td class="td-large schedule-buttons">
								<button class="button schedule-action-yes" ng-click="wantToWork( shift.id_community_shift )">
									<i class="fa fa-thumbs-o-up"></i>
								</button>
							</td>
						</tr>
					</table>
					<div class="divider"></div>
				</div>
			</div>

			</div>


			<div class="box-content2">
				<table>
					<tbody>
						<tr>
							<td>
								<ul class="ul-inputs">
									<li class="li-input" ng-show="!isSaving">
										<button class="button save" ng-click="save();">Save</button>
									</li>
									<li class="li-input" ng-show="isSaving">
										<i class="fa fa-circle-o-notch fa-spin"></i>
									</li>
								</ul>
							</td>
						</tr>
					</tbody>
				</table>
			</div>

		</div>

		<div ng-if="!shifts.length" class="box-content2">
			You currently have no shifts to this period.
		</div>

	</div>

</div>

<spinner-loading></spinner-loading>
<hack-expand-content></hack-expand-content>