<div class="top-pad"></div>

<div class="content-padding" ng-show="ready">

	<div class="dialog-message dialog-message-error">
		<b>In order to get paid</b></br> <div class="dialog-subtext">you MUST mark your orders as accepted & delivered!</div>		
	</div>
	
	<? /* @todo: make this a diff date. write date diff in js */ ?>
	
	<?/*		*/ ?>
	<div class="box-filter">
		<h1 class="title left"><i class ="fa fa-truck"></i><span>Orders &nbsp&nbsp</span></h1>
		<button class="button orange" ng-class="{ 'inactive' : !show.all }" ng-click="show.all = true">All</button>
		<button class="button orange" ng-class="{ 'inactive' : show.all }" ng-click="show.all = false">Mine</button>
		<div class="divider"></div>
	</div>

	<div class="drivers-order-list">

		<div ng-if="driverorders.length">

			<div class="box-content item order-item-wrap" ng-repeat="order in driverorders | filter:filterOrders" ng-class="order.lastStatus.status">
				<div ng-class="{'notMyOrder': order.lastStatus.id_admin !== account.user.id_admin, 'myOrder': order.lastStatus.id_admin == account.user.id_admin}">
					<h6 class="row-status" ng-if="order.lastStatus.id_admin !== account.user.id_admin && order.lastStatus.status !== 'new'">
						<span ng-switch="order.lastStatus.status">
							<span ng-switch-when="delivered">Delivered</span>
							<span ng-switch-when="pickedup">Picked up</span>
							<span ng-switch-when="accepted">Accepted</span>
							<span> by <b>{{order.lastStatus.name}}</b> @ {{order.lastStatus.date | date:'shortTime'}}</span>
						</span>
					</h6>
					
					<div class="order-item-content">
						<!-- action -->
						<div class="column-action">
							<button class="button orange-on-orange button-pushable" ng-click="accept(order.id_order)" ng-if="order.lastStatus.status == 'new' || !order.lastStatus.status" > Accept </button>
							<button class="button green-on-green button-pushable" ng-click="pickedup(order.id_order)" ng-if="order.lastStatus.id_admin == account.user.id_admin && order.lastStatus.status == 'accepted'"> Picked up </button>
							<button class="button dgray-on-dgray button-pushable" ng-click="delivered(order.id_order)" ng-if="order.lastStatus.id_admin == account.user.id_admin && order.lastStatus.status == 'pickedup' "> Delivered </button>
							<button class="button lgray-on-lgray button-pushable" ng-click="showOrder(order.id_order)" ng-if="order.lastStatus.id_admin == account.user.id_admin && order.lastStatus.status == 'delivered' "> View </button>
						</div>
	
						<!-- date -->
						<div class="column-date" ng-click="showOrder( order.id_order )">
							<?//<h3 class="day">{{order._date | date:'MM/dd'}}</h3> ?>
							<div class="orderid">#{{order.id_order}}</div>
							<div class="hour">{{order.date_hour | date:'h:mm a'}}</div>
						</div>
						
						<!-- vertical divider -->
						<div class="vert-divider"></div>
	
						<!-- info -->
						<div class="column-info">
							<div class="restaurant-pointer" ng-click="showOrder( order.id_order )">
								{{order.restaurant}}
							</div>
	
							<div class="customer-pointer">
								{{order.name}}
							</div>
							<div class="phone-pointer">
								<a href="tel:{{order.phone}}">{{order.phone | formatPhone}}</a>
							</div>
						</div>
						<div class="divider"></div>
					</div>
				</div>
			</div>
		</div>

		<div ng-if="!driverorders.length">
			<h3>You currently have no orders to deliver.</h3>
		</div>
		
		<div class="last-updated">Last Updated: <span class="last-updated-time">{{newDriverOrders.time.getTime() | date: 'hh:mm a'}}</span></div>

	</div>

</div>

<hack-expand-content></hack-expand-content>
