
<div class="drivers-welcome">
	<div class="top-pad"></div>
	<div class="content-padding">
		<h1 class="welcome-title">Enable location services</h1>
		
		<div class="welcome-icon"><i class="fa fa-location-arrow"></i></div>
		<p>
			In order to better serve customers, please enable your location services for me.
			<br><br>
			Location services are only enabled while you are on shift. This will help save your battery so we can hang out much longer.
			<br><br>
			Go ahead and click the enable button at the bottom so we can continue.
		</p>
		<div class="welcome-button"><a href ng-click="locateit()"><button class="ladda-button button orange" data-color="orange" data-style="zoom-in"><span class="ladda-label">Enable</span></button></a></div>
	</div>
</div>