<div class="drivers-welcome">
	<div class="top-pad"></div>
	<div class="content-padding">
		<h1 class="welcome-title">Fullfilling orders</h1>
		
		<div class="welcome-icon"><i class="fa fa-truck"></i></div>
		<p>Your task is to deliver the orders and my job is to make your task a lot easier. Let's work together!</p>
		<div class="welcome-button"><a href="/drivers/welcome/location"><button class="ladda-button button orange" data-color="orange" data-style="zoom-in"><span class="ladda-label">Next</span></button></a></div>
	</div>
</div>