
<div class="drivers-welcome">
	<div class="top-pad"></div>
	<div class="content-padding">
		<h1 class="welcome-title">Enable location services</h1>
		
		<div class="welcome-icon"><i class="fa fa-location-arrow"></i></div>
		<p>
			In order to better serve customers, please enable your location services for me.
			<br><br>
			Location services are only enabled while you are on shift. This will help save your battery so we can hang out much longer.
			<br><br>
			Go ahead and click the enable button at the bottom so we can continue.
		</p>
		<div class="welcome-button"><a href="/drivers/welcome/push"><button  class="button orange">Enable</button></a></div>

	</div>
</div>