<div class="top-pad"></div>

<div class="content-padding">

<h1 class="title left"><i class="fa fa-support"></i><span>FAQ</span></h1>

	<div class="divider"></div>
        <h2 style="font-size:2em; color: black; line-height: 1.5em">
            Table of Contents
    </h2>
        <a style="text-decoration:none; font-size:1.5em; line-height:1.2em; color:#317F7A" href="#deliveryBasics">
            Delivery Basics
        </a><br>
        <a style="text-decoration:none; font-size:1.5em; line-height:1.2em; color:#317F7A" href="#advancedDelivery">
            Advanced Delivery
        </a><br>
        <a style="text-decoration:none; font-size:1.5em; line-height:1.2em; color:#317F7A" href="#payment">
            Payment
        </a><br>
        <a style="text-decoration:none; font-size:1.5em; line-height:1.2em; color:#317F7A" href="#shifts">
            Shifts
        </a><br>
        <a style="text-decoration:none; font-size:1.5em; line-height:1.2em; color:#317F7A" href="#moreHelp">
            More Help
        </a>

    <br><br>
	<p>

		<b>Have questions during a delivery?</b><br>
		TXT us at <a ng-click="callText('646-783-1444')">646-783-1444</a>
		<br><br>
       <a name="deliveryBasics"></a>
        <b>How can we make your driving experience more awesome?</b><br>
		 <a href="https://docs.google.com/forms/d/1TsYU7LKyi8AQhM317n1v-SEiP-8OuiQIReV6XZHd-HM/viewform"  target="_system">Send us anonymous feedback!</a>

		<br><br>
<!--delivery basics section-->
        <span style="font-size:2em; color: black">
            Delivery Basics
        </span><br>

        <b>
			 Sooooo, how does this work?
		</b>
		<br>
		  Customers place orders for food on our website and app. When an order arrives during your shift, you'll get a text on your phone linking you to the order page right here on cockpit.la. You’ll see the details for each order - customer name, phone, and address; the restaurant name and address; and the order contents.You’ll pick up the food and deliver it. We aim for delivery times under 45 minutes. Simple enough, right?
		<br><br>

        <b>
			 How do I activate my PEX card?
		</b>
		<br>
		      Click <a href="/drivers/docs/pexcard">“Activate PEX Card”</a>. Follow the instructions. Please do this at least 2 hours before your first shift.
		<br><br>
       <b>
			How should I prepare for my shift?
		</b>
		<br>
		  Make sure your phone is fully charged, and you have enough gas. All of our restaurants are centrally located around the college campus you’re serving, so head to the restaurant district and wait for orders to come in.
		<br><br>

        <b>
			Will there be other drivers on shift with me?
		</b>
		<br>
		      That depends on order volume in your community. We try to make sure drivers have enough orders to stay busy and make money, without being overwhelmed with too many. You can find out who’s scheduled by clicking “Shifts” to the right. It’s great to be in touch with other drivers on shift to divvy up orders and make sure everyone is happy.
		<br><br>
        <b>
			Ok, how do I make sure I’m not picking up another driver’s order?
		</b>
		<br>
		Mark your orders as Accepted as soon as you get them, which ensures another driver won’t pick it up. Then mark them as Picked Up and Delivered as you go. This lets the customer follow your progress online. We also track delivery times--you want to go as fast as possible to delight the customer!
		<br><br>
        <b>
        Where do I park at the restaurant?
        </b>
        <br>
As you get more experience, you'll learn the best parking spots for each restaurant. Restaurants will also often have a reserved space out front or around the corner. If a restaurant has a tricky parking situation, make a note about it in cockpit.la to alert other drivers for next time.<br><br>
        <b>
        What do I do at the restaurant?
        </b>
        <br>
Some restaurants have formal arrangements with Crunchbutton, so the food will be paid for and prepared and you just pick it up. At other restaurants you buy the food yourself, as if you were a customer. The order page on cockpit.la will tell you which is the case for each restaurant. Double-check the order contents so you don't have to go back for missing items. If you need to buy the food yourself, use the Crunchbutton PexCard, except when the order says that the customer is paying cash - in that case, you should use your own money.<br><br>

        <b>
        Wait, cash?
        </b>
        <br>
Yup, be sure to carry cash while on shift! A small amount of customers pay with cash, so try to have $20 in small bills with you. You’ll keep the cash the customer pays with, so it’s like getting paid your commission right away.<br><br>

        <b>
        I’ve run out of money for a cash order! What do I do?!
        </b>
        <br>
If you run out of funds, you can either 1) ask another driver on shift to take that order or 2) use the PEX card. If you need to use the PEX card, make sure to email <a href="mailto:payment@crunchbutton.com">payment@crunchbutton.com</a> the order number and the amount you paid so we can adjust payments accordingly.<br><br>

        <b>
            What should I tell the restaurant?
        </b>
        <br>
In many cases we don't have a formal relationship with the restaurant, and it's best not to cause confusion. So order the food yourself, and don't mention that it's for delivery. If the order was sent directly to the restaurant, then say you're there to pick up the takeout order under the customer's name. If they point out that there's no name on the card, tell them it's a "company card" and everything will be fine.<br><br>

        <b>
        What if the order price is wrong?
        </b>
        <br>
We'll tell you how much the food should cost. If it costs more, email <a href="mailto:team@crunchbutton.com">team@crunchbutton.com</a> a photo of your receipt right away so we can change the prices and reimburse you correctly.<br><br>

        <b>
        What if the customer doesn’t show up?
        </b>
        <br>
Hang onto the food, text the customer and leave a friendly voicemail. Then go on to your next order, and hopefully the customer will respond soon! Meanwhile, let us know too, by text.<br><br>

        <b>
        Can I pick up multiple orders at once?
        </b>
        <br>

Absolutely. You don't have to deliver an order before picking up the next one. We aim for delivery times under 45 minutes, so do whatever is most efficient! Make sure to mark everything as Accepted, Picked Up, and Delivered as you go.<br><br>
        <a name="advancedDelivery"></a>
        <b>
			Do I get all my tips?
		</b>

		<br>
		Yes, every cent!
		<br><br>
<!--end #deliveryBasics-->
<!--start #advancedDelivery section-->
        <span style="font-size:2em; color: black">
            Advanced Delivery
        </span><br>

        <b>
			How can I get tipped more on cash orders?
		</b>
		<br>
            Easy! When a customer asks you how much the order is, say “[the order total], <i>not including tip</i>.”<br>
Customer: O hello kind driver. Hurray my food, how much is it??<br>
You: $25.67, <i>not including tip</i>.<br>
Customer: Ok, here, have a million dollars, keep the change.<br>
You: K thx bye.<br><br>

		<b>
			How do I pick up food faster at the restaurant?
		</b>
		<br>
		For restaurants where we don’t send the order directly to the restaurant, you’re told to “place the order yourself.”  Do this faster by placing the order on the restaurant’s app! These chains have apps in most locations—Chipotle, Taco Bell, Panda Express, Chik Fil A, Subway
		<br><br>

        <b>How do I deliver more orders faster and make more money?</b><br>
Pick up multiple orders at once, then deliver them all at once. This allows you to deliver more orders in the same period of time and make more money.<br><br>

Why this works: Restaurants are usually close together. And customers are usually close together. So first visit a bunch of restaurants, then deliver to a bunch of customers.
We aim for delivery times under 45 minutes, so do whatever is most efficient!<br><br>

        <b>
            How do I use my invite code and how do I earn extra $$$ with it?
        </b><br>
Your Personal Invite Code: <strong>{{account.user.invite_code}}</strong>. Get new customers to enter fhkjadsfds in the Notes section of their first order for <strong>${{account.user.referral_customer_credit}}</strong> off and you’ll earn <strong>${{account.user.referral_admin_credit}}</strong> for each person you refer, directly into your bank account!
<br>

        <b>
            3 great ways to use your invite code:
        </b><br>

1. Talk to everyone you can when waiting to pick up or deliver food. Tell EVERYONE waiting in line at Chipotle to get their food delivered, tell people going into dorms about Crunchbutton. <br>
<a name="payment"></a>
2. Post your code on Facebook/Twitter<br>
3. Hand out cards with your code on them to everyone you can<br><br>

<!--end #advancedDelivery section-->

 <!--start #payments section-->
        <span style="font-size:2em; color: black">
            Payment
        </span><br>

       <b>
		  How do I get paid?
        </b><br>
We pay by direct deposit. Click <a href="/drivers/docs">Documents</a> and make sure your forms are all uploaded to get paid properly.<br><br>

        <b>
        When do I get my $$$?
        </b><br>
We deposit your payment every Friday. You get to keep all cash received from cash orders as an advance towards that too.<br><br>
        <a name="shifts"></a>
        <b>
        I have a question about my payment.
        </b><br>
        Email <a href="mailto:payment@crunchbutton.com">payment@crunchbutton.com</a> with as many details as possible and we’ll figure it out!<br><br>

<!--end #payments section-->

<!--start #shifts section-->
         <span style="font-size:2em; color: black">
            Shifts
        </span><br>

        <b>
        What are Flex vs Perma-Shifts?
        </b><br>
You'll work either the same days every week (perma-shifts) or different days each week (flex shifts). In either case, you can view your shifts any time on cockpit. Email us at <a href="mailto:team@crunchbutton.com">team@crunchbutton.com</a> to set up perma-shifts.<br><br>

        <b>
        How do Flex Shifts work?
        </b><br>
Your shift preferences are due by Monday at 5pm. Click “Shift Preferences” to the right to submit them. You’ll be texted on Wed at 10 AM Pacific with the results, and you’ll be see them in cockpit.la/drivers/shifts too!<br><br>

        <b>
        I want to work more shifts. What do I do?
        </b><br>
Text us at <a ng-click="callText('646-783-1444')">646-783-1444</a>. You can also text other drivers and offer to drive for them—you can find the other drivers in your community and their numbers on the Shifts page.<br><br>

        <b>
        I can’t drive one of my upcoming shifts. What should I do?
        </b><br>
First, contact other drivers from cockpit.la/drivers/shifts to ask if someone can trade with you. Then text us to know about the trade.<br><br>

If you absolutely can’t find anyone yourself, it's important you give us 2 days notice if you can't make a shift you're scheduled for. We put a lot of faith in drivers to show up for their shifts. Otherwise we might have to shut down the community, which leads to sad customers and other drivers potentially not being able to work!<br><br>
<!--end #shifts section-->

<!--start #moreHelp section-->
  <span style="font-size:2em; color: black">
       <a name="moreHelp"></a>
            More Help
        </span><br>
<b>I’m having difficulty using cockpit.la.</b><br>
Try a different browser. On iOS devices, use Safari. On Android, use Chrome (not Firefox). If you’re still having issues, please text us at <a ng-click="callText('646-783-1444')">646-783-1444</a> or email the specifics and a screenshot of the issue to <a href="mailto:team@crunchbutton.com">team@crunchbutton.com</a>.
<br><br>

<b>I found a bug with Crunchbutton or Cockpit. What should I do?</b><br>
We hate bugs! Email us at <a href="mailto:team@crunchbutton.com">team@crunchbutton.com</a> with the exact details and pics if you can. If you tell us enough info to reproduce and fully fix the problem, we’d really appreciate it!<br><br>

<b>Can I change my cockpit password?</b><br>
Sure, but right now we have to do it for you manually. Text us what you want us to change your password to at <a ng-click="callText('646-783-1444')">646-783-1444</a> .<br><br>

<b>How does your insurance work?</b><br>
Youbeo, Inc (Crunchbutton's parent company) has an insurance policy that will protect from liability claims arising from a motor vehicle collision during the course of business. The protection is up to $1,000,000 liability insurance policy that protects you against claims to third parties for injuries and property damage. This protection does not cover physical damage to any vehicle being used by a driver associated with Youbeo. Physical damage to any employee or subcontractor’s vehicle must be done through the individual's primary insurance company.<br><br>

<b>There’s something else I don’t understand!</b><br>
Hey, we’re here to help. Text us at <a ng-click="callText('646-783-1444')">646-783-1444</a>  and we’ll figure it out!<br><br>
<!--end #moreHelp section-->

    </p>
</div>