<div class="top-pad"></div>
<div class="content-padding">
<div class="drivercontain">
    <h1 ng-if="!finished" class="title left"><i ng-if="!finished" class="fa fa-quote-left"></i><span ng-if="!finished">Feedback</span></h1>
    <div class="divider"></div>
<h1 class="title left" ng-if="finished">Thank you, your feedback has been submitted!</h1>
   <h2 ng-if="!finished">Help Us Help You</h2>
   <br>
    <form ng-if="!finished">
    <div class="driver-feedback">
 <div class="form-group">
            <label class="driverlabel">
                <span>*</span>How can we make Crunchbutton a more awesome experience? Tell us anything you can!
            </label>
            <br>
            
            <div class="drivertextbox">
            <div ng-if="errors.message">Please tell us how to improve!</div>
                <textarea ng-model="feedback.message" name="message" class="driverform-control"></textarea>
            </div>
        </div>

        <div class="form-group">
            <label class="driverlabel">
                Driving Community: (optional)
            </label>
            <div class="drivertextbox">
                <input type="text" ng-model="feedback.community" name="community" class="driverform-control" >
            </div>
        </div>
        
         <div class="form-group">
            <label class="driverlabel">
                Name: (optional)
            </label>
            <div class="drivertextbox">
                <input type="text" class="driverform-control" ng-model="feedback.name" name="name" >
            </div>
        </div>
        
    <button ng-click="post()" type="submit" class="button orange" name="submit">Submit</button>
    </div><!--close driver-feedback div-->
  </form>


 

</div>
</div>