<div class="top-pad"></div>

<div class="content-padding">

<h1 class="title left"><i class="fa fa-support"></i><span>Help</span></h1>

	<div class="divider"></div>

	<h2 class="title">
		<span>Credit Cards for Crunchbutton Student Deliverers</span>
	</h2>


	<p>
		<strong>Citi Forward Card for College Students</strong>: <a href="https://www.citicards.com/cards/acq/Apply.do?app=COLLEGE&m=10G2111111W&cmp=KNC~01~110901~CRDACQXX~Google&s_kwcid=AL!2561!3!25804763530!e!!g!!college%20credit%20card&ef_id=UjNAewAABM6TOTeD:20140304194247:s&ProspectID=1E74E77A3163470D8CFB131C199050FA&sc=4CECNDA3&langId=EN&siteId=CB&B=V&screenID=3220&uc=CEB&t=t%20" target="_blank">Apply here</a>
		<br><br>
		<strong>Capital One Journey Student Rewards Card</strong>: <a href="https://application.capitalone.com/icoreapp/jsp/application.faces?s=0012874009000XXCO31XX1ZZZZZZZZXXZSEM01ZZZZZZZZZZZZZZ&IARC=SEM&external_id=WWW_SB723_ZZZ_ONL-SE_ZZZGO_ZZ_ZZ_T_SEM2_ZZSD_Z09_541013619_23657864472" target="_blank">Apply here</a> | <a href="https://www.capitalone.com/credit-cards/journey-student/?Log=1&EventType=Link&ComponentType=T&LOB=MTS%3A%3ALCTMMQC4S&PageName=29&TargetLob=MTS%3A%3ALCTMMQC4S&TargetPageName=Student+Rewards+Card+Details&referer=https%3A%2F%2Fwww.capitalone.com%2Fcredit-cards%2Fgateway&external_id=WWW_SB723_ZZZ_ONL-SE_ZZZGO_ZZ_ZZ_T_SEM2_ZZSD_Z09_541013619_23657864472" target="_blank">More Information</a>
		<br><br>
		<strong>Discover Student Card</strong>: <a href="https://www.discovercard.com/application/student?execution=e1s1" target="_blank">Apply here</a> | <a href="https://www.discover.com/credit-cards/student/" target="_blank">More Information</a>
		<br><br>
		<strong>Wells Fargo Cashback College Card</strong> (need existing Wells Fargo account): <a href="https://www.wellsfargo.com/credit-cards/cash-back-college-card/" target="_blank">Apply here</a>
	</p>
</div>