<div class="top-pad"></div>

<div class="content-padding" ng-show="ready">

	<div class="dialog-message dialog-message-error">
		<b>In order to get paid</b></br> <div class="dialog-subtext">you MUST mark your orders as accepted & delivered!</div>		
	</div>
	
	<? /* @todo: make this a diff date. write date diff in js */ ?>
	
	<?/*		*/ ?>
	<div class="box-filter">
		<h1 class="title left"><i class ="fa fa-truck"></i><span>Orders &nbsp&nbsp</span></h1>
		<button class="button orange" ng-class="{ 'inactive' : !show.all }" ng-click="show.all = true">All</button>
		<button class="button orange" ng-class="{ 'inactive' : show.all }" ng-click="show.all = false">Mine</button>
		<div class="divider"></div>
	</div>

	<div class="drivers-order-list">

		<div ng-if="driverorders.length">

			<div class="box-content item" ng-repeat="order in driverorders | filter:filterOrders" ng-class="order.lastStatus.status">
				<div ng-class="{'notMyOrder': order.lastStatus.id_admin !== account.user.id_admin, 'myOrder': order.lastStatus.id_admin == account.user.id_admin}">
					<h6 class="row-status" ng-if="order.lastStatus.id_admin !== account.user.id_admin && order.lastStatus.status !== 'new'">
						<span ng-switch="order.lastStatus.status">
							<span ng-switch-when="delivered">Delivered</span>
							<span ng-switch-when="pickedup">Picked up</span>
							<span ng-switch-when="accepted">Accepted</span>
							<span> by <b>{{order.lastStatus.name}}</b> @ {{order.lastStatus.date | date:'shortTime'}}</span>
						</span>
					</h6>
					</br>
					
					<!-- action -->
					<div class="column-action">
						<button class="button orange button-pushable" ng-click="accept(order.id_order)" ng-if="order.lastStatus.status == 'new' || !order.lastStatus.status" > Accept </button>
						<button class="button green button-pushable" ng-click="pickedup(order.id_order)" ng-if="order.lastStatus.id_admin == account.user.id_admin && order.lastStatus.status == 'accepted'"> Picked up </button>
						<button class="button blue button-pushable" ng-click="delivered(order.id_order)" ng-if="order.lastStatus.id_admin == account.user.id_admin && order.lastStatus.status == 'pickedup' "> Delivered </button>
						<button class="button black button-pushable" ng-click="showOrder(order.id_order)" ng-if="order.lastStatus.id_admin == account.user.id_admin && order.lastStatus.status == 'delivered' "> View </button>
					</div>

					<!-- date -->
					<div class="column-date">
						<?//<h3 class="day">{{order._date | date:'MM/dd'}}</h3> ?>
						<h1 class="hour"><strong>#{{order.id_order}}</strong></h1></br>
						<h1 class="hour">{{order.date_hour | date:'h:mm a'}}</h1>
					</div>
					
					<!-- vertical divider -->
					<div class="vert-divider"></div>

					<!-- info -->
					<div class="column-info">
						<h2 class="restaurant-pointer" ng-click="showOrder( order.id_order )">
							<?//<i class="fa fa-cutlery"></i>?> <b>{{order.restaurant}}</b>
						</h2>
						</br>
						<h4 class="customer-pointer" ng-click="showOrder( order.id_order )">
							{{order.name}}</br></br><u>{{order.phone | formatPhone}}</u>
						</h4>
					</div>
					<div class="divider"></div>
					</br>
				</div>
			</div>
		</div>

		<div ng-if="!driverorders.length">
			<h3>You currently have no orders to deliver.</h3>
		</div>
		
		<div class="last-updated">Last Updated: <span class="last-updated-time">{{newDriverOrders.time.getTime() | date: 'hh:mm a'}}</span></div>

	</div>

</div>

<hack-expand-content></hack-expand-content>
