<div class="top-pad"></div>

<div class="content-padding" ng-show="ready">

	<h1 class="title left"><i class="fa fa-automobile"></i><span>Driver Onboarding Documents</span></h1>

	<div class="divider"></div>

	<navigation-back></navigation-back>

	<div class="box-filter right">
		<button class="button orange" ng-click="all()">All Drivers</button>
	</div>

	<div ng-if="count">
		<table class="tb-grid">
			<thead>
				<tr>
					<td class="td-medium">Name</td>
					<td class="td-medium">Login</td>
					<td>Document</td>
					<td>Community</td>
					<td>Date</td>
					<td>Download</td>
					<td></td>
				</tr>
			</thead>
			<tbody>
				<tr ng-repeat="doc in documents">
					<td class="link" ng-click="edit(doc.id_admin)">{{doc.name}}</td>
					<td>{{doc.login}}</td>
					<td>{{doc.doc}}</span></td>
					<td><span ng-repeat="community in doc.communities">{{community}}</span></td>
					<td>{{doc.update}}</td>
					<td><a ng-href="{{doc.url}}" target="_blank">Download</a></td>
					<td class="pointer" ng-click="approve(doc)">
						<span ng-if="doc.approved">
							<i class="fa fa-check-square-o"></i> {{doc.approved}}
						</span>
						<span ng-if="!doc.approved">
							<i class="fa fa-square-o"></i>
						</span>
					</td>
				</tr>
			</tbody>
		</table>

		<table class="tb-pagination" ng-if="pages > 1">
			<tbody>
				<tr>
					<td class="td-prev"><button class="button orange" ng-show="prev" ng-click="prevPage()">prev</button></td>
					<td class="td-info">Page {{page}} of {{pages}}</td>
					<td class="td-next"><button class="button orange" ng-show="next" ng-click="nextPage()">next</button></td>
				</tr>
			</tbody>
		</table>
	</div>

	<div ng-if="!count" class="box-content">
		No drivers.
	</div>

</div>

<spinner-loading></spinner-loading>
<hack-expand-content></hack-expand-content>