
<div class="drivers-welcome">
	<div class="top-pad"></div>
	<div class="content-padding">
		<h1 class="welcome-title">Enable location services</h1>
		
		<div class="welcome-icon"><i class="fa fa-location-arrow"></i></div>
		<p>
			In order to better serve customers, we need to enable your location services.
			<br><br>
			Continued use of GPS running can dramatically decrease battery life. To help you save battery, I will only enable location services while you are on shift.
			<br><br>
			Go ahead and click the enable button at the bottom to give me permission to do so.
		</p>
		<div class="welcome-button"><a href ng-click="locateit()"><button class="ladda-button button orange" data-color="orange" data-style="zoom-in"><span class="ladda-label">Enable</span></button></a></div>
	</div>
</div>