<div class="top-pad"></div>

<div class="content-padding" ng-show="ready">

	<h1 class="title left"><i class="fa fa-automobile"></i><span>Driver Onboarding</span></h1>

	<div class="divider"></div>

	<navigation-back></navigation-back>

	<h2 class="title">
		<span ng-if="!driver.id_admin">Add driver</span>
		<span ng-if="driver.id_admin">Edit driver</span>
	</h2>

	<form name="form" novalidate>

		<ul ng-class="{'submitted':submitted}" class="ul-inputs">

			<li class="li-input" ng-class="{'error':form.driverName.$invalid}">
				<div class="label">Name:</div>
				<div class="input"><input type="text" name="driverName" ng-model="driver.name" required placeholder="Name" ng-minlength="5" ng-maxlength="40" ></div>
				<div class="box-error">
					<small ng-show="form.driverName.$error.required">Required.</small>
					<small ng-show="form.driverName.$error.minlength">Name is too short. Name is required to be at least 5 characters.</small>
					<small ng-show="form.driverName.$error.maxlength">Name cannot be longer than 40 characters.</small>
				</div>
			</li>

			<li class="li-input" ng-class="{'error':form.driverName.$invalid}">
				<div class="label">Login:</div>
				<div class="input"><input type="text" name="driverLogin" ng-readonly="driver.id_admin" required is-unique="login" placeholder="Login" ng-model="driver.login"></div>
				<div class="box-error">
					<small ng-show="form.driverLogin.$error.required">Required.</small>
					<small ng-show="form.driverLogin.$error.isUnique">This login is already in use!</small>
				</div>
			</li>

			<li class="li-input" ng-class="{'error':form.driverPhone.$invalid}">
				<div class="label">Phone:</div>
				<div class="input"><input type="text" name="driverPhone" ng-model="driver.phone" required phone-validate placeholder="Phone" is-unique="phone"></div>
				<div class="box-error">
					<small ng-show="form.driverPhone.$error.required">Required.</small>
					<small ng-show="form.driverPhone.$error.phoneValidate">Enter a valid phone.</small>
					<small ng-show="form.driverPhone.$error.isUnique">This phone is already registred!</small>
				</div>
			</li>

			<li class="li-input" ng-class="{'error':form.driverVehicle.$invalid}">
				<div class="label">Vehicle:</div>
				<select name="driverVehicle" required ng-model="driver.vehicle" ng-options="opt as opt for opt in vehicles" ></select>
				<div class="box-error">
					<small ng-show="form.driverVehicle.$error.required">Required.</small>
				</div>
			</li>

			<li class="li-input" ng-class="{'error':form.driverIdCommunity.$invalid}">
				<div class="label">Community:</div>
				<select name="driverIdCommunity" required ng-model="driver.id_community" ng-options="opt.id_community as opt.name for opt in communities" class="cart-customize-select"></select>
				<div class="box-error">
					<small ng-show="form.driverIdCommunity.$error.required">Required.</small>
				</div>
			</li>

			<li class="li-input" ng-class="{'error':form.driverEmail.$invalid}">
				<div class="label">Email:</div>
				<div class="input"><input type="email" name="driverEmail" ng-model="driver.email" placeholder="Email"></div>
				<div class="box-error">
					<small ng-show="form.driverEmail.$invalid">Enter a valid email.</small>
				</div>
			</li>

		</ul>

		<div ng-if="driver.login">

			<h2 class="title">Access info</h2>

			<ul class="ul-inputs">

				<li class="li-input">
					<div class="label">Password:</div>
					<div class="input"><input type="text" name="driverPass" ng-model="driver.pass"></div>
					<small class="tip">Leave it blank if you don't wanna change it.</small>
				</li>

			</ul>

		</div>

	</form>

	<div ng-if="driver.id_admin">
		<h2 class="title">Documents</h2>
		<table class="tb-grid">
			<tbody>
				<tr ng-repeat="doc in documents">
					<td ng-click="edit(driver.id_admin)">
						{{doc.name}}
					</td>
					<td>
						<span ng-if="doc.status" class="link orange" ng-click="download( doc.status.id_driver_document_status )" title="Sent at {{doc.status.date_formated}}">Download</span>
						<span ng-if="!doc.status" ng-click="setDocument(doc.id_driver_document)" class="sp-label sp-label-warning link">
							Upload missing doc
						</span>
					</td>
					<td>
						<span ng-if="doc.status" class="link orange" ng-click="remove( doc.status.id_driver_document_status )">Delete</span>
					</td>
					<td>
						<div ng-if="doc.status" class="pointer" ng-click="approve(doc.status)">
							<span ng-if="doc.status.approved">
								<i class="fa fa-check-square-o"></i> {{doc.status.approved}}
							</span>
							<span ng-if="!doc.status.approved">
								<i class="fa fa-square-o"></i>
							</span>
						</div>
					</td>
				</tr>
			</tbody>
		</table>
	</div>

	<form name="docs" ng-if="driver.id_admin">

		<h3 class="title">Upload zone</h3>

		<ul class="ul-inputs box-content2">
			<li class="li-input">
				<div class="label">Select the file type:</div>
				<select name="driverDocument" ng-model="doc_uploaded" ng-change="setDocument( this.doc_uploaded )" ng-options="opt.id_driver_document as opt.name for opt in documents"></select>
			</li>
			<li ng-show="doc_uploaded">
				<input ng-file-select name="file" type="file" />
			</li>
			<li ng-show="uploader.progress"  class="li-input">
				<span class="sp-label sp-label-info">
					Progress {{uploader.progress}}%
				</span>
			</li>
			<li ng-show="doc_uploaded"  class="li-input">
				<button class="button" ng-click="uploader.uploadAll();">Upload</button>
			</li>
		</ul>

	</form>

	<ul class="ul-inputs">
		<li class="li-input" ng-show="!isSaving">
			<button class="button save" ng-click="save();">Save</button>
			<button class="button cancel" ng-click="cancel()">Cancel</button>
		</li>
		<li class="li-input" ng-show="isSaving">
			<i class="fa fa-circle-o-notch fa-spin"></i>
		</li>
	</ul>

</div>

<spinner-loading></spinner-loading>
<hack-expand-content></hack-expand-content>