<div class="top-pad"></div>

<div class="content-padding" ng-show="ready">

	<h1 class="title left"><i class="fa fa-automobile"></i><span>Driver Onboarding</span></h1>

	<div class="divider"></div>

	<div class="box-filter right">
		<input type="text" class="search" id="search" ng-model="search" placeholder="search" />
		<button class="button orange" ng-click="add()">New Driver</button>
		<button class="button green" ng-click="docs()">Documents</button>
	</div>
	
	<div class="divider"></div>

	<div class="divider"></div>

	<div ng-if="count">
		<table class="tb-grid">
			<thead>
				<tr>
					<td class="td-medium">Name</td>
					<td class="td-medium">Login</td>
					<td>Vehicle</td>
					<td>Community</td>
					<td></td>
				</tr>
			</thead>
			<tbody>
				<tr ng-repeat="driver in drivers">
					<td class="link" ng-click="edit(driver.id_admin)">
						{{driver.name}}
					</td>
					<td>
						<span ng-if="driver.login">{{driver.login}}</span>
					</td>
					<td>
						{{driver.vehicle}}
					</td>
					<td><span ng-repeat="community in driver.communities">{{community}}</span></td>
					<td>
						<span ng-if="driver.sent_all_docs" class="sp-label sp-label-success">
							Docs ok
						</span>
						<span ng-if="!driver.sent_all_docs" class="sp-label sp-label-warning">
							Docs missing
						</span>
					</td>
				</tr>
			</tbody>
		</table>

		<table class="tb-pagination" ng-if="pages > 1">
			<tbody>
				<tr>
					<td class="td-prev"><button class="button orange" ng-show="prev" ng-click="prevPage()">prev</button></td>
					<td class="td-info">Page {{page}} of {{pages}}</td>
					<td class="td-next"><button class="button orange" ng-show="next" ng-click="nextPage()">next</button></td>
				</tr>
			</tbody>
		</table>
	</div>

	<div ng-if="!count" class="box-content">
		No drivers.
	</div>

</div>

<spinner-loading></spinner-loading>
<hack-expand-content></hack-expand-content>