<div class="top-pad"></div>

<div class="content-padding">

    <div class="support-boxes">

        <div class="support-box-wrap box-content2" ng-if="account.user.invite_code">
            <div class="support-box-wrap-header">
                <h1><i class="fa fa-thumbs-up"></i>Referral</h1>
                <div class="divider"></div>
            </div>
            <div class="no-box-content-color">
                <br>
                <div ng-include="'assets/view/general-profile-referal.html'"></div>
            </div>
        </div>

    </div>
