<div class="top-pad"></div>

<div class="content-padding" ng-show="ready">

	<h1 class="title left"><i class="fa fa-calendar"></i><span>Summary</span></h1>

	<div class="divider"></div>

	<form name="form" ng-show="drivers">

		<ul class="ul-inputs box-content2">
			<li class="li-input">
				<div class="label">Select a driver:</div>
				<div class="input">
					<select name="driverSummary" ng-model="id_admin" ng-change="load_driver()" ng-options="opt.id_admin as opt.name for opt in drivers"></select>
				</div>
			</li>
		</ul>
	</form>

	<div ng-show="isLoading">
		<span><i class="fa fa-circle-o-notch fa-spin"></i> Loading</span>
	</div>

	<div ng-if="summary.payments">

		<h2 class="title" ng-show="summary.payments.length">Recent Payments</h2>

		<table class="tb-grid tb-zebra" ng-show="summary.payments.length">
			<thead>
				<tr>
					<td>Type</td>
					<td>Period</td>
					<td>Amount</td>
					<td>Status</td>
					<td>Transfer Initiated</td>
					<td>Estimated Date In Your Account</td>
				</tr>
			</thead>
			<tbody>
				<tr ng-repeat="payment in summary.payments">
					<td>
						<span class="link" ng-click="show_payment( payment.id_payment_schedule );">{{payment.type}}</span>
						<span ng-if="payment.total_cash_orders" class="note">
							<br>
							Already received in cash: ${{payment.total_received_cash | formatPrice}} + Cash Tips ({{payment.total_cash_orders}} orders)
						</span>
					</td>
					<td>{{payment.range_date}}</td>
					<td positive-or-negative-color="{{payment.amount}}">
						${{payment.amount | formatPrice}}
					</td>
					<td>
						<span ng-class="{ 'span-driver-summary-paid': payment.status == 'Paid',
															'span-driver-summary-pending': payment.status == 'Pending',
															'span-driver-summary-processing': payment.status == 'Processing' }">

							<span ng-switch="payment.status">
							<span ng-switch-when="Pending">Not Yet Paid</span>
							<span ng-switch-default>{{payment.status}}</span>
						</span>
					</td>
					<td>{{payment.send_date}}</td>
					<td>{{payment.paid_date}}</td>
				</tr>
			</tbody>
		</table>

		<p><span ng-click="payments()" class="link orange">All payments</span></p>
<!--
		<div ng-if="summary.earnings">

			<br><br>

			<table class="tb-grid tb-zebra">
				<tbody>
					<tr ng-if="summary.earnings.current">
						<td>Payment Earned Since Monday</td>
						<td positive-or-negative-color="{{summary.earnings.current.total_payment}}">
							${{summary.earnings.current.total_payment | formatPrice}}
						</td>
					</tr>
					<tr ng-if="summary.earnings.current">
						<td>Reimbursement Earned Since Monday</td>
						<td positive-or-negative-color="{{summary.earnings.current.total_reimburse}}">
							${{summary.earnings.current.total_reimburse | formatPrice}}
						</td>
					</tr>
					<tr ng-if="summary.earnings.previous">
						<td>Last week's earnings</td>
						<td positive-or-negative-color="{{summary.earnings.previous.total_payment}}">
							${{summary.earnings.previous.total_payment | formatPrice}}
						</td>
					</tr>
					<tr ng-if="summary.earnings.previous">
						<td>Last week's reimbursement</td>
						<td positive-or-negative-color="{{summary.earnings.previous.total_reimburse}}">
							${{summary.earnings.previous.total_reimburse | formatPrice}}
						</td>
					</tr>
					<tr ng-if="summary.last_shift.date">
						<td>Earned for Most Recent Shift ({{summary.last_shift.date}})</td>
						<td positive-or-negative-color="{{summary.last_shift.total_payment}}">
							${{summary.last_shift.total_payment | formatPrice}}
						</td>
					</tr>
					<tr ng-if="summary.last_shift.date">
						<td>Reimbursement for Most Recent Shift ({{summary.last_shift.date}})</td>
						<td positive-or-negative-color="{{summary.last_shift.total_reimburse}}">
							${{summary.last_shift.total_reimburse | formatPrice}}
						</td>
					</tr>
				</tbody>
			</table>
			<p class="note">
				<strong>Earnings</strong> are the money you made: delivery fees and non-cash tips (and you'll make more from cash tips).
				<br />
				<strong>Reimbursement</strong> is us paying you back for the money you spent in the restaurants that require drivers to pay in the restaurant.
			</p>
			<br />
			<br />
		</div>
	</div>
!-->

	<div ng-if="summary.weeks" class="driver-summary">
<!--
		<h2 class="title">View Details</h2>

		<table class="tb-grid tb-zebra-summary">
			<thead>
				<tr>
					<td style="max-width: 15px"></td>
					<td>Period</td>
					<td>Payment</td>
					<td>Reimbursement</td>
					<tr>
			</thead>
			<tbody ng-repeat="week in summary.weeks">
				<tr>
					<td>
						<div class="link expand-collapse" ng-click="week.show_week = !week.show_week">
							<i class="orange fa fa-plus-square-o" ng-show="!week.show_week"></i>
							<i class="fa fa-minus-square-o" ng-show="week.show_week"></i>
						</div>
					</td>
					<td>{{week.period}}</td>
					<td positive-or-negative-color="{{week.total_payment}}">
						${{week.total_payment | formatPrice}}
					</td>
					<td positive-or-negative-color="{{week.total_payment}}">
						${{week.total_reimburse | formatPrice}}
					</td>
				</tr>
				<tr ng-show="week.show_week">
					<td colspan="4">
						<table class="tb-grid tb-zebra-summary">
							<thead>
								<td style="max-width: 15px"></td>
								<td>Day</td>
								<td>Payment</td>
								<td>Reimbursement</td>
							</thead>
							<tbody ng-repeat="day in week.days">
								<tr>
									<td>
										<div class="link expand-collapse" ng-click="day.show_day = !day.show_day">
											<i class="orange fa fa-plus-square-o" ng-show="!day.show_day"></i>
											<i class="fa fa-minus-square-o" ng-show="day.show_day"></i>
										</div>
									</td>
									<td>{{day.day}}</td>
									<td positive-or-negative-color="{{day.total_payment}}">
										${{day.total_payment | formatPrice}}
									</td>
									<td positive-or-negative-color="{{day.total_reimburse}}">
										${{day.total_reimburse | formatPrice}}
									</td>
								</tr>
								<tr ng-show="day.show_day">
									<td colspan="4">
										<table class="tb-grid tb-zebra tb-zebra-summary" ng-if="day.shifts">
											<thead>
												<tr>
													<td>Shift Started At</td>
													<td>Shift Ended At</td>
													<td>Hours</td>
													<td>Pay</td>
													<td></td>
												</tr>
											</thead>
											<tbody ng-repeat="shift in day.shifts">
												<tr>
													<td>
														{{shift.date_start}}
													</td>
													<td>
														{{shift.date_end}}
													</td>
													<td>
														{{shift.hours}}
													</td>
													<td positive-or-negative-color="{{shift.total_payment}}">
														${{shift.total_payment | formatPrice}}
													</td>
													<td>
														<span ng-class="{ 'span-driver-summary-paid': shift.payment.status == 'Paid',
																							'span-driver-summary-pending': shift.payment.status == 'Pending',
																							'span-driver-summary-processing': shift.payment.status == 'Processing' }">
															{{shift.payment.status}}
														</span>
													</td>
												</tr>
											</tbody>
										</table>
										<table class="tb-grid tb-zebra tb-zebra-summary" ng-if="day.orders">
											<thead>
												<tr>
													<td class="hide-tiny-screen">Order</td>
													<td>
														<span class="hide-tiny-screen">Customer</span>
														<span class="show-tiny-screen">Order #/<br>Customer</span>
													</td>
													<td>Tip</td>
													<td>Delivery Fee</td>
													<td>CB Cash Fee</td>
													<td>Pay</td>
													<td class="hide-tiny-screen">&nbsp;</td>
													<td>Reimbursement</td>
													<td class="hide-tiny-screen">&nbsp;</td>
												</tr>
											</thead>
											<tbody ng-repeat="order in day.orders">
												<tr>
													<td class="hide-tiny-screen">{{order.id_order}}</td>
													<td>
														<span class="hide-tiny-screen">{{order.name}}</span>
														<span class="show-tiny-screen">#{{order.id_order}}<br>{{order.name}}</span>
													</td>
													<td positive-or-negative-color="{{order.tip}}">
														<span ng-if="order.tip == 0">
															paid in cash
														</span>
														<span ng-if="order.tip > 0">
															${{order.tip | formatPrice}}
														</span>
													</td>
													<td positive-or-negative-color="{{order.delivery_fee}}">
														${{order.delivery_fee | formatPrice}}
													</td>
													<td positive-or-negative-color="{{order.markup}}">
														${{order.markup | formatPrice}}
													</td>
													<td positive-or-negative-color="{{order.total_payment}}">
														${{order.total_payment | formatPrice}}
														<span class="show-tiny-screen" ng-class="{ 'span-driver-summary-paid': order.payment.status == 'Paid',
																							'span-driver-summary-pending': order.payment.status == 'Pending',
																							'span-driver-summary-processing': order.payment.status == 'Processing' }">
															{{order.payment.status}}
														</span>
													</td>
													<td class="hide-tiny-screen">
														<span ng-class="{ 'span-driver-summary-paid': order.payment.status == 'Paid',
																							'span-driver-summary-pending': order.payment.status == 'Pending',
																							'span-driver-summary-processing': order.payment.status == 'Processing' }">
															{{order.payment.status}}
														</span>
													</td>
													<td positive-or-negative-color="{{order.total_reimburse}}">
														${{order.total_reimburse | formatPrice}}
														<span class="show-tiny-screen" ng-class="{ 'span-driver-summary-paid': order.reimburse.status == 'Paid',
																							'span-driver-summary-pending': order.reimburse.status == 'Pending',
																							'span-driver-summary-processing': order.reimburse.status == 'Processing' }">
															{{order.reimburse.status}}
														</span>
													</td>
													<td class="hide-tiny-screen">
														<span ng-class="{ 'span-driver-summary-paid': order.reimburse.status == 'Paid',
																							'span-driver-summary-pending': order.reimburse.status == 'Pending',
																							'span-driver-summary-processing': order.reimburse.status == 'Processing' }">
															{{order.reimburse.status}}
														</span>
													</td>
												</tr>
											</tbody>
										</table>
									</td>
								</tr>
							</tbody>
						</table>
					</td>
				</tr>
			</tbody>
		</table>
!-->
		<div ng-if="summary.referral">
			<h2 class="title">New Invited Users</h2>
			<table class="tb-grid tb-zebra" ng-if="summary.referral.invites">
				<thead>
					<tr>
						<td>ID Order</td>
						<td>ID User</td>
						<td>Customer Name</td>
						<td>Date</td>
						<td>Amount</td>
					</tr>
				</thead>
				<tbody>
					<tr ng-repeat="invite in summary.referral.invites">
						<td>{{invite.id_order}}</td>
						<td>{{invite.user.id_user}}</td>
						<td>{{invite.user.name}}</td>
						<td>{{invite.date}}</td>
						<td>${{summary.referral.amount_per_user | formatPrice}}</td>
					</tr>
				</tbody>
				<tbody>
					<tr class="transparent">
						<td></td>
						<td></td>
						<td></td>
						<td><strong>Total</strong></td>
						<td>${{summary.referral.invites_total_payment | formatPrice}}</td>
					</tr>
				</tbody>
			</table>
		</div>

	</div>

	<div ng-if="!summary.payments && !isLoading" class="box-content2">
		Nothing yet. Go deliver some food!
	</div>

</div>

<spinner-loading></spinner-loading>
<hack-expand-content></hack-expand-content>