<div class="top-pad"></div>

<div class="content-padding">

	<h1 class="title"><i class="fa fa-automobile"></i>Driver Onboarding</h1>

	<div class="box-content2 box-content-table">
		<table>
			<tr>
				<td><i class="fa fa-search"></i>&nbsp;&nbsp;<input type="text" ng-model="query.search" id="search" tabindex="1"></td>
			</tr>
		</table>
	</div>
	<div class="bar-loader bar-loader-search" ng-class="{'bar-loader-loading': loading}"></div>

	<h2>
		<a href="/drivers/onboarding/docs">Documents</a> |
		<a href="/drivers/onboarding/new">Create a new driver</a>
	</h2>
	<br><br>

	<div class="box-content2 box-content-table">
		<table class="tb-zebra">
			<tr>
				<th>Name</th>
				<th>Login</th>
				<th>Vehicle</th>
				<th>Community</th>
				<th>Created by</th>
				<th>Active</th>
				<th></th>
			</tr>
			<tr ng-repeat="driver in drivers" ng-attr-tabindex="{{$index+1}}" tab-select="/drivers/onboarding/{{driver.id_admin}}">
				<td>
					<a href="/drivers/onboarding/{{driver.id_admin}}">{{driver.name}}</a>
				</td>
				<td>
					<span ng-if="driver.login">{{driver.login}}</span>
				</td>
				<td>
					{{driver.vehicle}}
				</td>
				<td>
					<span class="staff-community-repeat" ng-repeat="community in driver.communities">
						{{community}}
					</span>
				</td>
				<td>
					{{driver.author}}
				</td>
				<td class="tb-center">
					<span ng-if="driver.active"><i class="fa fa-check"></i></span>
				</td>
				<td>
					<span ng-if="driver.sent_all_docs" class="sp-label sp-label-success">
						Docs ok
					</span>
					<span ng-if="!driver.sent_all_docs" class="sp-label sp-label-warning">
						Docs missing
					</span>
				</td>
			</tr>
		</table>
	</div>

	<table class="tb-pagination right" ng-if="pages > 1" page-key>
		<tbody>
			<tr>
				<td class="td-prev"><button class="button orange" ng-if="query.page > 1" ng-click="setPage(query.page-1)">prev</button></td>
				<td class="td-info">Page {{query.page}} of {{pages}}</td>
				<td class="td-next"><button class="button orange" ng-if="query.page < pages" ng-click="setPage(query.page+1)">next</button></td>
			</tr>
		</tbody>
	</table>

	<div class="divider"></div>

</div>
