<div class="drivers-welcome">
	<div class="slide">
		<h1>Well, hello there beautiful!</h1>
	
		<p>So it seems this is the first time I have seen you. Lets take a second to get to know each other.</p>
	</div>
	<div class="slide">
		<h1>Enable location services</h1>
		
		<p>
			In order to better serve our customers, please enable your location services for me.
			<br><br>
			Location services are only enabled while you are on shift. This will help save your battery so we can hang out much longer.
			<br><br>
			Go ahead and click the enable button at the bottom so we can continue.
		</p>

	</div>
	<div class="slide">
		<h1>Enable push notifications</h1>
		
		<p>
			I just love talking to you, so lets do it more often. 
			<br><br>
			When an order comes in, I will let you know about it by sending you a notification.
			<br><br>
			Please enable push notifications so we can keep on chatin'.
		</p>

	</div>
	<div class="slide">
		<h1>Wahoo!</h1>
		
		<p>That't it! Lets be the best of friends!</p>
	</div>	
</div>