<div class="drivers-welcome">
	<div class="top-pad"></div>
	<div class="content-padding">
		<h1 class="welcome-title">Enable push notifications</h1>
		<div class="welcome-icon"><i class="fa fa-bell"></i></div>
		
		<p>
			I love talking to you, so let's do it more often. 
			<br><br>
			When an order comes in, I will let you know about it by sending you a notification.
			<br><br>
			Please enable push notifications so we can keep on chattin'.
		</p>
		<div class="welcome-button"><a href ng-click="pushit()"><button class="ladda-button button orange" data-color="orange" data-style="zoom-in"><span class="ladda-label">Enable</span></button></a></div>
	</div>
	
</div>