<? /*
	NOT USED RIGHT NOW
	
	
	<div class="top-pad"></div>

<div class="content-padding" ng-show="ready">

	<h1 class="title left"><i class="fa fa-bank"></i><span>Payments</span></h1>

	<div class="divider"></div>

	<form name="form" ng-show="drivers">

		<ul class="ul-inputs box-content2">
			<li class="li-input">
				<div class="label">Select a driver:</div>
				<div class="input">
					<select name="driverSummary" ng-model="id_admin" ng-change="list()" ng-options="opt.id_admin as opt.name for opt in drivers"></select>
				</div>
			</li>
		</ul>

	</form>

	<div class="divider"></div>

	<div ng-if="result">

		<div ng-show="result.payments.length">

			<h2 class="title">
				<span>Filter</span>
			</h2>

			<div class="box-filter">
				<button class="button green" ng-class="{ 'inactive' : filter }" ng-click="filter = false">All</button>
				<button class="button button-big green" ng-class="{ 'inactive' : filter != 'Reimbursement' }" ng-click="filter = 'Reimbursement'">Reimbursement</button>
				<button class="button button-big green" ng-class="{ 'inactive' : filter != 'Payment' }" ng-click="filter = 'Payment'">Payments</button>
			</div>
			
			<div class="divider"></div>

			<table class="tb-grid tb-zebra" ng-show="result.payments.length">
				<thead>
					<tr>
						<td>Type</td>
						<td>Period</td>
						<td>Amount</td>
						<td>Status</td>
						<td>Sent date</td>
						<td>Approximate payment date</td>
					</tr>
				</thead>
				<tbody>
					<tr ng-repeat="payment in result.payments" ng-show="!filter || filter == payment.type">
						<td>
							<span class="link" ng-click="show_payment( payment.id_payment_schedule );">{{payment.type}}</span>
							<span ng-if="payment.total_cash_orders" class="note">
								<br>
								Already received in cash: ${{payment.total_received_cash | formatPrice}} + Cash Tips ({{payment.total_cash_orders}} orders)
							</span>
						</td>
						<td>{{payment.range_date}}</td>
						<td positive-or-negative-color="{{payment.amount}}">
							${{payment.amount | formatPrice}}
						</td>
						<td>
							<span ng-class="{ 'span-driver-summary-paid': payment.status == 'Paid',
																'span-driver-summary-pending': payment.status == 'Pending',
																'span-driver-summary-processing': payment.status == 'Processing' }">

								<span ng-switch="payment.status">
								<span ng-switch-when="Pending">Not Yet Paid</span>
								<span ng-switch-default>{{payment.status}}</span>
							</span>
						</td>
						<td>{{payment.send_date}}</td>
						<td>{{payment.paid_date}}</td>
					</tr>
				</tbody>
			</table>

		</div>

		<div ng-if="!result.payments.length" class="box-content2">
			Nothing yet. Go deliver some food!
		</div>

	</div>
</div>

<spinner-loading></spinner-loading>
<hack-expand-content></hack-expand-content>

*/ ?>