<div class="top-pad"></div>
<div class="content-padding">
<div class="drivercontain">
    <h1 class="title left"><i class="fa fa-quote-left"></i><span>Feedback</span></h1>
    <div class="divider"></div>
   <h2>Help Us Help You</h2>
   <br>
    <form>
    <div class="driver-feedback">
 <div class="form-group">
            <label class="driverlabel">
                <span>*</span>How can we make driving for Crunchbutton a more awesome experience?
            </label>
            <br>
            
            <div class="drivertextbox">
            <div ng-if="errors.message">Please tell us how to improve!</div>
                <textarea ng-model="feedback.message" name="message" class="driverform-control"></textarea>
            </div>
        </div>

        <div class="form-group">
            <label class="driverlabel">
                Driving Community: (optional)
            </label>
            <div class="drivertextbox">
                <input type="text" ng-model="feedback.community" name="community" class="driverform-control" >
            </div>
        </div>
        
         <div class="form-group">
            <label class="driverlabel">
                Name: (optional)
            </label>
            <div class="drivertextbox">
                <input type="text" class="driverform-control" ng-model="feedback.name" name="name" >
            </div>
        </div>
        
    <button ng-click="post()" type="submit" class="button orange">Submit</button>
    </div><!--close driver-feedback div-->
  </form>


 

</div>
</div>