<div class="top-pad"></div>

<div class="content-padding">
	<div class="box-content2" ng-if="ready">
		<span ng-bind-html-unsafe="receipt"></span>
	</div>
	<div class="box-content2" ng-if="show_form">
		<ul class="ul-inputs">
			<li class="li-input">
				<label class="switch-wrap">
					<input type="checkbox" class="switch" ng-model="email.send"/><div></div>
				</label>
				<div class="label">Send receipt by email?</div>
			</li>
			<li class="li-input" ng-show="email.send">
				<div class="label">Email:</div>
				<div class="input"><input type="text" name="email" ng-model="email.email" placeholder="Email"></div>
			</li>
			<li class="li-input" ng-show="!isSaving">
				<button class="button save" ng-click="save();">Save</button>
				<button class="button orange" ng-click="clear();">Clear</button>
			</li>
			<li class="li-input" ng-show="isSaving">
				<i class="fa fa-circle-o-notch fa-spin"></i>
			</li>
		</ul>
	</div>
</div>
<spinner-loading></spinner-loading>
<hack-expand-content></hack-expand-content>