<div class="drivers-welcome">
	<div class="top-pad"></div>
	<div class="content-padding">
		<h1 class="welcome-title">Crunchbutton &amp; You</h1>
		
		<div class="welcome-icon"><i class="fa fa-truck"></i></div>
		<p>
			Crunchbutton lets customers order food delivered from their favorite restaurants. Your task is to deliver the food. I'm an app, and I'll help you do that. Looking forward to working together!
		</p>
		<div class="welcome-button"><a href="/drivers/welcome/location"><button class="ladda-button button orange" data-color="orange" data-style="zoom-in"><span class="ladda-label">Next</span></button></a></div>
	</div>
</div>