<div class="top-pad"></div>

<div class="content-padding" ng-show="ready">

	<div class="dialog-message dialog-message-error" style="font-size: 1.3em;">
			<b>In order to get paid</b></br> you must fill out and submit all documents!
	</div>

	<h1 class="title left"  style="font-size: 2em;"><i class="fa fa-briefcase"></i><span>Documents</span></h1>

	<div class="divider"></div>

	<h2 ng-if="!isLive" class="title" ng-click="pay_info()"><span class="link orange">Enter Payment Info</span></h2>

	<div class="dialog-message dialog-message-error" style="font-size: 1.3em;">
			Please upload documents using a desktop computer!
	</div>
	
	<div class="divider"></div>
	
	<h2 class="title"  style="font-size: 1.3em;">
		Please download the docs, fill them out and then upload them back to this page. We recommend signing them with <a href="https://www.hellosign.com/" target="_blank">Hellosign</a>.
	</h2>

	<table class="tb-grid">
		<tbody>
			<tr ng-repeat="doc in documents" ng-if="doc.url">
				<td ng-click="edit(driver.id_admin)" class="td-medium">
					<h2 class="title" style="font-family: Ruda; color: #000; font-size: 1.2em; line-height: 1em;">{{doc.name}}</h2>
					<br/>
					<a href="{{doc.url}}" target="_blank" style="font-size:1.2em;">Download</a>
				</td>
				<td class="td-medium" style="vertical-align: top;">
					<!-- if he already have this doc, show the download link -->
					<span ng-show="doc.status" title="Sent at {{doc.status.date_formated}}">
						<a href="{{doc.status.url}}" target="_blank">Download doc</a>
					</span>
					<!-- upload directive -->
					<div class="upbutton"><div driver-docs-upload="{{doc.id_driver_document}}"></div></div>
				</td>
			</tr>
		</tbody>
	</table>

	<h2 class="title" style="font-size: 1.3em;">
		Please upload a clear picture of your Drivers License and Insurance Card here. You can do this right from your smartphone.
	</h2>

	<table class="tb-grid">
		<tbody>
			<tr ng-repeat="doc in documents" ng-if="!doc.url">
				<td ng-click="edit(driver.id_admin)" style="vertical-align: top;">
					<h2 class="title" style="padding-top: 20px; font-family: Ruda; color: #000; font-size: 1.2em;">{{doc.name}}</h2>
				</td>
				<td class="td-medium upbutton">
					<span ng-show="doc.status" title="Sent at {{doc.status.date_formated}}"><a href="{{doc.status.url}}" target="_blank">Download</a></span>
					<div class="upbutton"><div driver-docs-upload="{{doc.id_driver_document}}"></div></div></br>
				</td>
			</tr>
		</tbody>
	</table>
</div>


<spinner-loading></spinner-loading>
<hack-expand-content></hack-expand-content>