<div class="account-reset-container modal zoom-anim-dialog small-container mfp-hide" ng-controller="AccountResetCtrl">
	<div ng-show="reset.step == 1">
		<form class="password-reset-form">
			<h1>Password reset</h1>
			<input type="text" maxlength="250" id="account-reset-code" value="" ng-model="reset.code" placeholder="enter the reset code" tabindex="10" />
			<div class="divider"></div>
			<div ng-show="reset.error == 'empty'" class="error">
				Please enter the reset code.
			</div>
			<div ng-show="reset.error == 'invalid'" class="error">
				Sorry, this code is invalid.
			</div>
			<div ng-show="reset.error == 'expired'" class="error">
				Sorry, this code is expired.
			</div>
			<button ng-tap="reset.validateCode();">Reset</button>
			<div class="divider"></div>
		</form>
	</div>
	<div ng-show="reset.step == 2">
		<form class="password-change-form" ng-show="!reset.success">
			<h1>Type your new password</h1>
			<input type="password" maxlength="250" ng-model="reset.password" id="account-reset-password" value="" placeholder="password" tabindex="10" />
			<div class="divider"></div>
			<div ng-show="reset.error == 'empty'" class="error">
				Please enter your new password.
			</div>
			<div ng-show="reset.error == 'invalid'" class="error">
				Sorry, this code is invalid.
			</div>
			<button ng-tap="reset.changePassword();">Change</button>
			<div class="divider"></div>
		</form>
		<div ng-show="reset.success">
			<h1>Done!</h1>
			<div class="success">
				Your password has changed!
			</div>
		</div>
	</div>
</div>
