<div class="facebook">
	<div class="social-button facebook-button" ng-click="facebook.auth()">
		<i class="icon-facebook"></i>
		<span class="social-button-text">{{title}}</span>
		<div class="divider"></div>
	</div>
	<div class="wait" ng-show="facebook.facebook.wait && !facebook.facebook.error.userExists && !facebook.facebook.error.unknown && !facebook.facebook.error.login">
		Just a sec...
	</div>
	<div class="error" ng-show="facebook.facebook.error.userExists">
		Sorry, it seems the facebook user is already related with other user.
	</div>
	<div class="error" ng-show="facebook.facebook.error.unknown">
		Sorry, something bad happened.
	</div>
	<div class="error" ng-show="facebook.facebook.error.login">
		Sorry, it seems you cancelled login or did not fully authorize.
	</div>
</div>