<div class="account-reset-container modal zoom-anim-dialog small-container mfp-hide" ng-controller="AccountResetCtrl">
	<div ng-show="reset.step == 1">
		<form>
			<h1>Password reset</h1>
			<input type="text" maxlength="250" id="account-reset-code" value="" ng-enter="reset.validateCode()" ng-model="reset.form.code" placeholder="enter the reset code" tabindex="10" />
			<div class="divider"></div>
			
			<div class="error">
				<div ng-repeat="error in reset.errors">
					{{error}}
				</div>
			</div>

		</form>
		<button ng-click="reset.validateCode();">Reset</button>
		<div class="divider"></div>
	</div>
	<div ng-show="reset.step == 2">
		<form ng-show="!reset.success">
			<h1>Type your new password</h1>
			<input type="password" maxlength="250" ng-model="reset.form.password" ng-enter="reset.changePassword()" id="account-reset-password" value="" placeholder="password" tabindex="10" />
			<div class="divider"></div>
			<div class="error">
				<div ng-repeat="error in reset.errors">
					{{error}}
				</div>
			</div>
		</form>
		<button ng-click="reset.changePassword();" ng-show="!reset.success">Change</button>
		<div class="divider"></div>
		<div ng-show="reset.success">
			<h1>Done!</h1>
			<div class="success">
				Your password has changed!
			</div>
		</div>
	</div>
</div>