<div class="main-content-readable">

	<h1 class="about-header">Free food</h1>
	<p>
		Earn a FREE DELIVERY for every new customer you refer with your code <b>{{account.user.invite_code}}</b>
		<br>
		Just get them to enter <b>{{account.user.invite_code}}</b> in the Notes section of their first order or visit your link:
	<div class="field-container">
		Invite URL:&nbsp;&nbsp;&nbsp;<input  type="text" ng-simulate-read-only="{{referral.cleaned_url()}}" value="{{referral.cleaned_url()}}" />
	</div>
	</p>

<!--	<div class="divider"></div>-->
	<div style="margin-top: 0" class="social-button twitter-button social-button-invite" ng-click="referral.twitter();">
		<i class="fa fa-twitter"></i><span class="social-button-text">Tweet</span>
	</div>
	<div style="margin-top: 0" class="social-button facebook-button social-button-invite" ng-click="referral.facebook();">
		<i class="fa fa-facebook"></i><span class="social-button-text">Share</span>
	</div>
	<div class="divider"></div>

	<div class="divider"></div>

	<br />
	<div class="divider"></div>
	<div ng-if="!account.user.points.free_delivery_message && account.user.points.away_free_delivery">
		0 &nbsp;<span class="points"><progress max="100" value="{{points_percent}}"></progress></span>&nbsp; {{account.user.points.free_delivery}}

	</div>
	<br />
	<div ng-if="account.user.points.away_free_delivery > 0">
		<p>
			You are <b>{{account.user.points.away_free_delivery}}</b> points away from a free delivery!<br>
		</p>
	</div>


	</div>
</div>