<div class="main-content-readable home-greeting">
	<div class="home-welcome home-welcome-click">
		<h1>Push a button. Get Food.</h1>
		<h2>
			Order the top food in your area. 
			<br />
			After you order, everything is saved for future 1 click ordering.
			<br />
			<strong>Enter your Address:</strong>
		</h2>
	</div>
	<div class="home-welcome home-welcome-touch">
		<h1>Push a button. Get Food.</h1>
		<h2>
			Order the top food in your area. 
			<br />
			After you order, everything is saved for future 1 click ordering.
			<br />
			<strong>Enter your Address:</strong>
		</h2>
	</div>
</div>
<div class="enter-location">
	<form class="button-letseat-formform" onsubmit="return false;">
		<table class="button-letseat-table" cellpadding="0" cellspacing="0">
			<tr>
				<td style="width: 100%;"><input type="text" class="location-address" placeholder="Enter your address"<%= autofocus %>></td>
			</tr>
		</table>
	</form>
</div>
<div class="divider"></div>
<button class="button-letseat-form button-bottom"><div>Let's Eat!</div></button>
<div class="error-location" style="display: none;">
	<div class="home-welcome home-welcom-error">
		<h1>Sorry!</h1>
		<h2>
				We don't serve <span class="loc-your-area change-location-inline"><%= yourArea %></span> yet. But we hope to--just tell us where's awesome to eat there!</h2>
	</div>
	<div class="divider"></div>
	<div class="home-recommend">
		<div class="home-recommend-form">
			<div class="home-recommend-title">
				<h1>Recommend a restaurant:</h1>
			</div>
			<input type="text" class="home-recommend-text">
			<button class="home-recommend-button"><div>Recommend!</div></button>
			<div class="divider"></div>
			<div class="home-recommend-message">
				What's your absolute favorite? What should be on Crunchbutton? Tell us, and we'll actually add it and get back to you.
			</div>
			<div class="divider"></div>
		</div>
		<div class="home-recommend-thank-you">
			<div class="home-recommend-title">
				<h1>Awesome, thanks!</h1>
			</div>
			<div class="divider"></div>
			<div class="home-recommend-message">
				<% if( App.config.user.has_auth ) { %>
					We'll let you know if they make it to Crunchbutton.
				<% } else { %>
					<a href="#" class="home-recommend-message-create-account">Create an account</a>, and when we'll let you know when we launch in your area!
				<% } %>
			</div>
		</div>
	</div>
	
	<div class="content-item-locations">
		<h1>Our most popular locations</h1>
	</div>
	<div class="content-padder-before"></div>
	<div class="content-padder">
		<div class="meal-items">
			<% _.each(topCommunities, function(community) { %>
				<div class="meal-item" data-permalink-community="<%= community.id_community %>">
					<div class="meal-item-spacer"></div>
					<div class="meal-item-content">
						<div class="meal-pic" style="background: url(<%= community.image %>);"></div>
						<h2 class="meal-restaurant"><%= community.name %></h2>
						<h3 class="meal-food">Top Restaurant: <%= community.restaurant %></h3>
					</div>
				</div>
			<% }); %>
		</div>
	</div>
</div>