<div class="main-content-readable home-greeting">
	<div class="home-welcome home-welcome-click">
		<h1>Push a button. Get Food.</h1>
		<h2>
			Order the top food in your area. 
			<br />
			After you order, everything is saved for future 1 click ordering.
			<br />
			<strong>Enter your Address:</strong>
		</h2>
	</div>
	<div class="home-welcome home-welcome-touch">
		<h1>Push a button. Get Food.</h1>
		<h2>
			Order the top food in your area. 
			<br />
			After you order, everything is saved for future 1 click ordering.
			<br />
			<strong>Enter your Address:</strong>
		</h2>
	</div>
</div>
<div class="enter-location">
	<form class="button-letseat-formform" onsubmit="return false;">
		<table class="button-letseat-table" cellpadding="0" cellspacing="0">
			<tr>
				<td style="width: 100%;">
					<input type="text" class="location-address" placeholder="Enter your address"<%= autofocus %>>
				</td>
				<td><div class="location-detect">
					<div class="location-detect-icon"></div>
					<div class="location-detect-loader"></div>
				</div></td>
			</tr>
		</table>
	</form>
</div>
<div class="divider"></div>
<button class="button-letseat-form button-bottom"><div>Enter your zip code or full address</div></button>
<div class="error-location" style="display: none;">
	<div class="main-content-readable">
		<div class="home-welcome home-welcom-error">
			<h1>Sorry!</h1>
			<h2>
					We don't serve <span class="loc-your-area change-location-inline"><%= yourArea %></span> yet.</span> But we can. Just tell us where's awesome to eat there!
			</h2>
		</div>
		<div class="divider"></div>
		<div class="home-recommend">
			<div class="home-recommend-form">
				<div class="home-recommend-title">
					<h1><strong>Recommend a restaurant:</strong></h1>
				</div>
				<input type="text" class="home-recommend-text">
				<button class="home-recommend-button"><div>Recommend!</div></button>
				<div class="divider"></div>
				<div class="home-recommend-message">
					What's your absolute favorite? What should be on Crunchbutton? Tell us, and we'll actually add it and get back to you.
				</div>
				<div class="divider"></div>
			</div>
			<div class="home-recommend-thank-you">
				<div class="home-recommend-title">
					<h1>Awesome, thanks!</h1>
				</div>
				<div class="divider"></div>
				<div class="home-recommend-message-thank-you">
					<% if( App.config.user.has_auth ) { %>
						We'll let you know if they make it to Crunchbutton.
					<% } else { %>
						<a href="#" class="home-recommend-message-create-account"><span>Create an account</span></a> and when we'll let you know when we launch in your area!
					<% } %>
				</div>
			</div>
		</div>
	</div>
	<div class="content-item-locations">
		<h1>Crunchbutton by city:</h1> 
		<div class="content-item-locations-cities">
			<% _.each(topCommunities, function(alias) { %>
				<span class="content-item-locations-city" permalink="<%= alias.alias %>"><%= alias.name %></span>&nbsp;&nbsp;&nbsp;&nbsp;
			<% }); %>
		</div>
	</div>
</div>