<div class="bg">
	<div class="home-top parallax-bg">
		<div class="top-pad"></div>

		<div class="home-inputs">
		<div class="splash-inputs">

			<div class="cafe-bubble-wrap">
				<div class="bubble-curved bubble-curved-white bubble-animated animated-resize">
					<div class="text" ng-switch="loseMessage">

						<span class="small" ng-switch-when="1">Just let us know that you want crunchbutton</span>
						<span class="small" ng-switch-when="2">and we will be there<br> as soon as we can!</span>
						<span class="small" ng-switch-when="3">Interested in becoming a Community Rep?</span>
						<span class="small" ng-switch-when="4">How about becoming a driver?</span>
						<span class="small" ng-switch-when="5">Head over to our jobs page and let us know!</span>
						<span class="single-line" ng-switch-when="6"><i class="fa fa-heart"></i> <i class="fa fa-heart"></i> <i class="fa fa-heart"></i></span>
						<span class="small" ng-switch-default><b>Grow your own delivery company</b></span>

					</div>
				</div>
				<div class="bubble-curved-spacer"></div>
			</div>
			<div class="faq-tomato-green animated-resize" ng-instant="loseMessage = (loseMessage > 6 ? 0 : (loseMessage+1))" instant-pass-thru></div>
			<div class="divider spacer-one-two"></div>

			<div ng-if="!complete">

				<div ng-show="!show_form">
					<p>
						Want to run your own on-demand business? Launch Crunchbutton in your community!
						<br><br>
						Crunchbutton provides you with the resources you'll need to deliver orders, add restaurants, and find customers. Develop your own small business with our tech powering you.
					</p>

					<div class="divider spacer-one-two"></div>

					<div class="button-pushable">
						<button class="button orange" ng-click="show_form = true;">
							<div><b>Bring Crunchbutton to Me</b></div>
						</button>
					</div>

					<div class="divider spacer-one-one"></div>

					<p class="center-text">
						<a href="" class="splash-continue" ng-instant="navigation.link('/location')">Try another location</a>
					</p>

				</div>

				<div ng-show="show_form">

					<div class="divider spacer-one-one"></div>

					<div class="run-business-error" ng-if="submitted && !contact.name">Please enter your name</div>
					<input class="location-recommend" autocapitalize="off" autocorrect="off" placeholder="Name"  ng-model="contact.name">

					<div class="run-business-error" ng-if="submitted && !contact.phone">Please enter your phone</div>
					<input class="location-recommend" autocapitalize="off" autocorrect="off" placeholder="Phone"  ng-model="contact.phone">

					<div class="run-business-error" ng-if="submitted && !contact.email">Please enter your email</div>
					<div class="run-business-error" ng-if="submitted && email_invalid">Please enter a valid email</div>
					<input class="location-recommend" autocapitalize="off" autocorrect="off" placeholder="Email"  ng-model="contact.email">

					<div class="run-business-error" ng-if="submitted && !contact.address">Please enter your address</div>
					<input class="location-recommend" autocapitalize="off" autocorrect="off" placeholder="Address"  ng-model="contact.address">

					<div class="run-business-error" ng-if="submitted && !contact.reason">Please tell us why you'd be a good fit to build your own business</div>
					<textarea class="run-business-textarea" autocapitalize="off" autocorrect="off" placeholder="Why I'd be a good fit to build my own business:" ng-model="contact.reason"></textarea>

					<div class="button-pushable">
						<a class="button orange" ng-click="sendMessage()">
							<div><b>Send</b></div>
						</a>
					</div>

					<p class="center-text">
						<a href="" class="splash-continue small" ng-click="show_form = false;">Cancel</a>
					</p>

				</div>

			</div>

			<div ng-if="complete" class="run-business-thank-you">
				<p>Thank you!</p>
			</div>


			<? /*
			<div ng-if="account.user.id_user && !recommend.greetings">
				<h4>We don't serve that address yet.</h4>
				<p>But you can recommend something. Let us know what you want to see on crunchbutton!</p>
				<div class="divider spacer-one-two"></div>

				<input class="location-recommend" autocapitalize="off" autocorrect="off" placeholder="e.g. Alpha Delta Pizza" ng-enter="recommend.send()" ng-model="recommend.form.restaurant">

				<div class="button-pushable">
					<button class="button orange" ng-click="recommend.send()"><b>Recommend</b></button>
				</div>
			</div>


			<div ng-if="recommend.greetings">
				<h4>Sent to our brains!</h4>
				<p>We will let you know soon! Thanks for trying crunchbutton!</p>
			</div>
			*/ ?>

		</div>


		</div>
	</div>

	<div ng-include src="'/assets/view/location.bottom.html'"></div>
</div>