<div class="bg">
	<div class="home-top parallax-bg">
		<div class="top-pad"></div>
	
		<div class="home-inputs">
		<div class="splash-inputs">

			<div class="cafe-bubble-wrap">
				<div class="bubble-curved bubble-curved-white bubble-animated animated-resize">
					<div class="text" ng-switch="loseMessage">

						<span class="small" ng-switch-when="1">Just let us know that you want crunchbutton</span>
						<span class="small" ng-switch-when="2">and we will be there<br> as soon as we can!</span>
						<span class="small" ng-switch-when="3">Interested in becoming a Community Rep?</span>
						<span class="small" ng-switch-when="4">How about becoming a driver?</span>
						<span class="small" ng-switch-when="5">Head over to our jobs page and let us know!</span>
						<span class="single-line" ng-switch-when="6"><i class="fa fa-heart"></i> <i class="fa fa-heart"></i> <i class="fa fa-heart"></i></span>
						<span class="single-line" ng-switch-default><b>Coming soon</b></span>

					</div>
				</div>
				<div class="bubble-curved-spacer"></div>
			</div>
			<div class="faq-tomato-green animated-resize" ng-instant="loseMessage = (loseMessage > 6 ? 0 : (loseMessage+1))" instant-pass-thru></div>
			<div class="divider spacer-one-two"></div>

			<div ng-if="!complete">
				<p>
					Crunchbutton is currently in a limited area trial featuring only a select few colleges.
					<span ng-if="account.user.email"> Want Crunchbutton in your area? Click the button below to vote and be notified when we join your area.</span>
					<span ng-if="!account.user.email"> Enter your email below to be notified when Crunchbutton is available near you.</span>
				</p>

				<div class="divider spacer-one-two" ng-if="account.user.email"></div>
				<div class="divider spacer-one-one" ng-if="!account.user.email"></div>

				<input ng-if="!account.user.email" class="location-recommend" autocapitalize="off" autocorrect="off" placeholder="Please enter your email address" ng-enter="recommend.notify()" ng-model="recommend.form.email">


				<div class="button-pushable">
					<button class="button orange" ng-click="notifyMe()">
						<div ng-spinner="loadingNotifyme" data-spinner-color="#fff" data-spinner-scale="1.6"><b>Bring crunchbutton to me</b></div>
					</button>
				</div>
			</div>
			
			<div ng-if="complete">
				<p>Thanks! We will let you know as soon as we are in your area.</p>
			</div>


			<? /*
			<div ng-if="account.user.id_user && !recommend.greetings">
				<h4>We don't serve that address yet.</h4>
				<p>But you can recommend something. Let us know what you want to see on crunchbutton!</p>
				<div class="divider spacer-one-two"></div>

				<input class="location-recommend" autocapitalize="off" autocorrect="off" placeholder="e.g. Alpha Delta Pizza" ng-enter="recommend.send()" ng-model="recommend.form.restaurant">

				<div class="button-pushable">
					<button class="button orange" ng-click="recommend.send()"><b>Recommend</b></button>
				</div>
			</div>


			<div ng-if="recommend.greetings">
				<h4>Sent to our brains!</h4>
				<p>We will let you know soon! Thanks for trying crunchbutton!</p>
			</div>
			*/ ?>

			<p class="center-text">
				<a href="" class="splash-continue" ng-instant="navigation.link('/location')">Try another location</a>
			</p>
		</div>
		

		</div>
	</div>
	
	<div ng-include src="'/assets/view/location.bottom.html'"></div>
</div>