<div class="bg">
	<div class="home-top parallax-bg">
		<div class="top-pad"></div>
	
		<div ng-if="!locationError">
			<div class="pushabutton"></div>
			<div class="home-inputs">
				<h4 class="action">What's your full address?</h4>
				<table cellpadding="0" cellspacing="0" class="home-location">
					<tr>
						<td style="width: 100%;"><input class="location-address needsclick" autocapitalize="off" autocorrect="off" placeholder="e.g. 37 Elm St, New Haven CT 06511" ng-focus="softKeyboard($event);" geo-complete-enter="letsEat()" id="input-location-address" ng-model="location.form.address" geo-complete ng-class="{'new-location-address' : location.form.address}">
						</td>
						<td>
							<button class="location-detect" ng-click="locEat()" ng-class="{'hide-location-detect': location.form.address}">
								<span class="fa fa-location-arrow" ng-spinner="loadingLocation" data-spinner-color="#fff" data-spinner-scale="1.5"></span>
							</button>
						</td>
					</tr>
				</table>
				<div class="button-pushable find-restaurants">
					<button class="button orange find-restaurants button-letseat-form" ng-click="letsEat()">
						<div ng-spinner="loadingGetfood" data-spinner-color="#fff" data-spinner-scale="1.6">Find Restaurants!</div>
					</button>
				</div>
			</div>
		</div>

	</div>
	
	<div ng-include src="'/assets/view/location.bottom.html'"></div>

</div>