<div class="main-content-readable home-greeting" ng-show="!locationError">
	<div class="home-welcome">
		<h1>Push a button. Get Food.</h1>
		<h2>
			Order the top food in your area. 
			<br />
			After you order, everything is saved for future 1 click ordering.
			<br />
			<strong>Enter your Address:</strong>
		</h2>
	</div>
</div>
<div class="enter-location" ng-show="!locationError">
	<form class="button-letseat-formform" onsubmit="return false;">
		<table class="button-letseat-table" cellpadding="0" cellspacing="0">
			<tr>
				<td style="width: 100%;">
					<input type="text" class="location-address" ng-class="{ 'location-warning' : warningPlaceholder }" ng-enter="letsEat()" ng-model="location.form.address" placeholder="Enter your zip code or full address"<?=$this->export ? '' : ' autofocus'?>>
				</td>
				<td>
					<div class="location-detect">
						<div class="location-detect-icon" ng-click="locEat()"></div>
						<div class="location-detect-loader"></div>
					</div>
				</td>
			</tr>
		</table>
	</form>
</div>
<div class="divider"></div>
<button ng-show="!locationError" class="button-letseat-form button-bottom" ng-click="letsEat()"><div>Let's Eat!</div></button>

<div class="error-location" ng-show="locationError">

	<div class="main-content-readable" ng-controller="RecommendRestaurantCtrl">
		<div class="home-welcome">
			<h1>&#9785; Sorry!</h1>
			<h2>
				We don't serve <span ng-click="resetFormLocation()" class="loc-your-area change-location-inline">{{yourArea}}</span> yet. Please {{isMobile | iif : 'tap' : 'click'}} <span ng-click="resetFormLocation()" class="change-location-inline">here</span> to enter a different address.
				<div ng-hide="recommend.greetings">
					<div class="home-reccomend-spacer"></div>
					Have something specific in mind? Tell us your favorite restaurant in your area! After we add it, we will let you know.
				</div>
			</h2>
		</div>

		<div class="home-recommend">
			<div class="home-recommend-form" ng-hide="recommend.greetings">
				<input type="text" ng-enter="recommend.send()" ng-model="recommend.form.restaurant" class="home-recommend-text" placeholder="ex: Your favorite restaurant">
				<button ng-click="recommend.send()" class="home-recommend-button"><div>Recommend it!</div></button>
				<div class="divider"></div>
				<div class="divider"></div>
			</div>

			<div class="home-recommend-thank-you" ng-show="recommend.greetings">
				<div class="divider"></div>
				<div class="home-recommend-message-thank-you">
					<div ng-show="account.user">
						<span class="home-reccomend-message-content">We'll let you know if they make it to Crunchbutton.</span>
					</div>
					<div ng-show="!account.user">
						<button ng-click="modal.signupOpen()" class="home-recommend-button"><div>Create an account</div></button>
						<span class="home-reccomend-message-content">and we'll let you know when we launch in your area!</span>
					</div>
				</div>
			</div>
			<div class="divider"></div>
		</div>
	</div>
	
	<div class="divider dots"></div>
	
	<div class="main-content-readable content-item-locations">
		<div class="home-welcome">
			<h1>Our popular cities</h1> 
			<h2>Take a look at some of of the best delivery food in these cities.</h2>
			<div class="content-item-locations-cities">
				<span ng-repeat="alias in topCommunities">
					<span class="content-item-locations-city" ng-click="openCity(alias.alias)" permalink="{{alias.alias}}">{{alias.name}}</span>
				</span>
			</div>
		</div>
	</div>
</div>