<div class="notification-remote-container zoom-anim-dialog mfp-hide dialog" ng-controller="NotificationRemoteCtrl">
	<div class="dialog-padding">
		<h1 ng-bind="title" ng-show="title"></h1>
		<p ng-bind-html-unsafe="message"></p>
		<div class="divider"></div>
	</div>
	<div class="dialog-divider"></div>
	<div class="dialog-padding dialog-bottom-buttons">
		<div ng-if="hasFn">
			<div class="button-pushable button-remote-fn"><button class="button lightorange" ng-click="complete()">view</button></div>
			<div class="button-pushable button-remote-fn"><button class="button green" ng-click="cancel()">close</button></div>
			<div class="divider"></div>
		</div>
		<div ng-if="!hasFn">
			<div class="button-pushable"><button class="button lightorange" ng-click="complete()">ok</button></div>
		</div>
	</div>
</div>