<div ng-show="!orders.length">
	Orders loader
</div>

<div ng-show="orders.length" class="main-content-readable">
	<div class="restaurant-item-title">order history</div>
	<ul class="resturant-dishes resturant-dish-container your-orders">
		<li ng-repeat="order in orders">
			<span ng-tap="displayRestaurant()" class="dish-name order-restaurant" name="{{order._restaurant_name}}" permalink="{{order._restaurant_permalink}}" id_restaurant="{{order.id_restaurant}}">{{order._restaurant_name}}</span>
			<span class="dish-price">{{order.timeFormat}} ({{order._tz}})</span>
			<a  ng-tap="displayOrder()" class="order-link" href="javascript:;" data-id_order="{{order.uuid}}">View Receipt</a>
			<div class="divider"></div>		
		</li>
	</ul>

	<div class="order-options">
		<a ng-show="(!account.facebook.logged && !account.user.facebook)" href="javascript:;" class="signup-add-facebook-button" >Connect with Facebook</a>
		<a href="javascript:;" ng-tap="signout.do()" class="signout-button">Sign out</a>
		<div class="divider"></div>
	</div>
</div>