<div ng-show="!orders.list">
	Orders loader
</div>
<div ng-show="orders.list" class="main-content-readable">

	<div class="restaurant-item-title">order history</div>

	<ul class="resturant-dishes resturant-dish-container your-orders">
		<li ng-repeat="order in orders.list">
			<span ng-click="orders.restaurant(order._restaurant_permalink)" class="dish-name order-restaurant">
				{{order._restaurant_name}}
			</span>
			<span class="dish-price">
				{{order.timeFormat}} ({{order._tz}})
			</span>
			<a ng-click="orders.receipt(order.id)" class="order-link" href="javascript:;">View Receipt</a>
			<div class="divider"></div>		
		</li>
	</ul>


	<div>
		<div class="invite-code-container field-container" ng-show="referral.enabled">
			<div class="restaurant-item-title">Invite code</div>
			<p>
				For every NEW friend who orders food, we'll give you ${{referral.value}} credit.
				<br/>
				You have {{referral.invites}} of the {{referral.limit}} invites remaining.
			</p>

			<input type="text" style="margin:10px;" ng-click-select-all value="{{referral.invite_url}}" readonly="readonly" />

			<p>
				<a target="blank"class="twitter-invite-button" href="https://twitter.com/intent/tweet?url={{referral.invite_url}}&text=Some call to action message here!"><i class="icon-twitter"></i> Tweet on Twitter</a>
				<a href="#" class="facebook-invite-button" ng-click="referral.facebook()"><i class="icon-facebook" style=""></i> Share on Facebook</a>
			</p>
			
			<div class="divider"></div>
		</div>
	</div>

	<div class="order-options">
		<a ng-show="!account.hasFacebook" href="javascript:;" ng-click="facebook()" class="signup-add-facebook-button" >Connect with Facebook</a>
		<a href="javascript:;" ng-click="signout()" class="signout-button">Sign out</a>
		<div class="divider"></div>
	</div>
</div>