<div ng-show="!order.id">
	order loader
</div>

<div ng-show="order.id">
	<div class="content-padder-before"></div>
	<div class="order-info content-padder main-content-readable">
	
		<span class="order-thanks-message" ng-show="order.new">
			Crunched!
			<span class="order-thanks-message-block">Your order is placed</span>
			<span class="order-thanks-message-small">(and saved for easy 1 click ordering next time)</span>
			<br /><br />
		</span>
	
		<div ng-show="user">
			You can one click order anywhere, including <a href="http://crunchbutton.com">crunchbutton.com</a> on your phone.
		</div>
		<div ng-show="!user">
			<span class="signup-call-to-action">
				Add a password to reorder your favorite food anywhere, including <a href="http://crunchbutton.com">crunchbutton.com</a> on your phone.
				<a href="javascript:;" class="signup-add-password-button">Add a password now</a>
			</span>			
		</div>
	
		<div class="order-details">

			<div ng-show="(order.delivery_type == 'delivery')">
				<b>Your delivery address:</b><br /><span ng-bind-html-unsafe="nl2br(order.address)"></span><br /><br />
			</div>
	
			<div ng-hide="(order.delivery_type == 'delivery')">
				<b>Takeout order</b><br /><br />
			</div>
	
			<b>Your phone #:</b><br />{{formatPhone(order.phone)}}<br /><br />
	
			<b>Your order:</b><span ng-bind-html-unsafe="order._message"></span><br /><br />
	
			<i ng-show="order.notes" ng-bind-html-unsafe="nl2br(order.notes)"><br /><br /></i>
	
			<b ng-show="(order.pay_type == 'card')">Your total:<br /></b>
			<b ng-hide="(order.pay_type == 'card')">Your approximate total:<br /></b>
			
			${{formatPrice(order.charged)}}
	
			<div class="credit" ng-show="(order.credit && order.credit > 0)">( ${{parseFloat(order.final_price).toFixed(2)}} - ${{parseFloat(order.credit).toFixed(2)}} credit )</div>
	
			<br /><br />
	
			For updates on your order, please call<br />{{restaurant.name}}: <b>{{App.callPhone(restaurant.phone)}}</b><br /><br />
	
			You can reach Crunchbutton by texting or calling <b>{{App.callPhone('(646) 783-1444' )}}</b> <br /><br />
	
			We've saved your order for easy 1 click ordering next time

			<div class="facebook-button facebook-button-share clearfix">
				<i class="icon-facebook"></i><span class="facebook-button-text">Share what you ordered</span>
			</div>
	
		</div>
	</div>
	
	<br />
	<a href="/printorder/{{order.uuid}}" class="print-icon" target="_blank"><div class="icon-print"></div> Print Receipt</a>
	<div class="divider"></div>
</div>