<div ng-show="!orders.list">
	Orders loader
</div>
<div ng-show="orders.list" class="main-content-readable">

	<div class="restaurant-item-title">order history</div>

	<ul class="resturant-dishes resturant-dish-container your-orders">
		<li ng-repeat="order in orders.list">
			<span ng-click="orders.restaurant(order._restaurant_permalink)" class="dish-name order-restaurant">
				{{order._restaurant_name}}
			</span>
			<span class="dish-price">
				{{order.timeFormat}} ({{order._tz}})
			</span>
			<a ng-click="orders.receipt(order.id)" class="order-link" href="javascript:;">View Receipt</a>
			<div class="divider"></div>		
		</li>
	</ul>

	<div class="order-options">
		<a ng-show="!account.hasFacebook" href="javascript:;" ng-click="facebook()" class="signup-add-facebook-button" >Connect with Facebook</a>
		<a href="javascript:;" ng-click="signout()" class="signout-button">Sign out</a>
		<div class="divider"></div>
	</div>
</div>