<div class="password-reset-container">
	<div class="password-reset-block">
		<form class="password-reset-form">
			<h1>Password reset</h1>
			<input type="text" maxlength="250" name="password-reset-code" value="<%= code %>" placeholder="enter the reset code" tabindex="10" />
			<div class="divider"></div>
			<div class="password-reset-code-error"></div>
			<a href="javascript:;" class="password-reset-code-button">Reset</a>
			<div class="divider"></div>
		</form>
	</div>
	<div class="password-change-block">
		<form class="password-change-form">
			<h1>Type your new password</h1>
			<input type="password" maxlength="250" name="password-new" value="" placeholder="password" tabindex="10" />
			<div class="divider"></div>
			<div class="password-change-error"></div>
			<a href="javascript:;" class="password-change-button">Change</a>
			<div class="divider"></div>
			<div class="password-change-message"></div>
		</form>
	</div>
</div>
