<div class="referral-container modal zoom-anim-dialog small-container mfp-hide" ng-controller="RewardCtrl">
	<div>
		<div class="success" ng-show="invitedUsers">
			<h1>Congrats</h1>
			<strong>{{invitedUsers}}</strong> just placed an order!
			<br/><br/>
			Get free deliveries for any other new customers you refer ;)
		</div>
		<div class="bottom-links">
			<span class="giftcard-later" ng-click="modal.close();">Great</span>
		</div>
		<div class="divider"></div>
	</div>
</div>
