<div class="top-pad"></div>
<div class="content-padding drivers-apply">
	<div class="apply-item-title text-your-order" name="userForm">
		Brand Representative Application
	</div>
	<p>
		<br>
		We'll get back to you to schedule a quick phone call once we receive your application.<br>
		All fields are required.
		<br><br>
	</p>
	<!--form goes here-->
	<form>

		<div class="form-group">
			<h4><span class="form-required">*</span> First Name:</h4>

			<div class="textbox">
				<div ng-if="errors.firstName">Please enter your first name:</div>
				<input type="text" ng-model="apply.firstName" name="firstName" class="form-control form-control-large">
			</div>
		</div>

		<div class="form-group">
			<h4><span class="form-required">*</span> Last Name:</h4>

			<div class="textbox">
				<div ng-if="errors.lastName">Please enter your last name:</div>
				<input type="text" ng-model="apply.lastName" name="lastName" class="form-control form-control-large" >
			</div>
		</div>

		<div class="form-group">
			<h4><span class="form-required">*</span> Email:</h4>

			<div class="textbox">
				<div ng-if="errors.email">Please enter your email:</div>
				<input type="text" class="form-control form-control-large" ng-model="apply.email" name="email" >
			</div>
		</div>

		<div class="form-group">
			<h4><span class="form-required">*</span> What school are you near?</h4>

			<div class="textbox">
				<div ng-if="errors.university || errors.otherUniversity">Please enter your nearest school:</div>
				<select class="form-control form-control-large form-control form-control-select" ng-model="apply.university" name="university" >
					<option></option>
					<option ng-repeat="community in communities | orderBy: 'name'" value="{{community.name}}">{{community.name}}</option>
					<option ng-model="apply.university" value="Other">Other</option>
					<input ng-click="apply.source='otherU'" ng-if="apply.university=='Other'" class="form-control form-control-small" type="text" ng-model="apply.otherUniversity" name="otherUniversity">

				</select>
			</div>
		</div>

		<div class="form-group">
			<h4><span class="form-required">*</span> Cell Phone Number:</h4>

			<div class="textbox">
				<div ng-if="errors.number">Please enter your number:</div>
				<input type="tel" class="form-control form-control-large" ng-model="apply.number" name="number" >
			</div>
		</div>

		<div class="form-group"></div>


		<div class="form-group">
			<h4><span class="form-required">*</span> Applicant Type:</h4>
			<p>
				<i>Select student if you're a student at the college we're operating at</i>
			</p>

			<div class="textbox">
				<div ng-if="errors.applicant">Please choose student or non-student:</div>
				<br>
				<input type="radio" ng-model="apply.applicant" name="applicant" value="student" id="apply-applicant-student"><label for="apply-applicant-student">Student</label><br>
				<input type="radio" ng-model="apply.applicant" name="applicant" value="non-student" id="apply-applicant-non-student"><label for="apply-applicant-non-student">Non-Student</label><br><br><br>
			</div>
		</div>

		<div class="form-group">
			<h4><span class="form-required">*</span> How did you find out about us?</h4>

			<div class="textbox">
				<div ng-if="errors.source">Please enter how you found out about us:</div>
				<input type="radio" ng-model="apply.source" name="source" value="craigslist" id="apply-source-craigslist"><label for="apply-source-craigslist">Craigslist</label><br>
				<input type="radio" ng-model="apply.source" name="source" value="school-job-list" id="apply-source-school"><label for="apply-source-school">School Job Board</label><br>
				<input type="radio" ng-model="apply.source" name="source" value="friend" id="apply-source-friend"><label for="apply-source-friend">Through a Friend</label><br>
				<input type="radio" ng-model="apply.source" name="source" value="campus-marketing" id="apply-source-marketing"><label for="apply-source-marketing">Marketing on Campus</label><br>
				<input type="radio" ng-model="apply.source" name="source" value="cb-website" id="apply-source-website"><label for="apply-source-website">Via Crunchbutton Website</label><br>
				<input type="radio" ng-model="apply.source" name="source" value="other" id="apply-source-other"><label for="apply-source-other">Other:</label>
				<div ng-if="errors.otherSource">Please specify how you found out about us:</div>
				<input ng-click="apply.source='other'" class="form-control form-control-small" type="text" ng-model="apply.otherSource" name="otherSource">
			</div>
		</div>


		<button class="button lightorange button-bottom " ng-click="post()">Submit</button>

	</form>
</div>
