<div class="top-pad"></div>

<div class="content-padding drivers-apply" ng-show="loaded">

	<div class="apply-item-title text-your-order">
		Welcome to the Crunchbutton Marketing Team! We'll be texting and emailing your shortly!
	</div>

	<br><br><br>

	<div class="apply-item-title text-your-order">
		Share With Friends
	</div>
	<p>
		<br>
		Earn $7 per new customer you refer.
		<br>

		<br>
		<div class="button-refer">

			<div class="hide-desktop button-refer-big">
				<a href="{{sms}}">
					<button class="button lightorange">
						<i class="fa fa-comment"></i>&nbsp;&nbsp;&nbsp;<span>Invite Friends</span>
					</button>
				</a>

				<br><br>
				<br><br>

			</div>

			Share on Facebook:<br><br>
			<button class="button facebook" ng-click="facebook();">
				<i class="fa fa-facebook-square"></i> <span>Share</span>
			</button>

			<br><br>
			<br><br>

			Share on Twitter:<br><br>
			<button class="button twitter" ng-click="twitter()">
				<i class="fa fa-twitter-square"></i> <span>Tweet</span>
			</button>
		</div>

	</p>

</div>
