<div class="top-pad"></div>

<div class="content-padding drivers-apply" ng-show="loaded">

	<div class="apply-item-title text-your-order">
		Share With Friends
	</div>
	<p>

		<br>
		<div class="button-refer">
			Share on Facebook:<br><br>
			<button class="button facebook" ng-click="facebook();">
				<i class="fa fa-facebook-square"></i> <span>Share</span>
			</button>

			<br><br>
			<br><br>

			Share on Twitter:<br><br>
			<button class="button twitter" ng-click="twitter()">
				<i class="fa fa-twitter-square"></i> <span>Tweet</span>
			</button>
		</div>

	</p>

</div>
