<div class="address-incomplete-warning order-warning  zoom-anim-dialog mfp-hide dialog mfp-hide">
	<div class="dialog-padding">
		<b class="order-warning-bold">Confirm your address?</b>
		<p>It looks like your address is incomplete: <br/> {{order.form.address}}</p>
		<div class="divider spacer-one-two"></div>
		<ul>
			<li>
				<div class="button-pushable">
					<button class="button lightorange" ng-click="addressLetMeChangeIt()">
						Add a City or Zip Code
					</button>
				</div>
			</li>
			<li>
				<div class="cursor link" ng-click="addressPlaceAnyway();">Place Order Anyway</div>
			</li>
		</ul>
	</div>
</div>

<div class="address-not-found-warning order-warning  zoom-anim-dialog mfp-hide dialog mfp-hide">
	<div class="dialog-padding">
		<b class="order-warning-bold">Confirm your address?</b>
		<p>We could not find the address: <br/> {{order.form.address}}</p>
		<div class="divider spacer-one-two"></div>
		<ul>
			<li>
				<div class="button-pushable">
					<button class="button lightorange" ng-click="addressLetMeChangeIt()">
						Add a City or Zip Code
					</button>
				</div>
			</li>
			<li>
				<div class="cursor link" ng-click="addressPlaceAnyway();">Place Order Anyway</div>
			</li>
		</ul>
	</div>
</div>


<div class="address-out-of-range-warning order-warning  zoom-anim-dialog mfp-hide dialog mfp-hide">
	<div class="dialog-padding">
		<b class="order-warning-bold">One sec!</b>
		<p>The address <b>{{order.form.address}}</b> is out of delivery range, or you have entered an invalid address.<br/><br/>Please check your address, or order takeout.</p>
		<div class="divider spacer-one-two"></div>
		<ul>
			<li>
				<div class="button-pushable">
					<button class="button lightorange" ng-click="addressLetMeChangeIt()">
						Modify Address
					</button>
				</div>
			</li>
			<li>
				<div class="cursor link" ng-click="addressPlaceAnyway();">Place Order Anyway</div>
			</li>
		</ul>
	</div>
</div>