<div restaurant-is-closed></div>

<!-- cart -->
<div class="cart-items">
	<ng-include src="'/assets/view/restaurant-cart.html'"></ng-include>
</div>

<!-- menu -->
<ng-include src="'/assets/view/restaurant-menu.html'"></ng-include>

<!-- payment and user info -->
<ng-include src="'/assets/view/restaurant-form-user-info.html'"></ng-include>

<!-- stored user info -->
<ng-include src="'/assets/view/restaurant-stored-user-info.html'"></ng-include>