<div class="restaurant-right-bar">

	<div restaurant-is-closed></div>

	<div ng-if="!order.cart.hasItems() && ( open || force_pre_order )" class="restaurant-box hide-mobile">
		<div class="restaurant-box-inner">
			<span class="restaurant-box-icon">
				<i class="fa fa-arrow-left"></i>
			</span>
			<span class="restaurant-box-content">
				<span class="restaurant-box-subtitle restaurant-box-align">{{nothingInTheCartDesktop}}</span>
			</span>
		</div>
	</div>

	<div ng-if="!order.cart.hasItems() && ( open || force_pre_order ) && restaurant.preOrderTimeToTime" class="restaurant-box-pre-order hide-mobile">
		{{restaurant.preOrderTimeToTime}}
	</div>

	<div class="cart-items restaurant-side-bar restaurant-side-bar-margin" ng-if="order.cart.hasItems() && ( open || force_pre_order )">

		<!-- cart -->
		<ng-include src="'/assets/view/restaurant-cart.html'"></ng-include>

		<div ng-if="( restaurant._open || restaurant.force_pre_order ) && order.cart.hasItems()">

			<!-- breakdown -->
			<div class="payment-content">
				<ng-include src="'/assets/view/restaurant-breakdown.html'"></ng-include>
			</div>

		</div>

	</div>

	<!-- payment and user info -->
	<ng-include src="'/assets/view/restaurant-form-user-info.html'"></ng-include>

	<!-- stored user info -->
	<ng-include src="'/assets/view/restaurant-stored-user-info.html'"></ng-include>

</div>

<!-- menu -->
<ng-include src="'/assets/view/restaurant-menu.html'"></ng-include>

<div class="divider"></div>