<div class="restaurant-closed-container zoom-anim-dialog small-container mfp-hide" ng-controller="RestaurantClosedCtrl">
	<div class="signin-form-container">
		<h1 ng-bind="restaurant.name"></h1>
		<p>
			<span ng-if="!acceptingOrders">
				<span ng-if="restaurant.delivery">is temporarily unavailable for delivery, but is usually available during the following hours</span>
				<span ng-if="!restaurant.delivery">is temporarily unavailable but is usually available during the following hours</span>
			</span>
			<span ng-if="acceptingOrders">
				<span ng-if="restaurant.delivery">is currently unavailable for delivery. Delivery will be available:</span>
				<span ng-if="!restaurant.delivery">is currently unavailable. It will be open during the following hours</span>
			</span>
<!--			&nbsp;(<span ng-bind="restaurant._tzabbr"></span>):--><br /><br />
			<span ng-bind-html-unsafe="closedMessage"></span>
		</p>
	</div>
</div>