<span class="tooltip-help-{{type}}-container">

	<span ng-show="type == 'mobile'" class="tooltip-help-mobile-touchable">
		<span class="tooltip-help tooltip-help-mobile" ng-click="show=!show">
			<span>?</span>
		</span>
	</span>

	<span ng-show="type == 'desktop'" class="tooltip-help tooltip-help-desktop" ng-click="show=!show">
		<span>?</span>
	</span>

	<div ng-show="show" class="tooltip-help-content tooltip-help-content-{{type}}">
		We've highlighted the top food from this restaurant below. If you really want something else, contact us at 646-783-1444 and we'll add it right away.
	</div>
</span>