<div class="restaurant-comment" ng-if="restaurant.comment">
	<div class="restaurant-comment-wrap">
		<div class="restaurant-comment-image">
			<div class="restaurant-comment-image-img" style="background: url(https://graph.facebook.com/{{restaurant.comment.fb}}/picture?type=normal)"></div>
		</div>
		<div class="restaurant-comment-content">
			<h4>{{restaurant.comment.user}} says</h4>
			<p>{{restaurant.comment.content}}</p>
		</div>
	</div>
</div>