<? /* --> REMOVED, ONE LESS THING TO WATCH
<div ng-show="!order.loaded">
 THIS WILL SHOW UP WHEN A RESTAURANT PAGE IS DIRECTLY LOADED FROM A BROWSER BEFORE THE PAGE SHOWS.
</div>
*/ ?>


<div ng-show="restaurant">
	<div class="giftcard-badge-container" ng-show="credit.hasValue">
		<div class="giftcard-badge">
			<div ng-click="credit.tooltip=!credit.tooltip" class="giftcard-badge-value">${{credit.value}}</div>
		</div>
		<div class="giftcard-badge-tooltip" ng-show="credit.tooltip">
			You have a <span class="giftcard-value">{{AB.dollar}}{{credit.value}}</span> gift card
		</div>
	</div>

	<div class="restaurant-name">
		<h1>{{restaurant.name}}</h1>
		<div class="giftcard-desktop-container" ng-show="credit.hasValue">
			<div class="giftcard-desktop-message">
				You have a <span class="giftcard-value">{{AB.dollar}}{{credit.value}}</span> gift card
			</div>
		</div>
	</div>

	<div class="restaurant-message">
		<div ng-bind-html-unsafe="restaurant.message" class="restaurant-message-message" ng-show="restaurant.message"></div>
		<div ng-if="restaurant.eta" class="restaurant-message-eta">Delivery estimate: {{restaurant.eta}} minutes</div>
	</div>

	<div ng-show="restaurant.image" class="restaurant-pic-wrapper {{AB.restaurantPage}}">
		<div class="restaurant-pic" style="background: url({{restaurant.img}});"></div>
	</div>

	<div ng-show="restaurant.message || restaurant.eta" class="main-content-readable">
		<div class="restaurant-message-mobile" ng-if="restaurant.eta">Delivery estimate: {{restaurant.eta}} minutes</div>
		<div class="restaurant-message-mobile" ng-bind-html-unsafe="restaurant.message"></div>
	</div>

	<div class="restaurant-closed-mobile" restaurant-is-closed></div>

	<div class="main-content-readable" ng-show="!restaurantLoaded">
		<div class="cart-items {{AB.restaurantPage}}">
			<div class="restaurant-item-title text-your-order">
				Loading
			</div>
		</div>
	</div>

	<div class="main-content-readable" ng-show="restaurantLoaded && !order.loaded">
		<div class="cart-items {{AB.restaurantPage}}">
			<div ng-show="restaurant._open">
				<div class="restaurant-item-title text-your-order">
					Your Order
				</div>
			</div>
		</div>
	</div>

	<!-- main-content-readable-margin -->
	<div class="main-content-readable">

		<!-- cart -->
		<div class="cart-items {{AB.restaurantPage}}" ng-show="order.loaded">
			<div ng-show="restaurant._open">
				<div class="restaurant-item-title text-your-order">
					<br ng-show="restaurant.message || restaurant.eta">
					Your Order
					<span suggestion-tool-tip type="mobile"></span>
				</div>
				<div class="your-order-label" style="font-weight: bold; display: none;">(we've chosen the most popular order, but you can order anything you want)</div>
				<div class="divider"></div>

				<div ng-show="!order.cart.hasItems()" class="order-begin-wrap">
					<div class="order-begin">
						<div class="icon">
							<i class="fa fa-arrow-left hidden-lt-1023"></i>
							<i class="fa fa-arrow-down hidden-gt-1024"></i>
						</div>
						<div class="text">
							<span class="hidden-lt-1023">{{nothingInTheCartDesktop}}</span>
							<span class="hidden-gt-1024">{{nothingInTheCartMobile}}</span>
						</div>
					</div>
					<div class="divider"></div>
				</div>
					<div class="divider"></div>

				<div ng-show="order.info.deliveryMinDiff && order.cart.hasItems()" class="delivery-minimum-error">
					Add $<span class="delivery-min-diff">{{order.info.deliveryMinDiff}}</span> from menu to meet delivery min.
				</div>

				<!-- Cart's basket -->
				<div>

					<div ng-repeat="item in order.cart.items">

						<div class="cart-item cart-item-dish">
							<div class="hidden-desktop">
								<div class="button-orange cart-button cart-button-remove" ng-click="order.cart.remove(item.details.id);"><span class="fa fa-times"></span></div>
							</div>
							<div class="hidden-phone">
								<div class="cart-button cart-button-remove" ng-click="order.cart.remove(item.details.id);"><span class="fa fa-times-circle"></span></div>
							</div>

							<div class="cart-item-name">{{item.details.name}}
								<span class="cart-item-description">{{item.details.description}}</span>
							</div>

							<div ng-if="item.details.customization.customizable" ng-click="item.details.customization.expanded=!item.details.customization.expanded" class="cart-item-config"><a href="javascript:;">Customize</a></div>

						</div>

						<!-- Customizable options -->
						<div class="cart-customize-options" ng-show="item.details.customization.customizable && item.details.customization.expanded">

							<div ng-repeat="option in item.details.customization.options">

								<div class="cart-item-customize-item">

									<div ng-switch on="option.type">

										<!-- Customizable - checkbox -->
										<div ng-switch-when="check">
											<input type="checkbox" custom-checkbox ng-change="order.cart.customizeItem(option, item)" ng-model="option.checked" class="cart-customize-check">
											<a ng-click="option.checked = !option.checked; order.cart.customizeItem(option, item);" class="cart-item-customize-name">{{option.name}}</a>
											<a ng-click="option.checked = !option.checked; order.cart.customizeItem(option, item);" class="cart-item-customize-price">{{option.priceFormated}}</a>
											<div class="divider"></div>
										</div>

										<!-- Customizable - select -->
										<div ng-switch-when="select">
											<label class="cart-item-customize-select-name">{{option.name}}</label>
											<select ng-change="order.cart.customizeItem(option, item)" ng-model="option.selected" ng-options="opt.id_option as opt.name for opt in option.options" class="cart-customize-select"></select>
										</div>

									</div>
								</div>

							</div>
						</div>

					</div>

				</div>
			</div>

			<div class="default-order-check" ng-show="order.info.totalItems && restaurant._open">
				<input custom-checkbox type="checkbox" ng-model="order.form.make_default">
				<a ng-click="order.form.make_default = !order.form.make_default;">Save this order for next time</a>
				<div class="divider"></div>
			</div>

		</div>

		<!-- menu -->
		<div class="restaurant-items">
			<div class="content-item-name content-item-main-name">
				<h1>
					Add to your order
					<span suggestion-tool-tip type="desktop"></span>
				</h1>
			</div>

			<div ng-bind-once ng-repeat="category in restaurant.categories()">
				<div class="restaurant-item-title">{{category.name}}{{category.locName()}}</div>
				<ul class="resturant-dishes resturant-dish-container" date-id_category="{{category.id_category}}">
					<li ng-bind-once ng-repeat="dish in category.dishes()" data-id_dish="{{dish.id_dish}}" add-to-cart class="dish-item">
						<span class="dish-name"><i class="fa fa-star" ng-if="dish.top"></i> {{dish.name}}</span>
						<span class="dish-price">({{AB.dollar}}{{dish.price}}<span ng-if="dish.changeable_price">+</span>)</span>
					</li>
				</ul>
			</div>

			<?php
			/* Remove the suggestion link: Issue #1703
			<div class="suggestion-link-container" ng-controller="RecommendFoodCtrl">
				<div class="suggestion-link-title">Really want something else?</div>
					<a href="javascript:;" ng-click="recommend.modal.open();"><b><i>Suggest other food</i></b></a>
			</div>
			*/
			?>

		</div>
		<div class="divider"></div>
	</div>

	<div class="restaurant-payment-div"></div>

	<div class="restaurant-closed-desktop">
		<div class="is-closet main-content-readable">
			<div restaurant-is-closed></div>
		</div>
	</div>

	<!-- payment and user info -->
	<form class="payment-form main-content-readable" ng-show="order.loaded && order.cart.hasItems() && order.showForm">

		<div ng-show="restaurant._open && order.showForm && order.cart.hasItems()">

			<div class="content-item-name"><h1>Your Info</h1></div>
			<div class="your-info-label">(enter this once, and we'll save it for next time)</div>

			<!-- user info -->
			<div class="delivery-info-container">
				<div ng-show="(restaurant.delivery == '1' && restaurant.takeout == '1')">
					<label class="pay-title-label">Delivery Info</label>

					<div class="input-item toggle-wrapper clearfix">
						<button ng-click="order.toogleDelivery( 'delivery' )" ng-class="{'toggle-active': order.form.delivery_type=='delivery' }" class="toggle-item">delivery</button>
						<span class="toggle-spacer">or</span>
						<button ng-click="order.toogleDelivery( 'takeout' )" ng-class="{'toggle-active': order.form.delivery_type=='takeout' }" class="toggle-item">takeout</button>
					</div>

				</div>

				<div ng-show="(restaurant.delivery == '1' && restaurant.takeout != '1')">
					<label class="pay-title-label">Delivery Info</label>
				</div>

				<div ng-show="(restaurant.delivery != '1' && restaurant.takeout == '1')">
					<label class="pay-title-label">Takeout Info </label>
					<span class="take-out-only">Take out only!</span>
				</div>

				<div class="personal-info field-container">
					<div class="divider"></div>
					<label>Name</label>
					<div class="input-item"><input class="needsclick" type="text" name="pay-name" tabindex="2" ng-model="order.form.name"></div><div class="divider"></div>

					<label>Email</label>
					<div class="input-item"><input class="needsclick" type="text" name="pay-email" tabindex="3" ng-model="order.form.email"></div><div class="divider"></div>

					<label>Phone #</label>
					<div class="input-item">
					<input type="tel" class="needsclick" name="pay-phone" tabindex="4" ng-format-phone ng-model="order.form.phone"></div><div class="divider"></div>

					<label ng-show="order.form.delivery_type=='delivery'">Delivery Address</label>
					<div ng-show="order.form.delivery_type=='delivery'" class="input-item">
					<textarea ng-model="order.form.address" class="needsclick" name="pay-address" id="pay-address" tabindex="5"></textarea></div>
					<div class="divider"></div>

					<div ng-show="(restaurant.id != 74)">
						<label>Notes</label>
						<div class="input-item"><textarea class="needsclick" name="notes" ng-blur="checkGiftCard()" ng-model="order.form.notes" tabindex="6"></textarea></div><div class="divider"></div>
						<div class="divider"></div>

						<!-- Gift card messages -->

						<div class="giftcard-info">

							<div class="warning" ng-show="giftcard.removed">
								You just removed a gift card. If you still want to use that gift card, you must put it back in the notes field.
							</div>

							<div ng-show="restaurant.giftcard == 0 && giftcard.hasGiftCards">
								This restaurant does not accept gift card.
							</div>

							<div ng-show="giftcard.hasValue && order.form.pay_type == 'cash' ">
								Pay with a card, NOT CASH, to use your ${{giftcard.value}} gift card!</span>
							</div>

							<div ng-repeat="success in giftcard.giftcards.success">
								<div ng-if="success.delivery_free && restaurant.delivery == '1' && order.form.delivery_type=='delivery'">
									<span ng-if="order.form.pay_type == 'card'">{{success.message}}</span>
									<span ng-if="order.form.pay_type == 'cash'">Pay with a card, NOT CASH, to get your delivery free</span>
								</div>
							</div>

							<div ng-show="restaurant.giftcard == 1 && order.form.pay_type == 'card' ">
								<!-- Gift card success -->
								<div ng-repeat="success in giftcard.giftcards.success">
									<div ng-if="!success.delivery_free">
										<div ng-show="!success.error && !success.message">
											Congrats! This gift card ({{success.giftcard}}) gives you ${{success.value}}.
										</div>
										<div ng-show="!success.error && success.message">
											{{success.message}}
										</div>
										<div ng-show="success.error == 'other restaurant'">
											The gift card ({{success.giftcard}}) you are trying to use belongs to another restaurant.
										</div>
									</div>
								</div>
								<!-- Gift card errors -->
								<div ng-repeat="error in giftcard.giftcards.error">
									<div ng-switch on="error.error">
										<div ng-switch-when="gift card already used">
											The gift card ({{error.giftcard}}) you are trying to use was already redeemed.
										</div>
										<div ng-switch-when="custom">
											{{error.message}}
										</div>
									</div>
								</div>
							</div>
							<span ng-show="giftcard.justOneGiftCardError">
								You can only use one gift card at a time!
							</span>
						</div>
					</div>

				</div>
			</div>

			<div class="divider"></div>

			<!-- payment info -->
			<div class="payment-info-container">

				<div class="payment-info field-container">

					<label class="pay-title-label">Payment Method</label>
					<div class="input-item toggle-wrapper">
						<button ng-click="order.tooglePayment( 'card' )" ng-show="(restaurant.credit == '1')" ng-class="{'toggle-active': order.form.pay_type=='card' }" class="toggle-item">card</button>
						<span ng-show="(restaurant.credit == '1' && restaurant.cash == '1')" class="toggle-spacer">or</span>
						<button ng-click="order.tooglePayment( 'cash' )" ng-show="(restaurant.cash == '1')"  ng-class="{'toggle-active': order.form.pay_type=='cash' }" class="toggle-item">cash</button>
					</div>

					<div class="divider"></div>

						<div ng-show="order.form.pay_type=='card'" class="payment-card-info"><p>Your credit card information is <br />super secure and encrypted.<br /><br /></p>
							<div class="card-icons">
								<div class="payment-card card-visa payment-card-grey" pre-load-image="/assets/images/payment/card-visa-grey@2x.png" title="visa"></div>
								<div class="payment-card card-master-card" pre-load-image="/assets/images/payment/card-master-grey@2x.png" title="master card"></div>
								<div class="payment-card card-amex" pre-load-image="/assets/images/payment/card-amex-grey@2x.png" title="american express"></div>
								<div class="payment-card card-discover" pre-load-image="/assets/images/payment/card-discover-grey@2x.png" title="discover card"></div>
							</div>
						</div>

						<label ng-show="order.form.pay_type=='card'">Credit card #</label>

						<div ng-show="order.form.pay_type=='card'" class="input-item"><input type="tel" class="needsclick" name="pay-card-number" tabindex="6" ng-change="order.creditCardChanged();" ng-model="order.form.cardNumber"></div><div class="divider"></div>

						<label ng-show="order.form.pay_type=='card'">Expiration</label>
						<div ng-show="order.form.pay_type=='card'" class="input-item">

							<select class="needsclick" ng-change="order.cardInfoChanged()" ng-model="order.form.cardMonth" ng-options="month.value as month.label for month in order._months" tabindex="7">{{order.form.card.month}}</select>

							<select class="needsclick" ng-change="order.cardInfoChanged()" ng-model="order.form.cardYear" ng-options="year.value as year.label for year in order._years" tabindex="8"></select>

							<div class="divider"></div>
						</div>

						<div class="divider"></div>

						<label ng-show="order.form.pay_type=='card'">Tip</label>
						<div ng-show="order.form.pay_type=='card'" class="input-item">

						<input type="hidden" name="pay-autotip-value" ng-model="order.form.autotip" value="0">
						<select ng-model="order.form.tip" ng-options="tip.value as tip.label for tip in order._tips" ng-change="order.tipChanged();" class="tip" tabindex="9"></select>
						<div class="divider"></div>
					</div>
				</div>

			</div>

			<div class="divider"></div>
			<div class="payment-total" ng-show="order.subtotal()">
				You're paying:&nbsp;
				<span ng-show="order.form.pay_type=='cash'">approximately</span>
				&nbsp;{{order.info.breakdownDescription}}&nbsp;
				<span ng-show="order.info.extraCharges">( + {{order.info.extraCharges}} )</span>
				<strong class="cart-gift" ng-show="credit.hasValue && order.form.pay_type == 'card' ">
					<span>
						&nbsp;(-{{AB.dollar}}
						<span ng-show="order.total() <= credit.number">{{order.total()}}</span>
						<span ng-show="order.total() > credit.number">{{credit.value}}</span>
						&nbsp;credit

						<span ng-show="order.info.creditLeft != ''" class="gift-left">
							- You'll still have {{AB.dollar}}{{order.info.creditLeft}} gift card left
						</span> )
					</span>
				</strong>&nbsp;
				for a total of {{order.info.totalText}}
				&nbsp;
				<div ng-show="credit.hasValue && order.form.pay_type == 'cash' ">
					<div class="giftcard-payment-message">Pay with a card, NOT CASH, to use your {{AB.dollar}}{{credit.value}} gift card</div>
				</div>
				&nbsp;
				<span ng-show="order.form.pay_type=='card'">by card</span>
			</div>

			<div ng-show="points.free_delivery_message && restaurant.delivery_service == '1'" >
				<strong ng-if="order.form.pay_type == 'card'">You have {{points.show}} points! This delivery fee is on us.</strong>
				<strong ng-if="order.form.pay_type == 'cash'">Pay with a card, NOT CASH, to get your delivery free.</strong>
			</div>

		</div>

	</form>

	<div ng-show="restaurant._open && order.cart.hasItems()" class="button-bottom-wrapper button-bottom-inline"><button class="button-bottom button-orange" ng-click="order.submit();"><div>Place Order</div></button></div>

	<!-- stored user info -->
	<div class="delivery-payment-info main-content-readable" ng-show="restaurant._open && !order.showForm && order.cart.hasItems()">


		<div ng-show="restaurant.delivery == '1' && order.form.delivery_type=='delivery' && points.free_delivery_message  && restaurant.delivery_service == '1'">
			<strong ng-if="order.form.pay_type == 'card'">You have {{points.show}} points! This delivery fee is on us.</strong>
			<strong ng-if="order.form.pay_type == 'cash'">Pay with a card, NOT CASH, to get your delivery free.</strong>
		</div>


		<div>
			<label>Your phone number:&nbsp;</label>
			<i ng-show="user.phone">{{ user.phone | formatPhone }}</i>
			<i ng-show="!user.phone">no phone # provided</i>
		</div>

		<div ng-show="order.subtotal()">
			<label>You're paying:&nbsp;<span ng-show="order.form.pay_type=='cash'" class="unbold">approximately</span></label>
			&nbsp;{{order.info.breakdownDescription}}&nbsp;
			<span ng-show="order.info.extraCharges">( + {{order.info.extraCharges}} )</span>
			<strong class="cart-gift" ng-show="credit.hasValue && order.form.pay_type == 'card' ">
					<span>
						&nbsp;(-{{AB.dollar}}
						<span ng-show="order.total() <= credit.number">{{order.total()}}</span>
						<span ng-show="order.total() > credit.number">{{credit.value}}</span>
						&nbsp;credit
						<span ng-show="order.info.creditLeft != ''" class="gift-left">
							- You'll still have {{AB.dollar}}{{order.info.creditLeft}} gift card left
						</span> )
					</span>
				</strong>&nbsp;
			for a total of {{order.info.totalText}}
			&nbsp;
				<div ng-show="credit.hasValue && order.form.pay_type == 'cash' ">
					<div class="giftcard-payment-message">Pay with a card, NOT CASH, to use your {{AB.dollar}}{{credit.value}} gift card</div>
				</div>
			&nbsp;
			<span ng-show="order.form.pay_type=='card'">by card</span>
			<span ng-show="order.form.pay_type=='cash' && !credit.hasValue">by cash</span>
		</div>

		<div ng-show="restaurant.delivery == '1' && order.form.delivery_type=='delivery'">
			<label>Your food will be delivered to:</label><br />
			<span ng-bind-html-unsafe="order.form.address | nl2br"></span>
			<i ng-hide="order.form.address">no address provided</i>
		</div>

		<div ng-show="restaurant.takeout == '1' && order.form.delivery_type=='takeout'">
			<label>Delivery Address:</label> <i>takeout</i>
		</div>

		<div ng-show="order.form.notes">
			<label>Notes:&nbsp;</label>
			<i>{{ order.form.notes }}</i>
		</div>

		<div>
			<span class="clickable" ng-click="order.showForm=true">Change delivery or payment details</span>
		</div>

		<div class="divider"></div>

	</div>

</div>
<div class="bottom-spacer"></div>

<div class="address-not-found-warning order-warning modal zoom-anim-dialog small-container mfp-hide">
	<h1>Confirm your address?</h1>
	<p><strong>We could not find the address:<br/>{{order.form.address}}</strong></p>
	<ul>
		<li>
			<div ng-click="addressPlaceAnyway();">Continue</div>
		</li>
		<li>
			<div ng-click="addressLetMeChangeIt();">Add a City or Zip Code</div>
		</li>
	</ul>
</div>

<div class="address-incomplete-warning order-warning modal zoom-anim-dialog small-container mfp-hide">
	<h1>Confirm your address?</h1>
	<p>It looks like your address is incomplete: <br/> {{order.form.address}}</p>
	<ul>
		<li>
			<div ng-click="addressPlaceAnyway();">Continue</div>
		</li>
		<li>
			<div ng-click="addressLetMeChangeIt();">Add a City or Zip Code</div>
		</li>
	</ul>
</div>

<div class="address-out-of-range-warning order-warning modal zoom-anim-dialog small-container mfp-hide">
	<h1>You might be too far for this restaurant :(</h1>
	<p>
		The address <strong>{{order.form.address}}</strong> is more than <strong>{{restaurant.delivery_radius}}</strong> miles from {{restaurant.name}}, or you have entered an invalid addres.
		<br/><br/>
		Please double check you’re not too far away.</p>
	<ul>
		<li>
			<div ng-click="addressOutOfRangePlaceAnyway();">I’m within delivery radius—Place my order anyway</div>
		</li>
		<li>
			<div ng-click="addressLetMeChangeIt();">Modify Address</div>
		</li>
	</ul>
	<p>
		Or try texting customer support at 646-783-1444
	</p>
</div>

