<div class="signin-container zoom-anim-dialog small-container mfp-hide">
	<div class="signin-form-container">	

		<div class="signin-form-options">
			<form class="signin-form">

				<div class="sign-form-links">
					<h1 ng-class="{{account.tab == 'signin' && 'tab-active' || 'link' }}" ng-click="account.setTab('signin')">Sign in</h1>
					<div class="divisor">|</div>
					<h1 ng-class="{{account.tab == 'signup' && 'tab-active' || 'link' }}" ng-click="account.setTab('signup')">Sign up</h1>
					<div class="divider"></div>
				</div>

				<input type="text" maxlength="250" name="signin-email" placeholder="email or phone" tabindex="10" ng-model="account.email">
				<div class="divider"></div>
				<input type="password" maxlength="250" name="signin-password" placeholder="password" tabindex="10" ng-model="account.password">
				<div class="divider"></div>
				<div class="signin-error">
					Your email or password were incorrect.
				</div>
				<a class="signin-password-help" ng-click="account.setHelp(true)">Password help?</a>
				<a href="javascript:;" class="signin-form-button">Log in</a>
				<input type="submit" style="visibility: hidden">
				<div class="divider"></div>
			</form>
			<div class="signin-facebook-container">
				<div class="social-button facebook-button social-button-share">
					<a href="javascript:;" class="signin-facebook-button">
						<span class="signin-facebook-icon"></span>
						<span class="signin-facebook-text">Login with Facebook</span>
						<div class="divider"></div>
					</a>
				</div>
				<div class="signin-facebook-message">
					Just a sec...
				</div>
			</div>
		</div>
		<div ng-show="account.help">
			<form class="signin-help-form">
				<h1>Password help?</h1>
				<input type="text" maxlength="250" name="password-help-email" id="password-help-email" placeholder="email or phone" tabindex="10" ng-model="account.email">
				<div class="divider"></div>
				<div class="password-help-error"></div>
				<a class="signin-password-help-back" ng-click="account.setHelp(false)">Never mind</a>
				<a href="javascript:;" class="signin-password-help-button">Reset</a>
				<div class="divider"></div>
			</form>
			<div class="signin-password-help-message"></div>
		</div>
	</div>

	<div class="signup-container zoom-anim-dialog small-container mfp-hide">
		<div class="signup-form-container">
			<div class="signup-form-options">
				<form class="signup-form">
					<div class="sign-form-links">
						<h1 class="signin signin-link link">Sign in</h1>
						<div class="divisor">|</div>
						<h1 class="active signup">Sign up</h1>
						<div class="divider"></div>
					</div>
					<input type="text" maxlength="250" name="signup-email" placeholder="email address" tabindex="10" />
					<div class="divider"></div>
					<input type="password" maxlength="250" name="signup-password" placeholder="password" tabindex="10" />
					<div class="divider"></div>
					<a href="javascript:;" class="signup-form-button">Sign up</a>
					<div class="divider"></div>
					<div class="signup-error"></div>
				</form>
				<div class="signup-facebook-container">
					<div class="signup-facebook">
						<a href="javascript:;" class="signup-facebook-button">
							<span class="signup-facebook-icon"></span>
							<span class="signup-facebook-text">Signup with Facebook</span>
							<div class="divider"></div>
						</a>
					</div>
					<div class="signup-facebook-message">
						Just a sec...
					</div>
				</div>
			</div>
			<div class="signup-success-container">
				<h1>Congratulations!</h1>
				<div class="signup-success">
					You can now sign in using <strong class="success-phone"></strong>!
				</div>
			</div>
		</div>
	</div>

</div>