<div class="signin-container">
	<div class="signin-form-container">
		<div class="signin-form-options">
			<form class="signin-form">
				<h1 class="signup-link">Sign up</h1>
				<h1>Sign in</h1>
				<input type="text" maxlength="250" name="signin-email" placeholder="email or phone" tabindex="10" />
				<div class="divider"></div>
				<input type="password" maxlength="250" name="signin-password" placeholder="password" tabindex="10" />
				<div class="divider"></div>
				<div class="signin-error">
					Your email or password were incorrect.
				</div>
				<a href="javascript:;" class="signin-password-help">Password help?</a>
				<a href="javascript:;" class="signin-form-button">Log in</a>
				<input type="submit" style="visibility: hidden">
				<div class="divider"></div>
			</form>
			<div class="signin-facebook-container">
				<div class="signin-facebook">
					<a href="javascript:;" class="signin-facebook-button">
						<span class="signin-facebook-icon"></span>
						<span class="signin-facebook-text">Login with Facebook</span>
						<div class="divider"></div>
					</a>
				</div>
				<div class="signin-facebook-message">
					Just a sec...
				</div>
			</div>
		</div>
		<div class="signin-help-container">
			<form class="signin-help-form">
				<h1>Password help?</h1>
				<input type="text" maxlength="250" name="password-help-email" placeholder="email or phone" tabindex="10" />
				<div class="divider"></div>
				<div class="password-help-error"></div>
				<a href="javascript:;" class="signin-password-help-back">Never mind</a>
				<a href="javascript:;" class="signin-password-help-button">Reset</a>
				<div class="divider"></div>
			</form>
			<div class="signin-password-help-message"></div>
		</div>
	</div>
</div>