<div class="signin-container zoom-anim-dialog small-container mfp-hide">
	<div class="signin-form-container">	

		<div class="signin-form-options" ng-hide="account.help">
			<form class="signin-form">
				<!--
				<div class="sign-form-links">
					<h1 ng-class="account.tab == 'signin' ? 'tab-active' : 'link'" ng-tap="account.setTab('signin')">Sign in</h1>
					<div class="divisor">|</div>
					<h1 ng-class="{account.tab == 'signup' ? 'tab-active' : 'link'}" ng-tap="account.setTab('signup')">Sign up</h1>
					<div class="divider"></div>
				</div>
				-->
				<div class="sign-form-links">
					<h1 ng-class="{{account.tab == 'signin' && 'tab-active' || 'link' }}" ng-tap="account.setTab('signin')">Sign in</h1>
					<div class="divisor">|</div>
					<h1 ng-class="{{account.tab == 'signup' && 'tab-active' || 'link' }}" ng-tap="account.setTab('signup')">Sign up</h1>
					<div class="divider"></div>
				</div>

				<input type="text" maxlength="250" name="signin-email" placeholder="email or phone" tabindex="10" ng-model="account.email" autofocus>
				<div class="divider"></div>
				<input type="password" maxlength="250" name="signin-password" placeholder="password" tabindex="10" ng-model="account.password">
				<div class="divider"></div>
				<div class="signin-error">
					Your email or password were incorrect.
				</div>
				<a class="signin-password-help" ng-tap="account.setHelp(true)">Password help?</a>
				<a href="javascript:;" class="signin-form-button">Log in</a>
				<input type="submit" style="visibility: hidden">
				<div class="divider"></div>
			</form>
			<div class="signin-facebook-container">
				<div class="signin-facebook">
					<a href="javascript:;" class="signin-facebook-button">
						<span class="signin-facebook-icon"></span>
						<span class="signin-facebook-text">Login with Facebook</span>
						<div class="divider"></div>
					</a>
				</div>
				<div class="signin-facebook-message">
					Just a sec...
				</div>
			</div>
		</div>
		<div ng-show="account.help">
			<form class="signin-help-form">
				<h1>Password help?</h1>
				<input type="text" maxlength="250" name="password-help-email" placeholder="email or phone" tabindex="10" ng-model="account.email" autofocus>
				<div class="divider"></div>
				<div class="password-help-error"></div>
				<a class="signin-password-help-back" ng-tap="account.setHelp(false)">Never mind</a>
				<a href="javascript:;" class="signin-password-help-button">Reset</a>
				<div class="divider"></div>
			</form>
			<div class="signin-password-help-message"></div>
		</div>
	</div>
</div>