<div class="signup-container">
	<div class="signup-form-container">
		<div class="signup-form-options">
			<form class="signup-form">
				<div class="sign-form-links">
					<h1 class="signin signin-link link">Sign in</h1>
					<div class="divisor">|</div>
					<h1 class="active signup">Sign up</h1>
					<div class="divider"></div>
				</div>
				<input type="text" maxlength="250" name="signup-email" placeholder="email address" tabindex="10" />
				<div class="divider"></div>
				<input type="password" maxlength="250" name="signup-password" placeholder="password" tabindex="10" />
				<div class="divider"></div>
				<a href="javascript:;" class="signup-form-button">Save</a>
				<div class="divider"></div>
				<div class="signup-error"></div>
			</form>
			<div class="signup-facebook-container">
				<div class="signup-facebook">
					<a href="javascript:;" class="signup-facebook-button">
						<span class="signup-facebook-icon"></span>
						<span class="signup-facebook-text">Signup with Facebook</span>
						<div class="divider"></div>
					</a>
				</div>
				<div class="signup-facebook-message">
					Just a sec...
				</div>
			</div>
		</div>
		<div class="signup-success-container">
			<h1>Well done!</h1>
			<div class="signup-success">
				Now you can use your <strong class="success-phone"></strong>!
			</div>
		</div>
	</div>
</div>