<div splash-position-fix class="bg home-top splash-top fixed parallax-bg">
	<div class="splash-spacer-one"></div>
	<div title="Crunchbutton" class="logo animated-resize" ng-click="navigation.home()"></div>
	<div class="splash-spacer-two"></div>

	<div class="about-green-orange-scene noselect" fixed-height="170">
		<div class="splash-bubble-wrap">
			<div class="bubble-curved bubble-curved-white bubble-animated animated-resize">
				<div class="text" ng-switch="splashMessage">
					<span class="single-line" ng-switch-when="1">Hey!!</span>
					<span class="single-line" ng-switch-when="2">Try logging in!</span>
					<span class="single-line" ng-switch-when="3">No, down THERE!</span>
					<span ng-switch-when="4">You are in<br>for a treat</span>
					<span ng-switch-when="5">I can tell you are excited</span>
					<span class="small" ng-switch-when="6">Perhaps too excited to follow directions</span>
					<span class="small" ng-switch-when="7">But the next page is even MORE exciting!</span>
					<span class="single-line" ng-switch-when="8">You can do it!</span>
					<span class="single-line" ng-switch-when="9">I believe in you!</span>
					<span class="single-line" ng-switch-when="10">You are awesome!</span>
					<span class="single-line" ng-switch-when="11">Log in!</span>
					<span class="single-line" ng-switch-when="12">YA!</span>
					<span ng-switch-when="13">There is now cow level.</span>
					<span ng-switch-when="14">Snape kills Dumbledore.</span>
					<span class="small" ng-switch-when="15">Rubber baby buggy bumpers.</span>
					<span class="small" ng-switch-when="16" style="margin-top: 1.2em;">
						<i class="fa fa-arrow-circle-up"></i>
						<i class="fa fa-arrow-circle-up"></i>
						<i class="fa fa-arrow-circle-down"></i>
						<i class="fa fa-arrow-circle-down"></i>
						<i class="fa fa-arrow-circle-left"></i>
						<i class="fa fa-arrow-circle-right"></i>
						<i class="fa fa-arrow-circle-left"></i>
						<i class="fa fa-arrow-circle-right"></i>
						B
						A
					</span>
					<span class="single-line" ng-switch-when="17">@#%*@%&!</span>


					<span class="single-line" ng-switch-when="18"><i class="fa fa-heart"></i> <i class="fa fa-heart"></i> <i class="fa fa-heart"></i></span>
					<span class="single-line" ng-switch-default>Oh, Hello!&nbsp;&nbsp;</span>
				</div>
			</div>
			<div class="bubble-curved-spacer"></div>
		</div>

		<div class="about-green-orange animated-resize" ng-instant="splashMessage = (splashMessage > 17 ? 0 : (splashMessage + 1))" instant-pass-thru></div>
	</div>
	<div class="divider"></div>

	<div class="splash-bottom fixed-599">
		<div class="splash-inputs">
			<p class="splash-tagline">
				<b>We’re Crunchbutton.</b>
				<br>We deliver you the best food from the best restaurants in your community.
			</p>
			<div class="button-pushable">
				<button class="button facebook" ng-click="facebook.auth()">
					<i class="fa fa-facebook-square"></i>&nbsp;
					<span ng-if="!facebook.facebook.wait">Log in with Facebook</span>
					<span ng-if="facebook.facebook.wait">Just a sec
						<div id="circleG">
							<div id="circleG_1" class="circleG"></div>
							<div id="circleG_2" class="circleG"></div>
							<div id="circleG_3" class="circleG"></div>
						</div>
					</span>
				</button>
			</div>

			<p class="center-text">
				<a href="" class="splash-continue" ng-instant="navigation.link('/location','fade')">Continue without logging in</a>
			</p>
		</div>
	</div>

</div>
