<div class="suggestion-container zoom-anim-dialog small-container mfp-hide">
	<div class="suggestion-form-container">
		<form class="suggestion-form">
			<h1>What do you suggest?</h1>
			<input type="text" maxlength="250" name="suggestion-name" tabindex="10" />
			<div class="divider"></div>
			<a href="javascript:;" class="suggestion-form-button">Suggest</a>
			<div class="divider"></div>
		</form>
		<div class="suggestion-message">
		</div>
	</div>
	<div class="suggestion-form-tip">
		Crunchbutton curates menus. <br/>
		We've curated just the top food here. <br/>
		You can suggest food, and, if it's really good, you'll see it on the menu soon.
	</div>
</div>