<div ng-controller="SupportCtrl" class="support-container" ng-show="!App.isMobile()">

	<div class="support-minimized" ng-show="support.minimized" ng-click="support.toggle();">
		<div class="support-icon"></div>
		<div class="support-title">Need help?</div>
		<div class="divider"></div>
	</div>

	<div class="support-maximized" ng-show="support.maximized">

		<div class="support-maximized-header" ng-click="support.toggle();">
			<div class="support-icon"></div>
			<div class="support-title">Question? Comment?</div>
			<div class="divider"></div>
		</div>

		<div class="support-maximized-content">
			<span ng-show="!support.thanks">
				Call us at (646) 783-1444 <br/>or send a message:
			</span>
			<div ng-show="support.thanks">
				Thanks, we'll get back to you as fast as we can.
			</div>
			<div ng-show="!support.thanks">
				<form name="formSupport">
					<label>Name</label>
					<input type="text" maxlength="50" ng-model="support.form.name" name="support-name"/>
					<div class="divider"></div>
					<label>Phone</label>
					<input type="text" maxlength="30" ng-model="support.form.phone" name="support-phone" />
					<div class="divider"></div>
					<label>Message</label>
					<textarea name="support-message" ng-model="support.form.message"></textarea>
					<div class="divider"></div>
					<button ng-show="!support.isSending" class="support-button" ng-click="support.send();">Send by sms</button>
					<div class="divider"></div>
					<i ng-show="support.isSending" class="icon-spinner icon-spin"></i>
				</form>				
			</div>

		</div>

	</div>

</div>