<div class="support-minimized">
	<div class="support-icon"></div>
	<div class="support-minimized-title">Need help?</div>
	<div class="divider"></div>
</div>

<div class="support-maximized">
	<div class="support-maximized-header">
		<div class="support-icon"></div>
		<div class="support-maximized-title">Question? Comment?</div>
		<div class="divider"></div>
	</div>
	<div class="support-maximized-content">
		Call or text us anytime at <br/> (646) 783-1444.
		<div class="divisor"></div>
		<form>
			<label>Name</label>
			<input type="text" maxlength="50" name="support-name"/>
			<div class="divider"></div>
			<label>Phone</label>
			<input type="text" maxlength="30" name="support-phone" />
			<div class="divider"></div>
			<label>Message</label>
			<textarea name="support-message"></textarea>
			<div class="divider"></div>
			<a href="javascript://" class="support-maximized-button">Send by sms</a>
			<div class="divider"></div>
		</form>
	</div>
</div>
