

<div class="content-padding noselect">
	<div class="jobs-bubble-wrap">
		<div class="bubble-curved bubble-curved-green bubble-animated animated-resize">
			<div class="text" ng-switch="orangeMessage">
				<span ng-switch-when="1">Free delivery<br>food</span>
				<span ng-switch-when="2">Free pink gorilla suit</span>
				<span class="single-line" ng-switch-when="3">Free hugs</span>
				<span ng-switch-when="4">Now THOSE are benefits!</span>
				<span ng-switch-when="5">What more could you want?</span>
				<span ng-switch-when="6">Good weather, you say?</span>
				<span ng-switch-when="7">Great people, you say?</span>
				<span ng-switch-when="8">Oh yeah, we got that too!</span>
				<span class="small" ng-switch-when="9">Send us a message and grab a beer with us!</span>
				<span class="single-line" ng-switch-when="10"><i class="fa fa-beer"></i> <i class="fa fa-beer"></i> <i class="fa fa-beer"></i></span>
				<span class="single-line" ng-switch-default><b>Free beer!</b></span>
			</div>
		</div>
	</div>

	<div class="home-join-us" ng-instant="orangeMessage = (orangeMessage > 9 ? 0 : (orangeMessage + 1))" instant-pass-thru></div>
	<div class="divider"></div>
</div>

<br />
<div class="content-padding col-box" ng-controller="SupportCtrl">

	<div class="two-col">
		<h4>Earn Free Food</h4>
		<p>
			Earn points by ordering food, sharing your order, or referring friends.
		</p>
		<br />
		<a href ng-click="navigation.link('/free-food','push')"><button class="button lightorange">Earn Free Food</button></a>
		<br /><br /><br /><br />
	</div>

	<div class="two-col">
		<h4>Delivery Drivers</h4>
		<p>
			What's better than getting delivery food? Delivering the food! If you have a smartphone, car, and auto insurance, send us a message!
		</p>
		<br />
		<a href ng-click="navigation.link('/drivers/apply','push')"><button class="button lightorange">apply now</button></a>
		<br /><br /><br /><br />
	</div>

	<div class="two-col">
		<h4>Community Manager</h4>
		<p>Manages the local team of brand reps to market Crunchbutton and establish us as a local staple.</p>
		<br />
		<a href="mailto:{{resumes}}"><button class="button lightorange">Apply Now</button></a>
		<br /><br /><br /><br />
	</div>


	<div class="two-col">
		<h4>Brand Reps</h4>
		<p>Representatives that work as a team to inform their community about Crunchbutton through flyering, talking to potential customers and leveraging their social media presence.
		</p>
		<br />
		<a href ng-click="navigation.link('/reps/apply','push')"><button class="button lightorange">join up</button></a>
		<br /><br /><br /><br />
	</div>


	<div class="two-col">
		<h4>Developers &amp; Designers</h4>
		<p>Look at this beautiful website! It's almost perfect! You know what would make it better? Your magical touch! Join our small team of developers located in Los Angeles and let's get shit done! More exclamation points!!!</p>
		<br />
		<a href="mailto:{{devs}}"><button class="button lightorange">rock out</button></a>
		<br /><br /><br /><br />
	</div>


	<div class="two-col">
		<h4>Apply to intern for us in LA</h4>
		<p> Looking for a "Jack-of-all-trades" to help us out in all aspects of our business. We're growing at an unbelievable rate, and we want someone interested in getting experience in every department of a growing food delivery company. You'll learn your way around and become an integral part of our operations!</p>
		<br />
		<a href="mailto:{{recruiting}}"><button class="button lightorange">apply now</button></a>
		<br /><br /><br /><br />
	</div>

	<div class="two-col">
		<div>
			<h4>Who are you?!</h4>
			<p>We're people! People who love food so much that we want to share our passion without asking you to even leave your homes.</p>
			<br>
			<button class="button green" ng-click="navigation.link('/about','push')">Meet the team</button>
			<br /><br /><br /><br />
		</div>
	</div>


</div>


