<div class="box">
	<div class="box-header">
		<span class="title">Update</span>
	</div>
	<div class="box-content ">
	
		<form class="fill-up">
		<ul class="box-list">
			<li>
				<span>Fault of</span>
				<span class="pull-right">
					<select name="restaurant" class="uniform">
						<option value="crunchbutton<?= $support->fault_of=='crunchbutton'?' selected':'' ?>">
							crunchbutton
						</option>
						<option value="customer<?= $support->fault_of=='customer'?' selected':'' ?>">
							customer
						</option>
						<option value="restaurant<?= $support->fault_of=='restaurant'?' selected':'' ?>">
							restaurant
						</option>
						<option value="other<?= $support->fault_of=='other'?' selected':'' ?>">
							other
						</option>
					</select>
				</span>
				<div style="clear: both;"></div>
			</li>
			<li>
				<span>User Happy</span>
				<span class="pull-right">
					<input type="checkbox" class="iButton-icons" <?=$this->support->customer_happy ? 'checked' : ''?>>
				</span>
				<div style="clear: both;"></div>
			</li>
			<li>
				<span>Ticket Open</span>
				<span class="pull-right">
					<input type="checkbox" class="iButton-icons" <?=$this->support->status == 'open' ? 'checked' : ''?>>
				</span>
			</li>
			<li class="input">
				<span>Ticket #<? if ($support->id_github) : ?><a href="https://github.com/crunchbutton/crunchbutton/issues/<?=$support->id_github?>"></a><? endif ; ?></span>
				<span class="pull-right">
					<input type="text" placeholder="Github Ticket ID" name="id_github" value="<?=$support->id_github?>">
				</span>
			</li>
		</ul>
		</form>

	
	</div>
</div>