<div class="box">
	<div class="box-header">
		<span class="title">Update</span>
	</div>
	<div class="box-content ">
	
		<form class="fill-up">
		<ul class="box-list">
			<li>
				<span>Fault of</span>
				<span class="pull-right">
					<select name="restaurant" class="uniform">
						<option value="crunchbutton<?= $support->fault_of=='crunchbutton'?' selected':'' ?>">
							crunchbutton
						</option>
						<option value="customer<?= $support->fault_of=='customer'?' selected':'' ?>">
							customer
						</option>
						<option value="restaurant<?= $support->fault_of=='restaurant'?' selected':'' ?>">
							restaurant
						</option>
						<option value="other<?= $support->fault_of=='other'?' selected':'' ?>">
							other
						</option>
					</select>
				</span>
				<div style="clear: both;"></div>
			</li>
			<li>
				<span>User Happy</span>
				<span class="pull-right">
					<input type="checkbox" class="iButton-icons" <?=$this->support->customer_happy ? 'checked' : ''?>>
				</span>
				<div style="clear: both;"></div>
			</li>
			<li>
				<span>Ticket Open</span>
				<span class="pull-right">
					<input type="checkbox" class="iButton-icons" <?=$this->support->status == 'open' ? 'checked' : ''?>>
				</span>
			</li>
			<li class="input">
				<span>Ticket #<? if ($support->id_github) : ?><a href="https://github.com/crunchbutton/crunchbutton/issues/<?=$support->id_github?>"></a><? endif ; ?></span>
				<span class="pull-right">
					<input type="text" placeholder="Github Ticket ID" name="id_github" value="<?=$support->id_github?>">
				</span>
			</li>
			<? if ( $this->support->id_order ) : ?>
			<li>
				<span>Refund</span>
				<span class="pull-right">
					<? if ( $this->support->order()->refunded ): ?>
						<b>Order refunded.</b>
					<? else: ?>
					<a title="Refund" href="javascript://" data-charged="<?php echo $this->support->order()->charged(); ?>" data-gift="<?php if( $this->support->order()->chargedByCredit() > 0 ){ echo $this->support->order()->chargedByCredit(); } else { echo '0'; } ?>" data-uuid="<?=$this->support->order()->uuid?>" class="btn btn-green refund"><i class="icon-reply"></i></a>
					<? endif ?>
				</span>
			</li>
			<li>
				<span>Gift card</span>
				<span class="pull-right">
					<a title="Issue a gift card" href="/giftcards/new?id_user=<?php echo $this->support->order()->user()->id_user; ?>&id_restaurant=<?php echo $this->support->order()->restaurant()->id_restaurant; ?>&id_order_reference=<?php echo $this->support->order()->id_order; ?>" class="btn btn-green"><i class="icon-gift"></i></a>
				</span>
			</li>
		<? endif ?>
		</ul>
		</form>

	
	</div>
</div>