<div class="box">
	<div class="box-header">
		<span class="title">Actions</span>
	</div>
	<div class="box-content padded">
	
		<form method=post action='<?=$this_url?>'>
			<input type=hidden name=action value=support_actions />
	
		<div class=content-sub-item>
			<div class=content-full-width>
				<? if(!$order->id) : ?>
					No Order Linked
				<? elseif($order->id && $order->refunded) : ?>
					Order was Refunded
				<? else : ?>
					<input type=submit class=button name=action_type value='Refund Order' />
				<? endif; ?>
			</div>
		</div>
		<div class=content-sub-item>
			<?
				$giftcard_url = '/giftcards/new?'
					."&id_user=$support->id_user"
					."&id_restaurant=$support->id_restaurant"
					."&id_order_reference=$support->id_order";
			?>
			<a target='_blank' href='<?= $giftcard_url ?>'>
				<div class=content-full-width>
					Issue Gift Card
				</div>
			</a>
		</div>
	
		<div class=content-sub-item>
			<div class=content-full-width>
				<? if($support->id_restaurant) : ?>
					<input type=submit class=button name=action_type value='Unlink Restaurant' />
				<? else : ?>
					<em>id or permalink</em> 
					<input type=text name=id_restaurant /><br>
					<input type=submit class=button name=action_type value='Link Restaurant' />
				<? endif; ?>
			</div>
		</div>
	
		<div class=content-sub-item>
			<div class=content-full-width>
				<? if($support->id_user) : ?>
					<input type=submit class=button name=action_type value='Unlink User' />
				<? else : ?>
					<em>id or phone number</em> 
					<input type=text name=id_user /><br>
					<input type=submit class=button name=action_type value='Link User' />
				<? endif; ?>
			</div>
		</div>
	
		<div class=content-sub-item>
			<div class=content-full-width>
				<? if($support->id_order) : ?>
					<input type=submit class=button name=action_type value='Unlink Order' />
				<? else : ?>
					<em>order id</em> 
					<input type=text name=id_order /><br>
					<input type=submit class=button name=action_type value='Link Order' />
				<? endif; ?>
			</div>
		</div>
	
		</form>
	</div>
</div>