<div class="alert alert-note" style="display:none;">
	<span class="alert-message"></span>
</div>

<div class="box">
	<div class="box-header">
		<span class="title">Add Note</span>
	</div>
	<div class="box-content ">
		<form class="fill-up">
			<ul class="box-list">
				<li class="input add-note-field" style="display:none">
					<textarea name="add-note-text" placeholder="Type your note here" id="add-note-text"></textarea>
				</li>
				<li class="input">
					<button type="button" class="btn btn-green button-add-note"><i class="icon-edit"></i> Add Note</button>
				</li>
			</ul>
		</form>
	</div>
</div>