<?php 
$supports = Crunchbutton_Support::byPhone( $this->support->phone );
$first = true;
?>
<div class="chat-scroll" style="height: 600px;overflow: auto;">
<ul class="chat-box">
	<?php	
	foreach ( $supports as $support ) {
		$messages = $support->messages();
		?>
			<li style="text-align:center;font-size:12px;margin-top:10px;<?php if( !$first ){ ?>border-top:1px solid #CCC;padding:15px;<?php } ?>" id="support-<?php echo $support->id_support;?>">
				<strong><a href="/support/<?php echo $support->id_support; ?>" style="color:#666;">Ticket <?php echo $support->id_support ?> - <?php echo $support->date()->format( 'M jS Y - g:i:s A T' ); ?></a></strong>
			</li>
		<?php
		foreach( $messages as $message ){
			$first = false;
			$date = $message->date();
			switch ( $message->from ) {
				case Crunchbutton_Support_Message::TYPE_FROM_CLIENT:
					?>
						<li class="arrow-box-left">
							<div class="avatar"><img class="avatar-small" src="/assets/images/admin/user.jpg" /></div>
							<div class="info">
								<span class="name"><strong>
									<?php if( $message->name ) { echo $message->name; } else { echo '<i>No name</i>'; } ?>
								</strong> <span class="badge badge-blue">user</span></span>
								<span class="time" title="<?=$date->format('M jS Y - g:i:s A');?>"><?php echo $message->relativeTime( true )?></span>
							</div>
						<?php echo nl2br( $message->body ); ?>
						</li>
					<?php
					break;
				case Crunchbutton_Support_Message::TYPE_FROM_REP:
					switch ( $message->type ) {
						case Crunchbutton_Support_Message::TYPE_SMS:
							?>
							<li class="arrow-box-right gray">
								<div class="avatar"><img class="avatar-small" src="/assets/images/admin/user.jpg" /></div>
								<div class="info">
									<span class="name">
										<strong>
											<?php echo $message->admin()->name; ?>
										</strong> 
										<span class="badge badge-green">SMS</span> <?php if( $message->visibility == 'external' ){ echo '<i class="icon-mobile-phone" title="sms"></i>'; } ?> 
									</span>
									<span class="time" title="<?=$date->format('M jS Y - g:i:s A');?>"><?php echo $message->relativeTime( true ); ?></span>
								</div>
								<?php echo nl2br( $message->body ); ?>
							</li>
							<?php
							break;
						
						case Crunchbutton_Support_Message::TYPE_NOTE:
							?>
							<li class="box-note">
								<div class="info">
									<span class="name">
										<strong>
											<?php echo $message->admin()->name; ?>
										</strong> 
										<span class="badge badge-green">NOTE</span>
									</span>
									<span class="time" title="<?=$date->format('M jS Y - g:i:s A');?>"><?php echo $message->relativeTime( true ); ?></span>
								</div>
								<?php echo nl2br( $message->body ); ?>
							</li>
							<?php
							break;
					}

					?>
					<?php
					break;
				case Crunchbutton_Support_Message::TYPE_FROM_SYSTEM:
					?>
						<li class="box-note-system">
							<div class="info">
								<span class="name">
									<strong>System</strong> 
									<span class="badge badge-gray">Log</span>
									<?php if( $message->visibility == 'external' ){ echo '<i class="icon-mobile-phone" title="sms"></i>'; } ?> 
								</span>
								<span class="time" title="<?=$date->format('M jS Y - g:i:s A');?>"><?php echo $message->relativeTime( true ); ?></span>
							</div>
							<?php echo nl2br( $message->body ); ?>
						</li>
					<?php
					break;
			}
		}
	}
	?>
</ul>
</div>
<script type="text/javascript">
	$( document ).ready( function(){
		setTimeout( function(){
			$('.chat-scroll').animate({scrollTop: $('.chat-box').height() }, 100, $.easing.easeInOutQuart ? 'easeInOutQuart' : null);
		}, 100 );
	} );
</script>