<?
	$this->title = 'Support';
	$this->titleicon = 'comments';
?>

<!-- support page -->
<div class="container-fluid padded">
	<div class="row-fluid">
		<div class="span6">
			<div class="box">
				<div class="box-header"><span class="title">Settings</span></div>

				<div class="box-content">
					<form class="fill-up">
						<ul class="box-list">
							<li class="input">
								<span>Num to call after 1AM</span>
								<span class="pull-right">
									<input type="text" placeholder="" name="support-phone-afterhours" id="support-phone-afterhours" value='<?=c::config()->site->config('support-phone-afterhours')->value?>'>
								</span>
							</li>
							<li class="input">
								<button type="button" class="btn btn-blue button-save-settings">Save changes</button>
							</li>
						</ul>
					</form>
				</div>

			</div>
		</div>
		<div class="span6">
			<div class="box">
				<div class="box-header"><span class="title">Stuff</span></div>
				<div class="box-content padded">
					<a href="/support/new"><button type="submit" class="btn btn-blue new-restaurant">New Support Ticket</button></a>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="container-fluid padded">
	<div class="row-fluid">

		<div class="box">
			<div class="box-header">
				<span class="title">Recent Issues</span>
				<ul class="box-toolbar">
					<li><span class="label label-green"><?=$this->total?> open</span></li>

					<li class="toolbar-link">
						<a href="/support/new" title="Create new"><i class="icon-edit"></i></a>
					</li>
				</ul>
			</div>
			<div class="box-content">
	
				<table cellpadding="0" cellspacing="0" border="0" class="dTable responsive table-normal">
					<thead>
						<tr>
							<? /*
							<td>#</td>
							<td>Date</td>
							<td>Name</td>
							<td>Message</td>
							<td>Status</td>
							<td></td>
							*/ ?>
							<th style="max-width: 80px;"><div>#</div></th>
							<th><div>Date</div></th>
							<th><div>Name</div></th>
							<th><div>Message</div></th>
							<th><div>Status</div></th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						<? foreach ($this->recent as $support): ?>
							<tr>
								<td style="white-space: nowrap;">
									<div style="float: left">#<?=str_pad($support->id_support, 4, '0000', STR_PAD_LEFT)?>&nbsp;&nbsp;&nbsp;</div>
									<div style="float: left"class="btn-group visible-phone hidden-tablet hidden-desktop">
										<a href="/support/<?= $support->id_support ?>"><button class="btn btn-mini btn-blue">View</button></a>
									</div>
								</td>
								<td nowrap><?= $support->repTime()->format('Y-m-d h:i:s')?></td>
								<td nowrap><?=$support->name?></td>
								<td><?=$support->message?></td>
								<td><?=$support->status?></td>
								<td>
									<div class="btn-group">
										<a href="/support/<?= $support->id_support ?>"><button class="btn btn-mini btn-blue">View</button></a>
										<? /* 
										<button class="btn btn-mini btn-blue dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></button>
										<ul class="dropdown-menu">
											<li><a href="#">Close</a></li>
										</ul>
										*/ ?>
									</div>
								</td>
							</tr>
						<? endforeach; ?>
					</tbody>
				</table>
			</div>
		</div>

		
	</div>
</div>
<!-- // end support page -->


<script>
	$(function() {
		$('.button-save-settings').click(function() {
			var self = $(this);
			$(this).attr('disabled','disabled');

			$.ajax({
				type: 'POST',
				url: '/api/siteconfig',
				data: {
					key: 'support-phone-afterhours',
					value: $('[name="support-phone-afterhours"]').val()
				},
				complete: function(data) {
					self.removeAttr('disabled');
				}
			});

		});
	});
</script>
	
