<div class="row-fluid">
	<div class="container-fluid">
		<div class="row-fluid">
			<div class="span12">
				<form>
					<div class="row-fluid">
						<div class="span12">
							<div class="span3">
								<strong>Phone</strong>
							</div>
							<div class="span7">
								<input type="text" name="form-make-call-phone" id="form-make-call-phone"/> 
								<br/><br/>
							</div>
						</div>
					</div>
					<div class="row-fluid">
						<div class="span12">
							<div class="span3">
								<strong>Are you calling to</strong>
							</div>
							<div class="span7">
								<select id="form-make-call-to" name="form-make-call-to">
									<option value="customer">customer</option>
									<option value="driver">driver</option>
									<option value="restaurant">restaurant</option>
								</select>
								<br/><br/>
							</div>
						</div>
					</div>
					<div class="row-fluid">
						<div class="span12">
							<div class="span3"></div>
							<div class="span7">
								<i class="icon-spinner icon-spin form-make-call-spin" style="display:none;"></i>
								<button type="button" onclick="makeCall.start();" class="form-make-call-button btn btn-green"><i class="icon-phone"></i>&nbsp;Call </button> 
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>