<?php 
$name = '';
$phone = '';
?>
<div class="row-fluid">
	<div class="container-fluid">
		<div class="row-fluid">
			<div class="span12" style="height:330px;">
				<form>
					<div class="row-fluid" style="<?php if( $this->id_admin ){ echo 'display:none'; } ?>">
						<div class="span12">
							<div class="span4">
								<strong>Choose an admin/driver</strong>
							</div>
							<div class="span7">
								<select id="form-start-chat-admin" name="form-start-chat-admin" class="chosen-select">
									<option value=""></option>
									<?php foreach( $this->admins as $admin ) { 
										if( $this->id_admin == $admin->id_admin ){
											$name = $admin->name;
											$phone = $admin->phone;
										}
										?>
									<option phone="<?php echo $admin->phone ?>" value="<?php echo $admin->id_admin ?>"><?php echo $admin->name; ?> <?php if( $admin->community != '' ) { echo ' - ' . $admin->community; }; ?></option>
									<?php } ?>
								</select>
								<br/><br/>
							</div>
						</div>
					</div>
					<div class="row-fluid" style="<?php if( $this->id_admin ){ echo 'display:none'; } ?>">
						<div class="span12" style="text-align:center;">
						- or - 
						</div>
					</div>
					<div class="row-fluid">
						<div class="span12">
							<div class="span4">
								<strong>Name</strong>
							</div>
							<div class="span7">
								<input type="text" maxlength="40" value="<?php echo $name; ?>" name="form-start-chat-name" id="form-start-chat-name"/> 
								<br/><br/>
							</div>
						</div>
					</div>
					<div class="row-fluid">
						<div class="span12">
							<div class="span4">
								<strong>Phone</strong>
							</div>
							<div class="span7">
								<input type="text" maxlength="25"  value="<?php echo $phone; ?>" name="form-start-chat-phone" id="form-start-chat-phone"/> 
								<br/><br/>
							</div>
						</div>
					</div>
					<div class="row-fluid">
						<div class="span12">
							<hr/>
						</div>
					</div>
					<div class="row-fluid">
						<div class="span12">
							<div class="span4">
								<strong>Message</strong>
							</div>
							<div class="span7">
								<input type="text" maxlength="140" name="form-start-chat-message" id="form-start-chat-message"/> 
								<br/><br/>
							</div>
						</div>
					</div>
					<div class="row-fluid">
						<div class="span12">
							<div class="span4"></div>
							<div class="span7">
								<i class="icon-spinner icon-spin form-start-chat-spin" style="display:none;"></i>
								<button type="button" onclick="startChat.send();" class="form-start-chat-button btn btn-blue"><i class="icon-mobile-phone"></i>&nbsp;Send </button> 
							</div>
						</div>
					</div>
				</form>

			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
$( function(){
	$( '.chosen-select' ).select2();
	$( '#form-start-chat-admin' ).change( function( event ) {
		var option = $( '#form-start-chat-admin option:selected' );
		$( '#form-start-chat-phone' ).val( option.attr( 'phone' ) );
		$( '#form-start-chat-name' ).val( option.text() );
	} );
} );
</script>