<div class="row-fluid">
	<div class="container-fluid">
		<div class="row-fluid">
			<div class="span12">
				<form>
					<div class="row-fluid">
						<div class="span12">
							<div class="span3">
								<strong>Name</strong>
							</div>
							<div class="span7">
								<input type="text" name="form-start-chat-name" id="form-start-chat-name"/> 
								<br/><br/>
							</div>
						</div>
					</div>
					<div class="row-fluid">
						<div class="span12">
							<div class="span3">
								<strong>Phone</strong>
							</div>
							<div class="span7">
								<input type="text" name="form-start-chat-phone" id="form-start-chat-phone"/> 
								<br/><br/>
							</div>
						</div>
					</div>
					<div class="row-fluid">
						<div class="span12">
							<div class="span3">
								<strong>Message</strong>
							</div>
							<div class="span7">
								<input type="text" maxlength="140" name="form-start-chat-message" id="form-start-chat-message"/> 
								<br/><br/>
							</div>
						</div>
					</div>
					<div class="row-fluid">
						<div class="span12">
							<div class="span3"></div>
							<div class="span7">
								<i class="icon-spinner icon-spin form-start-chat-spin" style="display:none;"></i>
								<button type="button" onclick="startChat.send();" class="form-start-chat-button btn btn-blue"><i class="icon-mobile-phone"></i>&nbsp;Send </button> 
							</div>
						</div>
					</div>
				</form>

			</div>
		</div>
	</div>
</div>