<div class="box">
	<div class="box-header">
		<span class="title">Notes &amp; Log</span>
	</div>

	<div class="box-content chat-box-wrapper">
		<ul class="chat-box">

			<? foreach ($this->support->notes('internal') as $note): ?>
			
				<li class="arrow-box-right gray" id="chat-note-<?=$note->id_support_note?>">
					<div class="avatar"><img class="avatar-small" src="/assets/images/admin/user.jpg" /></div>
					<div class="info">
						<span class="name"><strong><?=$note->from == 'system' ? 'System Note' : $note->from.' '?></strong><span class="badge badge-gray"><?=$note->from?></span></span>
						<span class="time"><?=$note->relativeTime()?></span>
					</div>
					<?=$note->text ?>
				</li>
			<? endforeach ; ?>
		</ul>
	</div>

	<hr class="divider">

	<div class="box-footer flat padded">

		<form method="post" class="support-conversation-reply">
			<input type="hidden" name="rep_name" value="<?=$this->username?>">
			<input type="hidden" name="id_support" value="<?=$this->support->id?>">

			<div class="input-append">
				<input type="text" name="text" placeholder="Enter notes...">
				<ul class="add-on">
					<li>
						<button class="btn btn-blue">Add Note</button>
					</li>
				</ul>
			</div>
		</form>
	</div>

</div>