<?
	$support = $this->support;
	$order = $support->order();



	$this->title = 'Support';
	$this->titleicon = 'comments';
	$this->titleLink = '/support';
	
	$this->title2 = 'Issue #'.$this->support->id_support;
	$this->title2icon = 'warning-sign';

?>



<!-- support page -->
<div class="container-fluid padded">
	<div class="row-fluid">
		<div class="span6">
			<?=$this->display('support/info')?>
		</div>
		<div class="span6">
			<?=$this->display('support/conversation')?>
		</div>
	</div>
	
	<div class="row-fluid">
		<div class="span6">
			<?=$this->display('support/actions')?>
		</div>
		<div class="span6">
			<?=$this->display('support/notes')?>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span6">
			<?=$this->display('support/resolution')?>
		</div>

	</div>
</div>
<!-- // end support page -->



<script>

$(function() {
	var w = $('.chat-box-wrapper');
	w.stop().animate({ scrollTop: w[0].scrollHeight }, 800);
	
	$('.support-conversation-reply').submit(function(e) {
		e.preventDefault();
		e.stopPropagation();
		var i = $(this).find('[name="text"]');
		var val = i.val();
		i.val('Sending...');
		i.prop('enabled',false);
		
		$.post('/support/' + $(this).find('[name="id_support"]').val() + '/conversation', {
			text: val
		}, function(res) {
			i.prop('enabled',true);
			i.val('');
			w.find('.chat-box').append(res);
			w.stop().animate({ scrollTop: w[0].scrollHeight }, 800);
		});
		return;
	});
});
</script>