<?php
$support = $this->support;
?>

<div class="alert alert-update" style="display:none;">
	<span class="alert-message"></span>
</div>

<div class="box">
	<div class="box-header">
		<span class="title">Resolution</span>
	</div>
	<div class="box-content">
		<form class="fill-up">
			<ul class="box-list">
				<li>
					<span>Ticket Open</span>
					<span class="pull-right">
						<input type="checkbox" id="status" name="status" class="iButton-icons" <?=$support->status == 'open' ? 'checked' : ''?>>
					</span>
				</li>
				<?php
				if( $support->permissionToEdit() ) { ?>
				<li class="input">
					<button type="button" class="btn btn-blue button-update">Save changes</button>
				</li>
				<?php } ?>
			</ul>
		</form>
	</div>
</div>