<html>
<style>
	body, td {
		font-size: 14px;
	}
	h1 {
		font-size: 19px;
	}
	h2 {
		font-size: 14px;
		margin-bottom: 0;
		margin-top: .25em;
	}
	.customer td {
		font-size: 12px;
	}
	td {
		border: 0;
		border-right: 1px solid #bbb;
		border-bottom: 1px solid #bbb;
		padding: 5px;
	}
	table {
		border-top: 1px solid #bbb;
		border-left: 1px solid #bbb;
	}
</style>
<body style="font-family:Helvetica,Arial">

<?=$this->content?>

</body>
</html>