<table class="list-orders">
	<tr>
		<th class="list-order-header">Date / ID</th>
		<th class="list-order-header">Restaurant</th>
		<th class="list-order-header">Order</th>
		<th class="list-order-header">Price</th>
		<th class="list-order-header">Pay Type</th>
		<th class="list-order-header">Order Type</th>
		<th class="list-order-header">Customer</th>
	</tr>
	<? foreach (Order::recent() as $order) : ?>
		<tr class="list-order-item">
			<td>
				<table>
					<tr><td><b>Date</b>: <?=$order->date?></td></tr>
					<tr><td><a href="/vieworder/<?=$order->uuid?>"><?=$order->uuid?></a></td></tr>
				</table>
			</td>
			<td><?=$order->restaurant()->name?></td>
			<td style="width: 300px; white-space: normal;">
				<ul>
				<? foreach ($order->dishes() as $dish) : ?>
					<li>
						<?=$dish->dish()->name?>
						<? if ($dish->options()->count()) : ?>
							<ul>
							<? foreach ($dish->options() as $option) : ?>
								<li><?=$option->option()->name?></li>
							<? endforeach ; ?>
							</ul>
						<? endif ; ?>
					</li>
				<? endforeach ; ?>
				</ul>
			</td>
			<td>
				<table>
					<tr>
						<th>Subtotal</th>
						<td>$<?=$order->price?></td>
					</tr>
					<tr>
						<th>Tax</th>
						<td>$<?=$order->tax?></td>
					</tr>
					<tr>
						<th>Tip</th>
						<td><?=$order->tip ? $order->tip.'%' : ''?></td>
					</tr>
					<tr>
						<th>Total</th>
						<td>$<?=$order->final_price?></td>
					</tr>
				</table>
			</td>
			<td><?=$order->pay_type?></td>
			<td><?=$order->delivery_type?></td>
			<td>
				<table>
					<tr>
						<th>Name</th>
						<td><?=$order->name?></td>
					</tr>
					<tr>
						<th>Phone</th>
						<td><?=$order->phone?></td>
					</tr>
					<tr>
						<th>Address</th>
						<td><?=$order->address?></td>
					</tr>
				</table>
			</td>
		</tr>
	<? endforeach ; ?>
</table>