<table class="list-orders">
	<tr>
		<th class="list-order-header">Info</th>
		<th class="list-order-header">Date</th>
		<th class="list-order-header">Restaurant</th>
		<th class="list-order-header">Order</th>
		<th class="list-order-header">Price</th>
		<th class="list-order-header">Pay Type</th>
		<th class="list-order-header">Order Type</th>
		<th class="list-order-header">Customer</th>
	</tr>
	<? foreach (Order::recent() as $order) : ?>
		<? $date = new DateTime($order->date); ?>
		<tr class="list-order-item">
			<td>
				<table>
					<tr><td><b>ID</b></td><td>#<?=$order->id?></td></tr>
					<tr><td><b>UUID</b></td><td><a href="/vieworder/<?=$order->uuid?>"><?=$order->uuid?></a></td></tr>
					<tr><td><b>Environment</b></td><td><?=$order->env?></td></tr>
					<tr><td><br />
						<? if ($order->refunded) : ?>
							REFUNDED
						<? else : ?>
							<a href="javascript:;" class="refund" data-uuid="<?=$order->uuid?>">REFUND</a></td></tr>
						<? endif ; ?>
				</table>
			</td>
			<td>
				<?=$date->format('Y-m-d')?><br /><?=$date->format('H:i:s')?>
			</td>
			<td><?=$order->restaurant()->name?></td>
			<td style="width: 300px; white-space: normal;">
				<ul>
				<? foreach ($order->dishes() as $dish) : ?>
					<li>
						<?=$dish->dish()->name?>
						<? if ($dish->options()->count()) : ?>
							<ul>
							<? foreach ($dish->options() as $option) : ?>
								<li><?=$option->option()->name?></li>
							<? endforeach ; ?>
							</ul>
						<? endif ; ?>
					</li>
				<? endforeach ; ?>
				</ul>
			</td>
			<td>
				<table>
					<tr>
						<th>Subtotal</th>
						<td>$<?=$order->price?></td>
					</tr>
					<tr>
						<th>Tax</th>
						<td>$<?=$order->tax?></td>
					</tr>
					<tr>
						<th>Tip</th>
						<td><?=$order->tip ? $order->tip.'%' : ''?></td>
					</tr>
					<tr>
						<th>Total</th>
						<td>$<?=$order->final_price?></td>
					</tr>
				</table>
			</td>
			<td><?=$order->pay_type?></td>
			<td><?=$order->delivery_type?></td>
			<td>
				<table>
					<tr>
						<th>Name</th>
						<td><?=$order->name?></td>
					</tr>
					<tr>
						<th>Phone</th>
						<td><?=$order->phone?></td>
					</tr>
					<tr>
						<th>Address</th>
						<td><?=$order->address?></td>
					</tr>
				</table>
			</td>
		</tr>
	<? endforeach ; ?>
</table>

<script>
	$(function() {
		$('.refund').live('click',function() {
			if (!confirm('Are you sure you want to refund this?')) {
				return;
			}
			var el = $(this);
			$.getJSON('/api/order/' + $(this).attr('data-uuid') + '/refund',function(json) {
				el.replaceWith('REFUNDED');
			});
		});
	});
</script>