<div class="top-pad"></div>

<div class="content-padding">

	<div class="support-boxes">

		<div class="support-box-wrap box-content2">
			<div class="support-box-wrap-header">
				<h1><i class="fa fa-wrench"></i>Tools</h1>
				<div class="divider"></div>
			</div>

			<div class="box-content-table">
				<table>
					<tr><td><a href="/pexcard/">Pex Card</a></td></tr>
					<tr><td><a href="/support/phone">Make a call / Send SMS</a></td></tr>
					<tr><td><a href="/blast">Blasts</a></td></tr>
					<tr><td><a href="/marketing/outgoing">Marketing: Outgoing Emails/Texts</a></td></tr>
					<tr><td><a href="/reports">Reports</a></td></tr>
					<tr><td><a href="/tools/eta">Smart ETA</a></td></tr>
					<tr><td><a href="/restaurants/weight-adjustment">Restaurants: Weight Adjustment</a></td></tr>
					<tr><td><a href="/disputes">Disputes</a></td></tr>
					<tr><td><a href="/blockeds">Blocked Customers/Phones</a></td></tr>
					<tr><td><a href="/delivery-signups">Delivery Sign Ups</a></td></tr>
					<tr><td><a href="/communities/closed">Closed Communities</a></td></tr>
				</table>
			</div>
		</div>

		<div class="support-box-wrap box-content2">
			<div class="support-box-wrap-header">
				<h1><i class="fa fa-cog"></i>Config</h1>
				<div class="divider"></div>
			</div>

			<div class="box-content-table">
				<table>
					<tr><td><a href="/config/auto-reply">Auto Reply - Customer Service</a></td></tr>
					<tr><td><a href="/config/rewards">Customer Rewards</a></td></tr>
					<tr><td><a href="/config/rules">Order Rules</a></td></tr>
					<tr><td><a href="/groups">Groups</a></td></tr>
					<tr><td><a href="/config/blocked">Blocked Customers/Phones Message</a></td></tr>
					<tr><td><a href="/config/live">Live Stuff</a></td></tr>
					<tr><td><a href="/config/cs-calls">Customer Service Calls</a></td></tr>
				</table>
			</div>
		</div>

		<div class="support-box-wrap box-content2">
			<div class="support-box-wrap-header">
				<h1><i class="fa fa-wrench"></i>CMS</h1>
				<div class="divider"></div>
			</div>

			<div class="box-content-table">
				<table>
					<tr><td><a href="/quotes/">Quotes</a></td></tr>
				</table>
			</div>
		</div>

		<div class="support-box-wrap box-content2">
			<div class="support-box-wrap-header">
				<h1><i class="fa fa-volume-up"></i>Notifications</h1>
				<div class="divider"></div>
			</div>
			<div class="box-content-table">
				<table>
					<tr><td><a href="/config/community-open">When community is opened by a driver</a></td></tr>
				</table>
			</div>
		</div>

		<div class="support-box-wrap box-content2">
			<div class="support-box-wrap-header">
				<h1><i class="fa fa-github-alt"></i>Version</h1>
				<div class="divider"></div>
			</div>

			<div class="box-content-table">
				<table>
					<tr><td>
						<a href="https://github.com/crunchbutton/crunchbutton/commit/{{bundle}}">{{bundle}}</a>
					</td></tr>
				</table>
			</div>
		</div>

	</div>
</div>
