<div class="top-pad"></div>

<div class="content-padding">

	<h1 class="title"><i class="fa fa-wrench"></i>Tools</h1>
	<div class="box-content2 box-content-table">
		<table>
			<tr><td><a href="/pexcard/card">Assign Pex Card to Driver</a></td></tr>
			<tr><td><a href="/support/phone">Make a call / Send SMS</a></td></tr>
			<tr><td><a href="/blast">Blasts</a></td></tr>
		</table>
	</div>

	<h1 class="title"><i class="fa fa-cog"></i>Config</h1>
	<div class="box-content2 box-content-table">
		<table>
			<tr><td><a href="/config/rewards">Customer Rewards</a></td></tr>
			<tr><td><a href="/pexcard/config">Pex Card Settings</a></td></tr>
		</table>
	</div>

</div>
