<?php 
$groups = $this->groups;
?>
<?php if (!$groups->count()) { ?>
	No results found
<?php } else { ?>
	<table class="table table-normal">
		<thead>
			<td>Name</td>
			<td>Description</td>
			<td>Number of users in this group</td>
			<td></td>
		</thead>
		<?php foreach ( $groups as $group ) { ?>
			<?php  
			// verify if it is an system group
			$pos = strrpos( $group->name, Crunchbutton_Group::DRIVER_GROUPS_PREFIX );
			?>
			<tr <?php if( $pos !== false ){ echo 'class="driver-group"'; } ?>>
				<td><?php echo $group->name;?> </td>
				<td><?php echo $group->description;?> </td>
				<td><?php echo $group->usersTotal();?> 

				</td>
				<td style="width:280px;">
					<?php if( $pos === false ) { ?>
						<a href="/permissions/groups/permissions/<?php echo $group->id_group; ?>" class="btn btn-blue"><i class="icon-unlock"></i> Permissions</a>
						&nbsp;
						<a href="/permissions/groups/<?php echo $group->id_group; ?>" class="btn btn-green"><i class="icon-edit"></i> Edit</a>
					<?php } else { ?>
						<i style="font-size:11px;">This group could not be modified</i>
					<?php } ?>
					&nbsp;
						<button data-id="<?php echo $group->id_group; ?>" class="btn group-remove btn-red"><i class="icon-trash"></i> Remove</button>
				</td>
			</tr>
		<?php } ?>
	</table>
<?php } ?>