<?php 
$groups = $this->groups;
?>
<?php if (!$groups->count()) { ?>
	No results found
<?php } else { ?>
	<table class="table table-normal">
		<thead>
			<td>Name</td>
			<td>Number of users at this group</td>
			<td></td>
		</thead>
		<?php foreach ( $groups as $group ) { ?>
			<tr>
				<td><?php echo $group->name;?> </td>
				<td><?php echo $group->usersTotal();?> </td>
				<td style="width:280px;">
					<a href="/permissions/groups/permissions/<?php echo $group->id_group; ?>" class="btn btn-blue"><i class="icon-unlock"></i> Permissions</a>
					&nbsp;
					<a href="/permissions/groups/<?php echo $group->id_group; ?>" class="btn btn-green"><i class="icon-edit"></i> Edit</a>
					&nbsp;
					<button data-id="<?php echo $group->id_group; ?>" class="btn group-remove btn-red"><i class="icon-trash"></i> Remove</button>
				</td>
			</tr>
		<?php } ?>
	</table>
<?php } ?>