<?
	$this->title = 'Permissions';
	$this->titleicon = 'lock';
	$this->titleLink = '/permissions/groups';
	
	$this->title2 = 'Groups';
	$this->title2icon = 'group';

	$group = $this->group;

?>
<div class="container-fluid padded">
	<div class="row-fluid">
		<div class="span6">
			<div class="box">
				<div class="box-header">
					<span class="title">Group</span>
				</div>
				<div class="box-content ">
					<ul class="box-list">
						<li>
							<span>Name</span>
							<span class="pull-right">
								<input type="text" name="name" maxlength="40" id="name" value="<?php echo $group->name; ?>" />
								<div class="note">Please don't use spaces-use dashes instead!</div>
							</span>
						</li>
						<li>
							<span>Description</span>
							<span class="pull-right">
								<input type="text" name="description" maxlength="250" id="description" value="<?php echo $group->description; ?>" />
							</span>
						</li>
						<li class="input">
							<button type="submit" class="btn btn-green admin-save"><i class="icon-save"></i> Save </button> 
						</li>
					</ul>
			</div>
			</div>
		</div>
		<div class="span6">
		<?php if( $group->usersTotal() > 0 ) { ?>
			<div class="box">
				<div class="box-header">
					<span class="title">Users</span>
				</div>
				<div class="box-content ">
					<ul class="box-list">
						<?php 
						$users = $group->users();
						foreach( $users as $user ){
						?>
							<li>
								<span>
									<a href="/permissions/users/<?php echo $user->id_admin; ?>">
										<?php echo $user->name; ?>
									</a>
								</span>
								<span class="pull-right">
									<a href="/permissions/users/<?php echo $user->id_admin; ?>" style="text-decoration:underline;">
										<?php echo $user->login; ?>
									</a>
								</span>
							</li>
						<?php } ?>
					</ul>
				</div>
			</div>
		<?php } ?>
		<?php if( $group->id_group ) { ?>
			<div class="box">
				<div class="box-header">
					<span class="title">Permissions</span>
				</div>
				<div class="box-content ">
					<ul class="box-list">
						<li>
							<a href="/permissions/groups/permissions/<?php echo $group->id_group; ?>" class="btn btn-blue"><i class="icon-unlock"></i> Edit Permissions of this group</a>
						</li>
					</ul>
				</div>
			</div>
			<?php } ?>
		</div>
	</div>
</div>
<script>

$(function() {
	$(document).on('click', '.admin-save', function() {
		sendForm();
	} );
});

var processing = false;

function sendForm(){

	if( processing ){
		return;
	}

	var name = $.trim( $( '#name' ).val() );
	var description = $.trim( $( '#description' ).val() );
	
	if( name == '' ){
		alert( 'Please type a name!' );
		$( '#name' ).focus();
		return;
	}

	var data = { 'name' : name, 'description' : description };
	
	processing = true;
	
	$( '.admin-save' ).html( '<i class="icon-spinner icon-spin"></i> Please wait' );

	var url = App.service + 'permissions/groups/<?php echo $group->id_group; ?>';
	$.ajax({
		type: "POST",
		dataType: 'json',
		data: data,
		url: url,
		success: function( json ) {
			processing = false;
			if( json.error ){
				alert( 'Error at saving the group!' );
				$( '.admin-save' ).html( '<i class="icon-save"></i> Save ' );
			} else {
				alert( 'Group saved!' );
				<?php if( $group->id_group ) { ?>
				location.href = '/permissions/groups/';
				<?php } else { ?>
				location.href = '/permissions/groups/permissions/' + json.success + '/new';
				<?php } ?>
			}
		},
		error: function( ){
			processing = false;
			alert( 'Error at saving the group!' );
			$( '.admin-save' ).html( '<i class="icon-save"></i> Save ' );
		}
	});
}
</script>