<?
	$this->title = 'Permissions';
	$this->titleicon = 'lock';
	$this->titleLink = '/permissions';
	
	$this->title2 = 'Groups';
	$this->title2icon = 'group';

?>
<!-- content -->
<div class="container-fluid padded">
	 <div class="row-fluid">
			<div class="box">
				 <div class="box-content">
						<div class="row-fluid">
							<div class="span6 separate-sections">
								 <ul class="padded separate-sections">
										<li class="input">
											 <input class="span12" name="name" type="text" value="<?=strip_tags($_REQUEST['name'])?>" placeholder="Name">
										</li>
								 </ul>
							</div>
							<div class="span6 separate-sections">
								 <ul class="padded separate-sections">
										<li><button class="btn btn-blue admin-group-search"><i class="icon-search"></i>&nbsp;&nbsp;&nbsp; Search </button> 
											 <a href="/permissions/groups/new" class="btn btn-green admin-group-new"><i class="icon-group"></i>&nbsp;&nbsp;&nbsp; New Group </a> 
										</li>
								 </ul>
							</div>
						</div>
				 </div>
			</div>
			<div class="box">
				 <div class="box-header"><span class="title">Results</span></div>
				 <div class="box-content">
						<div class="permissions-loader">
							 <center><i class="icon-spinner icon-spin" style="font-size: 50px;"></i></center>
						</div>
						<div class="permissions-content"></div>
				 </div>
			</div>
	 </div>
</div>
<script>

	$(function() {		

		$(document).on('click', '.admin-group-search', function() {
			App.permissions.group.load();
		} );

		$(document).on('keyup', '[name="name"]', function( e ) {
			if (e.which == 13) {
				App.permissions.group.load();
			}
		} );

		App.permissions.group.load();

		$(document).on('click', '.group-remove', function() {
			var button = $( this );
			if( confirm( 'Confirm? This action remove the group!' ) ){
				var id_group = button.attr( 'data-id' );
				App.permissions.group.remove( id_group );
			} 
		} );

	});
</script>