<?
	 $this->title = 'Permissions';
	 $this->titleicon = 'lock';
	 $this->titleLink = '/permissions/groups';
	 
	 $this->title2 = 'Groups permissions';
	 $this->title2icon = 'group';
	 
	 $group = $this->group;
	 $_permissions = $this->permissions;
	 $_elements = $this->elements;
	 
	 ?>
<div class="container-fluid padded">
	 <h2>Permissions of Group <?php echo $group->name ?></h2>
</div>
<div class="container-fluid padded">
	 <div class="row-fluid">
			<div class="span6">
				<?php 
					foreach( $_permissions as $permission_group ){ 
						$description = $permission_group[ 'description' ];
						$permissions = $permission_group[ 'permissions' ];
				?>
					 <div class="box">
							<div class="box-header">
								 <span class="title">
								 <?php echo $description; ?>
								 </span>
							</div>
							<div class="box-content ">
								 <ul class="box-list">
								 	<?php
								 		foreach( $permissions as $permission => $meta ){
								 			$description = $meta[ 'description' ];
								 			$type = 'checkbox';
								 			$element = '';
								 			switch ( $meta[ 'type' ] ) {
								 				case 'combo':
								 					$type = 'combo';
								 					$element = $meta[ 'element' ];
								 					break;
								 				
								 				default:
								 					$type = 'checkbox';
								 					break;
								 			};
								 	?>
										<li>
											<label for="<?php echo $description; ?>">
												<?php if( $type == 'checkbox' ) { 
													$checked = ( $group->hasPermission( $permission ) ) ? 'checked="checked"' : '' ;
													?>
													<input type="checkbox" <?php echo $checked; ?> class="permissions" value="1" name="<?php echo $permission; ?>" id="<?php echo $permission; ?>">
												<?php } ?>
												&nbsp;<?php echo $permission; ?>
												<span class="note">
													&nbsp;(<?php echo $description; ?>)
												</span>
												<?php if( $type == 'combo' ) { ?>
													<select id="<?php echo $permission; ?>" class="chzn-select permissions" multiple name="<?php echo $permission; ?>" data-placeholder="Choose" style="width:100%;">
														<?php 
														$elements = $_elements[ $element ];
														foreach ( $elements as $element ) { 
															$value = str_replace( 'ID' , $element->id, $permission);
															$selected = ( $group->hasPermission( $value ) ) ? 'selected="selected"' : '' ;
															?>
															<option <?php echo $selected; ?> value="<?php echo $value; ?>"><?php echo $element->name; ?></option>
														<? } ?>
													</select>
												<?php } ?>
											</label>
										</li>
									<?php 
										} 
									?>
									<li class="input">
										<button type="submit" class="btn btn-blue admin-save"><i class="icon-save"></i> Save </button> 
									</li>
								 </ul>
							</div>
					 	</div>
				 <?php 
				 	} 
				?>
			</div>
	 </div>
</div>
<script type="text/javascript">
	
	$(function() {
		$(document).on('click', '.admin-save', function() {
			sendForm();
		} );
	});

	function sendForm(){
		
		var data = {};

		$('.permissions').each( function(){ 
			var el = $( this );
			var type = null;
			if( el.is( 'input' ) ){
				type = el.attr( 'type' );
				if( type == 'checkbox' ){
					if( el.is( ':checked' ) ){
						data[ el.attr( 'name' ) ] = 1;
					}
				}
			} else if( el.is( 'select' ) ){
				var options = el.val();
				$( options ).each( function( index, val ){
					data[ val ] = 1;
				} );
			}

		} );
		
		var url = App.service + 'permissions/groups/<?php echo $group->id_group; ?>/permissions';
		$.ajax({
			type: 'POST',
			dataType: 'json',
			data: { permissions : data },
			url: url,
			success: function( json ) {
				processing = false;
				if( json.success ){
					alert( 'Permssions saved!' );
					location.reload();
				} else {
					alert( 'Error saving permissions!' );
				}
			},
			error: function( ){
				processing = false;
				alert( 'Error at saving the user!' );
				$( '.admin-save' ).html( '<i class="icon-save"></i> Save ' );
			}
		});

	}


</script>
