<?
	$this->title = 'Permissions';
	$this->titleicon = 'lock';
	$this->titleLink = '/permissions/groups';

	$this->title2 = 'Groups permissions';
	$this->title2icon = 'group';

	$group = $this->group;
	$_permissions = $this->permissions;
	$_elements = $this->elements;

?>
<div class="container-fluid padded">
	 <div class="row-fluid">
			<div class="span6">
				<h4>
					Permissions of Group <?php echo $group->name ?>
			</h4>
				<?php 
					foreach( $_permissions as $_group => $permission_group ){ 
						$description = $permission_group[ 'description' ];
						$permissions = $permission_group[ 'permissions' ];
						$doAllPermission = $permission_group[ 'doAllPermission' ];
				?>
					 <div class="box box-<?php echo $_group; ?> permission-box">
							<div class="box-header">
								 <span class="title">
								 <?php echo $description; ?>
								 </span>
							</div>
							<div class="box-content ">
								 <ul class="box-list">
								 	<?php
								 		foreach( $permissions as $permission => $meta ){
								 			$description = $meta[ 'description' ];
								 			$type = 'checkbox';
								 			$element = '';
								 			switch ( $meta[ 'type' ] ) {

								 				case 'combo':
								 					$type = 'combo';
								 					$element = $meta[ 'element' ];
								 					break;
								 				
								 				default:
								 					$type = 'checkbox';
								 					break;
								 			};
											$isPermissionFather = false;
											if( $doAllPermission ){
												$isPermissionFather = ( $doAllPermission == $permission );
											}
								 	?>
										<li class="permission-row row-<?php echo $permission; ?> <?php if( $isPermissionFather ) { ?>row-father-<?php echo $doAllPermission;?><?php } else { ?>row-child-<?php echo $doAllPermission;?><?php } ?>">
											<label for="<?php echo $permission; ?>">
												<?php if( $type == 'checkbox' ) { 
													$checked = ( $group->hasPermission( $permission ) ) ? 'checked="checked"' : '' ;
													?>
													<span class="pull-right">
														<input type="checkbox" <?php echo $checked; ?> class="icheck permissions <?php if( $isPermissionFather ) { ?>do-all-father <?php } ?>" family-name="<?php echo $doAllPermission;?>" value="1" name="<?php echo $permission; ?>" id="<?php echo $permission; ?>">
													</span>
												<?php } ?>
												&nbsp;<?php echo $description; ?>
												<span class="note">
													&nbsp;(<?php echo $permission; ?>)
												</span>
												<?php if( $type == 'combo' ) { ?>
													<select id="<?php echo $permission; ?>" class="permission-input permissions chosen" multiple name="<?php echo $permission; ?>" data-placeholder="Choose" style="width:100%;">
														<?php 
														$elements = $_elements[ $element ];
														foreach ( $elements as $element ) { 
															$value = str_replace( 'ID' , $element->id, $permission);
															$selected = ( $group->hasPermission( $value ) ) ? 'selected="selected"' : '' ;
															?>
															<option <?php echo $selected; ?> value="<?php echo $value; ?>" id="<?php echo $value; ?>"><?php echo $element->name; ?></option>
														<? } ?>
													</select>
												<?php } ?>
											</label>
											<?php 
											if( $meta[ 'copy' ] ){
												$copy = $meta[ 'copy' ];
												$copy_from = '';
												$commas = '';
												foreach( $copy[ 'permissions' ] as $copy_permission ){
													$copy_from .= $commas . $copy_permission;
													$commas = ',';
												}
											?>
												<button class="btn btn-green copy-ids" copy-to="<?php echo $permission; ?>" copy-from="<?php echo $copy_from; ?>"><i class="icon-copy"></i> <?php echo $copy[ 'title' ]; ?></button>
												<br />
											<?php 
											} 
											if ( $meta[ 'additional' ] ) {
												$adicional = $meta[ 'additional' ];
												$adicional_permissions = $adicional[ 'permissions' ];
												$father = $permission;
												?>
												<b><?php echo $adicional[ 'label' ]; ?></b><br/>
												<?php 
												foreach( $adicional_permissions as $permission => $meta  ){
													$description = $meta[ 'description' ];
													$pattern = '/' . str_replace( 'ID' , '.*', $permission ) . '/';
													$checked = ( $group->hasPermission( $pattern, true ) ) ? 'checked="checked"' : '' ;
													?>
													<div class="row-fluid">
														<label for="<?php echo $permission; ?>">
															<span class="pull-right">
																<input type="checkbox" <?php echo $checked; ?> class="icheck additional-permissions" father="<?php echo $father; ?>" value="1" name="<?php echo $permission; ?>" id="<?php echo $permission; ?>">
															</span>
															&nbsp;<?php echo $description; ?>
															<span class="note">
																&nbsp;(<?php echo $permission; ?>)
															</span>
														</label>
													</div>
													<?php
												}
											} ?>
										</li>
									<?php 
										} 
									?>
								 </ul>
							</div>
					 	</div>
				 <?php 
				 	} 
				?>
						 <div class="box">
				<div class="box-header">
					 <span class="title">
					 Save
					 </span>
				</div>
				<div class="box-content ">
					 <ul class="box-list">
						<li class="input">
							<button type="submit" class="btn btn-blue admin-save"><i class="icon-save"></i> Save </button> 
						</li>
					 </ul>
				</div>
		 	</div>
			</div>
	 </div>

</div>
<script type="text/javascript">
	
	$(function() {

		$(document).on( 'click', '.admin-save', function() {
			sendForm();
		} );

		$( '.chosen' ).chosen();

		$( '.copy-ids' ).on( 'click', function(){
			var el = $( this );
			var permissions = {};
			var copy_to = el.attr( 'copy-to' );
			var copy_from = el.attr( 'copy-from' ).split( ',' );
			if( copy_from ){
				$( copy_from ).each( function( index, value ){
					var values = $( '#' + value ).val();
					if( values ){
						var pattern = new RegExp( value.replace( 'ID', '((.)*)' ) ,'gm');
						$( values ).each( function( index, value ){
							var id = value.replace( pattern, '\$1' );
							var permission = copy_to.replace( 'ID', id );
							$( '#' + permission ).attr( 'selected', 'selected' );
						} );
					}
				} );
			}

			$( '#' + copy_to ).trigger( 'liszt:updated' );
		} );

		$( '#global' ).on( 'ifChanged', function(event){
			validateChecked( '#global' );
		});

		$( '.do-all-father' ).on( 'ifChanged', function( event ){
			validateDoAllPermissions( $( '#' + event.target.id ) );
		});

		$( '.do-all-father' ).each( function( index, el ){
			validateDoAllPermissions( $( el ) );
		} );

		validateChecked( '#global' );

	});

	function validateDoAllPermissions( el ){
		if( el.is( ':checked' ) ){
			$( '.row-child-' + el.attr( 'family-name' ) ).hide();
		} else {
			$( '.row-child-' + el.attr( 'family-name' ) ).show();
		}
	}

	function validateChecked( id ){
		var el = $( id );
		switch( id ){
			case '#global':
				if( el.is( ':checked' ) ){
					$( '.permission-box' ).hide();
					$( '.box-global' ).show();
				} else {
					$( '.permission-box' ).show();
				}
				break;
		}
	}

	function sendForm(){
		
		var data = {};

		$('.permissions').each( function(){ 
			var el = $( this );
			var type = null;
			var parent = el.parent();
			if( parent.is( ':visible' ) ){
				if( el.is( 'input' ) ){
					type = el.attr( 'type' );
					if( type == 'checkbox' ){
						if( el.is( ':checked' ) ){
							data[ el.attr( 'name' ) ] = 1;
						}
					}
				} else {
					var options = el.val();
					$( options ).each( function( index, val ){
						data[ val ] = 1;
					} );
				}
			}
		} );
		
		$('.additional-permissions').each( function(){ 
			var el = $( this );
			if( el.is( ':checked' ) && el.is( ':visible' ) ){
				var father = el.attr( 'father' );
				var pattern = new RegExp( father.replace( 'ID', '((.)*)' ) ,'gm');
				var values = $( '#' + father ).val();
				$( values ).each( function( index, val ){
					var id = val.replace( pattern, '\$1');
					var permission = el.attr( 'name' ).replace( 'ID', id );
					data[ permission ] = 1;
				} );
			}
		} );

		var url = App.service + 'permissions/groups/<?php echo $group->id_group; ?>/permissions';
		$.ajax({
			type: 'POST',
			dataType: 'json',
			data: { permissions : data },
			url: url,
			success: function( json ) {
				processing = false;
				if( json.success ){
					alert( 'Permssions saved!' );
					location.reload();
				} else {
					alert( 'Error saving permissions!' );
				}
			},
			error: function( ){
				processing = false;
				alert( 'Error saving permissions!' );
				$( '.admin-save' ).html( '<i class="icon-save"></i> Save ' );
			}
		});

	}


</script>