<style>
.comments .ui-state-default {
	border: 0;
}
.list-orders.table-normal tbody td {
	vertical-align: top;
}
.list-orders a {
	text-decoration: underline;
}
</style>

<? if (!$this->logs->count()) : ?>
	No results found
<? else : ?>

	<table class="list-orders table table-normal">
		<thead>
			<tr>
				<td style="width:95px;">Date</td>
				<td>Type</td>
				<td>Level</td>
				<td>Data</td>
			</tr>
		</thead>

		<? foreach ($this->logs as $log) :  /* @var $log Crunchbutton_Order */?>
			<? $date = $log->date(); ?>
			<tr class="list-order-item">
				<td>
					<?=$date->format('M jS Y')?><br /><br /><?=$date->format('g:i:s A')?>
				</td>
				<td>
					<?=$log->type?>
				</td>
				<td>
					<?=$log->level?>
				</td>
				<td>
					<?=$log->data?>
				</td>

			</tr>
		<? endforeach ; ?>
	</table>
<? endif ; ?>