<style>
.comments .ui-state-default {
	border: 0;
}
.list-orders.table-normal tbody td {
	vertical-align: top;
}
.list-orders a {
	text-decoration: underline;
}
</style>

<? if (!$this->orders->count()) : ?>
	No results found
<? else : ?>

	<table class="list-orders table table-normal">
		<thead>
			<tr>
				<td style="width:120px;">Info</td>
				<td style="width:95px;">Date</td>
				<td style="width:120px;">Restaurant</td>
				<td>Order</td>
				<td>Price</td>
				<td>Pay&nbsp;/&nbsp;Type</td>
				<td></td>
			</tr>
		</thead>

		<? foreach ($this->orders as $order) :  /* @var $order Crunchbutton_Order */?>
			<? $date = $order->date(); ?>
			<tr class="list-order-item">
				<td>
					<a href="/vieworder/<?=$order->uuid?>">#<?=$order->id?></a>
					<br/>
					<br/>
					<?=$order->env?>
					<br/>
					<br/>
							<? if ($order->refunded) : ?>
								REFUNDED
							<? else : ?>
								<a href="javascript:;" class="refund" data-charged="<?php echo $order->charged(); ?>" data-gift="<?php if( $order->chargedByCredit() > 0 ){ echo $order->chargedByCredit(); } else { echo '0'; } ?>" data-uuid="<?=$order->uuid?>">REFUND</a>
							<? endif ; ?>
							<?php 
							$credit = $order->hasCredit();
							if( $credit > 0 ){
								echo '<div style="color:red;margin-top:8px;">Received <strong style="font-weight:bold;">$' . number_format( $credit, 2 ) . '</strong> credit.</div>';
							}
							?>
							<?php 
							$giftcard = $order->hasGiftCard();
							if( $giftcard > 0 ){
								echo '<br/><br/><i class="icon-gift"></i> Received <b>$' . number_format( $giftcard, 2 ) . '</b> gift card.';
							}
							?>
							<br />
							<br /> 

							<div class="pointer pay_if_refunded" data-value="<?php if( $order->pay_if_refunded ){ echo 1; } else { echo 0; } ?>" data-uuid="<?=$order->uuid?>">
								<span><?php if( $order->pay_if_refunded ) { echo '<i class="icon-check"></i>'; } else { echo '<i class="icon-check-empty"></i>'; } ?></span> Pay if Refunded?
							</div>
					<br/>

					<?
						$support = Support::getSupportForOrder($order->id);
						if($support) {
							echo '<i class="icon-comments"></i> <a href="/support/$support->id">View support ticket</a>';
						}
						else {
							echo '<i class="icon-comments"></i> <a href="javascript:create_support_from_order(' . $order->id . ');">Create support ticket</a>';
						}
					?>


				</td>
				<td>
					<?=$date->format('M jS Y')?><br /><br /><?=$date->format('g:i:s A')?>
				</td>
				<td>
					<?=$order->restaurant()->name?>
					<br/>
					<br/>
					<hr/>
					<?php if( $order->confirmed ) { ?>
						<i class="icon-thumbs-up"></i>	Confirmed!
					<?php } else { ?>
						<i class="icon-thumbs-down"></i> NOT confirmed.
					<?php } ?>
					<br/>
					<br/>
					<i class="icon-bullhorn"></i> <a href="javascript:;" class="resend_notification" data-confirmed="<?php echo $order->confirmed; ?>" data-uuid="<?=$order->uuid?>">Resend notification</a>
				</td>
				<td style="width: 300px; white-space: normal;">
					<ul>
					<? foreach ($order->dishes() as $dish) : ?>
						<li>
							<?=$dish->dish()->name?>
							<? if ($dish->options()->count()) : ?>
								<ul>
								<? foreach ($dish->options() as $option) : ?>
									<li><?=$option->option()->name?></li>
								<? endforeach ; ?>
								<? if( $dish->id_order_dish && $dish->id_dish ){ 
										foreach ( $dish->optionsDefaultNotChoosen() as $option ) {
										?><li><i style="font-style:italic;">No <?=$option->option()->name?></i></li><?
									} 
								}?>
								</ul>
							<? endif ; ?>
						</li>
					<? endforeach ; ?>
					</ul>
				</td>
				<td style="padding:0;">
					<table style="margin:0;">
						<tr>
							<td style="border-top:0;">Subtotal</td>
							<td style="border-top:0;">$<?=number_format($order->price,2)?></td>
						</tr>
						<tr>
							<td>Service Fee</td>
							<td>$<?=$order->serviceFee()?> ($<?=$order->service_fee ? $order->service_fee : '0'?>) </td>
						</tr>
						<tr>
							<td nowrap="">Delivery Fee</td>
							<td>$<?=$order->deliveryFee()?></td>
						</tr>
						<tr>
							<td>Tax</td>
							<td>$<?=$order->tax()?> (<?=$order->tax ? $order->tax : '0'?>%)</td>
						</tr>
						<tr>
							<td>Tip</td>
							<td>$<?=$order->tip()?> <?php if( $order->tip_type != Crunchbutton_Order::TIP_NUMBER ) { echo '(' . $order->tip . '%)'; } ?></td>
						</tr>
						<tr>
							<td>Total</td>
							<td>$<?=number_format($order->final_price,2)?></td>
						</tr>
						<?php if( $order->chargedByCredit() > 0 ) { ?>
						<tr style="background:#F5F5F5;">
							<td>Gift card</td>
							<td>$<?=$order->chargedByCredit();?></td>
						</tr>
						<tr style="background:#F5F5F5;">
							<td>Charged</td>
							<td>$<?=$order->charged();?></td>
						</tr>
						<?php } ?>
					</table>
				</td>
				<td>
					<?=$order->pay_type?>
					<br />
					<br />
					<?=$order->delivery_type?>
				</td>
				<td style="padding:0;">
					<table style="margin:0;border-top:0;width:100%;">
						<tr title="Name">
							<td style="border-top:0;"><i class="icon-user"></i> <?=$order->name?> </td>
						</tr>
						<tr title="Phone">
							<td><i class="icon-phone"> </i><?=$order->phone();?> </td>
						</tr>
						<?php if ($order->delivery_type == 'delivery') { ?>
						<tr title="Address">
							<td><i class="icon-home"></i> <?=$order->address?> </td>
						</tr>
						<?php } ?>
						<? if ($order->notes) :?>
							<tr>
								<td>
									<span>
										<i class="icon-file-alt"></i> <?php echo $order->notes;	?>
									</span>
								</td>
							</tr>
						<? endif ?>
						<tr>
							<td>
								<br/>
								<a href="/giftcards/new?id_user=<?php echo $order->user()->id_user; ?>&id_restaurant=<?php echo $order->restaurant()->id_restaurant; ?>&id_order_reference=<?php echo $order->id_order; ?>"><i class="icon-gift"></i> Add gift card</a>
							</td>
						</tr>
					</table>
				</td>
			</tr>
		<? endforeach ; ?>
	</table>
<? endif ; ?>