<?
	$this->title = 'Orders';
	$this->subtitle = 'people order shit! then eat it!';
	$this->titleicon = 'truck';
?>


<!-- content -->
<div class="container-fluid padded">
	<div class="row-fluid">
		<div class="box">

			<div class="box-content">
				<div class="row-fluid">
					<form class="fill-up">
						<div class="span6 separate-sections">
							<ul class="padded separate-sections">
								<li class="input">
									<input name="order-search" type="text" placeholder="Search" value="<?=strip_tags($_REQUEST['s'])?>">
								</li>
								<li>
									<label class="span3">Environment</label>
									<span class="span8 pull-right">
										<? $envs = ['live','beta','dev','local']; ?>
										<select name="env" class="uniform">
											<? foreach ($envs as $env) : ?>
												<option value="<?=$env?>"<?=c::env() == $env ? ' selected' : ''?>><?=$env?></option>
											<? endforeach ; ?>
										</select>
									</span>
									<div class="clearfix"></div>
								</li>
								<li>
									<label class="span3">Limit</label>
									<span class="span8 pull-right">
										<? $envs = ['live','beta','dev','local']; ?>
										<input type="number" name="limit" value="25" min="0">
									</span>
								</li>
							</ul>	
						</div>
						
						<div class="span6 separate-sections">
							<ul class="padded separate-sections">
								<li class="input">
									<?
										$date = new DateTime('now');
										$start = $date->format('m/d/Y');
										$date->modify('14 days ago');
										$end = $date->format('m/d/Y');
									?>
									<label class="span3">Date range</label>
									<span class="span8 pull-right">
										<span class="dates">
											from &nbsp; <input name="date-range-end" class="date-picker" type="text" style="width: 90px;" value="<?=$end?>">
											&nbsp; to &nbsp; <input name="date-range-start" class="date-picker" type="text" style="width: 90px;" value="<?=$start?>">
										</span>
										<input type="checkbox" name="order-range-all"><label>&nbsp;All Dates</label>
									</span>
									<div class="clearfix"></div>
			
								</li>
								<li>
									<label class="span3">Processor</label>
									<span class="span8 pull-right">
										<select name="processor" class="uniform">
											<option value="" selected>[ All ]</option>
											<option value="balanced" selected>balanced</option>
											<option value="stripe">stripe</option>
										</select>
									</span>
									<div class="clearfix"></div>
								</li>
								<li>
									<label class="span3">Restaurant</label>
									<span class="span8 pull-right">
										<select name="restaurant" class="chzn-select">
											<option value="" selected>[ All ]</option>
											<? foreach (Restaurant::q('select * from restaurant order by name') as $restaurant) : ?>
												<option value="<?=$restaurant->id_restaurant?>"><?=$restaurant->name?></option>
											<? endforeach ; ?>
										</select>
									</span>
									<div class="clearfix"></div>
								</li>
								<li>
									<label class="span3">Community</label>
									<span class="span8 pull-right">
										<select name="community" class="chzn-select">
											<option value="" selected>[ All ]</option>
											<? foreach (Community::q('select * from community order by name') as $community) : ?>
												<option value="<?=$community->id_community?>"><?=$community->name?></option>
											<? endforeach ; ?>
										</select>
									</span>
									<div class="clearfix"></div>
								</li>
							</ul>	
						</div>
					</form>

				</div>
				
			</div>
			<center>
				<button type="submit" class="btn btn-blue admin-order-search"> Search </button>	
			</center>
			<br />
		</div>

		<div class="box">
			<div class="box-header"><span class="title">Results</span>
				<ul class="box-toolbar">
					<li class="toolbar-link">
						<a href="javascript:;" class="admin-order-export" title="Export"><i class="icon-download-alt"></i></a>
					</li>
				</ul>
			
			</div>
			<div class="box-content">
				<div class="orders-loader"><center><i class="icon-spinner icon-spin" style="font-size: 50px;"></i></center></div>
				<div class="orders-content"></div>
			</div>
		</div>
	</div>
</div>



<script>
	$(function() {

		$(document).on('click', '.refund', function() {
			var el = $(this);
			var question = 'Are you sure you want to refund this?';
			if( parseFloat( el.attr( 'data-gift' ) ) > 0 ){
				question += "\n";
				question += 'A gift card was used at this order the refund value will be $' + el.attr( 'data-charged' ) + ' + $' + el.attr( 'data-gift' ) + ' as gift card.' ;
			}
			if (!confirm( question )) {
				return;
			}
			$.getJSON('/api/order/' + el.attr('data-uuid') + '/refund',function(json) {
				el.replaceWith('REFUNDED');
			});				
		});

		$(document).on( 'click', '.pay_if_refunded', function() {
			var el = $( this );
			var uuid = el.attr( 'data-uuid' );
			var value = ( el.attr( 'data-value' ) == 1 ? 0 : 1 );
			el.attr( 'data-value', value );
			var url = '/api/order/' + el.attr('data-uuid') + '/pay_if_refunded/' + value;
			$.getJSON( url ,function( json ) {
				if( value ){
					el.find( 'span' ).html( '<i class="icon-check"></i>' );
				} else {
					el.find( 'span' ).html( '<i class="icon-check-empty"></i>' );
				}
			});				
		});
		

		$(document).on('click', '.resend_notification', function() {
			var el = $(this);
			var question = 'Are you sure you want to resend the notification?';
			if( parseFloat( el.attr( 'data-confirmed' ) ) > 0 ){
				question += "\n";
				question += 'This order was already confirmed!' ;
			}
			if (!confirm( question )) {
				return;
			}
			$.getJSON('/api/order/' + el.attr('data-uuid') + '/resend_notification',function( json ) {
				if( json.status == 'success' ){
					alert('Notification resent!');
				} else {
					alert('Oops, error! Please try it again.');
				}
			});				
		});
		

		$(document).on('click', '.admin-order-search', function() {
			App.orders.load();
		});

		$(document).on('click', '.admin-order-export', function() {
			App.orders.export();
		});
		
		$(document).on('keyup', 'input[name="order-search"]', function(e) {
			if (e.which == 13) {
				App.orders.load();
			}
		});
		$('.chzn').select2();
		App.orders.load();

		$( 'input[name="date-range-end"]' ).datepicker({
			defaultDate: "+1w",
			changeMonth: true,
			numberOfMonths: 3,
			onClose: function( selectedDate ) {
				$( 'input[name="date-range-start"]' ).datepicker( "option", "minDate", selectedDate );
			}
		});
		$( 'input[name="date-range-start"]' ).datepicker({
			defaultDate: "+1w",
			changeMonth: true,
			numberOfMonths: 3,
			onClose: function( selectedDate ) {
				$( 'input[name="date-range-end"]').datepicker( "option", "maxDate", selectedDate );
			}
		});
	});
</script>
