<?
	$this->title = $this->project->name;
?>

<div class="project-left">
	<a href="javascript:;" class="project-button-follow">
		<div class="button-large button-large-darkblue">
			<div><?=$this->project->following() ? 'Unfollow' : 'Follow'?></div>
		</div>
	</a>

	<a href="javascript:;" class="project-button-follow">	
		<div class="button-large button-large-orange" style="margin-left: 10px;">
			<div><span class="st_sharethis" displayText="Share"></span></div>
			

		</div>
	</a>
	

	<div class="divider"></div>
	
	<table class="project-status">
		<tr>
			<td>
				<div class="button-small button-small-lightblue" style="float: left;">
					<div><?=count($this->project->followers())?></div>
				</div>
			</td>
			<td>
				<div class="button-small button-small-lightblue" style="margin-left: 3px;">
					<div><?=$this->project->contributors()?></div>
				</div>
			</td>
			<td>
				<div class="button-small button-small-lightblue" style="float: right;">
					<div>$<?=$this->project->raised(true)?></div>
				</div>
			</td>
		</tr>
		<tr class="project-status-items">
			<td style="padding-right: 6px;">follower<?=count($this->project->followers()) == 1 ? '' : 's'?></td>
			<td>contributor<?=$this->project->contributors() == 1 ? '' : 's'?></td>
			<td style="padding-left: 6px;">funds raised</td>
		</tr>
	</table>
	
	<div class="divider"></div>
	
	<div style="height: 10px;"></div>
	<div class="bar-progress-container">
		<table>
			<tr>
				<td class="bar-progress-text-start">START</td>
				<td class="bar-progress-text-percent"><?=$this->project->goal()?>%</td>
				<td class="bar-progress-text-goal">GOAL</td>
			</tr>
		</table>
		<div class="bar-progress bar-progress-goal"><div class="bar-progress-inner" style="width: <?=ceil((($this->project->goal() > 100 ? 100 : $this->project->goal()) / 100)*300)?>px;"></div></div>
	</div>
	

	<div class="bar-progress-container">
		<table>
			<tr>
				<td class="bar-progress-text-start">Days Left</td>
				<td class="bar-progress-text-percent"><?=$this->project->daysleft()?></td>
				<td class="bar-progress-text-goal">END</td>
			</tr>
		</table>
		<div class="bar-progress bar-progress-days"><div class="bar-progress-inner" style="width: <?=abs(ceil(($this->project->daysleft()/$this->project->days())*300)-300)?>px;"></div></div>
	</div>

	<br /><br />

	<div class="project-left-content-wrapper">
		<div class="project-left-header">Team</div>
		<div class="project-left-content">
			<table class="project-team-members">
				<? foreach ($this->project->team() as $member) : ?>
					<tr>
						<td class="project-team-name"><a href="/user/<?=$member->user()->username?>"><?=$member->user()->first_name?> <?=$member->user()->last_name?></a></td>
						<td class="project-team-icon"><a href="http://facebook.com/<?=$member->user()->facebook?>"><img src="/assets/images/social/16/facebook.png"></a></td>
						<td class="project-team-icon"><a href="http://twitter.com/<?=$member->user()->twitter?>"><img src="/assets/images/social/16/twitter-2.png"></a></td>
						<td class="project-team-icon"><a href="http://pinterest.com/<?=$member->user()->pinterest?>"><img src="/assets/images/social/16/pinterest.png"></a></td>
						<td class="project-team-icon"><a href="mailto:<?=$member->user()->email?>"><img src="/assets/images/social/16/email.png"></a></td>
					</tr>
				<? endforeach ; ?>
			</table>
		</div>
	</div>
</div>

<div class="project-right">
	<h1 class="project-title"><?=$this->project->name?></h1>

	<div class="project-social">
		<a href="http://facebook.com/<?=$this->project->facebook?>"><img src="/assets/images/social/24/facebook.png"></a>
		<a href="http://twitter.com/<?=$this->project->twitter?>"><img src="/assets/images/social/24/twitter-2.png"></a>
		<a href="http://pinterest.com/<?=$this->project->pinterest?>"><img src="/assets/images/social/24/pinterest.png"></a>
		<a href="http://statigr.am/<?=$this->project->instagram?>"><img src="/assets/images/social/24/instagram.png"></a>
	</div>
	
	<div class="divider"></div>
	
	<div class="project-right-content-wrapper">
		<div class="project-right-tabgroup">
			<a href="javascript:;" class="project-right-tab project-right-tab-active">Fuelers Comments</a>
			<a href="javascript:;" class="project-right-tab">Facebook Comments</a>
			<a href="javascript:;" class="project-right-tab">Action Required</a>
			<div class="divider"></div>
		</div>
		<div class="divider"></div>

		<div class="project-right-content">
			<? foreach ($this->feed as $item) : ?>
				<? $i++; ?>
				<div class="feed-message">
					<div class="feed-poster-image"><img src="http://graph.facebook.com/<?=$item['from']['id']?>/picture"></div>
					<p><?=$item['message'] ? $item['message'] : ($item['caption'] ? $item['caption'] : $item['story'])?></p>
					<div class="divider"></div>
					<div class="divider dots"></div>
				</div>
				<? if ($i == 3) break; ?>
			<? endforeach ; ?>
		</div>
	</div>


	<div class="project-right-content-wrapper">
		<div class="project-right-header">Press Release</div>
		<div class="project-right-content">
			<p>
				Games can be better
				<br /><br />
				We as a community can make games better
				<br /><br />
				We do not have to wait on corporate giants to make games better
				<br /><br />
				The first steps will be small...but they will lead to great things
				<br /><br />
				This fundraiser was about allowing someone to continue to do the work they love and ensuring that they were never cut off from their passion. Once Allison is well, we’d like to use any excess money to pay that forward by helping to create jobs that allow others to build their dreams, and, in doing so, maybe change the industry for the better. We would like to create a fund to publish quality games.
				<br /><br />
				We won’t be starting with triple A titles or multimillion dollar projects. We will start with independent games that are small enough to take risks and to deliver experiences that might really have an impact on the medium. Dan, Allison and I will contribute our expertise to help ensure that the money spent has the best possible chance of making a difference; we won’t take any money from the fund and any profits earned off titles published will go back into the fund to help kick start additional games.
				<br /><br />
				It is our hope to expand who gets to be a game developer and our plan to change how games are published.
			</p>
		</div>
	</div>

</div>

<div class="divider"></div>