FROM php:5.6-apache

ENV DOCKER=1

RUN apt-get update && apt-get install -y \
        libmcrypt-dev \
        php-pear \
        curl \
        git \
    && docker-php-ext-install iconv mcrypt \
	&& docker-php-ext-install mysql pdo_mysql



ADD conf/apache2.docker.conf /etc/apache2/sites-enabled/000-default.conf

#ADD ./ /var/www/
RUN ln -s /opt/www /var/www/app
RUN mkdir /var/www/logs
RUN chmod -R 0777 /var/www/cache

RUN a2enmod rewrite
RUN a2enmod headers
