<div class="top-pad"></div>

<div class="content-padding">
	<h1 class="left title"><i class="fa fa-exchange"></i>Disputes</h1>
	<div class="divider"></div>

	<div class="box-content2 box-content-table">
		<table>
			<tr>
				<td colspan="1"><i class="fa fa-search"></i>&nbsp;&nbsp;<input type="text" ng-model="query.search" id="search" tabindex="1"></td>
			</tr>
		</table>
	</div>

	<div class="bar-loader bar-loader-search" ng-class="{'bar-loader-loading': loading}"></div>

	<ng-include src="'/assets/view/listview-disputes.html'"></ng-include>
	<ng-include src="'/assets/view/listview-paging.html'"></ng-include>

</div>
