<div class="main-content-readable">
<p>
	<b>Problem with your order?</b><br />
	Try contacting the restaurant you ordered from.
	<br /><br />
	<b>Need to contact Crunchbutton?</b><br />
	Send us a text message to 646-783-1444
	<br />
	Or call us at <?=c::config()->phone->support?>
	<br /><br />
	<b>What is Crunchbutton?</b><br />
	Don't spend money on shitty food. Get the Best Food. From the Best Restaurants. With one click. Crunchbutton.
	<br /><br />
	<b>How do I order food?</b><br />
	Easy!  Just go to crunchbutton.com and click the restaurant you want to order from.  Add whatever food you want, and enter your address, phone, and payment info. Click "Get Food" and try to stay hungry!  The restaurant will call you when they're outside. 
	<br /><br />
	<b>Do you save all my info for super easy one click repeat ordering?</b><br />
	Yes!! Just come back to crunchbutton.com, choose a restaurant, and you’ll find all your previous info saved--delivery info, payment info, and order contents (or top order at restaurants you haven’t tried). Order again with literally one click. 
	<br /><br />
	<b>Why is there already food in my cart?</b><br />
	We went ahead and filled your cart with the most popular order at each restaurant. You can also order your own favorite food and we’ll save it in your cart for the next time you order at that restaurant.
	<br /><br />
	<b>What is all this fuss about choosing just the best food and the best restaurants?</b><br />
	Rather than forcing you to sort through a million unwieldly menus, we’ve chosen just the best food from the best restaurants in your community. We’ve gotten opinions from the chefs who cook the food, the delivery guys who notice what gets ordered most, the internet who is a pretty cool dude, and the peepz here in our/your communities who know what they like to eat.
	<br /><br />
	<b>But my favorite food’s not on Crunchbutton?</b><br />
	Tell us[link to input reccs, can just be a modal text field]. If it’s really that good, we’ll probably add it.
	<br /><br />
	<b>How do I change my stored info?</b><br />
	Just click on the info you want to change, enter the changes, and, after you place your order, it’ll be saved for next time.
	<br /><br />
	<b>How do you save my info?</b><br />
	It’s safely encrypted using [Devin input here]
	<br /><br />
	<b>Do you really choose the best food?</b><br />
	Yes, really! It’s freakin’ good. Try it!!
	<br /><br />
	<b>Did the restaurant receive my order?</b><br />
	You'll receive a confirmation text from us. If there is any problem or delay, we'll let you know. We've got your back... er.. your food.
	<br /><br />
	<b>When will my food get here?</b><br />
	Just look at the estimated delivery time on your text receipt.  We'll let you know if there is any hold-up, but you can call the restaurant phone # (also on your receipt) for an update.
	<br /><br />
	<b>Can I change or cancel my order?</b><br />
	If your change doesn't affect the price of the order, call the restaurant as soon as you can to let them know.  Otherwise, call us and we'll sort it out for you.
	<br /><br />
	<b>What if there is a problem with my order?</b><br />
	If food is missing or the order is late, call the restaurant first to see what's up.  If that's not working, let us know and we'll bring in the air support.
	<br /><br />
	If the food doesn't match what you ordered, call the restaurant and let you them know that what you got doesn't match what's on your receipt. They'll have your receipt as well, and they'll get your order in order. If not, call us -- we're always happy to help.
	<br /><br />
	<b>How are restaurants sorted?</b><br />
	The most popular open restaurants that deliver tend to be in the front of the line, but, if it’s on Crunchbutton, it’s good.
	<br /><br />
	<b>But I've never used Crunchbutton before...</b><br />
	Oh man, it's okay. I remember my first time, it didn't last more than 30 seconds. I went to Crunchbutton.com, found my favorite restaurant, hit "Get Food." Minutes later, my sandwich arrived. Post-coital bliss ensued, that sandwich sure knew how to crunch my buttons.
	<br /><br />
	<b>omg i am wayy too drunk to enter my information</b><br />
	We thought this might happen.  Luckily, Crunchbutton saves your address, phone, and payment info, so all you have to do is click what you want and hit the big, red "Get Food" button.  Try to be awake when the delivery guy calls.
	<br /><br />
	<b>Dear Respected Crunchbutton-ey Sirs, I want to put my restaurant on Crunchbutton.</b><br />
	Good idea!  Contact elite@crunchbutton.com
</p>
</div>