<div class="main-content-readable">
	<h1 class="about-header">About</h1>
	<p>
		Crunchbutton lets you order your favorite food with one click. We highlight the top food from the top restaurants in a community. Place an order, and we save it for next time, along with your delivery and payment info. Come back and reorder your favorites with just one click/tap.
	</p>
	<br /><br />

	<h1 class="about-header">Help</h1>
	<p>
		<b>Problem with your order?</b><br />
		Try contacting the restaurant you ordered from.
		<br /><br />
		<b>Need to contact Crunchbutton?</b><br />
		Call us at <?=c::config()->phone->support?>.
		<br /><br />
	</p>
	<br /><br />

	<h1 class="about-header">FAQ</h1>
	<p>
		<b>How do I order food?</b><br />
		Easy! Just go to crunchbutton.com and click the restaurant you want to order from. Add whatever food you want, and enter your address, phone, and payment info. Click "Get Food" and try to stay hungry! The restaurant will call you when they're outside.
		<br /><br />
		<b>How do you save my info?</b><br />
		We use a super secure system away from our web server to store and encrypt all your financial information.
		<br /><br />
		<b>How do I change my stored info?</b><br />
		Just click on the info you want to change, enter the changes, and, after you place your order, it’ll be saved for next time.
		<br /><br />
		<b>But I've never used Crunchbutton before...</b><br />
		Oh man, it's okay. I remember my first time, it didn't last more than 30 seconds. I went to Crunchbutton.com, found my favorite restaurant, hit "Get Food." Minutes later, my sandwich arrived. Post-coital bliss ensued, that sandwich sure knew how to crunch my buttons.
		<br /><br />
		<b>omg i am wayy too drunk to enter my information</b><br />
		We thought this might happen. Luckily, Crunchbutton saves your address, phone, and payment info, so all you have to do is click what you want and hit the big, red "Get Food" button. Try to be awake when the delivery guy calls.
		<br /><br />
		<b>I want to put a restaurant on Crunchbutton.</b><br />
		Good idea! Contact join@crunchbutton.com
	</p>
</div>