<?
/**
 * Still not sure what this does
 *
 * View variables you can't overwrite (see Controller_admin_restaurants::_form())
 * - $this->category
 *
 * @package  Cruncbutton.Bundle
 * @category view
 *
 */

/* @var $this Cana_View */


/* Exports current community as JSON
 *
 * @todo move this to a controller
 */
if ($this->community) {
	/* @var $this->community Crunchbutton_Community */
	if ($this->admin) {
		$community = $this->community->exports();
	} else {
		$community = $this->community->exports();
	}
	$communityJson = json_encode($community);
	$communityJson = str_replace("'","\\'", $communityJson);
}


/*
<script src="/assets/js/json2.js"></script>
<script src="/assets/js/jquery.min.js"></script>
<script src="/assets/js/jquery-ui.min.js"></script>
<script src="/assets/js/underscore-min.js"></script>
*/


?>


<script src="/assets/js/snap.js"></script>
<script src="/assets/js/jquery.cookie.js"></script>
<script src="/assets/js/jquery.totalstorage.js"></script>
<script src="/assets/js/date.js"></script>
<script src="/assets/js/TimeMachine.js"></script>
<script src="/assets/js/jquery.browser.mobile.js"></script>
<script src="/assets/js/jquery.magnific-popup.js"></script>
<script src="/assets/js/fastclick.js"></script>


<script type="text/javascript">
$(function() {
	<? if (!c::isBot()) : ?>
		$('.home-text').hide();
	<? endif ; ?>
	App.aliases = <?php echo json_encode( Community_Alias::all( array( 'id_community', 'prep', 'name_alt' ) ) ); ?>;
	App.locations = <?php echo json_encode( Community::all_locations() ); ?>;
	App.facebookScope = '<?php echo c::config()->facebook->default->scope; ?>';
	App.communities = {};
	<? foreach (Community::all(c::getPagePiece(0)) as $community) : ?>
		App.communities['<?=$community->permalink?>'] = {
			<? foreach ($community->properties() as $key => $val) : ?>
				'<?=$key?>': "<?=$val?>",
			<? endforeach ; ?>
			stored: true
		};
	<? endforeach ; ?>
	<? if ($this->community && $communityJson) : ?>
		App.cached['Community'][<?=$this->community->id_community?>] = new Community(<?=$communityJson?>);
		App.cached['Community']['<?=$this->community->permalink?>'] = App.cached['Community'][<?=$this->community->id_community?>];
		<? if (!c::getPagePiece(1)) : ?>
			App.loadedPage = '<?=$this->community->permalink?>';
		<? endif ; ?>
	<? endif ; ?>

	App.topCommunities = [];
	<? foreach (Community_Alias::q('select * from community_alias where top="1" order by `sort`') as $community_alias) : ?>
		App.topCommunities[App.topCommunities.length] = {
			alias: '<?=$community_alias->alias;?>',
			name: '<?=$community_alias->name_alt;?>'
		};
	<? endforeach ; ?>
});
</script>

<?
	if (!$scripts) {
		$scripts = ['app'];
	}

?>
<? foreach ($scripts as $script) : ?>
	<script src="/assets/js/<?=$script?>.js?v=<?=Cana_Util::gitVersion()?>"></script>
<? endforeach ; ?>

<script src="/assets/js/datetime.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/js/base.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/js/util.js?v=<?=Cana_Util::gitVersion()?>"></script>

<? if (!in_array('admin', $scripts)) : ?>
	<script src="/assets/js/pages.js?v=<?=Cana_Util::gitVersion()?>"></script>
	<script src="/assets/js/accounts.js?v=<?=Cana_Util::gitVersion()?>"></script>
<? endif ; ?>

<script src="/assets/js/cart.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/js/orm.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/js/location.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/js/ab.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/js/community.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/js/restaurant.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/js/dish.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/js/option.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/js/category.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/js/notification.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/js/order.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/js/credit.js?v=<?=Cana_Util::gitVersion()?>"></script>
<!-- <script src="/assets/js/giftcard.js?v=<?=Cana_Util::gitVersion()?>"></script> -->
<script src="/assets/js/creditcard.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/js/log.js?v=<?=Cana_Util::gitVersion()?>"></script>

<!-- AngularJS Controllers -->
<script src="/assets/js/controllers.js?v=<?=Cana_Util::gitVersion()?>"></script>

<!-- AngularJS Directives -->
<script src="/assets/js/directives.js?v=<?=Cana_Util::gitVersion()?>"></script>

<!-- AngularJS Services -->
<script src="/assets/js/services.account.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/js/services.navigation.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/js/services.restaurant.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/js/services.community.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/js/services.recommend.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/js/services.support.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/js/services.order.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/js/services.facebook.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/js/services.giftcard.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/js/services.position.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/js/services.cart.js?v=<?=Cana_Util::gitVersion()?>"></script>


<script type="application/x-javascript">
	addEventListener('touchstart',function(){}); addEventListener('load', function(event) {setTimeout(scrollTo, 80, 0, 1);}, false);
</script>