<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="/assets/js/jquery-ui.min.js"></script>
<script src="/assets/js/jquery.history.js"></script>
<script src="/assets/js/jquery.cookie.js"></script>
<script src="/assets/js/date.js"></script>
<script src="/assets/js/TimeMachine.js"></script>
<script src="/assets/js/jquery.browser.mobile.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.4.4/underscore-min.js"></script>


<script type="text/javascript">
$(function() {
	<? if (!c::isBot()) : ?>
		$('.home-text').hide();
	<? endif ; ?>
	App.aliases = <?php echo json_encode( Community_Alias::all( array( 'id_community', 'prep', 'name_alt' ) ) ); ?>;
	App.locations = <?php echo json_encode( Community::all_locations() ); ?>;
	App.communities = {};
	<? foreach (Community::all(c::getPagePiece(0)) as $community) : ?>
		App.communities['<?=$community->permalink?>'] = {
			<? foreach ($community->properties() as $key => $val) : ?>
				'<?=$key?>': "<?=$val?>",
			<? endforeach ; ?>
			stored: true
		};
	<? endforeach ; ?>
	<? if ($this->community) : ?>
		App.cached['Community'][<?=$this->community->id_community?>] = new Community(<?=str_replace("'","\\'",json_encode($this->community->exports()))?>);
		App.cached['Community']['<?=$this->community->permalink?>'] = App.cached['Community'][<?=$this->community->id_community?>];
		<? if (!c::getPagePiece(1)) : ?>
			App.loadedPage = '<?=$this->community->permalink?>';
		<? endif ; ?>
	<? endif ; ?>

	App.topCommunities = [];
	<? foreach (Restaurant::o(1, 18) as $restaurant) : ?>
		App.topCommunities[App.topCommunities.length] = {
			id_community: '<?=$restaurant->community()->permalink?>',
			name: '<?=$restaurant->community()->name?>',
			image: '/cache/images/<?=$restaurant->thumb()->getFileName()?>',
			restaurant: '<?=str_replace("'","\'",$restaurant->name)?>'
		};
	<? endforeach ; ?>
});
</script>

<?
	if (!$scripts) {
		$scripts = ['app'];
	}
?>
<? foreach ($scripts as $script) : ?>
	<script src="/assets/js/<?=$script?>.js?v=<?=Cana_Util::gitVersion()?>"></script>
<? endforeach ; ?>

<script src="/assets/js/base.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/js/util.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/js/pages.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/js/accounts.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/js/suggestions.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/js/orm.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/js/community.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/js/restaurant.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/js/dish.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/js/option.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/js/category.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/js/notification.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/js/order.js?v=<?=Cana_Util::gitVersion()?>"></script>

<script type="text/javascript">(function(e,b){if(!b.__SV){var a,f,i,g;window.mixpanel=b;a=e.createElement("script");a.type="text/javascript";a.async=!0;a.src=("https:"===e.location.protocol?"https:":"http:")+'//cdn.mxpnl.com/libs/mixpanel-2.2.min.js';f=e.getElementsByTagName("script")[0];f.parentNode.insertBefore(a,f);b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==
typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.increment people.append people.track_charge people.clear_charges people.delete_user".split(" ");for(g=0;g<i.length;g++)f(c,i[g]);b._i.push([a,
e,d])};b.__SV=1.2}})(document,window.mixpanel||[]);
mixpanel.init("6eb260b54eecfd293d50b5f1423c6e98");</script>

<script type="application/x-javascript">
	addEventListener('touchstart',function(){}); addEventListener('load', function(event) {setTimeout(scrollTo, 80, 0, 1);}, false);
</script>