<?
$this->title = 'Restaurant hours';
$this->titleicon = 'time';

$restaurants = $this->restaurants;

?>

<!-- restaurants page -->
<div class="container-fluid padded">
	<div class="row-fluid">
		<div class="box">
			<div class="box-header"><span class="title">Restaurants</span></div>
			<div class="box-content padded">
					<?php 
					$_counter = 0;
					foreach( $restaurants as $restaurant ){
						if( $_counter == 0 ){
							echo '<div class="row-fluid">';
						}
						?>
						<div class="span6">
							<h5>
								<?php echo $restaurant->name; ?> &nbsp;
								<?php if( $restaurant->open() ) { ?>
									<span class="label label-green">open</span>
								<?php } else { ?>
									<span class="label label-gray">closed</span>
								<?php } ?>
							</h5>
							<strong><?php echo $restaurant->timezone; ?></strong><br/>
							<?php echo $restaurant->closed_message(); ?>
							<br />
							<br />
						</div>
						<?php
						$_counter++;
						if( $_counter >= 2 ){
							echo '</div>';
							$_counter = 0;
						}
					}
					?>
			</div>
		</div>

	</div>
</div>