<div class="admin-content-wrapper" style="width: 200px; float: left;">
	<div class="admin-content">
		<? foreach (Restaurant::q('select * from restaurant') as $restaurant) :  ?>
			<a href="javascript:;" data-id_restaurant="<?=$restaurant->id_restaurant?>" class="admin-restaurant-link<?=$restaurant->active ? '' : ' admin-restaurant-inactive'?>"><?=$restaurant->name?></a><br />
		<? endforeach ?>
		<br />
		<a href="javascript:;" data-id_restaurant="" class="admin-restaurant-link">NEW</a><br />
	</div>
</div>

<div class="admin-id_restaurant" data-id_restaurant=""></div>

<div class="admin-content-wrapper" style="width: 650px; float: left; margin-left: 20px;">
	<div class="admin-content">
		<h1 class="restaurant-item-title">Restaurant Information</h1>
		<br />
		<table class="admin-restaurant-form">
			<tr>
				<td class="label-primary">Restaurant Name:</td>
				<td class="content-primary"><input type="text" name="name" value="" class="input-primary"></td>
			</tr>
			<tr>
				<td class="label-primary">Phone Number:</td>
				<td class="content-primary"><input type="text" name="phone" value="" class="input-primary"></td>
			</tr>

			<tr>
				<td class="label-primary">Order Notification Methods:</td>
				<td class="content-primary">
					<div class="check-wrap">
						<div class="check"><input type="checkbox"><label>Fax</label></div>
					</div>
					<div class="check-wrap">
						<div class="check"><input type="checkbox"><label>Email</label></div>
					</div>
					<div class="check-wrap">
						<div class="check"><input type="checkbox"><label>Text Message</label></div>
					</div>
					<div class="check-wrap">
						<div class="check"><input type="checkbox"><label>Phone Call</label></div>
						<div class="check-content">Okay, well call blah blah</div>
					</div>
				</td>
			</tr>
			
			<tr>
				<td class="label-primary">Food Items:</td>
				<td class="content-primary">
					<div class="check-wrap">
						<div class="check"><input type="checkbox"><label>No, I'll add some items later.</label></div>
					</div>

				</td>
			</tr>
			
			<tr>
				<td class="label-primary">Open Hours:</td>
				<td class="content-primary">
					<div class="check-wrap">
						<div class="check"><input type="checkbox"><label>We're always open!</label></div>
					</div>
					<div class="check-wrap">
						<div class="check"><input type="checkbox"><label>We're open during these hours</label></div>
					</div>
				</td>
			</tr>
			
			<tr>
				<td class="label-primary">Delivery Options:</td>
				<td class="content-primary">
					<div class="check-wrap">
						<div class="check"><input type="checkbox"><label>We do not offer delivery</label></div>
					</div>
					<div class="check-wrap">
						<div class="check"><input type="checkbox"><label>Yes! We deliver!</label></div>
						<div class="check-content">
							<table class="admin-restaurant-form-sub">
								<tr>
									<td class="label-sub">Average Delivery Time:</td>
									<td class="content-sub"><input type="number" class="form-number"></td>
								</tr>
								<tr>
									<td class="label-sub">Delivery Radius:</td>
									<td class="content-sub"><input type="number" class="form-number"></td>
								</tr>
								<tr>
									<td class="label-sub">Delivery Fee?</td>
									<td class="content-sub">
										<div class="check-wrap">
											<div class="check"><input type="checkbox"><label>No</label></div>
										</div>
										<div class="check-wrap">
											<div class="check"><input type="checkbox"><label>Yes</label></div>
											<div class="check-content">
												<input type="text">
											</div>
										</div>
									</td>
								</tr>
								

							</table>
						</div>
					</div>
				</td>
			</tr>
			
			
			<tr>
				<td>Community</td>
				<td>
					<select name="id_community">
						<? foreach (Community::q('select * from community') as $community) : ?>
							<option value="<?=$community->id_community?>"><?=$community->name?></option>
						<? endforeach ; ?>
					</select>
				</td>
			</tr>
			<tr>
				<td>Timezone</td>
				<td><input type="text" name="timezone" value="America/New_York"></td>
			</tr>
			<tr>
				<td>Location</td>
				<td>
					Lat <input type="text" name="loc_lat" value="41.2">
					Long <input type="text" name="loc_long" value="-70">
				</td>
			</tr>
			<tr>
				<td>Delivery</td>
				<td><input type="checkbox" name="delivery" value="1"></td>
			</tr>
			<tr>
				<td>Credit</td>
				<td><input type="checkbox" name="credit" value="1"></td>
			</tr>
			<tr>
				<td>Maxitems</td>
				<td><input type="text" name="max_items" value=""></td>
			</tr>
			<tr>
				<td>Tax</td>
				<td><input type="text" name="tax" value="">%</td>
			</tr>
			<tr>
				<td>Fee Customer</td>
				<td><input type="text" name="fee_customer" value=""></td>
			</tr>

			<tr>
				<td>Permalink</td>
				<td><input type="text" name="permalink" value=""></td>
			</tr>
			<tr>
				<td>Delivery Min</td>
				<td><input type="text" name="delivery_min" value="">$</td>
			</tr>
			<tr>
				<td>Delivery Radius</td>
				<td><input type="text" name="delivery_radius" value="">KM</td>
			</tr>
			<tr>
				<td>Delivery Estimated Time</td>
				<td><input type="text" name="delivery_estimated_time" value=""> minites</td>
			</tr>
			<tr>
				<td>Delivery Fee</td>
				<td><input type="text" name="delivery_fee" value="">$</td>
			</tr>
			<tr>
				<td colspan="2" style="text-align: left;"><br /><a href="javascript:;" class="admin-restaurant-save admin-restaurant-hours-save-link">Save</a></td>
			</tr>
		</table>
	</div>
	
	<div style="border: 1px solid #ddd; padding: 10px; margin-left: 20px; margin-top: 20px;" class="admin-restaurant-panel">
		<h1 class="restaurant-item-title">Hours</h1>
		<div class="admin-restaurant-hours admin-restaurant-content"></div>
		<br /><a href="javascript:;" class="admin-restaurant-hours-save admin-restaurant-hours-save-link">Save</a>
	</div>
	
	<div style="border: 1px solid #ddd; padding: 10px; margin-left: 20px; margin-top: 20px;" class="admin-restaurant-panel">
		<h1 class="restaurant-item-title">Notifications</h1>
	</div>
	
	<div style="border: 1px solid #ddd; padding: 10px; margin-left: 20px; margin-top: 20px;" class="admin-restaurant-panel">
		<h1 class="restaurant-item-title">Dishes</h1>
	</div>
	
	<div style="border: 1px solid #ddd; padding: 10px; margin-left: 20px; margin-top: 20px;" class="admin-restaurant-panel">
		<h1 class="restaurant-item-title">Default Order</h1>
	</div>
	<br /><br />
	<center><a href="admin-restaurant-hours-save-all">Save All</a></center>
</div>
	
<div class="divider"></div>