<div class="top-pad"></div>

<div class="content-padding" ng-show="ready">
	<button ng-click="add()">new driver</button>
	<table>
		<thead>
			<tr>
				<td>Name</td>
				<td></td>
			</tr>
		</thead>		
		<tbody>
			<tr ng-repeat="driver in drivers">
				<td>{{driver.name}}</td>
				<td>
					<button ng-click="edit(driver.id_admin)">edit</button>
				</td>
			</tr>
		</tbody>
	</table>
</div>

<div ng-show="!ready" class="loading">Loading</div>