<div class="top-pad"></div>

<div class="content-padding" ng-show="ready">
	
	<input type="text" id="search" ng-model="search" placeholder="search" />

	<button ng-click="add()">new driver</button>

	<table>
		<thead>
			<tr>
				<td>Name</td>
				<td>Login</td>
				<td>Communities</td>
			</tr>
		</thead>		
		<tbody>
			<tr ng-repeat="driver in drivers">
				<td>{{driver.name}}</td>
				<td>{{driver.login}}</td>
				<td><span ng-repeat="community in driver.communities">{{community}}</span></td>
				<td>
					<button ng-click="edit(driver.id_admin)">edit</button>
				</td>
			</tr>
		</tbody>
	</table>

	<ul class="pagination">
		<li><button ng-show="prev" ng-click="prevPage()">prev</button></li>
		<li>{{page}} of {{pages}}</li>
		<li><button ng-show="next" ng-click="nextPage()">next</button></li>
	</ul>

</div>

<div ng-show="!ready" class="loading">Loading</div>