<div class="top-pad"></div>

<h1 class="title left"><i class="fa fa-calendar"></i><span>Shifts</span></h1>

<div class="content-padding" ng-show="ready">

	<div class="divider"></div>

	<div class="drivers-shifts-list">
		
		<div ng-if="shifts.length">
			
<!-- shifts I want to work -->
			<h3>want to work</h3>
			<div class="drivers-shift" ng-repeat="shift in shifts">
				<div ng-if="!shift.ranking && shift.ranking != 0">
					{{shift.day}} {{shift.period}}
					<button ng-click="wantToWork( shift.id_community_shift )">yes</button>
					<button ng-click="dontWantToWork( shift.id_community_shift )">no</button>
				</div>
			</div>

			<!-- shifts I want to work -->
			<h3>want to work</h3>
			<div class="drivers-shift" ng-repeat="shift in shifts">
				<div ng-if="shift.ranking > 0">
					{{shift.day}} {{shift.period}}
					<button ng-if="shift.ranking_prev" ng-click="rankingChange( shift.id_community_shift, shift.ranking_prev )">up</button>
					<button ng-if="shift.ranking_next" ng-click="rankingChange( shift.id_community_shift,  shift.ranking_next )">down</button>
					<button ng-if="!shift.assigned" ng-click="dontWantToWork( shift.id_community_shift )">no</button>
				</div>
			</div>

			<!-- shifts I don't want to work -->
			<h3>don't want to work</h3>
			<div class="drivers-shift" ng-repeat="shift in shifts">
				<div ng-if="shift.ranking == 0">
					{{shift.day}} {{shift.period}}
					<button ng-click="wantToWork( shift.id_community_shift )">yes</button>
				</div>
			</div>

		</div>
		
		<div ng-if="!shifts.length" class="box-content">
			You currently have no shifts.
		</div>

	</div>	

</div>

<spinner-loading></spinner-loading>
<hack-expand-content></hack-expand-content>