<div class="top-pad"></div>

<h1 class="title left"><i class="fa fa-calendar"></i><span>Shifts</span></h1>

<div class="content-padding" ng-show="ready">

	<div class="divider"></div>

	<div class="drivers-shifts-list">
		
		<div ng-if="shifts.length">
			

			<div class="drivers-shift">

			<div ng-if="available > 0">

				<h2 class="title">Available shifts</h2>

				<div class="box-content">
					
					<table class="tb-grid">
						<tr ng-repeat="shift in shifts" ng-if="!shift.ranking && shift.ranking != 0">
							<td>
								<div class="start-end-brace">{{shift.day}}</div>
							</td>
							<td >
								<div class="start-end-brace">{{shift.period}}</div>
							</td>
							<td class="td-large schedule-buttons">
								<button class="button schedule-action-yes" ng-if="!shift.assigned" ng-click="wantToWork( shift.id_community_shift )">
									<i class="fa fa-thumbs-o-up"></i>
								</button>
								<button class="button schedule-action-not" ng-if="!shift.assigned" ng-click="dontWantToWork( shift.id_community_shift )">
									<i class="fa fa-thumbs-o-down"></i>
								</button>
							</td>
						</tr>
					</table>

				</div>

			</div>

			<div ng-if="yes > 0">

				<h2 class="title">Shifts you want to work</h2>
				<h3 class="title">Ranked from most to least preferred</h3>

				<div class="box-content">
					
					<table class="tb-grid">
						<tr ng-repeat="shift in shifts" ng-if="shift.ranking > 0">
							<td>
								<div class="start-end-brace">{{shift.day}}</div>
							</td>
							<td >
								<div class="start-end-brace">{{shift.period}}</div>
							</td>
							<td class="td-large schedule-buttons">
								<button class="button schedule-action-down" ng-if="shift.ranking_next" ng-click="rankingChange( shift.id_community_shift,  shift.ranking_next )">
									<i class="fa fa-sort-desc"></i>
								</button>
								<button class="button schedule-action-up" ng-if="shift.ranking_prev" ng-click="rankingChange( shift.id_community_shift, shift.ranking_prev )">
									<i class="fa fa-sort-asc"></i>
								</button>
								<button class="button schedule-action-not" ng-if="!shift.assigned" ng-click="dontWantToWork( shift.id_community_shift )">
									<i class="fa fa-thumbs-o-down"></i>
								</button>
								<button class="button schedule-action-lock" ng-if="shift.assigned">
									<i class="fa fa-lock"></i>
								</button>
							</td>
						</tr>
					</table>

				</div>

			</div>

			<div ng-if="not > 0">

				<h2 class="title">Shifts you CANNOT work</h2>

				<div class="box-content">
					
					<table class="tb-grid">
						<tr ng-repeat="shift in shifts" ng-if="shift.ranking == 0">
							<td>
								<div class="start-end-brace">{{shift.day}}</div>
							</td>
							<td >
								<div class="start-end-brace">{{shift.period}}</div>
							</td>
							<td class="td-large schedule-buttons">
								<button class="button schedule-action-yes" ng-click="wantToWork( shift.id_community_shift )">
									<i class="fa fa-thumbs-o-up"></i>
								</button>
							</td>
						</tr>
					</table>

				</div>
			</div>

			</div>

		</div>
		
		<div ng-if="!shifts.length" class="box-content">
			You currently have no shifts.
		</div>

	</div>	

</div>

<spinner-loading></spinner-loading>
<hack-expand-content></hack-expand-content>