<div class="top-pad"></div>
<div class="content-padding drivers-order">
	<div class="content">
		<div class="wrap">
			<div class="status"></div>
			<div class="header">
				<div class="restaurant-name">{{order._restaurant_name}}</div>
				<div class="order-id">{{order.id_order}}</div>
				<div class="divider"></div>
			</div>
			<div class="order">
				<div class="order-item-block">
					<div class="order-icon">
						<i class="icon-{{order.delivery_type}}"></i>
					</div>
					<div class="order-info">
						<span ng-if="order.delivery_type=='takeout'">Takeout</span>
						<span ng-if="order.delivery_type=='delivery'">Delivery</span>
					</div>
				</div>
				<div class="order-item-block">
					<div class="order-icon"><i class="icon-{{order.pay_type}}"></i></div>
					<div class="order-info">
						<span ng-if="order.pay_type=='card'">Card</span>
						<span ng-if="order.pay_type=='cash'">Cash</span>
					</div>
				</div>
				<div class="order-item-block">
					<div class="order-icon"><i class="icon-clock"></i></div>
					<div class="order-info">
						{{order._date | date:'hh:mm a'}}
					</div>
				</div>
				<div class="order-item-block">
					<div class="order-icon"><i class="icon-timer"></i></div>
					<div class="order-info">
						<span ng-if="order._delivery_estimated_time">{{order._delivery_estimated_time}}</span>
					</div>
				</div>
				<div class="divider"></div>
				<div class="divider dots"></div>
				<div class="order-item-block-big">
					<div class="order-info order-info-small">
						{{order._instructions_payment}}
					</div>
				</div>
				<div class="order-item-block-big">
					<div class="order-info order-info-small">
						{{order._instructions_food}}
					</div>
				</div>
				<div class="divider"></div>
				<div class="divider dots"></div>
				<span ng-if="order._stealth_notification">
					<div class="order-item-block-big">
						Tell restaurant: <i>"I'm here to pick up a faxed order for {{order.id_order}}</i>".
					</div>
					<div class="divider"></div>
					<div class="divider dots"></div>
				</span>
				<br><br>
				<div class="order-icon"><i class="icon-user"></i></div>
				<div class="order-info">
					{{order.name}}
					<br><a href="tel:+1{{order.phone}}">{{order.phone | formatPhone}}</a>
				</div>
				<span ng-if="order.notes">
					<div class="order-comment-arrow"></div>
					<div class="order-comment">
						<p>{{ order.notes | nl2br }}</p>
					</div>
				</span>
				<span ng-if="!order.notes">
				<br>
				</span>
				<a href="http://maps.apple.com/?daddr={{order.address}}&saddr={{order._restaurant_address}}">
					<div class="order-map" style="background: url('https://maps.googleapis.com/maps/api/staticmap?size=640x300&markers=color:green%7Clabel:A%7C{{order.address | clearAddress}}&markers=color:red%7Clabel:B%7C{{order._restaurant_lat}},{{order._restaurant_lon}}&sensor=false&visual_refresh=true');"></div>
				</a>
				<br>
				<div class="order-item-block order-map-block">
					<div class="order-icon"><i class="icon-map-home"></i></div>
					<div class="order-info">
						<p class="order-info-address"><a href="http://maps.apple.com/?q={{order.address}}">{{order.address | nl2br}}</a></p>
					</div>
				</div>
				<div class="order-item-block order-map-block">
					<div class="order-icon"><i class="icon-map-restaurant"></i></div>
					<div class="order-info">
						<p class="order-info-address"><a href="http://maps.apple.com/?q={{order._restaurant_address}}">{{order._restaurant_address | nl2br }}</a></p>
					</div>
				</div>
				<br><br>
				<div class="divider dots"></div>
				<br><br>
				<table width="100%" celpadding="0" cellspacing="0" class="detail">
					<thead style="font-weight:bold">
						<td class="topitem">Qty</td>
						<td class="topitem">Item</td>
						<td class="topitem" nowrap="nowrap">Customer Price</td>
						<td class="topitem" style="width:80px;font-size:12px;color:#666;">Store Price</td>
					</thead>
					<tbody>
						<tr ng-repeat="dish in order._dishes">
							<td class="fooditem">1</td>
							<td class="fooditem">{{dish.name}} {{dish.options.without_default_options}} {{dish.options.with_option}} {{dish.options.select_options}} </td>
							<td style="width: 1%;" class="fooditem">
								${{dish.price.marked_up | formatPrice}}
							</td>
							<td class="fooditem" style="font-size:12px;color:#666;">
								${{dish.price.regular | formatPrice}}
							</td>
						</tr>
						<tr class="class">
							<td></td>
							<td style="text-align:right">Subtotal</td>
							<td>
								${{order.price_plus_delivery_markup | formatPrice}}
							</td>
							<td style="font-size:12px;color:#666;">
								${{order.price | formatPrice}}
							</td>
						</tr>
						<tr ng-if="order._tip">
							<td></td>
							<td style="text-align:right">Tip <span ng-if="order.tip_type != 'number'">%</span></td>
							<td>${{order._tip | formatPrice}}</td>
							<td style="font-size:12px;color:#666;">
								&mdash;
							</td>
						</tr>
						<tr ng-if="order.delivery_fee">
							<td></td>
							<td style="text-align:right">Delivery Fee</td>
							<td>${{order.delivery_fee | formatPrice}}</td>
							<td style="font-size:12px;color:#666;">
								&mdash;
							</td>
						</tr>
						<tr ng-if="order.service_fee">
							<td></td>
							<td style="text-align:right">Service Fee</td>
							<td>${{order.service_fee | formatPrice}}</td>
							<php if( $isDriverCockpit ) {  />
							<td style="font-size:12px;color:#666;">
								&mdash;
							</td>
						</tr>
						<tr>
							<td></td>
							<td style="text-align:right">Tax</td>
							<td>
								${{order._tax | formatPrice}}
							</td>
							<td style="font-size:12px;color:#666;">
								${{order._tax | formatPrice}}
							</td>
						</tr>
						<tr style="font-weight:bold;">
							<td></td>
							<td style="text-align:right">Total</td>
							<td>
								${{order.final_price_plus_delivery_markup | formatPrice}}
							</td>
							<td style="font-size:14px;color:#666;">
								${{order._final_price | formatPrice}}
							</td>
						</tr>
						<tr ng-if="order._tip_with_cash">
							<td colspan="3" style="text-align:left">Customer is tipping with cash</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>