<div class="top-pad"></div>

<div class="content-padding">
	<p>
		<b>Have questions during a delivery?</b><br>
		TXT us at <a href="tel:646-783-1444">646-783-1444</a>
		<br>
		or email <a href="mailto:drive@crunchbutton.com">drive@crunchbutton.com</a>
		<br><br>
		<b>When do I fill out my schedule for the next week?</b><br>
		Make sure to fill out your schedule by Monday at 8PM EDT at the latest.
		<br><br>
		<b>Payment:</b><br>
		At the end of each week, you will be reimburse for your credit/debit card spendings plus what you earned. You get to keep all cash received from cash orders. If there are discrepancies between what you paid for the order versus what the cost for JUST the itself (not including taxes, delivery fee, etc), email david so we can fix prices online. 
		<br><br>
		<b>Insurance:</b><br>
		Youbeo, Inc has an insurance policy that will protect Youbeo and its drivers from liability claims arising from a motor vehicle collision during the course of business. The protection is up to $1,000,000 liability insurance policy that protects you against claims to third parties for injuries and property damage. This protection does not cover physical damage to any vehicle being used by a driver associated with Youbeo. Physical damage to any employee or subcontract’s vehicle must be done through the individual's primary insurance company.
	</p>
</div>