<div class="top-pad"></div>

<div class="content-padding" ng-show="ready">
	<div class="content">

		<h1 ng-if="!driver.id_admin">New driver</h1>
		<h1 ng-if="driver.id_admin">Edit driver</h1>
		<form name="form" novalidate>
			<ul class="form" ng-class="{'submitted' : submitted}">
				<li> 
					<label for="driverName">
						<div class="label">Name:</div>
						<div class="input"><input type="text" name="driverName" ng-model="driver.name" required placeholder="Name" ng-minlength="5" ng-maxlength="40" ></div>
					</label>
					<div class="error" ng-show="submitted && form.driverName.$invalid">
						<small class="error" ng-show="form.driverName.$error.required">Required.</small>
						<small class="error" ng-show="form.driverName.$error.minlength">Name is too short. Name is required to be at least 5 characters.</small>
						<small class="error" ng-show="form.driverName.$error.maxlength">Name cannot be longer than 40 characters.</small>
					</div>
				</li>
				<li> 
					<label for="driverPhone">
						<div class="label">Phone:</div>
						<div class="input"><input type="text" name="driverPhone" ng-model="driver.phone" required phone-validate placeholder="Phone"></div>
					</label>
					<div class="error" ng-show="submitted && form.driverPhone.$invalid">
						<small class="error" ng-show="form.driverPhone.$error.required">Required.</small>
						<small class="error" ng-show="form.driverPhone.$error.phoneValidate">Enter a valid phone.</small>
					</div>
				</li>
				<li>
					<label for="driverCommunity">
						<div class="label">Community:</div>
						<select name="driverIdCommunity" required ng-model="driver.id_community" ng-options="opt.id_community as opt.name for opt in communities" class="cart-customize-select"></select>
					</label>
					<div class="error" ng-show="submitted && form.driverIdCommunity.$invalid">
						<small class="error" ng-show="form.driverIdCommunity.$error.required">Required.</small>
					</div>
				</li>
				<li>
					<label for="driverEmail">
						<div class="label">email:</div>
						<div class="input"><input type="email" name="driverEmail" ng-model="driver.email" placeholder="Email"></div>
					</label>
					<div class="error" ng-show="submitted && form.driverEmail.$invalid">
						<small class="error" ng-show="form.driverEmail.$invalid">Enter a valid email.</small>
  				</div>
				</li>
				<li ng-if="driver.id_admin">
					<h2>Documents</h2>
					<ul>
						<li ng-repeat="doc in documents">
							<div>{{doc.name}} <span ng-show="doc.status"><a href="{{doc.status.url}}" target="_blank">Download</a></span>
							</div>
						</li>
					</ul>
				</li>
				<li class="buttons">
					<button ng-click="save();">Save</button>
					<button ng-click="cancel()">Cancel</button>
				</li>
			</ul>
		</form>
		<hr/>
		<form name="docs" ng-if="driver.id_admin">
			<h2>Upload zone</h2>
			<ul>
				<li>
					<label for="driverDocument">
						<div class="label">Select the file type:</div>
						<select name="driverDocument" ng-model="doc_uploaded" ng-options="opt.id_driver_document as opt.name for opt in documents"></select>
					</label>		
				</li>
				<li ng-show="uploader.progress">
					Progress {{uploader.progress}}%
				</li>
				<li ng-show="doc_uploaded">
					<input ng-file-select name="file" type="file" />
				</li>
				<li ng-show="doc_uploaded">
					<button ng-click="uploader.uploadAll()"> Upload </button>
				</li>
			</ul>
		</form>
		<hr/>
		<div class="notifications" ng-if="driver.id_admin">
			
		</div>
	</div>
</div>
