<div class="top-pad"></div>

<div class="content-padding">
	<div class="dialog-message dialog-message-error">
		<u>In order to receive payment</u> for orders that you deliver, you <b>MUST</b> confirm all orders that you've delivered. 
		Make sure your orders are confirmed and delivered!
	</div>

	<? /* @todo: make this a diff date. write date diff in js */ ?>
	<div class="last-updated">Last Updated: <span class="last-updated-time">{{newDriverOrders.time.getTime() | date: 'h:mm'}}</span></div>	

	<div class="drivers-order-list">
		<div ng-if="orders">
			<div class="drivers-order-list-item" ng-repeat="order in driverorders" ng-class="order.lastStatus.status">
				<span class="text" ng-switch="order.lastStatus.status">
					<span ng-switch-when="delivered">Delivered by {{order.lastStatus.name}}</span>
					<span ng-switch-when="pickedup">Picked up by {{order.lastStatus.name}}</span>
					<span ng-switch-when="accepted">Accepted by {{order.lastStatus.name}}</span>
					<span ng-switch-default></span>
				</span>

				<div class="order-list-action">
					<button class="button button-list-accept" ng-click="accept(order.id_order)" ng-show="order.lastStatus.status='new' || !order.lastStatus.status"> Accept </button>
					<button class="button button-list-pickedup" ng-click="pickup(order.id_order)" ng-show="order.status.id_admin==account.user.id_admin && order.lastStatus.status=='accepted'"> Picked up </button>
					<button class="button button-list-delivered" ng-click="delivered(order.id_order)" ng-show="order.status.id_admin==account.user.id_admin && order.lastStatus.status=='pickedup'"> Delivered </button>
				</div>

				<div class="order-list-date">
					<div class="day">{{order.date.date | date:'M/d'}}</div>
					<div class="hour">{{order.date.date | date:'h:m'}}</div>
					<div class="ampm">{{order.date.date | date:'a'}}</div>
				</div>
				<div class="order-list-customer-info">
					<div class="restaurant" ng-click="viewOrder">
						{{order.restaurant}}
					</div>
					<div class="customer" ng-click="viewOrder">
						{{order.name}}
					</div>
				</div>
				<div class="divider"></div>
			</div>
		</div>
		
		<div ng-if="!orders">
			You currently have no orders to deliver.
		</div>
	</div>	

</div>
