<div class="top-pad"></div>

<div class="content-padding" ng-show="ready">

	<div class="box-filter">
		<button class="button orange" ng-class="{ 'inactive' : !show.all }" ng-click="show.all = true">All</button>
		<button class="button orange" ng-class="{ 'inactive' : show.all }" ng-click="show.all = false">Mine</button>
		<div class="divider"></div>
	</div>

	<div class="drivers-shifts-list">
		
		<div ng-if="drivershifts.length">
		
			<div class="box-content item" ng-repeat="shift in drivershifts | filter:filterShifts">

				<h4 class="community">{{shift.community}}</h4>
				<h2 class="day">{{shift.date.day}}</h2>
				<h1 class="start_end">{{shift.date.start_end}}</h1>
				<h4 class="timezone">{{shift.date.timezone}}</h4>
				
				<div nf-if="shift.drivers">
					<ul class="drivers">
						<li class="driver" ng-repeat="driver in shift.drivers">
							<strong>{{driver.name}}</strong> <span class="phone">{{driver.phone | formatPhone}}</span>
						</li>
					</ul>
				</div>

				<div ng-if="!shift.drivers">
					<h3>No drivers</h3>
				</div>

				<div class="divider"></div>

			</div>

		</div>
		
		<div ng-if="!drivershifts.length">
			<h3>You currently have no shifts.</h3>
		</div>

	</div>	

</div>
