<div class="top-pad"></div>

<div class="content-padding">
	<div class="dialog-message dialog-message-error">
		<u>In order to receive payment</u> for orders that you deliver, you <b>MUST</b> confirm all orders that you've delivered. 
		Make sure your orders are confirmed and delivered!
	</div>

	<? /* @todo: make this a diff date. write date diff in js */ ?>
	<div class="last-updated">Last Updated: <span class="last-updated-time">{{newDriverOrders.time.getTime() | date: 'hh:mm a'}}</span></div>	

	<div class="drivers-order-list-filter">
		<button class="button orange" ng-class="{ 'inactive' : !show.all }" ng-click="show.all = true">All</button>
		<button class="button orange" ng-class="{ 'inactive' : show.all }" ng-click="show.all = false">Mine</button>
		<div class="divider"></div>
	</div>

	<div class="drivers-order-list">
		
		<div ng-if="driverorders">
		
			<div class="box-with-shadown item" ng-repeat="order in driverorders | filter:filterOrders" ng-class="order.lastStatus.status">

				<!-- action -->
				<div class="action">
					<button class="button green button-pushable" ng-click="accept(order.id_order)" ng-if="order.lastStatus.status == 'new' || !order.lastStatus.status" > Accept </button>
					<button class="button orange button-pushable" ng-click="pickedup(order.id_order)" ng-if="order.lastStatus.id_admin == account.user.id_admin && order.lastStatus.status == 'accepted'"> Picked up </button>
					<button class="button lightorange button-pushable" ng-click="delivered(order.id_order)" ng-if="order.lastStatus.id_admin == account.user.id_admin && order.lastStatus.status == 'pickedup' "> Delivered </button>
				</div>

				<!-- date -->
				<div class="date">
					<div class="day">{{order._date | date:'MM/dd'}}</div>
					<div class="hour">{{order._date | date:'hh:mm'}}</div>
					<div class="ampm">{{order._date | date:'a'}}</div>
				</div>

				<!-- info -->
				<div class="info">

					<span class="status" ng-if="order.lastStatus.name">
						<span ng-switch="order.lastStatus.status">
							<span ng-switch-when="delivered">Delivered</span>
							<span ng-switch-when="pickedup">Picked up</span>
							<span ng-switch-when="accepted">Accepted</span>
							<span> by {{order.lastStatus.name}}</span>
						</span>
					</span>

					<div class="restaurant" ng-click="viewOrder">
						{{order.restaurant}}
					</div>
					<div class="customer" ng-click="viewOrder">
						{{order.name}}
					</div>
				</div>

				<div class="divider"></div>
			</div>
		</div>
		
		<div ng-if="!driverorders">
			You currently have no orders to deliver.
		</div>

	</div>	

</div>
