<div class="top-pad"></div>
<div class="content-padding" ng-show="ready">
	<div class="content">
		<hr/>
		<h2>Documents</h2>
		<p>
			Here are important docs to fill out and sign. Please download the docs, fill them out and then upload them back to this page. We recommend signing them with Hellosign
		</p>
		<table>
			<thead>
				<tr>
					<td>Document</td>
					<td>Template</td>
					<td>Status</td>
				</tr>
			</thead>
			<tbody>
				<tr ng-repeat="doc in documents" ng-if="doc.url">
					<td>{{doc.name}}</td>
					<td>
						<span ng-if="doc.url">
							<a href="{{doc.url}}" target="_blank">Download the template</a>
						</span>
					</td>
					<td>
						<span ng-if="doc.status && doc.status.date_formated && doc.status.url">
							<a href="{{doc.status.url}}" target="_blank">
								Sent at {{doc.status.date_formated}}
							</a>
						</span>
						<span class="not-sent" ng-if="!doc.status">
							<i>Not sent</i>
						</span>
					</td>
				</tr>
			</tbody>
		</table>
		
		<hr/>

		<p>
			Upload a clear picture of your Drivers License and Insurance Card here. You can take a clear, close up picture with a smartphone, and then upload in the appropriate spots below
		</p>
		<table>
			<thead>
				<tr>
					<td>Document</td>
					<td>Status</td>
				</tr>
			</thead>
			<tbody>
				<tr ng-repeat="doc in documents" ng-if="!doc.url">
					<td>{{doc.name}}</td>
					<td>
						<span ng-if="doc.status && doc.status.date_formated && doc.status.url">
							<a href="{{doc.status.url}}" target="_blank">
								Sent at {{doc.status.date_formated}}
							</a>
						</span>
						<span class="not-sent" ng-if="!doc.status">
							<i>Not sent</i>
						</span>
					</td>
				</tr>
			</tbody>
		</table>

		<form name="docs">
			<hr/>
			<h2>Upload zone</h2>
			<ul>
				<li>
					<label for="driverDocument">
						<div class="label">Select the file type:</div>
						<select name="driverDocument" ng-model="doc_uploaded" ng-change="setDocument( this.doc_uploaded )" ng-options="opt.id_driver_document as opt.name for opt in documents"></select>
					</label>		
				</li>
				<li ng-show="uploader.progress">
					Progress {{uploader.progress}}%
				</li>
				<li ng-show="doc_uploaded">
					<input ng-file-select name="file" type="file" />
				</li>
				<li ng-show="doc_uploaded">
					<button ng-click="uploader.uploadAll()"> Upload </button>
				</li>
			</ul>
		</form>
		<hr/>
		<p>
			<a target="_blank" href="https://s3.amazonaws.com/uploads.hipchat.com/41812/283752/nmB3Y2yH2HkjWLM/DeliveryDriverGuidelines.pdf">Download the Delivery Driver Guidelines</a>		
		</p>
	</div>
</div>