<div class="top-pad"></div>

<div class="content-padding" ng-show="ready">

	<div class="box-filter right">
		<button class="button orange" ng-click="list()">List</button>
		<div class="divider"></div>
	</div>

	<h1 class="title" ng-show="order.id_order"><i class="fa fa-credit-card"></i><span>Order #{{order.id_order}}</span></h1>

	<h1 class="title" ng-show="error">
		Invalid order!
	</h1>

	<div class="content box-content" ng-show="order.id_order">
		<div class="wrap">
			<div class="order">
				<div class="order-item-block">
					<div class="order-icon">
						<i class="icon-{{order.delivery_type}}"></i>
					</div>
					<div class="order-info">
						<span ng-if="order.delivery_type=='takeout'">Takeout</span>
						<span ng-if="order.delivery_type=='delivery'">Delivery</span>
					</div>
				</div>
				<div class="order-item-block">
					<div class="order-icon"><i class="icon-{{order.pay_type}}"></i></div>
					<div class="order-info">
						<span ng-if="order.pay_type=='card'">Card</span>
						<span ng-if="order.pay_type=='cash'">Cash</span>
					</div>
				</div>
				<div class="order-item-block">
					<div class="order-icon"><i class="icon-clock"></i></div>
					<div class="order-info">
						{{order._date_formatted}}
					</div>
				</div>
				<div class="order-item-block">
					<div class="order-icon"><i class="icon-timer"></i></div>
					<div class="order-info">
						<span ng-if="order._delivery_estimated_time">{{order._delivery_estimated_time}}</span>
					</div>
				</div>

				<div class="divider"></div>
				<div class="divider dots"></div>
				<br><br>
				<div class="order-icon"><i class="icon-user"></i></div>
				<div class="order-info">
					{{order.name}}
					<br><a href="tel:+1{{order.phone}}">{{order.phone | formatPhone}}</a>
				</div>
				<span ng-if="order.notes">
					<div class="order-comment-arrow"></div>
					<div class="order-comment">
						<p>{{ order.notes | nl2br }}</p>
					</div>
				</span>
				<span ng-if="!order.notes">
				<br>
				</span>
				<a href="http://maps.apple.com/?daddr={{order.address}}&saddr={{order._restaurant_address}}">
					<div class="order-map" style="background: url('https://maps.googleapis.com/maps/api/staticmap?size=640x300&markers=color:green%7Clabel:A%7C{{order.address | clearAddress}}&markers=color:red%7Clabel:B%7C{{order._restaurant_lat}},{{order._restaurant_lon}}&sensor=false&visual_refresh=true');"></div>
				</a>
				<br>
				<div class="order-item-block order-map-block">
					<div class="order-icon"><i class="icon-map-home"></i></div>
					<div class="order-info">
						<p class="order-info-address"><a href="http://maps.apple.com/?q={{order.address}}">{{order.address | nl2br}}</a></p>
					</div>
				</div>
				<div class="order-item-block order-map-block">
					<div class="order-icon"><i class="icon-map-restaurant"></i></div>
					<div class="order-info">
						<p class="order-info-address"><a href="http://maps.apple.com/?q={{order._restaurant_address}}">{{order._restaurant_address | nl2br }}</a></p>
					</div>
				</div>
				<br><br>
				<div class="divider dots"></div>
				<br><br>
				<table width="100%" celpadding="0" cellspacing="0" class="detail">
					<thead style="font-weight:bold">
						<td class="topitem"></td>
						<td class="topitem" nowrap="nowrap">Customer Price</td>
						<td class="topitem">Store Price</td>
					</thead>
					<tbody>
						<tr class="class">
							<td>Subtotal</td>
							<td>
								${{order.price_plus_delivery_markup | formatPrice}}
							</td>
							<td>
								${{order.price | formatPrice}}
							</td>
						</tr>
						<tr ng-if="order._tip">
							<td>Tip <span ng-if="order.tip_type != 'number'">%</span></td>
							<td>${{order._tip | formatPrice}}</td>
							<td>
								&mdash;
							</td>
						</tr>
						<tr ng-if="order.delivery_fee">
							<td>Delivery Fee</td>
							<td>${{order.delivery_fee | formatPrice}}</td>
							<td>
								&mdash;
							</td>
						</tr>
						<tr ng-if="order.service_fee">
							<td>Service Fee</td>
							<td>${{order.service_fee | formatPrice}}</td>
							<td>
								&mdash;
							</td>
						</tr>
						<tr>
							<td>Tax</td>
							<td>
								${{order._tax | formatPrice}}
							</td>
							<td>
								${{order._tax | formatPrice}}
							</td>
						</tr>
						<tr>
							<td><strong>Total</strong></td>
							<td>
								<strong>${{order.final_price_plus_delivery_markup | formatPrice}}</strong>
							</td>
							<td>
								<strong>${{order._final_price | formatPrice}}</strong>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

<spinner-loading></spinner-loading>
<hack-expand-content></hack-expand-content>