<div class="top-pad"></div>

<div class="content-padding" ng-show="ready">

	<h1 class="title left"><i class="fa fa-bank"></i><span>Settlement</span></h1>

	<div class="divider"></div>

	<h2 class="link title" ng-click="restaurants()">Restaurants</h2>
	<h2 class="link title" ng-click="drivers()">Drivers</h2>

	<div class="divider"></div>

</div>

<spinner-loading></spinner-loading>
<hack-expand-content></hack-expand-content>