<div class="top-pad"></div>

<div class="content-padding" ng-show="ready">

	<h1 class="title left"><i class="fa fa-bank"></i><span>Settlement</span></h1>

	<div class="divider"></div>

	<h2 class="title">Restaurants</h2>
	<h3 class="title link" ng-click="restaurants()">New Payment</h3>
	<h3 class="title link" ng-click="restaurants_payments()">Payments list</h3>
	<h3 class="title link" ng-click="restaurants_scheduled_payments()">Scheduled Payments (not finished or error)</h3>
	<hr/>
	<h2 class="title">Drivers</h2>
	<h3 class="title link" ng-click="drivers()">New Payment</h3>

	<div class="divider"></div>

</div>

<spinner-loading></spinner-loading>
<hack-expand-content></hack-expand-content>