<div class="top-pad"></div>

<div class="content-padding" ng-show="ready">

	<h1 class="title left"><i class="fa fa-bank"></i><span>Settlement:: Drivers</span></h1>

	<div class="divider"></div>

	<form name="form" novalidate ng-show="showForm">

		<ul ng-class="{'submitted':submitted}" class="ul-inputs box-content">

			<li class="li-input" ng-class="{'error':form.rangeStart.$invalid}">
				<div class="label">Date start:</div>
				<div class="input"><input type="date" name="rangeStart" ng-model="range.start" required placeholder=""></div>
				<div class="box-error">
					<small ng-show="form.rangeStart.$error.required">Required.</small>
					<small ng-show="form.rangeStart.$error.date">Enter a valid start date!</small>
				</div>
			</li>

			<li class="li-input" ng-class="{'error':form.rangeEnd.$invalid}">
				<div class="label">Date end:</div>
				<div class="input"><input type="date" name="rangeEnd" ng-model="range.end" required placeholder=""></div>
				<div class="box-error">
					<small ng-show="form.rangeEnd.$error.required">Required.</small>
					<small ng-show="form.rangeEnd.$error.date">Enter a valid end date!</small>
				</div>
			</li>
<?php /*
			<li class="li-input" ng-class="{'error':form.paymentType.$invalid}">
				<div class="label">Payment type:</div>
				<select name="paymentType" required ng-model="pay_type" ng-options="opt.value as opt.name for opt in pay_type_options" class="cart-customize-select"></select>
				<div class="box-error">
					<small ng-show="form.paymentType.$error.required">Required.</small>
				</div>
			</li>

			<li class="li-input" ng-class="{'error':form.sort.$invalid}">
				<div class="label">Sort by:</div>
				<select name="sort" required ng-model="sort" ng-options="opt.value as opt.name for opt in sort_options" class="cart-customize-select"></select>
				<div class="box-error">
					<small ng-show="form.sort.$error.required">Required.</small>
				</div>
			</li>
*/ ?>
			<li class="li-input" ng-show="!isSearching">
				<button class="button save" ng-click="begin();">Begin</button>
			</li>

			<li class="li-input" ng-show="isSearching">
				<span><i class="fa fa-circle-o-notch fa-spin"></i> Loading</span>
			</li>

		</ul>

	</form>

	<div class="box-content" ng-show="!showForm">
		<p>
			Listing orders from <strong>{{range.start | date:'MM/dd/yyyy'}}</strong> to <strong>{{range.end | date:'MM/dd/yyyy'}}</strong>.
			<br>
			<span class="link" ng-click="showForm = true">Show form</span>
		</p>
	</div>

	<div ng-if="result">

		<h2 class="title">
			<span>Summary</span>
		</h2>

		<div>
			<table class="tb-grid tb-zebra summary">
				<tbody>
					<tr>
						<td>Total Drivers</td>
						<td>{{result.total_drivers}}</td>
					</tr>
					<tr>
						<td>Total Orders</td>
						<td>{{result.total_orders}}</td>
					</tr>
					<tr positive-or-negative-color="{{result.total_payments}}">
						<td>Total Payments</td>
						<td>$ {{result.total_payments | formatPrice}}</td>
					</tr>
				</tbody>
			</table>
		</div>

		<div ng-repeat="driver in result.drivers">

			<br/><br/><br/>

			<h2 class="title">
				<span>{{driver.name}}</span>
			</h2>
			<h3 class="title" ng-if="driver.last_payment">
				Last payment #{{driver.last_payment.id_payment}}: <strong positive-or-negative-color="{{driver.last_payment.amount}}">$ {{driver.last_payment.amount | formatPrice}}</strong> on <strong>{{driver.last_payment.date}}</strong>
			</h3>
			<table class="tb-grid tb-zebra">
				<tbody>
					<tr positive-or-negative-color="{{driver.subtotal}}">
						<td>Subtotal</td>
						<td>$ {{driver.subtotal | formatPrice}}</td>
					</tr>
					<tr positive-or-negative-color="{{driver.tax}}">
						<td>Tax</td>
						<td>$ {{driver.tax | formatPrice}}</td>
					</tr>
					<tr positive-or-negative-color="{{driver.delivery_fee}}">
						<td>Delivery Fee</td>
						<td>$ {{driver.delivery_fee | formatPrice}}</td>
					</tr>
					<tr positive-or-negative-color="{{driver.tip}}">
						<td>Tip</td>
						<td>$ {{driver.tip | formatPrice}}</td>
					</tr>
					<tr positive-or-negative-color="{{driver.gift_card}}">
						<td>Gift Card</td>
						<td>$ {{driver.gift_card | formatPrice}}</td>
					</tr>
					<tr positive-or-negative-color="{{driver.credit_charge}}">
						<td>Credit Card Charge</td>
						<td>$ {{driver.credit_charge | formatPrice}}</td>
					</tr>
					<tr positive-or-negative-color="{{driver.restaurant_fee}}">
						<td>Restaurant Fee</td>
						<td>$ {{driver.restaurant_fee | formatPrice}}</td>
					</tr>
					<tr class="total-due" positive-or-negative-color="{{driver.total_due}}">
						<td class="td-medium">Total due</td>
						<td class="td-medium">$ {{driver.total_due | formatPrice}}</td>
					</tr>
				</tbody>
			</table>

			<h3 class="title link" ng-if="!driver.show_orders" ng-click="driver.show_orders = true">Show orders (total {{driver.orders_count}} orders )</h3>
			<h3 class="title link" ng-if="driver.show_orders" ng-click="driver.show_orders = false">Hide orders (total {{driver.orders_count}} orders )</h3>

			<table class="tb-grid tb-zebra" ng-if="driver.show_orders">
				<thead>
					<tr>
						<td>#</td>
						<td class="td-medium">Restaurant</td>
						<td class="td-medium">Name</td>
						<td>Amount</td>
						<td>Payment</td>
						<td class="td-medium">Date</td>
						<td></td>
					</tr>
				</thead>
				<tbody>
					<tr ng-repeat="order in driver.orders">
						<td>{{order.restaurant}}</td>
						<td>{{order.id_order}}</td>
						<td>{{order.name}}</td>
						<td>$ {{order.total | formatPrice}}</td>
						<td>{{order.pay_type}}</td>
						<td>{{order.date}}</td>
					</tr>
				</tbody>
			</table>

		</div>

	</div>

</div>

<spinner-loading></spinner-loading>
<hack-expand-content></hack-expand-content>