<?
	$this->title = 'Suggestions';
	$this->subtitle = 'people want shit.';
	$this->titleicon = 'envelope-alt';
?>



<!-- content -->
<div class="container-fluid padded">
	<div class="row-fluid">
		<div class="box">

			<div class="box-content">
				<div class="row-fluid">
					<form class="fill-up">
						<div class="span6 separate-sections">
							<ul class="padded separate-sections">
								<li class="input">
									<input name="suggestion-search" type="text" placeholder="Search" value="<?=strip_tags($_REQUEST['search'])?>">
								</li>
								<li>
									<label class="span3">Type</label>
									<span class="span8 pull-right">
										<select name="type" class="uniform">
											<option value="">[ All ]</option>
											<option value="dish">Dish</option>
											<option value="restaurant">Restaurant</option>
										</select>
									</span>
									<div class="clearfix"></div>
								</li>
								<li>
									<label class="span3">Limit</label>
									<span class="span8 pull-right">
										<? $envs = ['live','beta','dev','local']; ?>
										<input type="number" name="limit" value="25" min="0">
									</span>
								</li>
							</ul>	
						</div>
						
						<div class="span6 separate-sections">
							<ul class="padded separate-sections">
								<li class="input">
									<?
										$date = new DateTime('now');
										$start = $date->format('m/d/Y');
										$date->modify('14 days ago');
										$end = $date->format('m/d/Y');
									?>
									<label class="span3">Date range</label>
									<span class="span8 pull-right">
										<input name="date-range" class="date-picker" type="text" style="width: 200px;" value="<?=$end?>,<?=$start?>">
										<input type="checkbox" name="order-range-all"><label>&nbsp;All Dates</label>
									</span>
									<div class="clearfix"></div>
			
								</li>
								<li>
									<label class="span3">Status</label>
									<span class="span8 pull-right">
										<select name="status" class="uniform">
											<option value="" selected>[ All ]</option>
											<option value="new" selected>new</option>
											<option value="deleted">deleted</option>
											<option value="applied">applied</option>
										</select>
									</span>
									<div class="clearfix"></div>
								</li>
								<li>
									<label class="span3">Restaurant</label>
									<span class="span8 pull-right">
										<select name="restaurant" class="chzn-select">
											<option value="" selected>[ All ]</option>
											<? foreach (Restaurant::q('select * from restaurant order by name') as $restaurant) : ?>
												<option value="<?=$restaurant->id_restaurant?>"><?=$restaurant->name?></option>
											<? endforeach ; ?>
										</select>
									</span>
									<div class="clearfix"></div>
								</li>
								<li>
									<label class="span3">Community</label>
									<span class="span8 pull-right">
										<select name="community" class="chzn-select">
											<option value="" selected>[ All ]</option>
											<? foreach (Community::q('select * from community order by name') as $community) : ?>
												<option value="<?=$community->id_community?>"><?=$community->name?></option>
											<? endforeach ; ?>
										</select>
									</span>
									<div class="clearfix"></div>
								</li>
							</ul>	
						</div>
					</form>

				</div>
				
			</div>
			<center>
				<button type="submit" class="btn btn-blue admin-suggestion-search"> Search </button> 
			</center>
			<br />
		</div>
	</div>
</div>

<div class="container-fluid padded">
	<div class="row-fluid">
		<div class="box">
			<div class="box-header"><span class="title">Results</span></div>
			<div class="box-content">
				<div class="suggestions-loader"><center><i class="icon-spinner icon-spin" style="font-size: 50px;"></i></center></div>
				<div class="suggestions-content"></div>
			</div>
		</div>
	</div>
</div>




<script>
	$(function() {		
		$(document).on('click', '.admin-suggestion-search', function() {
			App.suggestions.load();
		} );

		$(document).on('keyup', '[name="suggestion-search"]', function( e ) {
			if (e.which == 13) {
				App.suggestions.load();
			}
		} );

		$(document).on('change', 'input[name="suggestion-range-all"]', function( e ) {
			if ($(this).prop('checked')) {
				$('.date-picker').attr('disabled', 'disabled');
				$('.date-picker').val('');
			} else {
				$('.date-picker').removeAttr('disabled');
			}
		});
		App.suggestions.load();
	});
</script>