<?
	$this->title = 'Suggestions';
	$this->titleicon = 'envelope-alt';
	$this->titleLink = '/suggestions';
	
	$this->title2 = 'Suggestion #' . $this->suggestion->id_suggestion;
	$this->title2icon = 'envelope';

if( $this->suggestion->status == 'deleted' ){
	$status = 'black';
} else if ( $this->suggestion->status == 'new' ){
	$status = 'green';
} else if ( $this->suggestion->status == 'applied' ){
	$status = 'blue';
}
?>
<div class="container-fluid padded">
	<div class="row-fluid">
		<div class="span6">
			<div class="box">
				<div class="box-header">
					<span class="title">Info</span>
					<ul class="box-toolbar">
						<li><span class="label label-<?=$status;?>"><?=strtoupper($this->suggestion->status) ?></span></li>
					</ul>
				</div>
				<div class="box-content ">
					<table class="table table-striped ">
						<tr>
							<td>Name</td>
							<td>
								<?=$this->suggestion->name;?>
							</td>
						</tr>
						<tr>
							<td>Content</td>
							<td>
								<?=nl2br($this->suggestion->content);?>
							</td>
						</tr>
						<tr>
							<td>Type</td>
							<td>
								<?=$this->suggestion->type;?>
							</td>
						</tr>
						<tr>
							<td>Date</td>
							<td><?=$this->suggestion->date()->format('M jS Y')?> - <?=$this->suggestion->date()->format('g:i:s A')?></td>
						</tr>
					</table>
				</div>
			</div>
		</div>
		<div class="span6">
			<div class="box">
				<div class="box-header">
					<span class="title">User</span>
				</div>
				<div class="box-content ">
					<table class="table table-striped ">
						<?php if( $this->suggestion->user()->id_user ) { ?>
						<tr>
							<td>User</td>
							<td>
								<?=$this->suggestion->user()->name;?>
							</td>
						</tr>
						<?php } ?>
						<?php if( $this->suggestion->user()->phone ) { ?>
						<tr>
							<td>Phone</td>
							<td>
								<?=$this->suggestion->user()->phone;?>
							</td>
						</tr>
						<?php } ?>
						<tr>
							<td>Type</td>
							<td>
								<?=$this->suggestion->type;?>
							</td>
						</tr>
						<tr>
							<td>IP</td>
							<td><?=$this->suggestion->ip;?></td>
						</tr>
					</table>
				</div>
			</div>
		</div>
	</div>

	<div class="row-fluid">
		<div class="span6">
			<div class="box">
				<div class="box-header">
					<span class="title">Update</span>
				</div>
				<div class="box-content ">
					<form class="fill-up">
						<ul class="padded separate-sections">
							<li>
								<label>Status</label>
								<? $states = ['new','deleted','applied']; ?>
								<select class="chzn-select" name="status" id="status">
								<? 
								foreach ($states as $status) { 
									$selected = ( $status == $this->suggestion->status ) ? 'selected="selected"' : '';
								?>
									<option <?=$selected?> value="<?=$status?>"><?=$status?></option>
								<? } ?>
								</select>
							</li>
						</ul>
						<div class="form-actions">
							<button type="button" class="btn btn-blue suggestion-save">Save changes</button>
						</div>
					</form>
				</div>
			</div>
			</div>
		</div>
</div>
<script>
$(function() {
	$(document).on('click', '.suggestion-save', function() {
		var status = $( '#status' ).val();
		var data = { 'status' : status };
		var url = App.service + 'suggestion/<?php echo $this->suggestion->id_suggestion; ?>';
		$.ajax({
			type: "POST",
			dataType: 'json',
			data: data,
			url: url,
			success: function(content) {
				alert( 'Suggestion saved!' );
				document.location.reload();
			},
			error: function( ){
				alert( 'Error, please try it again.' );
			}
		});
	} );
});
</script>