<?php 
$orders = $this->orders; 
$showAll = !$this->justMineOrders;
?>
<div class="control">
	<div class="wrap order-status-init">
		<b>List</b> | 
		<?php if( $showAll ) { ?>
			<strong>Show all</strong> | <a href="/mine">Show mine</a>
		 <?php } else { ?>
		 	<a href="/">Show all</a> | <strong>Show mine</strong>
		 <?php } ?>
		
		<div class="divider"></div>
	</div>
</div>

<div class="content">
	<div class="wrap">
		<?php 
		$id_admin = c::admin()->id_admin;
		foreach( $orders as $order ) { 
			$date = $order->date;
			$status = $order->lastStatus;
			$action = '';
			$orderLink = false;
			if( $id_admin == $status[ 'id_admin' ] ){
				$orderLink = true;
			} 
			switch ( $status[ 'status' ] ) {
				case 'delivered':
					if( $orderLink ){ $action = 'delivered'; } else { $action = 'other'; }
					$orderLink = false;
					$action = 'other';
					$info = 'Delivered by ' . $status[ 'name' ];
					break;
				case 'pickedup':
					if( $orderLink ){ $action = 'pickedup'; } else { $action = 'other'; }
					$info = 'Picked up by ' . $status[ 'name' ];
					break;
				case 'accepted':
					if( $orderLink ){ $action = 'accepted'; } else { $action = 'other'; }
					$info = 'Accepted by ' . $status[ 'name' ];
					break;
				case 'new':
				default:
					$action = 'new';
					$orderLink = true;
					break;
			}
			if( $orderLink && $action != 'delivered'){
				$info = $order->name . ' <br/>'. $order->phone;
			}
			?>
			<div class="order-list-item <?php echo $action; ?>">
				<?php 
					if( $orderLink ){ ?>
						<div class="order-list-action">
						<?php
						switch ( $action ) {
							case 'new':
								?>
								<button id_order="<?php echo $order->id_order; ?>" class="button button-list-accept"> Accept? </button>
								<?php
								break;
							case 'accepted':
								?>
								<button id_order="<?php echo $order->id_order; ?>" class="button button-list-pickedup"> Picked up? </button>
								<?php
								break;
							case 'pickedup':
								?>
								<button id_order="<?php echo $order->id_order; ?>" class="button button-list-delivered"> Delivered? </button>
								<?php
								break;
						} ?>
						</div>
						<?php
					}
				?>
				<div class="order-list-date">
					<div class="day">
						<?php echo $date->format( 'm/d' ); ?>
					</div>
					<div class="hour">
						<?php echo $date->format( 'h:i' ); ?>
					</div>
					<div class="ampm">
						<?php echo $date->format( 'a' ); ?>
					</div>
				</div>
				<div class="order-list-customer-info">
					<div class="restaurant">
						<?php if( $orderLink ) { ?>
							<a href="/<?php echo $order->id_order; ?>">
						<?php } ?>
							<?php echo $order->restaurant; ?>
						<?php if( $orderLink ) { ?>
							</a>
						<?php } ?>
					</div>
					<div class="customer">
						<?php if( $orderLink ) { ?>
							<a href="/<?php echo $order->id_order; ?>">
						<?php } ?>
							<?php echo $info; ?>
						<?php if( $orderLink ) { ?>
							</a>
						<?php } ?>
					</div>
				</div>
				<div class="divider"></div>
			</div>
		<?php } ?>
	</div>
</div>