
<table width="100%" celpadding="0" cellspacing="0">
	<thead style="font-weight:bold">
		<td>Qty</td>
		<td>Item</td>
		<td>Price</td>
	</thead>

	<? foreach ($order->dishes() as $dish) : ?>
		<tr>
			<td>1</td>
			<td><?
				$food = $dish->dish()->name;
				$cartPrice = $dish->dish()->price;
				$options = $dish->options();

				if (gettype($options) == 'array') {
					$options = i::o($options);
				}

				if ($options->count()) {
					$food .= '<i>&nbsp;&nbsp;&nbsp;w/&nbsp;&nbsp;&nbsp;';

					foreach ($dish->options() as $option) {
						if ($option->option()->type == 'select') {
							continue;
						}
						$cartPrice += $option->option()->price;
						if($option->option()->id_option_parent) {
							$optionGroup = Crunchbutton_Option::o($option->option()->id_option_parent);
							$food .= "$optionGroup->name: ";
						}
						$food .= $option->option()->name.', ';
					}
					$food = substr($food, 0, -2);

					$food .= '</i>';
				}

				$withoutDefaultOptions = '';

				$optionsNotChoosen = $dish->optionsDefaultNotChoosen();
				$commas = ' ';
				if( $optionsNotChoosen->count() ){
					foreach( $optionsNotChoosen as $dish_option ){
						$withoutDefaultOptions .= $commas . '<i> No ' . $dish_option->option()->name . '</i>';
						$commas = ', ';
					}
				}

				if ( $options->count() && $withoutDefaultOptions != '' ) {
					$food .= '. ';
				}
				$food .= $withoutDefaultOptions;

				?>
				<?=$food?>
			</td>
			<td>$<?=number_format($cartPrice,2)?></td>
		</tr>
	<? endforeach ; ?>

	<tr class="class">
		<td></td>
		<td style="text-align:right">Subtotal</td>
		<td>$<?=number_format($order->price,2)?></td>
	</tr>
	<? if ($order->pay_type == 'card' && $order->tip) : ?>
		<tr>
			<td></td>
			<td style="text-align:right">Tip <?php if( $order->tip_type != Crunchbutton_Order::TIP_NUMBER ) { echo $order->tip . '%'; } ?></td>
			<td>$<?=$order->tip()?></td>
		</tr>
	<? endif ; ?>
	<? if ($order->restaurant()->delivery_fee) : ?>
		<tr>
			<td></td>
			<td style="text-align:right">Delivery Fee</td>
			<td>$<?=$order->deliveryFee()?></td>
		</tr>
	<? endif ; ?>

	<? if ($order->restaurant()->fee_customer) : ?>
		<tr>
			<td></td>
			<td style="text-align:right">Service Fee</td>
			<td>$<?=$order->serviceFee()?></td>
		</tr>
	<? endif ; ?>
	
	<tr>
		<td></td>
		<td style="text-align:right">Tax</td>
		<td>$<?=$order->tax()?></td>
	</tr>

	<tr style="font-weight:bold;">
		<td></td>
		<td style="text-align:right">Total</td>
		<td>$<?=number_format($order->final_price,2)?></td>
	</tr>
	
	<?php /* Just the user and CB will see this info about gift card. See #1006. */ ?>
	<?php if( $user && $order->chargedByCredit() > 0 ) { ?>
	<tr style="font-weight:bold;">
		<td></td>
		<td style="text-align:right"><?php if( $order->pay_type == 'card' ) { ?>Gift Card <?php } else { ?> Already Paid by Gift Card <?php } ?></td>
		<td>$<?=number_format($order->chargedByCredit(),2)?></td>
	</tr>

	<tr style="font-weight:bold;">
		<td></td>
		<td style="text-align:right"><?php if( $order->pay_type == 'card' ) { ?>Total Charged <?php } else { ?> Total Owed <?php } ?></td>
		<td>$<?=number_format($order->charged(),2)?></td>
	</tr>
	<?php } ?>

</table>
