

<div class="xhatch separator-big"></div>

<table width="100%" cellpadding="0" cellspacing="0">
	<tr>
		<td style="border: 0; padding: 5px;">
			<h1 title="<?=$order->id_restaurant == 1 ? 'One Button Wenzel' : 'Crunchbutton'?>"><?=$order->id_restaurant == 1 ? 'One Button Wenzel' : 'Crunchbutton'?></h1>
		</td>
		<td style="border: 0; padding: 5px; text-align: right;">
			<span class="order-num">Order #<?=$order->id_order?></span><br />
			<?=$order->date()->format('M jS, h:i a')?>
		</td>
	</tr>
</table>

<div class="xhatch separator-small"></div>

<table width="100%" cellpadding="0" cellspacing="0">
	<tr>
		<td>
			<? if ($order->delivery_type == 'delivery') : ?>
				<table cellpadding="0" cellspacing="0"><tr>
					<td><img src="<?=$this->helper('ImageBase64')->output(c::config()->dirs->www.'assets/images/mprinter/delivery.png')?>" class="icon-big"></td>
					<td class="text-size-mid">Order for Delivery</td>
				</tr></table>
			<? else : ?>
				<table cellpadding="0" cellspacing="0"><tr>

					<td><img src="<?=$this->helper('ImageBase64')->output(c::config()->dirs->www.'assets/images/mprinter/takeout.png')?>" class="icon-big"></td>
					<td class="text-size-mid">Order for Takeout</td>
				</tr></table>
			<? endif ; ?>
		</td>
		<td>
			<? if ($order->pay_type == 'card') : ?>
				<table cellpadding="0" cellspacing="0"><tr>
					<td><img src="<?=$this->helper('ImageBase64')->output(c::config()->dirs->www.'/assets/images/mprinter/card.png')?>" class="icon-big"></td>
					<td class="text-size-mid">Prepaid by card</td>
				</tr></table>
			<? else : ?>
				<table cellpadding="0" cellspacing="0"><tr>
					<td><img src="<?=$this->helper('ImageBase64')->output(c::config()->dirs->www.'/assets/images/mprinter/cash.png')?>" class="icon-big"></td>
					<td class="text-size-mid">Cash order</td>
				</tr></table>
			<? endif ; ?>
		</td>
		<td>
			<table cellpadding="0" cellspacing="0"><tr>
				<td><img src="<?=$this->helper('ImageBase64')->output(c::config()->dirs->www.'/assets/images/mprinter/timer.png')?>" class="icon-big"></td>
				<td class="text-size-mid">Expected by <?=$order->expectedBy()->format('h:i')?></td>
			</tr></table>
		</td>
	</tr>
</table>




<? if ($order->notes) : ?>
	<div class="xhatch separator-small"></div>

	<table class="notes" cellpadding="0" cellspacing="0">
		<tr>
			<td valign="top"><img src="<?=$this->helper('ImageBase64')->output(c::config()->dirs->www.'/assets/images/mprinter/note.png')?>" class="icon-note"></td>
			<td style="margin: 0; padding: 22px 0 0 0;" valign="top"><div class="arrow-left"></div></td>
			<td style="width: 100%; padding-right: 0; "><table style="width: 100%"><tr><td class="notes-content"><?=nl2br($order->notes)?></td></tr></table></td>
		</tr>
	</table>
<? endif ; ?>

<div class="xhatch separator-small"></div>


<table width="100%" celpadding="0" cellspacing="0">
	<tr>
		<td style="width: 50%">
			<table cellpadding="0" cellspacing="0"><tr>
				<td><img src="<?=$this->helper('ImageBase64')->output(c::config()->dirs->www.'/assets/images/mprinter/customer.png')?>" class="icon-big"></td>
				<td class="text-size-mid"><?=$order->name?><br /><?=$order->phone()?></td>
			</tr></table>
		</td>
		<td>
			<table cellpadding="0" cellspacing="0"><tr>
				<td><img src="<?=$this->helper('ImageBase64')->output(c::config()->dirs->www.'/assets/images/mprinter/restaurant.png')?>" class="icon-big"></td>
				<td class="text-size-mid"><?=$order->restaurant()->name?><br /><?=$order->restaurant()->phone?></td>
			</tr></table>
		</td>
	</tr>
	<tr>
		<td style="width: 50%">
			<? if ($order->delivery_type == 'delivery') : ?>
				<table cellpadding="0" cellspacing="0"><tr>
					<td><img src="<?=$this->helper('ImageBase64')->output(c::config()->dirs->www.'/assets/images/mprinter/map.png')?>" class="icon-big"></td>
					<td class="text-size-mid"><?=nl2br(strip_tags($order->address))?></td>
				</tr></table>
			<? endif ; ?>
		</td>
		<td style="width: 50%">
			<? if ($order->_print && $order->delivery_type == 'takeout') : ?>
				<table cellpadding="0" cellspacing="0"><tr>
					<td><img src="<?=$this->helper('ImageBase64')->output(c::config()->dirs->www.'/assets/images/mprinter/map.png')?>" class="icon-big"></td>
					<td class="text-size-mid"><?=nl2br(strip_tags($order->restaurant()->address))?></td>
				</tr></table>
			<? endif ; ?>
		</td>
	</tr>

</table>

<div class="xhatch separator-small"></div>




<?=$this->render('order/details',['set' => ['order' => $order, 'user' => $user]]);?>
<br /><br />
<? if (!$order->_print) : ?>
	<table cellpadding="0" cellspacing="0" style="width: 100%; margin-top: 20px;">
		<tr>
			<td style="text-align: left;" class="text-size-small"><? if ($order->pay_type == 'card') : ?>Card on file. Signature not required.<? endif ; ?></td>
			<td style="text-align: right;" class="text-size-small">Crunchbutton support: <?=c::config()->phone->restaurant?></td>
		</tr>
	</table>
<? endif ; ?>

<div class="xhatch separator-big"></div>



<? if (!$user && $order->restaurant()->customer_receipt) : ?>
	<br /><br />
	<div style="border-top: 1px dashed black"> </div>
	<br /><br />
	
	<h2 align="center">Customer Copy</h2>
	<br /><br />
	<h1 style="text-align: center"><?=$order->restaurant()->name?></h1>
	<br /><br />
	<?=$this->display('order/details',['set' => ['order' => $order]])?>
<? endif ; ?>




<? if ($order->_print) : ?>
<script>window.print();</script>
<? endif ; ?>
