<div class="top-pad"></div>

<div class="content-padding">
	<h1 class="title"><i class="fa fa-bar-chart"></i>Metrics<div class="title-loader" ng-if="loading"></h1>
	<div class="box-content2">
		<form>
			<!-- changes here are handled by explicit watch in controller so we can set a timeout -->
			<input type='text' ng-model='settings.start'>
			<input type='text' ng-model='settings.end'>
			<div>Communities:
			<div multi-select input-model="multiSelectCommunities" button-label="name" item-label="name" tick-property="selected"
				on-item-click='orderSelectedCommunities()'
				on-cose='orderSelectedCommunities()'
				max-labels='3' style='height:10px'></div>
			</div>
			<select ng-options='period.symbol as period.description for period in availablePeriods' ng-model='settings.period' ng-change='refreshData()'></select>
			<button name='refresh' ng-click='refreshData()'>Refresh</button>
			<button name='addChart' ng-click='addChart()'>Add Chart</button>
			<button ng-click='toggleCombinedView()'>Show/Hide Combined</button>
			<div ng-repeat='chartOption in settings.charts'>
				<select ng-options='chart.type as chart.description for (t, chart) in availableCharts' ng-model='chartOption.type' ng-change='updateChartOption(chartOption)'></select>
				<select ng-options='item.kind as item.description for item in sortMethods' ng-model='chartOption.orderMethod' ng-change='updateChartOrders(chartOption, true)'></select>
				<select ng-options='item.kind as item.description for item in sortDirections' ng-model='chartOption.orderDirection' ng-change='updateChartOrders(chartOption, true)'></select>
				<select ng-options='item.kind as item.description for item in setScales' ng-model='chartOption.uniformScale' ng-change='updateChartOption(chartOption)'></select>
				<button name='removeChart' ng-click='removeChartOption(chartOption)'>X</button>
			</div>
		</form>
	</div>
	<div  ng-if='settings.separateCharts' ng-repeat='community in orderedCommunities'>
		{{community.name}}
		<div ng-repeat='chartOption in settings.charts' style="display:inline;width:40%;height:300px;">
			<h3 style='text-align:center'>{{availableCharts[chartOption.type].description}}</h3>
			<canvas class="chart chart-line" data="chartData[community.id_community][chartOption.type].data"
				options="chartData[community.id_community][chartOption.type].options"
				labels="chartData[community.id_community][chartOption.type].labels"
				legend="false"></canvas>
		</div>
	</div>
	<div ng-if='!settings.separateCharts' ng-repeat='chartOption in settings.charts'>
		<h3 style='text-align:center'>{{availableCharts[chartOption.type].description}}</h3>
		<canvas ng-if='orderedCommunities.length <= settings.maxCombinedCommunities'
			class="chart chart-line" data="combinedChartData[chartOption.type].data"
			options="combinedChartData[chartOption.type].options"
			labels="combinedChartData[chartOption.type].labels"
			series="combinedChartData[chartOption.type].series"
			legend="true"></canvas>
		<div ng-if='orderedCommunities.length > settings.maxCombinedCommunities'>
			<p>Too many communities to show combined chart.</p>
			<p>(select at most {{settings.maxCombinedCommunities}})</p>
		</div>
	</div>
</div>
