<!doctype html>
<html>
<head>
<title><?=$this->title ? $this->title : 'Crunchbutton'?></title>
<? /* <meta name="viewport" content="user-scalable=no, initial-scale = 1.0,maximum-scale = 1.0"> */ ?>
<meta name="viewport" content="initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0" />

<meta http-equiv="X-UA-Compatible" content="IE=edge" />

<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<link rel="apple-touch-icon-precomposed" href="/assets/images/micro/appicon.png">

<? if (c::config()->bundle) : ?>
	<link rel="stylesheet" type="text/css" href="/assets/css/bundle.css?v=<?=Cana_Util::gitVersion()?>&s=microsite">
<? else : ?>
	<?=$this->display('bundle/css', ['set' => ['style' => ['microsite']]])?>
<? endif ; ?>

<link rel="stylesheet" type="text/css" href="/assets/css/font-awesome.css?v=<?=Cana_Util::gitVersion()?>">
<link rel="shortcut icon" href="/assets/images/micro/favicon.ico">

<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,300,700" rel="stylesheet" type="text/css">

<script type="text/javascript" src="https://www.google.com/jsapi"></script>



