<?=$this->display('layout/html.top')?>

<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
<script src="/assets/js/jquery.autosize-min.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/js/jquery.dropdown-min.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/js/microsite.js?v=<?=Cana_Util::gitVersion()?>"></script>

<?=$this->display('layout/html.bottom')?>