<?php 
$orders = $this->orders; 
$showAll = !$this->justMineOrders;
$hours = $this->hours;
?>
<div class="content">
	<div class="wrap">
		<div class="warning">
			In order to receive payment for orders that you deliver, you <strong>MUST</strong> confirm all orders that you've delivered. <br/> Check back here at the of the night to make sure YOUR orders are confirmed and delivered!
		</div>
		<?php 
		if( count( $orders ) > 0 ){
			$id_admin = c::admin()->id_admin;
			foreach( $orders as $order ) { 
				$date = $order->date;
				$status = $order->lastStatus;
				$action = '';
				$orderLink = false;
				if( $id_admin == $status[ 'id_admin' ] ){
					$orderLink = true;
				} 
				switch ( $status[ 'status' ] ) {
					case 'delivered':
						if( $orderLink ){ $action = 'delivered'; } else { $action = 'other'; }
						$orderLink = false;
						$action = 'other';
						$info = 'Delivered by ' . $status[ 'name' ];
						break;
					case 'pickedup':
						if( $orderLink ){ $action = 'pickedup'; } else { $action = 'other'; }
						$info = 'Picked up by ' . $status[ 'name' ];
						break;
					case 'accepted':
						if( $orderLink ){ $action = 'accepted'; } else { $action = 'other'; }
						$info = 'Accepted by ' . $status[ 'name' ];
						break;
					case 'new':
					default:
						$action = 'new';
						$orderLink = true;
						break;
				}
				if( $orderLink && $action != 'delivered'){
					$info = $order->name . ' <br/>'. $order->phone;
				}
				?>
				<div class="order-list-item <?php echo $action; ?>">
					<?php 
						if( $orderLink ){ ?>
							<div class="order-list-action">
							<?php
							switch ( $action ) {
								case 'new':
									?>
									<button id_order="<?php echo $order->id_order; ?>" class="button button-list-accept"> Accept? </button>
									<?php
									break;
								case 'accepted':
									?>
									<button id_order="<?php echo $order->id_order; ?>" class="button button-list-pickedup"> Picked up? </button>
									<?php
									break;
								case 'pickedup':
									?>
									<button id_order="<?php echo $order->id_order; ?>" class="button button-list-delivered"> Delivered? </button>
									<?php
									break;
							} ?>
							</div>
							<?php
						}
					?>
					<div class="order-list-date">
						<div class="day">
							<?php echo $date->format( 'm/d' ); ?>
						</div>
						<div class="hour">
							<?php echo $date->format( 'h:i' ); ?>
						</div>
						<div class="ampm">
							<?php echo $date->format( 'a' ); ?>
						</div>
					</div>
					<div class="order-list-customer-info">
						<div class="restaurant">
							<?php if( $orderLink ) { ?>
								<a href="/<?php echo $order->id_order; ?>">
							<?php } ?>
								<?php echo $order->restaurant; ?>
							<?php if( $orderLink ) { ?>
								</a>
							<?php } ?>
						</div>
						<div class="customer">
							<?php if( $orderLink ) { ?>
								<a href="/<?php echo $order->id_order; ?>">
							<?php } ?>
								<?php echo $info; ?>
							<?php if( $orderLink ) { ?>
								</a>
							<?php } ?>
						</div>
					</div>
					<div class="divider"></div>
				</div>
			<?php 
			} 
		} else { ?>
			<div class="no-orders">
				No orders
			</div>
		<?php } ?>
	</div>
</div>
<script>
	$(document).ready(function(){

		$( '.button-list-accept' ).click( function() {
			var id_order = $( this ).attr( 'id_order' );
			makebusy();
			 $.post('/api/order/' + id_order + '/delivery-accept', function( json ){ 
			 	if( json.status ){
			 		location.reload();
			 	} else {
			 		var name = '';
			 		if( json[ 'delivery-status' ].accepted.name ){
			 			var name = 'by ' + json[ 'delivery-status' ].accepted.name;
			 		}
			 		alert( 'Opos!\n It seems this order was already accepted ' + name + '!'  );
			 		location.reload();	
			 	}
			 }, 'json' ); 
		} );

		$( '.button-list-pickedup' ).click( function() {
			var id_order = $( this ).attr( 'id_order' );
			makebusy();
			 $.post('/api/order/' + id_order + '/delivery-pickedup', function( json ){ location.reload(); },'json'); 
		} );

		$( '.button-list-delivered' ).click( function() {
			var id_order = $( this ).attr( 'id_order' );
			makebusy();
			 $.post('/api/order/' + id_order + '/delivery-delivered', function(){ location.reload(); },'json'); 
		} );


	} );

</script>