<?
	// group up the data by order of data items recieved
	// 0: X
	// 1: Y
	// 2: Group

	$categories = [];
	$ys = [];
	$group = [];
	
	// set up x labels and empty objects
	foreach ($data as $item) {
		$vars = get_object_vars($item);

		// X
		$xName = key($vars);
		$x = array_shift($vars);
		$xs[$x] = true;


		$yName = key($vars);
		$y = array_shift($vars);

		$group = array_shift($vars);
		
		$ys[$group] = [];

	}
	
	foreach ($xs as $k => $v) {
		$xx .= "'".str_replace("'","\\'",$k)."', ";
	}
	$xx = substr($xx,0,-2);
	
	// fill empty columns
	foreach ($xs as $k => $v) {
		foreach ($ys as $kk => $vv) {
			$ys[$kk][$k] = 0;
		}
	}


	// gather data
	foreach ($data as $item) {
		$vars = get_object_vars($item);
		
		// X
		$x = array_shift($vars);
		$xs[$x] = true;

		// Y & group
		$y = array_shift($vars);
		
		$groupName = key($vars);
		$group = array_shift($vars);
		
		$ys[$group][$x] = $y;

	}
	
	// remove assoc vals and add proper keys
	foreach ($ys as $k => $v) {
		$ys[$k] = array_values($ys[$k]);
		$ys[$k] = [
			'name' => $k,
			'data' => $ys[$k]
		];
	}

	
	$jsData = [
		'xs' => array_keys($xs),
		'ys' => array_values($ys)
	];

?>
<div class="row-fluid">
	<div class="row-fluid">
		<div class="span12">
			<h4 style="text-align:center;"><?php echo $title; ?></h4>	
		</div>
	</div>
	<div id="chart-<?=$chartId?>-<?php echo $number; ?>" style="min-width: 100%; height:300px; margin: 0 auto"></div>
	<br/>
	<div class="row-fluid">
		<div class="span3" id="week-<?=$chartId?>-<?php echo $number; ?>">
			Weeks from <?php echo $from; ?> to <?php echo $to; ?> (of <?php echo $totalWeeks; ?>):
		</div>
		<div class="span8">
			<div id="slider-<?=$chartId?>-<?php echo $number; ?>" data-from="<?php echo $from; ?>" data-to="<?php echo $to; ?>"></div>
	</div>
</div>
<hr />
<script type="text/javascript">
$(function () {
	var data = <?=json_encode($jsData, JSON_NUMERIC_CHECK)?>;
	$('#chart-<?=$chartId?>-<?php echo $number; ?>').highcharts({
		chart: {
			type: 'column',
			backgroundColor:'rgba(255, 255, 255, 0.1)'
		},
		title: {
			text: ''
		},
		xAxis: {
			categories: data.xs,
			tickmarkPlacement: 'on',
			title: {
				enabled: false
			},
			labels : {
				rotation: -45,
				align: 'right'
			}
		},
		yAxis: {
			title: {
				text: '<?=$yName?>'
			},
			labels: {
				formatter: function() {
					return this.value;
				}
			}
		},
		tooltip: {
			valueSuffix: ' <?=$unit?>'
		},
		plotOptions: {
			column: {
				pointPadding: 0,
				dataLabels: {
					enabled: false,
					color: ( Highcharts.theme && Highcharts.theme.dataLabelsColor ) || 'white'
				}
			}
		},
		series: data.ys
	});
	$( '#slider-<?=$chartId?>-<?php echo $number; ?>' ).slider( {
		range: true,
		min: 1,
		values: [ <?php echo $from; ?>, <?php echo $to; ?> ],
		max: <?php echo $totalWeeks; ?>,
		change: function( event, ui ) {
			var activeUserDays = $( '#active-user-days' ).val();
			$( '#week-<?=$chartId?>-<?php echo $number; ?>' ).html( '<i class="icon-spinner icon-spin"></i>' );
			$( '#slider-<?=$chartId?>-<?php echo $number; ?>' ).slider( 'disable' );
			$( '#slider-<?=$chartId?>-<?php echo $number; ?>' ).css( 'opacity', 0.4 );
			var self = $( '#<?=$chartId?>-<?php echo $number; ?>' );
			var url = '/home/charts/<?=$chartId?>/<?php echo $title; ?>/<?php echo $number; ?>/?from=' + ui.values[ 0 ] + '&to=' + ui.values[ 1 ] + '&activeUserDays=' + activeUserDays;
			$.ajax( { url: url, }).done(function( data ) { self.html( data ); } );
		}
	} );
});
</script>
