<div class="row-fluid">

	<div class="row-fluid">
		<div class="span12">
			<h4 style="text-align:center;">Orders by Restaurant</h4>	
		</div>
	</div>

	<?php if( $groups ){ ?>
		<span class="pull-right">
			<select class="charts-select" id="select-<?=$chartId?>" data-divId="<?php echo $divId; ?>" onchange="loadSubChart( this.id )">
				<?php foreach ( $groups as $key => $value ) { 
					$selected = ( $key == $chartId ) ? 'selected="selected"' : '';
					?>
					<option <?php echo $selected; ?> value="<?php echo $key; ?>"><?php echo $value; ?></option>
				<?php } ?>
			</select>
		</span>
	<?php } ?>

	<?
	$count = 1;
	foreach( $data as $group => $restaurants ){
		// $restaurants
		$info = '';
		foreach( $restaurants as $restaurant ){
			$info .= '["' . $restaurant['Restaurant'] . '",' . $restaurant['Orders'] . '],';
		}
	?>
	<div class="span12">
		<h5 style="text-align:center;"><?php echo $group; ?></h5>	
	</div>
	<div id="chart-<?=$chartId?><?php echo $count; ?>" style="min-width: 100%; height:300px; margin: 0 auto"></div>
	<script type="text/javascript">
	$(function () {
		var data = <?=json_encode($jsData, JSON_NUMERIC_CHECK)?>;
		$('#chart-<?=$chartId?><?php echo $count; ?>').highcharts({
					chart: {
							plotBackgroundColor: null,
							plotBorderWidth: null,
							plotShadow: false,
							backgroundColor:'rgba(255, 255, 255, 0.1)'
					},
					title: {
							text: ''
					},
					tooltip: {
						pointFormat: '{series.name}: <b>{point.y}</b> ({point.percentage:.1f}%)'
					},
					plotOptions: {
							pie: {
									allowPointSelect: true,
									cursor: 'pointer',
									dataLabels: {
											enabled: true,
											color: '#000000',
											connectorColor: '#000000',
											format: '<b>{point.name}</b>: {point.percentage:.1f} %'
									}
							}
					},
					series: [{
							type: 'pie',
							name: 'Orders',
							data: [<?php echo $info; ?>]
					}]
			});
	});
	</script>
	<?php 
	$count++;
	} 
	?>
</div>
</div>