<html>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<style>
	iframe {
		border: 1px solid #333;
		width: 100%
	}
	table {
		width: 100%;
	}
</style>
<body>
<table>
	<tr>
		<td>Stripe</td>
		<td>Balanced</td>
	</tr>
	<tr>
		<td><iframe src="/tests/svb/stripe"></iframe></td>
		<td><iframe src="/tests/svb/balanced"></iframe></td>
	</tr>
</table>
	


</body>
</html>