<div class="top-pad"></div>

<div class="content-padding">

	<h1 class="title box-title"><i class="fa fa-user"></i>{{staff.name}}</h1>
	<div class="divider"></div>
	<div class="bar-loader bar-loader-search bar-loader-boxes-top" ng-class="{'bar-loader-loading': loading}"></div>

	<div class="support-boxes">

		<div class="support-box-wrap box-content2">
			<div class="support-box-wrap-header">
				<h1>Info</h1>
				<div class="divider"></div>
			</div>

			<div class="no-box-content-color">
				<div class="field-container">
					<div class="field-row">
						<div class="field-key">Name</div>
						<div class="field-value">{{staff.name}}</div>
					</div>
					<div class="field-row">
						<div class="field-key">Phone</div>
						<div class="field-value"><a href ng-click="callText(staff.phone)">{{staff.phone | formatPhone}}</a></div>
					</div>
					<div class="field-row">
						<div class="field-key">Email</div>
						<div class="field-value"><a href="mailto:{{staff.email}}">{{staff.email}}</a></div>
					</div>
					<div class="field-row">
						<div class="field-key">Login</div>
						<div class="field-value">{{staff.login}}</div>
					</div>
					<div class="field-row">
						<div class="field-key">Timezone</div>
						<div class="field-value">{{staff.timezone}}</div>
					</div>
					<div class="field-row" ng-if="staff.date_terminated_formatted">
						<div class="field-key">Inactive since</div>
						<div class="field-value">{{staff.date_terminated_formatted}}</div>
					</div>
				</div>

			</div>
		</div>

		<div class="support-box-wrap box-content2">
			<div class="support-box-wrap-header">
				<h1>Permissions</h1>
				<div class="support-box-header-actions-wrap">
					<div class="support-box-header-actions">
						<a href="/permission/staff/{{staff.login}}"><button class="button button-small button-empty button-green"><i class="fa fa-pencil"></i>&nbsp;&nbsp;Edit</button></a>
					</div>
				</div>
				<div class="divider"></div>
			</div>

			<div class="no-box-content-color">
				<div class="field-container">
					<div class="field-row">
						<div class="field-key">Groups</div>
						<div class="field-value">
							<span class="staff-community-repeat" ng-repeat="group in staff.groups_description">
								{{group}}
							</span>
							&nbsp;&nbsp;&nbsp;&nbsp;<span class="link orange" ng-click="assignGroups()"><i class="fa fa-plus-circle"></i></span>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="support-box-wrap box-content2">
			<div class="support-box-wrap-header">
				<h1>Payment Info</h1>
				<div class="support-box-header-actions-wrap">
					<div class="support-box-header-actions">
						<a href="/staff/{{staff.login}}/pexcard" ng-if="staff.pexcard.active"><button class="button button-small button-empty button-green"><i class="fa fa-pencil"></i>&nbsp;&nbsp;Add PEX Funds</button></a>
						<a href="/pexcard/card/driver/{{staff.id_admin}}" ng-if="!staff.pexcard.active"><button class="button button-small button-empty button-green"><i class="fa fa-plus"></i>&nbsp;&nbsp;Add PEX Card</button></a>
						<a href="/staff/{{staff.login}}/payinfo"><button class="button button-small button-empty button-green"><i class="fa fa-pencil"></i>&nbsp;&nbsp;Edit</button></a>
						<a href ng-click="reverify()" ng-if="!staff.verified"><button class="button button-small button-empty button-green"><i class="fa fa-check"></i>&nbsp;&nbsp;Reverify</button></a>
					</div>
				</div>
				<div class="divider"></div>
			</div>

			<div class="no-box-content-color">
				<div class="field-container">
					<div class="field-row">
						<div class="field-key">PEX Card</div>
						<div class="field-value">
							<span class="tag tag-green" ng-if="staff.pexcard.active">Active</span>
							<span class="tag tag-red" ng-if="!staff.pexcard.active">Inctive</span>
						</div>
					</div>
					<div class="field-row" ng-if="staff.pexcard.active">
						<div class="field-key">PEX Serial</div>
						<div class="field-value">{{staff.pexcard.card_serial}}</div>
					</div>
					<div class="field-row" ng-if="staff.pexcard.active">
						<div class="field-key">PEX Last Four</div>
						<div class="field-value">{{staff.pexcard.last_four}}</div>
					</div>
					<div class="field-row">
						<div class="field-key">Stripe Status</div>
						<div class="field-value">
							<span class="tag tag-green" ng-if="staff.verified">Verified</span>
							<span class="tag tag-red" ng-if="!staff.verified">Unverified</span>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="support-box-wrap box-content2">
			<div class="support-box-wrap-header">
				<h1>Tools</h1>
				<div class="divider"></div>
			</div>

			<div class="no-box-content-color">
				<div class="field-container">
					<div class="field-row">
						<div class="field-key"><a href="/settlement/drivers/payments?driver={{staff.id_admin}}">Settlement</a></div>
						<div class="field-value"></div>
					</div>
					<div class="field-row">
						<div class="field-key"><a href="/drivers/summary/{{staff.id_admin}}">Payments</a></div>
						<div class="field-value"></div>
					</div>
				</div>
			</div>
		</div>

		<div class="support-box-wrap box-content2">
			<div class="support-box-wrap-header">
				<h1>Driver Info</h1>
				<div class="support-box-header-actions-wrap">
					<div class="support-box-header-actions">
						<a href="/drivers/onboarding/{{staff.id_admin}}"><button class="button button-small button-empty button-green"><i class="fa fa-pencil"></i>&nbsp;&nbsp;Edit</button></a>
					</div>
				</div>
				<div class="divider"></div>
			</div>

			<div class="no-box-content-color">
				<div class="field-container">
					<div class="field-row">
						<div class="field-key">Communities</div>
						<div class="field-value">
							<span class="staff-community-repeat" ng-repeat="community in staff.communities">
								{{community}}
							</span>
							&nbsp;&nbsp;&nbsp;&nbsp;<span class="link orange" ng-click="assignCommunities()"><i class="fa fa-plus-circle"></i></span>
						</div>
					</div>
					<div class="field-row">
						<div class="field-key">Vehicle</div>
						<div class="field-value">
							<span class="tag tag-orange" ng-if="staff.vehicle == 'car'">Car</span>
							<span class="tag tag-purple" ng-if="staff.vehicle == 'bike'">Bike</span>
							<span class="tag tag-grey" ng-if="staff.vehicle != 'bike' && staff.vehicle != 'car'">None</span>
						</div>
					</div>
					<div class="field-row">
						<div class="field-key">Referral Code</div>
						<div class="field-value">
							{{staff.invite_code}}
						</div>
					</div>
					<div class="field-row">
						<div class="field-key">Activations</div>
						<div class="field-value">
							{{staff.referral_total || 0}}
						</div>
					</div>
					<div class="field-row">
						<div class="field-key">Activations in past week</div>
						<div class="field-value">
							{{staff.referral_total_last_week || 0}}
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="support-box-wrap box-content2">

			<div class="support-box-wrap-header">
				<h1>Additional Info</h1>
				<div class="divider"></div>
			</div>

			<div class="no-box-content-color">

				<div class="field-container">

					<div class="field-row" ng-if="staff.phone_type">
						<div class="field-key">Phone</div>
						<div class="field-value">
							{{staff.phone_type}}
							<span ng-if="staff.phone_subtype"> - {{staff.phone_subtype}}</span>
							<span ng-if="staff.phone_version"> - {{staff.phone_version}}</span>
							<span ng-if="staff.iphone_type"> - {{staff.iphone_type}}</span>
						</div>
					</div>

					<div class="field-row" ng-if="staff.cell_carrier">
						<div class="field-key">Cell Carrier</div>
						<div class="field-value">
							{{staff.cell_carrier}}
						</div>
					</div>

					<div class="field-row" ng-if="staff.is_driver">
						<div class="field-key">Student</div>
						<div class="field-value">
							<span class="tag tag-green" ng-if="staff.student">Yes</span>
							<span class="tag tag-red" ng-if="!staff.student">No</span>
						</div>
					</div>

					<div class="field-row" ng-if="staff.is_driver">
						<div class="field-key">Permashifts</div>
						<div class="field-value">
							<span class="tag tag-green" ng-if="staff.permashifts">Yes</span>
							<span class="tag tag-red" ng-if="!staff.permashifts">No</span>
						</div>
					</div>

					<div class="field-row" ng-if="staff.weekly_hours">
						<div class="field-key">Desired Weekly Hours</div>
						<div class="field-value">
							{{staff.weekly_hours}}
						</div>
					</div>

					<div class="field-row" ng-if="staff.tshirt_size">
						<div class="field-key">T-shirt Size</div>
						<div class="field-value">
							{{staff.tshirt_size}}
						</div>
					</div>

					<div class="field-row" ng-if="staff.address">
						<div class="field-key">Address</div>
						<div class="field-value"><a href ng-click="routeAddress(staff.address)">{{staff.address}}</a></div>
					</div>

					<div class="field-row" ng-if="staff.payment_type">
						<div class="field-key">Pay Structure</div>
						<div class="field-value">
							<span class="tag tag-blue" ng-if="staff.payment_type == 'orders'">Commission</span>
							<span class="tag tag-purple" ng-if="staff.payment_type == 'hours'">Hourly with tips</span>
							<span class="tag tag-orange" ng-if="staff.payment_type == 'hours_without_tips'">Hourly without tips (but a higher hourly rate)</span>
							<span class="tag tag-green" ng-if="staff.payment_type == 'making_whole'">Making whole</span>
						</div>
					</div>

					<div class="field-row" ng-if="staff.hour_rate">
						<div class="field-key">Hour rate</div>
						<div class="field-value">
							{{staff.hour_rate}}
						</div>
					</div>

				</div>
			</div>
		</div>

		<div class="support-box-wrap box-content2">
			<div class="support-box-wrap-header">
				<h1>Shifts</h1>
				<div class="support-box-header-actions-wrap">
					<div class="support-box-header-actions">
						<span class="tag tag-red" ng-if="!staff.shifts.length">No Shifts</span>
					</div>
				</div>
				<div class="divider"></div>
			</div>

			<div class="no-box-content-color box-content-table" ng-if="staff.shifts.length">
				<table class="tb-zebra">
					<tr>
						<th>Time</th>
						<th>Community</th>
						<th class="tb-small"></th>
					</tr>
					<tr ng-repeat="shift in staff.shifts">
						<td>
							<span class="listview-smaller">
								<span class="listview-bold">Start</span>: {{shift.date_start | localtime | timestamp | date:'MM/dd hh:mm a'}}<br>
								<span class="listview-bold">End</span>: {{shift.date_end | localtime | timestamp | date:'MM/dd hh:mm a'}}
							</span>
						</td>
						<td><a href="/community/{{shift.id_community}}">{{shift.community_name}}</a></td>
						<td>
							<span class="tag tag-green" ng-if="shift.current">Now</span>
						</td>
					</tr>
				</table>
			</div>
		</div>


		<div class="support-box-wrap box-content2">
			<div class="support-box-wrap-header">
				<h1>Location</h1>
				<div class="support-box-header-actions-wrap">
					<div class="support-box-header-actions">
						<span class="tag tag-red">BETA</span>
					</div>
				</div>
				<div class="divider"></div>
			</div>
			<? /*
			<div class="no-box-content-color box-content-table">
				<map zoom="12" center="false" class="maps-map" map-type-control="false" style="height: 230px;" options="{streetViewControl: false}"></map>
			</div>
			*/ ?>
		</div>
	</div>

	<ng-include src="'assets/view/staff-group.html'"></ng-include>
	<ng-include src="'assets/view/staff-community.html'"></ng-include>


	<? /*
	<div class="box-content2 box-content-table">
		<table class="tb-zebra">
			<tr>
				<th>ID</th>
				<th>From</th>
				<th>Updated</th>
				<th>Name</th>
				<th>Message</th>
			</tr>
			<tr ng-repeat="ticket in tickets">
				<td><a href="/ticket/{{ticket.id_support}}">{{ticket.id_support}}</td>
				<td><a href ng-click="callText(ticket.user.phone)">{{ticket.user.phone | formatPhone}}</a></td>
				<td>
					<span ng-if="ticket.timestamp" am-time-ago="ticket.timestamp*1000"></span>
					<span ng-if="!ticket.timestamp"><i>Unknown</i></span>
				</td>
				<td>{{ticket.name}}</td>
				<td>{{ticket.message}}</td>
			</tr>
		</table>
	</div>
	*/ ?>


</div>