<div class="top-pad"></div>

<div class="content-padding">
	<div class="page-title-wrap">
		<h1 class="title"><i class="fa fa-file"></i>Notes</h1>
		<div class="page-title-nav">
			<button ng-click="openStaffNoteContainer()" class="button button-green nav-button-green"><i class="fa fa-plus"></i></button>
		</div>
	</div>
	<div class="divider"></div>

	<div class="box-content2 box-content-table">
		<table>
			<tr>
				<td colspan="4" width="100%">
					<i class="fa fa-search"></i>&nbsp;&nbsp;<input type="text" ng-model="query.search" id="search" tabindex="1">
				</td>
				<td>
					<i title="More options" class="fa fa-search-plus link no-underline" ng-class="{'orange':show_more_options}" ng-click="moreOptions()">
				<td>
			</tr>
			<tr ng-if="show_more_options">
				<th>Staff Member</th>
				<td>
					<ui-select ng-model="query.admin" theme="select2" close-on-select="true" style="width: 300px;" title="Select an admin">
						<ui-select-match placeholder="Select a admin">{{$select.selected.name}}</ui-select-match>
						<ui-select-choices repeat="admin.id_admin as admin in staff | propsFilter: {name: $select.search}">
							{{admin.name}}
						</ui-select-choices>
					</ui-select>
					<a ng-show="query.admin" ng-click="query.admin=null" href=""><button class="button button-small button-empty button-green"><i class="fa fa-trash-o"></i></button></a>
				</td>
				<th>Added by</th>
				<td>
					<ui-select ng-model="query.added_by" theme="select2" close-on-select="true" style="width: 300px;" title="Select an admin">
						<ui-select-match placeholder="Select a admin">{{$select.selected.name}}</ui-select-match>
						<ui-select-choices repeat="admin.id_admin as admin in staff | propsFilter: {name: $select.search}">
							{{admin.name}}
						</ui-select-choices>
					</ui-select>
					<a ng-show="query.added_by" ng-click="query.added_by=null" href=""><button class="button button-small button-empty button-green"><i class="fa fa-trash-o"></i></button></a>
				</td>
				<td></td>
			</tr>
		</table>
	</div>
	<div class="bar-loader bar-loader-search" ng-class="{'bar-loader-loading': loading}"></div>
	<ng-include src="'/assets/view/listview-admin-notes.html'"></ng-include>
	<ng-include src="'/assets/view/listview-paging.html'"></ng-include>
</div>
