<div class="top-pad"></div>

<div class="content-padding">
	<div class="page-title-wrap">
		<h1 class="title"><i class="fa fa-users"></i>Staff</h1>
		<div class="page-title-nav">
			<a href="/staff/marketing/new"><button class="button button-green nav-button-green"><i class="fa fa-plus"></i><span>Add Community Manager/Brand Rep</span></button></a>
			<a href="/drivers/onboarding/new"><button class="button button-green nav-button-green"><i class="fa fa-plus"></i><span>Add Driver</span></button></a>
		</div>
	</div>
	<div class="divider"></div>

	<div class="box-content2 box-content-table">
		<table>
			<tr>
				<td colspan="10"><i class="fa fa-search"></i>&nbsp;&nbsp;<input type="text" ng-model="query.search" id="search" tabindex="1"></td>
				<td><i title="More options" class="fa fa-search-plus link no-underline" ng-class="{'orange':show_more_options}" ng-click="moreOptions()"></i></td>
			</tr>
			<tr ng-if="show_more_options">
				<th>Community</th>
				<td nowrap="nowrap">
					<ui-select ng-model="query.community" theme="select2" close-on-select="true" style="width:200px;" title="Select a community">
						<ui-select-match placeholder="Select a community">{{$select.selected.name}}</ui-select-match>
						<ui-select-choices repeat="community.id_community as community in communities | propsFilter: {name: $select.search}">
							{{community.name}}
						</ui-select-choices>
					</ui-select>
					<a ng-show="query.community" ng-click="query.community=null" href=""><button class="button button-small button-empty button-green"><i class="fa fa-trash-o"></i></button></a>
				</td>

				<th>Type</th>
				<td>
					<select ng-model="query.type" name="searchType" tabindex="2">
						<option value="all">All</option>
						<option value="driver">Drivers</option>
						<option value="marketing-rep">Brand Representative</option>
						<option value="community-manager">Community Manager</option>
					</select>
				</td>
				<th>Status</th>
				<td>
					<select ng-model="query.status" name="searchType" tabindex="3">
						<option value="all">All</option>
						<option value="active">Active</option>
						<option value="inactive">Inactive</option>
					</select>
				</td>
				<th>Working</th>
				<td>
					<select ng-model="query.working" name="searchType" tabindex="4">
						<option value="all">All</option>
						<option value="today">Today</option>
						<option value="yes">Yes</option>
						<option value="no">No</option>
					</select>
				</td>
				<th>Using Pex Card</th>
				<td>
					<select ng-model="query.pexcard" name="searchType" tabindex="5">
						<option value="all">All</option>
						<option value="yes">Yes</option>
						<option value="no">No</option>
					</select>
				</td>
				<td></td>
			</tr>
		</table>
	</div>

	<div class="bar-loader bar-loader-search" ng-class="{'bar-loader-loading': loading}"></div>

	<ng-include src="'assets/view/listview-staff.html'"></ng-include>
	<ng-include src="'assets/view/listview-paging.html'"></ng-include>
</div>