<div ng-controller="StaffCommunityCtrl" class="assign-communities-container zoom-anim-dialog mfp-hide dialog">
	<ul class="ul-inputs" ng-if="ready">
		<li class="li-input">
			<div class="label">Communities:</div>
			<div class="input">
				<ui-select multiple ng-model="assigned.communities" theme="select2" close-on-select="true" style="width: 300px;" title="Select a community">
					<ui-select-match placeholder="Select a community...">{{$item.name}}</ui-select-match>
					<ui-select-choices repeat="community.id_community as community in communities | propsFilter: {name: $select.search}">{{community.name}}</ui-select-choices>
				</ui-select>
			</div>
		</li>
		<li class="li-input" ng-show="!isSaving">
			<button class="button save" ng-click="save();">Save</button>
		</li>
	</ul>
</div>