<div ng-controller="StaffGroupCtrl" class="assign-groups-container zoom-anim-dialog mfp-hide dialog">
	<ul class="ul-inputs" ng-if="ready">
		<li class="li-input">
			<div class="label">Groups:</div>
			<div class="input">
				<ui-select multiple ng-model="assigned.groups" theme="select2" close-on-select="true" style="width: 300px;" title="Select a group">
					<ui-select-match placeholder="Select a group...">{{$item.description}} {{$item.name}}</ui-select-match>
					<ui-select-choices repeat="group.id_group as group in groups | propsFilter: { name: $select.search, description: $select.search }">{{group.description}} {{group.name}}</ui-select-choices>
				</ui-select>
			</div>
		</li>
		<li class="li-input" ng-show="!isSaving">
			<button class="button save" ng-click="save();">Save</button>
		</li>
	</ul>
</div>
