<div class="top-pad"></div>

<div class="content-padding" ng-show="ready">

	<h1 class="title left"><i class="fa fa-credit-card"></i><span>Permissions</span></h1>

	<div class="divider"></div>

	<div class="support-boxes">

		<form name="form" novalidate>

			<div class="support-box-wrap box-content2" ng-repeat="permission in list">

				<div class="support-box-wrap-header">
					<h1>{{permission.description}}</h1>
					<div class="divider"></div>
				</div>

				<div class="no-box-content-color">

					<ul class="ul-inputs">

						<li class="li-input" ng-repeat="permission in permission.permissions">
							<div class="label">{{permission.description}}:</div>

							<div class="input">
								<select ng-model="permission.has" required name="payInfoUsingPex" ng-options="type.value as type.label for type in yesNo"></select>
							</div>
							<div class="notes">
								<span class="code tag" ng-class="{'tag-green': permission.has == '1', 'tag-grey': permission.has == '0'}">{{permission.name}}</span>
							</div>
						</li>

					</ul>

				</div>
			</div>

		</form>

	</div>

</div>

<spinner-loading></spinner-loading>
<hack-expand-content></hack-expand-content>