
<div class="top-pad"></div>

<div class="content-padding">

	<h1 class="title box-title"><i class="fa fa-support"></i><span>FAQ</span></h1>


	<div class="support-boxes">


		<div class="support-box-wrap box-content2">
			<a name="deliveryBasics"></a>
			<div class="support-box-wrap-header">
				<h1>Frequently Asked Question</h1>
				<div class="divider"></div>
			</div>

			<div class="no-box-content-color">
				<br>
				<p>
					<span ng-if="is_campus_manager">
						<b>
							How much do I make?
						</b>
						<br>
							You make {{profit_percent}}% of the profits that come in through your community via orders! Note, this is subject to change based on how many community managers are part of the team.
						<br><br>


						<b>Q: How does payment work?</b>
						<br>
							We work on a profit share basis and pay via direct deposit. If you ever have any questions or problems, please reach out to payment@crunchbutton.com
						<br><br>

						<b>How does Crunchbutton decide which restaurants to offer?</b>
						<b>Q: How does payment work?</b>
						<br>
							Crunchbutton provides delivery from the best fast food and local restaurants near campus, with a fleet of delivery drivers. Check out <a href="http://www.crunchbutton.com">crunchbutton.com</a> to see the list at your school.
						<br><br>

						<b>Is there a minimum dollar amount required to place a Crunchbutton order? </b>
						<br>
							Yes, but it varies by school, and is generally at most $5-$10, with a $3 delivery fee.
						<br><br>

						<b>How do users know when their order will arrive? </b>
						<br>
						Upon ordering, users are given a time estimate, which is usually around 25-45 minutes. Customers are provided the driver’s phone number, which they can call or text if they want a status update. They can also text customer service at (646) 783-1444.
						<br><br>

					</span>
					<span ng-if="!is_campus_manager">
						<b>
							What is an activation?
						</b>
						<br>
							An activation is when a new Crunchbutton user uses your code to make their first order. You are compensated for every activation.
						<br><br>
						<b>
							How much do I make?
						</b>
						<br>
							You make ${{referral_admin_credit}} for every new user that uses your code!
						<br><br>
						<b>
							What does the promo code offer?
						</b>
						<br>
						The code provides new users
							<span ng-if="referral_customer_credit">${{referral_customer_credit}}</span>
							<span ng-if="!referral_customer_credit">$3</span> off their first Crunchbutton order!
						<br><br>

						<b>
							How does a user input my code to get a discount on their first order?
						</b>
						<br>
						Just enter your individual code in the “Notes” section on the order page.
						<br><br>

						<b>
							How often should I be marketing Crunchbutton?
						</b>
						<br>
						Our most successful reps spend 5-10 hours every week, but it’s up to you!
						<br><br>

						<b>
							How do users know when their order will arrive?
						</b>
						<br>
						Upon ordering, users are given a time estimate, which is usually around 45 minutes. Customers are provided the driver’s phone number, which they can call or text if they want a status update. They can also contact customer service at (646) 783-1444.
						<br><br>

						<b>
							How does Crunchbutton decide which restaurants to offer?
						</b>
						<br>
							Crunchbutton provides delivery from the best fast food and local restaurants near campus, via our fleet of delivery drivers.  Check out www.crunchbutton.com to see the list at your school.
						<br><br>

						<b>
							 Is there a minimum dollar amount required to place a Crunchbutton order?
						</b>
						<br>
							Yes, but it varies by school, and is generally at most $5-10, with a $3 delivery fee.
						<br><br>
					</span>

				</p>

			</div>
		</div>

	</div>
</div>