

<div class="top-pad"></div>

<div class="content-padding">

	<h1 class="title left"><i class="fa fa-user"></i>{{staff.name}}</h1>
	<div class="ticket-status-top" ng-if="staff.id_admin">
		<div class="ticket-status-open" ng-if="staff.active">Active</div>
		<div class="ticket-status-closed" ng-if="!staff.active">Inactive</div>
	</div>

	<div class="divider"></div>

	<div class="bar-loader bar-loader-search" ng-class="{'bar-loader-loading': loading}"></div>

	<div class="support-boxes">

		<div class="support-box-wrap box-content2">
			<div class="support-box-wrap-header">
				<h1>Info</h1>
				<div class="support-box-header-actions">

				</div>
				<div class="divider"></div>
			</div>

			<div class="no-box-content-color">
				<div class="field-container">
					<div class="field-row">
						<div class="field-key">Name</div>
						<div class="field-value">{{staff.name}}</div>
					</div>
					<div class="field-row">
						<div class="field-key">Phone</div>
						<div class="field-value"><a href ng-click="callText(staff.phone)">{{staff.phone | formatPhone}}</a></div>
					</div>
					<div class="field-row">
						<div class="field-key">Email</div>
						<div class="field-value"><a href="mailto:{{staff.email}}">{{staff.email}}</a></div>
					</div>
					<div class="field-row">
						<div class="field-key">Login</div>
						<div class="field-value">{{staff.login}}</div>
					</div>
					<div class="field-row">
						<div class="field-key">Timezone</div>
						<div class="field-value">{{staff.timezone}}</div>
					</div>
					<div class="field-row">
						<div class="field-key">Communities</div>
						<div class="field-value">
							<span class="staff-community-repeat" ng-repeat="community in staff.communities">
								{{community}}
							</span>
							&nbsp;&nbsp;&nbsp;&nbsp;<a href="https://cockpit.crunchbutton.com/drivers/assign/driver/1" target="_blank"><i class="fa fa-plus-circle"></i></a>
						</div>
					</div>
					<div class="field-row" ng-if="staff.date_terminated_formatted">
						<div class="field-key">Inactive since</div>
						<div class="field-value">{{staff.date_terminated_formatted}}</div>
					</div>
				</div>

			</div>
		</div>
		
		
		<div class="support-box-wrap box-content2">
			<div class="support-box-wrap-header">
				<h1>Pex Card</h1>
				<div class="support-box-header-actions">
					<span class="tag tag-green" ng-if="staff.pexcard.active">Active</span>
					<span class="tag tag-red" ng-if="!staff.pexcard.active">Inctive</span>
				</div>
				<div class="divider"></div>
			</div>
			
			<div class="no-box-content-color" ng-if="staff.pexcard.active">
				<div class="field-container">
					<div class="field-row">
						<div class="field-key">Serial</div>
						<div class="field-value">{{staff.pexcard.card_serial}}</div>
					</div>
					<div class="field-row">
						<div class="field-key">Last Four</div>
						<div class="field-value">{{staff.pexcard.last_four }}</div>
					</div>
					<div class="field-row">
						<div class="field-key"><a href="/staff/{{staff.login}}/pexcard"><button class="button button-small button-small-green"><i class="fa fa-eye"></i>&nbsp;&nbsp;Add Funds</button></a></div>
						<div class="field-value"></div>
					</div>
				</div>
			</div>
			<div class="no-box-content-color" ng-if="!staff.pexcard.active">
				<div class="field-container">
					<div class="field-row">
						<div class="field-key"><a href="/pexcard/card/driver/{{staff.id_admin}}"><button class="button button-small button-small-green">Add Card</button></a></div>
						<div class="field-value"></div>
					</div>
				</div>
			</div>
		</div>
		
		<div class="support-box-wrap box-content2">
			<div class="support-box-wrap-header">
				<h1>Tools</h1>
				<div class="divider"></div>
			</div>
			
			<div class="no-box-content-color">
				<div class="field-container">
					<div class="field-row">
						<div class="field-key"><a href="/settlement/drivers/payments?driver={{staff.id_admin}}">Settlement</a></div>
						<div class="field-value"></div>
					</div>
					<div class="field-row">
						<div class="field-key"><a href="/drivers/summary/{{staff.id_admin}}">Payments</a></div>
						<div class="field-value"><a href="/staff/{{staff.login}}/payinfo">Payment Info</a></div>
					</div>

				</div>
			</div>
		</div>


		
<? /*
		<div class="support-box-wrap">
			<h1>Location</h1>
			<map zoom="12" center="false" class="maps-map" map-type-control="false" style="height: 230px;" options="{streetViewControl: false}">

			</map>
		</div>
		*/ ?>
		
	</div>
	
	<div class="divider"></div>

	<h1 class="title"><i class="fa fa-calendar"></i>Shifts</h1>
	<div class="box-content2 box-content-table">
		<table class="tb-zebra">
			<tr>
				<th>Start</th>
				<th>End</th>
				<th>Community</th>
				<th>Current</th>
			</tr>
			<tr ng-repeat="shift in staff.shifts" ng-class="{'highlight':shift.current}">
				<td>{{shift.date_start | localtime | timestamp | date:'MM/dd hh:mm a'}}</td>
				<td>{{shift.date_end | localtime | timestamp | date:'MM/dd hh:mm a'}}</td>
				<td><a href="/community/{{shift.id_community}}">{{shift.community_name}}</a></td>
				<td>
					<span ng-if="shift.current"><i class="fa fa-check"></i></span>
				</td>
			</tr>
		</table>
	</div>




	<? /*
	<div class="box-content2 box-content-table">
		<table class="tb-zebra">
			<tr>
				<th>ID</th>
				<th>From</th>
				<th>Updated</th>
				<th>Name</th>
				<th>Message</th>
			</tr>
			<tr ng-repeat="ticket in tickets">
				<td><a href="/ticket/{{ticket.id_support}}">{{ticket.id_support}}</td>
				<td><a href ng-click="callText(ticket.user.phone)">{{ticket.user.phone | formatPhone}}</a></td>
				<td>
					<span ng-if="ticket.timestamp" am-time-ago="ticket.timestamp*1000"></span>
					<span ng-if="!ticket.timestamp"><i>Unknown</i></span>
				</td>
				<td>{{ticket.name}}</td>
				<td>{{ticket.message}}</td>
			</tr>
		</table>
	</div>
	*/ ?>


</div>