<div class="top-pad"></div>

<div class="content-padding">

	<div class="box-content2 box-content-table box-search-bar table-sticky-dependant">
		<table>
			<tr>
				<td colspan="4">
					<div title="More options" class="search-bar-options" ng-class="{'orange':show_more_options}" ng-click="moreOptions()">
						<i class="fa" ng-class="{'fa-search':show_more_options, 'fa-search-plus':!show_more_options}"></i>
					</div>&nbsp;&nbsp;<input type="text" ng-model="query.search" id="search" tabindex="1" placeholder="Search orders">
				</td>
				<td colspan="7">
					<div class="page-title-nav">
						<a href="/staff/marketing/new"><button class="button button-green nav-button-green"><i class="fa fa-plus"></i><span>Add Community Manager/Brand Rep</span></button></a>
						<a href="/drivers/onboarding/new"><button class="button button-green nav-button-green"><i class="fa fa-plus"></i><span>Add Driver</span></button></a>
						<a href="/staff/notes"><button class="button button-green nav-button-green"><i class="fa fa-file"></i> Notes</button></a>
					</div>
				</td>
			</tr>
			<tr ng-if="show_more_options">
				<th>Community</th>
				<td nowrap="nowrap">
					<ui-select ng-model="query.community" theme="select2" close-on-select="true" style="width:200px;" title="Select a community">
						<ui-select-match placeholder="Select a community">{{$select.selected.name}}</ui-select-match>
						<ui-select-choices repeat="community.id_community as community in communities | propsFilter: {name: $select.search}">
							{{community.name}}
						</ui-select-choices>
					</ui-select>
					<a ng-show="query.community" ng-click="query.community=null" href=""><button class="button button-small button-empty button-green"><i class="fa fa-trash-o"></i></button></a>
				</td>

				<th>Type</th>
				<td>
					<select name="searchType" tabindex="2" ng-model="query.type" ng-options="opt.value as opt.label for opt in staffType" ></select>
						</div>
				</td>
				<th>Status</th>
				<td>
					<select ng-model="query.status" name="searchType" tabindex="3">
						<option value="all">All</option>
						<option value="active">Active</option>
						<option value="inactive">Inactive</option>
					</select>
				</td>
				<th>Working</th>
				<td>
					<select ng-model="query.working" name="searchType" tabindex="4">
						<option value="all">All</option>
						<option value="today">Today</option>
						<option value="yes">Now</option>
					</select>
				</td>
				<th>Pex</th>
				<td>
					<select ng-model="query.pexcard" name="searchType" tabindex="5">
						<option value="all">All</option>
						<option value="yes">Yes</option>
						<option value="no">No</option>
					</select>
				</td>
				<td></td>
			</tr>
		</table>
	</div>

	<div class="bar-loader bar-loader-search" ng-class="{'bar-loader-loading': loading}"></div>

	<ng-include src="'assets/view/listview-staff.html'"></ng-include>
	<div sticky-bottom="47" class="table-sticky-dependant" ng-show="pages > 1 || more">
		<div class="no-box-content-color">
			<ng-include src="'assets/view/listview-paging.html'"></ng-include>
		</div>
	</div>
</div>
