<?
	$this->title = 'Crunchbutton';
?>

<? $count = 5; ?>

<? if ($count == 4) : ?>
	<style>
		@media only screen
		and (min-width : 1224px) {
			.content {
				width: 676px;
			}
		}
	</style>
<? endif ; ?>

<div class="home-tagline"><h1>one click food ordering</h1></div>

<div class="content-padder">
	<div class="meal-items">
		<? for ($x=1;$x<=$count;$x++) : ?>
		<div class="meal-item">
			<div class="meal-pic" style="background: url(/assets/images/food/wenzel.png);"></div>
			<h2 class="meal-restaurant">Alpha Delta Pizza</h2>
			<h3 class="meal-food">Top Item: Wenzel Sandwich</h3>
		</div>
		<? endfor; ?>
	</div>
</div>