<div class="top-pad"></div>

<div class="content-padding" ng-show="ready">

	<h1 class="title left"><i class="fa fa-bank"></i><span>Arbitrary Payment - Driver</span></h1>

	<div class="divider"></div>

	<form name="form" ng-show="drivers">

		<ul ng-class="{'submitted':submitted}" class="ul-inputs box-content2">
			<li class="li-input" ng-class="{'error':form.paymentDriver.$invalid}">
				<div class="label">Select a driver:</div>
				<div class="input">
					<div isteven-multi-select selection-mode="single" input-model="drivers" output-model="outputDriver" button-label="name" item-label="name" tick-property="ticked" ></div>
				</div>
				<div class="box-error">
					<small ng-show="form.paymentDriver.$error.required">Required.</small>
				</div>
			</li>
			<li class="li-input" ng-class="{'error':form.paymentAmount.$invalid}">
				<div class="label">Amount:</div>
				<div class="input"><input step="any" type="number" name="paymentAmount" ng-model="payment.amount" required ignore-mouse-wheel placeholder=""></div>
				<div class="box-error">
					<small ng-show="form.paymentAmount.$error.required">Required.</small>
				</div>
			</li>
			<li class="li-input" ng-class="{'error':form.paymentType.$invalid}">
				<div class="label">Payment type:</div>
				<div class="input">
					<select name="paymentType" ng-model="payment.pay_type" required ng-options="opt.pay_type as opt.name for opt in payments_type"></select>
				</div>
				<div class="box-error">
					<small ng-show="form.paymentType.$error.required">Required.</small>
				</div>
			</li>
			<li class="li-input" ng-class="{'error':form.paymentNotes.$invalid}">
				<div class="label">Message displayed to driver in payment summary and automated email that gets sent right now:</div>
				<div class="input"><input type="text" name="paymentNotes" ng-model="payment.notes" required maxlength="255" placeholder=""></div>
				<div class="box-error">
					<small ng-show="form.paymentNotes.$error.required">Required.</small>
				</div>
			</li>
		</ul>

		<ul class="ul-inputs">
			<li class="li-input" ng-show="!isPaying">
				<button class="button save" ng-click="pay();">Pay Driver</button>
			</li>
			<li class="li-input" ng-show="isPaying">
				<i class="fa fa-circle-o-notch fa-spin"></i>
			</li>
		</ul>

	</form>

<spinner-loading></spinner-loading>
<hack-expand-content></hack-expand-content>