<div class="top-pad"></div>

<div class="content-padding" ng-show="ready">

	<h1 class="title left"><i class="fa fa-bank"></i><span>Payments - Drivers</span></h1>

	<div class="divider"></div>

	<h2 class="title">
		<span>Payments</span>
	</h2>

	<ul class="ul-inputs box-content2">
		<li class="li-input">
			<div class="label">Driver:</div>
			<select ng-model="id_driver" ng-options="opt.id_driver as opt.name for opt in drivers" class="cart-customize-select"></select>
		</li>
		<li class="li-input">
			<div class="label">Type:</div>
			<select ng-model="pay_type" ng-options="opt.type as opt.label for opt in pay_types" class="cart-customize-select"></select>
		</li>
		<li class="li-input">
			<div class="label">Balanced Status:</div>
			<select ng-model="balanced_status_filter" ng-options="opt.type as opt.label for opt in balanced_statuses" class="cart-customize-select"></select>
		</li>
	</ul>

	<div ng-if="count">

		<div class="box-content2" ng-show="!showForm">
			<p>
				Total of <strong>{{count}}</strong> payments found.
			</p>
		</div>

		<table class="tb-grid tb-zebra">
			<thead>
				<tr>
					<td>#</td>
					<td class="td-medium">Driver</td>
					<td>Type</td>
					<td>Amount</td>
					<td class="td-medium">Balanced Status</td>
					<td>Date</td>
				</tr>
			</thead>
			<tbody>
				<tr ng-repeat="payment in payments">
					<td>
						<span ng-show="payment.id_payment_schedule" class="orange link" ng-click="open(payment.id_payment)">
							{{payment.id_payment}}
						</span>
						<span ng-show="!payment.id_payment_schedule">
							{{payment.id_payment}}
						</span>
					</td>
					<td>{{payment.driver}}</td>
					<td>{{payment.pay_type}}</td>
					<td>$ {{payment.amount | formatPrice}}</td>
					<td ng-class="payment.balanced_status">
						<span ng-if="payment.balanced_failure_reason">
							<i title="{{payment.balanced_failure_reason}}" class="fa fa-warning"></i>&nbsp;
						</span>

						{{payment.balanced_status}}
						<span title="Check balanced status" class="link no-underline" ng-if="payment.balanced_status != 'succeeded'" ng-click="balanced_status( payment.id_payment );"> <i class="fa fa-refresh"></i> </span>
					</td>
					<td>{{payment.date}}</td>
				</tr>
			</tbody>
		</table>

		<table class="tb-pagination" ng-show="pages > 1">
			<tbody>
				<tr>
					<td class="td-prev"><button class="button orange" ng-show="prev" ng-click="prevPage()">prev</button></td>
					<td class="td-info">Page {{page}} of {{pages}}</td>
					<td class="td-next"><button class="button orange" ng-show="next" ng-click="nextPage()">next</button></td>
				</tr>
			</tbody>
		</table>
	</div>
	<div ng-if="!count">
		No payments
	</div>

</div>

<spinner-loading></spinner-loading>
<hack-expand-content></hack-expand-content>