<div class="top-pad"></div>

<div class="content-padding">
	<h1 class="title"><i class="fa fa-bank"></i>Scheduled Driver Payments Summary</h1>

	<div ng-if="result">

		<h3 class="title">
			Summary updated at {{result.updated_at}} <span class="orange link" ng-click="update()">Update now</span>
		</h3>

		<div class="box-content2 box-content-table">
			<table>
				<tr>
					<th>Total of Payments</th>
					<td>{{result.total_payments}}</td>
				</tr>
				<tr>
					<th>Total of Reimbursements</th>
					<td>{{result.total_reimbursements}}</td>
				</tr>
				<tr>
					<th>Scheduled</th>
					<td>{{result.scheduled}}</td>
				</tr>
				<tr>
					<th>Processing</th>
					<td>{{result.processing}}</td>
				</tr>
				<tr ng-class="{'orange' : result.error > 0 }">
					<th>Errors</th>
					<td>{{result.error}}</td>
				</tr>
			</table>
		</div>

		<div ng-show="result.drivers">
			
			<h1 class="title left"><i class="fa fa-bank"></i>Payments</h1>

			<div class="box-filter right">
				<button class="button green" ng-class="{ 'inactive' : filter }" ng-click="filter = false">All</button>
				<button class="button button-big green" ng-class="{ 'inactive' : filter != 'reimbursement' }" ng-click="filter = 'reimbursement'">Reimbursement</button>
				<button class="button button-big green" ng-class="{ 'inactive' : filter != 'payment' }" ng-click="filter = 'payment'">Payments</button>
			</div>
			
			<div class="divider"></div>

			<div>
				<h3 class="title">
					Summary updated at {{result.updated_at}} <span class="orange link" ng-click="update()">Update now</span>
				</h3>
				<h3 ng-click="do_err_payments()" class="title">
					<strong class="orange link">Process errors all again</strong>
				</h3>
			</div>

			<div class="box-content2 box-content-table">
				<table class="tb-zebra">
					<tr>
						<th>ID</th>
						<th>Driver</th>
						<th>Scheduled at</th>
						<th>Type</th>
						<th>Amount</th>
						<th>Status</th>
						<th></th>
					</tr>
					<tr ng-repeat="driver in result.drivers" ng-show="!filter || filter == driver.pay_type">
						<td><a href="/settlement/drivers/scheduled/{{driver.id_payment_schedule}}">{{driver.id_payment_schedule}}</td>
						<td>{{driver.driver}}</td>
						<td>{{driver.date}}</td>
						<td>{{driver.pay_type}}</td>
						<td>${{driver.amount | formatPrice}}</td>
						<td class="deploy-status-{{driver.status}}">
							{{driver.status}}
						</td>
						<td>
							{{driver.log}}
						</td>
					</tr>
				</table>
			</div>
		</div>
	</div>
</div>

<spinner-loading></spinner-loading>
<hack-expand-content></hack-expand-content>