<div class="top-pad"></div>

<div class="content-padding">

	<h1 class="title box-title"><i class="fa fa-bank"></i>Settlement</h1>

	<div class="support-boxes">

		<div class="support-box-wrap box-content2">
			<div class="support-box-wrap-header">
				<h1><i class="fa fa-bank"></i>Settlement</h1>
				<div class="divider"></div>
			</div>

			<div class="box-content-table">
				<table>
					<tr><td><a href="/settlement/list">All Payments</a></td></tr>
				</table>
			</div>
		</div>

		<div class="support-box-wrap box-content2">
			<div class="support-box-wrap-header">
				<h1><i class="fa fa-coffee"></i>Restaurants</h1>
				<div class="divider"></div>
			</div>

			<div class="box-content-table">
				<table>
					<tr><td><a href="/settlement/restaurants">New Payment</a></td></tr>
					<tr><td><a href="/settlement/restaurants/payment/arbitrary">New Arbitrary Payment</a></td></tr>
					<tr><td><a href="/settlement/list?limit=20&page=1&fullcount=false&search=&type=restaurant&status=0&payment_type=0&date=">Payments list</a></td></tr>
					<tr><td><a href="/settlement/restaurants/no-payment-method">Restaurants with no payment method</a></td></tr>
				</table>
			</div>
		</div>


		<div class="support-box-wrap box-content2">
			<div class="support-box-wrap-header">
				<h1><i class="fa fa-credit-card"></i>Pex Card</h1>
				<div class="divider"></div>
			</div>


			<div class="box-content-table">
				<table>
					<tr><td><a href="/pexcard/report">Pex Card Report <i class="fa fa-star"></i></a></td></tr>
					<tr><td><a href="/pexcard/report/old">Pex Card Report (old)</a></td></tr>
				</table>
			</div>
		</div>

		<div class="support-box-wrap box-content2">
			<div class="support-box-wrap-header">
				<h1><i class="fa fa-car"></i>Drivers</h1>
				<div class="divider"></div>
			</div>


			<div class="box-content-table">
				<table>
					<tr><td><a href="/settlement/drivers">New Payment</a></td></tr>
					<tr><td><a href="/settlement/drivers/payment/arbitrary">New Arbitrary Payment</a></td></tr>
					<tr><td><a href="/settlement/list?limit=20&page=1&fullcount=false&search=&type=driver&status=0&payment_type=0&date=">Payments list</a></td></tr>
					<tr><td><a href="/staff?type=driver&status=active&limit=25&page=1">Edit driver's payment info</a></td></tr>
					<tr><td><a target="_blank" href="/api/settlement/drivers/info-payroll/2015">Info for 1099s - 2015 </a></td></tr>
				</table>
			</div>
		</div>

		<div class="support-box-wrap box-content2">
			<div class="support-box-wrap-header">
				<h1><i class="fa fa-list-ul"></i>Settlement Queue</h1>
				<div class="divider"></div>
			</div>


			<div class="box-content-table">
				<table>
					<tr><td><a href="/settlement/queue">Schedule Queue</a></td></tr>
				</table>
			</div>
		</div>

	</div>

</div>
