<div class="top-pad"></div>

<div class="content-padding" ng-show="ready">

	<h1 class="title left"><i class="fa fa-bank"></i><span>Arbitrary Payment - Driver</span></h1>

	<div class="divider"></div>

	<form name="form" ng-show="drivers || staff">

		<ul ng-class="{'submitted':submitted}" class="ul-inputs box-content2">

			<li class="li-input" ng-class="{'error':form.paymentDriver.$invalid}" ng-if="!staff.id_admin">
				<div class="label">Select a driver:</div>
				<div class="input">
					<ui-select ng-model="payment.id_driver" theme="select2" ng-disabled="disabled" style="width: 90%;" title="Select a driver">
						<ui-select-match placeholder="Select a driver">{{$select.selected.name}}</ui-select-match>
						<ui-select-choices repeat="driver.id_admin as driver in drivers | propsFilter: {name: $select.search}">
							{{driver.name}}
						</ui-select-choices>
					</ui-select>
				</div>
				<div class="box-error">
					<small ng-show="form.paymentDriver.$error.required">Required.</small>
				</div>
			</li>

			<li class="li-input" ng-if="staff.id_admin">
				<div class="label">Driver:</div>
				<div class="input">{{staff.name}}</div>
			</li>

			<li class="li-input" ng-class="{'error':form.paymentAmount.$invalid}">
				<div class="label">Amount:</div>
				<div class="input"><input step="any" type="number" name="paymentAmount" ng-model="payment.amount" required ignore-mouse-wheel placeholder=""></div>
				<div class="box-error">
					<small ng-show="form.paymentAmount.$error.required">Required.</small>
				</div>
			</li>
			<li class="li-input" ng-class="{'error':form.paymentType.$invalid}">
				<div class="label">Payment type:</div>
				<div class="input">
					<select name="paymentType" ng-model="payment.pay_type" required ng-options="opt.pay_type as opt.name for opt in payments_type"></select>
				</div>
				<div class="box-error">
					<small ng-show="form.paymentType.$error.required">Required.</small>
				</div>
			</li>
			<li class="li-input" ng-class="{'error':form.paymentNotes.$invalid}">
				<div class="label">Message displayed to driver in payment summary and automated email that gets sent right now:</div>
				<div class="input"><input type="text" name="paymentNotes" ng-model="payment.notes" required maxlength="255" placeholder=""></div>
				<div class="box-error">
					<small ng-show="form.paymentNotes.$error.required">Required.</small>
				</div>
			</li>
		</ul>

		<ul class="ul-inputs">
			<li class="li-input" ng-show="!isPaying">
				<button class="button save" ng-click="pay();">Pay Driver</button>
			</li>
			<li class="li-input" ng-show="isPaying">
				<i class="fa fa-circle-o-notch fa-spin"></i>
			</li>
		</ul>

	</form>

<spinner-loading></spinner-loading>
<hack-expand-content></hack-expand-content>