<div class="top-pad"></div>

<div class="content-padding">

	<div class="box-content2 box-content-table box-search-bar table-sticky-dependant">
		<table>
			<tr>
				<td colspan="5">
					<div title="More options" class="search-bar-options" ng-class="{'orange':show_more_options}" ng-click="showMoreOptions()">
						<i class="fa" ng-class="{'fa-search':show_more_options, 'fa-search-plus':!show_more_options}"></i>
					</div>&nbsp;&nbsp;<input type="text" ng-readonly="query.id_driver" ng-model="query.search" id="search" tabindex="1" placeholder="Search settlement">
				</td>
			</tr>
			<tr ng-if="show_more_options">
				<th>Date</th>
				<td>
					<input type="date" ng-model="query.date" tabindex="2">
				</td>
				<th>Type</th>
				<td>
					<span ng-show="query.id_driver">
						Driver
					</span>
					<span ng-show="!query.id_driver">
						<select ng-model="query.type" ng-readonly="query.id_driver" ng-options="opt.type as opt.label for opt in types" class="cart-customize-select"></select>
					</span>
				</td>
				<th>Payment Type</th>
				<td>
					<select ng-disabled="query.type == 'restaurant'" ng-model="query.payment_type" ng-options="opt.type as opt.label for opt in pay_types" class="cart-customize-select"></select>
				</td>
				<th>Status</th>
				<td>
					<select ng-model="query.status" ng-options="opt.type as opt.label for opt in payment_statuses" class="cart-customize-select"></select>
				</td>
				<td></td>
			</tr>
		</table>
	</div>
	<div class="bar-loader bar-loader-search" ng-class="{'bar-loader-loading': loading}"></div>

	<ng-include src="'assets/view/listview-settlement.html'"></ng-include>
	<div sticky-bottom="47" class="table-sticky-dependant" ng-show="pages > 1 || more">
		<div class="no-box-content-color">
			<ng-include src="'assets/view/listview-paging.html'"></ng-include>
		</div>
	</div>

</div>
