<div class="top-pad"></div>

<div class="content-padding">

	<h1 class="title box-title"><i class="fa fa-bank"></i>Settlement</h1>

	<div class="support-boxes">

		<div class="support-box-wrap box-content2">
			<div class="support-box-wrap-header">
				<h1><i class="fa fa-bank"></i>Settlement</h1>
				<div class="divider"></div>
			</div>

			<div class="box-content-table">
				<table>
					<tr><td><a href="/settlement/list">Payments</a></td></tr>
				</table>
			</div>
		</div>

		<div class="support-box-wrap box-content2">
			<div class="support-box-wrap-header">
				<h1><i class="fa fa-coffee"></i>Restaurants</h1>
				<div class="divider"></div>
			</div>

			<div class="box-content-table">
				<table>
					<tr><td><a href="/settlement/restaurants">New Payment</a></td></tr>
					<tr><td><a href="/settlement/restaurants/payment/arbitrary">Arbitrary Payment</a></td></tr>
					<tr><td><a href="/settlement/restaurants/payments">Payments list</a></td></tr>
					<tr><td><a href="/settlement/restaurants/scheduled">Scheduled Payments</a> (<i>not finished or error</i>)</td></tr>
					<tr><td><a href="/settlement/restaurants/no-payment-method">Restaurants with no payment method</a></td></tr>
				</table>
			</div>
		</div>


		<div class="support-box-wrap box-content2">
			<div class="support-box-wrap-header">
				<h1><i class="fa fa-credit-card"></i>Pex Card</h1>
				<div class="divider"></div>
			</div>


			<div class="box-content-table">
				<table>
					<tr><td><a href="/pexcard/report">Pex Card Report</a></td></tr>
				</table>
			</div>
		</div>

		<div class="support-box-wrap box-content2">
			<div class="support-box-wrap-header">
				<h1><i class="fa fa-car"></i>Drivers</h1>
				<div class="divider"></div>
			</div>


			<div class="box-content-table">
				<table>
					<tr><td><a href="/settlement/drivers">New Payment</a></td></tr>
					<tr><td><a href="/settlement/drivers/payments">Payments list</a></td></tr>
					<tr><td><a href="/settlement/drivers/scheduled">Scheduled Payments</a> (<i>not finished or error</i>)</td></tr>
					<tr><td><a href="/settlement/drivers/payment/arbitrary">Arbitrary Payment</a></td></tr>
					<tr><td><a href="/staff?type=driver&status=active&limit=25&page=1">Edit driver's payment info</a></td></tr>
					<tr><td><a href="/settlement/drivers/archived">Archived Payments</a></td></tr>
					<tr><td><a href="/settlement/drivers/deleted">Deleted Payments</a></td></tr>
				</table>
			</div>
		</div>

	</div>

</div>
