<div class="top-pad"></div>

<div class="content-padding">

	<h1 class="title"><i class="fa fa-calendar"></i>Schedule Shifts<div class="title-loader" ng-if="loading"></h1>

	<div class="support-box-wrap box-content2">

		<div class="support-box-wrap-header">
			<h1>Options</h1>
			<div class="divider"></div>
		</div>

		<div class="no-box-content-color">

			<ul class="ul-inputs">
				<li class="li-input" ng-if="options.start">
					<div class="label">Starting at:</div>
					<div class="input"><input type="date" name="dateStart" ng-model="options.start" ></div>
				</li>

				<li class="li-input" ng-if="communities.length">
					<div class="label">Communities:</div>
					<div class="input">
						<button ng-click="selectNoneCommunity();" class="button button-small button-empty button-border button-orange"><i class="fa fa-minus-circle"></i>&nbsp;&nbsp;Select None</button>
						<button ng-click="selectAllCommunities();" class="button button-small button-empty button-border button-green"><i class="fa fa-plus-circle"></i>&nbsp;&nbsp;Select All</button>
						<br/>
						<br/>
					</div>

					<div class="input">
						<ui-select multiple ng-model="options.communities" theme="select2" close-on-select="true" title="Select a community">
							<ui-select-match placeholder="Select a community...">{{$item.name}}</ui-select-match>
							<ui-select-choices repeat="community.id_community as community in communities | propsFilter: {name: $select.search}">
								{{community.name}}
							</ui-select-choices>
						</ui-select>

					</div>
				</li>

				<li class="li-input" ng-if="options.communities.length">
					<br>
					<div class="input">
						<button name='refresh' ng-click='loadShifts()' class="button button-small button-empty button-border button-green"><i class="fa fa-refresh"></i>&nbsp;&nbsp;Load Shifts</button>
					</div>
				</li>
			</ul>
		</div>
	</div>


	<table class="tb-grid tb-zebra" ng-if="shifts.communities">
		<tbody ng-repeat="community in shifts.communities">
			<tr ng-repeat="community in shifts.communities">
				<td></td>
			</tr>
		</tbody>
	</table>


	<div class="divider"></div>

</div>
