<div class="edit-shift-dialog-container zoom-anim-dialog mfp-hide dialog" ng-controller="ShiftScheduleEditShiftCtrl">

	<div>
		<h1 class="title"><span>Edit shift: {{shift.community.name}}</span></h1>

		<div class="divider"></div>

		<span ng-if="loading"><br></span>

		<div class="bar-loader bar-loader-search" ng-class="{'bar-loader-loading': loading}"></div>

		<ng-form name="formEditShift">

			<div class="ul-inputs">

				<ul ng-class="{'submitted':formEditShiftSubmitted}" class="ul-inputs">

					<li class="li-input">
						<div class="info">
							<span class="label">Date:</span>
							<strong>{{shift.segment.start.day}}</strong>
						</div>
					</li>

					<li class="li-input" ng-class="{'error':formEditShift.shiftHours.$invalid}">
						<div class="label">Hours:</div>
						<div class="input"><input type="text" name="shiftHours" ng-model="shift.period" shift-hours-validation required placeholder="Hours" ></div>
						<div class="box-error">
							<small ng-show="formEditShift.shiftHours.$error.required">Required.</small>
							<small ng-show="formEditShift.shiftHours.$error.shiftHoursValidation">Unable to figure out what this time means.</small>
						</div>
						<div class="notes">
							e.g. “12 PM - 2:30 AM”
						</div>
					</li>

					<li class="li-input" ng-if="shift.recurring" ng-class="{'error': formEditShift.shiftChange.$invalid}" >
						<div class="label">Change:</div>
						<div class="input">
							<select name="shiftChange" ng-model="shift.change" required>
								<option value="only-this-shift">Apply to only this shift</option>
								<option value="all-recurring-shifts">Apply to all recurring shifts</option>
							</select>
						</div>
						<div class="box-error">
							<small ng-show="formEditShift.shiftChange.$error.required">Required.</small>
						</div>
					</li>

					<li class="li-input" ng-show="!isSavingAddShift">
						<button class="button button-empty button-border button-green button-full" ng-click="formEditShiftSave();"><span class="fa fa-save"></span>&nbsp;&nbsp;Save</button>
					</li>
					<li class="li-input" ng-show="isSavingAddShift">
						<i class="fa fa-circle-o-notch fa-spin"></i>
					</li>
				</ul>
			</div>
		</ng-form>
	</div>
</div>