<div class="top-pad"></div>

<div class="content-padding">
	<div class="box-content2 box-content-table box-search-bar table-sticky-dependant">
		<table>
			<tr>
				<td><i class="fa fa-search"></i>&nbsp;&nbsp;<input type="text" ng-model="query.search" id="search" tabindex="1" placeholder="Search checkins within the next 48 hours"></td>
				<td></td>
				<th>Status</th>
				<td>
					<select ng-model="query.status" name="searchType" tabindex="2">
						<option value="all">All</option>
						<option value="confirmed">Confirmed</option>
						<option value="not-confirmed">Not Confirmed</option>
					</select>
				</td>
			</tr>
		</table>
	</div>

	<div class="bar-loader bar-loader-search" ng-class="{'bar-loader-loading': loading}"></div>

	<ng-include src="'assets/view/listview-shift-checkin.html'"></ng-include>
	<div sticky-bottom="47" class="table-sticky-dependant" ng-show="pages > 1 || more || query.page > 1">
		<div class="no-box-content-color">
			<ng-include src="'assets/view/listview-paging.html'"></ng-include>
		</div>
	</div>
</div>
