<div class="dont-remove-me i-am-needed-for-comlile ">
	<div class="box-content2 box-content-table map-info-box">
		<table class="tb-zebra">
			<tr>
				<th>Info</th>
				<th>Date</th>
				<th>Restaurant</th>
				<th>Customer</th>
				<th>Driver</th>
				<th>Order</th>
				<th>Status</th>
			</tr>
			<tr >
				<td><a href="/order/{{order.id_order}}">{{order.id_order}}</td>
				<td>{{order.date | localtime | timestamp | date:'MM/dd @ HH:mm'}}</td>
				<td>
					<a href="/restaurant/{{order._restaurant_permalink}}">{{order._restaurant_name}}</a><br>
					<a href="/community/{{order._community_permalink}}" ng-if="!community">{{order._community_name}}</a>
				</td>
				<td><a href="/customer/{{order.id_user}}">{{order.name}}</a></td>
				<td><a href="/staff/{{order.status.driver.id_admin}}">{{order.status.driver.name}}</a></td>
				<td>${{order.final_price_plus_delivery_markup}}</td>
				<td>
					<b>{{order.status.status}}</b><br>
					<span ng-if="order.status"><span am-time-ago="order.status.date | localtime | timestamp"></span></span>
				</td>
			</tr>
		</table>
	</div>

</div>