<!doctype html>
<html>
<head>
<title><?='CBC ' . $this->title?></title>
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale = 1.0,maximum-scale = 1.0">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">
	<link rel="stylesheet" type="text/css" href="/assets/css/admin_feather.css">
	<link rel="shortcut icon" href="/favicon-admin.ico">
</head>

<body>
	<div class="wrapper">
		<div class="nav" data-role="header" data-position="fixed">
			<div class="content">
				<a href="/"><div class="nav-link">
					CB Cockpit Home
				</div></a>
				<? if(c::getPagePiece(1)): ?>
					<?
						$url = c::app()->pages();
						if(end($url) == '') array_pop($url);
						array_pop($url);
						$up_dir = '/' . implode('/', $url);
						echo "<a href='$up_dir'>";
					?>
						<div class="nav-link">
							Up One Level
						</div>
					</a>
				<? endif ?>
			</div>
		</div>
		<div class="body">
			<div class="content">
				<?=$this->content?>
			</div>
		</div>
		<a href="#"><div class='foot'>
			Top
		</div></a>
	</div>

</body>
</html>
