<!DOCTYPE html>
<html>
	<head>
		<title>Calling...</title>
		<link href="http://static0.twilio.com/packages/quickstart/client.css" type="text/css" rel="stylesheet" />

		<script type="text/javascript" src="http://static.twilio.com/libs/twiliojs/1.2/twilio.min.js"></script>
		<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>


		<script type="text/javascript">
			var phone = '<?=$this->phone?>';

			Twilio.Device.setup('<?=$this->token?>');

			Twilio.Device.ready(function (device) {
				$("#log").text("Client is ready");
				if (phone) {
					call();
				}
			});

			Twilio.Device.error(function (error) {
				$("#log").text("Error: " + error.message);
			});

			Twilio.Device.connect(function (conn) {
				$("#log").text("Successfully established call");
			});

			Twilio.Device.disconnect(function (conn) {
				$("#log").text("Call ended");
			});

			Twilio.Device.incoming(function (conn) {
				$("#log").text("Incoming connection from " + conn.parameters.From);
				conn.accept();
			});

			Twilio.Device.presence(function (pres) {
				if (pres.available) {
					$("<li>", {id: pres.from, text: pres.from}).click(function () {
						$("#number").val(pres.from);
						call();
					}).prependTo("#people");
				} else {
					$("#" + pres.from).remove();
				}
			});

			function call() {
				Twilio.Device.connect({
					'PhoneNumber': $('#number').val()
				});
			}

			function hangup() {
				Twilio.Device.disconnectAll();
			}

		</script>
	</head>
	<body>
		<?=$this->content?>
	</body>
</html>