
<style>
	.image {
		height: 100px;
		width: 100px;
	}
	.hidden {
		display: none;
	}
</style>
<? foreach ($this->images as $image) : ?>
	<img src="<?=$image['image']?>" class="image <?=$image['type']?>">
<? endforeach ; ?>
<div class="count"></div>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script>
$(document).ready(function() {
	$('img').error(function () { 
		$(this).addClass('hidden');
	});
});
</script>