<div class="top-pad"></div>

<div class="content-padding">

	<h1 class="subltitle"><i class="fa fa-database"></i>&nbsp;&nbsp;<span>Servers</span></h1>
	<div class="box-content2 deploy-wrap">
		<table>
			<tr>
				<th>Server</th>
				<th>Last Update</th>
				<th>Last Git Version</th>
			</tr>
			<tr ng-repeat="server in servers">
				<td><a href="/deploy/server/{{server.id_deploy_server}}">{{server.name}}</a></td>
				<td>{{server.version.timestamp | date:'MM/dd @ HH:mm'}}</td>
				<td><a href="{{server.repo}}/commit/{{server.version.version}}" target="_system">{{server.version.version}}</a></td>
			</tr>
		</table>
	</div>


	<h1 class="subltitle "><i class="fa fa-bookmark"></i>&nbsp;&nbsp;<span>Versions</span></h1>
	<div class="box-content2 deploy-wrap">
		<table>
			<tr>
				<th>Version</th>
				<th>Server</th>
				<th>Date</th>
				<th>Git Version / Tag</th>
				<th>Status</th>
				<th>Admin</th>
			</tr>
			<tr ng-repeat="version in versions">
				<td><a href="/deploy/version/{{version.id_deploy_version}}">{{version.id_deploy_version}}</td>
				<td>{{version.server.name}}</td>
				<td>{{version.timestamp | date:'MM/dd @ HH:mm'}}</td>
				<td>
					<span ng-if="version.version">
						<a href="{{version.server.repo}}/commit/{{version.version}}" target="_system">{{version.version}}</a>
					</span>
					<span ng-if="version.version && version.tag">
						&nbsp;/&nbsp;
					</span>				
					<span ng-if="version.tag">
						<a href="{{version.server.repo}}/tree/{{version.tag}}" target="_system">{{version.tag}}</a>
					</span>
				</td>
				<td>{{version.status}}<span ng-if="version.status=='deploying'">&nbsp;&nbsp;&nbsp;<i class="fa fa-cog fa-spin"></i></span></td>
				<td><a href="/staff/info/{{version.id_admin}}">{{version.admin.name}}</a></td>
			</tr>
		</table>
	</div>

</div>
