<div class="top-pad"></div>

<div class="content-padding">

	<h1 class="subltitle"><i class="fa fa-database"></i>&nbsp;&nbsp;<span>{{server.name}}</span></h1>
	<div class="box-content2 deploy-wrap">
		<table>
			<tr>
				<th>Hostname</th>
				<td>{{server.hostname}}</td>
			</tr>
			<tr>
				<th>IP</th>
				<td>{{server.ip}}</td>
			</tr>
			<tr>
				<th>Script</th>
				<td>{{server.script}}</td>
			</tr>
			<tr>
				<th>Params</th>
				<td>{{server.params}}</td>
			</tr>
			<tr>
				<th>Git Repo</th>
				<td><a href="{{server.repo}}" target="_system">{{server.repo}}</a></td>
			</tr>
			<tr>
				<th>Requires Travis Validation</th>
				<td>{{server.travis == '1' ? 'Yes' : 'No'}}</td>
			</tr>
			<tr>
				<th>Requires Git Tag</th>
				<td>{{server.tag == '1' ? 'Yes' : 'No'}}</td>
			</tr>
			<tr>
				<th>Last Update</th>
				<td><span ng-if="server.version.timestamp">{{server.version.timestamp*1000 | date:'MM/dd @ HH:mm'}}</span></td>
			</tr>
			<tr>
				<th>Last Git Version</th>
				<td>{{server.version.version}}</td>
			</tr>
		</table>
	</div>
	
	<h1 class="subltitle "><i class="fa fa-bolt"></i>&nbsp;&nbsp;<span>Deploy a Version</span></h1>
	<div class="box-content2 deploy-wrap">
		<table>
			<tr>
				<th>Date</th>
				<td><input type="datetime" ng-model="deploy.date"></td>
			</tr>
			<tr>
				<th>Git Version</th>
				<td>
					<select ng-model="deploy.version">
						<option value="master">master</option>
						<option ng-repeat="gitversion in gitversions">{{gitversion.commit}} / {{gitversion.author}} / {{gitversion.date | date:'MM/dd @ HH:mm'}}</option>
					</select>
				</td>
			</tr>
			<tr>
				<td colspan="2"><button class="button orange" ng-click="saveDeploy()">Deploy</button></td>
			</tr>
		</table>
	</div>


	<h1 class="subltitle "><i class="fa fa-bookmark"></i>&nbsp;&nbsp;<span>Versions</span></h1>
	<div class="box-content2 deploy-wrap">
		<table>
			<tr>
				<th>Version</th>
				<th>Server</th>
				<th>Date</th>
				<th>Git Version / Tag</th>
				<th>Status</th>
				<th>Admin</th>
			</tr>
			<tr ng-repeat="version in versions">
				<td><a href="/deploy/version/{{version.id_deploy_version}}">{{version.id_deploy_version}}</td>
				<td>{{version.server.name}}</td>
				<td>{{version.timestamp*1000 | date:'MM/dd @ HH:mm'}}</td>
				<td>
					<span ng-if="version.version">
						<a href="{{version.server.repo}}/commit/{{version.version}}" target="_system">{{version.version}}</a>
					</span>
					<span ng-if="version.version && version.tag">
						&nbsp;/&nbsp;
					</span>				
					<span ng-if="version.tag">
						<a href="{{version.server.repo}}/tree/{{version.tag}}" target="_system">{{version.tag}}</a>
					</span>
				</td>
				<td>{{version.status}}<span ng-if="version.status=='deploying'">&nbsp;&nbsp;&nbsp;<i class="fa fa-cog fa-spin"></i></span></td>
				<td><a href="/staff/info/{{version.id_admin}}">{{version.admin.name}}</a></td>
			</tr>
		</table>
	</div>

</div>
