<? if (!$this->support->count()) : ?>
	No results found
<? else : ?>
	<table class="list-support">
		<tr>
			<th>Date</th>
			<th>Name</th>
			<th>Phone</th>
			<th>Session</th>
			<th>Message</th>
			<th>Answered</th>
			<th>Type</th>
		</tr>
		<? foreach ($this->support as $support) : ?>
			<? $date = $support->date(); ?>
			<? $answered = ( $support->answers()->count() > 0 ); ?>
			<tr class="list-support-item <?=$support->status; ?>">
				<td> <?=$date->format('M jS Y')?><br /><br /><?=$date->format('g:i:s A')?> </td>
				<td> <?=$support->name; ?></td>
				<td> <?=$support->phone; ?></td>
				<td> <?php if( $support->id_session_twilio ){ echo '@' . $support->id_session_twilio; } else { echo '-'; } ?></td>
				<td><a href="/admin/support/<?=$support->id_support;?>"><?=nl2br( $support->message ); ?></a></td>
				<td> <span class="<? if( $answered  ){ echo ' yes '; } else { echo 'no'; } ?>"> <? if( $answered  ){ echo ' Yes '; } else { echo 'No'; } ?>
				<td> <?=$support->type; ?> </td>
			</tr>
		<? endforeach ; ?>
	</table>
<? endif ; ?>