<div class="admin-content-wrapper">
	<div class="admin-content admin-content-supports">
		<h1 class="support-item-title">Support</h1>
		<br /><br />
		<table class="admin-support-form">
			<tr>
				<td class="label-primary">Support:</td>
				<td class="content-primary">
					<div class="check-wrap">
						<div class="check-content">
							<table style="width:90%;">
								<tbody>
									<tr>
										<td class="label-sub">Name:</td>
										<td class="content-sub"><div class="input-faker"><?=$this->support->name;?></div></td>
									</tr>
									<tr>
										<td class="label-sub">Phone:</td>
										<td class="content-sub"><div class="input-faker"><?=$this->support->phone;?></div></td>
									</tr>
									<?php if( trim( $this->support->message ) != '' ) { ?>
									<tr>
										<td class="label-sub">Message:</td>
										<td class="content-sub"><div class="input-faker"><?=nl2br($this->support->message);?></div></td>
									</tr>
									<?php } ?>
									<tr>
										<td class="label-sub">Type:</td>
										<td class="content-sub"><div class="input-faker"><?=$this->support->type;?></div></td>
									</tr>
									<?php if( $this->support->id_session_twilio ){ ?>
									<tr>
										<td class="label-sub">Session:</td>
										<td class="content-sub"><div class="input-faker">@<?=$this->support->id_session_twilio;?></div></td>
									</tr>
									<?php } ?>
								</tbody>
							</table>
						</div>
					</div>
				</td>
			</tr>
			<tr>
				<td class="label-primary">More information:</td>
				<td class="content-primary">
					<div class="check-wrap">
						<div class="check-content">
							<table style="width:90%;">
								<tbody>
									<?php if( $this->support->user()->id_user ) { ?>
									<tr>
										<td class="label-sub">User:</td>
										<td class="content-sub"><div class="input-faker"><?=$this->support->user()->name;?></div></td>
									</tr>
									<?php } ?>
									<tr>
										<td class="label-sub">IP:</td>
										<td class="content-sub"><div class="input-faker"><?=$this->support->ip;?></div></td>
									</tr>
									<tr>
										<td class="label-sub">Date:</td>
										<td class="content-sub"><div class="input-faker"><?=$this->support->date()->format('M jS Y')?> - <?=$this->support->date()->format('g:i:s A')?></div></td>
									</tr>
								</tbody>
							</table>
						</div>
					</div>
				</td>
			</tr>
			<?php $answers = $this->support->answers(); ?>
			<?php if( $answers->count() > 0 ) { ?>
			<tr>
				<td class="label-primary">Answer(s):</td>
				<td class="content-primary">
					<div class="check-wrap">
						<div class="check-content">
							<?php foreach( $answers as $answer ) { ?>
							<table style="width:90%;">
								<tbody>
									<tr>
										<td class="label-sub">From:</td>
										<td class="content-sub"><div class="input-faker"><?=$answer->name;?></div></td>
									</tr>
									<tr>
										<td class="label-sub">Phone:</td>
										<td class="content-sub"><div class="input-faker"><?=$answer->phone;?></div></td>
									</tr>
									<tr>
										<td class="label-sub">Answer:</td>
										<td class="content-sub"><div class="input-faker"><?=$answer->message;?></div></td>
									</tr>
									<tr>
										<td class="label-sub">Date:</td>
										<td class="content-sub"><div class="input-faker"><?=$answer->date()->format('M jS Y')?> - <?=$answer->date()->format('g:i:s A')?></div></td>
									</tr>
									<tr>
										<td></td>
										<td style="text-align:right;"> <hr /> </td>
									</tr>
								</tbody>
							</table>
							<?php } ?>
						</div>
					</div>
				</td>
			</tr>
			<?php } ?>
		</table>
	</div>
</div>
<script>
$(function() {
	App.supports.prepareForm(<?=$this->support->id_support?>);
});
</script>