<div class="admin-content-wrapper">
	<div class="admin-content admin-content-supports">
		<h1 class="support-item-title">Support</h1>
		<br /><br />
		<table class="admin-support-form">
			<tr>
				<td class="label-primary">Support:</td>
				<td class="content-primary">
					<div class="check-wrap">
						<div class="check-content">
							<table style="width:90%;">
								<tbody>
									<tr>
										<td class="label-sub">Name:</td>
										<td class="content-sub"><div class="input-faker"><?=$this->support->name;?></div></td>
									</tr>
									<tr>
										<td class="label-sub">Phone:</td>
										<td class="content-sub"><div class="input-faker"><?=$this->support->phone;?></div></td>
									</tr>
									<?php if( trim( $this->support->message ) != '' ) { ?>
									<tr>
										<td class="label-sub">Message:</td>
										<td class="content-sub"><div class="input-faker"><?=nl2br($this->support->message);?></div></td>
									</tr>
									<?php } ?>
									<tr>
										<td class="label-sub">Type:</td>
										<td class="content-sub"><div class="input-faker"><?=$this->support->type;?></div></td>
									</tr>
								</tbody>
							</table>
						</div>
					</div>
				</td>
			</tr>
			<tr>
				<td class="label-primary">More information:</td>
				<td class="content-primary">
					<div class="check-wrap">
						<div class="check-content">
							<table style="width:90%;">
								<tbody>
									<?php if( $this->support->user()->id_user ) { ?>
									<tr>
										<td class="label-sub">User:</td>
										<td class="content-sub"><div class="input-faker"><?=$this->support->user()->name;?></div></td>
									</tr>
									<?php } ?>
									<tr>
										<td class="label-sub">IP:</td>
										<td class="content-sub"><div class="input-faker"><?=$this->support->ip;?></div></td>
									</tr>
									<tr>
										<td class="label-sub">Date:</td>
										<td class="content-sub"><div class="input-faker"><?=$this->support->date()->format('M jS Y')?> - <?=$this->support->date()->format('g:i:s A')?></div></td>
									</tr>
								</tbody>
							</table>
						</div>
					</div>
				</td>
			</tr>
		</table>
	</div>
</div>
<script>
$(function() {
	App.supports.prepareForm(<?=$this->support->id_support?>);
});
</script>