
<b>User</b><br/>
Name: <?php echo $user->name; ?> <br />
Phone: <?php echo $user->phone; ?> <br />
Address: <?php echo $user->address; ?> <br />
Email: <?php if( $user->email ){ echo $user->email; } else { echo '-'; }  ?> <br />
<br/>

<?
$support = Support::getSupportForOrder( $order->id );
if($support) {
	?>
	<b>Support: <a href="http://cockpit.crunchbutton.com/support/<?php echo $support->id; ?>">#<?php echo $support->id; ?></a><br /><br /></b>
	<?php
}
?>

<b>Order</b><br/>
Date: <?php echo $order->date()->format('D, M jS Y, H:i:s (T)'); ?> <br />
Restaurant: <?php echo $order->restaurant()->name; ?> <br />
Estimated delivery: <?php echo $order->restaurant()->delivery_estimated_time; ?> min. <br />
Payment: <?php echo $order->pay_type; ?> <br />
Delivery: <?php echo $order->delivery_type; ?> <br />
Tip: $<?php if( $order->tip() ){ echo $order->tip(); } else { echo 0; } ; ?><?php if( $order->tip_type != Crunchbutton_Order::TIP_NUMBER ) { echo $order->tip . '%'; } ?> <br />
Gift card: $<?=number_format($order->chargedByCredit(),2)?> <br />
Total: $<?php echo number_format( $order->final_price, 2 ); ?> <br />
Notes: <?php if( $order->notes ){ echo $order->notes; } else { echo ''; }  ?> <br />
<br/>
<b>Dishes</b><br/>
<ul>
	<?php foreach ($order->dishes() as $dish) : ?>
	<li>
		<?
			$food = $dish->dish()->name;
			$cartPrice = $dish->dish()->price;
			$options = $dish->options();?>
			<?=$food?>

	</li>
	<? endforeach ; ?>
</ul>