<div class="top-pad"></div>

<div class="about-bubble-wrap">
	<div class="bubble-tail bubble-tail-green">
		<div class="text">
			<b>&nbsp;&nbsp;Hey there!</b><br />
			Nice to meet you!
		</div>
	</div>
	<div class="about-pear"></div>
	<div class="divider"></div>
</div>

<div class="content-padding">
	<br />
	<p>will finish once my computer is capable of using photoshop again...</p>
	<br /><br />
	<p>
		Like food? Like fun? Like beer? Then we want you! Join our young ambitious team in sunny LA!
	</p>
	<button class="button green" ng-click="navigation.link('/jobs')">Jobs</button>
</div>
