<div class="top-pad"></div>

<div class="about-bubble-wrap">
	<div class="bubble-tail-green">
		<div class="text">
			<b>&nbsp;&nbsp;Hey there!</b><br />
			Nice to meet you!
		</div>
	</div>
	<div class="about-pear"></div>
	<div class="divider"></div>
</div>

<div class="content-padding">
	<br />
	<h4>So, what exactly do you do?</h4>
	<p>We highlight the top food from the top restaurants in a community. Place an order, and we save it for next time, along with your delivery and payment info. Reorder your favorites with a single tap :)</p>
	<br /><br />
	<h4>Hey! I need help with my order!</h4>
	<p>Please visit your <a href="/orders">Previous Orders</a> and contact the restaurant you ordered from.</p>
	<br /><br />
	<h4>Need to contact Crunchbutton?</h4>
	<p>Call or text us at <a href="tel:+16467831444">(646) 783-1444</a> or email us at <a href="mailto:happycustomers@crunchbutton.com">happycustomers@crunchbutton.com</a>.</p>
	<br /><br />
	<button class="button green">Live chat with us</button>
</div>
