<div class="top-pad"></div>

<div class="about-bubble-wrap">
	<div class="bubble-tail bubble-tail-green">
		<div class="text" ng-switch="pearMessage">
			<span ng-switch-when="1">I don't actually work here.</span>
			<span ng-switch-when="2">These guys do though.</span>
			<span ng-switch-when="3">You should buy them a beer.</span>
			<span ng-switch-when="4">I'm sure they deserve it.</span>
			<span class="single-line" ng-switch-when="5">Maybe two.</span>
			<span class="single-line" ng-switch-when="6">Or three.</span>
			<span ng-switch-when="7">In fact just buy them a keg.</span>
			<span class="single-line" ng-switch-when="8">Me?</span>
			<span class="small" ng-switch-when="9">I'll take a magnum of Veuve Clicquot, thanks.</span>
			<span class="single-line" ng-switch-when="10">Cheers!</span>
			<span class="single-line" ng-switch-when="11"><i class="fa fa-glass"></i> <i class="fa fa-glass"></i> <i class="fa fa-glass"></i></span>
			<span ng-switch-default><b>Hey there!</b><br>Nice to meet you!</span>
		</div>
	</div>
	<div class="about-pear" ng-instant="pearMessage = (pearMessage > 11 && 1) || pearMessage + 1"></div>
	<div class="divider"></div>
</div>

<div class="content-padding">
	<br />
	<div class="staff">
		<div class="staff-judd staff-image"></div>
		<h1>Judd Rosenblatt</h1>
		<h2>Chief Eater</h2>
		<p class="staff-favorite">
			Fav<span class="staff-orite">orite</span> food: THE Wenzel
			<br>Fav<span class="staff-orite">orite</span> beer: Oatmeal Stout
		</p>
		<p class="staff-content">
			Entrepreneur, Yale grad, and other words go here. I dont have anything to say because im too busy trying to make things look pretty right now. Maybe you should think of some shit. Or maybe close ur mouth.
		</p>
	</div>

	<div class="staff">
		<div class="staff-devin staff-image"></div>
		<h1>Devin Smith</h1>
		<h2>Head Chef</h2>
		<p class="staff-favorite">
			Fav<span class="staff-orite">orite</span> food: Toro Sushi
			<br>Fav<span class="staff-orite">orite</span> beer: Matilda
		</p>
		<p class="staff-content">
			Building stuff. Thats what he does. Since Devin was a kid he has been building software and websites. Devin brings his passion for design and development to Crunchbutton paired with a strong belgian ale. 
		</p>
	</div>
	
	<div class="staff">
		<div class="staff-david staff-image"></div>
		<h1>David Klumpp</h1>
		<h2>Chief Taster</h2>
		<p class="staff-favorite">
			Fav<span class="staff-orite">orite</span> food: Chocolate Crostata
			<br>Fav<span class="staff-orite">orite</span> beer: Root Beer
		</p>
		<p class="staff-content">
			We're not really sure what he does. But without him we're pretty sure that we would be thrown into a state of chaos.
		</p>
	</div>
	
	<div class="staff">
		<div class="staff-nick staff-image"></div>
		<h1>Nick Hunter</h1>
		<h2>Garbage Disposal</h2>
		<p class="staff-favorite">
			Fav<span class="staff-orite">orite</span> food: Mexican
			<br>Fav<span class="staff-orite">orite</span> beer: Hefeweizen
		</p>
		<p class="staff-content">
			He like miso soup too much.
		</p>
	</div>
	
	<div class="staff">
		<div class="staff-daniel staff-image"></div>
		<h1>Daniel Camargo</h1>
		<h2>Ambassador</h2>
		<p class="staff-favorite">
			Fav<span class="staff-orite">orite</span> food: Pepperoni Pizza
			<br>Fav<span class="staff-orite">orite</span> beer: Stella Artois
		</p>
		<p class="staff-content">
			Hes in Brazil.
		</p>
	</div>

	<div class="about-join-bubble-wrap">
		<div class="bubble-curved bubble-curved-green">
			<div class="text">
				Join the team!
			</div>
		</div>
	</div>
	<div class="about-green-orange"></div>
	<div class="divider"></div>

	<p>
		<br><br>
		Like food? Like fun? Like beer? Then we want you! Join our young ambitious team in sunny LA!
	</p>
	<br>
	<button class="button lightorange" ng-click="navigation.link('/jobs')">Jobs</button>
</div>
