<div class="account-container zoom-anim-dialog mfp-hide dialog mfp-hide">

	<div class="dialog-padding">
	
		<? /* Header links */ ?>
		<div ng-controller="AccountModalHeaderCtrl" modal-reset="resetModal()" class="header">
			
			<div ng-show="modal.header">
				<span class="account-title-link signin {{ modal.signin && 'active' || 'link' }}" ng-click="modal.toggleSignForm( 'signin' )">Log In</span>
				<span class="account-title-link signup {{ modal.signup && 'active' || 'link' }}" ng-click="modal.toggleSignForm( 'signup' )">Sign up</span>
			</div>
			
			<div ng-show="!modal.header">
				<span class="account-title-link signin link" ng-click="help.show(false)">&laquo; back</span>
			</div>
			
			<div class="divider spacer-one-one"></div>
		
			<? /* Error messages */ ?>
			<div class="dialog-message dialog-message-error" ng-repeat="error in account.errors">{{error}}</div>
			<div class="dialog-message dialog-message-error" ng-repeat="error in help.errors">{{error}}</div>	

			<? /* success messages */ ?>	
			<div class="dialog-message dialog-message-success" ng-show="help.success.visible">
				Please check your email or phone. You will receive a password reset link that will expire in 24 hours.
			</div>

		</div>

		<? /* Log in form fields */ ?>
		<div ng-controller="AccountSignInCtrl" ng-show="modal.signin">

			<div ng-show="!help.visible">
			
				<form name="formSignin" ng-submit="account.signin()">
					<div class="support-form-group form-group">
						<input type="email" maxlength="250" ng-model="account.form.email" name="email" tabindex="10" class="form-input support-form-input" placeholder="email address" ng-enter="account.signin()">
					</div>
					<div class="support-form-group form-group">
						<input type="password" maxlength="250" ng-model="account.form.password" name="password" tabindex="11" class="form-input support-form-input" placeholder="password" ng-enter="account.signin()">
					</div>
				</form>

				<div class="divider spacer-half"></div>
				<a class="account-login-help" ng-click="help.show(true)">Password help?</a>
				<button class="button lightorange account-go" ng-click="account.signin();">Go!</button>
				<div class="divider"></div>
				<div class="spacer-half"></div>
				<button class="button facebook" ng-click="facebook.auth()">
					<i class="fa fa-facebook-square"></i>&nbsp;
					<span ng-hide="facebook.facebook.wait">Log in with Facebook</span>
					<span ng-show="facebook.facebook.wait">Just a sec...</span>
				</button>
			</div>

			<div ng-show="help.visible">
				<form name="formLoginHelp" novalidate>
					<p>Enter your email or phone number and we will send you a link to reset your password.</p>
					<br />
					<input type="text" maxlength="250" name="email" required  class="form-input support-form-input" ng-enter="help.sendForm()" validate-login placeholder="email or phone" tabindex="10" ng-model="account.form.email">
				</form>

				<button class="button lightorange account-go" ng-click="help.sendForm()">Reset</button>
				<div class="divider"></div>
				<div class="spacer-half"></div>
			</div>
		</div>
	
		<? /* Sign up form fields */ ?>
		<div ng-controller="AccountSignUpCtrl" ng-show="modal.signup">
			<div ng-show="!account.user.has_auth">
				<form name="formSignup" novalidate>
					<div class="support-form-group form-group">
						<input type="email" maxlength="250" ng-model="account.form.email" name="email" tabindex="10" class="form-input support-form-input" placeholder="email address" ng-enter="account.signup()">
					</div>
					<div class="support-form-group form-group">
						<input type="password" maxlength="250" ng-model="account.form.password" name="password" tabindex="11" class="form-input support-form-input" placeholder="password" ng-enter="account.signup()">
					</div>
				</form>

				<button class="button lightorange account-go" ng-click="account.signup();">Go!</button>
				<div class="divider"></div>
				<div class="spacer-one-half"</div>
				<button class="button facebook" ng-click="facebook.auth()">
					<i class="fa fa-facebook-square"></i>&nbsp;
					<span ng-hide="facebook.facebook.wait">Sign up with Facebook</span>
					<span ng-show="facebook.facebook.wait">Just a sec...</span>
				</button>
			</div>

			<div ng-show="account.user.has_auth">
				<h1>Congratulations!</h1>
				<p>You can now log in using <b>{{account.email}}</b>!</p>
			</div>
		</div>
	
	</div>

</div>