<div class="top-pad"></div>


<div class="content-padding">
	<button class="button lightorange" ng-click="start()" ng-show="!running">Start</button>
	<button class="button lightorange" ng-click="stop()" ng-show="running">Stop</button>
	<br><br>
	
	<div class="cafe-message">
		<div class="dialog-message dialog-message-error" ng-show="message.error">
			<span ng-bind-html-unsafe="message.error"></span>
		</div>
		<div class="dialog-message dialog-message-success" ng-show="message.good">
			<span ng-bind-html-unsafe="message.good"></span>
		</div>
	</div>

	<div class="cafe-request">
		<h4>{{requested.name}}</h4>
	</div>
	{{score}}
	<div class="cafe-level">
		<b>{{stats.round.name}}</b><br>
		Time: <b>{{stats.timer}}</b> / <b>{{stats.round.time/1000}}:00</b> seconds<br>
		Errors: <b>{{stats.errors}}</b><br>
		Success: <b>{{stats.success}}</b><br>
		Required: <b>{{stats.round.required}}</b><br>
	</div>
	<br><br><br>
	<button class="cafe-button {{button.id}}" ng-repeat="button in items" ng-instant="buttonPress(button.id)">{{button.name && stats.round.descriptions ? button.name : ''}}</button>
	<div class="divider"></div>
</div>

<div class="cafe-button cafe-preload {{button.id}}" ng-repeat="button in allitems"></div>
