

<div class="cafe-start cafe-animate" ng-show="home">
	<div class="double-content-padding">
		<button class="pushable button pink pushable big ani-all" ng-click="start()">Start</button>
	</div>
</div>

<div class="cafe-top fixed">
	<div class="top-pad"></div>
	<div class="double-content-padding">
	
		<!-- home -->
		<div ng-show="home" class="cafe-home">
			<br>
			<div class="cafe-logo-clean"></div>
			<br><br><br>
			<p>These guys are hungry. It’s your job to feed them! Feed enough of them within the allowed time and win!</p>
			<br><br><br><br>
			<div class="cafe-start-toons"></div>
		</div>
		
		<div ng-show="running" class="cafe-game">
			
			<div class="cafe-message">
				<div class="dialog-message dialog-message-error" ng-show="message.error">
					<span ng-bind-html-unsafe="message.error"></span>
				</div>
				<div class="dialog-message dialog-message-success" ng-show="message.good">
					<span ng-bind-html-unsafe="message.good"></span>
				</div>
			</div>
		
			<div class="cafe-request">
				<h4>{{requested.name}}</h4>
			</div>
			
			<div class="cafe-level">
				<b>{{stats.round.name}}</b> / <b>{{$scope.difficulties[difficulty].name}}</b><br>
				Time: <b>{{stats.timer}}</b> / <b>{{stats.round.time/1000}}:00</b> seconds<br>
				Orders: <b>{{stats.success}}</b> / <b>{{stats.round.required}}</b><br>
				Score: <b>{{score}}</b>
			</div>
			<br><br><br>
			<button class="cafe-button {{button.id}}" ng-repeat="button in items" ng-instant="buttonPress(button.id)">{{button.name && stats.round.descriptions ? button.name : ''}}</button>

		</div>
	
		<? /* <button class="button lightorange" ng-click="stop()" ng-show="running">Stop</button> */ ?>
	
		<div class="divider"></div>
	</div>
	
	<div class="cafe-button cafe-preload {{button.id}}" ng-repeat="button in allitems"></div>
</div>