<div class="bg home-top splash-top">
	<div class="splash-spacer-two"></div>

	<div class="download-top">
		<h1>Hey,</h1>
		<h2>theres an app for that.</h2>

		<div class="button-pushable">
			<a href="https://itunes.apple.com/app/id721780390" target="_blank">
				<button class="button orange download" ng-click="letsEat()" ng-spinner data-style="zoom-out" data-spinner-color="#FFFFFF">
					Download
				</button>
			</a>
		</div>
		<div class="divider"></div>
		

		<p>
			<a href="" class="splash-continue" ng-instant="navigation.link('/location')">Continue to mobile site</a>
		</p>

	</div>

	<div class="divider"></div>
	
	<div class="download-bottom">
		<div class="download-phone"></div>
	</div>

</div>
