<div class="bg home-top splash-top fixed">
	<div class="splash-spacer-two"></div>

	<div class="download-top">
		<h1>Hey,</h1>
		<h2>theres an app for that.</h2>

		<div class="button-pushable">
			<a href="https://itunes.apple.com/app/id721780390" target="_blank">
				<button class="button orange download ani-all" ng-click="letsEat()" ng-spinner data-style="zoom-out" data-spinner-color="#FFFFFF">
					Download
				</button>
			</a>
		</div>
		<div class="divider"></div>
		

		<p>
			<a href="" class="splash-continue" ng-instant="cancelDownload()">Continue to mobile site</a>
		</p>

	</div>

	<div class="divider"></div>
	
	<div class="download-bottom fixed-699">
		<a href="https://itunes.apple.com/app/id721780390" target="_blank"><div class="download-phone image-animated"></div></a>
	</div>

</div>
