<div class="bg home-top splash-top fixed">
	<div class="splash-spacer-two"></div>

	<div class="download-mobile">
		<div class="download-top">
			<h1>Hey,</h1>
			<h2>there's an app for that.</h2>

			<div class="button-pushable">
				<a href="{{downloadLink}}" target="_blank">
					<button class="button orange download ani-all">
						Download
					</button>
				</a>
			</div>
			<div class="divider"></div>
			<p class="center-text"><a href="" class="splash-continue" ng-instant="cancelDownload()">Continue to mobile site</a></p>
		</div>

		<div class="divider"></div>

		<div class="download-bottom fixed-699">
			<a href="{{downloadLink}}" target="_blank"><div class="download-phone image-animated"></div></a>
		</div>
	</div>

	<div class="download-desktop">
		<div class="content">
			<a href="{{downloadLink}}" target="_blank"><div class="download-phone image-animated"></div></a>

			<div class="download-top">
				<!-- dont hate. -->
				<table cellpadding="0" cellspacing="0" class="download-top-grid">
					<tr><td class="download-top-grid-head">
						<h1>Hey,</h1>
						<h2>there's an app for that.</h2>
					</td></tr>
					<tr><td class="download-top-grid-act">

						<div ng-show="text.sent">

							<div ng-show="!account.user.facebook">
								<p>To one click log into the app, link your account with facebook here.
								</p>
								<br><br>

								<div class="button-pushable">

									<button class="button facebook ani-all" ng-click="facebook.auth()"><i class="fa fa-facebook-square"></i>
										<span ng-show="!facebook.facebook.wait" >Connect with Facebook</span>
										<span ng-show="facebook.facebook.wait">Just a sec
											<div id="circleG">
												<div id="circleG_1" class="circleG"></div>
												<div id="circleG_2" class="circleG"></div>
												<div id="circleG_3" class="circleG"></div>
											</div>
										</span>
									</button>

								</div>
							</div>

							<div ng-show="account.user.facebook">

								<p>
									Your account is linked with facebook!
								</p>
								<br><br>

							</div>

						</div>

						<div ng-show="!text.sent">
							<br><br>
							<div ng-show="!account.user.phone">
								<input type="tel" class="location-recommend" placeholder="e.g. 646-783-1444" ng-format-phone autocapitalize="off" autocorrect="off" ng-enter="text.send()" ng-model="text.number">
							</div>
							<div class="button-pushable">
								<button class="button download ani-all" ng-click="text.send()">Text me the link</button>
							</div>
						</div>
					</td></tr>
					<tr><td class="download-top-grid-foot">

						<a href="https://itunes.apple.com/app/id721780390" target="_blank"><div class="app-store"></div></a>
						<a href="https://play.google.com/store/apps/details?id=com.crunchbutton" target="_blank"><div class="play-store"></div></a>

						<br>

						<a href="" class="splash-continue" ng-click="navigation.link('/food-delivery')">Return to desktop site</a>
					</td></tr>
				</table>
			</div>

		</div>

	</div>

</div>
