<div class="top-pad"></div>

<div class="content-padding">
	<div class="user-account-credit col-box">

		<div class="two-col">

			<div ng-show="account.user.invite_code">
				<p>
					Get your friends to enter <b>your referral code</b> in the Notes section of their first order, and they will get $3 off and you a delivery free ;)
				</p><br/>

			</div>
			<br/>
		</div>
			<div class="two-col">

				<div class="hide-desktop">
					<a href="{{referral.sms}}" target="_blank">
						<button class="button green button-invite">
							<i class="fa fa-comment"></i> <span>Invite Friends</span>
						</button>
					</a>
				</div>

				<div class="hide-mobile">
					<div class="col-box">
						<button class="button facebook button-refer" ng-click="referral.facebook()">
							<i class="fa fa-facebook-square"></i> <span>Share</span>
						</button>

						<br><br>

						<button class="button twitter button-refer" ng-click="referral.twitter()">
							<i class="fa fa-twitter-square"></i> <span>Tweet</span>
						</button>
					</div>

				</div>

			<br><br>
			<p>Your code: <span class="referal-text-spacer"></span><b>{{account.user.invite_code}}</b></p>
			<div class="hide-mobile">
				<br>
				<p>Invite URL: <span class="referal-text-spacer"></span><input class="referal-text-box" type="text" ng-simulate-read-only="{{referral.cleaned_url()}}" value="http://{{referral.cleaned_url()}}"></p>
			</div>
		</div>
	</div>

</div>