
<div class="content-padding">
	<div class="jobs-bubble-wrap">
		<div class="bubble-curved bubble-curved-green bubble-animated animated-resize">
			<div class="text" ng-switch="orangeMessage">
				<span ng-switch-when="1">When you invite friends...</span>
				<span class="single-line" ng-switch-when="2">family...</span>
				<span class="single-line" ng-switch-when="3">co-workers...</span>
				<span class="single-line" ng-switch-when="4">or arch enemies.</span>
				<span ng-switch-when="5">Don't have any of those?</span>
				<span class="small" ng-switch-when="6">Give some strangers your code</span>
				<span ng-switch-when="7">And make new friends!</span>
				<span class="single-line" ng-switch-when="8"><i class="fa fa-coffee"></i> <i class="fa fa-cutlery"></i> <i class="fa fa-spoon"></i></span>
				<span class="single-line" ng-switch-default><b>Free food!</b></span>
			</div>
		</div>
	</div>

	<div class="free-food-friends" ng-instant="orangeMessage = (orangeMessage > 7 ? 0 : (orangeMessage + 1))" instant-pass-thru></div>
	<div class="divider"></div>
</div>
<br>
<div class="content-padding">

	<div class="user-account-credit col-box">

		<div class="two-col">

			<div ng-show="referral.invite_code">
				<p>
					Get your friends to enter your referral code in the Notes section of their first order, and you'll both get a FREE Delivery ;)
				</p><br/>

			</div>
			<div ng-show="!referral.invite_code">
				<p>
					Get your friends to enter your referral code in the Notes section of their first order, and you'll both get a FREE Delivery ;)
				</p><br/>
				<p>
					Create an account and receive your referral code.
				</p><br/>

			</div>
			<br/>
		</div>
			<div class="two-col" ng-show="referral.invite_code">

				<div class="hide-desktop">
					<a href="{{referral.sms}}" target="_blank">
						<button class="button lightorange button-invite">
							<i class="fa fa-comment"></i> <span>Invite Friends</span>
						</button>
					</a>
				</div>

				<div class="hide-mobile">
					<div class="col-box">
						<button class="button facebook button-refer" ng-click="referral.facebook('account')">
							<i class="fa fa-facebook-square"></i> <span>Share</span>
						</button>

						<br><br>

						<button class="button twitter button-refer" ng-click="referral.twitter('account')">
							<i class="fa fa-twitter-square"></i> <span>Tweet</span>
						</button>
					</div>

				</div>

			<br><br>

			<p>Your code: <span class="referal-text-spacer"></span><b class="allow-select">{{referral.invite_code}}</b></p>
			<div class="hide-mobile">
				<br>
				<p>Invite URL: <span class="referal-text-spacer"></span><input class="referal-text-box" type="text" ng-simulate-read-only="{{referral.cleaned_url()}}" value="http://{{referral.cleaned_url()}}"></p>
			</div>
		</div>

		<div class="two-col" ng-show="!referral.invite_code">
			<div class="button-pushable">
				<button class="button lightorange" ng-click="modal.signupOpen();">Create an account</button>
			</div>
		</div>

	</div>

</div>