<div class="giftcard-container zoom-anim-dialog mfp-hide dialog mfp-hide" ng-controller="GiftCardCtrl">



	<div ng-show="modal.intro" class="dialog-padding account-modal">
		<p>Doin' stuff. Just a sec...</p>
	</div>

	<!-- Error -->
	<div ng-show="modal.error && !modal.success">
		<div class="dialog-padding account-modal">
			<div class="dialog-message dialog-message-error" ng-show="modal.error == 'used'">
				Sorry, this gift card was already used.
			</div>
			<div class="dialog-message dialog-message-error" ng-show="modal.error == 'invalid'">
				Sorry, this is an invalid gift card.
			</div>
			<div class="dialog-message dialog-message-error" ng-show="modal.error == 'not-eligible'">
				Sorry, invite codes are for first time users only.
			</div>
			<div class="dialog-message dialog-message-error" ng-show="modal.error != 'used' && modal.error != 'invalid' && modal.error != 'not-eligible'">
				Please try it again.
			</div>
		</div>
	</div>

	<!-- Success -->
	<div ng-show="modal.success && !modal.error">
		<div class="dialog-padding account-modal">
			<p>
				<b>Congrats!</b>
			</p>
			<div class="divider spacer-one-onehalf"></div>
			<p>

				<span ng-show="modal.restaurant">
					You just got a <b>${{giftcard.value}}</b> gift card to <b class="pointer" ng-click="giftcard.openRestaurant();">{{modal.restaurant.name}}</b>.
				</span>
				<span ng-show="!modal.restaurant">
					<div ng-if="giftcard.message">
						{{giftcard.message}}
					</div>
					<div ng-if="!giftcard.message">
						You just got a <b>${{giftcard.value}}</b> gift card.
					</div>
				</span>

				&nbsp;Go ahead and order some food!
			</p>
		</div>

		<div class="dialog-divider"></div>
		<div class="dialog-padding dialog-bottom-buttons">
			<div class="button-pushable">
				<button ng-click="modal.close()" class="button green">Great</button>
			</div>
		</div>
	</div>


</div>
