<div class="top-pad"></div>

<div class="faq-bubble-wrap">
	<div class="bubble-tailless bubble-tailless-green">
		<div class="text">
			<b>&nbsp;&nbsp;Don’t Worry!</b><br />
			We’re here to help!
		</div>
	</div>
	<div class="faq-tomato"></div>
	<div class="divider"></div>
</div>

<div class="content-padding" ng-controller="SupportCtrl">
	<br />
	<h4>So, what is Crunchbutton?</h4>
	<p>Crunchbutton lets you order the best food in your area delivered straight to your door. Place an order, and we save it for next time, along with your delivery and payment info. Come back and reorder your favorites with just one click.</p>
	<br /><br />
	<h4>Need to contact Crunchbutton?</h4>
	<p>Problem with your order? Need help with your homework? Text or call us at <a href="sms:+16467831444" target="_system">(646) 783-1444</a> or email us at <a href="mailto:{{customers}}">{{customers}}</a>.</p>
	<br /><br />
	<button class="button green" ng-click="support.dialog()">Send us a message</button>
</div>

<div class="content-padding">
	<br /><br /><br /><br />
	<div class="faq-sun"></div>
	<br /><br /><br /><br />
</div>

<div class="content-padding">
	<h4>Who are you?!</h4>
	<p>We're people! People who love food so much that we want to share our passion without asking you to even leave your homes.</p>
	<br>
	<button class="button lightorange" ng-click="navigation.link('/about','push')">Meet the team</button>
	<br><br><br>
	
	<h4>How do I order food?</h4>
	<p>Easy! Just go to <a href="http://crunchbutton.com" target="_blank">crunchbutton.com</a> and click the restaurant you want to order from. Add whatever food you want, and enter your address, phone, and payment info. Click "Get Food" and try to stay hungry! The driver will call you when they're outside.</p>
	<br /><br />
	<h4>How do you save my info?</h4>
	<p>We use SSL and a PCI-DSS Level 1 Compliant provider to encrypt your information when you place an order. We never store any of your financial information on our web servers.</p>
	<br /><br />
	<h4>How do I change my stored info?</h4>
	<p>Just click on the info you want to change, enter the changes, and, after you place your order, it’ll be saved for next time.</p>
	<br /><br />
	<h4>But I've never used Crunchbutton before...</h4>
	<p>Oh man, it's okay. I remember my first time, it didn't last more than 30 seconds. I went to Crunchbutton.com, found my favorite restaurant, hit "Get Food." Minutes later, my sandwich arrived. Post-coital bliss ensued, that sandwich sure knew how to crunch my buttons.</p>
	<br /><br />
	<h4>omg i am wayy too drunk to enter my information</h4>
	<p>We thought this might happen. Luckily, Crunchbutton saves your address, phone, and payment info, so all you have to do is click what you want and hit the big, red "Get Food" button. Try to be awake when the delivery guy calls.</p>
	<br /><br />
	<h4>I want to put a restaurant on Crunchbutton.</h4>
	<p>Good idea! <a ng-click="navigation.link('/owners','push')">Get more info and contact us</a>.</p>
	<br /><br />
	
	<h4>I want to drive for Crunchbutton</h4>
	<p>Cool! <a ng-click="navigation.link('/drivers/apply','push')">Fill out an application here</a>.</p>
	<br /><br />
	
	<h4>I know I can order food online, but can I order by US mail?</h4>
	<p>Why yes you can! Give us one week's notice, and we will get you your food! Send a check or money order to: 
	Crunchbutton, 1120 Princeton Dr STE 7, Marina Del Rey, CA 90292</p>
	<br /><br />
	
	<h4>I know I can order food by US mail, but can I order by teleportation?</h4>
	<p>Why yes you can! Send a check or money order to Crunchbutton, 1120 Princeton Dr STE 7, Marina Del Rey, CA 90292, give us 25 years to develop the appropriate technology, and we will get you your food!<br />
	
	<br /><br /><br /><br />
	
	Visit our <a ng-click="navigation.link('/legal','push')">legal page</a> for legal and privacy information.
	<br /><br /><br /><br /><br /><br /><br />
	<center><div class="fa fa-heart faq-heart"></div></center>
	<br /><br /><br /><br />
</div>
