<div class="top-pad"></div>

<div class="restaurants-bubble-wrap">
	<div class="bubble-tail bubble-tail-green bubble-animated">
		<div class="text" ng-switch="pushMessage">
			<span ng-switch-when="1">We choose<br>the best food...</span>
			<span ng-switch-when="2">From the best restaurants...</span>
			<span ng-switch-when="3">So you don't<br> have to!</span>
			<span ng-switch-when="4">Screw huge<br> menus!</span>
			<span class="single-line" ng-switch-when="5">Screw gross food!!</span>
			<span ng-switch-when="6">We only have awesome stuff!</span>
			<span class="single-line" ng-switch-when="7">Got a suggestion?</span>
			<span ng-switch-when="8">Want to work<br> for us?</span>
			<span class="single-line" ng-switch-when="9">Send us a text!</span>
			<span ng-switch-when="10">We are always looking for...</span>
			<span ng-switch-when="11" class="single-line">Awesome people...</span>
			<span class="single-line" ng-switch-when="12">And great food!</span>
			<span class="single-line" ng-switch-when="13"><i class="fa fa-heart"></i> <i class="fa fa-heart"></i> <i class="fa fa-heart"></i></span>
			<span ng-switch-default class="restaurants-push-tagline">Push a button.<br>Get food delivered.</span>
		</div>
		<div class="bubble-tail-spacer"></div>
	</div>
	<div class="restaurants-orange" ng-instant="pushMessage = (pushMessage > 13 ? 0 : (pushMessage + 1))" instant-pass-thru></div>
	<div class="divider"></div>
	<div class="restaurants-tagline">
		<h2><i class="fa fa-hand-o-right"></i>&nbsp;&nbsp;Choose a restaurant</h2>
	</div>
	<div class="divider"></div>
</div>
