

<div class="content-padding">
	<br /><br />
	<div class="home-join-us"></div>
</div>

<div class="content-padding" ng-controller="SupportCtrl">
	<br />

	<h4>Marketing Interns</h4>
	<p>We offer an extensive paid internship program for ambitious candidates, as well as pink gorilla suits.</p>
	<br />
	<a href="mailto:campusreps@crunchbutton.com" target="_blank"><button class="button green">join up</button></a>
	<br /><br /><br /><br />

	<h4>Rockstar Developers &amp; Designers</h4>
	<p>Developer? Rockstar? Perfect.</p>
	<br />
	<a href="mailto:rockstarsonly@crunchbutton.com" target="_blank"><button class="button lightorange">rock out</button></a>
</div>
