
	<div class="divider-orange-food divider-circle" ng-click="scrollHalf()"></div>

	<br /><br /><br />
	<div class="content-padding home-buttons col-box">
		<div class="two-col">
			<h4>Your favorite restaurants, delivered</h4>
			<p>Get food delivered from places that don't deliver. Place an order, and we save it for next time, along with your delivery and payment info. Come back and reorder your favorites with just one click.</p>
			<br><br><br>

			<div class="location-gorillia hide-desktop" ng-click="rage()"></div>

			<h4>Who are you?!</h4>
			<p>We're people! People who love food so much that we want to share our passion without asking you to even leave your homes.</p>
			<br>
			<button class="button lightorange" ng-click="navigation.link('/about','push')">Meet the Team</button>
		</div>
		<div class="two-col hide-mobile">
			<div class="location-gorillia animated-resize" ng-click="rage()"></div>
		</div>
	</div>

	<div class="divider dots spacer-two-one"></div>


	<div class="about-join-bubble-wrap">
		<div class="bubble-curved bubble-curved-green bubble-animated animated-resize">
			<div class="text" ng-switch="orangeMessage">
				<span class="small" ng-switch-when="1">So you can write stupid messages like this</span>
				<span ng-switch-when="2">That no one will ever read</span>
				<span ng-switch-when="3">So you could put anything</span>
				<span class="single-line" ng-switch-when="4">No really.</span>
				<span class="single-line" ng-switch-when="5">Like...</span>
				<span class="single-line" ng-switch-when="6">"Hi Crystal!"</span>
				<span ng-switch-when="7">Did I mention we like beer?</span>
				<span class="single-line" ng-switch-when="8">Yeah we do.</span>
				<span ng-switch-when="9">We even brew our own beer</span>
				<span class="small" ng-switch-when="10">That just screams cool right there</span>
				<span class="single-line" ng-switch-when="11"><i class="fa fa-beer"></i> <i class="fa fa-beer"></i> <i class="fa fa-beer"></i></span>
				<span class="single-line" ng-switch-default><b>Join us!</b></span>
			</div>
		</div>
		<div class="bubble-curved-spacer"></div>
	</div>
	<div class="about-green-orange animated-resize" ng-instant="orangeMessage = (orangeMessage > 10 ? 0 : (orangeMessage + 1))" instant-pass-thru></div>
	<div class="divider"></div>
	<br><br>

	<div class="content-padding home-buttons col-box" ng-controller="SupportCtrl">
		<div class="three-col">
			<h4>Delivery Drivers</h4>
			<p>
				What's better than getting delivery food? Delivering the food! If you have a smartphone, car, and auto insurance, send us a message!
			</p>
			<br />
			<a href ng-click="navigation.link('/drivers/apply','push')"><button class="button green">Apply Now</button></a>
			<br /><br /><br /><br />
		</div>

		<div class="three-col">
			<h4>Marketing Interns</h4>
			<p>
				No one knows more about your college or community than you. You know what's "cool", and that's why we’re going to work with you! Scout for local awesome restaurants to sign up, and play a significant role in orchestrating marketing campaigns.
			</p>
			<br />
			<a href="mailto:{{reps}}"><button class="button green">Join up</button></a>
			<br /><br /><br /><br />
		</div>

		<div class="three-col">
			<h4>Developers &amp; Designers</h4>
			<p>Look at this beautiful website! It's almost perfect! You know what would make it better? Your magical touch! Join our small team of developers located in Los Angeles and let's get shit done!</p>
			<br />
			<a href="mailto:{{devs}}"><button class="button green">Rock Out</button></a>
		</div>

		<!--
		<div class="three-col">
			<a href ng-click="navigation.link('/drivers/apply','push')"><button class="button lightorange">Apply Now</button></a>
		</div>
		<div class="three-col">
			<a href="mailto:{{reps}}"><button class="button lightorange">Join up</button></a>
		</div>
		<div class="three-col">
			<a href="mailto:{{devs}}"><button class="button lightorange">Rock Out</button></a>
		</div>
-->
	</div>

	<div class="divider dots spacer-two-two"></div>
	<br><br>


	<div class="col-box content-padding">
		<div class="two-col">
			<div class="location-map"></div>
		</div>
		<div class="two-col">

				<h4>We’re expanding!</h4>
				<p>We may not be everywhere yet, but the communities we are in love us! Browse some of the food from our most popular locations:</p>
				<br /><br /><br />
				<p>
					<span class="popular-location" ng-repeat="alias in topCommunities">
						<a href="/{{alias.alias}}">{{alias.name}}</a>
					</span>
				</p>

		</div>
	</div>
