<div class="bg">
	<div class="home-top parallax-bg">
		<div class="top-pad"></div>
	
		<div ng-if="!locationError">
			<div class="pushabutton"></div>
			<div class="home-inputs">
				<h4 class="action">What's your full address?</h4>
				<table cellpadding="0" cellspacing="0" class="home-location">
					<tr>
						<td style="width: 100%;"><input class="location-address needsclick" autocapitalize="off" autocorrect="off" placeholder="e.g. 37 Elm St, New Haven CT 06511" ng-focus="softKeyboard($event);" geo-complete-enter="letsEat()" id="input-location-address" ng-model="location.form.address" geo-complete ng-class="{'new-location-address' : location.form.address}">
						</td>
						<td>
							<button class="location-detect" ng-click="locEat()" ng-if="!location.form.address">
								<span class="fa fa-location-arrow" ng-spinner="loadingLocation" data-spinner-color="#fff" data-spinner-scale="1.5"></span>
							</button>
						</td>
					</tr>
				</table>
				<div class="button-pushable find-restaurants">
					<button class="button orange find-restaurants button-letseat-form" ng-click="letsEat()">
						<div ng-spinner="loadingGetfood" data-spinner-color="#fff" data-spinner-scale="1.6">Find Restaurants!</div>
					</button>
				</div>
			</div>
		</div>
		
		<div ng-if="locationError">
			<div class="home-inputs">
			<div class="splash-inputs">

				<div class="cafe-bubble-wrap">
					<div class="bubble-curved bubble-curved-white bubble-animated animated-resize">
						<div class="text" ng-switch="loseMessage">

							<span class="single-line" ng-switch-when="1">Don't worry</span>
							<span class="small" ng-switch-when="2">Just let us know that you want crunchbutton</span>
							<span class="small" ng-switch-when="3">and we will be there<br> as soon as we can!</span>
							<span class="single-line" ng-switch-when="4"><i class="fa fa-cutlery"></i> <i class="fa fa-cutlery"></i> <i class="fa fa-cutlery"></i></span>
							<span class="single-line" ng-switch-default><b>Oh, no!</b></span>

							<? /*
							<div ng-if="account.user.id_user && !recommend.greetings">
								<span class="single-line" ng-switch-when="1">What's the best?</span>
								<span ng-switch-when="2">We listen to our users</span>
								<span class="small" ng-switch-when="3">Let us know <br>and we will add it!</span>
								<span class="single-line" ng-switch-when="4"><i class="fa fa-heart"></i> <i class="fa fa-heart"></i> <i class="fa fa-heart"></i></span>
								<span ng-switch-default><b>What's your<br>favorite?</b></span>
							</div>
							<div ng-if="recommend.greetings">
								<span class="small" ng-switch-when="1">We check this<br> stuff daily!</span>
								<span class="small" ng-switch-when="2">We will get back to you as soon as we can!</span>
								<span class="single-line" ng-switch-when="3"><i class="fa fa-heart"></i> <i class="fa fa-heart"></i> <i class="fa fa-heart"></i></span>
								<span class="single-line" ng-switch-when="4"><i class="fa fa-heart"></i> <i class="fa fa-heart"></i> <i class="fa fa-heart"></i> <i class="fa fa-heart"></i> <i class="fa fa-heart"></i></span>
								<span class="single-line" ng-switch-default><b>Thanks!</b></span>
							</div>
							*/ ?>
						</div>
					</div>
					<div class="bubble-curved-spacer"></div>
				</div>
				<div class="faq-tomato-green animated-resize" ng-instant="loseMessage = (loseMessage > 3 ? 0 : (loseMessage+1))" instant-pass-thru></div>
				<div class="divider spacer-one-two"></div>
				

				<h4>We don't serve that address yet.</h4>
				<p>Crunchbutton is currently in a limited area trial featuring only a select few colleges. Interested in helping to bring Crunchbutton to your area? Become a marketing rep or driver!</p>
				<? /* <p>But you can get notified when we are in your area. We are always expanding and looking for that next popular sandwich. Log in and let us know what you want to see on crunchbutton!</p> */ ?>
				<div class="divider spacer-one-two"></div>

				<div class="button-pushable">
					<button class="button orange" ng-click="navigation.link('/work','push')"><b>bring crunchbutton to you!</b></button>
				</div>

				
				<? /*
				<div ng-if="account.user.id_user && !recommend.greetings">
					<h4>We don't serve that address yet.</h4>
					<p>But you can recommend something. Let us know what you want to see on crunchbutton!</p>
					<div class="divider spacer-one-two"></div>

					<input class="location-recommend" autocapitalize="off" autocorrect="off" placeholder="e.g. Alpha Delta Pizza" ng-enter="recommend.send()" ng-model="recommend.form.restaurant">
					
					<div class="button-pushable">
						<button class="button orange" ng-click="recommend.send()"><b>Recommend</b></button>
					</div>
				</div>

				
				<div ng-if="recommend.greetings">
					<h4>Sent to our brains!</h4>
					<p>We will let you know soon! Thanks for trying crunchbutton!</p>
				</div>
				*/ ?>
	
				<p class="center-text">
					<a href="" class="splash-continue" ng-instant="resetFormLocation()">Try another location</a>
				</p>
			</div>
		</div>

		</div>
	</div>
	
	<div class="divider-orange-food divider-circle" ng-click="scrollHalf()"></div>
	
	<br /><br /><br />
	<div class="content-padding home-buttons col-box">
		<div class="two-col">
			<h4>Order your favorite restaurants, delivered</h4>
			<p>Crunchbutton lets you order the best restaurants in your area delivered straight to your door. Place an order, and we save it for next time, along with your delivery and payment info. Come back and reorder your favorites with just one click.</p>
			<br><br><br>
			
			<div class="location-gorillia hide-desktop" ng-click="rage()"></div>
			
			<h4>Who are you?!</h4>
			<p>We're people! People who love food so much that we want to share our passion without asking you to even leave your homes.</p>
			<br>
			<button class="button lightorange" ng-click="navigation.link('/about','push')">Meet the Team</button>
		</div>
		<div class="two-col hide-mobile">
			<div class="location-gorillia animated-resize" ng-click="rage()"></div>
		</div>
	</div>

	<div class="divider dots spacer-two-one"></div>
	

	<div class="about-join-bubble-wrap">
		<div class="bubble-curved bubble-curved-green bubble-animated animated-resize">
			<div class="text" ng-switch="orangeMessage">
				<span class="small" ng-switch-when="1">So you can write stupid messages like this</span>
				<span ng-switch-when="2">That no one will ever read</span>
				<span ng-switch-when="3">So you could put anything</span>
				<span class="single-line" ng-switch-when="4">No really.</span>
				<span class="single-line" ng-switch-when="5">Like...</span>
				<span class="single-line" ng-switch-when="6">"Hi Crystal!"</span>
				<span ng-switch-when="7">Did I mention we like beer?</span>
				<span class="single-line" ng-switch-when="8">Yeah we do.</span>
				<span ng-switch-when="9">We even brew our own beer</span>
				<span class="small" ng-switch-when="10">That just screams cool right there</span>
				<span class="single-line" ng-switch-when="11"><i class="fa fa-beer"></i> <i class="fa fa-beer"></i> <i class="fa fa-beer"></i></span>
				<span class="single-line" ng-switch-default><b>Join us!</b></span>
			</div>
		</div>
		<div class="bubble-curved-spacer"></div>
	</div>
	<div class="about-green-orange animated-resize" ng-instant="orangeMessage = (orangeMessage > 10 ? 0 : (orangeMessage + 1))" instant-pass-thru></div>
	<div class="divider"></div>
	<br><br>
	
	<div class="content-padding home-buttons col-box" ng-controller="SupportCtrl">
		<div class="three-col">
			<h4>Delivery drivers</h4>
			<p>
				What's better than getting delivery food? Delivering the food! If you have a smartphone, car, and auto insurance, send us a message!
			</p>
			<br />
			<a href ng-click="navigation.link('/drivers/apply','push')"><button class="button green">Apply Now</button></a>
			<br /><br /><br /><br />
		</div>

		<div class="three-col">
			<h4>Community Representative</h4>
			<p>
				No one knows more about your college or community than you. You know what's "cool", and that's why we’re going to work with you! Scout for local awesome restaurants to sign up, and play a significant role in orchestrating marketing campaigns.
			</p>
			<br />
			<a href="mailto:{{reps}}"><button class="button green">Join up</button></a>
			<br /><br /><br /><br />
		</div>

		<div class="three-col">
			<h4>Rockstar Developers &amp; Designers</h4>
			<p>Look at this beautiful website! It's almost perfect! You know what would make it better? Your magical touch! Join our small team of developers located in Los Angeles and let's get shit done!</p>
			<br />
			<a href="mailto:{{devs}}"><button class="button green">Rock Out</button></a>
		</div>

		<!--
		<div class="three-col">
			<a href ng-click="navigation.link('/drivers/apply','push')"><button class="button lightorange">Apply Now</button></a>
		</div>
		<div class="three-col">
			<a href="mailto:{{reps}}"><button class="button lightorange">Join up</button></a>
		</div>
		<div class="three-col">
			<a href="mailto:{{devs}}"><button class="button lightorange">Rock Out</button></a>
		</div>
-->
	</div>
	
	<div class="divider dots spacer-two-two"></div>
	<br><br>
	
	
	<div class="col-box content-padding">
		<div class="two-col">
			<div class="location-map"></div>
		</div>
		<div class="two-col">

				<h4>We’re expanding!</h4>
				<p>We may not be everywhere yet, but the communities we are in love us! Browse some of the food from our most popular locations:</p>
				<br /><br /><br />
				<p>
					<span class="popular-location" ng-repeat="alias in topCommunities">
						<a href ng-click="openCity(alias.alias)" permalink="{{alias.alias}}">{{alias.name}}</span>
					</span>
				</p>
			
		</div>
	</div>
</div>