<div class="top-pad"></div>

<div ng-if="!order.id">
	<div class="content-padding">
		<div class="ajax-loader-teal"></div>
		<br />
	</div>
</div>

<div ng-if="order.id">


	<div class="">

		<div class="content-padding">
			<div class="order-tagline"><p>
				<b>Crunched!</b> Your order is placed and has been saved for easy 1 click reordering
			</p></div>
		</div>

		<div class="divider dots"></div>
		<div class="spacer-two-two"></div>

		<div class="content-padding-desktop">

			<div class="content-padding-mobile">

				<div ng-hide="account.user.has_auth">
					<div class="order-buttons">
						<p>
							Create an account and earn {{order.reward.points}} points towards a <b>free delivery</b> and reorder your favorite food anywhere, including <a data-ng-href="http://crunchbutton.com">crunchbutton.com</a> and our&nbsp;
							<span ng-if="!isMobile"><a href="/download">mobile apps</a>.</span>
							<span ng-if="isMobile">
								<span ng-if="!isAndroid"><a data-ng-href="https://itunes.apple.com/app/id721780390">iOS App</a>.</span>
								<span ng-if="isAndroid"><a data-ng-href="https://play.google.com/store/apps/details?id=com.crunchbutton">Android App</a>.</span>
							</span>
						</p>
						<br>
						<div class="button-pushable">
							<button class="button lightorange" ng-click="modal.signupOpen();">Create an account</button>
						</div>
						<br />
					</div>

				</div>

				<div ng-show="account.user.has_auth">

					<div class="order-buttons">
						<p ng-if="account.user.points.free_delivery_message && account.user.points.free_delivery" class="delivery-free order-delivery-free">
							You have <strong>{{account.user.points.show}}</strong> points! The next delivery fee is on us.
						</p>
						<div ng-if="!account.user.points.free_delivery_message">
							<p class="delivery-free points-earned-message">
								You just earned <strong>{{order.reward.points}}</strong> points!
								<span ng-if="!account.user.points.free_delivery_message">
									<strong> {{account.user.points.free_delivery}}</strong> points gets you a free delivery.
								</span>
							</p>
						</div>

					</div>
				</div>

			</div>
			<div class="content-padding-mobile" ng-show="account.user.has_auth">

				<!-- <div class="col-box"> -->

					<div class="hide-desktop button-refer-big">
						<a href="{{referral.sms}}">
							<button class="button lightorange">
								<i class="fa fa-comment"></i>&nbsp;&nbsp;&nbsp;<span>Invite Friends</span>
							</button>
						</a>
					</div>

					<div class="button-refer-big">
						<span class="refer-multiply hide-mobile">Double your points by sharing on Facebook</span>
						<span class="refer-multiply-small hide-desktop">Double your points by sharing on Facebook</span>

						<button class="button facebook" ng-click="referral.facebook('order');" ng-if="account.user.has_auth && !order.reward.shared.facebook">
							<i class="fa fa-facebook-square"></i> <span>Share</span>
						</button>
					</div>

					<div class="button-refer-big">
						<span class="refer-multiply hide-mobile">Triple them by sharing on Twitter.</span>
						<span class="refer-multiply-small hide-desktop">Triple them by sharing on Twitter</span>
						<button class="button twitter" ng-click="referral.twitter('order')" ng-if="account.user.has_auth && !order.reward.shared.twitter">
							<i class="fa fa-twitter-square"></i> <span>Tweet</span>
						</button>
					</div>

				<!-- </div> -->

				<div ng-if="order.reward.shared.facebook">
					Thanks for sharing on Facebook.
				</div>

				<div ng-if="order.reward.shared.twitter">
					Thanks for sharing on Twitter.
				</div>
				<div class="divider"></div>
				<br><br>
				<div class="content-padding">
					<p class="center-text">
						Earn a FREE DELIVERY for every new customer you refer with your link!
						<br><br>
					</p>
				</div>

			</div>

		</div>

		<div class="divider dots"></div>
		<div class="spacer-two-two"></div>

		<div class="content-padding-desktop">
			<div class="content-padding-mobile">

				<div class="order-bubble-wrap">
					<div class="bubble-tail bubble-tail-green bubble-animated">
						<div class="text" ng-switch="cherryMessage">
							<span ng-switch-when="1" class="single-line">Yay! Food!</span>
							<span ng-switch-when="2" class="single-line">It's on it's way.</span>
							<span ng-switch-when="3" class="small">Questions? Please contact the restaurant.</span>
							<span ng-switch-when="4">Feedback? Send us a text.</span>
							<span ng-switch-when="5">We'd love to hear your thoughts...</span>
							<span ng-switch-when="6">suggestions, or even complaints!</span>
							<span ng-switch-when="7">The customer is always right!</span>
							<span class="single-line" ng-switch-when="8"><i class="fa fa-heart"></i> <i class="fa fa-heart"></i> <i class="fa fa-heart"></i></span>
							<span ng-switch-default class="single-line"><b>Sit back &amp relax!</b></span>
						</div>
						<div class="bubble-tail-spacer"></div>
					</div>
					<div class="hot-dog-relax animated-resize" ng-instant="cherryMessage = (cherryMessage > 7 ? 0 : (cherryMessage + 1))" instant-pass-thru></div>
					<div class="divider"></div>
				</div>
			</div>

			<div class="divider"></div>

			<div class="spacer-two-two"></div>

		</div>

		<div class="content-padding">
			<p class="center-text">
				For more info about your order, view <a ng-click="receipt()">Order Details</a>.
			</p>
		</div>
		<div class="content-padding">
			<p class="notes-text">
				If you need to cancel or change details about your order, please text us at <a href="sms:+16467831444">(646) 783-1444</a> within 5 min of ordering for us to be able to issue refunds/make changes.
			</p>
		</div>




	</div>

</div>