<div class="top-pad"></div>

<div ng-if="!order.id">
	<div class="content-padding">
		<div class="ajax-loader-teal"></div>
		<br />
	</div>
</div>

<div ng-if="order.id">
	
		
	<div class="hide-mobile">
		<div class="content-padding">
			<div class="order-tagline"><p>
				<b>Your order
				<span ng-show="(order.delivery_type == 'delivery')">is on its way</span>
				<span ng-hide="(order.delivery_type == 'delivery')">has been placed</span>
				</b>and saved for easy 1 click reordering
			</p></div>
		</div>
	
		<div class="divider dots"></div>
		<div class="spacer-two-two"></div>
	</div>

	<div class="col-box content-padding-desktop">

		
		<div class="two-col content-padding-mobile" ng-if="confirm">
			<div class="order-bubble-wrap">
				<div class="bubble-tail bubble-tail-green bubble-animated">
					<div class="text" ng-switch="cherryMessage">
						<span ng-switch-when="1" class="single-line">Yay! Food!</span>
						<span ng-switch-when="2" class="single-line">It's on it's way.</span>
						<span ng-switch-when="3" class="small">Questions? Please contact the restaurant.</span>
						<span ng-switch-when="4">Feedback? Send us a text.</span>
						<span ng-switch-when="5">We'd love to hear your thoughts...</span>
						<span ng-switch-when="6">suggestions, or even complaints!</span>
						<span ng-switch-when="7">The customer is always right!</span>
						<span class="single-line" ng-switch-when="8"><i class="fa fa-heart"></i> <i class="fa fa-heart"></i> <i class="fa fa-heart"></i></span>
						<span ng-switch-default class="single-line"><b>Sit back &amp Relax!</b></span>
					</div>
					<div class="bubble-tail-spacer"></div>
				</div>
				<div class="hot-dog-relax animated-resize" ng-instant="cherryMessage = (cherryMessage > 7 ? 0 : (cherryMessage + 1))" instant-pass-thru></div>
				<div class="divider"></div>
			</div>
		</div>

		<div class="content-padding-mobile hide-desktop">
			<div class="order-tagline"><p>
				<b>Your order
				<span ng-show="(order.delivery_type == 'delivery')">is on its way</span>
				<span ng-hide="(order.delivery_type == 'delivery')">has been placed</span>
				</b><br>and saved for easy 1 click reordering
			</p></div>
		</div>

		<div class="divider dots spacer-one-one"></div>

		<div class="two-col content-padding-mobile">
			<div ng-hide="account.user.has_auth">
				<div class="order-buttons">
					<p>
						Create an account and earn {{order.reward.points}} points towards a <b>free delivery</b> and reorder your favorite food anywhere, including <a data-ng-href="http://crunchbutton.com">crunchbutton.com</a> and our&nbsp;
						<a ng-show="!isAndroid" data-ng-href="https://itunes.apple.com/app/id721780390">iOS App</a>
						<a ng-show="isAndroid" data-ng-href="https://play.google.com/store/apps/details?id=com.crunchbutton">Android App</a>
					</p>

					<br>
					<div class="button-pushable">
						<button class="button lightorange" ng-click="modal.signupOpen();">Create an account</button>
					</div>
					<br />
				</div>

			</div>

			<div ng-show="account.user.has_auth">

				<div class="order-buttons">

					<p ng-if="account.user.points.free_delivery_message && account.user.points.free_delivery" class="delivery-free order-delivery-free">
						You have <strong>{{account.user.points.show}}</strong> points! The next delivery fee is on us.
					</p>
					<div ng-if="!account.user.points.free_delivery_message">
						<p class="delivery-free">
							You just earned <strong>{{order.reward.points}}</strong> points!
							<span ng-if="account.user.points.away_free_delivery > 0"> You are <strong>{{account.user.points.away_free_delivery}}</strong> points away from a free delivery.</span>
						</p>
					</div>
					<div class="hide-mobile">
						<p>
							Want more points? Share on Facebook or Twitter for double points<span ng-if="referral.invite_url && referral.enabled">, and earn free delivery for any friends you refer</span>.
							<br><br>
						</p>

						<div class="col-box">

							<button class="button facebook button-refer" ng-click="referral.facebook('order');" ng-if="account.user.has_auth && !order.reward.shared.facebook">
								<i class="fa fa-facebook-square"></i> <span>Share</span>
							</button>

							<button class="button twitter button-refer" ng-click="referral.twitter('order')" ng-if="account.user.has_auth && !order.reward.shared.twitter">
								<i class="fa fa-twitter-square"></i> <span>Tweet</span>
							</button>
						</div>

						<div ng-if="order.reward.shared.facebook">
							Thanks for sharing on Facebook.
						</div>

						<div ng-if="order.reward.shared.twitter">
							Thanks for sharing on Twitter.
						</div>
						<div class="divider"></div>

					</div>


					<div class="hide-desktop">
						<p class="order-earn-mobile">Earn more free deliveries by inviting friends.</p>
						<br>
						<a href="{{referral.sms}}">
							<button class="button lightorange">
								<i class="fa fa-comment"></i>&nbsp;&nbsp;&nbsp;<span>Invite Friends</span>
							</button>
						</a>
					</div>

				</div>
			</div>

		</div>
	</div>


	<div class="order-content">

		<div class="divider dots spacer-two-two"></div>


		<div class="content-padding">
			<p>
				For order details, receipt, and to track your order, view <a ng-click="receipt()">Order details</a>.
			</p>
		</div>

		


	</div>
</div>