<div class="top-pad"></div>

<div class="content-padding">

	<a id="credit"></a>

	<div ng-show="!account.user.points.free_delivery_message && account.user.points.away_free_delivery">
		<p class="delivery-free">You are <strong>{{account.user.points.away_free_delivery}}</strong> points away from a free delivery.</p><br/>
		<p>Earn points by ordering food, sharing your order, or referring friends.</p><br/>
	</div>
	<div ng-show="account.user.points.free_delivery_message && account.user.points.free_delivery">
		<p class="delivery-free">You have <strong>{{account.user.points.free_delivery}}</strong> points! The next delivery fee is on us.</p>
	</div>

	<br/>

	<div class="divider"></div>

	<div ng-show="account.user.invite_code">
		<p>
			Get your friends to enter your code below in the Notes section of their first order, and they will get $3 off and you a 	delivery free ;)
		</p><br/>
		<p class="order-code"><strong>{{account.user.invite_code}}</strong></p>
	</div>
	<br/>


	<button class="button facebook" ng-click="referral.facebook()">
		<i class="fa fa-facebook-square"></i> <span>Share</span>
	</button>

	<br><br>

	<button class="button twitter" ng-click="referral.twitter()">
		<i class="fa fa-twitter-square"></i> <span>Tweet</span>
	</button>

	<br><br>

</div>

<div class="divider"></div>

<div class="content-padding">

<div ng-show="!orders.list">
	<div class="content-padding">
		<div class="stamp-loader">
			<div class="stamp-loader-button"></div>
			<div class="stamp-loader-words"></div>
		</div>
	</div>
</div>

<div class="content-padding" ng-show="orders.list">

	<div class="orders-oranges animated-resize"></div>
	<? /* You know, you can reorder any of your previous orders by taping on one of them, then reordering from the next page. Try it! */ ?>
</div>



<div ng-show="orders.list.length == 0">
	<div class="content-padding">
		<p>After you place orders, you'll see them all right here. </p>
		<h4><a href="/food-delivery" ng-click="navigation.link('/food-delivery')">Place an order</a></h4>
		<br /><br />
	</div>
</div>

<div ng-show="orders.list && orders.list.length > 0">
	<div class="content-padding">
		<ul class="orders-list">
			<li ng-repeat="order in orders.list" class="order-item-wrap" ng-click="orders.receipt(order.id)">
				<div class="order-item">
					<div class="order-date">
						<div class="order-month">{{order._date.getMonthNameShort()}}</div>
						<div class="order-day">{{order._date.getDate().pad(2)}}</div>
					</div>
					<div class="order-details">
						<div class="order-name" ng-click="$event.preventDefault(); $event.stopPropagation(); orders.restaurant(order._restaurant_permalink);">
							{{order._restaurant_name}}
						</div>
						<div class="divider"></div>
						<div class="order-summary">
							{{order.summary}}
						</div>
					</div>

					<div class="order-link fa fa-arrow-circle-right"></div>
				</div>
				<div class="divider"></div>
			</li>
		</ul>
	</div>
</div>