<div class="top-pad"></div>

<div class="faq-bubble-wrap">
	<div class="bubble-tailless-green">
		<div class="text">
			<b>&nbsp;&nbsp;We're good</b><br />
			for your business!
		</div>
	</div>
	<div class="owner-brocoli"></div>
	<div class="divider"></div>
</div>

<div class="content-padding owner-content" ng-controller="SupportCtrl">
	<br />


	<p>We choose the best food that local customers love. We make your restaurant cemented as a local favorite, drive additional business, and make you and your customers happier.</p>
	<br /><br />

	<div class="owner-block">
		<div class="owner-icon"><i class="fa fa-usd"></i></div>
		<div class="owner-text">
			<h4>No upfront costs.</h4>
			<p>There is a percentage fee, but any or all of itcan be passed to customers -- this includes credit card fees.</p>
		</div>
	</div>
	<div class="divider"></div>

	<div class="owner-block">
		<div class="owner-icon"><i class="fa fa-heart"></i></div>
		<div class="owner-text">
			<h4>Customers love us.</h4>
			<p>Simply put, we're the easiest to use online ordering out there. Customers make repeat orders with the click of a button. We make it easy for customers to view and order their favorite items, and if you qualify, we label you as a favorite for them.</p>
		</div>
	</div>

	<div class="divider"></div>

	<div class="owner-block">
		<div class="owner-icon"><i class="fa fa-check"></i></div>
		<div class="owner-text">
			<h4>We're streamlined.</h4>
			<p>Getting you up and running is as simple as collecting a few pieces of info. We can notify you of orders by fax, phone, text message, email, and/or online system. We pay you by check or bank deposit.</p>
		</div>
	</div>

	<div class="divider"></div>

	<div class="owner-block">
		<div class="owner-icon"><i class="fa fa-star"></i></div>
		<div class="owner-text">
			<h4>It's great for business.</h4>
			<p>Your popular items are promoted as user favorites. Case study: a week after our launch in New Haven, we were driving $9K in orders per month to early adopter restaurants.</p>
		</div>
	</div>
	<br><br>
	<a href="tel:+18003514161"><button class="button green">Call us @ 800-351-4161</button></a>
</div>
