<div class="top-pad"></div>

<div class="faq-bubble-wrap">
	<div class="bubble-tailless-green">
		<div class="text">
			<b>&nbsp;&nbsp;Don’t Worry!</b><br />
			We’re here to help!
		</div>
	</div>
	<div class="faq-tomato"></div>
	<div class="divider"></div>
</div>

<div class="content-padding" ng-controller="SupportCtrl">
	<br />


	<p>We choose the best food that local customers love. We make your restaurant cemented as a local favorite, drive additional business, and make you and your customers happier.</p>
	<br /><br />
	
	<h4>No upfront costs.</h4>
	<p>There is a percentage fee, but any or all of itcan be passed to customers -- this includes credit card fees.</p>

	<h4>Customers love us.</h4>
	<p>Simply put, we're the easiest to use online ordering out there. Customers make repeat orders with the click of a button. We make it easy for customers to view and order their favorite items, and if you qualify, we label you as a favorite for them.</p>

	<h4>We're streamlined.</h4>
	<p>Getting you up and running is as simple as collecting a few pieces of info. We can notify you of orders by fax, phone, text message, email, and/or online system. We pay you by check or bank deposit.</p>

	<h4>It's great for business.</h4>
	<p>Your popular items are promoted as user favorites. Case study: a week after our launch in New Haven, we were driving $9K in orders per month to early adopter restaurants.</p>
	
	<button class="button green" ng-click="support.dialog()">Send us a message</button>
</div>
