<div class="referral-container zoom-anim-dialog mfp-hide dialog mfp-hide" ng-controller="RewardCtrl">
	<!-- Success -->
	<div class="dialog-padding account-modal">
		<p>
			<b>Congrats!</b>
		</p>
		<div class="divider spacer-one-onehalf"></div>
		<p>
			<strong>{{invitedUsers}}</strong> just placed an order!
			Get free deliveries for any other new customers you refer ;)
		</p>
	</div>

	<div class="dialog-divider"></div>
	<div class="dialog-padding dialog-bottom-buttons">
		<div class="button-pushable">
			<button ng-click="modal.close()" class="button green">Great</button>
		</div>
	</div>

</div>
