<div class="top-pad"></div>

<div class="faq-bubble-wrap">
	<div class="bubble-tailless-green">
		<div class="text">
			<b>&nbsp;&nbsp;Don’t Worry!</b><br />
			We’re here to help!
		</div>
	</div>
	<div class="faq-tomato"></div>
	<div class="divider"></div>
</div>

<div class="content-padding" ng-controller="SupportCtrl">
	<br />

	<h4>Need to contact Crunchbutton?</h4>
	<p>Call or text us at <a href="tel:+16467831444">(646) 783-1444</a> or email us at <a href="mailto:happycustomers@crunchbutton.com">happycustomers@crunchbutton.com</a>.</p>
	<br /><br />
	<button class="button green" ng-click="support.dialog()">Send us a message</button>
</div>
