<div class="restaurant-suggestion-container zoom-anim-dialog mfp-hide dialog mfp-hide">

	<div ng-controller="RestaurantSuggestionCtrl">

		<div ng-if="tab == 'form'">

			<div class="dialog-padding">

				<p>What's wrong?</p>

				<div class="support-form-group form-group">
					<textarea ng-focus="softKeyboardModal($event)" ng-model="suggestion.content" class="form-input form-field"></textarea>
				</div>

				<div class="divider spacer-one-onehalf"></div>

				<p>Any specific items you'd like to see, enter here:</p>

				<div class="support-form-group form-group">
					<textarea ng-focus="softKeyboardModal($event)" ng-model="suggestion.add_more_content" class="form-input form-field"></textarea>
				</div>

			</div>

			<div class="dialog-padding dialog-bottom-buttons">
				<div class="button-pushable">
					<button class="button green" ng-click="send_form()">Submit</button>
				</div>
			</div>


		</div>

		<div ng-if="tab == 'thank-you'">

			<div class="dialog-padding">
				<p><strong>Thank you!</strong></p>
				<div class="location-gorillia animated-resize shake"></div>
				<button class="button green" ng-click="close()">Get me out of here</button>
			</div>

		</div>

	</div>

</div>