<div class="bg">
	<div ng-show="!order.loaded">
		<? /* THIS WILL SHOW UP WHEN A RESTAURANT PAGE IS DIRECTLY LOADED FROM A BROWSER BEFORE THE PAGE SHOWS. */ ?>
	</div>

	<div ng-show="restaurant">

		<div class="restaurant-pad"></div>

		<!-- image -->
		<ng-include src="'assets/view/restaurant-image.html'"></ng-include>

		<!-- main-content-readable-margin -->
		<div class="restaurant-content-body content-padding">
			<div class="restaurant-content-body-background"></div>

			<!-- comment -->
			<ng-include src="'assets/view/restaurant-comment.html'"></ng-include>

			<div ng-if="restaurant.eta" class="restaurant-message">Delivery estimate: {{restaurant.eta}} minutes</div>

			<div restaurant-is-closed></div>


			<div class="cart-items restaurant-side-bar restaurant-side-bar-margin">

				<!-- cart -->
				<ng-include src="'assets/view/restaurant-cart.html'"></ng-include>

				<!-- just for desktop -->
				<div ng-if="!isMobileWidth && restaurant._open && order.cart.hasItems()">
					<div class="payment-content"><ng-include src="'assets/view/restaurant-breakdown.html'"></ng-include></div>
					<!-- place order button -->
					<div class="button-pushable" ng-show="order.form.name || order.form.phone"><button class="button orange get-food ani-all" ng-click="order.submit();"><div>Place Order</div></button></div>
					<div class="button-pushable" ng-show="!order.form.name && !order.form.phone"><button class="button orange get-food ani-all" ng-click="order.checkout();"><div>Checkout</div></button></div>
				</div>

			</div>

			<!-- menu -->
			<ng-include src="'assets/view/restaurant-menu.html'"></ng-include>

			<div class="divider"></div>

			<!-- payment and user info -->
			<ng-include src="'assets/view/restaurant-form-user-info.html'"></ng-include>

			<!-- stored user info -->
			<ng-include src="'assets/view/restaurant-stored-user-info.html'"></ng-include>

		<div class="divider"></div>

		</div>

	</div>

	<!-- total breakdown -->
	<ng-include ng-if="isMobileWidth" src="'assets/view/restaurant-breakdown.html'"></ng-include>

	<div class="divider bottom-spacer"></div>

</div>

<ng-include src="'assets/view/restaurant-message-boxes.html'"></ng-include>