<div class="bg">
	<div ng-show="!order.loaded">
		<? /* THIS WILL SHOW UP WHEN A RESTAURANT PAGE IS DIRECTLY LOADED FROM A BROWSER BEFORE THE PAGE SHOWS. */ ?>
	</div>

	<div ng-show="restaurant">

		<div class="restaurant-pad"></div>

		<!-- image -->
		<ng-include src="'assets/view/restaurant-image.html'"></ng-include>

		<!-- main-content-readable-margin -->
		<div class="restaurant-content-body content-padding">
			<div class="restaurant-content-body-background"></div>

			<!-- comment -->
			<ng-include src="'assets/view/restaurant-comment.html'"></ng-include>

			<div ng-if="restaurant.eta" class="restaurant-message">Delivery estimate: {{restaurant.eta}} minutes</div>

			<div restaurant-is-closed></div>

			<!-- desktop version -->
			<ng-include ng-if="!isMobileWidth" src="'assets/view/restaurant-desktop.html'"></ng-include>

			<!-- mobile version -->
			<ng-include ng-if="isMobileWidth" src="'assets/view/restaurant-mobile.html'"></ng-include>

		</div>

	</div>

	<!-- total breakdown - mobile only -->
	<ng-include ng-if="isMobileWidth" src="'assets/view/restaurant-breakdown.html'"></ng-include>

	<div class="divider bottom-spacer"></div>

</div>

<ng-include src="'assets/view/restaurant-message-boxes.html'"></ng-include>