<div class="delivery-payment-info restaurant-side-bar restaurant-side-user-info" ng-if="order.loaded && restaurant._open && !order.showForm && order.cart.hasItems()">

	<div class="divider dots"></div>

	<div class="content-padding">

		<div class="order-icon"><div class="icon-phone"></div></div>
		<div class="order-info order-info-oneline">
			<p>
				<span ng-show="user.phone">{{ user.phone | formatPhone }}</span>
				<span ng-show="!user.phone">no phone # provided</span>
			</p>
		</div>
		<div class="divider"></div>
		<div class="order-icon">
				<div class="icon-credit" ng-show="order.form.pay_type=='card' && order.total() <= credit.number"></div>
				<div class="icon-card" ng-show="order.form.pay_type=='card' && order.total() > credit.number"></div>
				<div class="icon-cash" ng-show="order.form.pay_type=='cash'"></div>
		</div>
		<div class="order-info order-info-oneline">

			<p>
				<span ng-show="order.form.pay_type=='card' && order.total() <= credit.number">Gift card balance</span>
				<span ng-show="order.form.pay_type=='card' && credit.number && order.total() > credit.number">Card ending in {{user.card_ending}} &amp; - {{credit.value}} credit</span>
				<span ng-show="order.form.pay_type=='card' && !credit.number">Card ending in {{user.card_ending}}</span>
				<span ng-show="order.form.pay_type=='cash'">Pay and tip with <b>cash</b>
					<span ng-if="config.driver_change_amount">
						<br><i>Drivers only carry ${{config.driver_change_amount}} in change</i>
					</span>
				</span>
			</p>
		</div>
		<div class="divider"></div>


		<div class="order-icon">
			<div class="icon-map-home" ng-show="restaurant.delivery == '1' && order.form.delivery_type=='delivery'"></div>
			<div class="icon-map-restaurant" ng-show="restaurant.takeout == '1' && order.form.delivery_type=='takeout'"></div>
		</div>
		<div class="order-info" ng-show="restaurant.delivery == '1' && order.form.delivery_type=='delivery'">
			<p>
				Delivered to:<br />
			</p>
			<p class="restaurant-info-address">
				<span ng-bind-html-unsafe="order.form.address | nl2br"></span>
				<i ng-hide="order.form.address">no address provided</i>
			</p>
		</div>
		<div class="order-info" ng-show="restaurant.takeout == '1' && order.form.delivery_type=='takeout'">
			<p class="restaurant-info-address">
				Pick up from:<br />
				<span ng-bind-html-unsafe="restaurant.address | nl2br"></span>
			</p>
		</div>


		<div class="divider"></div>

				<div class="payment-form-group form-group">

					<i class="fa fa-bullhorn payment-form-icon form-icon form-field"></i>
					<textarea ng-focus="softKeyboard($event);" ng-autosize name="notes" ng-blur="checkGiftCard()" ng-model="order.form.notes" tabindex="6" class="payment-form-input form-input form-field notes-text-area" placeholder="notes"></textarea>

					<!-- Gift card messages -->
					<div class="giftcard-info">

						<div class="warning" ng-if="giftcard.removed">
							You just removed a gift card. If you still want to use that gift card, you must put it back in the notes field.
						</div>

						<div ng-if="restaurant.giftcard == 0 && giftcard.hasGiftCards">
							This restaurant does not accept gift card.
						</div>

						<div ng-if="giftcard.hasValue && order.form.pay_type == 'cash' ">
							Pay with a card, NOT CASH, to use your {{AB.dollar}}{{giftcard.value}} gift card!</span>
						</div>

					<div ng-repeat="success in giftcard.giftcards.success">
						<div ng-if="success.delivery_free && restaurant.delivery == '1' && order.form.delivery_type=='delivery'">
							<span ng-if="order.form.pay_type == 'card'">{{success.message}}</span>
							<span ng-if="order.form.pay_type == 'cash'">Pay with a card, NOT CASH, to get your delivery free</span>
						</div>
					</div>


					<div ng-if="restaurant.giftcard == 1 && order.form.pay_type == 'card' ">
						<!-- Gift card success -->
						<div ng-repeat="success in giftcard.giftcards.success">
							<div ng-if="!success.delivery_free && !success.message">
								<div ng-show="!success.error">
									Congrats! This gift card ({{success.giftcard}}) gives you ${{success.value}}.
								</div>
								<div ng-show="success.error == 'other restaurant'">
									The gift card ({{success.giftcard}}) you are trying to use belongs to another restaurant.
								</div>
							</div>
							<div ng-if="success.message">
								{{success.message}}
							</div>
						</div>
						<!-- Gift card errors -->
						<div ng-repeat="error in giftcard.giftcards.error">
							<div ng-switch on="error.error">
								<div ng-switch-when="gift card already used">
									The gift card ({{error.giftcard}}) you are trying to use was already redeemed.
								</div>
								<div ng-switch-when="custom">
									{{error.message}}
								</div>
							</div>
						</div>
						<span ng-if="giftcard.justOneGiftCardError">
							You can only use one gift card at a time!
						</span>
					</div>
				</div>
		</div>

		<div class="divider"></div>

		<div class="divider spacer-one-two"></div>

		<p>We’ve saved your payment and delivery info for one click reordering.</p>

		<div class="divider spacer-one-two"></div>

		<button class="button green" ng-click="order.showForm=true">Change info</button>
	</div>
</div>