

<div ng-show="!order.loaded">
	<div class="top-pad"></div>

	<? /* THIS WILL SHOW UP WHEN A RESTAURANT PAGE IS DIRECTLY LOADED FROM A BROWSER BEFORE THE PAGE SHOWS. */ ?>
</div>

<div ng-show="order.loaded">

	<div class="restaurant-pad"></div>
	
	<div ng-show="restaurant.image">
		<div class="restaurant-pic" style="background: url({{restaurant.img}});">
		
			<div class="restaurant-name">
				<h1>{{restaurant.name}}</h1>
				<h2>{{restaurant.message || restaurant.short_description}}</h2>
			</div>
		</div>
		
		<div class="giftcard-badge-container" ng-show="credit.hasValue">
			<div class="giftcard-badge">
				<div ng-click="credit.tooltip=!credit.tooltip" class="giftcard-badge-value">${{credit.value}}</div>
			</div>
			<div class="giftcard-badge-tooltip" ng-show="credit.tooltip">
				You have a <span class="giftcard-value">{{AB.dollar}}{{credit.value}}</span> gift card
			</div>
		</div>
	</div>


	<!-- main-content-readable-margin -->
	<div class="content-padding">
	
		<div restaurant-is-closed></div>

		<!-- cart -->
		<div class="cart-items">
			<div ng-show="restaurant._open">

				<div ng-show="!order.cart.hasItems()" class="restaurant-box">
					<div class="restaurant-box-inner">
						<span class="restaurant-box-icon">
							<i class="fa fa-arrow-down"></i> 
						</span>
						<span class="restaurant-box-content">
							<? /* <span class="hidden-lt-1023">{{nothingInTheCartDesktop}}</span> */ ?>
							<span class="restaurant-box-subtitle restaurant-box-align">{{nothingInTheCartMobile}}</span>
						</span>
					</div>
				</div>

				<div ng-show="order.cart.hasItems()">
					<div class="restaurant-title">The Order</div>
			
					<div ng-show="order.info.deliveryMinDiff && order.cart.hasItems()" class="delivery-minimum-error">
						Add $<span class="delivery-min-diff">{{order.info.deliveryMinDiff}}</span> from menu to meet delivery minimum.
					</div>
				</div>


				<!-- Cart's basket -->
				<div ng-repeat="item in order.cart.items">

					<div class="cart-item">

						<div class="cart-button cart-button-remove" ng-click="order.cart.remove(item.details.id);"><span class="fa fa-times-circle"></span></div>

						<div class="cart-item-text">
							<span class="cart-item-name">{{item.details.name}}</span><br />
							<span class="cart-item-description">{{item.details.description}}</span>
						</div>

						<div ng-show="item.details.customization.customizable" ng-click="item.details.customization.expanded=!item.details.customization.expanded" class="cart-item-config">Customize</div>
						
						<div class="divider"></div>

					</div>

					<!-- Customizable options -->
					<div class="cart-customize-options" ng-show="item.details.customization.customizable && item.details.customization.expanded">
						
						<div ng-repeat="option in item.details.customization.options">

							<div class="cart-item-customize-item">
							
								<div ng-switch on="option.type">

									<!-- Customizable - checkbox -->
									<div ng-switch-when="check">
										<input type="checkbox" custom-checkbox ng-change="order.cart.customizeItem(option, item)" ng-model="option.checked" class="cart-customize-check">
										<span ng-click="option.checked = !option.checked; order.cart.customizeItem(option, item);" class="cart-item-customize-name">{{option.name}}</span>
										<span ng-click="option.checked = !option.checked; order.cart.customizeItem(option, item);" class="cart-item-customize-price">{{option.priceFormated}}</span>
										<div class="divider"></div>
									</div>

									<!-- Customizable - select -->
									<div ng-switch-when="select">
										<label class="cart-item-customize-select-name">{{option.name}}</label>
										<select ng-change="order.cart.customizeItem(option, item)" ng-model="option.selected" ng-options="opt.id_option as opt.name for opt in option.options" class="cart-customize-select"></select>
									</div>

								</div>
							</div>

						</div>
					</div>

				</div>
			</div>


			<div class="default-order-check" ng-show="order.info.totalItems && restaurant._open">
				<input custom-checkbox type="checkbox" ng-model="order.form.make_default">
				<a ng-click="order.form.make_default = !order.form.make_default;">Save this order for next time</a>
				<div class="divider"></div>
			</div>

		</div>
		
		<!-- menu -->
		<div class="restaurant-items">
			
			<div ng-show="fullmenu">
				<div ng-repeat="category in restaurant.categories()">
					<div class="restaurant-category">{{category.name}}{{category.locName()}}</div>
					<ul class="resturant-dishes resturant-dish-container" date-id_category="{{category.id_category}}">
						<li ng-repeat="dish in category.dishes()" ng-click="order.cart.add(dish.id_dish)" class="dish-item">
							<span class="dish-item-name"><i class="fa fa-star" ng-show="dish.top"></i> {{dish.name}}</span><span class="dish-item-price">(${{dish.price}}<span ng-show="dish.changeable_price">+</span>)</span><br />
							<span class="dish-item-description">{{dish.description}}</span>
						</li>
					</ul>
				</div>

				<button class="button lightorange restaurant-items-toggle" ng-click="fullmenu=0">less food</button>
			</div>
			
			<div ng-show="!fullmenu">
				<div class="restaurant-title">The Menu</div>

				<div ng-repeat="category in restaurant.categories()">
					<ul class="resturant-dishes resturant-dish-container" date-id_category="{{category.id_category}}">
						<li ng-repeat="dish in category.dishes() | filter: {top: 1}" ng-click="order.cart.add(dish.id_dish)" class="dish-item">
							<span class="dish-item-name">{{dish.name}}</span><span class="dish-item-price">(${{dish.price}}<span ng-show="dish.changeable_price">+</span>)</span><br />
							<span class="dish-item-description">{{dish.description}}</span>
						</li>
					</ul>
				</div>
				
				<button class="button lightorange restaurant-items-toggle" ng-click="fullmenu=1">more food</button>
			</div>
			
		</div>
		<div class="divider"></div>
	</div>

	<div class="divider dots restaurant-payment-spacer" ng-show="order.loaded && order.cart.hasItems() && order.showForm"></div>



	<!-- payment and user info -->
	<form class="payment-form content-padding" ng-show="order.loaded && order.cart.hasItems() && order.showForm">
	
		<div ng-show="restaurant._open && order.showForm && order.cart.hasItems()">
			
			<!-- user info -->
			<div class="delivery-info-container">
				<div ng-show="(restaurant.delivery == '1' && restaurant.takeout == '1')">

					<div class="input-item toggle-wrapper clearfix">
						<button ng-click="order.toogleDelivery( 'delivery' )" ng-class="{'toggle-active': order.form.delivery_type=='delivery' }" class="payment-form-toggle">delivery</button>
						<button ng-click="order.toogleDelivery( 'takeout' )" ng-class="{'toggle-active': order.form.delivery_type=='takeout' }" class="payment-form-toggle">takeout</button>
					</div>

				</div>

				<div ng-show="(restaurant.delivery == '1' && restaurant.takeout != '1')">
					<label class="pay-title-label">Delivery Info</label>
				</div>

				<div ng-show="(restaurant.delivery != '1' && restaurant.takeout == '1')">
					<label class="pay-title-label">Takeout Info </label>
					<span class="take-out-only">Take out only!</span>
				</div>

				<div class="personal-info field-container">
					<div class="payment-field-group">
						<i class="fa fa-user payment-form-icon"></i>
						<input type="text" name="pay-name" tabindex="2" ng-model="order.form.name" class="payment-form-input" placeholder="name">
					</div>

					<div class="payment-field-group">
						<i class="fa fa-phone payment-form-icon"></i>
						<input type="tel" name="pay-phone" tabindex="3" ng-format-phone ng-model="order.form.phone" class="payment-form-input" placeholder="phone number">
					</div>

					<div class="payment-field-group">
						<i ng-show="order.form.delivery_type=='delivery'" class="fa fa-map-marker payment-form-icon"></i>
						<textarea ng-autosize ng-show="order.form.delivery_type=='delivery'" class="payment-form-input" ng-model="order.form.address" name="pay-address" id="pay-address" tabindex="5" placeholder="address"></textarea>
					</div>

					<div class="payment-field-group">

						<i class="fa fa-bullhorn payment-form-icon"></i>
						<textarea ng-autosize name="notes" ng-blur="checkGiftCard()" ng-model="order.form.notes" tabindex="6" class="payment-form-input" placeholder="notes"></textarea>

						<!-- Gift card messages -->
						<div class="giftcard-info">

							<div class="warning" ng-show="giftcard.removed">
								You just removed a gift card. If you still want to use that gift card, you must put it back in the notes field.
							</div>

							<div ng-show="restaurant.giftcard == 0 && giftcard.hasGiftCards">
								This restaurant does not accept gift card.
							</div>

							<div ng-show="giftcard.hasValue && order.form.pay_type == 'cash' ">
								Pay with a card, NOT CASH, to use your ${{giftcard.value}} gift card!</span>
							</div>

							<div ng-show="restaurant.giftcard == 1 && order.form.pay_type == 'card' ">
								<!-- Gift card success -->
								<div ng-repeat="success in giftcard.giftcards.success">
									<div ng-show="!success.error">
										Congrats! This gift card ({{success.giftcard}}) gives you ${{success.value}}.	
									</div>
									<div ng-show="success.error == 'other restaurant'">
										The gift card ({{success.giftcard}}) you are trying to use belongs to another restaurant.
									</div>
								</div>
								<!-- Gift card errors -->
								<div ng-repeat="error in giftcard.giftcards.error">
									<div ng-switch on="error.error">
										<div ng-switch-when="gift card already used">
										The gift card ({{error.giftcard}}) you are trying to use was already redeemed.
										</div>
									</div>
								</div>
							</div>
							<spa ng-show="giftcard.justOneGiftCardError">
								You can only use one gift card at a time!
							</span>
						</div>
					</div>
	
				</div>
			</div>
		
			<div class="divider"></div>
			
			<!-- payment info -->
			<div class="payment-info-container">
		
				<div class="payment-info field-container">
		
					<label class="pay-title-label">Payment Method</label>
					<div class="input-item toggle-wrapper">
						<button ng-click="order.tooglePayment( 'card' )" ng-show="(restaurant.credit == '1')" ng-class="{'toggle-active': order.form.pay_type=='card' }" class="toggle-item">card</button> 
						<span ng-show="(restaurant.credit == '1' && restaurant.cash == '1')" class="toggle-spacer">or</span> 
						<button ng-click="order.tooglePayment( 'cash' )" ng-show="(restaurant.cash == '1')"  ng-class="{'toggle-active': order.form.pay_type=='cash' }" class="toggle-item">cash</button>
					</div>
	
					<div class="divider"></div>
		
						<div ng-show="order.form.pay_type=='card'" class="payment-card-info"><p>Your credit card information is <br />super secure and encrypted.<br /><br /></p>
							<div class="card-icons">
								<div class="payment-card card-visa payment-card-grey" pre-load-image="/assets/images/payment/card-visa-grey@2x.png" title="visa"></div>
								<div class="payment-card card-master-card" pre-load-image="/assets/images/payment/card-master-grey@2x.png" title="master card"></div>
								<div class="payment-card card-amex" pre-load-image="/assets/images/payment/card-amex-grey@2x.png" title="american express"></div>
								<div class="payment-card card-discover" pre-load-image="/assets/images/payment/card-discover-grey@2x.png" title="discover card"></div>
							</div>
						</div>

						<label ng-show="order.form.pay_type=='card'">Credit card #</label>

						<div ng-show="order.form.pay_type=='card'" class="payment-form-input"><input type="tel" name="pay-card-number" tabindex="6" ng-change="order.creditCardChanged();" ng-model="order.form.cardNumber"></div><div class="divider"></div>
		
						<label ng-show="order.form.pay_type=='card'">Expiration</label>
						<div ng-show="order.form.pay_type=='card'" class="payment-form-input">

							<select  ng-change="order.cardInfoChanged()" ng-model="order.form.cardMonth" ng-options="month.value as month.label for month in order._months()" tabindex="7">{{order.form.card.month}}</select> 

							<select  ng-change="order.cardInfoChanged()" ng-model="order.form.cardYear" ng-options="year.value as year.label for year in order._years()" tabindex="8"></select> 

							<div class="divider"></div>
						</div>
		
						<div class="divider"></div>

						<label ng-show="order.form.pay_type=='card'">Tip</label>
						<div ng-show="order.form.pay_type=='card'" class="payment-form-input">
	
						<input type="hidden" name="pay-autotip-value" ng-model="order.form.autotip" value="0">
						<select ng-model="order.form.tip" ng-options="tip.value as tip.label for tip in order._tips()" ng-change="order.tipChanged();" class="tip" tabindex="9"></select> 
						<div class="divider"></div>
					</div>
				</div>
		
			</div>
			
			<div class="divider"></div>
			<div class="payment-total" ng-show="order.subtotal()">
				You're paying:&nbsp;
				<span ng-show="order.form.pay_type=='cash'">approximately</span>
				&nbsp;{{order.info.breakdownDescription}}&nbsp;
				<span ng-show="order.info.extraCharges">( + {{order.info.extraCharges}} )</span>
				<strong class="cart-gift" ng-show="credit.hasValue && order.form.pay_type == 'card' ">
					<span>
						&nbsp;(-{{AB.dollar}}
						<span ng-show="order.total() <= credit.number">{{order.total()}}</span>
						<span ng-show="order.total() > credit.number">{{credit.value}}</span>
						&nbsp;credit 

						<span ng-show="order.info.creditLeft != ''" class="gift-left">
							- You'll still have {{AB.dollar}}{{order.info.creditLeft}} gift card left
						</span> )
					</span>
				</strong>&nbsp;
				for a total of {{order.info.totalText}}
				&nbsp;
				<div ng-show="credit.hasValue && order.form.pay_type == 'cash' ">
					<div class="giftcard-payment-message">Pay with a card, NOT CASH, to use your {{AB.dollar}}{{credit.value}} gift card</div>
				</div>
				&nbsp;
				<span ng-show="order.form.pay_type=='card'">by card</span>
			</div>
		</div>
	
	</form>

	<!-- stored user info -->
	<div class="delivery-payment-info main-content-readable" ng-show="restaurant._open && !order.showForm && order.cart.hasItems()">

		<div>
			<label>Your phone number:&nbsp;</label>
			<i ng-show="user.phone">{{ user.phone | formatPhone }}</i>
			<i ng-show="!user.phone">no phone # provided</i>
		</div>

		<div ng-show="order.subtotal()">
			<label>You're paying:&nbsp;<span ng-show="order.form.pay_type=='cash'" class="unbold">approximately</span></label>
			&nbsp;{{order.info.breakdownDescription}}&nbsp;
			<span ng-show="order.info.extraCharges">( + {{order.info.extraCharges}} )</span>
			<strong class="cart-gift" ng-show="credit.hasValue && order.form.pay_type == 'card' ">
					<span>
						&nbsp;(-{{AB.dollar}}
						<span ng-show="order.total() <= credit.number">{{order.total()}}</span>
						<span ng-show="order.total() > credit.number">{{credit.value}}</span>
						&nbsp;credit 
						<span ng-show="order.info.creditLeft != ''" class="gift-left">
							- You'll still have {{AB.dollar}}{{order.info.creditLeft}} gift card left
						</span> )
					</span>
				</strong>&nbsp;
			for a total of {{order.info.totalText}}
			&nbsp;
				<div ng-show="credit.hasValue && order.form.pay_type == 'cash' ">
					<div class="giftcard-payment-message">Pay with a card, NOT CASH, to use your {{AB.dollar}}{{credit.value}} gift card</div>
				</div>
			&nbsp;
			<span ng-show="order.form.pay_type=='card'">by card</span>
		</div>

		<div ng-show="restaurant.delivery == '1' && order.form.delivery_type=='delivery'">
			<label>Your food will be delivered to:</label><br />
			<span ng-bind-html-unsafe="order.form.address | nl2br"></span>
			<i ng-hide="order.form.address">no address provided</i>
		</div>

		<div ng-show="restaurant.takeout == '1' && order.form.delivery_type=='takeout'">
			<label>Delivery Address:</label> <i>takeout</i>
		</div>

		<div>
			<span class="clickable" ng-click="order.showForm=true">Change delivery or payment details</span>
		</div>

		<div class="divider"></div>

	</div>

</div>
<div class="divider bottom-spacer"></div>

<div class="address-not-found-warning order-warning modal zoom-anim-dialog small-container mfp-hide">
	<h1>Confirm your address?</h1>
	<p><strong>We could not find the address:<br/>{{order.form.address}}</strong></p>
	<ul>
		<li>
			<div ng-click="addressPlaceAnyway();">Continue</div>
		</li>
		<li>
			<div ng-click="addressLetMeChangeIt();">Add a City or Zip Code</div>
		</li>
	</ul>
</div>

