<div class="top-pad"></div>

<div ng-show="!restaurants">
	<div class="content-padding">
		<h1>Finding you the best food...</h1>
	</div>
</div>

<div ng-show="restaurants">

	<div class="restaurants-bubble-wrap">
		<div class="bubble-tail-green">
			<div class="text">
				Push a button.<br />
				&nbsp;&nbsp;&nbsp;&nbsp;Get food.
			</div>
		</div>
		<div class="restaurants-orange"></div>
		<div class="divider"></div>
		<div class="restaurants-tagline">
			<h1>Order the top local delivery food.</h1>
			<h2>Choose one of these awesome restaurants</h2>
		</div>
		<div class="divider"></div>
	</div>

	<div class="restaurants-items">
		<div ng-click="display($event)" ng-class="{'meal-item-closed': restaurant._open==false}" class="restaurants-item" data-id_restaurant="{{restaurant.id_restaurant}}" data-permalink="{{restaurant.permalink}}" ng-repeat="restaurant in restaurants | limitTo:restaurantsToShow">

			<div class="restaurants-closed" ng-show="restaurant._tag == 'closed'">
				<h2 class="restaurants-name">{{restaurant.name}}</h2>
				<div class="restaurants-opensin">Opens in 4 hours</div>			
			</div>

			<div class="restaurants-open" ng-hide="restaurant._tag == 'closed'">
				<div class="restaurants-item-content ladda-button" style="background: url({{restaurant.img64}});" ng-spinner data-style="zoom-out" data-spinner-color="#333333">
					<div class="ladda-label">
						<div class="restaurants-pic" style="background: url({{restaurant.img64}});"></div>
						<h2 class="restaurants-name">{{restaurant.name}}</h2>
						<h3 class="restaurants-description">{{restaurant._short_description}}</h3>


						<div ng-switch on="restaurant._tag">
							<div class="meal-item-tag" ng-switch-when="takeout">Take out only</div>
							<div class="meal-item-tag about-to-close" ng-switch-when="closing">Hurry, closes in {{restaurant._closesIn}} min!</div>
						</div>
						
						<div class="meal-item-tag-bottom" ng-show="restaurant._tag == 'closing' || restaurant._tag == 'takeout'"></div>

					</div>
					<span class="ladda-spinner"></span>
				</div>
			</div>
		</div>

		<button class="button green" ng-show="restaurantsToShow < restaurants.length" ng-click="showMoreRestaurants()">
			More awesome Restaurants
		</button>

	</div>
</div>