<div class="delivery-payment-info restaurant-side-bar restaurant-side-user-info" ng-if="order.loaded && ( restaurant._open || restaurant.force_pre_order ) && !order.showForm && order.cart.hasItems()">

	<div class="divider dots"></div>

	<div class="content-padding">

		<div class="order-icon">
			<i class="fa fa-phone payment-form-icon form-icon form-field"></i>
		</div>
		<div class="order-info order-info-oneline">
			<p>
				<span ng-if="user.phone">{{ user.phone | formatPhone }}</span>
				<span ng-if="!user.phone">no phone # provided</span>
			</p>
		</div>
		<div class="divider"></div>
		<div class="order-icon">
			<i class="fa fa-birthday-cake gift-card-balance payment-form-icon form-icon form-field" ng-if="order.form.pay_type=='card' && order.total() <= credit.number"></i>
			<i class="fa fa-credit-card payment-form-icon form-icon form-field" ng-if="order.form.pay_type=='card' && order.total() > credit.number"></i>
			<i class="fa fa-money payment-form-icon form-icon form-field" ng-if="order.form.pay_type=='cash'"></i>
		</div>
		<div class="order-info order-info-oneline">

			<p>
				<span ng-if="order.form.pay_type=='card' && order.total() <= credit.number">Gift card balance</span>
				<span ng-if="order.form.pay_type=='card' && credit.number && order.total() > credit.number">Card ending in {{user.card_ending}} &amp; - {{credit.value}} credit</span>
				<span ng-if="order.form.pay_type=='card' && !credit.number">Card ending in {{user.card_ending}}</span>
				<span ng-if="order.form.pay_type=='cash'">Pay and tip with <b>cash</b>
					<span ng-if="config.driver_change_amount">
						<br><i>Drivers only carry ${{config.driver_change_amount}} in change</i>
					</span>
				</span>
			</p>
		</div>
		<div class="divider"></div>


		<div class="order-icon">
			<i class="fa fa-map-marker payment-form-icon form-icon form-field"></i>
		</div>
		<div class="order-info" ng-if="restaurant.delivery == '1' && order.form.delivery_type=='delivery'">
			<p>
				Delivered to:<br />
			</p>
			<p class="restaurant-info-address">
				<span ng-bind-html-unsafe="order.form.address | nl2br"></span>
				<i ng-hide="order.form.address">no address provided</i>
			</p>
		</div>
		<div class="order-info" ng-if="restaurant.takeout == '1' && order.form.delivery_type=='takeout'">
			<p class="restaurant-info-address">
				Pick up from:<br />
				<span ng-bind-html-unsafe="restaurant.address | nl2br"></span>
			</p>
		</div>


		<div class="divider"></div>

				<div class="payment-form-group form-group">

					<i class="fa fa-bullhorn payment-form-icon form-icon form-field"></i>
					<textarea ng-focus="softKeyboard($event);" ng-blur="checkGiftCard();softKeyboardExit()" ng-autosize name="notes" ng-model="order.form.notes" tabindex="6" class="payment-form-input form-input form-field notes-text-area" placeholder="notes / code"></textarea>

					<ng-include src="'assets/view/restaurant-gift-card.html'"></ng-include>
		</div>

		<div class="divider"></div>

		<div class="divider spacer-one-two"></div>

		<p>We’ve saved your payment and delivery info for one click reordering.</p>

		<div class="divider spacer-one-two"></div>

		<button class="button green button-empty" ng-click="order.showForm=true">Change info</button>
	</div>
</div>