<div class="top-pad"></div>

<div class="restaurants-top-wrap content-padding">
	<div class="restaurants-top-tag hide-mobile" ng-if="slogan">
		<h4 ng-bind-html-unsafe="slogan" class="restaurants-top-title"></h4>
		<p ng-bind-html-unsafe="tagline"></p>
		<p><br>{{entered}} - <a href="/location">Change</a></p>
	</div>

	<div class="restaurants-bubble-wrap noselect">
		<div ng-if="!image">
			<div ng-if="!allClosed">
				<div class="bubble-tail bubble-tail-green bubble-animated">
					<div class="text" ng-switch="pushMessage">
						<span ng-switch-when="1">We choose<br>the best food...</span>
						<span ng-switch-when="2">From the best restaurants...</span>
						<span ng-switch-when="3">So you don't<br> have to!</span>
						<span ng-switch-when="4">Screw huge<br> menus!</span>
						<span class="single-line" ng-switch-when="5">Screw gross food!!</span>
						<span ng-switch-when="6">We only have awesome stuff!</span>
						<span class="single-line" ng-switch-when="7">Got a suggestion?</span>
						<span ng-switch-when="8">Want to work<br> for us?</span>
						<span class="single-line" ng-switch-when="9">Send us a text!</span>
						<span ng-switch-when="10">We are always looking for...</span>
						<span ng-switch-when="11" class="single-line">Awesome people...</span>
						<span class="single-line" ng-switch-when="12">And great food!</span>
						<span class="single-line" ng-switch-when="13"><i class="fa fa-heart"></i> <i class="fa fa-heart"></i> <i class="fa fa-heart"></i></span>
						<span ng-switch-default class="restaurants-push-tagline">
							<span class="hide-desktop"><b>Push a button</b><br>Get food delivered</span>
							<span class="hide-mobile">Choose a <br><b>restaurant</b></span>
						</span>

					</div>
					<div class="bubble-tail-spacer"></div>
				</div>
				<div class="restaurants-orange" ng-instant="pushMessage = (pushMessage > 12 ? 0 : (pushMessage + 1))" instant-pass-thru></div>
			</div>

			<div ng-if="allClosed">
				<div class="bubble-tail bubble-tail-green bubble-animated noselect">
					<div class="text" ng-switch="pushMessage">
						<span ng-switch-when="1">We will be back soon.</span>
						<span ng-switch-when="2" class="small">Know of some awesome restaurants in your area?</span>
						<span ng-switch-when="3">Want to become a delivery driver?</span>
						<span class="single-line" ng-switch-when="4">Send us a txt...</span>
						<span class="single-line" ng-switch-when="5">And lets do stuff!</span>
						<span class="single-line" ng-switch-when="6"><i class="fa fa-cutlery"></i> <i class="fa fa-cutlery"></i> <i class="fa fa-cutlery"></i></span>
						<span ng-switch-default class="restaurants-push-tagline">
							<span ng-if="community_closed" class="small">
								{{community_closed}}
							</span>
							<span ng-if="!community_closed"><b>Wahhhhhh!!!</b><br>No delivery is available</span>
						</span>
					</div>
					<div class="bubble-tail-spacer"></div>
				</div>
				<div class="restaurants-orange restaurants-orange-sad" ng-instant="pushMessage = (pushMessage > 6 ? 0 : (pushMessage + 1))" instant-pass-thru></div>
			</div>

			<div class="divider"></div>
			<br>

			<? /*
			<div class="restaurants-tagline">
				<h2><i class="fa fa-hand-o-right"></i>&nbsp;&nbsp;Choose a restaurant</h2>
			</div>
			*/?>
		</div>

		<div ng-if="image" class="community-image"></div>


		<div class="divider"></div>
	</div>
	<div class="divider"></div>

</div>

<div ng-if="restaurants">
	<div class="restaurants-items">

	<span ng-repeat="restaurant in restaurants | limitTo:restaurantsToShow" class="restaurants-repeated">

			<? /*
			<div class="restaurant-list-divider" ng-if="restaurant._divider"></div>
			*/ ?>

			<div ng-click="display($event)" ng-class="{'meal-item-closed': restaurant._open==false}" class="restaurants-item" data-id_restaurant="{{restaurant.id_restaurant}}" data-permalink="{{restaurant.permalink}}">

				<div class="restaurants-closed" ng-if="showSmallClosures && restaurant._tag == 'closed'">
					<h2 class="restaurants-name">{{restaurant.name}}</h2>
					<div class="restaurants-opensin" ng-if="restaurant._openIn > 0" >Available {{restaurant._opensIn_formatted}}</div>
				</div>

				<div class="restaurants-closed" ng-if="showSmallClosures && restaurant._tag == 'force_close'">
					<h2 class="restaurants-name">{{restaurant.name}}</h2>
					<div class="restaurants-opensin">Temporarily closed {{restaurant._closedDueTo}}</div>
				</div>

				<div class="restaurants-open" ng-if="!showSmallClosures || (showSmallClosures && restaurant._tag != 'closed' && restaurant._tag != 'force_close')">

					<div ng-spinner="loadingRestaurant[restaurant.id_restaurant]" class="restaurants-item-content" data-spinner-color="#333333" data-spinner-scale=".5">
						<div class="ladda-label">
							<div class="restaurants-pic" style="background-image: url({{restaurant.images.normal || restaurant.img}});"></div>
							<h2 class="restaurants-name">{{restaurant.name}}</h2>
							<h3 class="restaurants-description">{{restaurant._short_description}}</h3>

							<div ng-switch on="restaurant._tag">
								<div class="meal-item-tag about-to-open" ng-switch-when="closed">Available {{restaurant._opensIn_formatted}}</div>
								<div class="meal-item-tag about-to-open" ng-switch-when="force_close"><span ng-if="restaurant._opensIn_formatted">Available {{restaurant._opensIn_formatted}}</span><span ng-if="!restaurant._opensIn_formatted">Temporarily closed {{restaurant._closedDueTo}}</span></div>
								<div class="meal-item-tag" ng-switch-when="takeout">Take out only</div>
								<div class="meal-item-tag" ng-switch-when="next_open">{{restaurant.next_open_time_message.message}}</div>
								<div class="meal-item-tag about-to-close" ng-switch-when="closing">Hurry, closes in {{restaurant._closesIn}} min!</div>
								<div ng-switch-when="opening">
									<div ng-if="restaurant._opensIn_formatted" class="meal-item-tag about-to-open"><span >Available {{restaurant._opensIn_formatted}}</span></div>
								</div>
							</div>

							<div class="meal-item-tag-bottom" ng-if="restaurant._tag != ''"></div>

						</div>
					</div>
				</div>
			</div>

		</span>
		<div class="divider"></div>

		<button class="button green restaurants-more" ng-if="restaurantsToShow < restaurants.length" ng-click="showMoreRestaurants()">
			More awesome Restaurants
		</button>

	</div>
</div>