<div class="restaurant-box" ng-show="!open && order.loaded">
	<div class="restaurant-box-inner">
		<span class="restaurant-box-icon restaurant-box-align-top">
			<i class="fa fa-clock-o"></i>
		</span>
		<span class="restaurant-box-content">
			<div class="restaurant-box-title">Opens in {{restaurant._opensIn_formatted}}</div>
			<div class="restaurant-box-text">
				Hours of operation (<span ng-bind="restaurant._tzabbr"></span>):<br>
				<span ng-bind-html-unsafe="restaurant.closedMessage() | nl2br"></span>
			</div>
		</span>
	</div>
</div>