<?php 
$shifts = $this->shifts;
$id_admin = c::admin()->id_admin;
?>
<div class="content">
	<div class="wrap">
		<?php 
		if( $shifts->count() > 0 ){
			foreach( $shifts as $shift ) { 
				$drivers = $shift->getDrivers();
				$mine = false;
				foreach ( $drivers as $driver ) { 
					if( $driver->id_admin == $id_admin ){
						$mine = true;
					}
				}
				?>
				<div class="shifts-list-item <?php if( $mine ){ echo 'mine'; } else { echo 'false'; } ?>">
					<div class="shifts-list-item-community">
						<?php echo $shift->community()->name; ?>
					</div>
					<div class="shifts-list-item-date">
						<div class="shifts-list-item-day">
							<?php echo $shift->dateStart()->format( 'D, M jS' ); ?>
						</div>
						<div class="shifts-list-item-hour">
							<?php echo $shift->startEndToString(); ?> (<?php echo $shift->timezoneAbbr(); ?>)
						</div>
					</div>
					<ul class="drivers">
					<?php
					if ( $drivers->count() ) {
						foreach ( $drivers as $driver ) { 
							?>
							<li <?php if( $driver->id_admin == $id_admin ){ echo 'class="you"'; } ?>>
								<?php echo $driver->name; ?> - <?php echo $driver->phone(); ?>
							</li>
							<?php
						}
					} else {
						?>
							<li class="no-drivers">No drivers</li>
						<?php
					}
					?>
					</ul>
					<div class="divider"></div>
				</div>
			<?php 
			} 
		} else { ?>
			<div class="no-orders">
				No shifts
			</div>
		<?php } ?>
	</div>
</div>