<div class="top-pad"></div>

<div class="content-padding">
	<h1 class="title"><i class="fa fa-credit-card"></i>Pex Card</h1>
	<div class="box-content2 box-content-table">
		<table>
			<tr><td><a href="/pexcard/card">Assign Pex Card to Driver</a></td></tr>
			<tr><td><a href="/pexcard/log">Transactions log</a></td></tr>
			<tr><td><a href="/pexcard/report">Pex Card Report <i class="fa fa-star"></i></a></td></tr>
			<tr><td><a href="/pexcard/report/old">Pex Card Report (old)</a></td></tr>
			<tr><td><a href="/pexcard/card/log">Card Activations Log</a></td></tr>
			<tr><td><a href="/pexcard/config">Config</a></td></tr>
		</table>
	</div>
</div>
