<div class="top-pad"></div>

<div class="content-padding">
	<h1 class="title"><i class="fa fa-credit-card"></i>Pex Card: Card Activations Log</h1>
	<div class="box-content2 box-content-table">
		<table>
			<tr>
				<td colspan="2"><i class="fa fa-search"></i>&nbsp;&nbsp;<input type="text" ng-model="query.search" id="search" tabindex="1"></td>
			</tr>
			<tr>
				<th>Type</th>
				<td>
					<select ng-model="query.type" name="searchType" tabindex="2">
						<option value="using_pex">Using pex</option>
						<option value="card_assign">Card Assignment</option>
					</select>
				</td>
		</table>
	</div>

	<div class="bar-loader bar-loader-search" ng-class="{'bar-loader-loading': loading}"></div>

	<ng-include src="'/assets/view/listview-pexcard-card-log.html'"></ng-include>
	<ng-include src="'/assets/view/listview-paging.html'"></ng-include>
</div>