<div class="top-pad"></div>

<div class="content-padding">

	<h1 class="title"><i class="fa fa-credit-card"></i>Pex Card: Report</h1>

		<div class="divider"></div>

		<navigation-back></navigation-back>

		<form name="form" novalidate>

		<ul ng-class="{'submitted':submitted}" class="ul-inputs box-content2">

			<li class="li-input" ng-class="{'error':form.rangeStart.$invalid}">
				<div class="label">Date start:</div>
				<div class="input"><input type="date" name="rangeStart" ng-model="range.start" required placeholder=""></div>
				<div class="box-error">
					<small ng-show="form.rangeStart.$error.required">Required.</small>
					<small ng-show="form.rangeStart.$error.date">Enter a valid start date!</small>
				</div>
			</li>

			<li class="li-input" ng-class="{'error':form.rangeEnd.$invalid}">
				<div class="label">Date end:</div>
				<div class="input"><input type="date" name="rangeEnd" ng-model="range.end" required placeholder=""></div>
				<div class="box-error">
					<small ng-show="form.rangeEnd.$error.required">Required.</small>
					<small ng-show="form.rangeEnd.$error.date">Enter a valid end date!</small>
				</div>
			</li>

			<li class="li-input" ng-show="!isProcessing">
				<button class="button save" ng-click="report();">Report</button>
				<button class="button save" ng-click="import_data();">Import data and Report</button>
			</li>

			<li class="li-input" ng-show="isProcessing">
				<span><i class="fa fa-circle-o-notch fa-spin"></i> Processing</span>
			</li>

		</ul>

	</form>

	<div ng-if="result">

		<h2 class="title">
			<span>Report</span>
		</h2>

		<table class="tb-grid tb-zebra">
			<thead>
				<tr>
					<td>Driver Name</td>
					<td>Serial</td>
					<td>Last Four</td>
					<td>Email</td>
					<td>Orders</td>
					<td>Pex Card Spent</td>
					<td>Card Orders Spent</td>
					<td>Card and Cash Orders Spent</td>
					<td>Diff</td>
				</tr>
			</thead>
			<tbody ng-repeat="driver in result.drivers_expenses">
				<tr>
					<td>
						<span ng-if="driver.login"><a href="/staff/{{driver.login}}">{{driver.driver}}</a></span>
						<span ng-if="!driver.login">{{driver.driver}}</span>
					</td>
					<td>{{driver.card_serial}}</td>
					<td>{{driver.last_four}}</td>
					<td>
						<span ng-if="driver.login"><a href="mailto:{{driver.email}}">{{driver.email}}</a></span>
					</td>
					<td>{{driver.orders}}</td>
					<td positive-or-negative-color="{{driver.pexcard_amount}}">$ {{driver.pexcard_amount | formatPrice}}</td>
					<td positive-or-negative-color="{{driver.card_amount}}">$ {{driver.card_amount | formatPrice}}</td>
					<td positive-or-negative-color="{{driver.card_cash_amount}}">$ {{driver.card_cash_amount | formatPrice}}</td>
					<td positive-or-negative-color="{{driver.diff}}">$ {{driver.diff | formatPrice}}</td>
				</tr>
				<?php /*
				<tr class="tb-mini-grid">
					<th colspan="3"><strong>Date</strong></th>
					<th colspan="3"><strong>Description</strong></th>
					<th colspan="3"><strong>Amount</strong></th>
				</tr>
				<tr class="tb-mini-grid" ng-repeat="transaction in driver.transactions">
					<td colspan="3">{{transaction.date}}</td>
					<td colspan="3">{{transaction.description}}</td>
					<td colspan="3" positive-or-negative-color="{{transaction.amount}}">$ {{transaction.amount | formatPrice}}</td>
				</tr>
				*/ ?>
			</tbody>
		</table>

	</div>

</div>
