<?
	$this->title = 'Dashboard';
	$this->subtitle = 'Crunchbutton overview';
	$this->titleicon = 'dashboard';
?>



<!-- restaurants page -->
<div class="container-fluid padded">
	<div class="row-fluid">
		<div class="box">
			<div class="box-header"><span class="title"></span></div>
			<div class="box-content padded">

				<div style="width:480px;">
					For most everything, use <a href="http://cockpit.la">http://cockpit.la</a>
				</div>
				<div class="divider"></div>
				<!-- old -->

			</div>
		</div>
	</div>
</div>
<!-- // end restaurants page -->

<script type="text/javascript" src="/assets/js/admin_restaurants.js"></script>
