<?
	$this->title = 'Dashboard';
	$this->subtitle = 'Crunchbutton overview';
	$this->titleicon = 'dashboard';
?>


<!-- content -->
<div class="container-fluid padded">
	<div class="row-fluid">
		<div class="span3">
			<!--big normal buttons-->
			<div class="action-nav-normal">

				<div class="row-fluid">
					<div class="span6 action-nav-button">
						<a href="/restaurants/new" title="New Restaurant">
							<i class="icon-file-alt"></i>
							<span>New Restaurant</span>
						</a>
						<span class="triangle-button red"><i class="icon-plus"></i></span>
					</div>
			
					<div class="span6 action-nav-button">
						<a href="/support" title="Support">
							<i class="icon-comments-alt"></i>
							<span>Support</span>
						</a>
						<span class="label label-black"><?=$this->data['all']['tickets']?></span>
					</div>
				</div>

			
				<div class="row-fluid">
					<div class="span6 action-nav-button">
						<a href="https://github.com/crunchbutton/crunchbutton" title="Github" target="_blank">
							<i class="icon-github"></i>
							<span>Github</span>
						</a>
					</div>
			
					<div class="span6 action-nav-button">
						<a href="https://www.facebook.com/crunchbutton" title="Facebook" target="_blank">
							<i class="icon-facebook-sign"></i>
							<span>Facebook</span>
						</a>
					</div>
				</div>
			
			</div>
		</div>

		
		<div class="span9">
			
			<div class="box">
				<div class="box-header">
					<div class="title">Recent Orders</div>
					<? /*
					<ul class="box-toolbar">
						<li class="toolbar-link">
							<a href="#" data-toggle="dropdown"><i class="icon-cog"></i></a>
							<ul class="dropdown-menu">
								<li><a href="#"><i class="icon-plus-sign"></i> Add</a></li>
								<li><a href="#"><i class="icon-remove-sign"></i> Remove</a></li>
								<li><a href="#"><i class="icon-pencil"></i> Edit</a></li>
							</ul>
						</li>
					</ul>
					*/ ?>
				</div>
			
				<div class="box-content padded">
					<div class="row-fluid">
						<div class="span4 separate-sections" style="margin-top: 5px;">
			
							<div class="row-fluid">
								<div class="span12">
									<div class="dashboard-stats">
										<ul class="inline">
											<li class="glyph"><i class="icon-bolt icon-2x"></i></li>
											<li class="count"><?=$this->data['all']['orders']?></li>
										</ul>
										
										<div class="stats-label">Total Orders</div>
									</div>
								</div>
							</div>
			
							<div class="row-fluid" style="margin-top:30px;">
								<div class="span6">
									<div class="dashboard-stats small">
										<ul class="inline">
											<li class="glyph"><i class="icon-user"></i></li>
											<li class="count"><?=$this->data['week']['orders']?></li>
										</ul>
										
										<div class="stats-label">This Week</div>
									</div>
								</div>
			
								<div class="span6">
									<div class="dashboard-stats small">
										<ul class="inline">
											<li class="glyph"><i class="icon-eye-open"></i></li>
											<li class="count"><?=$this->data['day']['orders']?></li>
										</ul>
										<? /* <div class="progress progress-blue"><div class="bar tip" title="80%" data-percent="80"></div></div> */ ?>
										<div class="stats-label">Today</div>
									</div>
								</div>
							</div>
			
						</div>
						<div class="span8">
							<div class="sine-chart" id="xchart-sine"></div>
						</div>
					</div>
				</div>
				
			</div>
		</div>
	</div>





	<div class="box">
		<div class="box-header"><span class="title">Dash shit</span></div>
		<div class="box-content padded">


		<? foreach ($this->graphs as $id => $graph ){ 

			$this->display('charts/area', ['set' => [
				'chartId' => $id,
				'data' => $graph['data'],
				'title' => $graph['title'],
				'unit' => $graph['unit']
			]]); 
		}
		?>
	



		</div>
	</div>
</div>
