<?
	$this->title = 'Dashboard';
	$this->titleicon = 'dashboard';
	$this->titleLink = '/';
	
	$this->title2 = 'Marketing events';
	$this->title2icon = 'bullhorn';

	$data = $this->data;

?>
<div class="container-fluid padded">
	<div class="row-fluid">
		<div class="span12">
			<div class="box">
				<div class="box-header">
					<span class="title">Marketing events</span>
				</div>
				<div class="box-content padded">
				
				<table cellpadding="0" cellspacing="0" border="0" class="table table-normal">
					<tr>
						<th rowspan="2" style="text-align:center !important;vertical-align:middle !important;">Group</th>
						<th rowspan="2" style="text-align:center !important;vertical-align:middle !important;">Date</th>
						<th rowspan="2" style="text-align:center !important;vertical-align:middle !important;">Community</th>
						<th rowspan="2" style="text-align:center !important;vertical-align:middle !important;">Promotion Type</th>
						<th colspan="3" style="text-align:center !important;vertical-align:middle !important;border-right:1px solid #eaebef;border-left:1px solid #eaebef;">Gift cards</th>
						<th colspan="4" style="text-align:center !important;vertical-align:middle !important;border-right:1px solid #eaebef;">Users</th>
						<th colspan="2" style="text-align:center !important;vertical-align:middle !important;border-right:1px solid #eaebef;">Active users</th>
						<th rowspan="2" style="text-align:center !important;vertical-align:middle !important;">Hours</th>
						<th rowspan="2" style="text-align:center !important;vertical-align:middle !important;border-right:1px solid #eaebef;border-left:1px solid #eaebef;">Hours / New <br/>users</th>
						<th rowspan="2" style="text-align:center !important;vertical-align:middle !important;">Hours / Gift <br/>card redeemed</th>
						<th rowspan="2" style="text-align:center !important;vertical-align:middle !important;border-left:1px solid #eaebef;">CAC</th>
					</tr>
					<tr>
						<th>Total</th>
						<th>Redeemed</th>
						<th style="border-right:1px solid #eaebef;">Redeemed %</th>
						<th>New</th>
						<th>Returned</th>
						<th>New / Gift card</th>
						<th style="border-right:1px solid #eaebef;">New / Gift card redeemed</th>
						<th>15 days</th>
						<th style="border-right:1px solid #eaebef;">45 days</th>
					</tr>
				<?php 
				foreach ( $data as $group ) {
?>
					<tr>
						<td><?php echo $group[ 'name' ]; ?></td>
						<td><?php echo $group[ 'date' ]; ?></td>
						<td><?php echo $group[ 'community' ]; ?></td>
						<td><?php echo $group[ 'promotion_type' ]; ?></td>
						<td><?php echo $group[ 'report' ][ 'giftcards' ][ 'redeemed' ]; ?></td>
						<td><?php echo number_format( $group[ 'report' ][ 'giftcards' ][ 'redeemed_percent' ], 2 ); ?>%</td>
						<td><?php echo $group[ 'report' ][ 'users' ][ 'unique' ]; ?></td>
						<td><?php echo $group[ 'report' ][ 'users' ][ 'new' ]; ?></td>
						<td><?php echo $group[ 'report' ][ 'users' ][ 'returned' ]; ?></td>
						<td><?php echo number_format( $group[ 'report' ][ 'users' ][ 'new_per_giftcard' ], 2 ); ?></td>
						<td><?php echo number_format( $group[ 'report' ][ 'users' ][ 'new_per_giftcard_redeemed' ], 2 ); ?></td>
						<td><?php echo $group[ 'report' ][ 'users' ][ 'active' ][ '15' ]; ?></td>
						<td><?php echo $group[ 'report' ][ 'users' ][ 'active' ][ '45' ]; ?></td>
						<td><?php echo $group[ 'man_hours' ]; ?></td>
						<td>
							<?php 
							if( $group[ 'man_hours' ] > 0 && $group[ 'report' ][ 'users' ][ 'new' ] > 0 ) { 
								echo number_format( ( $group[ 'man_hours' ] / $group[ 'report' ][ 'users' ][ 'new' ] ) , 2);
							} else {
								echo '0';
							}
							?>
						</td>
						<td>
							<?php 
							if( $group[ 'man_hours' ] > 0 && $group[ 'report' ][ 'giftcards' ][ 'redeemed' ] > 0 ) { 
								echo number_format( ( $group[ 'man_hours' ] / $group[ 'report' ][ 'giftcards' ][ 'redeemed' ] ) , 2);
							} else {
								echo '0';
							}
							?>
						</td>
						<td>
							<?php 
							if( $group[ 'man_hours' ] > 0 && $group[ 'report' ][ 'users' ][ 'new' ] > 0 ) { 
								echo number_format( ( $group[ 'man_hours' ] / $group[ 'report' ][ 'users' ][ 'new' ] ) * 15 , 2);
							} else {
								echo '0';
							}
							?>
						</td>
					</tr>
<?php
				}
				?>
					
				</table>
				</div>
			</div>
		</div>
	</div>
</div>