<?
$this->restaurant->exports();

	$this->title = 'TESTS';
	$this->titleicon = 'food';
?>

<!-- restaurants page -->
<div class="container-fluid padded">
	<div class="row-fluid">
		<div class="box">
			<div class="box-header"><span class="title">Select a Restaurant</span></div>
			<div class="box-content ">
				<form class="fill-up">
					<ul class="box-list">
						<li>
							<span>Restaurant</span>
							<span class="pull-right">
								<select class="test-restaurant chosen-select" style="width:480px;">
									<option value="" selected>Choose...</option>
									<? foreach (Restaurant::q('select * from restaurant order by name') as $restaurant) : ?>
										<option value="<?=$restaurant->id_restaurant?>" <?php if( $restaurant->id_restaurant == $this->restaurant->id_restaurant ){ echo 'selected="selected"'; } ?>><?=$restaurant->name?> (permalink: <?=$restaurant->permalink?>)</option>
									<? endforeach ; ?>
								</select>
							</span>
						</li>
						<li>
							<span>Time</span>
							<span class="pull-right">
								<input type="text" class="test-time span12" value="<?= $this->time->format('M jS Y g:i:s A')?>">
								<?php echo$this->restaurant->timezone; ?>
							</span>
						</li>
						<li>
							<span class="pull-right">
								<a class="btn btn-blue test-calculate">Calculate</a> 
							</span>
						</li>
					</ul>
				</form>
			</div>
		</div>
		
		<div class="box">
			<div class="box-content padded">
				<?=$this->restaurant->name?> is <b title="<?php echo $this->time->format(' M jS Y g:i:s A - D '); ?>"><?=$this->open ? 'OPEN' : 'CLOSED'?></b> <?=$this->now ? 'now (' . $this->time->format(' M jS Y g:i:s A ') . ')' : 'at '.$this->time->format(' M jS Y g:i:s A ');?>
				<br/>
				<br/>
			</div>
		</div>
	</div>
</div>