<?
	$this->title = 'TESTS';
	$this->titleicon = 'food';
?>

<!-- restaurants page -->
<div class="container-fluid padded">
	<div class="row-fluid">
		<div class="box">
			<div class="box-header"><span class="title">Select a Restaurant</span></div>
			<div class="box-content ">
				<form class="fill-up">
					<ul class="box-list">
						<li>
							<span>Restaurant</span>
							<span class="pull-right">
								<select class="test-restaurant chosen-select" style="width:480px;">
									<option value="" selected>Choose...</option>
									<? foreach (Restaurant::q('select * from restaurant order by name') as $restaurant) : ?>
										<option value="<?=$restaurant->id_restaurant?>"><?=$restaurant->name?> (permalink: <?=$restaurant->permalink?>)</option>
									<? endforeach ; ?>
								</select>
							</span>
						</li>
						<li>
							<span>Time</span>
							<span class="pull-right">
								<input type="text" class="test-time" value="<?=$this->now ? 'NOW' : $this->time->format('Y-m-d H:i:s')?>">
							</span>
						</li>
						<li>
							<span class="pull-right">
								<a class="btn btn-blue test-calculate">Calculate</a> 
							</span>
						</li>
					</ul>
				</form>
			</div>
		</div>
		
		

		<div class="box">
			<div class="box-content padded">
				<?=$this->restaurant->name?> is <b><?=$this->open ? 'OPEN' : 'CLOSED'?></b> <?=$this->now ? 'now' : 'at '.$this->time->format('Y-m-d H:i:s')?>
			</div>
		</div>

		
	</div>
</div>




<script>

$(document).ready(function() {
	var go = function() {
		var loc = '/tests/hours?r=' + $('.test-restaurant option:selected').val() + '&t=' + $('.test-time').val();
		location.href = loc;
	};
	$('.chosen-select').select2();
	$('.test-restaurant').change(go);
	$('.test-calculate').click(go);
});
</script>



