<div class="box-content2 box-content-table">
	<table class="tb-zebra">
		<tr>
			<th>Name</th>
			<th>Phone</th>
			<th>Login</th>
			<th ng-if="!community">Community</th>
			<th class="tb-center">Active</th>
			<th class="tb-center">Working</th>
			<th class="tb-center">Working Today</th>
			<th class="tb-center">Pex Card</th>
			<th class="tb-center">Serial / Last four</th>
			<th> </th>
		</tr>
		<tr ng-repeat="s in staff track by $index" ng-attr-tabindex="{{$index+4}}" tab-select="/staff/{{s.login}}">
			<td><a href="/staff/{{s.login}}">{{s.name}}</a></td>
			<td><a href ng-click="callText(s.phone)">{{s.phone | formatPhone}}</a></td>
			<td>{{s.login}}</td>
			<td ng-if="!community">
				<span class="staff-community-repeat" ng-repeat="community in s.communities">
					{{community}}
				</span>
			</td>
			<td class="tb-center">
				<span ng-if="s.active"><i class="fa fa-check"></i></span>
			</td>
			<td class="tb-center">
				<span ng-if="s.working"><i class="fa fa-check"></i></span>
			</td>
			<td class="tb-center">
				<span ng-if="s.working_today"><i class="fa fa-check"></i></span>
			</td>
			<td class="tb-center">
				<span ng-if="s.pexcard"><i class="fa fa-check"></i></span>
			</td>
			<td class="tb-center">
				<span ng-if="s.pexcard">{{s.pexcard.card_serial}} / {{s.pexcard.last_four}}</span>
			</td>
			<td><a href="/staff/{{s.login}}/payinfo">Pay Info</a></td>
		</tr>
	</table>
</div>