<div class="box-content2 box-content-table">
	<table class="tb-zebra">
		<tr>
			<th>Community</th>
			<th>Note</th>
			<th>Added By</th>
			<th>Date</th>
		</tr>
		<tr ng-repeat="note in notes">
			<td>
				<a href="/community/{{note.community.permalink}}/">{{note.community.name}}</a>
			</td>
			<td><span class="listview-smaller">{{note.text}}</span></td>
			<td>
				<a href="/staff/{{note.admin.login}}/">{{note.admin.name}}</a></td>
			<td>{{note.date}}</td>
		</tr>
	</table>
</div>