<div class="box-content2 box-content-table">
	<table class="tb-zebra">
		<tr>
			<th>Info</th>
			<th>Date</th>
			<th>Restaurant</th>
			<th>Customer</th>
			<th>Driver</th>
			<th>Order</th>
			<th>Status</th>
		</tr>
		<tr ng-repeat="order in orders track by $index" ng-class="{ 'delivery_is_self': order.delivery_is_self }" ng-attr-tabindex="{{$index+1}}" tab-select="/order/{{order.id_order}}">
			<td>
				<?php /* Info */ ?>
					<div>
						<a href="/order/{{order.id_order}}">{{order.id_order}}</a>
					</div>
					<div class="link no-underline" ng-click="ticket(order.id_order);">
						<i class="fa fa-comments-o"></i> Ticket
					</div>
				<?php /* Info */ ?>
			</td>
			<td>
				<?php /* Date */ ?>
				{{order.date | localtime | timestamp | date:'MM/dd @ HH:mm'}}
				<?php /* Date */ ?>
			</td>
			<td>
				<?php /* Restaurant */ ?>
				<a href="/restaurant/{{order._restaurant_permalink}}">{{order._restaurant_name}}</a><br>
				<a href="/community/{{order._community_permalink}}" ng-if="!community">{{order._community_name}}</a>
				<?php /* Restaurant */ ?>
			</td>
			<td>
				<?php /* Customer */ ?>
					<div><a href="/customer/{{order.id_user}}">{{order.name}}</a></div>
					<a href ng-click="callText(order.phone)">{{order.phone | formatPhone}}</a>
				<?php /* Customer */ ?>
			</td>
			<td>
				<?php /* Driver */ ?>
					<div><a href="/staff/{{order.status.driver.id_admin}}">{{order.status.driver.name}}</a></div>
					<div><strong>{{order.status.status}}</strong></div>
				<?php /* Driver */ ?>
			</td>
			<td>
				<?php /* Order */ ?>
				${{order.final_price_plus_delivery_markup}}
				<?php /* Order */ ?>
			</td>
			<td>
				<?php /* Status */ ?>
				<b>{{order.status.status}}</b><br>
				<span ng-if="order.status"><span am-time-ago="order.status.date | localtime | timestamp"></span></span>
				<?php /* Status */ ?>
			</td>
		</tr>
	</table>
</div>