<div class="box-content2 box-content-table">
	<table class="tb-zebra">
		<tr>
			<th></th>
			<th>ID</th>
			<th>Name</th>
			<th>Phone</th>
			<th>Address</th>
			<th>Orders</th>
			<th>Last&nbsp;Order</th>
		</tr>
		<tr ng-repeat="customer in customers track by $index" ng-attr-tabindex="{{$index+1}}" tab-select="/customer/{{customer.id_user}}">
			<td class="tb-image-row"><a href="/customer/{{customer.id_user}}">
				<div class="customer-image-crop">
					<img ng-if="customer.image" class="customer-image" src="{{customer.image}}"></img>
					<div ng-if="!customer.image" class="customer-image customer-image-null"></div>
				</div>
			</a></td>
			<td><a href="/customer/{{customer.id_user}}">{{customer.id_user}}</a></td>
			<td>{{customer.name}}</td>
			<td><a href ng-click="callText(customer.phone)">{{customer.phone | formatPhone}}</a></td>
			<td>{{customer.address}}</td>
			<td>{{customer.orders}}</td>
			<td><span ng-if="customer._order_date"><span am-time-ago="customer._order_date"></span></span></td>
		</tr>
	</table>
</div>