<div class="box-content2 box-content-table">
	<table class="tb-zebra">
		<tr>
			<th>Chain</th>
			<th>Community</th>
			<th>Restaurant</th>
			<th>Does a chain exist</th>
			<th>Close enough to campus</th>
			<th class="tb-small"></th>
		</tr>
		<tr ng-repeat="chain in chains track by $index" ng-attr-tabindex="{{$index+1}}" tab-select="/chain/{{chain.id_chain}}">
			<td><span class="listview-bold">{{chain.chain}}</span></td>
			<td><span class="listview-bold">{{chain.community}}</span></td>
			<td>{{chain.restaurant}}</td>
			<td>
				<span class="tag tag-red" ng-if="!chain.exist_at_community">No</span>
				<span class="tag tag-green" ng-if="chain.exist_at_community">Yes</span>
			</td>
			<td>
				<span class="tag tag-red" ng-if="!chain.within_range">No</span>
				<span class="tag tag-green" ng-if="chain.within_range">Yes</span>
			</td>
			<td nowrap class="tb-v-center">
				<div>
					<a href="/chain/community/{{chain.id_community_chain}}"><button class="button button-small button-empty button-green"><i class="fa fa-pencil"></i>&nbsp;&nbsp;Edit</button></a>
				</div>
			</td>
		</tr>
	</table>
</div>