<div class="box-content2 box-content-table">
	<table class="tb-zebra">
		<tr>
			<th>Changed by</th>
			<th>Staff</th>
			<th ng-if="query.type == 'using_pex'">Using pex</th>
			<th ng-if="query.type == 'card_assign'">Card Serial</th>
			<th>Type</th>
			<th>Community</th>
			<th>Date</th>
		</tr>
		<tr ng-repeat="l in logs track by $index" ng-attr-tabindex="{{$index+4}}" tab-select="/staff/{{l.login}}">
		<td>{{l.admin_name}}</td>
			<td>{{l.staff_name}}</td>
			<td ng-if="query.type == 'using_pex'" class="tb-center">
				<span ng-if="l.type == 'using_pex'">
					<span ng-if="l.value">Yes</span>
					<span ng-if="!l.value">No</span>
				</span>
				<span ng-if="l.type != 'using_pex'">-</span>
			</td>
			<td ng-if="query.type == 'card_assign'">
				<span ng-if="l.card_serial">{{l.card_serial}}</span>
				<span ng-if="!l.card_serial">-</span>
			</td>
			<td>{{l.type}}</td>
			<td>{{l.communities}}</td>
			<td>{{l.date}}</td>
		</tr>
	</table>
</div>