<div class="box-content2 box-content-table">
	<table class="tb-zebra">
		<tr>
			<th></th>
			<th><a ng-click="sort('name')">Customer</a></th>
			<th><a ng-click="sort('address')">Location</a></th>
			<th><a ng-click="sort('order')">Last&nbsp;Order</a></th>
			<th>Balanced</th>
			<th>Stripe</th>
			<th></th>
		</tr>
		<tr ng-repeat="customer in customers track by $index" ng-attr-tabindex="{{$index+1}}" tab-select="/customer/{{customer.id_user}}">
			<td class="tb-image-row"><a href="/customer/{{customer.id_user}}">
				<div class="customer-image-crop">
					<img ng-if="customer.image" class="customer-image" src="{{customer.image}}"></img>
					<div ng-if="!customer.image" class="customer-image customer-image-null"></div>
				</div>
			</a></td>
			<td>
				<span class="listview-bold">{{customer.name}}</span>
				<br><span class="listview-smaller"><a href ng-click="callText(customer.phone)">{{customer.phone | formatPhone}}</a></span>
			</td>
			<td>
				<a href="/community/{{customer._id_community}}">{{customer._community_name}}</a>
				<br><span class="listview-smaller">{{customer.address}}</span>
			</td>
			<td><span ng-if="customer._order_date"><span am-time-ago="customer._order_date"></span></span></td>
			<td nowrap class="tb-center tb-v-center">
				<span class="tag tag-green" ng-if="customer._balanced_id">Yes</span>
				<span class="tag tag-red" ng-if="!customer._balanced_id">No</span>
			</td>
			<td nowrap class="tb-center tb-v-center">
				<span class="tag tag-green" ng-if="customer._stripe_id">Yes</span>
				<span class="tag tag-red" ng-if="!customer_stripe_id">No</span>
			</td>
			<td nowrap class="tb-v-center">
				<a href="/orders?search=phone:{{customer.phone}}"><button class="button button-small button-empty button-green"><i class="fa fa-phone"></i>&nbsp;&nbsp;Orders</button></a>
				<a href="/customer/{{customer.id_user}}"><button class="button button-small button-empty button-green"><i class="fa fa-eye"></i>&nbsp;&nbsp;View</button></a>
			</td>
		</tr>
	</table>
</div>