<div class="box-content2 box-content-table">
	<div sticky-header>
		<table class="thead">
			<tr>
				<th>Driver</th>
				<th>Community</th>
				<th>Date</th>
				<th title="PST&#013;Community Timezone">Time</th>
				<th class="tb-small tb-center" title="Texted">Txt</th>
				<th class="tb-small tb-center" title="Called">Cll</th>
				<th class="tb-small tb-center" title="Confirmed">Cnf</th>
				<th class="tb-small"></th>
			</tr>
		</table>
		<div class="tbody">
			<table class="tb-zebra">
				<tr ng-repeat="s in shifts track by $index" ng-attr-tabindex="{{$index+4}}" ng-init="$last ? ngRepeatFinished() : null">
					<td nowrap="">
						<span class="listview-bold"><a href="/staff/{{s.login}}">{{s.driver}}</a></span>
						<br><a href ng-click="callText(s.phone)" class="listview-smaller">{{s.phone | formatPhone}}</a>
					</td>
					<td>
						<a href="/community/{{s.community_permalink}}">{{s.community}}</a>
					</td>
					<td>
						{{s.date}}
					</td>
					<td>
						<span class="listview-bold">{{s.period_pst}} (PDT)</span><br>
						<span class="listview-smaller">{{s.period}} ({{s.community_tz}})</span>
					</td>
					<td nowrap class="tb-center tb-v-center">
						<span class="tag tag-empty tag-green" ng-if="s.text">Yes</span>
						<span class="tag tag-empty tag-red" ng-if="!s.text">No</span>
					</td>
					<td nowrap class="tb-center tb-v-center">
						<span class="tag tag-empty tag-green" ng-if="s.call">Yes</span>
						<span class="tag tag-empty tag-red" ng-if="!s.call">No</span>
					</td>

					<td nowrap class="tb-center tb-v-center">
						<span class="tag tag-red" ng-if="!s.confirmed">No</span>
						<span class="tag tag-green" ng-if="s.confirmed">Yes</span>
					</td>
					<td nowrap class="tb-v-center tb-right">
						<button ng-if="!s.confirmed" class="button button-small button-empty button-green" ng-click="shift_checkin( s.id_admin_shift_assign )"><i class="fa fa-calendar"></i>&nbsp;&nbsp;Check In</button></a>
					</td>
				</tr>
			</table>
		</div>
	</div>
</div>
