<div class="box-content2 box-content-table">
	<table class="tb-zebra">
		<tr>
			<th>Customer</th>
			<th>Reason</th>
			<th>Due To</th>
			<th class="tb-small tb-center">Amount</th>
			<th class="tb-small tb-center">Status</th>
			<th class="tb-small"></th>
		</tr>

		<tr ng-repeat="dispute in disputes">
			<td nowrap>
				<a href="/customer/{{dispute.id_user}}">{{dispute.name}}</a>
				<br><a href ng-click="callText(dispute.phone)" class="listview-smaller">{{dispute.phone | formatPhone}}</a>
			</td>
			<td>
				<span class="listview-smaller">
					{{dispute.reason}}
				</span>
			</td>
			<td>
				{{dispute.due_to | convertimeformat:account.user.timezone:'MMMM Do YYYY, h:mm:ss a'}}
				&nbsp;(<span class="listview-bold">{{dispute.due_to | convertimeformat:account.user.timezone:'z'}}</span>)
			</td>
			<td class="tb-v-center tb-center">
				$ {{dispute.charged}}
			</td>
			<td class="tb-v-center tb-center">
				<div ng-switch="dispute.status">
					<span class="tag tag-red no-wrap" ng-switch-when="needs_response">Needs Response</span>
					<span class="tag tag-blue no-wrap" ng-switch-when="under_review">Under Review</span>
					<span class="tag tag-black no-wrap" ng-switch-when="lost">Lost</span>
					<span class="tag tag-green no-wrap" ng-switch-when="won">Won</span>
					<span ng-switch-default class="tag tag-purple no-wrap">{{dispute.status}}</span>
				</div>
			</td>
			<td nowrap class="tb-v-center">
				<a href="/dispute/{{dispute.id_stripe_dispute}}"><button class="button button-small button-empty button-green">
				<i class="fa fa-eye"></i>
				&nbsp;&nbsp;View</button></a>
			</td>
		</tr>
	</table>
</div>
