<div class="box-content2 box-content-table">
	<table class="tb-zebra">
		<tr>
			<th>Contact</th>
			<th>Message</th>
			<th class="tb-small tb-center">Type</th>
			<th class="tb-small tb-center">Status</th>
			<th class="tb-small"></th>
		</tr>

		<tr ng-repeat="ticket in lotsoftickets">
			<td nowrap>
				<span ng-if="ticket.type == 'WARNING'">
					<i>System</i>
				</span>
				<span ng-if="ticket.type != 'WARNING'">
					<a href="/staff/{{ticket.id_admin}}" ng-if="ticket.name_admin">{{ticket.name}}</a>
					<a href="/customer/{{ticket.id_user}}" ng-if="!ticket.id_admin && ticket.id_user">{{ticket.name}}</a>
					<br><a href ng-click="callText(ticket.phone)" class="listview-smaller">{{ticket.phone | formatPhone}}</a>
				</span>
			</td>
			<td>
				<span class="listview-smaller">
					<i ng-if="ticket.timestamp_client" am-time-ago="ticket.timestamp_client*1000"></i>
					<i ng-if="!ticket.timestamp_client"><i>Unknown</i></i>
					<br>
					<span>{{ticket.message_client}}</span>
				</span>
			</td>
			<td class="tb-v-center tb-center">
				<span class="tag tag-purple" ng-if="ticket.type == 'WARNING'">System</span>
				<span ng-if="ticket.type != 'WARNING'">
					<span class="tag tag-blue" ng-if="ticket.id_user">Customer</span>
					<span class="tag tag-orange" ng-if="!ticket.id_user && ticket.id_admin_from">Driver</span>
					<span class="tag tag-grey" ng-if="!ticket.id_user && !ticket.id_admin_from">Unknown</span>
				</span>
			</td>
			<td class="tb-v-center tb-center">
				<span class="tag tag-green" ng-if="ticket.status == 'open'">Open</span>
				<span class="tag tag-red" ng-if="ticket.status != 'open'">Closed</span>
			</td>
			<td nowrap class="tb-v-center">
				<button ng-if="ticket.status == 'open'" ng-click="closeTicket(ticket.id_support);" class="button button-small button-empty button-green"><i class="fa fa-times-circle"></i>&nbsp;&nbsp;Close</button>
				<a href="/ticket/{{ticket.id_support}}" eat-click ng-click="loadTicket( ticket.id_support );ticket.loading = true;" ><button class="button button-small button-empty button-green">
				<i class="fa fa-eye" ng-if="!ticket.loading"></i>
				<i class="fa fa-spinner fa-spin" ng-if="ticket.loading"></i>
				&nbsp;&nbsp;View</button></a>
			</td>
		</tr>
	</table>
</div>