<div class="box-content2 box-content-table">
	<table class="tb-zebra">
		<tr>
			<th></th>
			<th><a ng-click="sort('id')">ID</a></th>
			<th><a ng-click="sort('name')">Name</a></th>
			<th><a ng-click="sort('phone')">Phone</a></th>
			<th><a ng-click="sort('address')">Address</a></th>
			<th class="tb-center"><a ng-click="sort('orders')">Orders</a></th>
			<th><a ng-click="sort('order')">Last&nbsp;Order</a></th>
		</tr>
		<tr ng-repeat="customer in customers track by $index" ng-attr-tabindex="{{$index+1}}" tab-select="/customer/{{customer.id_user}}">
			<td class="tb-image-row"><a href="/customer/{{customer.id_user}}">
				<div class="customer-image-crop">
					<img ng-if="customer.image" class="customer-image" src="{{customer.image}}"></img>
					<div ng-if="!customer.image" class="customer-image customer-image-null"></div>
				</div>
			</a></td>
			<td><a href="/customer/{{customer.id_user}}">{{customer.id_user}}</a></td>
			<td>{{customer.name}}</td>
			<td><a href ng-click="callText(customer.phone)">{{customer.phone | formatPhone}}</a></td>
			<td>{{customer.address}}</td>
			<td class="tb-center">{{customer.orders}}</td>
			<td><span ng-if="customer._order_date"><span am-time-ago="customer._order_date"></span></span></td>
		</tr>
	</table>
</div>