<div class="box-content2 box-content-table">
	<table class="tb-zebra">
		<tr>
			<th></th>
			<th>Name</th>
			<th>Contact</th>
			<th class="tb-center">Orders</th>
			<th>Last&nbsp;Order</th>
			<th class="tb-small">Active</th>
			<th class="tb-small">Open</th>
			<th class="tb-small">Delivery</th>
			<th class="tb-small"></th>
		</tr>
		<tr ng-repeat="restaurant in restaurants track by $index" ng-class="{ 'delivery_it_self': restaurant.delivery_it_self }" ng-attr-tabindex="{{$index+1}}" tab-select="/restaurant/{{restaurant.permalink}}">
			<td class="tb-image-row"><a href="/restaurant/{{restaurant.permalink}}">
				<div class="customer-image-crop">
					<img ng-if="restaurant.image" class="customer-image" src="https://i.crunchbutton.com/66x66/{{restaurant.image}}"></img>
					<div ng-if="!restaurant.image" class="customer-image restaurant-image-null"></div>
				</div>
			</a></td>
			<td>
				<span class="listview-bold">{{restaurant.name}}</span><br>
				<span ng-if="!community">
					<span class="staff-community-repeat listview-smaller" ng-repeat="community in restaurant.communities">
						<a href="/community/{{community.permalink}}">{{community.name}}</a>
					</span>
				</span>
			</td>
			<td>
				<span class="listview-smaller">
					<a href ng-click="callText(restaurant.phone)">{{restaurant.phone | formatPhone}}</a>
				</span>
				<br>
				<span class="listview-smaller">
					{{restaurant.address | formatAddress}}
				</span>
			</td>
			<td class="tb-center">
				<a href="/orders?restaurant={{restaurant.id_restaurant}}" ng-if="restaurant.orders != '0'">{{restaurant.orders}}</a>
				<span ng-if="restaurant.orders == '0'">0</span>
			</td>
			<td><span ng-if="restaurant._order_date"><span am-time-ago="restaurant._order_date"></span></span></td>


			<td nowrap class="tb-center tb-v-center">
				<span class="tag tag-green" ng-if="restaurant.active">Active</span>
				<span class="tag tag-red" ng-if="!restaurant.active">Inactive</span>
			</td>
			<td nowrap class="tb-center tb-v-center">
				<span class="tag tag-red" ng-if="!restaurant.open_for_business">Closed</span>
					<span ng-if="restaurant.open_for_business">
					<span class="tag tag-green" ng-if="restaurant.open">Open</span>
					<span class="tag tag-red" ng-if="!restaurant.open">Closed</span>
				</span>
			</td>
			<td class="tb-center tb-v-center">
				<span class="tag tag-orange" ng-if="restaurant.delivery && restaurant.delivery_service">3rd</span>
				<span class="tag tag-blue" ng-if="restaurant.delivery && !restaurant.delivery_service">1st</span>
				<span class="tag tag-lightgrey" ng-if="restaurant.takeout && !restaurant.delivery">Takeout</span>
				<span class="tag tag-lightgrey" ng-if="!restaurant.takeout && !restaurant.delivery">None</span>
			</td>
			<td nowrap class="tb-v-center">
				<a href="https://cockpit.crunchbutton.com/restaurants/{{restaurant.id_restaurant}}" target="_system"><button class="button button-small button-empty button-green"><i class="fa fa-pencil"></i>&nbsp;&nbsp;Edit</button></a>
				<a href="/restaurant/payment-info/{{restaurant.permalink}}"><button class="button button-small button-empty button-green"><i class="fa fa-money"></i>&nbsp;&nbsp;Pay Info</button></a>
				<a href="/restaurant/{{restaurant.permalink}}"><button class="button button-small button-empty button-green"><i class="fa fa-eye"></i>&nbsp;&nbsp;View</button></a>
			</td>
		</tr>
	</table>
</div>