<div class="show-more-links left">
	<a href="" ng-click="viewLess()" ng-if="allowAll && query.limit == 'none'">Show Less</a>
	<a href="" ng-click="viewAll()" ng-if="allowAll && query.limit != 'none'">Show All</a>
</div>

<table class="tb-pagination right" ng-if="pages > 1 || more || query.page > 1" page-key>
	<tbody>
		<tr>
			<td class="td-prev"><button class="button orange" ng-if="query.page > 1" ng-click="setPage(query.page-1)">prev</button></td>
			<td class="td-info">Page {{query.page}} of <span ng-if="query.fullcount != 'false' && query.fullcount">{{pages}}</span><span ng-if="query.fullcount == 'false' || !query.fullcount">many</span></td>
			<td class="td-next"><button class="button orange" ng-if="(query.page < pages) || more" ng-click="setPage(query.page+1)">next</button></td>
		</tr>
	</tbody>
</table>
<div class="divider"></div>
