<div class="box-content2 box-content-table">
	<table class="tb-zebra">
		<tr>
			<th>ID</th>
			<th>From</th>
			<th>Updated</th>
			<th>Name</th>
			<th>Message</th>
		</tr>

		<tr ng-repeat="ticket in lotsoftickets">
			<td><a href="/ticket/{{ticket.id_support}}">{{ticket.id_support}}</td>
			<td><a href ng-click="callText(ticket.phone)">{{ticket.phone | formatPhone}}</a></td>
			<td nowrap="nowrap">
				<span ng-if="ticket.timestamp" am-time-ago="ticket.timestamp*1000"></span>
				<span ng-if="!ticket.timestamp"><i>Unknown</i></span>
			</td>
			<td>{{ticket.name}}</td>
			<td>{{ticket.message}}</td>
		</tr>
	</table>
</div>