<div class="top-pad"></div>
<div class="content-padding">
	<div class="page-title-wrap">
		<h1 class="title"><i class="fa fa-shield"></i>Groups</h1>
		<div class="page-title-nav">
			<a href="/group/new"><button class="button button-green nav-button-green"><i class="fa fa-plus"></i><span>Add Group</span></button></a>
		</div>
	</div>
	<div class="divider"></div>
	<div class="box-content2 box-content-table">
		<table>
			<tr>
				<td colspan="4"><i class="fa fa-search"></i>&nbsp;&nbsp;<input type="text" ng-model="query.search" id="search" tabindex="1"></td>
			</tr>
		</table>
	</div>
	<div class="bar-loader bar-loader-search" ng-class="{'bar-loader-loading': loading}"></div>
	<ng-include src="'/assets/view/listview-groups.html'"></ng-include>
	<ng-include src="'/assets/view/listview-paging.html'"></ng-include>
</div>