<?php if ( !$this->orders->count() ) { ?>
	No results found
<?php } else { ?>

	<table class="list-orders table table-normal">
		<thead>
			<tr>
				<td>Order</td>
				<td>Driver</td>
				<td>Notifications</td>
				<td>Actions</td>
			</tr>
		</thead>

		<?php 
			foreach( $this->orders as $order ) { 
				$timeToDelivery = '';
				$date = $order->date(); ?>
			<tr>
				<td style="vertical-align:top;">
					<a href="/vieworder/<?php echo $order->uuid; ?>" target="blank">Order #<?php echo $order->id_order; ?></a>
					<br/>
					<a href="http://cbtn.io/<?php echo $order->id_order; ?>" target="blank">http://cbtn.io/<?php echo $order->id_order; ?></a>
					<br />
					<?php echo $order->restaurant()->name; ?>
					<br />
					<?php echo $date->format('M jS Y')?> <?php echo $date->format('g:i:s A')?>
				</td>
				<td style="vertical-align:top;">
					<?php 
						if( $order->driver()->name ){
							echo '<strong>' . $order->driver()->name . '</strong>';
							if( $order->driver()->phone ){
								echo '<br/><i class="icon icon-phone"></i> ' . $order->driver()->phone;	
							}
							if( $order->driver()->txt ){
								echo '<br/><i class="icon icon-mobile-phone"></i> ' . $order->driver()->txt;	
							}
							if( $order->driver()->email ){
								echo '<br/><i class="icon icon-envelope"></i> ' . $order->driver()->email;	
							}
						} else {
							echo '<i style="color:#CCC;font-size:11px;">None</i>';
						}
						?>
				</td>
				<td style="vertical-align:top;">
				<?php 
					$hasNotification = false;
					$notifications = Crunchbutton_Admin_Notification_Log::byOrder( $order->id_order );
					foreach( $notifications as $notification ){
						$hasNotification = true;
						$_date = $notification->date();
						echo $notification->description . ' : ' . $_date->format( 'g:i:s A' ) . '<br/>';
					}
					if( !$hasNotification ){
						echo '<i style="color:#CCC;font-size:11px;">-</i>';
					}
				?>
				</td>
				<td style="vertical-align:top;">
				<?php 
				$editActions = true;
				$_log = '';
				$logs = $order->actions();
				foreach( $logs as $log ){
					$_date = $log->date();
					switch ( $log->type ) {
						case Crunchbutton_Order_Action::DELIVERY_REJECTED:
							$editActions = false;
							$color = '#fb3927';
							break;
						case Crunchbutton_Order_Action::DELIVERY_ACCEPTED:
						case Crunchbutton_Order_Action::DELIVERY_PICKEDUP:
						case Crunchbutton_Order_Action::DELIVERY_DELIVERED:
							$color = '#009c48';
							$editActions = false;
							break;
						default:
							$color = '#000';
							break;
					}
					if( $log->type == Crunchbutton_Order_Action::DELIVERY_DELIVERED ){
					 	$timeToDelivery = $date->diff( $_date );
					 	$timeToDelivery = ( $timeToDelivery->days * 24 * 60 ) + ( $timeToDelivery->h * 60 ) + ( $timeToDelivery->i );
						$timeToDelivery .= ' minutes';
					}
						$_log .= '<span style="color:' . $color . '">' . $log->type . '</span> : ' . $_date->format('g:i:s A') . '<br/>';
				}

				if( $editActions ){
					?>
						<div>
							<button onclick="deliveries.action( <?php echo $order->id_order ?> );" class="btn btn-blue"> Assign driver</button>
						</div>
					<?php
				}

				if( $timeToDelivery != '' ){
					echo '<strong style="color:#666;font-size:12px;">Delivered in ' . $timeToDelivery . '</strong><br/>';
				}
				if( $_log ){
					echo $_log;	
				} else {
					echo '<i style="color:#CCC;font-size:11px;">-</i>';
				}
				?>
				</td>
			</tr>
		<?php } ?>
	</table>
<?php } ?>