<?
	$this->title = 'Drivers';
	$this->titleicon = 'road';
	$this->titleLink = '/drivers';
	$this->title2 = 'Shift';
	$this->title2icon = 'clock';
	$communities = $this->communities;
?>
<div class="container-fluid padded">
	<div class="row-fluid">
		<div class="box">
			<div class="box-header"><span class="title">Enter your shift preferences</span></div>
			<?php foreach( $communities as $community ) { ?>
				<div class="padded">
					<div class="row-fluid">
						<div class="box-content">
							<h6><?php echo $community->name; ?></h6>
								<table width="100%">
								<tr>
									<?php 
									foreach( $this->days as $day ){ 
										$dark = ( $day->format( 'N' ) % 2 == 0 ) ? '#F5F5F5' : '';
									?>
									<th width="14%" style="background:<?php echo $dark; ?>">
										<div class="row-fluid padded">
											<strong style="font-size:15px;color:#666;">
												<?php echo ucfirst( $day->format( l ) ); ?>
												<div style="font-size:10px;font-weight:normal;color:#CCC;"><?php echo $day->format( 'M' ); ?> <?php echo $day->format( 'd' ); ?></div>
											</strong>
										</div>
									</th>
									<?php } ?>
									<tr>
									<?php 
									$hasShift = false;
									foreach( $this->days as $day ){ 
										$dark = ( $day->format( 'N' ) % 2 == 0 ) ? '#F5F5F5' : '';
										$segments = Crunchbutton_Community_Shift::shiftByCommunityDay( $community->id_community, $day->format( 'Y-m-d' ) );
										?>
										<td style="background:<?php echo $dark; ?>">											
											<?php 
											foreach( $segments as $segment ) { 
												$hasShift = true;
												?><div class="row-fluid padded">
														<strong><?php echo $segment->startEndToString(); ?></strong> ( <?php echo $segment->timezoneAbbr(); ?> )
													</div><?php
											} ?>
										</td>
									<?php } ?>
									</tr>
								</table>
								<?php if( !$hasShift ){ ?><i><?php echo $community->name; ?> has no shift for this period!</i><?php } ?>
							<hr />
						</div>
					</div>
				</div>
			<?php } ?>
			<div class="form-actions">
							<button type="button" class="save-shift-community btn btn-blue">Save changes</button>
						</div>
				<div class="divider"></div>
			</div>
		</div>
	</div>

</div>
<style type="text/css">
	label{
		text-align: right;
	}
</style>
<script type="text/javascript" src="/assets/js/admin.shift.js"></script>
<script type="text/javascript">
$( document ).ready( function(){
	shift.community.init();
} );
</script>