<div class="top-pad"></div>

<div class="content-padding">
	<h1 class="left title"><i class="fa fa-truck"></i>Delivery Sign Ups</h1>
	<div class="divider"></div>

	<div class="box-content2 box-content-table">
		<table>
			<tr>
				<td colspan="1"><i class="fa fa-search"></i>&nbsp;&nbsp;<input type="text" ng-model="query.search" id="search" tabindex="1"></td>
				<th>Status</th>
				<td>
					<select ng-model="query.status" name="searchStatus" tabindex="2">
						<option value="new">New</option>
						<option value="review">Needs to Review</option>
						<option value="archived">Archived</option>
						<option value="deleted">Deleted</option>
					</select>
				</td>
			</tr>
		</table>
	</div>

	<div class="bar-loader bar-loader-search" ng-class="{'bar-loader-loading': loading}"></div>

	<ng-include src="'/assets/view/listview-delivery-signups.html'"></ng-include>
	<ng-include src="'/assets/view/listview-paging.html'"></ng-include>

</div>
