<?
	$this->title = 'Drivers';
	$this->titleicon = 'road';
	$this->titleLink = '/drivers';
	$this->title2 = 'Assign by community';
	$this->title2icon = 'magnet';
	$this->title2Link = '/drivers/assign';
?>
<!-- content -->
<div class="container-fluid padded">
	<div class="row-fluid">
		<div class="box">
			<div class="box-header">
				<span class="title">Assign by community</span>
			</div>
			<div class="box-content">
				<ul class="box-list">
					<li>
						<label><strong>Community</strong></label>
						<span>
							<select class="chzn-select" name="community" id="community" data-placeholder="Choose a community">
								<option></option>
								<? foreach ( $this->communities as $id_community => $name ) { ?>
									<option value="<?php echo $id_community; ?>" <?php if( $this->community->id_community == $id_community ){ echo 'selected="selected"'; } ?> ><?php echo $name; ?></option>
								<? } ?>
							</select>
						</span>
					</li>
					<?php ?>
					<?php if( $this->community ) { ?>
						<li>
							<label><strong>Restaurants of <?php $this->community->name ?></strong></label>
							<span>

								<?php 
									$join = ' ';
									foreach( $this->restaurants_community as $restaurant ) {
										echo $join . $restaurant->name;
										$join = ', ';
									} 
								?>
							</span>
						</li>
						<li>
							<label><strong>Drivers*</strong></label>
							<span>
								<select id="id_admin" class="chzn-select" multiple name="id_admin" data-placeholder="Choose the drivers" style="width:100%;">
								<option></option>
								<? foreach ( $this->drivers as $driver ) { ?>
									<option value="<?php echo $driver->id_admin; ?>" <?php if( $this->drivers_delivery[ $driver->id_admin ] ){ echo 'selected="selected"'; } ?> ><?php echo $driver->name; ?></option>
								<? } ?>
								</select>
							</span>
							<div class="note">
								*Admin users with active notifications.
							</div>
						</li>
						<li>
							<span>
								<button type="button" onclick="assign.save();" class="btn btn-green"><i class="icon-save"></i> Save </button> 
							</span>
						</li>
					<?php } 
					?>
				</ul>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
var assign = {};
assign.save = function(){
	var data = { 'id_admin' : $( '#id_admin' ).val(), 'id_community' : '<?php echo $this->community->id_community ?>' };
	$.ajax( {
		url: '/api/drivers/community',
		method: 'POST',
		data: data,
		dataType: 'json',
	} ).done( function( data ) {
		if( data.success ){
			alert( 'Saved!' );
			location.reload();
		} else {
			alert( 'Oops! ' + data.error );
		}
	} );
};
$(document).ready( function(){
	$( '#community' ).on( 'change', function(){
		location.href = '/drivers/assign/community/' + $( this ).val();
	} );
} );
</script>