<?
	$this->title = 'Drivers';
	$this->titleicon = 'road';
	$this->titleLink = '/drivers';
	$this->title2 = 'Assign drivers to restaurants/communities';
	$this->title2icon = 'magnet';
?>
<!-- content -->
<div class="container-fluid padded">
	<div class="row-fluid">
		<div class="box">
			<div class="box-header">
				<span class="title">Assign drivers to restaurants/communities</span>
			</div>
			<div class="box-content padded">
				<a href="/drivers/assign/driver"> <i class="icon-road"></i> By driver</a>
				<br />
				<br />
				<a href="/drivers/assign/restaurant"> <i class="icon-food"></i> By restaurant</a>
				<br />
				<br />
				<a href="/drivers/assign/community"> <i class="icon-group"></i> By community</a>
			</div>
		</div>
	</div>
</div>