<?php 
	$id_order = 16844;
	$url = 'http://cockpit.la/' . $id_order;
?>
<p>
	Hey <?php echo $name; ?>,
</p>
<p>
	Here's your username to log in when orders come in.
</p>
<p>
	Username: <?php echo $login ?>
	<br/>
	Password: (is the one you typed)
</p>
<p>
	Test this URL out on your phone (exactly as it appears, no www.) and enter your username and password:<a href="<?php echo $url; ?>">cockpit.la/<?php echo $id_order; ?></a> 
</p>
<p>
	Once you've tested it, let me know, to confirm that it worked.
</p>
<p>
	Thanks,<br />
	The Crunchbutton Team
</p>