<script type="text/javascript">
if (App){
	App.config = <?=json_encode(c::appConfig())?>;
} else {
	$(function() {
		App.config = <?=json_encode(c::appConfig())?>;
	});
}
</script>

</head>
<?
	$basicPages = ['legal','help','faq','hello'];
	if (!c::getPagePiece(0) || (c::getPagePiece(0) && !in_array(c::getPagePiece(0), $basicPages) && !$this->community)) {
		$e = ' short-meal-list';
	}
?>
<body><? /* data-ng-controller="AppController" */?>
	<div class="wrapper">
	
		<div class="nav" data-role="header" data-position="fixed">
			<div class="content<?=$e?>">
				<div class="pacman-loading pacman-left"></div>
				<div class="nav-back" ng-tap="back()"></div>
				<div class="logo"><a href="javascript:;" ng-tap="link('/')"><div class="logo-img"></div></a></div>
				<div class="sign-in-icon"></div>
				<div title="Change location" class="config-icon" ng-tap="link('/location')"></div>
				<div class="signin-box-header">
					<div class="signin-user" title="My Account + Past Orders"></div>
					<div class="signin-icon"></div>
				</div>
			</div>
		</div>
		<div class="body">
			<div class="content<?=$e?>">
				<div class="main-content pages">
					<div ng-include="view/signin.html"></div>
					<div ng-view><?=$this->content?></div>
				</div>
			</div>
		</div>
		<div class="divider"></div>
		<div class="footer">
			<div class="fb-like-mobile fb-like-box" data-href="http://www.facebook.com/crunchbutton" data-width="300" data-show-faces="false" data-stream="false" data-header="false"></div>

			<div class="footer-content">
				<a href="javascript:;" ng-tap="link('/help')">Help</a>
				<a href="javascript:;" ng-tap="link('/legal')">Legal</a>
				<a href="javascript:;" ng-tap="link('/orders')" <?=!c::user()->id_user ? ' style="display: none;"' : ''?>>Order History</a>
				<? if (c::env() == 'beta' || c::env() == 'local') : ?>
					<a href="javascript:App.test.card();" class="test-card">TEST: card</a>
					<a href="javascript:App.test.logout();" class="test-logout">TEST: logout</a>
					<a href="javascript:App.test.clearloc();" class="test-clearloc">TEST: clear loc</a>
				<? endif ; ?>
				<br />
				<span class="copyright">&copy; <?=date('Y')?> YouBeo. All rights reserved.</span>
			</div>
		</div>

		<div ng-include="'view/signin.html'"></div>
		<div ng-include="'view/signup.html'"></div>
		<div ng-include="'view/suggestion.html'"></div>
		<div ng-include="'view/support.html'"></div>

	</div>

	<div id="fb-root"></div>

	<audio id="get-food-audio">
		<source src="/assets/audio/crunch.mp3"></source>
		<source src="/assets/audio/crunch.ogg"></source>
	</audio>	
</body>

<script type="text/javascript">
	$(function() {
		window.fbAsyncInit = function() {
			FB.init({
				appId: '<?=Cana::config()->facebook->app?>',
				cookie: true,
				xfbml: true,
				oauth: true
			});
			FB.getLoginStatus(App.signin.facebook.processStatus);
			FB.Event.subscribe('auth.statusChange', App.signin.facebook.processStatus);
		};
	});

	(function(d, s, id) {
	var js, fjs = d.getElementsByTagName(s)[0];
	if (d.getElementById(id)) return;
	js = d.createElement(s); js.id = id;
	js.src = "//connect.facebook.net/en_US/all.js";
	fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));

</script>

<? if ($_SERVER['__HTTP_HOST'] == 'crunchbutton.com') : ?>
	<script type="text/javascript">
		var _gaq = _gaq || [];
		_gaq.push(['_setAccount', 'UA-36135548-1']);
		_gaq.push(['_setDomainName', 'crunchbutton.com']);
		_gaq.push(['_setAllowLinker', true]);
		_gaq.push(['_trackPageview']);
		(function() {
			var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		})();
	</script>
<? endif ; ?>

<div id="small-dialog" class="zoom-anim-dialog mfp-hide">
        <h1>Dialog example</h1>
        <p>This is dummy copy. It is not meant to be read. It has been placed here solely to demonstrate the look and feel of finished, typeset text. Only for show. He who searches for meaning here will be sorely disappointed.</p>
      </div>
</html>