<? foreach (new DirectoryIterator(c::config()->dirs->view.'default/crunchbutton/frontend') as $fileInfo) : ?>
	<? if (!$fileInfo->isDot() && $fileInfo->getBasename() != '.DS_Store' ) : ?>
		<script type="text/ng-template" id="assets/view/<?=$fileInfo->getBasename('.phtml')?>.html">
			<?=$this->render('frontend/'.$fileInfo->getBasename('.phtml'), ['filter' => false])?>
		</script>
	<? endif ; ?>
<? endforeach; ?>