<!doctype html>
<html lang="en">
<head>
<base href="/">
<title><?=$this->title ? $this->title : 'Crunchbutton'?></title>
<meta name="fragment" content="!" />
<meta name="viewport" content="initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0" />
<meta name="format-detection" content="telephone=no">


<meta property="al:ios:app_name" content="Crunchbutton">
<meta property="al:ios:app_store_id" content="721780390">
<meta property="al:ios:url" content="crunchbutton://<?=$_REQUEST['__url']?>">
<meta property="al:android:package" content="com.crunchbutton" />
<meta property="al:android:url" content="crunchbutton://<?=$_REQUEST['__url']?>" />
<meta property="al:android:app_name" content="Crunchbutton" />
<meta property="al:web:url" content="https://crunchbutton.com/<?=$_REQUEST['__url']?>">
<meta property="al:web:should_fallback" content="true">

<meta http-equiv="X-UA-Compatible" content="IE=edge" />

<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black">

<link rel="apple-touch-icon-precomposed" href="/assets/images/micro/appicon.png">
<?=$this->display('layout/html.servertime')?>

<? if (c::config()->bundle) : ?>
	<? $css = c::config()->site->config('s3-bundle')->val() ? 'https://'.c::config()->s3->buckets->build->cache.'/'.getenv('HEROKU_SLUG_COMMIT').'/css/crunchbutton.css' : '/assets/css/bundle.css?v='.getenv('HEROKU_SLUG_COMMIT') ?>
	<link rel="stylesheet" type="text/css" href="<?=$css?>">
<? else : ?>
	<?=$this->display('bundle/css', ['set' => ['style' => ['seven']]])?>
<? endif ; ?>
<link rel="shortcut icon" href="/assets/images/micro/appicon.png">

<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
<link href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet" type="text/css">

<script>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
document,'script','//connect.facebook.net/en_US/fbevents.js');
fbq('init', '1668785076668148');
fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=1668785076668148&ev=PageView&noscript=1"/></noscript>

<script type="text/javascript" src="https://www.google.com/jsapi"></script>

<?=$this->display('layout/html.templates')?>

<?=$this->display('layout/html.facebook')?>
