<?
	$basicPages = ['legal','help','faq','hello'];
	if (!c::getPagePiece(0) || (c::getPagePiece(0) && !in_array(c::getPagePiece(0), $basicPages) && !$this->community)) {
		$e = ' short-meal-list';
	}
?>

<div class="snap-drawers" ng-controller="SideMenuCtrl">
	<div class="snap-drawer snap-drawer-left">
		<div>
			<div class="pushabutton-getfood"></div>
<? /* for testing			<div ng-bind="account.user.name"></div> */ ?>
			<ul>
				<li ng-instant="navigation.link('/food-delivery')">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-cutlery"></i></td>
							<td class="side-menu-label">Restaurants</a></td>
						</tr>
					</table>
				</li>
				<li ng-show="account.user.id_user" ng-instant="navigation.link('/orders')">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-clock-o"></i></td>
							<td class="side-menu-label">Previous Orders</a></td>
						</tr>
					</table>
				</li>
				<li ng-instant="navigation.link('/location')">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-map-marker" style="margin-left: 3px;"></i></td>
							<td class="side-menu-label">Change Location</a></td>
						</tr>
					</table>
				</li>
				<li ng-instant="navigation.link('/help')">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-question-circle"></i></td>
							<td class="side-menu-label">FAQ</a></td>
						</tr>
					</table>
				</li>
				<li ng-show="!account.user.id_user" ng-instant="navigation.signin()">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-user"></i></td>
							<td class="side-menu-label">Log In</a></td>
						</tr>
					</table>
				</li>
				<li ng-show="account.user.id_user" ng-instant="signout.signout()">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-mail-reply"></i></td>
							<td class="side-menu-label">Logout</a></td>
						</tr>
					</table>
				</li>

				<li ng-instant="test.card()" ng-show="debug()">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-circle-o"></i></td>
							<td class="side-menu-label">TEST: card</a></td>
						</tr>
					</table>
				</li>
				<li ng-instant="test.clearloc()" ng-show="debug()">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-circle-o"></i></td>
							<td class="side-menu-label">TEST: clear loc</a></td>
						</tr>
					</table>
				</li>
				<li ng-instant="test.reload()" ng-show="debug()">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-circle-o"></i></td>
							<td class="side-menu-label">TEST: reload page</a></td>
						</tr>
					</table>
				</li>
			</ul>
			<div>
				<p>&copy; <?=date('Y')?> YouBeo. All rights reserved.</p>
			</div>
		</div>
	</div>
</div>

<div class="wrapper">

	<div id="snap-content" class="snap-content">
		<div class="navs" data-position="fixed" ng-controller="MainHeaderCtrl">
			<div class="nav nav-top">
				<div class="content<?=$e?>">

					<div class="logo"><a href="javascript:;" ng-instant="navigation.home()"><div class="logo-img"></div></a></div>

					<div title="Back" ng-show="navigation.buttons.back" class="hide-before-init nav-back" ng-instant="back()"></div>

					<div title="Change location" ng-show="navigation.buttons.location" class="hide-before-init location-icon config-icon-desktop-hide" ng-instant="navigation.link('/location')"></div>
					<div title="Menu" ng-show="navigation.buttons.menu" class="hide-before-init menu-icon {{ navigation.page == 'home' && 'config-icon-desktop-hide' || '' }}" ng-click="navigation.menu()"></div>

					<div class="signin-box-header hide-before-init">
						<div ng-show="account.user.id_user" ng-instant="navigation.link('/orders')" class="signin-user" title="My Account + Past Orders"></div>
						<div ng-show="!account.user.id_user" ng-instant="navigation.signin()" class="signin-icon"></div>
					</div>

				</div>
			</div>
			<div class="nav nav-cart" ng-click="cartScroll()">
				<div class="cart-summary cart-summary-detail">
					<div class="cart-summary-icon"></div>
					<div class="cart-summary-item-count"><span>{{order.info.totalItems}}</span></div>
					<div class="cart-summary-items">{{order.info.cartSummary}}</div>
				</div>
			</div>
		</div>


		<div ng-class="{'button-bottom-show': (navigation.page == 'restaurant' && navigation.order.cart.hasItems() && !notificationBarStatus ), 'button-bottom-show-notification-bar-on': (navigation.page == 'restaurant' && navigation.order.cart.hasItems() && notificationBarStatus )}" class="button-bottom-wrapper button-bottom-bar" data-position="fixed">
			<button class="button-bottom button-orange" ng-click="navigation.order.submit();"><div>Place Order</div></button>
			<button class="button-bottom button-orange" ng-click="navigation.order.checkout();"><div>Checkout</div></button>
		</div>

		<div class="snap-content-inner bg" ng-scroll-position>
			<div class="body">
				<div class="content<?=$e?>">
					<div class="main-content pages">
						<div ng-view><?=$this->content?></div>
					</div>
				</div>
			</div>

			<div class="divider"></div>

			<div class="footer hide-before-init">

				<? if (!$this->export) : ?>
					<div class="fb-like-mobile fb-like-box" data-href="http://www.facebook.com/crunchbutton" data-width="300" data-show-faces="false" data-stream="false" data-header="false"></div>
				<? endif ; ?>

				<div class="footer-content hidden-phone" ng-controller="MainHeaderCtrl">
					<a ng-show="account.user.id_user" href="javascript:;" ng-click="navigation.link('/free-food')">Free Food</a>
					<a href="javascript:;" ng-click="navigation.link('/help')">Help</a>
					<? if (c::config()->site->config('apply-to-drive')->val()) : ?>
						<a href="/drivers/apply">Apply to Drive</a>
					<? endif ; ?>
					<a ng-show="navigation.account.user" href="javascript:;" ng-click="navigation.link('/orders')">Order History</a>

					<a href="javascript:App.test.card();" class="test-card" ng-show="debug()">TEST: card</a>
					<a href="javascript:App.test.logout();" class="test-logout" ng-show="debug()">TEST: logout</a>
					<a href="javascript:App.test.clearloc();" class="test-clearloc" ng-show="debug()">TEST: clear loc</a>
					<a href="javascript:;" ng-click="navigation.link('/')" ng-show="debug()">TEST: go home</a>
					<a href="javascript:;" ng-click="navigation.link('/location')" ng-show="debug()">TEST: go location</a>

					<br />
					<span class="copyright">&copy; <?=date('Y')?> YouBeo. All rights reserved.</span>
				</div>
			</div>

		</div>


	</div>

	<div class="divider"></div>
</div>

<div ng-include="'assets/view/notification.alert.html'"></div>
<div ng-include="'assets/view/restaurant.closed.html'"></div>
<div ng-include="'assets/view/restaurant.suggestion.tooltip.html'"></div>
<div ng-include="'assets/view/account.html'"></div>
<div ng-include="'assets/view/account.reset.html'"></div>
<div ng-include="'assets/view/account.facebook.html'"></div>
<div ng-include="'assets/view/restaurant.closed.inline.html'"></div>
<div ng-include="'assets/view/giftcard.html'"></div>
<div ng-include="'assets/view/referral.html'"></div>
<div ng-include="'assets/view/suggestion.html'"></div>
<div ng-include="'assets/view/support.html'"></div>
<div ng-include="'assets/view/connection.error.html'"></div>

<div id="fb-root"></div>

<? /*
@sky-loader
<div class="order-sky-loader">
	<div id="Stage" class="EDGE-977700350">
		<div id="Stage_sky-pie" class="edgeLoad-EDGE-977700350"></div>
		<div id="Stage_sky-burger" class="edgeLoad-EDGE-977700350"></div>
	</div>
</div>
*/


