<!doctype html>
<html>
<head>
<title><?=$this->title ? $this->title : 'Crunchbutton'?></title>
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale = 1.0,maximum-scale = 1.0">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<link rel="apple-touch-icon-precomposed" href="/assets/images/appicon.png">

<link rel="stylesheet" type="text/css" href="/assets/css/<?=c::config()->bundle ? 'bundle' : 'style'?>.css?v=<?=Cana_Util::gitVersion()?>">
<link rel="shortcut icon" href="/favicon.ico">

<? if (c::browser()->platform != 'Mac') : ?>
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,300,700" rel="stylesheet" type="text/css">
<? endif ; ?>

<script type="text/javascript" src="https://www.google.com/jsapi"></script>
