<?

/* Exports current community as JSON
 *
 * @todo move this to a controller
 */
if ($this->community) {
	/* @var $this->community Crunchbutton_Community */
	if ($this->admin) {
		$community = $this->community->exports();
	} else {
		$community = $this->community->exports();
	}
	$communityJson = json_encode($community);
	$communityJson = str_replace("'","\\'", $communityJson);
}

?>

<script type="text/javascript">
var c = <?=json_encode(c::appConfig())?>;
if (App) {
	App.config = c;
	c = null;
} else {
	$(function() {
		App.config = c;
		c = null;
	});
}
</script>

</head>

<body class="bg">
<?=$this->display('layout/html.body')?>	
</body>

<audio id="get-food-audio">
	<source src="/assets/audio/crunch.mp3"></source>
	<source src="/assets/audio/crunch.ogg"></source>
</audio>

<script type="text/javascript">
$(function() {
	<? foreach (c::appConfig(['extended']) as $key => $value) : ?>
		App['<?=$key?>'] = <?=json_encode($value)?>;
	<? endforeach ; ?>
	App.init();
});
</script>

<script type="text/javascript">
	$(function() {
		window.fbAsyncInit = function() {
			FB.init({
				appId: '<?=Cana::config()->facebook->app?>',
				cookie: true,
				xfbml: true,
				oauth: true
			});
			var facebookService = angular.element('html').injector().get('FacebookService');
			FB.Event.subscribe('auth.statusChange', facebookService.processStatus);
		};
	});

	(function(d, s, id) {
	var js, fjs = d.getElementsByTagName(s)[0];
	if (d.getElementById(id)) return;
	js = d.createElement(s); js.id = id;
	js.src = "//connect.facebook.net/en_US/all.js";
	fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));
</script>

<? if ($_SERVER['__HTTP_HOST'] == 'crunchbutton.com') : ?>
	<script type="text/javascript">
		var _gaq = _gaq || [];
		_gaq.push(['_setAccount', 'UA-36135548-1']);
		_gaq.push(['_setDomainName', 'crunchbutton.com']);
		_gaq.push(['_setAllowLinker', true]);
		_gaq.push(['_trackPageview']);
		(function() {
			var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		})();
	</script>
<? endif ; ?>

<script type="text/javascript">
    (function(c,a){window.mixpanel=a;var b,d,h,e;b=c.createElement("script");
    b.type="text/javascript";b.async=!0;b.src=("https:"===c.location.protocol?"https:":"http:")+
    '//cdn.mxpnl.com/libs/mixpanel-2.2.min.js';d=c.getElementsByTagName("script")[0];
    d.parentNode.insertBefore(b,d);a._i=[];a.init=function(b,c,f){function d(a,b){
    var c=b.split(".");2==c.length&&(a=a[c[0]],b=c[1]);a[b]=function(){a.push([b].concat(
    Array.prototype.slice.call(arguments,0)))}}var g=a;"undefined"!==typeof f?g=a[f]=[]:
    f="mixpanel";g.people=g.people||[];h=['disable','track','track_pageview','track_links',
    'track_forms','register','register_once','unregister','identify','alias','name_tag',
    'set_config','people.set','people.increment','people.track_charge','people.append'];
    for(e=0;e<h.length;e++)d(g,h[e]);a._i.push([b,c,f])};a.__SV=1.2;})(document,window.mixpanel||[]);
    mixpanel.init("6eb260b54eecfd293d50b5f1423c6e98");
</script>

