<? if (strpos($_SERVER['HTTP_USER_AGENT'],'facebookexternalhit') !== false) : ?>

	<? if ($this->restaurant->id_restaurant) : ?>
		<meta property="og:title" content="<?=$this->restaurant->name?> on Crunchbutton">
		<meta property="og:description" content="One click food ordering from <?=$this->restaurant->name?>. We find the best restaurants <?=$this->community->prep?> <?=$this->community->name?> and make ordering your favorite dishes as easy as one click.">
		<? if ($this->restaurant->image()) : ?>
			<meta property="og:image" content="http://<?=$_SERVER['HTTP_HOST']?>/cache/images/<?=$this->restaurant->facebook()->getFileName()?>">
		<? else : ?>
			<meta property="og:image" content="http://<?=$_SERVER['HTTP_HOST']?>/assets/images/facebook-like.png">
		<? endif ; ?>

	<? elseif ($this->community->id_community) : ?>
		<meta property="og:title" content="Crunchbutton - One click food ordering from <?=$this->community->name?>">
		<meta property="og:description" content="We feature the top restaurants <?=$this->community->prep?> <?=$this->community->name?>. Order your favorite dishes with a click of one button from your computer or phone.">
		<? foreach ($this->community->restaurants() as $restaurant) : ?>
			<? if ($restaurant->image()) : ?>
				<meta property="og:image" content="http://<?=$_SERVER['HTTP_HOST']?>/cache/images/<?=$restaurant->facebook()->getFileName()?>">
			<? else : ?>
				<meta property="og:image" content="http://<?=$_SERVER['HTTP_HOST']?>/assets/images/facebook-like.png">
			<? endif ; ?>

			<? break;?>
		<? endforeach; ?>

	<? else : ?>
		<meta property="og:title" content="Crunchbutton - One click food ordering">
		<meta property="og:description" content="We feature the top restaurants in your neighborhood. Order your favorite dishes with a click of one button from your computer or phone.">
		<meta property="og:image" content="http://<?=$_SERVER['HTTP_HOST']?>/assets/images/facebook-like.png">
	<? endif ; ?>

	<meta property="og:type" content="company">
	<meta property="og:url" content="https://<?=$_SERVER['HTTP_HOST']?><?=$_SERVER['REQUEST_URI']?>">
	<meta property="og:site_name" content="Crunchbutton">
	<meta property="fb:app_id" content="***REMOVED***">
<? endif ; ?>
<!-- Facebook Custom Audience Pixel Code -->
<script>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
document,'script','//connect.facebook.net/en_US/fbevents.js');
// Insert Your Facebook Pixel ID below.
fbq('init', '1668785076668148');
fbq('track', 'PageView');
</script>
<!-- Insert Your Facebook Pixel ID below. -->
<noscript><img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=1668785076668148&ev=PageView&noscript=1"/></noscript>
<!-- End Facebook Custom Audience Pixel Code -->

<? if ($_SERVER['__HTTP_HOST'] == 'crunchbutton.com') : ?>
	<script>
		(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
		ga('create', 'UA-36135548-1', 'crunchbutton.com');
		ga('require', 'ecommerce', 'ecommerce.js');
		ga('require', 'displayfeatures');
		ga('send', 'pageview');
	</script>
<? endif ; ?>