<?

/* Exports current community as JSON
 *
 * @todo move this to a controller
 */
if ($this->community) {
	/* @var $this->community Crunchbutton_Community */
	if ($this->admin) {
		$community = $this->community->exports();
	} else {
		$community = $this->community->exports();
	}
	$communityJson = json_encode($community);
	$communityJson = str_replace("'","\\'", $communityJson);
}

?>


<script type="text/javascript">
var c = <?=json_encode(c::appConfig())?>;
if (App) {
	App.config = c;
	c = null;
	App.logService = 'http<?=$_SERVER['SERVER_NAME'] == 'crunchbutton.com' ? 's' : ''?>://log.<?=$_SERVER['SERVER_NAME']?>/api/';
} else {
	$(function() {
		App.logService = 'http<?=$_SERVER['SERVER_NAME'] == 'crunchbutton.com' ? 's' : ''?>://log.<?=$_SERVER['SERVER_NAME']?>/api/';
		App.config = c;
		c = null;
	});
}
</script>

</head>

<body class="bg no-init">
<?=$this->display('layout/html.body')?>
</body>

<audio id="get-food-audio">
	<source src="/assets/audio/crunch.mp3"></source>
	<source src="/assets/audio/crunch.ogg"></source>
</audio>

<?php
	switch ( c::env() ) {
		case 'local':
			$facebook = c::config()->facebook->{ 'crunchbutton.localhost' };
			break;
		case 'beta':
			$facebook = c::config()->facebook->{ 'beta.crunchr.co' };
			break;
		case 'live':
		default:
			$facebook = c::config()->facebook->{ 'crunchbutton.com' };
			break;
	}
?>
<script type="text/javascript">
	$(function() {
		window.fbAsyncInit = function() {
			console.debug('Init facebook <?=$facebook->app;?>');
			FB.init({
				appId: '<?=$facebook->app;?>',
				cookie: true,
				xfbml: true,
				oauth: true,
				version: 'v2.2'
			});
			var facebookService = angular.element('html').injector().get('FacebookService');
			FB.Event.subscribe('auth.statusChange', facebookService.processStatus);
		};

		(function(d, s, id) {
		var js, fjs = d.getElementsByTagName(s)[0];
		if (d.getElementById(id)) return;
		js = d.createElement(s); js.id = id;
		js.src = '//connect.facebook.com/en_US/sdk<?=strpos($_SERVER['__HTTP_HOST'],'localhost') !== false ? '/debug' : ''?>.js';
		fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));
	});


</script>

<? if ($_SERVER['__HTTP_HOST'] == 'crunchbutton.com') : ?>
	<script>
		(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
		ga('create', 'UA-36135548-1', 'crunchbutton.com');
		ga('require', 'ecommerce', 'ecommerce.js');
		ga('require', 'displayfeatures');
		ga('send', 'pageview');
	</script>
<? endif ; ?>