<!doctype html>
<html>
<head>
<title><?=$this->title ? $this->title : 'Crunchbutton'?></title>
<meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<link rel="apple-touch-icon-precomposed" href="/assets/images/appicon.png">

<link rel="stylesheet" type="text/css" href="/assets/css/landing.css">
<link rel="shortcut icon" href="/favicon.ico">

<script type="application/x-javascript">addEventListener("touchstart",function(){}); addEventListener('load', function(event) {setTimeout(scrollTo, 80, 0, 1);}, false);</script>
</head>

<body>
	<div class="wrapper">
		<div class="body">
			<div class="content">
				<div class="main-content">
					<div class="main-content-item">
						<?=$this->content?>
					</div>
				</div>
			</div>
		</div>
		<div class="divider"></div>
	</div>
</body>
</html>