<?php 
$admins = $this->admins;
?>
<?php if (!$admins->count()) { ?>
	No results found
<?php } else { ?>
	<table class="table table-normal">
		<thead>
			<td>Name</td>
			<td>Login</td>
			<td>Group(s)</td>
			<td>Phone</td>
			<td>Txt</td>
			<td>Email</td>
			<td></td>
		</thead>
		<?php foreach ( $admins as $admin ) { ?>
			<tr class="<?php echo ( $admin->active ) ? '' : 'inactive'; ?>">
				<td><?php echo $admin->name;?> </td>
				<td><?php echo $admin->login;?> </td>
				<td><?php echo $admin->groups2str(); ?></td>
				<td><?php echo $admin->phone; ?></td>
				<td><?php echo $admin->txt; ?></td>
				<td><?php echo $admin->email; ?></td>
				<td style="width:280px;">
					<a href="/permissions/users/permissions/<?php echo $admin->id_admin; ?>" class="btn btn-blue"><i class="icon-unlock"></i> Permissions</a>
					
					<a style="margin:0 5px;" href="/permissions/users/<?php echo $admin->id_admin; ?>" class="btn btn-green"><i class="icon-edit"></i> Edit</a>
					
					<?php if( $admin->active ) { ?>
						<button data-id="<?php echo $admin->id_admin; ?>" class="btn admin-user-inactive btn-red"><i class="icon-trash"></i> Make Inactive</button>
					<?php } else { ?>
						<button data-id="<?php echo $admin->id_admin; ?>" class="btn admin-user-active btn-default"><i class="icon-trash"></i> Make Active</button>
					<?php } ?>
				</td>
			</tr>
		<?php } ?>
	</table>
<?php } ?>