<?
	$this->title = 'Permissions';
	$this->titleicon = 'lock';
	$this->titleLink = '/permissions/users';

	$this->title2 = 'Users';
	$this->title2icon = 'user';

	$admin = $this->admin;

	$_permissions = new Crunchbutton_Admin_Permission();
?>
<div class="container-fluid padded">
	<div class="row-fluid">
		<div class="span6">

	<div class="box">
			<div class="box-header">
				<span class="title">Required</span>
			</div>
			<div class="box-content ">
				<ul class="box-list">
						<li>
							<span>Name</span>
							<span class="pull-right">
								<input type="text" name="name" maxlength="40" id="name" value="<?php echo $admin->name; ?>" />
							</span>
						</li>
					<li>
						<span>Login</span>
						<span class="pull-right">
							<input type="text" name="login" <?php if( $admin->id_admin ) { echo 'readonly="readonly"'; } ?> maxlength="40" id="login" value="<?php echo $admin->login; ?>" />
						</span>
					</li>
					<li>
						<span>Password</span>
						<span class="pull-right">
							<input type="text" name="password" maxlength="250" id="password" value="" />
						</span>
						<?php if( $admin->id_admin ){ ?>
							<div class="note">Leave it blank if you don't want to change it!</div>
						<?php } ?>
					</li>
					<li>
						<label>Group(s)</label>
						<span>
							<select id="id_group" class="chzn-select" multiple name="id_group" data-placeholder="Choose a group" style="width:100%;">
								<? foreach (Crunchbutton_Promo_Group::q('SELECT * FROM `group` ORDER BY name') as $group) { ?>
									<option <?php if( $admin->id_admin && $admin->hasGroup( $group->id_group ) ){ echo 'selected="selected"'; } ?> value="<?=$group->id_group?>"><?=$group->name?></option>
								<? } ?>
							</select>
						</span>
					</li>

				</ul>
			</div>
		</div>

		<div class="box">
				<div class="box-header">
					<span class="title">Optional</span>
				</div>
				<div class="box-content ">
					<ul class="box-list">

						<li>
							<span>Phone #</span>
							<span class="pull-right">
								<input type="text" name="phone" maxlength="12" id="phone" value="<?php echo $admin->phone; ?>" />
							</span>
						</li>
						<li>
							<span>Text (sms)</span>
							<span class="pull-right">
								<input type="text" name="txt" maxlength="12" id="txt" value="<?php echo $admin->txt; ?>" />
							</span>
						</li>
						<li>
							<span class="pull-right">
								<input type="text" name="testphone" maxlength="12" id="testphone" value="<?php echo $admin->testphone; ?>" />
							</span>
							<span>Phone # for Receiving Error Calls</span>
							<div class="note">Only for test!</div>

						</li>
						<li>
							<span>Email</span>
							<span class="pull-right">
								<input type="text" name="email" maxlength="255" id="email" value="<?php echo $admin->email; ?>" />
							</span>
						</li>
						<?php
						$payment_type = $admin->payment_type();
						$using_pex = ( intval( $payment_type->using_pex ) ? intval( $payment_type->using_pex ) : 0 );
						?>
						<li>
							<span>Using Pex</span>
							<span class="pull-right">
								<select id="using_pex" name="using_pex" class="uniform">
									<option <?php if( $using_pex == 0 ) { echo 'selected="selected"'; } ?> value="0">No</option>
									<option <?php if( $using_pex == 1 ) { echo 'selected="selected"'; } ?> value="1">Yes</option>
								</select>
							</span>
						</li>
						<li>
							<span>Timezone</span>
							<span class="pull-right">
								<select id="timezone" name="timezone" class="uniform">
									<option <?php if( $admin->timezone == 'America/New_York' ) { echo 'selected="selected"'; } ?> value="America/New_York">Eastern (America/New_York)</option>
									<option <?php if( $admin->timezone == 'America/Chicago' ) { echo 'selected="selected"'; } ?> value="America/Chicago">Central (America/Chicago)</option>
									<option <?php if( $admin->timezone == 'America/Denver' ) { echo 'selected="selected"'; } ?> value="America/Denver">Mountain (America/Denver)</option>
									<option <?php if( $admin->timezone == 'America/Los_Angeles' ) { echo 'selected="selected"'; } ?> value="America/Los_Angeles">Pacific (America/Los_Angeles)</option>
								</select>
							</span>
						</li>
					</ul>
				</div>
			</div>

		<div class="box">
			<div class="box-header">
				<span class="title">Save</span>
			</div>
			<div class="box-content ">
				<ul class="box-list">
					<li class="input">
						<button type="submit" class="btn btn-green admin-save"><i class="icon-save"></i> Save </button>
					</li>
				</ul>
			</div>
		</div>

	</div>

	<div class="span6">

			<?php if( $admin->id_admin ) {

			$notifications = $admin->getNotifications();

			?>
				<div class="box">
				<div class="box-header">
					 <span class="title">
					 Notifications
					 </span>
				</div>
				<div class="box-content padded">
					 	<ul>
							<?php
							if( $notifications->count() > 0 ){
							foreach( $notifications as $notification ) { ?>
								<li>
									<?php if( $notification->active == 1 ) { ?>
										<span class="label label-green"> Active </span>
									<?php } else { ?>
										<span class="label label-grey"> Inactive </span>
									<?php } ?> <?php echo $notification->type; ?> : <?php echo $notification->value; ?>
								</li>
							<?php }
							} ?>
						</ul>
						<?php if( $admin->id_admin ){ ?>
						<div class="padded">
							<a href="/permissions/users/notifications/<?php echo $admin->id_admin; ?>" class="btn btn-blue"><i class="icon-bullhorn"></i> Edit Notifications of this user</a>
						</div>
						<?php } ?>
				</div>
		 </div>

		 <?php } ?>

		<?php if( $admin->id_admin ) {

		$userPermissions = $admin->getPermissionsByUser();
		$userPermissions = Crunchbutton_Admin_Permission::groupedPermissions( $userPermissions );


			?>
				<div class="box">
				<div class="box-header">
					 <span class="title">
					 User-level Permissions
					 </span>
				</div>
				<div class="box-content padded">
					 	<ul>
							<?php
							if( count( $userPermissions ) > 0 ){
							foreach( $userPermissions as $permission ) { ?>
								<li>
										<?php
											echo $permission[ 'description' ];
											if( $permission[ 'elements' ] ){
												?>
												&nbsp;<br/><span class="note"><?php echo join( ', ', $permission[ 'elements' ] ); ?></span>
												<?php
											}
										?>
								</li>
							<?php } } ?>
						</ul>
						<?php if( $admin->id_admin ){ ?>
						<div class="padded">
							<a href="/permissions/users/permissions/<?php echo $admin->id_admin; ?>" class="btn btn-blue"><i class="icon-unlock"></i> Edit Permissions of this user</a>
						</div>
						<?php } ?>
				</div>
		 </div>

			<?php


		$groups = $admin->groups();
		if( $groups->count() > 0 ){
			foreach( $groups as $group ){
				$groupPermissions = $group->permissions();
				$groupPermissions = Crunchbutton_Admin_Permission::groupedPermissions( $groupPermissions );
				?>
				<div class="box">
				<div class="box-header">
					 <span class="title">
					 Group-level Permissions: "<?php echo $group->name ?>"
					 </span>
				</div>
				<div class="box-content padded">
					 	<ul>
							<?php
							if( count( $groupPermissions ) > 0 ){
							foreach( $groupPermissions as $permission ) { ?>
								<li>
										<?php
											echo $permission[ 'description' ];
											if( $permission[ 'elements' ] ){
												?>
												&nbsp;<br/><span class="note"><?php echo join( ', ', $permission[ 'elements' ] ); ?></span>
												<?php
											}
										?>
								</li>
							<?php } } ?>
						</ul>
						<div class="padded">
						<a href="/permissions/groups/<?php echo $group->id_group; ?>" class="btn btn-green"><i class="icon-group"></i> View Group</a>
					</div>
				</div>
		 	</div>
				<?php

			}
		}

		?>


		<?php } ?>


</div>
<script>

$(function() {
	$(document).on('click', '.admin-save', function() {
		sendForm();
	} );
});

var processing = false;

function sendForm(){

	if( processing ){
		return;
	}

	var name = $.trim( $( '#name' ).val() );
	var phone = $.trim( $( '#phone' ).val() );
	var txt = $.trim( $( '#txt' ).val() );
	var email = $.trim( $( '#email' ).val() );
	var testphone = $.trim( $( '#testphone' ).val() );
	var timezone = $.trim( $( '#timezone' ).val() );
	var login = $.trim( $( '#login' ).val() );
	var password = $.trim( $( '#password' ).val() );
	var id_group = $.trim( $( '#id_group' ).val() );
	var using_pex = $.trim( $( '#using_pex' ).val() );
	console.log('id_group',id_group);
	if( name == '' ){
		alert( 'Please type a name!' );
		$( '#name' ).focus();
		return;
	}
	if( login == '' ){
		alert( 'Please type a login!' );
		$( '#login' ).focus();
		return;
	}

	<?php if( !$admin->id_admin ) { ?>

		if( login == '' ){
			alert( 'Please type a password!' );
			$( '#password' ).focus();
			return;
		}

	<?php } ?>

	var data = { 	'name' : name,
								'phone' : phone,
								'txt' : txt,
								'email' : email,
								'testphone' : testphone,
								'timezone' : timezone,
								'login' : login,
								'password' : password,
								'id_group' : id_group,
								'using_pex' : using_pex
							};

	processing = true;

	$( '.admin-save' ).html( '<i class="icon-spinner icon-spin"></i> Please wait' );

	var url = App.service + 'permissions/users/<?php echo $admin->id_admin; ?>';
	$.ajax({
		type: "POST",
		dataType: 'json',
		data: data,
		url: url,
		success: function( json ) {
			processing = false;
			if( json.error ){
				if( json.error == 'login' ){
					alert( 'This login is already in use!' );
					$( '#login' ).focus();
					$( '.admin-save' ).html( '<i class="icon-save"></i> Save ' );
				} else {
					alert( 'Error at saving the user!' );
					$( '.admin-save' ).html( '<i class="icon-save"></i> Save ' );
				}
			} else {
				alert( 'User saved!' );
				location.href = '/permissions/users/' + json.success;
			}
		},
		error: function( ){
			processing = false;
			alert( 'Error at saving the user!' );
			$( '.admin-save' ).html( '<i class="icon-save"></i> Save ' );
		}
	});
}
</script>