<?
	$this->title = 'Permissions';
	$this->titleicon = 'lock';
	$this->titleLink = '/permissions/users';
	
	$this->title2 = 'Users';
	$this->title2icon = 'user';

	$admin = $this->admin;

	$_permissions = new Crunchbutton_Admin_Permission();
?>
<div class="container-fluid padded">
	<div class="row-fluid">
		<div class="span6">
			<div class="box">
				<div class="box-header">
					<span class="title">Admin user</span>
				</div>
				<div class="box-content ">
					<ul class="box-list">
						<li>
							<span>Name</span>
							<span class="pull-right">
								<input type="text" name="name" maxlength="40" id="name" value="<?php echo $admin->name; ?>" />
							</span>
						</li>
						<li>
							<span>Phone</span>
							<span class="pull-right">
								<input type="text" name="phone" maxlength="12" id="phone" value="<?php echo $admin->phone; ?>" />
							</span>
						</li>
						<li>
							<span>Text (sms)</span>
							<span class="pull-right">
								<input type="text" name="txt" maxlength="12" id="txt" value="<?php echo $admin->txt; ?>" />
							</span>
						</li>
						<li>
							<span>Email</span>
							<span class="pull-right">
								<input type="text" name="email" maxlength="255" id="email" value="<?php echo $admin->email; ?>" />
							</span>
						</li>
						<li>
							<span>Test phone</span>
							<span class="pull-right">
								<input type="text" name="testphone" maxlength="12" id="testphone" value="<?php echo $admin->testphone; ?>" />
							</span>
						</li>
						<li>
							<span>Timezone</span>
							<span class="pull-right">
								<select id="timezone" name="timezone" class="uniform">
									<option <?php if( $admin->timezone == 'America/New_York' ) { echo 'selected="selected"'; } ?> value="America/New_York">Eastern (America/New_York)</option>
									<option <?php if( $admin->timezone == 'America/Chicago' ) { echo 'selected="selected"'; } ?> value="America/Chicago">Central (America/Chicago)</option>
									<option <?php if( $admin->timezone == 'America/Denver' ) { echo 'selected="selected"'; } ?> value="America/Denver">Mountain (America/Denver)</option>
									<option <?php if( $admin->timezone == 'America/Los_Angeles' ) { echo 'selected="selected"'; } ?> value="America/Los_Angeles">Pacific (America/Los_Angeles)</option>
								</select>
							</span>
						</li>
					</ul>
				</div>
			</div>

			<div class="box">
				<div class="box-header">
					<span class="title">Save</span>
				</div>
				<div class="box-content ">
					<ul class="box-list">
						<li class="input">
							<button type="submit" class="btn btn-green admin-save"><i class="icon-save"></i> Save </button> 
						</li>
					</ul>
				</div>
			</div>

	</div>

	<div class="span6">
		
		<div class="box">
			<div class="box-header">
				<span class="title">Access</span>
			</div>
			<div class="box-content ">
				<ul class="box-list">
					<li>
						<span>Login</span>
						<span class="pull-right">
							<input type="text" name="login" <?php if( $admin->id_admin ) { echo 'readonly="readonly"'; } ?> maxlength="40" id="login" value="<?php echo $admin->login; ?>" />
						</span>
					</li>
					<li>
						<span>Password</span>
						<span class="pull-right">
							<input type="text" name="password" maxlength="250" id="password" value="" />
						</span>
						<?php if( $admin->id_admin ){ ?>
							<div class="note">Leave it blank if you don't want to change it!</div>
						<?php } ?>
					</li>
					<li>
						<label>Group(s)</label>
						<span>
							<select id="id_group" class="chzn-select" multiple name="id_group" data-placeholder="Choose a group" style="width:100%;">
								<? foreach (Crunchbutton_Promo_Group::q('SELECT * FROM `group` ORDER BY name') as $group) { ?>
									<option <?php if( $admin->id_admin && $admin->hasGroup( $group->id_group ) ){ echo 'selected="selected"'; } ?> value="<?=$group->id_group?>"><?=$group->name?></option>
								<? } ?>
							</select>
						</span>
					</li>
					<?php if( $admin->id_admin ){ ?>
					<li>
						<a href="/permissions/users/permissions/<?php echo $admin->id_admin; ?>" class="btn btn-blue"><i class="icon-unlock"></i> Edit Permissions of this user</a>
					</li>
					<?php } ?>
				</ul>
			</div>
		</div>

		<?php if( $admin->id_admin ) { ?>
		<div class="accordion" id="accordion">
		<?php 

		$userPermissions = $admin->getPermissionsByUser();

		if( $userPermissions->count() > 0 ){
			?>
			<div class="accordion-group">
				<div class="accordion-heading">
					<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse<?php echo $admin->id_admin; ?>">
						Permissions of the user
					</a>
				</div>
				<div id="collapse<?php echo $admin->id_admin; ?>" class="accordion-body collapse" style="height: 0px;">
					<div class="accordion-inner">
						<ul>
							<?php foreach( $userPermissions as $permission ) { ?>
								<li>
										<?php 
											$info = $_permissions->getPermissionInfo( $permission->permission ); 
											if( $info ){
												echo $info[ 'description' ];
											}
										?>
										&nbsp;<span class="note"><?php echo $permission->permission ?></span>
								</li>
							<?php } ?>
						</ul>
					</div>
				</div>
			</div>
			<?php
		}

		$groups = $admin->groups();
		if( $groups->count() > 0 ){
			foreach( $groups as $group ){
				$groupPermissions = $group->permissions();
				?>
			<div class="accordion-group">
				<div class="accordion-heading">
					<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse<?php echo str_replace( ' ' , '', $group->name); ?>">
						Permissions of the group "<?php echo $group->name ?>"
					</a>
				</div>
				<div id="collapse<?php echo str_replace( ' ' , '', $group->name); ?>" class="accordion-body collapse" style="height: 0px;">
					<div class="accordion-inner">
						<ul>
							<?php foreach( $groupPermissions as $permission ) { ?>
								<li>
										<?php 
											$info = $_permissions->getPermissionInfo( $permission->permission ); 
											if( $info ){
												echo $info[ 'description' ];
											}
										?>
										&nbsp;<span class="note"><?php echo $permission->permission ?></span>
								</li>
							<?php } ?>
						</ul>
					</div>
				</div>
			</div>
				<?php

			}
		}

		?><!--
			<div class="accordion-group">
				<div class="accordion-heading">
					<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
						Collapsible Group Item #2
					</a>
				</div>
				<div id="collapseTwo" class="accordion-body collapse" style="height: 0px;">
					<div class="accordion-inner">
						Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
					</div>
				</div>
			</div>
			<div class="accordion-group">
				<div class="accordion-heading">
					<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
						Collapsible Group Item #3
					</a>
				</div>
				<div id="collapseThree" class="accordion-body in collapse" style="height: auto;">
					<div class="accordion-inner">
					<ul >
							<li>
								<span>Login</span>
								<span class="pull-right">
									<input type="text" name="login" <?php if( $admin->id_admin ) { echo 'readonly="readonly"'; } ?> maxlength="40" id="login" value="<?php echo $admin->login; ?>" />
								</span>
							</li>
						</ul>
					</div>
				</div>
			</div>-->
		</div>

		<?php } ?>


	</div>
</div>
<script>

$(function() {
	$(document).on('click', '.admin-save', function() {
		sendForm();
	} );
});

var processing = false;

function sendForm(){

	if( processing ){
		return;
	}

	var name = $.trim( $( '#name' ).val() );
	var phone = $.trim( $( '#phone' ).val() );
	var txt = $.trim( $( '#txt' ).val() );
	var email = $.trim( $( '#email' ).val() );
	var testphone = $.trim( $( '#testphone' ).val() );
	var timezone = $.trim( $( '#timezone' ).val() );
	var login = $.trim( $( '#login' ).val() );
	var password = $.trim( $( '#password' ).val() );
	var id_group = $.trim( $( '#id_group' ).val() );
	if( name == '' ){
		alert( 'Please type a name!' );
		$( '#name' ).focus();
		return;
	}
	if( login == '' ){
		alert( 'Please type a login!' );
		$( '#login' ).focus();
		return;
	}

	<?php if( !$admin->id_admin ) { ?>

		if( login == '' ){
			alert( 'Please type a password!' );
			$( '#password' ).focus();
			return;
		}

	<?php } ?>

	var data = { 	'name' : name, 
								'phone' : phone,
								'txt' : txt,
								'email' : email,
								'testphone' : testphone,
								'timezone' : timezone,
								'login' : login,
								'password' : password,
								'id_group' : id_group
							};
	
	processing = true;
	
	$( '.admin-save' ).html( '<i class="icon-spinner icon-spin"></i> Please wait' );

	var url = App.service + 'permissions/users/<?php echo $admin->id_admin; ?>';
	$.ajax({
		type: "POST",
		dataType: 'json',
		data: data,
		url: url,
		success: function( json ) {
			processing = false;
			if( json.error ){
				if( json.error == 'login' ){
					alert( 'This login is already in use!' );
					$( '#login' ).focus();
					$( '.admin-save' ).html( '<i class="icon-save"></i> Save ' );
				} else {
					alert( 'Error at saving the user!' );
					$( '.admin-save' ).html( '<i class="icon-save"></i> Save ' );
				}
			} else {
				alert( 'User saved!' );
				location.href = '/permissions/users/';
			}
		},
		error: function( ){
			processing = false;
			alert( 'Error at saving the user!' );
			$( '.admin-save' ).html( '<i class="icon-save"></i> Save ' );
		}
	});
}
</script>