<?
	
	$admin = $this->admin;

	$this->title = 'User ' . $admin->name;
	$this->titleicon = 'user';
	$this->titleLink = '/permissions/users/' . $admin->id_admin;
	
	$this->title2 = 'Notifications';
	$this->title2icon = 'bullhorn';

	$notifications = $admin->getNotifications( 'id_admin_notification' );
	 
?>
<!-- content -->
<div class="container-fluid padded">
	 <div class="row-fluid">
			<div class="box">
				<div class="box-header"><span class="title">Add notification for <?php echo $admin->name; ?></span></div>
				 <div class="box-content">
						<div class="row-fluid padded">
							<div class="span4 separate-sections">
								 <input class="span12" name="value" id="value" type="text" value="" placeholder="Number/URL/Email">
							</div>
							<div class="span4 separate-sections">
									<select class="span12" name="type" id="type">
										<option value="fax">Fax</option>
										<option value="sms" selected="selected">Text Message</option>
										<option value="sms-dumb">Text Message (Dumb)</option>
										<option value="email">Email</option>
										<option value="phone">Phone Call</option>
										<option value="url">URL Request</option>
									</select>
							</div>
							<div class="span4 separate-sections">
								 <button class="btn btn-blue notification-save"><i class="icon-save"></i> Save </button> 
							</div>
						</div>
				 </div>
			</div>
			<div class="box">
				 <div class="box-header"><span class="title">Notifications</span></div>
				 <div class="box-content">
					<?php if (!$notifications->count()) { ?>
						No results found
					<?php } else { ?>
						<table class="table table-normal">
							<thead>
								<td>Value</td>
								<td>Type</td>
								<td>Active</td>
								<td>Remove</td>
							</thead>
							<?php foreach ( $notifications as $notification ) { ?>
								<tr>
									<td><?php echo $notification->value;?> <span style="display:none" id="saved_<?php echo $notification->id_admin_notification; ?>" class="label label-green"> <i class="icon-ok"></i> Saved </span> </td>
									<td><?php echo $notification->type;?> </td>
									<td >
										<input class="notification-active" <?php if( $notification->active == 1 ){ echo 'checked="checked"'; } ?> type="checkbox" value="<?php echo $notification->id_admin_notification; ?>" id="active_<?php echo $notification->id_admin_notification; ?>" name="active_<?php echo $notification->id_admin_notification; ?>" />	
									</td>
									<td>
										<button type="button" onclick="AdminNotifications.remove(<?php echo $notification->id_admin_notification; ?>);" class="notification-remove btn btn-small btn-red"><i title="Remove" class="icon-trash"/></button>
									</td>
								</tr>
							<?php } ?>
						</table>
					<?php } ?>
				 </div>
			</div>
	 </div>
</div>
<script type="text/javascript">

$(document).ready( function(){
	$( '.notification-save' ).click( function(){
		AdminNotifications.save();
	} );
	$('.notification-active').iButton({
	  labelOn: '<i class="icon-ok"></i>',
	  labelOff: '<i class="icon-remove"></i>',
	  handleWidth: 30,
	  change: function( checkbox ){
	  	var id_admin_notification = $( checkbox ).val();
	  	var active = ( $( checkbox ).is( ':checked' ) ? '1' : '0' );
	  	AdminNotifications.changeStatus( id_admin_notification, active );
	  }
	});
} );

var AdminNotifications = {};

AdminNotifications.changeStatus = function( id_admin_notification, active ){
	var url = App.service + 'permissions/users/<?php echo $admin->id_admin; ?>/notifications/active';
	$.ajax({
		type: 'POST',
		dataType: 'json',
		data: { 'id_admin_notification' : id_admin_notification, 'active' : active },
		url: url,
		success: function( json ) {
			if( json.success ){
				var id_admin_notification = json.success;
				var saved = $( '#saved_' + id_admin_notification );
				saved.show( function(){
					setTimeout( function(){
						saved.hide();
					}, 1500 );
				} );	
			} else {
				alert( 'Error saving notification status!' );
			}
		},
		error: function( ){
			alert( 'Error saving notification status!' );
		}
	});
};

AdminNotifications.remove = function( id_admin_notification ){
	if( !confirm( 'Confirm remove?' ) ){ return; }
	var url = App.service + 'permissions/users/<?php echo $admin->id_admin; ?>/notifications/remove';
	$.ajax({
		type: 'POST',
		dataType: 'json',
		data: { 'id_admin_notification' : id_admin_notification },
		url: url,
		success: function( json ) {
			if( json.success ){
				alert( 'Notification removed!' );
				location.reload();
			} else {
				alert( 'Error removing notification!' );
			}
		},
		error: function( ){
			alert( 'Error removing notification!' );
		}
	});
};


AdminNotifications.save = function(){

	var value = $( '#value' ).val();
	var type = $( '#type' ).val();

	if( $.trim( value ) == '' ){
		alert( 'Please type a number, URL or email' );
		$( '#value' ).focus();
		return;
	}

	var url = App.service + 'permissions/users/<?php echo $admin->id_admin; ?>/notifications/save';
	$.ajax({
		type: 'POST',
		dataType: 'json',
		data: { 'value' : value, 'type' : type },
		url: url,
		success: function( json ) {
			if( json.success ){
				alert( 'Notification saved!' );
				location.reload();
			} else {
				alert( 'Error saving notification!' );
			}
		},
		error: function( ){
			alert( 'Error saving notification!' );
		}
	});
}

</script>