<?
	$this->title = 'Permissions';
	$this->titleicon = 'lock';
	$this->titleLink = '/permissions/users';
	
	$this->title2 = 'Users';
	$this->title2icon = 'user';

	$admin = $this->admin;
	 
	$_permissions = $this->permissions;
	$_elements = $this->elements;
	 
?>
<div class="container-fluid padded">
	 <div class="row-fluid">
			<div class="span6 ">
				 <h4>
					"<?php echo $admin->name ?>" has these permissions in addition to his group permissions.
				</h4>
				<?php 
					foreach( $_permissions as $permission_group ){ 
						$description = $permission_group[ 'description' ];
						$permissions = $permission_group[ 'permissions' ];
				?>
					 <div class="box">
							<div class="box-header">
								 <span class="title">
								 <?php echo $description; ?>
								 </span>
							</div>
							<div class="box-content ">
								 <ul class="box-list">
								 	<?php
								 		foreach( $permissions as $permission => $meta ){
								 			$description = $meta[ 'description' ];
								 			$type = 'checkbox';
								 			$element = '';
								 			switch ( $meta[ 'type' ] ) {

								 				case 'combo':
								 					$type = 'combo';
								 					$element = $meta[ 'element' ];
								 					break;
								 				
								 				default:
								 					$type = 'checkbox';
								 					break;
								 			};
								 	?>
										<li>
											<label for="<?php echo $permission; ?>">
												<?php if( $type == 'checkbox' ) { 
													$checked = ( $admin->hasPermission( $permission ) ) ? 'checked="checked"' : '' ;
													?>
													<span class="pull-right">
														<input type="checkbox" <?php echo $checked; ?> class="icheck permissions" value="1" name="<?php echo $permission; ?>" id="<?php echo $permission; ?>">
													</span>
												<?php } ?>
												&nbsp;<?php echo $description; ?>
												<span class="note">
													&nbsp;(<?php echo $permission; ?>)
												</span>
												<?php if( $type == 'combo' ) { ?>
													<select id="<?php echo $permission; ?>" class="chzn-select permissions" multiple name="<?php echo $permission; ?>" data-placeholder="Choose" style="width:100%;">
														<?php 
														$elements = $_elements[ $element ];
														foreach ( $elements as $element ) { 
															$value = str_replace( 'ID' , $element->id, $permission);
															$selected = ( $admin->hasPermission( $value ) ) ? 'selected="selected"' : '' ;
															?>
															<option <?php echo $selected; ?> value="<?php echo $value; ?>"><?php echo $element->name; ?></option>
														<? } ?>
													</select>
												<?php } ?>
											</label>
										</li>
									<?php 
										} 
									?>
								 </ul>
							</div>
					 	</div>
				 <?php 
				 	} 
				?>
				<div class="box">
				<div class="box-header">
					 <span class="title">
					 Save
					 </span>
				</div>
				<div class="box-content ">
					 <ul class="box-list">
						<li class="input">
							<button type="submit" class="btn btn-blue admin-save"><i class="icon-save"></i> Save </button> 
						</li>
					 </ul>
				</div>
		 	</div>
			</div>
			<div class="span6">
			<h5>The user has permissions from these groups:</h5>
			<?php 
			$_permissions = new Crunchbutton_Admin_Permission();
			$groups = $admin->groups();
			if( $groups->count() > 0 ){ ?>
				
			<?php 
			foreach( $groups as $group ){
				$groupPermissions = $group->permissions();
				?>

				<div class="box">
				<div class="box-header">
					 <span class="title">
					 Group-level Permissions: "<?php echo $group->name ?>"
					 </span>
				</div>
				<div class="box-content padded">
					 <ul>
							<?php foreach( $groupPermissions as $permission ) { ?>
								<li>
										<?php 
											$info = $_permissions->getPermissionInfo( $permission->permission ); 
											if( $info ){
												echo $info[ 'description' ];
											}
										?>
										&nbsp;<span class="note"><?php echo $permission->permission ?></span>
								</li>
							<?php } ?>
						</ul>
											<div class="padded">
						<a href="/permissions/groups/<?php echo $group->id_group; ?>" class="btn btn-green"><i class="icon-group"></i> View Group</a>
					</div>
				</div>
		 	</div>


				<?php

			} ?>

			<?php
		}

		?>
			</div>
	 </div>

</div>
<script type="text/javascript">
	
	$(function() {
		$(document).on('click', '.admin-save', function() {
			sendForm();
		} );
	});

	function sendForm(){
		
		var data = {};

		$('.permissions').each( function(){ 
			var el = $( this );
			var type = null;
			if( el.is( 'input' ) ){
				type = el.attr( 'type' );
				if( type == 'checkbox' ){
					if( el.is( ':checked' ) ){
						data[ el.attr( 'name' ) ] = 1;
					}
				}
			} else if( el.is( 'select' ) ){
				var options = el.val();
				$( options ).each( function( index, val ){
					data[ val ] = 1;
				} );
			}

		} );
		
		var url = App.service + 'permissions/users/<?php echo $admin->id_admin; ?>/permissions';
		$.ajax({
			type: 'POST',
			dataType: 'json',
			data: { permissions : data },
			url: url,
			success: function( json ) {
				processing = false;
				if( json.success ){
					alert( 'Permssions saved!' );
					location.reload();
				} else {
					alert( 'Error saving permissions!' );
				}
			},
			error: function( ){
				processing = false;
				alert( 'Error saving permissions!' );
				$( '.admin-save' ).html( '<i class="icon-save"></i> Save ' );
			}
		});

	}


</script>
