<div class="top-pad"></div>

<div class="content-padding">

	<h1 class="title box-title"><i class="fa fa-link"></i>Chains</h1>

	<div class="support-boxes">

		<div class="support-box-wrap box-content2">
			<div class="support-box-wrap-header">
				<h1><i class="fa fa-link"></i>Chains</h1>
				<div class="divider"></div>
			</div>

			<div class="box-content-table">
				<table>
					<tr><td><a href="/chains/list">List</a></td></tr>
					<tr><td><a href="/chain/">Add New</a></td></tr>
				</table>
			</div>
		</div>

		<div class="support-box-wrap box-content2">
			<div class="support-box-wrap-header">
				<h1><i class="fa fa-link"></i>Chains x Community</h1>
				<div class="divider"></div>
			</div>

			<div class="box-content-table">
				<table>
					<tr><td><a href="/chain/communities/">List</a></td></tr>
					<tr><td><a href="/chain/community">Add New</a></td></tr>
				</table>
			</div>
		</div>

	</div>

</div>
