<?
	$this->title = 'Permissions';
	$this->titleicon = 'lock';
?>
<!-- content -->
<div class="container-fluid padded">
	<div class="row-fluid">
		<div class="box padded">
			<?php if (c::admin()->permission()->check(['global','permissions-all', 'permission-groups'])) { ?>
				<a class="btn btn-blue" href="https://cockpit.la/groups"> <i class="icon-group"> </i>Groups</a>
				&nbsp;
			<?php } ?>
			<?php if (c::admin()->permission()->check(['global','permissions-all', 'permission-users'])) { ?>
				<a class="btn btn-green" href="https://cockpit.la/staff"> <i class="icon-user"></i> Users</a>
				&nbsp;
			<?php } ?>
		</div>
	</div>
</div>