<!doctype html>
<html>
<head>
<title><?=$this->title ? $this->title : 'Crunchbutton'?></title>
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale = 1.0,maximum-scale = 1.0">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<link rel="shortcut icon" href="/favicon-admin.ico">

<style type="text/css">
	@font-face {
	    font-family: 'Museo Slab';
	    src: url('/assets/fonts/museo_slab_500-webfont.eot');
	    src: url('/assets/fonts/museo_slab_500-webfont.eot?#iefix') format('embedded-opentype'),
	         url('/assets/fonts/museo_slab_500-webfont.woff') format('woff'),
	         url('/assets/fonts/museo_slab_500-webfont.ttf') format('truetype'),
	         url('/assets/fonts/museo_slab_500-webfont.svg#MuseoSlab500Regular') format('svg');
	    font-weight: normal;
	    font-style: normal;
	}

	body, table, td, tr, p, h1, h2, h3, h4, button {
		margin: 0;
		padding: 0;
		border: 0;
		font-family: Museo Slab, Helvetica, Lucida Grande, Arial, sans-serif;
	}
	
input[type="submit"]:focus, input[type="button"]:focus, input[type="text"]:focus, button, :focus {
	outline : none;
}
input[type="submit"]::-moz-focus-inner, input[type="button"]::-moz-focus-inner, button::-moz-focus-inner {
	border : 0;
}

	
	@media(min-width:500px) {
		body {
			font-size: 12px;
		}
	
	}
	@media(max-width:499px) {
		body {
			font-size: 10px;
		}
	}
	
	.control {
		background-image: -moz-linear-gradient( 90deg, rgb(203,203,203) 0%, rgb(232,232,232) 100%);
		background-image: -webkit-linear-gradient( 90deg, rgb(203,203,203) 0%, rgb(232,232,232) 100%);
		background-image: -ms-linear-gradient( 90deg, rgb(203,203,203) 0%, rgb(232,232,232) 100%);
		box-shadow: 0px 1px 0px 0px rgb( 150, 150, 150 );
	}
	
	.control .buttons {
		display: table-cell;
		vertical-align: middle;
		text-align: right;
		width: 100%;
	}
	
	.content {
		
	}

	.wrap {
		padding: .5em;
		max-width: 740px;
		margin: 0 auto;
	}
	.header {
		background-color: #f97e5c;
		color: #fff;
		font-size: 1.7em;
		padding: .5em;
	}
	.divider {
		clear: both;
	}
	.divider.dots {
		border-top: 1px solid #eeede7;
	}
	
	.restaurant-name {
		float: left;
	}

	.order-id {
		float: right;
	}
	
	.order-icon {
		font-size: 1.2em;
		display: table-cell;
		width: 3.2em;
		text-align: center;
		vertical-align: middle;
	}
	.order-info {
		display: table-cell;
		font-size: 1.3em;
		vertical-align: middle;
		line-height: 1.4em;
	}
	.order-item-block, .order-item-block-big {
		display: table;
		float: left;
		width: 15em;
		margin: 1em 0 1em 0;
	}
	.order-item-block-big{
		width: 30em;
	}
	.order-map-block {
		width: 100%;
		margin-top: 0;
		
	}
	
	.order-map {
		width: 100%;
		height: 15em;
		background-size:cover !important;
	}
	
	[class*='icon-'] {
		display: inline-block;
	}
	
	a {
		color: #d74924;
		text-decoration: underline;
	}

	
	.order-comment-arrow {
		width: 0;
		height: 0;
		border-left: 7px solid transparent;
		border-right: 7px solid transparent;
		border-bottom: 7px solid #00957f;
		margin-left: 1.2em;
	}
	
	.order-comment {
		background: #00957f;
		color: #fff;
		padding: .9em .9em .8em 1em;
		border-radius: 4px;
		margin-bottom: .8em;
	}

	.icon-support {
		background: url(http://dev.crunchr.co/assets/images/micro/icon-support.svg) no-repeat;
		background-position: top center;
		width: 2.4em;
		height: 2.8em;
		background-size: 100%;
	}
	
	.icon-chef {
		background: url(http://dev.crunchr.co/assets/images/micro/icon-chef.svg) no-repeat;
		background-position: top center;
		width: 2.0em;
		height: 2.6em;
		background-size: 100%;
	}
	
	.icon-user {
		background: url(http://dev.crunchr.co/assets/images/micro/icon-user.svg) no-repeat;
		background-position: top center;
		width: 1.9em;
		height: 2.4em;
		background-size: 100%;
	}
	
	.icon-delivery {
		background: url(http://dev.crunchr.co/assets/images/micro/icon-delivery.svg) no-repeat;
		background-position: top center;
		width: 2.2em;
		height: 1.6em;
		background-size: 100%;
	}
	
	.icon-card {
		background: url(http://dev.crunchr.co/assets/images/micro/icon-card.svg) no-repeat;
		background-position: top center;
		width: 2.3em;
		height: 1.6em;
		background-size: 100%;
	}
	
	.icon-clock {
		background: url(http://dev.crunchr.co/assets/images/micro/icon-clock.svg) no-repeat;
		background-position: top center;
		width: 1.6em;
		height: 2em;
		background-size: 100%;
	}
	
	.icon-timer {
		background: url(http://dev.crunchr.co/assets/images/micro/icon-timer.svg) no-repeat;
		background-position: top center;
		width: 1.6em;
		height: 2.3em;
		background-size: 100%;
	}
	
	.icon-map-home {
		background: url(http://dev.crunchr.co/assets/images/micro/icon-map-home.svg) no-repeat;
		background-position: top center;
		width: 1.6em;
		height: 2.41em;
		background-size: 100%;
	}
	
	.icon-map-restaurant {
		background: url(http://dev.crunchr.co/assets/images/micro/icon-map-restaurant.svg) no-repeat;
		background-position: top center;
		width: 1.6em;
		height: 2.41em;
		background-size: 100%;
	}
	
	.icon-cash {
		background: url(http://dev.crunchr.co/assets/images/micro/icon-cash.svg) no-repeat;
		background-position: top center;
		width: 2.1em;
		height: 1.6em;
		background-size: 100%;
	}
	
	.icon-takeout {
		background: url(http://dev.crunchr.co/assets/images/micro/icon-takeout.svg) no-repeat;
		background-position: top center;
		width: 1.5em;
		height: 2.0em;
		background-size: 100%;
	}
	
	.icon-phone {
		background: url(http://dev.crunchr.co/assets/images/micro/icon-phone.svg) no-repeat;
		background-position: top center;
		width: 1.4em;
		height: 1.4em;
		background-size: 100%;
		margin-top: .2em;
	}
	
	.icon-notes {
		background: url(http://dev.crunchr.co/assets/images/micro/icon-notes.svg) no-repeat;
		background-position: top center;
		width: 1.9em;
		height: 1.6em;
		background-size: 100%;
	}
	
	.icon-credit {
		background: url(http://dev.crunchr.co/assets/images/micro/icon-credit.svg) no-repeat;
		background-position: top center;
		width: 2.5em;
		height: 1.9em;
		background-size: 100%;
	}

	td {
		border: 0;
		padding: .5em;
	}

	.fooditem {
		border-bottom: 1px solid #999;
	}
	
	.topitem {
		border-bottom: 2px solid #999;
	}
	
	.control .wrap {
		width: 100%;
		box-sizing: border-box;
		display: table;
	}
	
	.control .message {
		font-size: 1.3em;
		display: table-cell;
		vertical-align: middle;
		text-shadow:1px 1px 0px #fff;
		white-space:nowrap;
	}

	.button {
		padding: .3em 1em .3em 1em;
		margin: .2em 0 .2em .6em;
		color: #fff;
		cursor: pointer;
		font-size: 1.4em;
		font-weight: bold;
		border: 1px solid rgba(0,0,0,.2);
		box-shadow: 0px 0px 3px rgba(0,0,0,.3);
		text-shadow: 1px 1px 0 rgba(0,0,0,.4);
	}
	
	.button:active {
		box-shadow: 0px 0px 1px rgba(0,0,0,.3);
	}
	
	.button-yes {
		background: #7bca72;
		border-radius: 4px;
	}
	
	.button-no {
		background: #dc534b;
		border-radius: 4px;
	}
	
	.order-status-delivered .status-control:not(.control-delivered) {
		display: none !important;
	}
	
	.order-status-pickedup .status-control:not(.control-pickedup) {
		display: none !important;
	}
	
	.order-status-rejected .status-control:not(.control-rejected) {
		display: none !important;
	}
	
	.order-status-accepted .status-control:not(.control-accepted) {
		display: none !important;
	}
	
	.order-status-accepted-other .status-control:not(.control-accepted-other) {
		display: none !important;
	}
	
	.order-status-none .status-control:not(.control-accept-reject) {
		display: none !important;
	}
	
	.order-status-init .status-control {
		display: none !important;
	}

	
	.loader-wrap {
		position: fixed;
		bottom: -10px;
		height: 0;
		background: rgba(0,0,0,0);
		z-index: 99;
		overflow: hidden;

		-webkit-transition: background .2s;
		   -moz-transition: background .2s;
		    -ms-transition: background .2s;
		     -o-transition: background .2s;
		        transition: background .2s;
	}
	
	.loader-frame {
		border-radius: 10px;
		background: rgba(0,0,0,.5);
		padding: 2em;
		width: 8em;
		height: 8em;
		margin: 0 auto;
		margin-top: 16em;
		opacity: .2;
		
		-webkit-transform:translate3d(0,0,0);

		-webkit-transform: scale(3);
		   -moz-transform: scale(3);
		    -ms-transform: scale(3);
		     -o-transform: scale(3);
		        transform: scale(3);
		
		-webkit-transition: all .1s;
		   -moz-transition: all .1s;
		    -ms-transition: all .1s;
		     -o-transition: all .1s;
		        transition: all .1s;
	}

	.loader {
		opacity: 1;
		background: url(/assets/images/ajax_loader_orange_512.gif);
		height: 8em;
		width: 8em;
		background-size: cover;
	}	

	body.loading {
		overflow: hidden;
		
	}
	
	body.loading .loader-frame {
		-webkit-transform: scale(1);
		   -moz-transform: scale(1);
		    -ms-transform: scale(1);
		     -o-transform: scale(1);
		        transform: scale(1);
		opacity: 1;
	}
	
	body.loading .loader-wrap {
		top: 0;
		left: 0;
		bottom: 0;
		right: 0;
		width: 100%;
		height: 100%;
		background: rgba(0,0,0,.5);
	}

	.order-list-item a{
		color: #FFF;
		text-decoration: none;
	}
	.order-list-item{
		color: #FFF;
		font-size: 1.1em;
		padding:0.5em;
		-webkit-border-radius: .3em;
		-moz-border-radius: .3em;
		border-radius: .3em;
		margin: .5em 0;
	}
		.new{ background: #e0463e; }
		.accepted{ background: #1ebda0; }
		.pickedup{ background: #505050; }
		.delivered{ background: #6d6d6d; }
		.other{ background: #6d6d6d; }

	.order-list-date{
		display: table;
		float: left;
		width: 4em;
		font-size: .9em;
		margin-right: 1em;
		opacity:0.9;
	}
		.order-list-date .day{
			font-size: 1em;
			opacity:0.7;
		}
		.order-list-date .hour{
			font-size: 2em;
			font-weight: bold;
			text-align: right;
		}
		.order-list-date .ampm{
			font-size: .8em;
			text-align: right;
			text-transform: uppercase;
		}
	.order-list-customer-info{
		display: table;
		float: left;
	}
		.order-list-customer-info .restaurant{
			font-weight: bold;
			font-size: 1em;
			line-height: 2em;
		}
			.order-list-customer-info .restaurant a{
				text-decoration: underline;
			}
		.order-list-customer-info .customer{
			font-size:0.9em;
		}
			.other .order-list-customer-info .restaurant{
				font-size: 1.3em;
			}
			.other .order-list-customer-info .customer{
				font-size: 1.2em;
			}
	.order-list-action{
		display: table;
		float: right;
		font-size: 1em;
	}
		.order-list-action .button{
			font-weight: bold;
			border: 1px solid #FFF;
			background: #FFF;
			text-align: center;	
			-webkit-border-radius: .5em;
			-moz-border-radius: .5em;
			border-radius: .5em;
			padding: .6em 1em;
			margin-top: .3em;
			font-size: 1.3em;
			text-shadow: none;
		}
		.new .order-list-action .button{ color:#e0463e; }
		.accepted .order-list-action .button{ color:#1ebda0; }
		.pickedup .order-list-action .button{ color:#505050; }

</style>
</head>


<body>
	<div class="loader-wrap">
		<div class="loader-frame"><div class="loader">asd</div></div>
	</div>
	<div class="control">
		<div class="wrap order-status-init">
			<div class="status-control control-accept-reject">
				<div class="message">Accept this order?</div>
				<div class="buttons">
					<button class="button button-yes button-accept">Yes</button>
					<button class="button button-no button-reject">No</button>
				</div>
			</div>
			<div class="status-control control-rejected">
				<div class="message">You rejected. </div>
				<div class="buttons">
					<button class="button button-yes button-accept">Accept</button>
				</div>
			</div>
			<div class="status-control control-accepted">
				<div class="message">You accepted.</div>
				<div class="buttons">
					<button class="button button-yes button-pickedup">Picked up</button>
					<button class="button button-no button-reject">Cancel</button>
				</div>
			</div>
			<div class="status-control control-accepted-other">
				DO NOT DELIVER. THIS ORDER HAS ALREADY BEEN ACCEPTED BY <span class="delivery-name"></span>.
			</div>
			<div class="status-control control-pickedup">
				<div class="message">You picked up.</div>
				<div class="buttons">
					<button class="button button-yes button-delivered">Delivered</button>
				</div>
			</div>
			<div class="status-control control-pickedup-other">
				This order has been picked up by <span class="delivery-name"></span>.
			</div>
			<div class="status-control control-delivered">
				This order has been delivered by <span class="delivery-name"></span>.
			</div>
			<div class="divider"></div>
		</div>
	</div>
	
	<div class="content">
		<div class="wrap">
			<?=$this->content?>
		</div>
	</div>
</body>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="/assets/js/fastclick.js"></script>

<script>
	$(document).ready(function(){

		<?php if( $this->order->id_order ) { ?>

		var d = <?=json_encode($this->order->deliveryExports())?>;
		var id_admin = '<?=c::admin()->id_admin?>';
		var id_order = '<?=$this->order->id_order?>';
		
		var updateStatus = function(data) {
			console.log(data);
		
			$('.wrap').removeClass('order-status-init order-status-delivered order-status-pickedup order-status-rejected order-status-accepted order-status-accepted-other order-status-none');

			var className, name;

			if (data['delivery-status'].delivered) {
				className = 'order-status-delivered';
				name = data['delivery-status'].delivered.name;

			} else if (data['delivery-status'].pickedup) {
				className = 'order-status-pickedup';
				name = data['delivery-status'].pickedup.name;
		
			} else if (data['delivery-status'].accepted && data['delivery-status'].accepted.id_admin != id_admin) {
				className = 'order-status-accepted-other';
				name = data['delivery-status'].accepted.name;
		
			} else if (data['delivery-status'].accepted && data['delivery-status'].accepted.id_admin == id_admin) {
				className = 'order-status-accepted';
				name = data['delivery-status'].accepted.name;
		
			} else if (data['self-reply'] == 'rejected') {
				className = 'order-status-rejected';

			} else {
				className = 'order-status-none';
			}
			
			$('.wrap').addClass(className);
			$('.delivery-name').html(name);
			
			$('body').removeClass('loading');
		};
		
		$('.button-reject').click(function() {
			makebusy();
			$.post('/api/order/' + id_order + '/delivery-reject', updateStatus,'json');
		});

		$('.button-accept').click(function() {
			makebusy();
			$.post('/api/order/' + id_order + '/delivery-accept', updateStatus,'json');
		});
		
		$('.button-pickedup').click(function() {
			makebusy();
			$.post('/api/order/' + id_order + '/delivery-pickedup', updateStatus,'json');
		});
		
		$('.button-delivered').click(function() {
			makebusy();
			$.post('/api/order/' + id_order + '/delivery-delivered', updateStatus,'json');
		});
	
		updateStatus(d);

		<?php } else { ?>


		$( '.button-list-accept' ).click( function(  ) {
			var id_order = $( this ).attr( 'id_order' );
			makebusy();
			 $.post('/api/order/' + id_order + '/delivery-accept', function(){ location.reload(); },'json'); 
		} );

		$( '.button-list-pickedup' ).click( function() {
			var id_order = $( this ).attr( 'id_order' );
			makebusy();
			 $.post('/api/order/' + id_order + '/delivery-pickedup', function(){ location.reload(); },'json'); 
		} );

		$( '.button-list-delivered' ).click( function() {
			var id_order = $( this ).attr( 'id_order' );
			makebusy();
			 $.post('/api/order/' + id_order + '/delivery-delivered', function(){ location.reload(); },'json'); 
		} );
		

		<?php } ?>

	} );
	var makebusy = function() {
		$('body').addClass('loading');
	};

</script>
</html>