<!doctype html>
<html>
<head>
<title><?=$this->title ? $this->title : 'Crunchbutton'?></title>
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale = 1.0,maximum-scale = 1.0">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<link rel="shortcut icon" href="/favicon-admin.ico">

<style type="text/css">
	@font-face {
	    font-family: 'Museo Slab';
	    src: url('/assets/fonts/museo_slab_500-webfont.eot');
	    src: url('/assets/fonts/museo_slab_500-webfont.eot?#iefix') format('embedded-opentype'),
	         url('/assets/fonts/museo_slab_500-webfont.woff') format('woff'),
	         url('/assets/fonts/museo_slab_500-webfont.ttf') format('truetype'),
	         url('/assets/fonts/museo_slab_500-webfont.svg#MuseoSlab500Regular') format('svg');
	    font-weight: normal;
	    font-style: normal;
	}

	body, table, td, tr, p, h1, h2, h3, h4, button {
		margin: 0;
		padding: 0;
		border: 0;
		font-family: Museo Slab, Helvetica, Lucida Grande, Arial, sans-serif;
	}
	
input[type="submit"]:focus, input[type="button"]:focus, input[type="text"]:focus, button, :focus {
	outline : none;
}
input[type="submit"]::-moz-focus-inner, input[type="button"]::-moz-focus-inner, button::-moz-focus-inner {
	border : 0;
}

	
	@media(min-width:500px) {
		body {
			font-size: 12px;
		}
	
	}
	@media(max-width:499px) {
		body {
			font-size: 10px;
		}
	}
	
	.control {

		background-image: -moz-linear-gradient( 90deg, rgb(203,203,203) 0%, rgb(232,232,232) 100%);
		background-image: -webkit-linear-gradient( 90deg, rgb(203,203,203) 0%, rgb(232,232,232) 100%);
		background-image: -ms-linear-gradient( 90deg, rgb(203,203,203) 0%, rgb(232,232,232) 100%);
		box-shadow: 0px 1px 0px 0px rgb( 150, 150, 150 );


	}
	
	.control .buttons {
		display: table-cell;
		vertical-align: middle;
		text-align: right;
	}
	
	.content {
		
	}

	.wrap {
		padding: .5em;
		max-width: 740px;
		margin: 0 auto;
	}
	.header {
		background-color: #f97e5c;
		color: #fff;
		font-size: 1.7em;
		padding: .5em;
	}
	.divider {
		clear: both;
	}
	.divider.dots {
		border-top: 1px solid #eeede7;
	}
	
	.restaurant-name {
		float: left;
	}

	.order-id {
		float: right;
	}
	
	.order-icon {
		font-size: 1.2em;
		display: table-cell;
		width: 3.2em;
		text-align: center;
		vertical-align: middle;
	}
	.order-info {
		display: table-cell;
		font-size: 1.3em;
		vertical-align: middle;
		line-height: 1.4em;
	}
	.order-item-block {
		display: table;
		float: left;
		width: 15em;
		margin: 1em 0 1em 0;
	}
	.order-map-block {
		width: 100%;
		margin-top: 0;
		
	}
	
	.order-map {
		width: 100%;
		height: 15em;
		background-size:cover !important;
	}
	
	[class*='icon-'] {
		display: inline-block;
	}
	
	a {
		color: #d74924;
		text-decoration: underline;
	}

	
	.order-comment-arrow {
		width: 0;
		height: 0;
		border-left: 7px solid transparent;
		border-right: 7px solid transparent;
		border-bottom: 7px solid #00957f;
		margin-left: 1.2em;
	}
	
	.order-comment {
		background: #00957f;
		color: #fff;
		padding: .7em .9em .5em 1em;
		border-radius: 4px;
		margin-bottom: .8em;
	}

	.icon-support {
		background: url(http://dev.crunchr.co/assets/images/micro/icon-support.svg) no-repeat;
		background-position: top center;
		width: 2.4em;
		height: 2.8em;
		background-size: 100%;
	}
	
	.icon-chef {
		background: url(http://dev.crunchr.co/assets/images/micro/icon-chef.svg) no-repeat;
		background-position: top center;
		width: 2.0em;
		height: 2.6em;
		background-size: 100%;
	}
	
	.icon-user {
		background: url(http://dev.crunchr.co/assets/images/micro/icon-user.svg) no-repeat;
		background-position: top center;
		width: 1.9em;
		height: 2.4em;
		background-size: 100%;
	}
	
	.icon-delivery {
		background: url(http://dev.crunchr.co/assets/images/micro/icon-delivery.svg) no-repeat;
		background-position: top center;
		width: 2.2em;
		height: 1.6em;
		background-size: 100%;
	}
	
	.icon-card {
		background: url(http://dev.crunchr.co/assets/images/micro/icon-card.svg) no-repeat;
		background-position: top center;
		width: 2.3em;
		height: 1.6em;
		background-size: 100%;
	}
	
	.icon-clock {
		background: url(http://dev.crunchr.co/assets/images/micro/icon-clock.svg) no-repeat;
		background-position: top center;
		width: 1.6em;
		height: 2em;
		background-size: 100%;
	}
	
	.icon-timer {
		background: url(http://dev.crunchr.co/assets/images/micro/icon-timer.svg) no-repeat;
		background-position: top center;
		width: 1.6em;
		height: 2.3em;
		background-size: 100%;
	}
	
	.icon-map-home {
		background: url(http://dev.crunchr.co/assets/images/micro/icon-map-home.svg) no-repeat;
		background-position: top center;
		width: 1.6em;
		height: 2.41em;
		background-size: 100%;
	}
	
	.icon-map-restaurant {
		background: url(http://dev.crunchr.co/assets/images/micro/icon-map-restaurant.svg) no-repeat;
		background-position: top center;
		width: 1.6em;
		height: 2.41em;
		background-size: 100%;
	}
	
	.icon-cash {
		background: url(http://dev.crunchr.co/assets/images/micro/icon-cash.svg) no-repeat;
		background-position: top center;
		width: 2.1em;
		height: 1.6em;
		background-size: 100%;
	}
	
	.icon-takeout {
		background: url(http://dev.crunchr.co/assets/images/micro/icon-takeout.svg) no-repeat;
		background-position: top center;
		width: 1.5em;
		height: 2.0em;
		background-size: 100%;
	}
	
	.icon-phone {
		background: url(http://dev.crunchr.co/assets/images/micro/icon-phone.svg) no-repeat;
		background-position: top center;
		width: 1.4em;
		height: 1.4em;
		background-size: 100%;
		margin-top: .2em;
	}
	
	.icon-notes {
		background: url(http://dev.crunchr.co/assets/images/micro/icon-notes.svg) no-repeat;
		background-position: top center;
		width: 1.9em;
		height: 1.6em;
		background-size: 100%;
	}
	
	.icon-credit {
		background: url(http://dev.crunchr.co/assets/images/micro/icon-credit.svg) no-repeat;
		background-position: top center;
		width: 2.5em;
		height: 1.9em;
		background-size: 100%;
	}

	td {
		border: 0;
		padding: .5em;
	}

	.fooditem {
		border-bottom: 1px solid #999;
	}
	
	.topitem {
		border-bottom: 2px solid #999;
	}
	
	.control .wrap {
		width: 100%;
		box-sizing: border-box;
		display: table;
	}
	
	.control .message {
		font-size: 1.3em;
		display: table-cell;
		vertical-align: middle;
		text-shadow:1px 1px 0px #fff
	}

	.button {
		padding: .3em 1em .3em 1em;
		margin: .2em 0 .2em .6em;
		color: #fff;
		cursor: pointer;
		font-size: 1.4em;
		font-weight: bold;
		border: 1px solid rgba(0,0,0,.2);
		box-shadow: 0px 0px 3px rgba(0,0,0,.3);
		text-shadow: 1px 1px 0 rgba(0,0,0,.4);
		-webkit-transition: all .09s ease;
	}
	
	.button:active {
		-webkit-transform:translate(0, 2px);
		box-shadow: 0px 0px 1px rgba(0,0,0,.3);
	}
	
	.button-yes {
		background: #7bca72;
		border-radius: 4px;
	}
	
	.button-no {
		background: #dc534b;
		border-radius: 4px;
	}

</style>
</head>

<body>
	<div class="control">
		<div class="wrap">
			<div class="message">Accept this order?</div>
				<div class="buttons">
					<button class="button button-yes">Yes</button>
					<button class="button button-no">No</button>
				</div>
			</div>
			<div class="divider"></div>
		</div>
	</div>
	
	<div class="content">
		<div class="wrap">
			<?=$this->content?>
		</div>
	</div>
</body>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="/assets/js/fastclick.js"></script>
</html>