<?php 
$shift = $this->shift;
?>
<div class="row-fluid">
	<div class="container-fluid">
		<div class="row-fluid">
			<div class="span12">
						<form>
							<div class="row-fluid">
								<div class="span12">
									<div class="span4">
										<strong>Community:</strong>
									</div>
									<div class="span7">
										<?php echo $shift->community()->name; ?>
									</div>
								</div>
							</div>
							<div class="row-fluid">
								<div class="span12">
									<div class="span4">
										<strong>Date:</strong>
									</div>
									<div class="span7">
										<input type="hidden" name="form-id_community_shift" id="form-id_community_shift" value="<?php echo $shift->id_community_shift ?>"/>
										<?php echo $shift->dateStart()->format( 'm/d/Y' ); ?>
									</div>
								</div>
							</div>
							<div class="row-fluid">
								<div class="span12">
									<div class="span4">
										<strong>Timezone</strong>
									</div>
									<div class="span7">
										<strong><?php echo $shift->timezone(); ?></strong>
									</div>
								</div>
							</div>
							<div class="row-fluid">
								<div class="span12">
									<div class="span4">
										<strong>Hours</strong>
									</div>
									<div class="span7">
										<input type="text" value="<?php echo $shift->startEndToString(); ?>" name="form-hours" id="form-hours"/> 
										<br/>
										*Add this one shift per time.
										<br/><br/>
									</div>
								</div>
							</div>
							<div class="row-fluid">
								<div class="row-fluid">
									<div class="span12">
										<br/>
									</div>
								</div>
								<div class="row-fluid">
									<div class="span6">
										<button type="button" onclick="shift.community.edit();" class="btn btn-green"><i class="icon-save"></i> Save </button> <button type="button" onclick="shift.community.remove();" class="btn btn-red"><i class="icon-trash"></i> Remove </button> 
									</div>
								</div>
							</div>
						</form>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript" src="/assets/js/admin.shift.js"></script>