<div class="admin-content-wrapper">
	<div class="admin-content admin-content-giftcards">
		<h1 class="giftcard-item-title">Gift card</h1>
		<br /><br />
		<table class="admin-giftcard-form">
			<tr>
				<td class="label-primary">Promo code:</td>
				<td class="content-primary">
					<div class="check-wrap">
						<div class="check-content">
							<table style="width:100%;">
								<tbody>
									<tr>
										<td class="label-sub">Value:</td>
										<td class="content-sub"><input type="text" id="value" name="value"></div></td>
									</tr>
									<tr>
										<td class="label-sub">Phones:</td>
										<td class="content-sub">
											<textarea style="height:100px;" name="phones" id="phones"></textarea>
											<br/>
											*One phone per line.
										</td>
									</tr>
									<tr>
										<td class="label-sub">Type:</td>
										<td class="content-sub">gift_card</td>
									</tr>
									<tr>
										<td class="label-sub">Restaurant:</td>
										<td class="content-sub">
											<select id="id_restaurant" class="chosen-select" name="id_restaurant" data-placeholder="Choose a restaurant" style="width:350px;">
												<option value="" selected></option>
												<? foreach (Restaurant::q('SELECT * FROM restaurant ORDER BY name') as $restaurant) : ?>
													<option value="<?=$restaurant->id_restaurant?>"><?=$restaurant->name?></option>
												<? endforeach ; ?>
											</select>
										</td>
									</tr>
									<tr>
										<td></td>
										<td>
											<div class="action-button action-button-small green admin-giftcard-save">
												<span>Save</span>
											</div>
										</td>
									</tr>
								</tbody>
							</table>
						</div>
					</div>
				</td>
			</tr>
		</table>
	</div>
</div>
<script>
$(function() {
	App.giftcards.prepareFormBunchSMS();
	$(".chosen-select").chosen();
});
</script>