<div class="admin-content-wrapper" style="width: 700px;">
	<div class="admin-content">

		<? if (!$this->notification) : ?>
			<b>This restaurant does not currently have a fax # set up</b>
		<? else : ?>
			<h1 class="restaurant-item-title">Send a fax to <?=$this->notification?></h1>
			<br /><br />
			
			<form enctype="multipart/form-data" id="restaurant-fax" method="post" action="/admin/fax">
				<input type="hidden" name="id_restaurant" value="<?=$this->restaurant->id_restaurant?>">
				<table class="admin-restaurant-pay-form">
					<tr>
						<td>File</td>
						<td>
							<input type="file" name="fax">
						</td>
					</tr>
					<tr>
						<td colspan="2">
							<br />
							<div class="action-button action-button-small green restaurant-fax-button" style="float: left;"><span>Send</span></div>
						</td>
					</tr>
				</table>
			</form>

		<? endif ; ?>

	</div>
</div>

<script>
	$(function() {
		$('.restaurant-fax-button').click(function() {
			$('#restaurant-fax').submit();
		});
	});
</script>

