<div class="admin-content-wrapper" style="width: 700px;">
	<div class="admin-content">

		
		
		<form id="restaurant-image" action="" method="post" enctype="multipart/form-data">
			<table class="admin-restaurant-pay-form">
				<tr>
					<td>
						<img src="http://i.crunchr.co/600x600/<?=$this->restaurant->image?>" style="max-width: 600px;">
					</td>
				</tr>
				<tr>
					<td>
						<input type="file" name="image">
					</td>
				</tr>
				
				<tr>
					<td>
						<br />
						<div class="action-button action-button-small green restaurant-image-button" style="float: left;"><span>Upload</span></div>
					</td>
				</tr>
			</table>
		</form>
	</div>
</div>

<script>
	$(function() {
		$('.restaurant-image-button').click(function() {
			var form = $(this).closest('form');
			form.get(0).submit();
		});
	});
</script>

