<?
/**
 * List all restaurants and the add-new-restaurant button
 *
 * @package  Crunchbutton.Restaurant
 * @category view
 */
?>

<? ob_start() ?>
<? foreach ($this->communities as $community) : ?>
	<? /* @var $community Crunchbutton_Community */ ?>
	<option value="<?=$community->id_community?>">
		<?=$community->name?>
	</option>
<? endforeach ?>
<? $communityOptions = preg_replace('/\s+/', ' ', ob_get_clean());?>

<style>
.labeled-form label      { display: block; }
.labeled-form span.label {
	display:       inline-block;
	margin-bottom: 10px;
	width:         100px;
}
</style>

<div class="admin-content-wrapper">
	<div class="admin-content">

		<a href="/admin/restaurants/new">
			<div class="admin-food-item admin-restaurant-item">
				<span class="food-name">Create New</span>
			</div>
		</a>
		<hr class="divider" />
		<? foreach (Restaurant::q('select * from restaurant') as $restaurant) :  ?>
			<a href="/admin/restaurants/<?=$restaurant->id_restaurant?>">
				<div class="admin-food-item admin-restaurant-item">
					<span class="food-name"><?=$restaurant->name?></span>
				</div>
			</a>
		<? endforeach ?>
		<div class="divider"></div>


	</div>
</div>

<div class="divider"></div>
