
<div class="admin-content-wrapper">
	<div class="admin-content">
		<? foreach (Restaurant::q('select * from restaurant') as $restaurant) :  ?>
			<a href="/admin/restaurants/<?=$restaurant->id_restaurant?>">
				<div class="admin-food-item admin-restaurant-item">
					<span class="food-name"><?=$restaurant->name?></span>
				</div>
			</a>
		<? endforeach ?>

		<a href="/admin/restaurants/new">
			<div class="admin-food-item admin-restaurant-item">
				<span class="food-name">Create New</span>
			</div>
		</a>

		<div class="divider"></div>
	</div>
</div>

<div class="divider"></div>
