

<div class="admin-id_restaurant" data-id_restaurant=""></div>

<div class="admin-content-wrapper" style="width: 650px; float: left;">
	<div class="admin-content">
		<h1 class="restaurant-item-title">Restaurant Information</h1>
		<br /><br />
		<table class="admin-restaurant-form">
			<tr>
				<td class="label-primary">Restaurant Name:</td>
				<td class="content-primary"><input type="text" name="name" value="" class="input-primary"></td>
			</tr>
			<tr>
				<td class="label-primary">Phone Number:</td>
				<td class="content-primary"><input type="text" name="phone" value="" class="input-primary"></td>
			</tr>

			<tr>
				<td class="label-primary">Order Notification Methods:</td>
				<td class="content-primary">
					<div class="check-wrap">
						<div class="check"><input type="checkbox"><label>Fax</label></div>
					</div>
					<div class="check-wrap">
						<div class="check"><input type="checkbox"><label>Email</label></div>
					</div>
					<div class="check-wrap">
						<div class="check"><input type="checkbox"><label>Text Message</label></div>
					</div>
					<div class="check-wrap">
						<div class="check"><input type="checkbox"><label>Phone Call</label></div>
						<div class="check-content">Okay, well call blah blah</div>
					</div>
				</td>
			</tr>
			
			<tr>
				<td class="label-primary">Food Items:</td>
				<td class="content-primary">
					<div class="check-wrap">
						<div class="check"><input type="checkbox"><label>No, I'll add some items later.</label></div>
					</div>

				</td>
			</tr>
			
			<tr>
				<td class="label-primary">Open Hours:</td>
				<td class="content-primary">
					<div class="check-wrap">
						<div class="check"><input type="checkbox"><label>We're always open!</label></div>
					</div>
					<div class="check-wrap">
						<div class="check"><input type="checkbox"><label>We're open during these hours</label></div>
						<div class="check-content admin-restaurant-hours admin-restaurant-content"></div>
					</div>
				</td>
			</tr>
			
			<tr>
				<td class="label-primary">Delivery Options:</td>
				<td class="content-primary">
					<div class="check-wrap">
						<div class="check"><input type="checkbox"><label>We do not offer delivery</label></div>
					</div>
					<div class="check-wrap">
						<div class="check"><input type="checkbox"><label>Yes! We deliver!</label></div>
						<div class="check-content">
							<table class="admin-restaurant-form-sub">
								<tr>
									<td class="label-sub">Average Delivery Time:</td>
									<td class="content-sub"><input type="number" name="delivery_estimated_time" class="form-number"> minites</td>
								</tr>
								<tr>
									<td class="label-sub">Delivery Radius:</td>
									<td class="content-sub"><input type="number" name="delivery_radius" class="form-number" step="any"> miles</td>
								</tr>
								<tr>
									<td class="label-sub">Delivery Fee?</td>
									<td class="content-sub">
										<div class="check-wrap">
											<div class="check"><input type="checkbox"><label>No</label></div>
										</div>
										<div class="check-wrap">
											<div class="check"><input type="checkbox"><label>Yes</label></div>
											<div class="check-content">
												$ <input type="number" name="delivery_fee" step="any" class="form-number">
											</div>
										</div>
									</td>
								</tr>
								<tr>
									<td class="label-sub">Minimum order for delivery?</td>
									<td class="content-sub">
										<div class="check-wrap">
											<div class="check"><input type="checkbox"><label>No</label></div>
										</div>
										<div class="check-wrap">
											<div class="check"><input type="checkbox"><label>Yes</label></div>
											<div class="check-content">
												$ <input type="number" name="delivery_min" step="any" class="form-number">
											</div>
										</div>
									</td>
								</tr>
							</table>
						</div>
					</div>
				</td>
			</tr>
			
			<tr>
				<td class="label-primary">More Information:</td>
				<td class="content-primary">
					<div class="check-wrap">
						<div class="check-content">
							<table class="admin-restaurant-form-sub">
								<tr>
									<td class="label-sub">Restaurant Address:</td>
									<td class="content-sub"><textarea class="form-sub"></textarea></td>
								</tr>
								<tr>
									<td class="label-sub">Contact Email:</td>
									<td class="content-sub"><input type="text" class="form-sub"></td>
								</tr>
								<tr>
									<td class="label-sub">Manager/Owner can be reached at:</td>
									<td class="content-sub"><textarea class="form-sub"></textarea></td>
								</tr>
								<tr>
									<td class="label-sub">Include in a community?</td>
									<td class="content-sub">
										<div class="check-wrap">
											<div class="check"><input type="checkbox"><label>No</label></div>
										</div>
										<div class="check-wrap">
											<div class="check"><input type="checkbox"><label>Yes</label></div>
											<div class="check-content">
												<select name="id_community">
													<? foreach (Community::q('select * from community') as $community) : ?>
														<option value="<?=$community->id_community?>"><?=$community->name?></option>
													<? endforeach ; ?>
												</select>
											</div>
										</div>
									</td>
								</tr>
							</table>
						</div>
					</div>
				</td>
			</tr>
			
			<tr>
				<td class="label-primary">Admin shit:</td>
				<td class="content-primary">
					<div class="check-wrap">
						<div class="check-content">
							<table class="admin-restaurant-form-sub">
								<tr>
									<td class="label-sub">Permalink:</td>
									<td class="content-sub"><input type="text" name="permalink" value="" class="form-sub"></td>
								</tr>
								<tr>
									<td class="label-sub">Timezone:</td>
									<td class="content-sub"><input type="text" name="timezone" value="America/New_York" class="form-sub"></td>
								</tr>
								<tr>
									<td class="label-sub">Location:</td>
									<td class="content-sub">
										<table class="admin-restaurant-form-sub">
											<tr>
												<td class="labcon-sub-sub">Lat:</td>
												<td class="labcon-sub-sub"><input type="number" name="loc_lat" value="41.2" step="any" class="form-number"></td>
											</tr>
											<tr>
												<td class="labcon-sub-sub">Long:</td>
												<td class="labcon-sub-sub"><input type="number" name="loc_long" value="-70" step="any" class="form-number"></td>
											</tr>
										</table>
									</td>
								</tr>
								<tr>
									<td class="label-sub">Tax:</td>
									<td class="content-sub"><input type="number" name="tax" value="" step="any" class="form-number"> %</td>
								</tr>
								<tr>
									<td class="label-sub">Require confirmation?</td>
									<td class="content-sub">
										<div class="check-wrap">
											<div class="check"><input type="checkbox"><label>No</label></div>
										</div>
										<div class="check-wrap">
											<div class="check"><input type="checkbox"><label>Yes</label></div>
										</div>
									</td>
								</tr>
								<tr>
									<td class="label-sub">Customer receipt on fax?</td>
									<td class="content-sub">
										<div class="check-wrap">
											<div class="check"><input type="checkbox"><label>No</label></div>
										</div>
										<div class="check-wrap">
											<div class="check"><input type="checkbox"><label>Yes</label></div>
										</div>
									</td>
								</tr>
								<tr>
									<td class="label-sub">Restaurant Fee?</td>
									<td class="content-sub">
										<div class="check-wrap">
											<div class="check"><input type="checkbox"><label>No</label></div>
										</div>
										<div class="check-wrap">
											<div class="check"><input type="checkbox"><label>Yes</label></div>
											<div class="check-content">
												<input type="number" name="fee_restaurant" step="any" class="form-number"> %
											</div>
										</div>
									</td>
								</tr>
								<tr>
									<td class="label-sub">Customer Fee?</td>
									<td class="content-sub">
										<div class="check-wrap">
											<div class="check"><input type="checkbox"><label>No</label></div>
										</div>
										<div class="check-wrap">
											<div class="check"><input type="checkbox"><label>Yes</label></div>
											<div class="check-content">
												<input type="number" name="fee_customer" step="any" class="form-number"> %
											</div>
										</div>
									</td>
								</tr>
								<tr>
									<td class="label-sub">Active?</td>
									<td class="content-sub">
										<div class="check-wrap">
											<div class="check"><input type="checkbox"><label>No</label></div>
										</div>
										<div class="check-wrap">
											<div class="check"><input type="checkbox"><label>Yes</label></div>
										</div>
									</td>
								</tr>
							</table>
						</div>
					</div>
				</td>
			</tr>

			<tr>
				<td>Delivery</td>
				<td><input type="checkbox" name="delivery" value="1"></td>
			</tr>
			<tr>
				<td>Credit</td>
				<td><input type="checkbox" name="credit" value="1"></td>
			</tr>

			<tr>
				<td colspan="2" style="text-align: right;"><br />
					<div class="action-button green admin-restaurant-save">
						<span>Save Restaurant</span>
					</div>
				</td>
			</tr>
		</table>
	</div>

	
</div>


<div class="admin-content-wrapper" style="width: 200px; float: left; margin-left: 20px;">
	<div class="admin-content">
		<? foreach (Restaurant::q('select * from restaurant') as $restaurant) :  ?>
			<a href="javascript:;" data-id_restaurant="<?=$restaurant->id_restaurant?>" class="admin-restaurant-link<?=$restaurant->active ? '' : ' admin-restaurant-inactive'?>"><?=$restaurant->name?></a><br />
		<? endforeach ?>
		<br />
		<a href="javascript:;" data-id_restaurant="" class="admin-restaurant-link">NEW</a><br />
	</div>
</div>

<div class="divider"></div>
	

