<?
/**
 * Shows the Restaurant form for the admin
 *
 * @package Crunchbutton.Admin.Restaurant
 * @category view
 */

?>


<div id="admin-body-content">

	<div id="admin-top-content-bar">
		<div class="admin-jump-list">
			Jump to: 
			<a href="#menu">menu</a>
		</div>
		<div id="admin-top-button-group">
			<div id="legacy-button" class="admin-button">Legacy View</div>
			<div id="revert-button" class="admin-button">Revert</div>
		</div>
	</div>


	<div class=admin-h3>Basic Information</div>

	<div class=admin-item>
		<div class=admin-item-left>
			<div class=admin-item-name>Name</div>
			<div class=admin-item-desc>for display</div>
		</div>
		<div class=admin-item-right>
			<input type="input" id="restaurant-name" />
		</div>
	</div>

	<div class=admin-item>
		<div class=admin-item-left>
			<div class=admin-item-name>Permalink</div>
			<div class=admin-item-desc>crunchbutton.com/food-delivery/&lt;permalink></div>
		</div>
		<div class=admin-item-right>
			<input type="input" id="restaurant-permalink" />
		</div>
	</div>

	<div class=admin-item>
		<div class=admin-item-left>
			<div class=admin-item-name>Phone Number</div>
			<div class=admin-item-desc>publicly listed</div>
		</div>
		<div class=admin-item-right>
			<input type="input" id="restaurant-phone" />
		</div>
	</div>

	<div class=admin-item>
		<div class=admin-item-left>
			<div class=admin-item-name>Address</div>
			<div class=admin-item-desc>for delivery radius and pickup</div>
		</div>
		<div class=admin-item-right>
			<textarea id="restaurant-address"></textarea>
			<div class=admin-item-col-med>
				Latitude
				<input type="input" id="restaurant-lat" />
			</div>
			<div class=admin-item-col-med>
				Longitude
				<input type="input" id="restaurant-lng" />
			</div>
			<div class=admin-item-col-large>
				<div class=admin-map id=restaurant-map></div>
			</div>
		</div>
	</div>

	<div class=admin-item>
		<div class=admin-item-left>
			<div class=admin-item-name>Active</div>
			<div class=admin-item-desc>is it listed on the live site</div>
		</div>
		<div class=admin-item-right>
			<div class=admin-item-col-small id=restaurant-active-container></div>
		</div>
	</div>

	<div class=admin-item></div><!-- for the border line -->



	<div class=admin-h3>Vitals</div>

	<div class=admin-item>
		<div class=admin-item-left>
			<div class=admin-item-name>Notifications</div>
			<div class=admin-item-desc>what happens when an order goes through</div>
		</div>
		<div class=admin-item-right>
			<div class=admin-item-col-x-wide id=notifications-container></div>
			<div class=admin-item-col-med>
				<div class=admin-button-workflow id=add-notification>add another method</div>
			</div>
		</div>
	</div>

	<div class=admin-item>
		<div class=admin-item-left>
			<div class=admin-item-name>Timezone</div>
			<div class=admin-item-desc>where the restaurant is</div>
		</div>
		<div class=admin-item-right>
			<select id="restaurant-timezone">
				<option value="America/New_York">Eastern</option>
				<option value="America/Chicago">Central</option>
				<option value="America/Denver">Mountain</option>
				<option value="America/Los_Angeles">Pacific</option>
			</select>
		</div>
	</div>

	<div class=admin-item>
		<div class=admin-item-left>
			<div class=admin-item-name>Hours</div>
			<div class=admin-item-desc>restaurant's actual open hours</div>
			<div class=admin-item-desc>e.g. 12PM - 2:30AM</div>
		</div>
		<div class=admin-item-right id="restaurant-hours">
			<div class=admin-item-right-row>
				<div class=admin-item-col-wide>
					<input type="input" id="restaurant-hours-mon" />
				</div>
				<div class=admin-item-col-small> Monday </div>
				<div class=admin-item-col-med> </div>
			</div>
			<div class=admin-item-right-row>
				<div class=admin-item-col-wide>
					<input type="input" id="restaurant-hours-tue" />
				</div>
				<div class=admin-item-col-small> Tuesday</div>
				<div class=admin-item-col-med>
					<div class=admin-button-workflow id=copy-tue-from-mon>
						copy from Monday
					</div>
				</div>
			</div>
			<div class=admin-item-right-row>
				<div class=admin-item-col-wide>
					<input type="input" id="restaurant-hours-wed" />
				</div>
				<div class=admin-item-col-small> Wednesday</div>
				<div class=admin-item-col-med>
					<div class=admin-button-workflow id=copy-wed-from-tue>
						copy from Tuesday
					</div>
				</div>
			</div>
			<div class=admin-item-right-row>
				<div class=admin-item-col-wide>
					<input type="input" id="restaurant-hours-thu" />
				</div>
				<div class=admin-item-col-small> Thursday</div>
				<div class=admin-item-col-med>
					<div class=admin-button-workflow id=copy-thu-from-wed>
						copy from Wednesday
					</div>
				</div>
			</div>
			<div class=admin-item-right-row>
				<div class=admin-item-col-wide>
					<input type="input" id="restaurant-hours-fri" />
				</div>
				<div class=admin-item-col-small> Friday</div>
				<div class=admin-item-col-med>
					<div class=admin-button-workflow id=copy-fri-from-thu>
						copy from Thursday
					</div>
				</div>
			</div>
			<div class=admin-item-right-row>
				<div class=admin-item-col-wide>
					<input type="input" id="restaurant-hours-sat" />
				</div>
				<div class=admin-item-col-small> Saturday</div>
				<div class=admin-item-col-med>
					<div class=admin-button-workflow id=copy-sat-from-fri>
						copy from Friday
					</div>
				</div>
			</div>
			<div class=admin-item-right-row>
				<div class=admin-item-col-wide>
					<input type="input" id="restaurant-hours-sun" />
				</div>
				<div class=admin-item-col-small> Sunday</div>
				<div class=admin-item-col-med>
					<div class=admin-button-workflow id=copy-sun-from-sat>
						copy from Saturday
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class=admin-item></div><!-- for the border line -->

	<div id="float-bottom-right-container">
		<div id="save-button" class="admin-button">Save</div>
	</div>
	<div id="float-bottom-left-container">
		<div id="admin-msg"></div>
	</div>

</div>

<!-- templates -->

<div class=template-container>

	<div class=admin-toggle-active id=toggle-template>active</div>

	<div class=admin-notifications id=notifications-template></div>

	<div class=admin-notification id=notification-template>
		<div class=admin-item-col-small>
			<div class=admin-toggle-active></div>
		</div>
		<div class="admin-item-col-med-2 restaurant-notification">
			<select>
				<option value="fax">Fax</option>
				<option value="sms">Text Message</option>
				<option value="email">Email</option>
				<option value="phone">Phone Call</option>
				<option value="url">URL Request</option>
				<option value="confirmation">Confirmation Phone Call</option>
			</select>
		</div>
		<div class=admin-item-col-med-2>
			<input type="input" name="val" />
		</div>
	</div>

</div>






<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
<script type="text/javascript" src="/assets/js/admin_restaurant.js"></script>
<script>
ADMIN.restaurant_init(<?=$this->restaurant->id_restaurant?>);
</script>



