<?
/**
 * Shows the Restaurant form for the admin
 *
 * @package Crunchbutton.Admin.Restaurant
 * @category view
 */

/* @var $this Cana_View */
/* @var $this->restaurantCommunity Crunchbutton_Community */

/**
 * View helper to preselect the <select> community form input
 *
 * @param Crunchbutton_Community $current Which community is the current restaurant linked to
 * @param Crunchbutton_Community $tested  Which community we are listing in the <select>
 *
 * @return string
 */
function _selectedCommunity(Crunchbutton_Community $current, Crunchbutton_Community $tested) {
	$selected = '';
	if ($current->id_community == $tested->id_community) {
		$selected = ' selected="selected" ';
	}
	return $selected;
}

?>

<script>

$(function(){
	$('body').on('mouseenter', '.jqui-button', function(){
		$(this).removeClass('ui-state-default');
		$(this).addClass   ('ui-state-hover');
	});
	$('body').on('mouseleave', '.jqui-button', function(){
		$(this).addClass   ('ui-state-default');
		$(this).removeClass('ui-state-hover');
	});
});

</script>

<style>
/**
 * sets the page one column only
 */
.admin-content-wrapper { width: 970px;}
.admin-restaurant-form { width: 100%; }
.check-wrap            { width: 650px;}

/**
 * Link buttons without underline
 */
.action-button, #sub-tasks > a {
	text-decoration: none;
}

/**
 * The buttons at the top
 */
#sub-tasks > a {
	display: inline-block;
	width:   200px;
}

/* adds/removes spacing where needed for the dishes */
.ui-accordion .ui-accordion-content { padding: 0.4em;}
.ui-accordion .ui-accordion-header  { padding: 0.4em; padding-left: 2.2em; }


.fixed { position: fixed;}
.clear { clear: both;}

input.notification {width: 400px;}


.labeled-fields  label {
	float:         none;
	display:       block;
	margin-bottom: 5px;
}

.labeled-fields  label span {
	display: inline-block;
	width:   115px;
}
.labeled-fields .clear + label { margin-top: 5px; }

#categories .button-delete {
	cursor:  pointer;
	float:   right;
	margin:  2px;
	padding: 4px 0;
}

</style>

<div class="admin-id_restaurant" data-id_restaurant=""></div>
<div class="admin-content-wrapper">
	<?=Crunchbutton_Session::flashWidget()?>
	<div class="admin-content">
		<h1 class="restaurant-item-title">Restaurant Information</h1>
		<br /><br />
		<div id="sub-tasks">
			<a href="/admin/restaurants/<?=$this->restaurant->id_restaurant?>/pay">
				<div class="admin-food-item admin-restaurant-button">
					<span class="food-name">Payments &amp; Settings</span>
				</div>
			</a>
			<a href="/admin/restaurants/<?=$this->restaurant->id_restaurant?>/fax">
				<div class="admin-food-item admin-restaurant-button">
					<span class="food-name">Send a Fax</span>
				</div>
			</a>
			<a href="/admin/restaurants/<?=$this->restaurant->id_restaurant?>/image">
				<div class="admin-food-item admin-restaurant-button">
					<span class="food-name">Upload image</span>
				</div>
			</a>
		</div>

		<table class="admin-restaurant-form">
			<tr>
				<td class="label-primary">Restaurant Name:</td>
				<td class="content-primary"><input type="text" name="name" value="" class="input-primary dataset-restaurant"></td>
			</tr>
			<tr>
				<td class="label-primary">Phone Number:</td>
				<td class="content-primary"><input type="text" name="phone" value="" class="input-primary dataset-restaurant"></td>
			</tr>

			<tr>
				<td class="label-primary">Order Notification Methods:</td>
				<td class="content-primary" id="notifications">
					<div class="check-wrap">
						<div class="check">Text Message</div>
						<div class="check-content sms"></div>
					</div>
					<div class="check-wrap">
						<div class="check">Email</div>
						<div class="check-content email"></div>
					</div>
					<div class="check-wrap">
						<div class="check">Phone Call</div>
						<div class="check-content phone"></div>
					</div>
					<div class="check-wrap">
						<div class="check">URL</div>
						<div class="check-content url"></div>
					</div>
					<div class="check-wrap">
						<div class="check">Fax</div>
						<div class="check-content fax"></div>
					</div>
				</td>
			</tr>

			<tr>
				<td class="label-primary">Food Items:</td>
				<td class="content-primary">
					<div class="check-wrap">
						<div class="check"><input type="checkbox" value="0" name="dish_check" class="bind-a-check"><label>No, I'll add some items later.</label></div>
					</div>
					<div class="check-wrap">
						<div class="check"><input type="checkbox" value="1" name="dish_check" class="bind-a-check"><label>Our best items:</label></div>
						<div class="check-content admin-restaurant-dishes">
							<div class="admin-restaurant-content"></div>
							<div class="admin-restaurant-dishes-controls">
								<div class="control-link">
									<a href="#" class="control-link-add-category">
										<div class="control-icon-plus control-icon"></div>
										<label class="control-label">Add another dish category?</label>
									</a>
								</div>
								<div class="control-link">
									<a href="#" class="control-link-add-dish">
										<div class="control-icon-plus control-icon"></div>
										<label class="control-label">Add another dish?</label>
									</a>
								</div>
							</div>
							<div class="divider"></div>
						</div>
					</div>
				</td>
			</tr>

			<tr>
				<td class="label-primary">Open Hours:</td>
				<td class="content-primary">
					<div class="check-wrap">
						<div class="check"><input type="checkbox" value="0" name="hours_check" class="bind-a-check dataset-restaurant"><label>We're always open!</label></div>
					</div>
					<div class="check-wrap">
						<div class="check"><input type="checkbox" value="1" name="hours_check" class="bind-a-check dataset-restaurant"><label>We're open during these hours</label></div>
						<div class="check-content admin-restaurant-hours admin-restaurant-content"></div>
					</div>
				</td>
			</tr>

			<tr>
				<td class="label-primary">Delivery Options:</td>
				<td class="content-primary">
					<div class="check-wrap">
						<div class="check"><input type="checkbox" name="delivery" value="0" class="bind-a-check dataset-restaurant"><label>We do not offer delivery</label></div>
					</div>
					<div class="check-wrap">
						<div class="check"><input type="checkbox" name="delivery" value="1" class="bind-a-check dataset-restaurant"><label>Yes! We deliver!</label></div>
						<div class="check-content">
							<table class="admin-restaurant-form-sub">
								<tr>
									<td class="label-sub">Average Delivery Time:</td>
									<td class="content-sub"><input name="delivery_estimated_time" min="0" class="form-number dataset-restaurant"> minutes</td>
								</tr>
								<tr>
									<td class="label-sub">Delivery Radius:</td>
									<td class="content-sub"><input name="delivery_radius" min="0" class="form-number dataset-restaurant" step="any"> miles</td>
								</tr>
								<tr>
									<td class="label-sub">Delivery Fee?</td>
									<td class="content-sub">
										<div class="check-wrap">
											<div class="check"><input type="checkbox" name="delivery_fee_check" value="0" class="bind-a-check-values"><label>No</label></div>
										</div>
										<div class="check-wrap">
											<div class="check"><input type="checkbox" name="delivery_fee_check" value="1" class="bind-a-check-values"><label>Yes</label></div>
											<div class="check-content">
												$ <input name="delivery_fee" step="any" min="0" class="form-number dataset-restaurant">
											</div>
										</div>
									</td>
								</tr>
								<tr>
									<td class="label-sub">Minimum order for delivery?</td>
									<td class="content-sub">
										<div class="check-wrap">
											<div class="check"><input type="checkbox" name="delivery_min_check" value="0" class="bind-a-check-values"><label>No</label></div>
										</div>
										<div class="check-wrap">
											<div class="check"><input type="checkbox" name="delivery_min_check" value="1" class="bind-a-check-values"><label>Yes</label></div>
											<div class="check-content">
												$ <input name="delivery_min" step="any" min="0" class="form-number dataset-restaurant">
											</div>
										</div>
									</td>
								</tr>
							</table>
						</div>
					</div>
				</td>
			</tr>

			<tr>
				<td class="label-primary">More Information:</td>
				<td class="content-primary">
					<div class="check-wrap">
						<div class="check-content">
							<table class="admin-restaurant-form-sub">
								<tr>
									<td class="label-sub">Message:</td>
									<td class="content-sub"><textarea class="form-sub dataset-restaurant" name="message"></textarea><br/>Some information you want to show at the restaurant's page:</td>
								</tr>
								<tr>
									<td class="label-sub">Average Pickup Time:</td>
									<td class="content-sub"><input name="pickup_estimated_time" min="0" class="form-number dataset-restaurant"> minutes</td>
								</tr>
								<tr>
									<td class="label-sub">Restaurant Address:</td>
									<td class="content-sub"><textarea class="form-sub dataset-restaurant" name="address"></textarea></td>
								</tr>
								<tr>
									<td class="label-sub">Contact Email:</td>
									<td class="content-sub"><input type="text" class="form-sub dataset-restaurant" name="email"></td>
								</tr>
								<tr>
									<td class="label-sub">Manager/Owner can be reached at:</td>
									<td class="content-sub"><textarea class="form-sub dataset-restaurant" name="notes_owner"></textarea></td>
								</tr>
								<tr>
									<td class="label-sub">Include in a community?</td>
									<td class="content-sub">
										<div class="check-wrap">
											<div class="check"><input type="checkbox" name="id_community_check" value="0" class="bind-a-check-values"><label>No</label></div>
										</div>
										<div class="check-wrap">
											<div class="check"><input type="checkbox" name="id_community_check" value="1" class="bind-a-check-values"><label>Yes</label></div>
											<div class="check-content">
												<select name="id_community" class="dataset-restaurant">
													<option value="0">[remove communites]</option>
													<? foreach ($this->communities as $community) : ?>
														<? /* @var $community Crunchbutton_Community */ ?>
														<option value="<?=$community->id_community?>"
														<?=($this->restaurantCommunity) ? _selectedCommunity($this->restaurantCommunity, $community) : ''?>
														>
															<?=$community->name?>
														</option>
													<? endforeach ; ?>
												</select>
											</div>
										</div>
									</td>
								</tr>
							</table>
						</div>
					</div>
				</td>
			</tr>

			<tr>
				<td class="label-primary">Admin shit:</td>
				<td class="content-primary">
					<div class="check-wrap">
						<div class="check-content">
							<table class="admin-restaurant-form-sub">
								<tr>
									<td class="label-sub">Permalink:</td>
									<td class="content-sub"><input type="text" name="permalink" value="" class="form-sub dataset-restaurant"></td>
								</tr>
								<tr>
									<td class="label-sub">Timezone:</td>
									<td class="content-sub"><input type="text" name="timezone" value="America/New_York" class="form-sub dataset-restaurant"></td>
								</tr>
								<tr>
									<td class="label-sub">Location:</td>
									<td class="content-sub">
										<table class="admin-restaurant-form-sub">
											<tr>
												<td class="labcon-sub-sub">Lat:</td>
												<td class="labcon-sub-sub"><input name="loc_lat" value="41.2" step="any" class="form-number dataset-restaurant"></td>
											</tr>
											<tr>
												<td class="labcon-sub-sub">Long:</td>
												<td class="labcon-sub-sub"><input name="loc_long" value="-70" step="any" class="form-number dataset-restaurant"></td>
											</tr>
										</table>
									</td>
								</tr>
								<tr>
									<td class="label-sub">Sort Order:</td>
									<td class="content-sub"><input name="sort" value="" step="any" min="0" class="form-number dataset-restaurant"></td>
								</tr>
								<tr>
									<td class="label-sub">Tax:</td>
									<td class="content-sub"><input name="tax" value="" step="any" min="0" class="form-number dataset-restaurant"> %</td>
								</tr>
								<tr>
									<td class="label-sub">Deliv Min Applies to:</td>
									<td class="content-sub">
										<select name="delivery_min_amt" class="dataset-restaurant">
											<option value="subtotal">Subtotal</option>
											<option value="total">Total</option>
										</select>
									</td>
								</tr>
								<tr>
									<td class="label-sub">Require confirmation?</td>
									<td class="content-sub">
										<div class="check-wrap">
											<div class="check"><input type="checkbox" name="confirmation" value="0" class="dataset-restaurant bind-a-check"><label>No</label></div>
										</div>
										<div class="check-wrap">
											<div class="check"><input type="checkbox" name="confirmation" value="1" class="dataset-restaurant bind-a-check"><label>Yes</label></div>
										</div>
									</td>
								</tr>
								<tr>
									<td class="label-sub">Customer receipt on fax?</td>
									<td class="content-sub">
										<div class="check-wrap">
											<div class="check"><input type="checkbox" name="customer_receipt" value="0" class="dataset-restaurant bind-a-check"><label>No</label></div>
										</div>
										<div class="check-wrap">
											<div class="check"><input type="checkbox" name="customer_receipt" value="1" class="dataset-restaurant bind-a-check"><label>Yes</label></div>
										</div>
									</td>
								</tr>
								<tr>
									<td class="label-sub">Restaurant Fee?</td>
									<td class="content-sub">
										<div class="check-wrap">
											<div class="check"><input type="checkbox" name="fee_restaurant_check" value="0" class="dataset-restaurant bind-a-check-values"><label>No</label></div>
										</div>
										<div class="check-wrap">
											<div class="check"><input type="checkbox" name="fee_restaurant_check" value="1" class="dataset-restaurant bind-a-check-values"><label>Yes</label></div>
											<div class="check-content">
												<input name="fee_restaurant" step="any" min="0" class="form-number dataset-restaurant change-a-check"> %
											</div>
										</div>
									</td>
								</tr>
								<tr>
									<td class="label-sub">Customer Fee?</td>
									<td class="content-sub">
										<div class="check-wrap">
											<div class="check"><input type="checkbox" name="fee_customer_check" value="0" class="dataset-restaurant bind-a-check-values"><label>No</label></div>
										</div>
										<div class="check-wrap">
											<div class="check"><input type="checkbox" name="fee_customer_check" value="1" class="dataset-restaurant bind-a-check-values"><label>Yes</label></div>
											<div class="check-content">
												<input name="fee_customer" step="any" min="0" class="form-number dataset-restaurant change-a-check"> %
											</div>
										</div>
									</td>
								</tr>
								<tr>
									<td class="label-sub">Accepts Credit Cards?</td>
									<td class="content-sub">
										<div class="check-wrap">
											<div class="check"><input type="checkbox" name="credit" value="0" class="dataset-restaurant bind-a-check"><label>No</label></div>
										</div>
										<div class="check-wrap">
											<div class="check"><input type="checkbox" name="credit" value="1" class="dataset-restaurant bind-a-check"><label>Yes</label></div>
										</div>
									</td>
								</tr>
								<tr>
									<td class="label-sub">Accepts Cash?</td>
									<td class="content-sub">
										<div class="check-wrap">
											<div class="check"><input type="checkbox" name="cash" value="0" class="dataset-restaurant bind-a-check"><label>No</label></div>
										</div>
										<div class="check-wrap">
											<div class="check"><input type="checkbox" name="cash" value="1" class="dataset-restaurant bind-a-check"><label>Yes</label></div>
										</div>
									</td>
								</tr>
								<tr>
									<td class="label-sub">Active?</td>
									<td class="content-sub">
										<div class="check-wrap">
											<div class="check"><input type="checkbox" name="active" value="0" class="dataset-restaurant bind-a-check"><label>No</label></div>
										</div>
										<div class="check-wrap">
											<div class="check"><input type="checkbox" name="active" value="1" class="dataset-restaurant bind-a-check"><label>Yes</label></div>
										</div>
									</td>
								</tr>
								<tr>
									<td class="label-sub">Notes:</td>
									<td class="content-sub"><textarea class="form-sub dataset-restaurant form-sub-big" name="notes"></textarea></td>
								</tr>
								<tr>
									<td class="label-sub">Todo:</td>
									<td class="content-sub"><textarea class="form-sub dataset-restaurant form-sub-big" name="notes_todo"></textarea></td>
								</tr>
							</table>
						</div>
					</div>
				</td>
			</tr>
		</table>
		<div class="hovering-container">
			<div class="action-button action-button-small red admin-restaurant-revert">
				<span>Revert</span>
			</div>
			<div class="action-button action-button-small green admin-restaurant-save" style="margin-right: 10px;">
				<span>Save Restaurant</span>
			</div>
			<div class="clear"></div>
		</div>
	</div>


</div>



<div class="divider"></div>


<div id="dialog-option-group" title="Create Option Group" style="display: none;">
	<table class="admin-restaurant-form-sub">
		<tr>
			<td colspan="2" class="label-sub"><input type="text" name="admin-option-name" placeholder="Name" class="form-sub"></td>
		</tr>
		<tr>
			<td class="label-sub">Display type:</td>
			<td class="content-sub">
				<select name="admin-option-type">
					<option value="check">Checkboxes</option>
					<option value="select">Select</option>
				</select>
			</td>
		</tr>
		<tr>
			<td class="label-sub">Modifies the base price?</td>
			<td class="content-sub">
				<input type="checkbox" name="admin-option-price">
			</td>
		</tr>
	</table>
</div>

<div id="dialog-add-menu" title="Create Dish Category" style="display: none;">
	<table class="admin-restaurant-form-sub">
		<tr>
			<td colspan="2" class="label-sub"><input type="text" name="admin-category-name" placeholder="Name" class="form-sub"></td>
	</table>
</div>

<script>
$(function() {
	App.loadRestaurant(<?=$this->restaurant->id_restaurant?>);
});
</script>
