<? die('#5430 deprecated'); ?>

<? if (!count($this->restaurants)) : ?>
	No restaurants with orders found
<? else : ?>
	<div class='box'>
		<div class='box-header'>
			<span class='title'>Summary</span>
		</div>
		<div style='padding:5px; border-bottom:1px solid #ccc;' >
			<span style='display:inline-block;min-width:100px;'>Num Restaurants</span>&nbsp;&nbsp;
			<span id='num_restaurants'>
			<strong><?=count($this->restaurants) ?></strong>
			</span>
		</div>
		<div style='padding:5px; border-bottom:1px solid #ccc;' >
			<span style='display:inline-block;min-width:100px;'>Total Payments</span>&nbsp;&nbsp;
			<span id='total_payments'><strong>$0</strong></span>
		</div>
	</div>

	<? foreach($this->restaurants as $restaurant) : ?>
		<? if (!$restaurant->payableOrders()->count()) :
			continue;
		endif ; ?>
		<div class='box RST_container RST<?=$restaurant->id?>_container'
			data_restaurant_id=<?=$restaurant->id?>
			data_fax_number="<?=$restaurant->fax()?>"
			data_name="<?=$restaurant->name?>" >
		<div class='box-header'>
			<span class="title"><?=$restaurant->name ?></span>
		</div>

		<div style='padding:5px; border-bottom:1px solid #ccc;' class='last_payment'>
			<div>
				<span>Last Payment: </span>
				<? $payment = $restaurant->getLastPayment(); ?>
				<? if ($payment) : ?>
					[#<?=$payment->id_payment?>]
					<b><?=Util::format_price($payment->amount)?></b> on
					<b><?=$payment->date?></b> -
					<?=$payment->note?>
				<? else : ?>
					<b>Never</b>
				<? endif ; ?>
			</div>
		</div>

			<div>
				<table>
					<tbody>
					<? foreach ( $restaurant->payableOrders() as $order) : ?>
						<tr>
							<td>
								<a href='https://crunchbutton.com/order/<?=$order->uuid?>' target='_blank'>
									#<?=$order->id_order?>
								</a>
							</td>
							<td>
								<?=$order->name?>
							</td>
							<td>
								<?=Util::format_price($order->final_price)?>
							</td>
							<td>
								<?=$order->pay_type?>
							</td>
							<td>
								<?=date_format($order->date(),'M d, Y')?>
							</td>
						</tr>
					<?
						endforeach;
					?>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td>Cash Orders</td>
						<td>$<?=$restaurant->payment_data[ 'order_payment' ]; ?></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td>Card Subtotal</td>
						<td>$<?=$restaurant->payment_data[ 'card_subtotal' ]; ?></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td>Tax</td>
						<td>$<?=$restaurant->payment_data[ 'tax' ]; ?></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td>Delivery Fee</td>
						<td>$<?=$restaurant->payment_data[ 'delivery_fee' ]; ?></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td>Tip</td>
						<td>$<?=$restaurant->payment_data[ 'tip' ]; ?></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td>Customer fee</td>
						<td>$<?=$restaurant->payment_data[ 'customer_fee' ]; ?></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td>Markup</td>
						<td>$<?=$restaurant->payment_data[ 'markup' ]; ?></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td>Credit Card Charges</td>
						<td>$<?=$restaurant->payment_data[ 'credit_charge' ]; ?></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td>Crunchbutton Fees (<?=$restaurant->fee_restaurant?>%)</td>
						<td>$<?=$restaurant->payment_data[ 'restaurant_fee' ]; ?></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td>Gift Card</td>
						<td>$<?=$restaurant->payment_data[ 'promo_gift_card' ]; ?></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td>Apology Gift Card</td>
						<td>$<?=$restaurant->payment_data[ 'apology_gift_card' ]; ?></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td>Total Payment</td>
						<td>$<?=$restaurant->payment_data[ 'total_due' ]; ?></td>
						<td></td>
						<td></td>
					</tr>
				</tbody></table>
			</div>

		</div>
	<? endforeach; ?>
<? endif ; ?>






