<? if (!count($this->settlement->restaurants)) : ?>
	No restaurants with orders found
<? else : ?>

	<div class='box'>
		<div class='box-header'>
			<span class='title'>Summary</span>
		</div>
		<div style='padding:5px; border-bottom:1px solid #ccc;' >
			<span style='display:inline-block;min-width:100px;'>Num Restaurants</span>&nbsp;&nbsp;
			<span id='num_restaurants'>
			<strong><?=count($this->settlement->restaurants) ?></strong>
			</span>
		</div>
		<div style='padding:5px; border-bottom:1px solid #ccc;' >
			<span style='display:inline-block;min-width:100px;'>Total Payments</span>&nbsp;&nbsp;
			<span id='total_payments'><strong>$0</strong></span>
		</div>
	</div>

	<? foreach($this->settlement->restaurants as $restaurant) : ?>
		<? if (!$restaurant->payableOrders()->count()) : 
			continue;
		endif ; ?>

		<div class='box RST_container RST<?=$restaurant->id?>_container'
			data_restaurant_id=<?=$restaurant->id?> 
			data_fax_number="<?=$restaurant->fax()?>" 
			data_name="<?=$restaurant->name?>" 
		>
		<div class='box-header'>
			<span class="title"><?=$restaurant->name ?></span>
		</div>
			
		<div style='padding:5px; border-bottom:1px solid #ccc;' class='last_payment'>
			<div>
				<span>Last Payment: </span>
				<? $payment = $restaurant->getLastPayment(); ?>
				<? if ($payment) : ?>
					[#<?=$payment->id_payment?>] 
					<b><?=Util::format_price($payment->amount)?></b> on 
					<b><?=$payment->date?></b> - 
					<?=$payment->note?>
				<? else : ?>
					<b>Never</b>
				<? endif ; ?>
			</div>
		</div>

			<div style='padding:5px; border-bottom:1px solid #ccc;'>
				<table class=''><tbody>
					<? foreach ($restaurant->payableOrders() as $order) : ?>
						<tr>
							<td style='min-width:100px;padding-right:10px;'>
								<div 
									id='ORD<?=$order->id_order?>' 
									style='display:none;'
									class='ord_row' 
									data_pay_type='<?=$order->pay_type?>' 
									data_cc_fee_cents='<?=round($order->_cc_fee*100)?>' 
									data_cb_fee_cents='<?=round($order->_cb_fee*100)?>' 
									data_final_price_cents='<?=$order->_display_final_price*100?>' 
									data_subtotal_cents='<?=$order->_display_price*100?>' 
									data_id_order='<?=$order->id_order?>' 
								/>
								<!--a href='#' onclick="javascript:delete_row(this);return false;">
									<span class='remove_row icon-remove-sign' />
								</a-->
								&nbsp;&nbsp;
								<a href='https://crunchbutton.com/order/<?=$order->uuid?>' target='_blank'>
									#<?=$order->id_order?>
								</a>
							</td>
							<td style='min-width:200px;'>
								<? if ($order->refunded) : ?>
									<span class='name' style='display:none;'><?=$order->name?></span>
									<span class='choice' style='color:red;'>
										Refunded! Choose: 
										<a href='#' onclick='javascript:$(this).closest("td").find(".name").show();$(this).closest(".choice").hide();return false;' <?= ($order->pay_if_refunded ? 'style="font-weight:bold;"' : '') ?> >Keep</a> or 
										<a href='#' onclick="javascript:delete_row(this);return false;" <?= (!$order->pay_if_refunded ? 'style="font-weight:bold;"' : '') ?> >
											Remove
										</a>
									</span>
								<? elseif(Crunchbutton_Credit::creditByOrderPaidBy( $order->id_order, Crunchbutton_Credit::PAID_BY_RESTAURANT )) : ?>
									<span class='name' style='display:none;'><?=$order->name?></span>
									<span class='choice' style='color:red;'>
										Restaurant Credit! Choose: 
										<a href='#' onclick='javascript:$(this).closest("td").find(".name").show();$(this).closest(".choice").hide();return false;' <?= ($order->pay_if_refunded ? 'style="font-weight:bold;"' : '') ?> >Keep</a> or 
										<a href='#' onclick="javascript:delete_row(this);return false;" <?= (!$order->pay_if_refunded ? 'style="font-weight:bold;"' : '') ?> >
											Remove
										</a>
									</span>
								<? else : ?>
									<?=$order->name?>
								<? endif ; ?>
							</td>
							<td style='min-width:80px; text-align:right; padding-right:10px;'>
								<?=Util::format_price($order->_display_final_price)?>
							</td>
							<td style='min-width:80px;'>
								<?=$order->pay_type?>
							</td>
							<td style='min-width:80px;'>
								<?=date_format($order->date(),'M d, Y')?>
							</td>
						</tr>
					<?
						endforeach;
					?>
					<tr style="height:10px;">
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td>Cash Subtotal</td>
						<td class="settlement-subtotal settlement-subtotal-grey">$<?=$restaurant->_settlement_cash?></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td>Card Subtotal</td>
						<td class="settlement-subtotal settlement-subtotal-grey">$<?=$restaurant->_settlement_card?></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td>Visa/Mastercard/Amex Charges</td>
						<td class="settlement-subtotal settlement-subtotal-red">$<?=$restaurant->_settlement_cc_fees?></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td>Crunchbutton Fees (<?=$restaurant->fee_restaurant?>%)</td>
						<td class="settlement-subtotal settlement-subtotal-red">$<?=$restaurant->_settlement_cb_fees?></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td>Total Payment</td>
						<td class="settlement-subtotal settlement-subtotal-green">$<?=$restaurant->_settlement_total?></td>
						<td></td>
						<td></td>
					</tr>
				</tbody></table>
			</div>

			<div style='padding:5px; border-bottom:1px solid #ccc;' class='summary_row'>
				<div>
					<a href='#' onclick='javascript: send_summary_email(<?=$restaurant->id?>, "<?=$restaurant->payment_type()->summary_email?>"); return false;'>
						<span class="remove_row icon-user"></span>
					</a>&nbsp;&nbsp;
					<span>Email: </span>
					<span class='RST<?=$restaurant->id?>_summary_email'>
						<?
							if($restaurant->payment_type()->summary_email) {
								echo "<strong>$restaurant->payment_type()->summary_email</strong> ";
							}
							else {
								echo '<strong>None</strong>';
							}
						?>
					</span>
				</div>
			</div>
			
			<div style='padding:5px; border-bottom:1px solid #ccc;' class='summary_row'>
				<div>
					<!--
					<a href='#' onclick='javascript: send_summary_email(<?=$restaurant->id?>, "<?=$restaurant->payment_type()->summary_fax?>"); return false;'>
						<span class="remove_row icon-user"></span>
					</a> -->
					&nbsp;
					<span>Summary Fax: </span>
					<span class='RST<?=$restaurant->id?>_summary_fax'>
						<?
							if($restaurant->summary_fax) {
								echo "<strong>$restaurant->payment_type()->summary_fax</strong> ";
							}
							else {
								echo '<strong>None</strong>';
							}
						?>
					</span>
				</div>
			</div>
			
			<div style='padding:5px; border-bottom:1px solid #ccc;' class='summary_row'>
				<div>
					<!--
					<a href='#' onclick='javascript: send_summary_email(<?=$restaurant->id?>, "<?=$restaurant->payment_type()->summary_email?>"); return false;'>
						<span class="remove_row icon-user"></span>
					</a> -->
					&nbsp;
					<span>Payment Method: </span>
					<span class='RST<?=$restaurant->id?>_payment_method'>
						<strong><?= $restaurant->payment_type()->payment_method ?></strong>
					</span>
				</div>
			</div>
			
			<div style='padding:5px' class='button_row'>
				<button type="submit" class="btn btn-blue admin-order-search" onclick="javascript:(function(){start_payment_popup(<?=$restaurant->id?>);})()"> Start Payment </button>
				&nbsp;
				<button type="submit" class="btn btn-red admin-order-search" onclick="javascript:(function(){start_fax_popup(<?=$restaurant->id?>, '<?=$restaurant->payment_method?>');})()"> Acknowledge no payment for this term </button>
			</div>




		</div>
	<? endforeach; ?>
<? endif ; ?>






