<?
die('#5430 deprecated');
?><style type="text/css">
	.settlement-subtotal {
		text-align: right;
		padding-right: 10px;
		font-weight: bold;
	}
	.settlement-subtotal-grey {
		color: gray;
	}
	.settlement-subtotal-green {
		color: green;
	}
	.settlement-subtotal-red {
		color: red;
	}
</style>

<?
	$this->title = 'Settlement';
?>

<div class="admin-content container-fluid padded">
	<div class="">
		<span class="x" style='display:inline-block; width:100px;'>Date Range</span>
		<?
			$date = new DateTime('now');
			$start = $date->format('m/d/Y');
			$date->modify('7 days ago');
			$end = $date->format('m/d/Y');
		?>

		<span class="content-sub">
			<input name="date-range-start" class="date-picker" type="text" style="width: 90px;" value="<?=$end?>">&nbsp;to&nbsp;
			<input name="date-range-end" class="date-picker" type="text" style="width: 90px;" value="<?=$start?>">
		</span>

		<br>

		<span class="x" style='display:inline-block; width:100px;'>Pay Type</span>
		<span class="content-sub">
			<select name="payment_method">
				<option value=''>All</option>
				<option value='check'>Check</option>
				<option value='deposit'>Deposit</option>
			</select>
		</span>

		<br>

		<span class="x" style='display:inline-block; width:100px;'>Sort by</span>
		<span class="content-sub">
			<select name="order_by">
				<option value='last_payment'>Last Payment</option>
				<option value='alphabetical'>Alphabetical</option>
			</select>
		</span>



	</div>
	<button id="payments_begin" type="submit" class="btn btn-blue admin-order-search"> Begin </button>

	<hr>

	<div id='restaurants_container'>
	</div>

	<div id='start_payment_popup' class='' style='border:1px solid gray; padding:15px; background:white; display:none; width:500px;'>
		<h5>Make Payment</h5>
		<hr>
		<div class='content'></div>
		<hr>
		<button id="go_to_payment_page" type="submit" class="btn btn-blue admin-order-search" > Go To Payment Page </button>
		&nbsp;
		<button id="close_payment_popup" type="submit" class="btn btn-blue admin-order-search" > Close </button>
		&nbsp;
	</div>


<script>

$(function() {
	$(document).on('click', '#payments_begin', function() {
		$.ajax({
			url : '/settlement/begin',
			data : {
				start : $('input[name="date-range-start"]').val(),
				end : $('input[name="date-range-end"]').val(),
				payment_method : $('select[name="payment_method"]').val(),
				order_by : $('select[name="order_by"]').val(),
			},
			method : 'post',
		}).done(function(rsp) {
			$('#restaurants_container').html(rsp);
			$('.RST_container').each(function(i,e){update_totals(e);});
		});
		$('#restaurants_container').html('<i>loading...</i>');
	});

	$('input[name="date-range-start"], input[name="date-range-end"]').bind('keypress', function(e) {
		if(e.keyCode === 13) {
			$('#payments_begin').click();
		}
	});

	$('input[name="date-range-end"]').datepicker({
		defaultDate: "+1w",
		changeMonth: true,
		numberOfMonths: 3,
		onClose: function( selectedDate ) {
			$('input[name="date-range-start"]' ).datepicker('option', 'minDate', selectedDate);
		}
	});

	$('input[name="date-range-start"]').datepicker({
		defaultDate: "+1w",
		changeMonth: true,
		numberOfMonths: 3,
		onClose: function( selectedDate ) {
			$('input[name="date-range-end"]').datepicker('option', 'maxDate', selectedDate);
		}
	});
});

function start_payment_popup(id_restaurant) {
	$('#start_payment_popup').dialog({
		modal: true,
		show : { effect : 'drop', duration : 100, direction : 'up', },
		hide : { effect : 'drop', duration : 100, direction : 'up', },
		width: '360px',
		resizable : false,
	});
	/* set contents of modal */
	$('.ui-dialog-titlebar').hide();
	$('.ui-dialog').css('background','orangered');
	$('.ui-dialog').css('padding','6px');

	$('#start_payment_popup .content').html(
		'You are about to pay '
		+'<span style="font-weight:bold;color:green">' + $('.RST'+id_restaurant+'_container .total_payment').html() + '</span>'
		+' to '
		+'<span style="font-weight:bold;">' + $('.RST'+id_restaurant+'_container .title').html() + '</span>'
		+'.'
		);
	go_to_payment_page = (function() {
		pay_cents = $('.RST'+id_restaurant+'_container .title').html();
		return function() {
			window.open('/restaurants/' + id_restaurant + '/pay?pay_cents=' + $('.RST'+id_restaurant+'_container .total_payment').attr('data_cents'));
		}
	})();
	$('#go_to_payment_page').off('click').on('click', go_to_payment_page);
	$('#close_payment_popup').off('click').on('click', function(){$('#start_payment_popup').dialog('close');});
}



</script>
