<?
	$this->title = 'Settlement';
	$this->titleicon = 'money';
	$this->titleLink = '/settlement';
	$this->title2 = 'Test';
	$this->title2icon = 'time';
?>
<div class="container-fluid padded">
	<div class="row-fluid">
		<div class="box">
			<div class="box-header">
				<span class="title">Math test</span>
			</div>
			<div class="box-content">
				<ul class="box-list">
					<li>
						<label for="id_order"><strong>Order(s) #</strong></label>
						<input type="text" name="id_order" value="" placeholder="24515, 24505, 24497, 24420, 24407" id="id_order" />
					</li>
					<li>
						<button class="calc btn btn-blue"><i class="icon-cogs"></i>&nbsp;Calculate</button>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>
<?php if( $this->pay ) {
	$pay = $this->pay;
	?>
<div class="container-fluid padded">
	<div class="row-fluid">
		<div class="box">
			<div class="box-header">
				<span class="title">Total Due</span>
			</div>
			<div class="box-content">
				<table class="table table-normal">
					<thead>
					<tr>
						<td>Description</td>
						<td>Value</td>
						<td>Formatted Value</td>
					</tr>
					</thead>
					<tbody>
					<tr>
						<td>Credit Card Subtotal</td>
						<td>
							<?php echo $pay['card_subtotal']; ?>
						</td>
						<td>
							<strong><?php echo Util::format_price( $pay['card_subtotal'] ); ?></strong>
						</td>
					</tr>
					<tr>
						<td>Cash Subtotal</td>
						<td>
							<?php echo $pay['cash_subtotal']; ?>
						</td>
						<td>
							<strong><?php echo Util::format_price( $pay['cash_subtotal'] ); ?></strong>
						</td>
					</tr>
					<tr>
						<td>Tax</td>
						<td>
							<?php echo $pay['tax']; ?>
						</td>
						<td>
							<strong><?php echo Util::format_price( $pay['tax'] ); ?></strong>
						</td>
					</tr>
					<tr>
						<td>Delivery Fee</td>
						<td>
							<?php echo $pay['delivery_fee']; ?>
						</td>
						<td>
							<strong><?php echo Util::format_price( $pay['delivery_fee'] ); ?></strong>
						</td>
					</tr>
					<tr>
						<td>Tip</td>
						<td>
							<?php echo $pay['tip']; ?>
						</td>
						<td>
							<strong><?php echo Util::format_price( $pay['tip'] ); ?></strong>
						</td>
					</tr>
					<tr>
						<td>Customer Fee</td>
						<td>
							<?php echo $pay['customer_fee']; ?>
						</td>
						<td>
							<strong><?php echo Util::format_price( $pay['customer_fee'] ); ?></strong>
						</td>
					</tr>
					<tr>
						<td>Markup</td>
						<td>
							<?php echo $pay['markup']; ?>
						</td>
						<td>
							<strong><?php echo Util::format_price( $pay['markup'] ); ?></strong>
						</td>
					</tr>
					<tr>
						<td>Credit Charge</td>
						<td>
							<?php echo $pay['credit_charge']; ?>
						</td>
						<td>
							<strong><?php echo Util::format_price( $pay['credit_charge'] ); ?></strong>
						</td>
					</tr>
					<tr>
						<td>Restaurant Fee</td>
						<td>
							<?php echo $pay['restaurant_fee']; ?>
						</td>
						<td>
							<strong><?php echo Util::format_price( $pay['restaurant_fee'] ); ?></strong>
						</td>
					</tr>
					<tr>
						<td>Promo Gift Card</td>
						<td>
							<?php echo $pay['promo_gift_card']; ?>
						</td>
						<td>
							<strong><?php echo Util::format_price( $pay['promo_gift_card'] ); ?></strong>
						</td>
					</tr>
					<tr>
						<td>Apology Gift Card</td>
						<td>
							<?php echo $pay['apology_gift_card']; ?>
						</td>
						<td>
							<strong><?php echo Util::format_price( $pay['apology_gift_card'] ); ?></strong>
						</td>
					</tr>
					<tr style="background:#b3dc63;">
						<td>Total Due</td>
						<td>
							<?php echo $pay['total_due']; ?>
						</td>
						<td>
							<strong><?php echo Util::format_price( $pay['total_due'] ); ?></strong>
						</td>
					</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

<div class="container-fluid padded">
	<div class="row-fluid">
		<div class="box">
			<div class="box-header">
				<span class="title">Orders</span>
			</div>
			<div class="box-content">
				<table class="table table-normal">
					<thead>
						<tr>
							<td>Order #</td>
							<td>Restaurant</td>
							<td>Card</td>
							<td>Cash</td>
							<td>Tax</td>
							<td>Delivery Fee</td>
							<td>Tip</td>
							<td>Credit Card Charge</td>
							<td>Restaurant Fee</td>
						</tr>
					</thead>
					<tbody>

					<?php foreach( $this->orders as $order ) { ?>
						<tr>
							<td><?php echo $order->id_order; ?></td>
							<td><?php echo $order->restaurant()->name; ?></td>
							<td><?php echo $order->values[ 'subtotal_card' ]; ?></td>
							<td><?php echo $order->values[ 'subtotal_cash' ]; ?></td>
							<td><?php echo $order->values[ 'tax' ]; ?></td>
							<td><?php echo $order->values[ 'delivery_fee' ]; ?></td>
							<td><?php echo $order->values[ 'tip' ]; ?></td>
							<td><?php echo $order->values[ 'card_charge' ]; ?></td>
							<td><?php echo $order->values[ 'restaurant_fee' ]; ?></td>
						</tr>
					<?php } ?>

					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

<?php } ?>
<script type="text/javascript">
$(document).ready( function(){
	$( '.calc' ).on( 'click', function(){
		if( $( '#id_order' ).val() ){
			window.location.href = '/settlement/test/' + $( '#id_order' ).val();
		} else {
			alert( 'You need to type the id_order!' );
			$( '#id_order' ).focus();
		}
	} );
} );
</script>