<?
	die('#5430 deprecated');
	$this->title = 'Settlement';
	$this->titleicon = 'money';
	$this->titleLink = '/settlement';
	$this->title2 = 'Test';
	$this->title2icon = 'time';
?>
<div class="container-fluid padded">
	<div class="row-fluid">
		<div class="box">
			<div class="box-header">
				<span class="title">Math test</span>
			</div>
			<div class="box-content">
				<ul class="box-list">
					<li>
						<label for="id_order"><strong>Order(s) #</strong></label>
						<input type="text" name="id_order" value="<?php echo $this->order_ids; ?>" placeholder="24515, 24505, 24497, 24420, 24407" id="id_order" />
					</li>
					<li>
						<button class="calc-restaurants btn btn-blue"><i class="icon-food"></i>&nbsp;Calculate Restaurants</button>
						&nbsp;&nbsp;&nbsp;
						<button class="calc-drivers btn btn-blue"><i class="icon-truck"></i>&nbsp;Calculate Drivers</button>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>
<?php if( $this->pay_restaurants ) {
	$pay = $this->pay_restaurants;
	?>
<div class="container-fluid padded">
	<div class="row-fluid">
		<div class="box">
			<div class="box-header">
				<span class="title">Total Due:: Restaurants</span>
			</div>
			<div class="box-content">
				<table class="table table-normal">
					<thead>
					<tr>
						<td>Description</td>
						<td>Value</td>
						<td>Formatted Value</td>
					</tr>
					</thead>
					<tbody>
					<tr>
						<td>Credit Card Subtotal</td>
						<td>
							<?php echo $pay['card_subtotal']; ?>
						</td>
						<td>
							<strong><?php echo Util::format_price( $pay['card_subtotal'] ); ?></strong>
						</td>
					</tr>
					<tr>
						<td>Cash Subtotal</td>
						<td>
							<?php echo $pay['cash_subtotal']; ?>
						</td>
						<td>
							<strong><?php echo Util::format_price( $pay['cash_subtotal'] ); ?></strong>
						</td>
					</tr>
					<tr>
						<td>Tax</td>
						<td>
							<?php echo $pay['tax']; ?>
						</td>
						<td>
							<strong><?php echo Util::format_price( $pay['tax'] ); ?></strong>
						</td>
					</tr>
					<tr>
						<td>Delivery Fee</td>
						<td>
							<?php echo $pay['delivery_fee']; ?>
						</td>
						<td>
							<strong><?php echo Util::format_price( $pay['delivery_fee'] ); ?></strong>
						</td>
					</tr>
					<tr>
						<td>Tip</td>
						<td>
							<?php echo $pay['tip']; ?>
						</td>
						<td>
							<strong><?php echo Util::format_price( $pay['tip'] ); ?></strong>
						</td>
					</tr>
					<tr>
						<td>Customer Fee</td>
						<td>
							<?php echo $pay['customer_fee']; ?>
						</td>
						<td>
							<strong><?php echo Util::format_price( $pay['customer_fee'] ); ?></strong>
						</td>
					</tr>
					<tr>
						<td>Markup</td>
						<td>
							<?php echo $pay['markup']; ?>
						</td>
						<td>
							<strong><?php echo Util::format_price( $pay['markup'] ); ?></strong>
						</td>
					</tr>
					<tr>
						<td>Credit Charge</td>
						<td>
							<?php echo $pay['credit_charge']; ?>
						</td>
						<td>
							<strong><?php echo Util::format_price( $pay['credit_charge'] ); ?></strong>
						</td>
					</tr>
					<tr>
						<td>Restaurant Fee</td>
						<td>
							<?php echo $pay['restaurant_fee']; ?>
						</td>
						<td>
							<strong><?php echo Util::format_price( $pay['restaurant_fee'] ); ?></strong>
						</td>
					</tr>
					<tr>
						<td>Promo Gift Card</td>
						<td>
							<?php echo $pay['promo_gift_card']; ?>
						</td>
						<td>
							<strong><?php echo Util::format_price( $pay['promo_gift_card'] ); ?></strong>
						</td>
					</tr>
					<tr>
						<td>Apology Gift Card</td>
						<td>
							<?php echo $pay['apology_gift_card']; ?>
						</td>
						<td>
							<strong><?php echo Util::format_price( $pay['apology_gift_card'] ); ?></strong>
						</td>
					</tr>
					<tr style="background:#b3dc63;">
						<td>Total Due</td>
						<td>
							<?php echo $pay['total_due']; ?>
						</td>
						<td>
							<strong><?php echo Util::format_price( $pay['total_due'] ); ?></strong>
						</td>
					</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
<?php } ?>

<?php if( $this->pay_drivers ) {
	$pay = $this->pay_drivers;
	?>
<div class="container-fluid padded">
	<div class="row-fluid">
		<div class="box">
			<div class="box-header">
				<span class="title">Total Due:: Drivers</span>
			</div>
			<div class="box-content">
				<table class="table table-normal">
					<thead>
					<tr>
						<td>Driver</td>
						<td>Subtotal</td>
						<td>Tax</td>
						<td>Delivery Fee</td>
						<td>Tip</td>
						<td>Customer Fee</td>
						<td>Markup</td>
						<td>Credit Charge</td>
						<td>Restaurant Fee</td>
						<td>Gift Card</td>
						<td>Orders</td>
						<td>Total Due</td>
					</tr>
					</thead>
					<tbody>
					<?php
					foreach( $pay as $key => $val ){ ?>
						<tr>
							<td><?php echo $val[ 'name' ]; ?></td>
							<td><?php echo Util::format_price( $pay[ $key ][ 'subtotal' ] ); ?></td>
							<td><?php echo Util::format_price( $pay[ $key ][ 'tax' ] ); ?></td>
							<td><?php echo Util::format_price( $pay[ $key ][ 'delivery_fee' ] ); ?></td>
							<td><?php echo Util::format_price( $pay[ $key ][ 'tip' ] ); ?></td>
							<td><?php echo Util::format_price( $pay[ $key ][ 'customer_fee' ] ); ?></td>
							<td><?php echo Util::format_price( $pay[ $key ][ 'markup' ] ); ?></td>
							<td><?php echo Util::format_price( $pay[ $key ][ 'credit_charge' ] ); ?></td>
							<td><?php echo Util::format_price( $pay[ $key ][ 'restaurant_fee' ] ); ?></td>
							<td><?php echo Util::format_price( $pay[ $key ][ 'gift_card' ] ); ?></td>
							<td><?php echo count( $pay[ $key ][ 'orders' ] ); ?></td>
							<td><strong><?php echo Util::format_price( $pay[ $key ][ 'total_due' ] ); ?></strong></td>
						</tr>
						<?php
					}
					?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
<?php } ?>




<?php if( $this->orders ) { ?>

<div class="container-fluid padded">
	<div class="row-fluid">
		<div class="box">
			<div class="box-header">
				<span class="title">Orders</span>
			</div>
			<div class="box-content">
				<table class="table table-normal">
					<thead>
						<tr>
							<td>Order #</td>
							<td>Restaurant</td>
							<td>Card</td>
							<td>Cash</td>
							<td>Tax</td>
							<td>Delivery Fee</td>
							<td>Tip</td>
							<td>Credit Card Charge</td>
							<td>Restaurant Fee</td>
							<td>Driver</td>
						</tr>
					</thead>
					<tbody>

					<?php foreach( $this->orders as $order ) { ?>
						<tr>
							<td><?php echo $order->id_order; ?></td>
							<td><?php echo $order->restaurant()->name; ?></td>
							<td><?php echo $order->values[ 'subtotal_card' ]; ?></td>
							<td><?php echo $order->values[ 'subtotal_cash' ]; ?></td>
							<td><?php echo $order->values[ 'tax' ]; ?></td>
							<td><?php echo $order->values[ 'delivery_fee' ]; ?></td>
							<td><?php echo $order->values[ 'tip' ]; ?></td>
							<td><?php echo $order->values[ 'card_charge' ]; ?></td>
							<td><?php echo $order->values[ 'restaurant_fee' ]; ?></td>
							<td><?php echo $order->values[ 'driver' ]; ?></td>
						</tr>
					<?php } ?>

					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

<?php } ?>
<script type="text/javascript">
$(document).ready( function(){
	$( '.calc-restaurants' ).on( 'click', function(){
		if( $( '#id_order' ).val() ){
			window.location.href = '/settlement/test/restaurants/' + $( '#id_order' ).val();
		} else {
			alert( 'You need to type at least one id_order!' );
			$( '#id_order' ).focus();
		}
	} );
	$( '.calc-drivers' ).on( 'click', function(){
		if( $( '#id_order' ).val() ){
			window.location.href = '/settlement/test/drivers/' + $( '#id_order' ).val();
		} else {
			alert( 'You need to type at least one id_order!' );
			$( '#id_order' ).focus();
		}
	} );
} );
</script>