<div class="top-pad"></div>

<div class="content-padding">
	<h1 class="title"><i class="fa fa-paper-plane"></i>Marketing: Outgoing<div class="title-loader" ng-if="loading"><i class="fa fa-refresh fa-spin"></i></div></h1>
	<div class="box-content2 box-content-table">
		<table>
			<tr>
				<td colspan="2"><i class="fa fa-search"></i>&nbsp;&nbsp;<input type="text" ng-model="query.search" id="search" tabindex="1"></td>
			</tr>
			<tr>
				<th>Type</th>
				<td>
					<select ng-model="query.type" name="searchType" tabindex="2">
						<option value="all">All</option>
						<option value="email">Email</option>
						<option value="text">Text</option>
					</select>
				</td>
		</table>
	</div>

	<div class="bar-loader bar-loader-search" ng-class="{'bar-loader-loading': loading}"></div>

	<ng-include src="'/assets/view/listview-marketing-outgoing.html'"></ng-include>
	<ng-include src="'/assets/view/listview-paging.html'"></ng-include>
</div>