<div class="top-pad"></div>

<div class="content-padding">
	<div class="page-title-wrap">
		<h1 class="title"><i class="fa fa-road"></i>Drivers</h1>
	</div>
	<div class="divider"></div>

	<div class="bar-loader bar-loader-search" ng-class="{'bar-loader-loading': loading}"></div>

	<ng-include src="'assets/view/listview-marketing-drivers.html'"></ng-include>
	<ng-include src="'assets/view/listview-paging.html'"></ng-include>
</div>