ALTER TABLE promo ADD `track` TINYINT(1) DEFAULT 1;
ALTER TABLE promo ADD `notify_phone` VARCHAR( 50 ) NULL DEFAULT NULL;
ALTER TABLE promo ADD `name` VARCHAR( 50 ) NULL DEFAULT NULL;
ALTER TABLE promo ADD `contact` TEXT NULL DEFAULT NULL;