INSERT INTO `config` (`id_site`, `key`, `value`, `exposed`)
VALUES
(NULL, 'order-loading-phrase', 'Building a perpetual motion machine', 0),
(NULL, 'order-loading-phrase', 'Locating Atlantis', 0),
(NULL, 'order-loading-phrase', 'Proving the ABC Conjecture', 0),
(NULL, 'order-loading-phrase', 'Counting to 1,000,000,000', 0),
(NULL, 'order-loading-phrase', 'Restoring peace to the Middle East', 0),
(NULL, 'order-loading-phrase', 'Escaping the Bermuda Triangle', 0),
(NULL, 'order-loading-phrase', 'Photographing Bigfoot', 0),
(NULL, 'order-loading-phrase', 'Waiting for the Angels to win the Pennant', 0),
(NULL, 'order-loading-phrase', 'Optomizing the Traveling Salesman\'s route in polynomial time', 0),
(NULL, 'order-loading-phrase', 'Reversing entropy', 0),
(NULL, 'order-loading-phrase', 'Solving a problem like Maria', 0),
(NULL, 'order-loading-phrase', 'Teaching an old dog new tricks', 0),
(NULL, 'order-loading-phrase', 'Identifying JFK\'s killer', 0),
(NULL, 'order-loading-phrase', 'Defining the Tao', 0),
(NULL, 'order-loading-phrase', 'Adding apples to oranges', 0),
(NULL, 'order-loading-phrase', 'Doing a 1080', 0),
(NULL, 'order-loading-phrase', 'Attaining enlightenment', 0),
(NULL, 'order-loading-phrase', 'Having our cake and eating it as well', 0),
(NULL, 'order-loading-phrase', 'Your food is being raised and harvested', 0),
(NULL, 'order-loading-phrase', 'Ending world hunger', 0),
(NULL, 'order-loading-phrase', 'Inventing strong AI', 0),
(NULL, 'order-loading-phrase', 'Finding extraterrestrial life', 0),
(NULL, 'order-loading-phrase', 'Beating the stock market', 0),
(NULL, 'order-loading-phrase', 'Stopping global warming', 0),
(NULL, 'order-loading-phrase', 'Becoming one with Christ', 0),
(NULL, 'order-loading-phrase', 'Describing the universal grammar', 0),
(NULL, 'order-loading-phrase', 'Lowering our Erdos number', 0),
(NULL, 'order-loading-phrase', 'Curing Ebola', 0),
(NULL, 'order-loading-phrase', 'Detaching ourselves from material things', 0),
(NULL, 'order-loading-phrase', 'Understanding consciousness', 0),
(NULL, 'order-loading-phrase', 'Polishing up the Unified Field Theory', 0),
(NULL, 'order-loading-phrase', 'Looking up the definition of runcible', 0),
(NULL, 'order-loading-phrase', 'Burning a tree to power the server', 0);