<?
	$this->title = $this->restaurant->name;
	$this->titleicon = 'food';
	$this->titleLink = '/restaurants/'.$this->restaurant->id_restaurant;

	$this->title2 = 'Holidays';
	$this->title2icon = 'calendar';
?>
<div class="container-fluid padded">
	<div class="row-fluid">
		<div class="container-fluid">
			<div class="row-fluid">
				<div class="span6">
					<div class="box">
						<div class="box-header"><span class="title">Add Date</span></div>
						<div class="box-content padded">
							<h4 class="restaurant-item-title">Add new date</h4>
							<form id="restaurant-bank-info" onsubmit="return false;">
								<div class="row-fluid">
									<div class="span12">
										<div class="span4">
											<strong>Start at:</strong>
										</div>
										<div class="span3">
											<input type="text" class="datepicker span12" id="date_start" name="date_start">
										</div>
										<!-- <div class="span2">
											Hour:
										</div>
										<div class="span3">
											<input type="text" name="date_start_hour" id="date_start_hour" class="span8">
										</div> -->
									</div>
								</div>
								<div class="row-fluid">
									<div class="span12">
										<div class="span4">
											<strong>Finish at:</strong>
										</div>
										<div class="span3">
											<input type="text" class="datepicker span12" id="date_end" name="date_end">
										</div>
										<!-- <div class="span2">
											Hour:
										</div>
										<div class="span3">
											<input type="text" name="date_end_hour" id="date_end_hour" class="span8">
										</div> -->
									</div>
								</div>
								<div class="row-fluid">
									<div class="span12">
										<div class="span4">
											<strong>The restaurant will be</strong>
										</div>
										<div class="span3">
											<select name="type" class="chzn-select" >
													<option value="close" default>Closed</option>
													<option value="open">Opened</option>
											</select>
										</div>
									</div>
								</div>
								<div class="row-fluid">
									<div class="span12">
										<div class="span4">
											
										</div>
										<div class="span3">
											<br/>
											<button type="submit" class="btn btn-blue restaurant-bank-info-button"><i class="icon-save"></i> Save </button> 
											<i class="restaurant-bank-info-button-loading icon-spinner icon-spin" style="display:none;"></i>
										</div>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="box">
			<div class="box-header"><span class="title">Holidays</span></div>
			<div class="box-content">
				<table class="table table-normal">
					<thead>
						<tr>
							<td>Start at</td>
							<td>Finish at</td>
							<td>The restaurant will be </td>
							<td></td>
						</tr>
					</thead>
					<tr>
						<td>10/10/2013</td>
						<td>12/10/2013</td>
						<td>Opened</td>
						<td><button type="submit" class="btn btn-red"><i class="icon-trash"></i> Remove </button> </td>
					</tr>
					<tr>
						<td>14/10/2013</td>
						<td>15/10/2013</td>
						<td>Closed</td>
						<td><button type="submit" class="btn btn-red"><i class="icon-trash"></i> Remove </button> </td>
					</tr>
				</table>
			</div>
		</div>
	</div>
</div>

