<?
/**
 * List all restaurants and the add-new-restaurant button
 *
 * @package  Crunchbutton.Restaurant
 * @category view
 */
?>

<div class="admin-content-wrapper">
	<div class="admin-content">

		<select id="restaurant-id" class="chosen-select" style="width:280px;">
			<option value="" selected>Choose...</option>
			<? foreach (Restaurant::q('select * from restaurant order by name') as $restaurant) : ?>
				<option value="<?=$restaurant->id_restaurant?>"><?=$restaurant->name?></option>
			<? endforeach ; ?>
		</select>
		<div class="divider"></div>
		<br>
		<br>

		<div class="new-restaurant admin-button-workflow">Create New</div>
		<!-- <a href="/restaurants/new"> -->


	</div>
</div>
<div class="divider"></div>

<script type="text/javascript" src="/assets/js/admin_restaurants.js"></script>

