<?
	$this->title = $this->restaurnt->name;
	$this->titleicon = 'food';
	$this->titleLink = '/restaurants/'.$this->restaurnt->id_restaurant;

	$this->title2 = 'Pay';
	$this->title2icon = 'money';
?>
<div class="container-fluid padded">
	<div class="row-fluid">
		<div class="container-fluid padded">
			<div class="row-fluid">
				<div class="span6">

					<div class="box">
						<div class="box-header">
							<div class="title">Payments</div>

							<ul class="nav nav-tabs nav-tabs-right">
								<li class="__active"><a href="#balanced" data-toggle="tab">Balanced</i></a></li>
								<li><a href="#stripe" class="active" data-toggle="tab">Stripe</a></li>
							</ul>

						</div>

						<div class="box-content padded">
							<div class="tab-content">
								<div class="tab-pane __active" id="balanced" style="overflow:hidden;">
									<!-- Balanced stuff BEGIN -->
									<div class="box">
										<div class="box-header"><span class="title">Bank Info</span></div>
										<div class="box-content padded">
											<? if ($this->payment->balanced_bank) : ?>
											<b>This restaurant already has a bank account. <a href="javascript:;" class="restaurant-merchant-button-accountremove">Remove</a></b>
											<? else : ?>
											<h4 class="restaurant-item-title">Add <?=$this->payment->balanced_bank ? 'New ' : ''?>Bank Info</h4>
											<form id="restaurant-bank-info" onsubmit="return false;">
												<table class="admin-restaurant-pay-form">
													<tr>
														<td>Routing #</td>
														<td>
															<input type="text" class="span8" name="routing">
														</td>
													</tr>
													<tr>
														<td>Account #</td>
														<td>
															<input type="text" class="span8" name="account">
														</td>
													</tr>
													<tr>
														<td>Name on Account</td>
														<td>
															<input type="text" class="span8" name="name">
														</td>
													</tr>
													<tr>
														<td>Type</td>
														<td>
															<select name="type" class="chzn-select span8" >
																	<option value="checking" default>Checking</option>
																	<option value="savings">Savings</option>
															</select>
														</td>
													</tr>
													<tr>
														<td colspan="2">
															<br />
															<button type="submit" class="btn btn-blue restaurant-bank-info-button"><i class="icon-save"></i>&nbsp;&nbsp;&nbsp; Save </button> 
															&nbsp;&nbsp;&nbsp;<i class="restaurant-bank-info-button-loading icon-spinner icon-spin" style="display:none;"></i>
														</td>
													</tr>
												</table>
											</form>
											<? endif ; ?>
										</div>
									</div>
									<div class="box">
										<div class="box-header"><span class="title">Merchant Configuration</span></div>
										<div class="box-content padded">
											<? if ($this->payment->balanced_id == c::config()->balanced->sharedMerchant) : ?>
											<b><?=$this->payment->name?> is using a fake merchant configuration. <a href="javascript:;" class="restaurant-merchant-button-fakeremove">Remove</a></b>
											<? elseif ($this->payment->balanced_id) : ?>
											<b><?=$this->payment->name?> already has a merchant configuration. <a href="javascript:;" class="restaurant-merchant-button-fakeremove">Remove</a></b>		
											<? else : ?>
											<h4 class="restaurant-item-title">Create a Merchant Account</h4>
											<form id="restaurant-merchant" onsubmit="return false;">
												<table class="admin-restaurant-pay-form ">
													<? /*
														<tr>
															<td class="label-sub">Merchant Type</td>
															<td class="content-sub">
																<select name="type">
																	<option value="person">Person</option>
																	<option value="business">Business</option>
																</select>
															</td>
														</tr>
														<tr>
															<td>taxid (business)</td>
															<td>
																<input type="text" name="taxid">
															</td>
														</tr>
														<tr>
															<td>person name (business)</td>
															<td>
																<input type="text" name="person">
															</td>
														</tr>
														*/ ?>
													<tr>
														<td>Name</td>
														<td>
															<input type="text" class="span8" name="name">
														</td>
													</tr>
													<tr>
														<td>Date of Birth (YYYY-MM)</td>
														<td>
															<input type="text" name="dob" class="span8">
														</td>
													</tr>
													<tr>
														<td>Address</td>
														<td>
															<input type="text" name="address" class="span8">
														</td>
													</tr>
													<tr>
														<td>ZIP code</td>
														<td>
															<input type="text" name="zip" class="span8">
														</td>
													</tr>
													<tr>
														<td colspan="2">
															<br />
															<button type="submit" class="btn btn-blue restaurant-merchant-button"><i class="icon-save"></i>&nbsp;&nbsp;&nbsp; Save </button> 
															<button type="submit" class="btn btn-blue restaurant-merchant-button-fake"><i class="icon-globe"></i>&nbsp;&nbsp;&nbsp; Use global merchant </button>
														</td>
													</tr>
												</table>
											</form>
											<? endif ; ?>
										</div>
									</div>
									<div class="box">
										<div class="box-header"><span class="title">Send Payment</span></div>
										<div class="box-content padded">
											<form id="restaurant-pay" onsubmit="return false;">
												<table class="admin-restaurant-pay-form">
													<tr>
														<td>Amount</td>
														<td>
															<input type="text" name="amount" class="span8">
														</td>
													</tr>
													<tr>
														<td>Note</td>
														<td>
															<input type="text" name="note" class="span8">
														</td>
													</tr>
													<tr>
														<td colspan="2">
															<br />
															<button type="submit" class="btn btn-blue restaurant-pay-button"><i class="icon-cloud-upload"></i>&nbsp;&nbsp;&nbsp; Send </button>
														</td>
													</tr>
												</table>
											</form>
										</div>
									</div>
									<!-- Balanced stuff END -->
								</div>
								<div class="tab-pane active" id="stripe" style="overflow:hidden;">
<!-- Stripe stuff - BEGIN -->
									<div class="box">
										<div class="box-header"><span class="title">Bank Info</span></div>
										<div class="box-content padded">
											
											<h4 class="restaurant-item-title">Add Bank Info</h4>
											<form id="restaurant-bank-info-stripe" onsubmit="return false;">
												<table class="admin-restaurant-pay-form">
													<tr>
														<td>Name on Account</td>
														<td>
															<input type="text" class="span8" name="name">
														</td>
													</tr>
													<tr>
														<td>Routing #</td>
														<td>
															<input type="text" class="span8" name="stripe-routing-number" value="111000025">
														</td>
													</tr>
													<tr>
														<td>Account #</td>
														<td>
															<input type="text" class="span8" name="stripe-account-number" value="000123456789">
														</td>
													</tr>
													<tr>
														<td>Type</td>
														<td>
															<select name="stripe-type" class="chzn-select span8" >
																	<option value="individual" default>Individual</option>
																	<option value="corporation">Corporation</option>
															</select>
														</td>
													</tr>

													<tr>
														<td colspan="2">
															<br />
															<button type="button" class="btn btn-blue restaurant-bank-info-stripe-button"><i class="icon-save"></i>&nbsp;&nbsp;&nbsp; Save </button> 
															&nbsp;&nbsp;&nbsp;<i class="restaurant-bank-info-stripe--button-loading icon-spinner icon-spin" style="display:none;"></i>
														</td>
													</tr>
												</table>
											</form>

										</div>
									</div>

<!-- Stripe stuff - END -->

								</div>
							</div>
						</div>
					</div>

					
				</div>
				<div class="span6">
					<div class="box">
						<div class="box-header">
							<span class="title">Payment info</span>
						</div>
						<div class="box-content">
							<form id="restaurant-payment-info" class="fill-up" onsubmit="return false;">
								<ul class="box-list">
									<li>
										<span>Charge Credit Fees?</span>
										<span class="pull-right">
										<input type="checkbox" name="charge_credit_fee" id="charge_credit_fee" class="iButton-icons" <?=$this->payment->charge_credit_fee ? 'checked' : ''?>>
										</span>
									</li>
									<li>
										<span>Waive Fee 1st Month?</span>
										<span class="pull-right">
										<input type="checkbox" name="waive_fee_first_month" id="waive_fee_first_month" class="iButton-icons" <?=$this->payment->waive_fee_first_month ? 'checked' : ''?>>
										</span>
									</li>
									<li>
										<span>Pay For Apology Credits?</span>
										<span class="pull-right">
											<input type="checkbox" name="pay_promotions" id="pay_promotions" class="iButton-icons" <?=$this->payment->pay_promotions ? 'checked' : ''?>>
										</span>
									</li>
									<li class="input">
										<span>Max Apology Credit</span>
										<span class="pull-right span9">
											<input type="number" class="fill-up" name="max_apology_credit" maxlength="5" id="max_apology_credit" value="<?php echo $this->payment->max_apology_credit;?>" />
										</span>
									</li>
									<li>
										<span>Pay For Promotions?</span>
										<span class="pull-right">
											<input type="checkbox" name="pay_apology_credits" id="pay_apology_credits" class="iButton-icons" <?=$this->payment->pay_apology_credits ? 'checked' : ''?>>
										</span>
									</li>
									<li class="input">
										<span>Check Address</span>
										<span class="pull-right span9">
											<input type="text" class="fill-up" name="check_address" maxlength="255" id="check_address" value="<?php echo $this->payment->check_address;?>" />
										</span>
									</li>
									<li class="input">
										<span>Contact Name</span>
										<span class="pull-right span9">
											<input type="text" name="contact_name" maxlength="255" id="contact_name" value="<?php echo $this->payment->contact_name;?>" />
										</span>
									</li>
									<li class="input">
										<span>Summary Fax</span>
										<span class="pull-right span9">
											<input type="text" name="summary_fax" maxlength="255" id="summary_fax" value="<?php echo $this->payment->summary_fax;?>" />
										</span>
									</li>
									<li class="input">
										<span>Summary Email</span>
										<span class="pull-right span9">
											<input type="text" name="summary_email" maxlength="255" id="summary_email" value="<?php echo $this->payment->summary_email;?>" />
										</span>
									</li>
									<li class="input">
										<span>Summary Frequency</span>
										<span class="pull-right span9">
											<input type="number" name="summary_frequency" maxlength="5" id="summary_frequency" value="<?php echo $this->payment->summary_frequency;?>" />
										</span>
									</li>
									<li class="input">
										<span>Summary Method</span>
										<span class="pull-right span9">
											<?php 
												$options = array( 'fax', 'email' );
												?>
											<select name="summary_method" id="summary_method" class="uniform">
												<option value="">None</option>
												<? foreach ($options as $option) { 
													$selected = ( $option == $this->payment->summary_method ) ? 'selected="selected"' : ''; ?>
												<option <?=$selected?> value="<?=$option?>"><?=$option?></option>
												<? } ?>
											</select>
										</span>
									</li>
									
									<li class="input">
										<span>Legal Name for Payment</span>
										<span class="pull-right span9">
											<input type="text" name="legal_name_payment" maxlength="255" id="legal_name_payment" value="<?php echo $this->payment->legal_name_payment;?>" />
										</span>
									</li>
									<li class="input">
										<span>Tax ID # </span>
										<span class="pull-right span9">
											<input type="text" name="tax_id" maxlength="255" id="tax_id" value="<?php echo $this->payment->tax_id;?>" />
										</span>
									</li>
									<div style="clear: both;"></div>
									<li class="input">
										<span>Payment Method</span>
										<span class="pull-right">
											<?php 
												$options = array( 'check', 'deposit' );
												?>
											<select name="payment_method" id="payment_method" class="uniform">
												<? foreach ($options as $option) { 
													$selected = ( $option == $this->payment->payment_method ) ? 'selected="selected"' : ''; ?>
												<option <?=$selected?> value="<?=$option?>"><?=$option?></option>
												<? } ?>
											</select>
										</span>
									</li>
									<li class="input">
										<span>Pay Another Restaurant</span>
										<span class="pull-right span9">
											<select class="chzn-select" name="id_restaurant_pay_another_restaurant" id="id_restaurant_pay_another_restaurant">
												<option value="" selected>Choose...</option>
												<? foreach (Restaurant::q('select * from restaurant order by name') as $restaurant) :
													$selected = ( $restaurant->id_restaurant == $this->payment->id_restaurant_pay_another_restaurant ) ? 'selected="selected"' : ''; ?>
												<option <?=$selected?> value="<?=$restaurant->id_restaurant?>"><?=$restaurant->name?></option>
												<? endforeach ; ?>
											</select>
										</span>
									</li>
									<li class="input">
										<button type="button" class="btn btn-blue payment-info-button"><i class="icon-money"></i>  Save Payment changes</button>
										<span class="pull-right">
											<div class="alert-payment-info" style="display:none">
												<span class="alert-message"><strong>Ok!</strong> Payment info saved!</span>
											</div>
										</span>
									</li>
								</ul>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="box">
			<div class="box-header"><span class="title">Recent Payments</span></div>
			<div class="box-content padded">
				<table width="100%" cellpadding="4" cellspacing="4">
					<tr>
						<th>Date</th>
						<th>Amount</th>
						<th>Note</th>
					</tr>
					<? foreach ($this->restaurant->payments() as $payment) : ?>
					<tr>
						<td><?=$payment->date?></td>
						<td>$<?=$payment->amount?></td>
						<td><?=$payment->note?></td>
					</tr>
					<? endforeach; ?>
				</table>
			</div>
		</div>
	</div>
</div>

<script>
	$(function() {
		
		$('.restaurant-merchant-button').click(function() {
			var form = $(this).closest('form');
			$.post('/api/restaurant/<?=$this->payment->id_restaurant?>/merchant', {
				type: 'person', /* form.find('[name="type"]').val() */
				name: form.find('[name="name"]').val(),
				address: form.find('[name="address"]').val(),
				zip: form.find('[name="zip"]').val(),
/*				person: form.find('[name="person"]').val(),
				taxid: form.find('[name="taxid"]').val(), */
				dob: form.find('[name="dob"]').val()
			}, function() {
				location.href = location.href;
			});
		});


		/* Form payment info */
		$( document ).on( 'click', '.payment-info-button', function(){ 

			var parent = $( this ).parent();
			var button = parent.html();
		
			parent.html( '<i class="icon-spinner icon-spin"></i> Processing' );

			$.post('/api/restaurant/<?=$this->payment->id_restaurant?>/paymentinfo', {
				payment_method : ( $( '#payment_method' ).val() ),
				id_restaurant_pay_another_restaurant : ( $( '#id_restaurant_pay_another_restaurant' ).val() ),
				check_address : ( $( '#check_address' ).val() ),
				contact_name : ( $( '#contact_name' ).val() ),
				summary_fax : ( $( '#summary_fax' ).val() ),
				summary_email : ( $( '#summary_email' ).val() ),
				summary_frequency : ( $( '#summary_frequency' ).val() ),
				legal_name_payment : ( $( '#legal_name_payment' ).val() ),
				summary_method : ( $( '#summary_method' ).val() ),
				max_apology_credit : ( $( '#max_apology_credit' ).val() ),
				tax_id : ( $( '#tax_id' ).val() ),
				charge_credit_fee : ( $( '#charge_credit_fee' ).is( ':checked' ) ? '1' : 0 ),
				waive_fee_first_month : ( $( '#waive_fee_first_month' ).is( ':checked' ) ? '1' : 0 ),
				pay_promotions : ( $( '#pay_promotions' ).is( ':checked' ) ? '1' : 0 ),
				pay_apology_credits : ( $( '#pay_apology_credits' ).is( ':checked' ) ? '1' : 0 )
			}, function( ) {
				$( '.alert-payment-info' ).show();
				setTimeout( function(){
					parent.html( button );
					$( '.alert-payment-info' ).show();
					setTimeout( function(){
						$( '.alert-payment-info' ).hide();
					}, 2500 );
				}, 500 );
			} );

		} );

		$('.restaurant-merchant-button-fake').click(function() {
			$.post('/api/restaurant/<?=$this->payment->id_restaurant?>/fake-merchant', function() {
				location.href = location.href;
			});
		});
		
		$('.restaurant-merchant-button-fakeremove').click(function() {
			$.post('/api/restaurant/<?=$this->payment->id_restaurant?>/fakeremove-merchant', function() {
				location.href = location.href;
			});
		});
		
		$('.restaurant-merchant-button-accountremove').click(function() {
			$.post('/api/restaurant/<?=$this->payment->id_restaurant?>/remove-bankinfo', function() {
				location.href = location.href;
			});
		});		

		$('.restaurant-bank-info-button').click(function() {
			var form = $(this).closest('form');
			$( '.restaurant-bank-info-button-loading' ).show();
			$.ajax({
				type: 'POST',
				url: '/api/restaurant/<?=$this->payment->id_restaurant?>/bankinfo',
				data: {
								routing: form.find('[name="routing"]').val(),
								account: form.find('[name="account"]').val(),
								type: form.find('[name="type"]').val(),
								name: form.find('[name="name"]').val()
							}
			}).done(function( data ) {
				if( data.success ){
					location.href = location.href;
				} else {
					$( '.restaurant-bank-info-button-loading' ).hide();
					alert( 'Error: see the console!'  );
					console.log('Err:', data );	
				}
			}).fail(function(jqXHR, textStatus) {
				$( '.restaurant-bank-info-button-loading' ).hide();
				alert( 'Error: see the console!'  );
				console.log('Err:', jqXHR.responseText);
			});
		});

		$('.restaurant-pay-button').click(function() {
			var form = $(this).closest('form');
			$.ajax({
				type: 'POST',
				url: '/api/restaurant/<?=$this->payment->id_restaurant?>/credit',
				data: { amount: form.find('[name="amount"]').val(), note: form.find('[name="note"]').val() },
				complete: function(){
					alert( 'done' );
					
				}
			})
		});


		$('.restaurant-bank-info-stripe-button').click(function() {

			var routingNumber = $('[name=stripe-routing-number]').val();
			var accountNumber = $('[name=stripe-account-number]').val();
			var country = 'US';
			if( $.trim( routingNumber ) == '' ){
				alert( 'Please type the Routing!' );
				$('[name=stripe-routing-number]').focus();
				return;
			}

			if( !Stripe.bankAccount.validateRoutingNumber( routingNumber, country )  ){
				alert( 'Please type a valid Routing!' );
				$('[name=stripe-routing-number]').focus();
				return;
			}

			if( $.trim( accountNumber ) == '' ){
				alert( 'Please type the Account!' );
				$('[name=stripe-account-number]').focus();
				return;
			}

			if( !Stripe.bankAccount.validateAccountNumber( accountNumber, country )  ){
				alert( 'Please type a valid Account!' );
				$('[name=stripe-account-number]').focus();
				return;
			}

			$( '.restaurant-bank-info-stripe-button-loading' ).show();

			Stripe.bankAccount.createToken({
				country: country,
				routingNumber: routingNumber,
				accountNumber: accountNumber,
			}, function( status, response ){
				console.log('reponse', status, response);
			});


		} );

	});
</script>
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<script type="text/javascript">Stripe.setPublishableKey('<?=c::config()->stripe->{c::getEnv()}->{'public'}?>');</script>