<?
/**
 * Shows the Restaurant form for the admin
 *
 * @package Crunchbutton.Admin.Restaurant
 * @category view
 */

?>


<div id=admin-body-content>

	<div id=admin-top-content-bar>
		<div class=admin-jump-list>
			Jump to: 
			<a href=#vitals>vitals</a> 
			<a href=#menu>menu</a> 
			<a href=#notes>notes</a> 
			<a href=# class=button-fax>fax</a> 
			<a href=# class=button-pay>pay</a> 
		</div>
		<div id=admin-top-button-group>
			<a target='_blank' id=view-on-site-button><div class=admin-button>View on Site</div></a>
			<div id=legacy-button class=admin-button>Old Admin</div>
			<div id=revert-button class=admin-button>Revert</div>
		</div>
	</div>


	<div class=admin-h3>Basic Information</div>

	<div class=admin-item>
		<div class=admin-item-left>
			<div class=admin-item-name>Name</div>
			<div class=admin-item-desc>for display</div>
		</div>
		<div class=admin-item-right>
			<input type=input id=restaurant-name />
		</div>
	</div>

	<div class=admin-item>
		<div class=admin-item-left>
			<div class=admin-item-name>Permalink</div>
			<div class=admin-item-desc>crunchbutton.com/food-delivery/&lt;permalink></div>
		</div>
		<div class=admin-item-right>
			<input type=input id=restaurant-permalink />
		</div>
	</div>

	<div class=admin-item>
		<div class=admin-item-left>
			<div class=admin-item-name>Tagline 1</div>
			<div class=admin-item-desc>on the restaurants list page</div>
		</div>
		<div class=admin-item-right>
			<input type=input id=restaurant-short-description />
		</div>
	</div>

	<div class=admin-item>
		<div class=admin-item-left>
			<div class=admin-item-name>Tagline 2</div>
			<div class=admin-item-desc>on the restaurant order page</div>
		</div>
		<div class=admin-item-right>
			<input type=input id=restaurant-message />
		</div>
	</div>

	<div class=admin-item>
		<div class=admin-item-left>
			<div class=admin-item-name>Phone Number</div>
			<div class=admin-item-desc>publicly listed</div>
		</div>
		<div class=admin-item-right>
			<input type=input id=restaurant-phone />
		</div>
	</div>

	<div class=admin-item>
		<div class=admin-item-left>
			<div class=admin-item-name>Address</div>
			<div class=admin-item-desc>for delivery radius and pickup</div>
		</div>
		<div class=admin-item-right>
			<textarea id=restaurant-address></textarea>
			<div class=admin-item-col-med>
				Latitude
				<input type=input id=restaurant-lat />
			</div>
			<div class=admin-item-col-med>
				Longitude
				<input type=input id=restaurant-lng />
			</div>
			<div class=admin-item-col-large>
				<div class=admin-map id=restaurant-map></div>
			</div>
		</div>
	</div>

	<div class=admin-item>
		<div class=admin-item-left>
			<div class=admin-item-name>Active</div>
			<div class=admin-item-desc>is it listed on the live site</div>
		</div>
		<div class=admin-item-right>
			<div class=admin-item-col-small id=restaurant-active-container></div>
		</div>
	</div>

	<div class=admin-item>
		<div class=admin-item-left>
			<div class=admin-item-name>Open for Business</div>
			<div class=admin-item-desc>is this restaurant accepting orders during open hours</div>
		</div>
		<div class=admin-item-right>
			<div class=admin-item-col-small id=restaurant-open-for-business-container></div>
		</div>
	</div>

	<div class=admin-item>
		<div class=admin-item-left>
			<div class=admin-item-name>Image</div>
		</div>
		<div class=admin-item-right id=restaurant-image>
			<a target='_blank'><img></img></a>
		</div>
	</div>

	<div class=admin-item></div><!-- for the border line -->



	<a name=vitals></a>
	<div class=admin-h3>Vitals</div>

	<div class=admin-item>
		<div class=admin-item-left>
			<div class=admin-item-name>Notifications</div>
			<div class=admin-item-desc>what happens when an order goes through</div>
		</div>
		<div class=admin-item-right>
			<div class=admin-item-col-x-wide id=notifications-container></div>
			<div class=admin-item-col-med>
				<div class=admin-button-workflow id=add-notification>add another method</div>
			</div>
		</div>
	</div>

	<div class=admin-item>
		<div class=admin-item-left>
			<div class=admin-item-name>Timezone</div>
			<div class=admin-item-desc>where the restaurant is</div>
		</div>
		<div class=admin-item-right>
			<select id=restaurant-timezone>
				<option value=America/New_York>Eastern</option>
				<option value=America/Chicago>Central</option>
				<option value=America/Denver>Mountain</option>
				<option value=America/Los_Angeles>Pacific</option>
			</select>
		</div>
	</div>

	<div class=admin-item>
		<div class=admin-item-left>
			<div class=admin-item-name>Hours</div>
			<div class=admin-item-desc>restaurant's actual open hours</div>
			<div class=admin-item-desc>e.g. 12PM - 2:30AM</div>
			<div class=admin-item-desc>use a comma for multiple time segments</div>
		</div>
		<div class=admin-item-right id=restaurant-hours>
			<div class=admin-item-right-row>
				<div class=admin-item-col-wide>
					<input type=input id=restaurant-hours-mon />
				</div>
				<div class=admin-item-col-small> Monday </div>
				<div class=admin-item-col-med> </div>
			</div>
			<div class=admin-item-right-row>
				<div class=admin-item-col-wide>
					<input type=input id=restaurant-hours-tue />
				</div>
				<div class=admin-item-col-small> Tuesday</div>
				<div class=admin-item-col-med>
					<div class=admin-button-workflow id=copy-tue-from-mon>
						copy from Mon
					</div>
				</div>
			</div>
			<div class=admin-item-right-row>
				<div class=admin-item-col-wide>
					<input type=input id=restaurant-hours-wed />
				</div>
				<div class=admin-item-col-small> Wednesday</div>
				<div class=admin-item-col-med>
					<div class=admin-button-workflow id=copy-wed-from-tue>
						copy from Tue
					</div>
				</div>
			</div>
			<div class=admin-item-right-row>
				<div class=admin-item-col-wide>
					<input type=input id=restaurant-hours-thu />
				</div>
				<div class=admin-item-col-small> Thursday</div>
				<div class=admin-item-col-med>
					<div class=admin-button-workflow id=copy-thu-from-wed>
						copy from Wed
					</div>
				</div>
			</div>
			<div class=admin-item-right-row>
				<div class=admin-item-col-wide>
					<input type=input id=restaurant-hours-fri />
				</div>
				<div class=admin-item-col-small> Friday</div>
				<div class=admin-item-col-med>
					<div class=admin-button-workflow id=copy-fri-from-thu>
						copy from Thu
					</div>
				</div>
			</div>
			<div class=admin-item-right-row>
				<div class=admin-item-col-wide>
					<input type=input id=restaurant-hours-sat />
				</div>
				<div class=admin-item-col-small> Saturday</div>
				<div class=admin-item-col-med>
					<div class=admin-button-workflow id=copy-sat-from-fri>
						copy from Fri
					</div>
				</div>
			</div>
			<div class=admin-item-right-row>
				<div class=admin-item-col-wide>
					<input type=input id=restaurant-hours-sun />
				</div>
				<div class=admin-item-col-small> Sunday</div>
				<div class=admin-item-col-med>
					<div class=admin-button-workflow id=copy-sun-from-sat>
						copy from Sat
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class=admin-item>
		<div class=admin-item-left>
			<div class=admin-item-name>Transactions</div>
			<div class=admin-item-desc>allowed payment methods</div>
		</div>
		<div class=admin-item-right>
			<div class=admin-item-col-small>
				Cash
				<div id=restaurant-cash-container></div>
			</div>
			<div class=admin-item-col-small>
				Credit
				<div id=restaurant-credit-container></div>
			</div>
		</div>
	</div>

	<div class=admin-item>
		<div class=admin-item-left>
			<div class=admin-item-name>Delivery Options</div>
			<div class=admin-item-desc></div>
		</div>
		<div class=admin-item-right>
			<div class=admin-item-col-small>
				<div class=admin-item-label>Delivery</div>
				<div id=restaurant-delivery-container></div>
			</div>
			<div class=admin-item-col-small>
				<div class=admin-item-label>Delivery minimum ($)</div>
				<input type=input id=restaurant-delivery-min />
			</div>
			<div class=admin-item-col-small>
				<div class=admin-item-label>Based on</div>
				<select id=restaurant-delivery-min-amt>
					<option value=subtotal>Subtotal</option>
					<option value=total>Total</option>
				</select>
			</div>
			<div class=admin-item-col-small>
				<div class=admin-item-label>Delivery fee ($)</div>
				<input type=input id=restaurant-delivery-fee />
			</div>
			<div class=admin-item-col-small>
				<div class=admin-item-label>Radius (miles)</div>
				<input type=input id=restaurant-delivery-radius />
			</div>
			<div class=admin-item-col-small>
				<div class=admin-item-label>Est. time (minutes)</div>
				<input type=input id=restaurant-delivery-estimated-time />
			</div>
		</div>
	</div>

	<div class=admin-item>
		<div class=admin-item-left>
			<div class=admin-item-name>Takeout Options</div>
			<div class=admin-item-desc></div>
		</div>
		<div class=admin-item-right>
			<div class=admin-item-col-small>
				<div class=admin-item-label>Takeout</div>
				<div id=restaurant-takeout-container></div>
			</div>
			<div class=admin-item-col-small>
				<div class=admin-item-label>Est. time (minutes)</div>
				<input type=input id=restaurant-pickup-estimated-time />
			</div>
		</div>
	</div>

	<div class=admin-item>
		<div class=admin-item-left>
			<div class=admin-item-name>Taxes and Fees</div>
			<div class=admin-item-desc></div>
		</div>
		<div class=admin-item-right>
			<div class=admin-item-col-small>
				Restaurant fee (%)
				<input type=input id=restaurant-fee-restaurant />
			</div>
			<div class=admin-item-col-small>
				Customer fee (%)
				<input type=input id=restaurant-fee-customer />
			</div>
			<div class=admin-item-col-small>
				Tax charged (%)
				<input type=input id=restaurant-tax />
			</div>
		</div>
	</div>

	<div class=admin-item>
		<div class=admin-item-left>
			<div class=admin-item-name>Sorting</div>
			<div class=admin-item-desc>
				see <a href='https://github.com/crunchbutton/crunchbutton/issues/787#issuecomment-15988987' target='_blank'>here</a> for explanation
			</div>
		</div>
		<div class=admin-item-right>
			<div class=admin-item-col-small>
				Sort weight adjustment
				<input type=input id=restaurant-weight-adj />
			</div>
		</div>
	</div>

	<div class=admin-item>
		<div class=admin-item-left>
			<div class=admin-item-name>Actions</div>
		</div>
		<div class=admin-item-right>
			<div class=admin-item-col-med>
				<a class=button-pay target='_blank'><div class=admin-button-workflow>send payment</div></a>
			</div>
			<div class=admin-item-col-med>
				<a class=button-fax target='_blank'><div class=admin-button-workflow>send a fax</div></a>
			</div>
		</div>
	</div>

	<div class=admin-item></div><!-- for the border line -->


	<a name=menu></a>
	<div class=admin-h3>Menu</div>

	<div id=restaurant-menu-container>
	</div>
	<div class=admin-item>
		<div class=admin-item-left>
			<div class=admin-button-workflow id=add-menu-category>add another category</div>
		</div>
	</div>
	<!--
	<div class=admin-item>
		<div class=admin-item-left>
			<div class=admin-item-name>Full Menu</div>
			<div class=admin-item-desc></div>
		</div>
		<div class=admin-item-right id=restaurant-menu-container>
		</div>
	</div>
	-->

	<div class=admin-item></div><!-- for the border line -->


	<a name=notes></a>
	<div class=admin-h3>Notes</div>

	<div class=admin-item>
		<div class=admin-item-left>
			<div class=admin-item-name>Email</div>
			<div class=admin-item-desc>used internally</div>
		</div>
		<div class=admin-item-right>
			<input type=input id=restaurant-email />
		</div>
	</div>

	<div class=admin-item>
		<div class=admin-item-left>
			<div class=admin-item-name>General Notes</div>
			<div class=admin-item-desc></div>
		</div>
		<div class=admin-item-right>
			<textarea id=restaurant-notes></textarea>
		</div>
	</div>

	<div class=admin-item>
		<div class=admin-item-left>
			<div class=admin-item-name>TODO</div>
			<div class=admin-item-desc></div>
		</div>
		<div class=admin-item-right>
			<textarea id=restaurant-notes-todo></textarea>
		</div>
	</div>

	<div class=admin-item>
		<div class=admin-item-left>
			<div class=admin-item-name>About the Owner</div>
			<div class=admin-item-desc></div>
		</div>
		<div class=admin-item-right>
			<textarea id=restaurant-notes-owner></textarea>
		</div>
	</div>

	<div class=admin-item></div><!-- for the border line -->


<!-- floating things -->

	<div id=float-bottom-right-container>
		<div id=save-button class=admin-button>Save</div>
	</div>
	<div id=float-bottom-left-container>
		<div id=admin-msg></div>
	</div>

</div>


<!-- templates -->

<div class=template-container>

	<div class=admin-toggle-active id=toggle-template>active</div>

	<div class=admin-notifications id=notifications-template></div>

	<div class=admin-notification id=notification-template>
		<div class=admin-item-col-small>
			<div class=admin-toggle-active></div>
		</div>
		<div class="admin-item-col-med-2 restaurant-notification">
			<select>
				<option value=fax>Fax</option>
				<option value=sms>Text Message</option>
				<option value=email>Email</option>
				<option value=phone>Phone Call</option>
				<option value=url>URL Request</option>
				<option value=confirmation>Confirmation Phone Call</option>
			</select>
		</div>
		<div class=admin-item-col-med-2>
			<input type=input name=val />
		</div>
	</div>

	<div class=admin-menu id=menu-template>
		<div class=admin-menu-categories></div>
	</div>
	<div class="admin-menu-category admin-item" id=menu-category-template>
		<div class=admin-item-left>
			<input type=hidden class=admin-menu-category-id />
			<input type=hidden class=admin-menu-category-loc />
			<input type=hidden class=admin-menu-category-sort />
			<input type=input class=admin-menu-category-name placeholder="Category name" />
			<div class=hr></div>
			<div class="admin-button-workflow add-menu-dish">add dish</div> &nbsp;
			<div class="admin-button-workflow delete-menu-category">delete category</div> &nbsp;
			<div class=hr></div>
			<div class="move_category_up sprite-arrow_up" title="Move this category up"></div>
			<div class="move_category_down sprite-arrow_down" title="Move this category down"></div>
		</div>
		<div class="admin-item-right restaurant-dishes-container"></div>
	</div>
	<div class=admin-menu-dish id=menu-dish-template>
		<input type=hidden class=admin-menu-dish-active-id />
		<input type=hidden class=admin-menu-dish-id />
		<input type=hidden class=admin-menu-dish-id_dish />
		<input type=hidden class=admin-menu-dish-sort />
		<input type=hidden class=admin-menu-dish-top />
		<input type=hidden class=admin-menu-dish-top_name />
		<input type=hidden class=admin-menu-dish-image />      <!-- expose this field? -->
		<div class=admin-item-col-small>
			<div class=admin-menu-dish-active-button></div>
		</div>
		<div class=admin-item-col-med-2>
			<input type=input class=admin-menu-dish-name placeholder="Dish name" />
		</div>
		<div class=admin-item-col-small>
			<input type=input class=admin-menu-dish-price placeholder=$ />
		</div>
		<div class=admin-item-col-small>
			<div class="admin-button-workflow-fit details-button">details</div>
		</div>
		<div class="admin-item-col-no-pad vertical-middle">
			<div class="move_dish_up sprite-arrow_up" title="Move this dish up"></div>
			<div class="move_dish_down sprite-arrow_down" title="Move this dish down"></div>
			<div class="dish_lightning sprite-bolt" title="Copy this dish or its options"></div>
			<div class="delete-menu-dish sprite-x_alt" title="Delete this dish"></div>
		</div>
		<div class="admin-item-right hidden admin-menu-dish-details">
			Description
			<textarea class="small admin-menu-dish-description"></textarea>
			<div class=admin-option-group-hr></div>
			<div class=admin-item-col-fit>
				<label>
					<input type=checkbox class=admin-menu-dish-expand-view>
					Expanded view when added to cart
				</label>
			</div>
			<div class=admin-option-group-hr></div>
			<div class=admin-item-col-med>
				<div class="admin-button-workflow-fit add-checkbox-option">add checkbox option</div>
			</div>
			<div class=admin-item-col-med>
				<div class="admin-button-workflow-fit add-option-group">add multi-valued option</div>
			</div>
			<div class=admin-option-group-hr></div>
			<div class=dish-option-groups-container></div>
		</div>
	</div>
	<div class=admin-menu-option-group id=menu-option-group-template>
		<input type=hidden class=admin-menu-option-group-id />
		<input type=hidden class=admin-menu-option-group-id_dish_option />
		<input type=hidden class=admin-menu-option-group-id_option />
		<input type=hidden class=admin-menu-option-group-id_option_parent />
		<input type=hidden class=admin-menu-option-group-id_restaurant />
		<input type=hidden class=admin-menu-option-group-sort />
		<input type=hidden class=admin-menu-option-group-price placeholder=$ />
		<div class=admin-item-col-med-2>
			<input type=input class=admin-menu-option-group-name placeholder="Option name" />
		</div>
		<div class=hidden>
			<select class=admin-menu-option-group-type>
				<option value=select selected>Choose one</option>
				<option value=check>Choose many</option>
			</select>
		</div>
		<div class="admin-item-col-fit vertical-middle">
			<div class="move_option_group_up sprite-arrow_up" title="Move this option up"></div>
			<div class="move_option_group_down sprite-arrow_down" title="Move this option down"></div>
			<div class="delete-option-group sprite-x_alt" title="Delete this option"></div>
		</div>
		<input type=hidden class=admin-menu-option-group-description placeholder=Description />
		<br>
		<div class=admin-menu-options-container></div>
		<div class="admin-item-col-wide not-visible-for-basic-option-group">
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<div class="admin-button-workflow add-option">add another value</div>
		</div>
		<div class=admin-option-group-hr></div>
	</div>
	<div class=admin-menu-option id=menu-option-template>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		<input type=hidden class=admin-menu-option-id />
    <input type=hidden class=admin-menu-option-id_dish_option />
    <input type=hidden class=admin-menu-option-id_option />
    <input type=hidden class=admin-menu-option-id_restaurant />
    <input type=hidden class=admin-menu-option-description />
    <input type=hidden class=admin-menu-option-sort />
		<label>
			<div class=admin-item-col-no-pad>
				<input type=checkbox class=admin-menu-option-default title="Option is selected by default" />
			</div>
		</label>
		<div class=admin-item-col-med>
			<input type=input class=admin-menu-option-name placeholder="Option name" />
		</div>
		<div class=admin-item-col-small>
			<input type=input class=admin-menu-option-price placeholder=$ />
		</div>
		<div class="admin-item-col-fit vertical-middle">
			<div class="move_option_up sprite-arrow_up" title="Move this option up"></div>
			<div class="move_option_down sprite-arrow_down" title="Move this option down"></div>
			<div class="delete-option sprite-x_alt" title="Delete this option"></div>
		</div>
	</div>

	<div id=admin-dish-lightning-modal>
		<div class=admin-modal-title>
			Dish
		</div>
		<div class=admin-modal-item>
			<div class=admin-modal-explanation>
				Move this dish to a different category
			</div>
			&nbsp;&nbsp;
			<div class=admin-modal-right>
				<select class=move-dish-to-category-select></select>
				&nbsp;&nbsp;
				<div class="move-dish-to-category-button admin-button-workflow">move</div>
			</div>
		</div>
		<div class=admin-modal-item>
			<div class=admin-modal-explanation>
				Create a new copy of this dish in the same or another category.
			</div>
			&nbsp;&nbsp;
			<div class=admin-modal-right>
				<select class=copy-dish-to-category-select></select>
				&nbsp;&nbsp;
				<div class="copy-dish-to-category-button admin-button-workflow">copy</div>
			</div>
		</div>
		<div class=admin-modal-item>
			<div class=admin-modal-explanation>
				Copy the options for this dish to another dish, and keep them linked (option names and prices stay synced).
			</div>
			&nbsp;&nbsp;
			<div class=admin-modal-right>
				<select class=copy-options-to-dish-linked-select></select>
				&nbsp;&nbsp;
				<div class="copy-options-to-dish-linked-button admin-button-workflow">copy</div>
			</div>
		</div>
		<div class=admin-modal-item>
			<div class=admin-modal-explanation>
				Copy the options for this dish to another dish, and unlink them (option names and prices can be changed independently).
			</div>
			&nbsp;&nbsp;
			<div class=admin-modal-right>
				<select class=copy-options-to-dish-unlinked-select></select>
				&nbsp;&nbsp;
				<div class="copy-options-to-dish-unlinked-button admin-button-workflow">copy</div>
			</div>
		</div>
		<div class=admin-modal-item>
			<div class=admin-modal-right>
				<div class="lightning-cancel admin-button-workflow">do nothing</div>
			</div>
		</div>
	</div>

</div>



<script type=text/javascript src=https://maps.googleapis.com/maps/api/js?sensor=false></script>
<script type=text/javascript src=/assets/js/admin_restaurant.js?v=<?=Cana_Util::gitVersion()?>></script>
<script type=text/javascript src=/assets/js/intro.js></script>
<script>
ADMIN.restaurant_init(<?=$this->restaurant->id_restaurant?>);
</script>



