<div class="support-box-wrap box-content2" ng-if="order.id_restaurant">
	<div class="support-box-wrap-header">
		<h1>Contents</h1>
		<div class="divider"></div>
	</div>

	<div class="no-box-content-color">
		<table align="right" class="basic-table detail">
			<tr>
				<td class="topitem order-contents-item-qty">Qty</td>
				<td class="topitem itemname">Item</td>
				<td class="topitem itemname"></td>
				<td class="topitem itemprice">Store Price</td>
				<td class="topitem itemprice">Customer Price</td>
			</tr>
			<tr ng-repeat="dish in order.dishes_data">
				<td class="fooditem order-contents-item-qty" ng-class="{'order-contents-item-qty-highlight': dish.quantity > 1 }">{{dish.quantity}}</td>
				<td class="fooditem dish-name">
					<b>{{dish.name}}</b>
					<div ng-show="dish.with_option">
						{{dish.with_option}}
					</div>
					<div ng-show="dish.without_default_options">
						{{dish.without_default_options}}
					</div>
				</td>
				<td class="fooditem dish-price-unity">
					<span ng-if="dish.quantity > 1">
						{{dish.quantity}} * ${{dish.price.regular_unity | formatPrice}}
					</span>
				</td>
				<td class="fooditem dish-price">
					${{dish.price.regular | formatPrice}}
					<span ng-if="dish.price.regular_new" title="Price changed to: ${{dish.price.regular_new | formatPrice}}">*</span>
				</td>
				<td class="fooditem dish-price">
					${{dish.price.final_price | formatPrice}}
				</td>

			</tr>
			<tr><td><br></td><td></td></tr>

			<tr class="listview-smaller"><td></td>
				<td colspan="3" style="text-align: right">Subtotal:</td><td nowrap class="dish-price">${{order.price | number:2}}</td>
			</tr>
			<tr class="listview-smaller"><td></td><td colspan="3" style="text-align: right">Markup:</td><td nowrap class="dish-price">${{order.delivery_service_markup_value || 0 | number:2}} ({{order.delivery_service_markup || 0}}%)</td></tr>
			<tr class="listview-smaller"><td></td><td colspan="3" style="text-align: right">Service Fee:</td><td nowrap class="dish-price">${{order.price * (order.service_fee/100) | number:2}} ({{order.service_fee || 0}}%)</td></tr>
			<tr class="listview-smaller"><td></td><td colspan="3" style="text-align: right">Delivery Fee:</td><td nowrap class="dish-price">${{order.delivery_fee || 0 | number:2}}</td></tr>
			<tr class="listview-smaller"><td></td><td colspan="3" style="text-align: right">Tax:</td><td nowrap class="dish-price">${{order.price * (order.tax/100) | number:2}} ({{order.tax}}%)</td></tr>
			<tr class="listview-smaller"><td></td><td colspan="3" style="text-align: right">Service Fee:</td><td nowrap class="dish-price">${{order.cb_service_fee | number:2}}</td></tr>
			<tr class="listview-smaller"><td></td><td colspan="3" style="text-align: right">Tip:</td><td nowrap class="dish-price">${{order._tip || 0 | number:2}}
					<span ng-if="order.tip_type == 'percent'">({{order.tip}}%)</span>
					<span ng-if="order.tip_type != 'percent'">({{ order._tip/order.price*100  | number:2 }}%)</span>
				</td></tr>
			<tr class="listview-smaller"><td></td><td colspan="3" style="text-align: right">Gift Card (Credit):</td><td nowrap class="dish-price">${{order.credit || 0 | number:2}} </td></tr>
			<tr class="listview-smaller"><td></td><td colspan="3" style="text-align: right">Total (Charged):</td><td nowrap class="dish-price">${{order.charged || 0 | number:2}} </td></tr>

			<tr class="listview-smaller"><td></td><td colspan="3" class="listview-bold" style="text-align: right">Total:</td><td class="listview-bold " nowrap>${{order.final_price_plus_delivery_markup | number:2}}</td></tr>
		</table>

		<div class="no-box-content-color">
			<div class="field-container">
				<div class="field-row">
					<div class="field-note">
						* Item prices are estimates and do not necessarily reflect what the user was charged.
					</div>
				</div>
			</div>
			<br>
		</div>

	</div>
	<div class="divider"></div>
</div>