<div class="top-pad"></div>

<div class="content-padding">
	<h1 class="title left"><i class="fa fa-car"></i>Orders</h1>
	<div class="box-filter">
		<button class="button orange" ng-class="{ 'inactive' : query.view=='list' }" ng-click="query.view = 'map'">Map</button>
		<button class="button orange" ng-class="{ 'inactive' : query.view=='map' }" ng-click="query.view = 'list'">List</button>
	</div>
	<div class="divider"></div>

	<div class="box-content2 box-content-table">
		<table>
			<tr>
				<td colspan="4"><i class="fa fa-search"></i>&nbsp;&nbsp;<input type="text" ng-model="query.search" id="search" tabindex="1"></td>
			</tr>
			<tr>
				<th>Start</th>
				<td>
					<input type="date" ng-model="query.datestart" tabindex="2">
				</td>
				<th>End</th>
				<td>
					<input type="date" ng-model="query.dateend" tabindex="3">
				</td>
			</tr>
		</table>
	</div>

	<div class="bar-loader bar-loader-search" ng-class="{'bar-loader-loading': loading}"></div>

	<ng-include src="'assets/view/listview-orders.html'" ng-show="query.view=='list'"></ng-include>
	<ng-include src="'assets/view/listview-paging.html'" ng-show="query.view=='list'"></ng-include>
	
	<ng-include src="'assets/view/mapview-orders.html'" ng-show="query.view=='map'"></ng-include>
</div>
