<span ng-if="order.delivery_service">
	<span class="tag tag-black" ng-if="order.status.status == 'canceled'">Canceled</span>
	<span class="tag tag-red" ng-if="order.status.status == 'new'">Not&nbsp;yet&nbsp;accepted</span>
	<span class="tag tag-green" ng-if="order.status.status == 'accepted'">Accepted</span>
	<span class="tag tag-blue" ng-if="order.status.status == 'pickedup'">Pickedup</span>
	<span class="tag tag-purple" ng-if="order.status.status == 'delivered'">Delivered</span>
</span>
<span ng-if="!order.delivery_service && order._restaurant_confirmation">
	<span class="tag tag-red" ng-if="!order.confirmed">Unconfirmed</span>
	<span class="tag tag-green" ng-if="order.confirmed">Confirmed</span>
</span>
<span ng-if="!order.delivery_service && !order._restaurant_confirmation">
	<span class="tag tag-grey">Placed</span>
</span>
<br>
<span ng-if="order.status && !order.minutes_to_delivery" class="listview-smallest"><span am-time-ago="order.status.date_timestamp | timestamp"></span></span>
<span ng-if="order.status && order.minutes_to_delivery" class="listview-smallest">in {{order.minutes_to_delivery}} minutes</span>