<?
	$this->title = 'Drivers';
	$this->titleicon = 'road';
?>
<!-- content -->
<div class="container-fluid padded">
	<div class="row-fluid">
		<div class="box">
			<div class="box-header">
				<span class="title">Drivers</span>
			</div>
			<div class="box-content padded">
				<a href="/drivers/deliveries"> <i class="icon-truck"></i> Delivered orders</a>
				<br />
				<br />
				<a href="/drivers/assign"> <i class="icon-magnet"></i> Assign drivers to restaurants/communities</a>
				<br />
				<br />
				<a href="/drivers/hours"> <i class="icon-time"></i> Working hours</a>
				<br />
				<br />
				<a href="/drivers/schedule"> <i class="icon-calendar"></i> Schedule</a>
			</div>
		</div>
	</div>
</div>