

<div class="top-pad"></div>

<div class="content-padding">

	<h1 class="subltitle "><i class="fa fa-comments-o"></i>&nbsp;&nbsp;<span>Messages</span></h1>
	<div class="box-content2 box-content-table">
		<table class="tb-zebra">
			<tr>
				<th>Support&nbsp;ID</th>
				<th>From</th>
				<th>Updated</th>
				<th>Name</th>
				<th>Message</th>
			</tr>
			<tr ng-repeat="ticket in tickets">
				<td><a href="/ticket/{{ticket.id_support}}">#{{ticket.id_support}}</td>
				<td><a href ng-click="callText(ticket.user.phone)">{{ticket.user.phone | formatPhone}}</a></td>
				<td>
					<span ng-if="ticket.timestamp" am-time-ago="ticket.timestamp*1000"></span>
					<span ng-if="!ticket.timestamp"><i>Unknown</i></span>
				</td>
				<td>{{ticket.name}}</td>
				<td>{{ticket.message}}</td>

			</tr>
		</table>
	</div>
	
	<h1 class="subltitle"><i class="fa fa-phone"></i>&nbsp;&nbsp;<span>Calls</span>&nbsp;&nbsp;<div class="title-loader" ng-if="!calls"><i class="fa fa-refresh fa-spin"></i></div></h1>
	<div class="box-content2 box-content-table">
		<table class="tb-zebra">
			<tr>
				<th>Support&nbsp;ID</th>
				<th>From</th>
				<th>Status</th>
				<th>Start</th>
				<th>End</th>
			</tr>
			<tr ng-repeat="call in calls">
				<td>{{call.support.id_support}}</td>
				<td><a href ng-click="callText(call.from)">{{call.from | formatPhone}}</a></td>
				<td>{{call.status}}</td>
				<td>{{call.start_time}}</td>
				<td>{{call.end_time}}</td>
			</tr>
		</table>
	</div>

</div>
