<div class="tickets-side-list">
	<div ng-controller="SideChatCtrl">
		<div ng-if="account.user.permissions.GLOBAL">
			<h1>Tickets</h1>
			<div class="tickets-side-tickets">
				<div ng-repeat="ticket in tickets" class="tickets-side-item">
					
					<a href="#" class="tickets-side-ticket">#{{ticket.id_support}}</a>
					<span class="tickets-side-time">10 m ago</span>
					<div class="divider"></div>
					<br>
					<span class="tickets-side-name">{{ticket.name}}: </span>
					<span class="tickets-side-message">{{ticket.message}}</span>
				</div>
			</div>
		</div>

		<div ng-if="!account.user.permissions.GLOBAL">
			<br>
			<p>We will soon have a chat feature that goes to support here. Until then, text us at: <br><br><a href="tel:16467831444" target="_system">(646) 783-1444</a></p>
		</div>
	</div>
</div>
