<div class="top-pad"></div>

<div class="content-padding">

	<h1 class="title left"><i class="fa fa-comments-o"></i><span>Support</span> : Issue #{{ticket.id_support}}</h1>

	<div class="divider"></div>
	
	<div ng-if="ticket.user.id_user" class="support-box-wrap">
		<h1>Customer <a href="/customer/{{ticket.user.id_user}}">#{{ticket.user.id_user}}</a></h1>
		<div class="box-content-color">
			<div class="field-container">
				<div class="field-row">
					<div class="field-key">Name</div>
					<div class="field-value">{{ticket.user.name}}</div>
				</div>
				<div class="field-row">
					<div class="field-key">Phone</div>
					<div class="field-value"><a href ng-click="callText(ticket.user.phone)">{{ticket.user.phone | formatPhone}}</a></div>
				</div>
				<div class="field-row">
					<div class="field-key">Address</div>
					<div class="field-value"><a href ng-click="routeAddress(ticket.user.address)">{{ticket.user.address}}</a></div>
				</div>
				<div class="field-row">
					<div class="field-key">Distance from restaurant</div>
					<div class="field-value">@todo</div>
				</div>
			</div>
		</div>
	</div>
	
	<div ng-if="ticket.driver.id_admin" class="support-box-wrap">
		<h1>Driver <a href="/driver/{{ticket.driver.id_admin}}">#{{ticket.driver.id_admin}}</a></h1>
		<div class="box-content2">
			Name {{ticket.admin.name}}
		</div>
	</div>
	
	<div ng-if="ticket.restaurant.id_restaurant" class="support-box-wrap">
		<h1>Restaurant <a href="/restaurant/{{ticket.restaurant.id_restaurant}}">#{{ticket.restaurant.id_restaurant}}</a></h1>
		<div class="box-content-color">
			<div class="field-container">
				<div class="field-row">
					<div class="field-key">Name</div>
					<div class="field-value">{{ticket.restaurant.name}}</div>
				</div>
				<div class="field-row">
					<div class="field-key">Phone</div>
					<div class="field-value"><a href ng-click="callText(ticket.restaurant.phone)">{{ticket.restaurant.phone | formatPhone}}</a></div>
				</div>
				<div class="field-row">
					<div class="field-key">Address</div>
					<div class="field-value"><a href ng-click="routeAddress(ticket.restaurant.address)">{{ticket.restaurant.address}}</a></div>
				</div>
				<div class="field-row">
					<div class="field-key">Distance from customer</div>
					<div class="field-value">@todo</div>
				</div>
			</div>
		</div>
	</div>

</div>

<hack-expand-content></hack-expand-content>