<div class="top-pad"></div>

<div class="content-padding">
	<h1 class="title"><i class="fa fa-bookmark"></i>Tickets</h1>

	<div class="box-content2 box-content-table">
		<table>
			<tr>
				<td colspan="4">
					<i class="fa fa-search"></i>&nbsp;&nbsp;<input type="text" ng-model="query.search" id="search" tabindex="1">
				</td>
			</tr>
			<tr>
				<th>Status</th>
				<td>
					<select ng-model="query.status" name="searchType" tabindex="3">
						<option value="all">All</option>
						<option value="open">Open</option>
						<option value="closed">Closed</option>
					</select>
				</td>
				<th>Type</th>
				<td>
					<select ng-model="query.type" name="searchType" tabindex="3">
						<option value="all">All</option>
						<option value="system">System</option>
					</select>
				</td>
			</tr>
		</table>
	</div>

	<div class="bar-loader bar-loader-search" ng-class="{'bar-loader-loading': loading}"></div>

	<ng-include src="'assets/view/listview-tickets.html'"></ng-include>
	<ng-include src="'assets/view/listview-paging.html'"></ng-include>
</div>
