<div class="top-pad"></div>

<div class="content-padding">
	<h1 class="title"><i class="fa fa-bookmark"></i>Tickets</h1>

	<div class="box-content2 box-content-table">
		<table>
			<tr>
				<td colspan="6">
					<i class="fa fa-search"></i>&nbsp;&nbsp;<input type="text" ng-model="query.search" id="search" tabindex="1">
					<td><i title="More options" class="fa fa-search-plus link no-underline" ng-class="{'orange':show_more_options}" ng-click="moreOptions()"></i></td>
				</td>
			</tr>
			<tr ng-if="show_more_options">
				<th>Staff</th>
					<td nowrap="nowrap">
						<ui-select ng-model="query.admin" theme="select2" close-on-select="true" style="width:200px;" title="Select a staff">
							<ui-select-match placeholder="Select a staff">{{$select.selected.name}}</ui-select-match>
							<ui-select-choices repeat="admin.id_admin as admin in staff | propsFilter: {name: $select.search}">
								{{admin.name}}
							</ui-select-choices>
						</ui-select>
						<a ng-show="query.admin" ng-click="query.admin=null" href=""><button class="button button-small button-empty button-green"><i class="fa fa-trash-o"></i></button></a>
				</td>
				<th>Status</th>
				<td>
					<select ng-model="query.status" name="searchType" tabindex="3">
						<option value="all">All</option>
						<option value="open">Open</option>
						<option value="closed">Closed</option>
					</select>
				</td>
				<th>Type</th>
				<td>
					<select ng-model="query.type" name="searchType" tabindex="3">
						<option value="all">All</option>
						<option value="system">System</option>
					</select>
				</td>
			</tr>
		</table>
	</div>

	<div class="bar-loader bar-loader-search" ng-class="{'bar-loader-loading': loading}"></div>

	<ng-include src="'assets/view/listview-tickets.html'"></ng-include>
	<ng-include src="'assets/view/listview-paging.html'"></ng-include>
</div>
