<div class=content-item>
	<div class=content-item-header>
		Overview
	</div>
	<div class=content-sub-item>
		<?= Support::q("select count(*) as count from support where status='open'")->count ?>
		&nbsp;open support issues
	</div>
</div>

<div class=content-item>
	<div class=content-item-header>
		Last Five Support Issues
	</div>
	<? foreach ($this->supports as $support): ?>
		<a href='/support/<?= $support->id_support ?>'>
			<div class='content-sub-item <?='support-'.$support->status?>'>
					#SUP<?= $support->id_support ?> - 
					<?= date('M j, g:i a', strtotime($support->timestamp)); ?> - 
					<?= $support->name ?> - 
					<?= $support->message ?>
			</div>
		</a>
	<? endforeach; ?>
</div>

