<?
	$support = $this->support;
	$order = $support->order();

	/*
	$url = c::app()->pages();
	if(end($url) == '') array_pop($url);
	$this_url = '/' . implode('/', $url);
	*/
	$this_url = "/support/$support->id_support";

?>
<div class=content-item> <!-- details --> 
	<div class=content-item-header>
		Support #SUP<?= $support->id_support ?>
		 - 
		<?= Crunchbutton_Util::datetime_date_str($support->datetime, $this->rep_timezone); ?>, 
		<?= Crunchbutton_Util::datetime_time_str($support->datetime, $this->rep_timezone); ?>
		 - 
		<?= strtoupper($support->status) ?>
	</div>
	<div class=content-sub-item> <!-- user -->
		<div class=content-sub-item-left>user</div>
		<div class=content-sub-item-right>
			<?= $support->name ?>

			<?
				$user = $support->user();
				$phone = $support->phone;
				if(!$phone && $user->id_user && $user->phone)
					$phone = $user->phone;
			?>
			<? if($user->id):
					echo " (#USER$user->id)";
			 endif ; ?>
			<br>
			<a href='tel:+1<?= $phone ?>'>
			<?= Crunchbutton_Util::format_phone($phone) ?>
			</a>
		</div>
	</div>
	<div class=content-sub-item> <!-- rep -->
		<div class=content-sub-item-left>rep</div>
		<div class=content-sub-item-right>
			<?
				$rep = $support->rep();
				if(!$rep->id) {
					echo '(no rep has handled this ticket)';
				}
				else {
					echo "$rep->name ";
					echo "<br>".Crunchbutton_Util::format_phone($rep->phone);
				}
			?>
		</div>
	</div>
	<div class=content-sub-item> <!-- order -->
		<div class=content-sub-item-left>order</div>
		<div class=content-sub-item-right>
			<?
				if($support->id_order) {
					echo "<a target='_blank' href='/vieworder/$order->uuid'>#ORD$order->id</a>";
					echo "<br>";
					echo $order->message('support');
				}
				else {
					echo '(no linked order)';
				}
			?>
		</div>
	</div>
	<div class=content-sub-item> <!-- restaurant -->
		<div class=content-sub-item-left>restaurant</div>
		<div class=content-sub-item-right>
			<?
				if($support->id_restaurant) {
					$restaurant = Restaurant::o($support->id_restaurant);
					echo "$restaurant->name ";
					echo "(#RST$restaurant->id_restaurant)";
					echo "<br><a href='tel:+1-$restaurant->phone'>";
					echo Crunchbutton_Util::format_phone($restaurant->phone);
					echo "</a>";
					echo "<br><a target='_blank' href='https://crunchbutton.com/food-delivery/$restaurant->permalink'>view on site</a> / ";
					echo "<a target='_blank' href='http://cockpit.crunchr.co/restaurants/$restaurant->id'>view in cockpit</a>";
				}
				else {
					echo '(no linked restaurant)';
				}
			?>
		</div>
	</div>
</div>

<div class=content-item> <!-- conversation -->
	<div class=content-item-header>
		Conversation
	</div>
	<div class=content-sub-item>
		<div class=content-sub-item-left>
			initial issue
			<br>
			<?= Crunchbutton_Util::datetime_time_str($support->datetime, $this->rep_timezone); ?>
		</div>
		<div class=content-sub-item-right>
			<?= $support->message ?>
		</div>
	</div>

	<? foreach ($support->notes('external') as $note): ?>
		<div class=content-sub-item>
			<div class=content-sub-item-left>
				<?= $note->from ?>
				<? if(Crunchbutton_Util::datetime_date_str($note->datetime,    $this->rep_timezone) !== 
					    Crunchbutton_Util::datetime_date_str($support->datetime, $this->rep_timezone)   ) {
					echo '<br>' . Crunchbutton_Util::datetime_date_str($note->datetime, $this->rep_timezone);
				}?>
				<br>
				<? echo Crunchbutton_Util::datetime_time_str($note->datetime, $this->rep_timezone); ?>
			</div>
			<div class=content-sub-item-right>
				<?= $note->text ?>
			</div>
		</div>
	<? endforeach; ?>

	<div class=content-sub-item>
		<form method=post action='<?= $this_url ?>'>
			<input type=hidden name=action value=conversation />
			<input type=hidden name=rep_name value='<?=$this->username?>' />
			<input type=hidden name=id_support value='<?=$support->id?>' />
			<div class=content-full-width>
				<textarea name=text>
				</textarea>
			</div>
			<div class=content-full-width>
				<input class=button type=submit value='Respond to Client' />
			</div>
		</form>
	</div>
</div>

<div class=content-item>
	<div class=content-item-header>
		Actions
	</div>

	<form method=post action='<?=$this_url?>'>
		<input type=hidden name=action value=support_actions />

	<div class=content-sub-item>
		<div class=content-full-width>
			<? if(!$order->id) : ?>
				No Order Linked
			<? elseif($order->id && $order->refunded) : ?>
				Order was Refunded
			<? else : ?>
				<input type=submit class=button name=action_type value='Refund Order' />
			<? endif; ?>
		</div>
	</div>
	<div class=content-sub-item>
		<?
			$giftcard_url = '/giftcards/new?'
				."&id_user=$support->id_user"
				."&id_restaurant=$support->id_restaurant"
				."&id_order_reference=$support->id_order";
		?>
		<a target='_blank' href='<?= $giftcard_url ?>'>
			<div class=content-full-width>
				Issue Gift Card
			</div>
		</a>
	</div>

	<div class=content-sub-item>
		<div class=content-full-width>
			<? if($support->id_restaurant) : ?>
				<input type=submit class=button name=action_type value='Unlink Restaurant' />
			<? else : ?>
				<em>id or permalink</em> 
				<input type=text name=id_restaurant /><br>
				<input type=submit class=button name=action_type value='Link Restaurant' />
			<? endif; ?>
		</div>
	</div>

	<div class=content-sub-item>
		<div class=content-full-width>
			<? if($support->id_user) : ?>
				<input type=submit class=button name=action_type value='Unlink User' />
			<? else : ?>
				<em>id or phone number</em> 
				<input type=text name=id_user /><br>
				<input type=submit class=button name=action_type value='Link User' />
			<? endif; ?>
		</div>
	</div>

	<div class=content-sub-item>
		<div class=content-full-width>
			<? if($support->id_order) : ?>
				<input type=submit class=button name=action_type value='Unlink Order' />
			<? else : ?>
				<em>order id</em> 
				<input type=text name=id_order /><br>
				<input type=submit class=button name=action_type value='Link Order' />
			<? endif; ?>
		</div>
	</div>

	</form>

</div>


<form method=post action='<?= $this_url ?>'>
	<input type=hidden name=action value=update />
	<input type=hidden name=rep_name value='<?=$this->username?>' />
	<input type=hidden name=id_support value='<?=$support->id?>' />

<div class=content-item>
	<div class=content-item-header>
		Internal Notes
	</div>
	<div class=content-sub-item>
		<div class=content-sub-item-left>
			description (client)
		</div>
		<div class=content-sub-item-right>
			<textarea name=description_client>
				<?= $support->description_client ?>
			</textarea>
		</div>
	</div>
	<div class=content-sub-item>
		<div class=content-sub-item-left>
			description (crunchbutton)
		</div>
		<div class=content-sub-item-right>
			<textarea name=description_cb>
				<?= $support->description_cb ?>
			</textarea>
		</div>
	</div>
	<? foreach ($support->notes('internal') as $note): ?>
		<div class=content-sub-item>
			<div class=content-sub-item-left>
				<?= $note->from ?>


				<? if(Crunchbutton_Util::datetime_date_str($note->datetime,    $this->rep_timezone) !== 
					    Crunchbutton_Util::datetime_date_str($support->datetime, $this->rep_timezone)   ) {
					echo '<br>' . Crunchbutton_Util::datetime_date_str($note->datetime, $this->rep_timezone);
				}?>
				<br>
				<? echo Crunchbutton_Util::datetime_time_str($note->datetime, $this->rep_timezone); ?>
			</div>
			<div class=content-sub-item-right>
				<?= $note->text ?>
			</div>
		</div>
	<? endforeach; ?>
	<div class=content-sub-item>
		<div class=content-sub-item-left>
			add a new note
		</div>
		<div class=content-sub-item-right>
			<textarea name=new_note>
			</textarea>
		</div>
	</div>
	<div class=content-sub-item>
		<div class=content-full-width>
			<input class=button type=submit value='Update' />
		</div>
	</div>
</div>

<div class=content-item>
	<div class=content-item-header>
		Resolution
	</div>
	<div class=content-sub-item>
		<div class=content-sub-item-left>
			fault of
		</div>
		<div class=content-sub-item-right>
			<select name=fault_of>
				<option value=crunchbutton<?= $support->fault_of=='crunchbutton'?' selected':'' ?>>
					crunchbutton
				</option>
				<option value=customer<?= $support->fault_of=='customer'?' selected':'' ?>>
					customer
				</option>
				<option value=restaurant<?= $support->fault_of=='restaurant'?' selected':'' ?>>
					restaurant
				</option>
				<option value=other<?= $support->fault_of=='other'?' selected':'' ?>>
					other
				</option>
			</select>
		</div>
	</div>
	<div class=content-sub-item>
		<div class=content-sub-item-left>
			user happy?
		</div>
		<div class=content-sub-item-right>
			<select name=customer_happy>
				<option value=no<?= $support->customer_happy=='no'?' selected':'' ?>>
					no
				</option>
				<option value=yes<?= $support->customer_happy=='yes'?' selected':'' ?>>
					yes
				</option>
			</select>
		</div>
	</div>
	<div class=content-sub-item>
		<div class=content-sub-item-left>
			ticket status
		</div>
		<div class=content-sub-item-right>
			<select name=status>
				<option value=open<?= $support->status=='open'?' selected':'' ?>>
					open
				</option>
				<option value=closed<?= $support->status=='closed'?' selected':'' ?>>
					closed
				</option>
			</select>
		</div>
	</div>
	<div class=content-sub-item>
		<div class=content-sub-item-left>
			github ticket id?
		</div>
		<div class=content-sub-item-right>
			<input type=text name=id_github value='<?= $support->id_github ?>' />
		</div>
	</div>
	<div class=content-sub-item>
		<div class=content-sub-item-left>
			how to prevent this in the future
		</div>
		<div class=content-sub-item-right>
			<textarea name=how_to_prevent>
				<?= $support->how_to_prevent ?>
			</textarea>
		</div>
	</div>
	<div class=content-sub-item>
		<div class=content-full-width>
			<input class=button type=submit value='Update' />
		</div>
	</div>
</div>

</form>






