<?
	$support = $this->support;
?>
<div class=content-item>
	<div class=content-item-header>
		Support #SUP<?= $support->id_support ?>
		 - 
		<?= date('M j, g:i a', strtotime($support->timestamp)); ?>
		 - 
		<?= strtoupper($support->status) ?>
	</div>
	<div class=content-sub-item> <!-- user -->
		<div class=content-sub-item-left>user</div>
		<div class=content-sub-item-right>
			<?= $support->name ?>

			<?
				$user = $support->user();
				$phone = $support->phone;
				if(!$phone && $user->id_user && $user->phone)
					$phone = $user->phone;
			?>
			<? if($user->id):
					echo " (#USER$user->id)";
			 endif ; ?>
			<br>
			<a href='tel:+1<?= $phone ?>'>
			<?
				if(preg_match('/^(\d{3})(\d{3})(\d{4})$/', $phone, $m)) {
					echo "($m[1]) $m[2]-$m[3]";
				}
				else {
					echo $phone;
				}
			?>
			</a>
		</div>
	</div>
	<div class=content-sub-item> <!-- rep -->
		<div class=content-sub-item-left>rep</div>
		<div class=content-sub-item-right>
			<?
				$rep = $support->rep();
				if(!$rep->id) {
					echo '(no rep has handled this ticket)';
				}
				else {
					echo "$rep->name ($rep->phone)";
				}
			?>
		</div>
	</div>
	<div class=content-sub-item> <!-- order -->
		<div class=content-sub-item-left>order</div>
		<div class=content-sub-item-right>
			<?
				if($support->id_order) {
					$order = $support->order();
					echo "<a href='/vieworder/$order->uuid'>#ORD$order->id</a>";
					echo "<br>";
					echo $order->message('support');
					echo "<br>";


					echo '
	id_restaurant
		restaurant_name
		restaurant_phone
		';
				}
				else {
					echo '(no linked order)';
				}
			?>



		</div>
	</div>
</div>

<div class=content-item>
	<div class=content-item-header>
		Conversation
	</div>
	<div class=content-sub-item>
		(details...)
	</div>
	<div class=content-sub-item>
		(details...)
	</div>
	<div class=content-sub-item>
		(details...)
	</div>
</div>

<div class=content-item>
	<div class=content-item-header>
		Resolution
	</div>
	<div class=content-sub-item>
		(details...)
	</div>
	<div class=content-sub-item>
		(details...)
	</div>
	<div class=content-sub-item>
		(details...)
	</div>
</div>




messages

id_github
description_client
description_cb
fault_of enum('restaurant', 'customer', 'crunchbutton', 'other')
refunded / refund button ?
customer_happy

ALSO TODO
# of orders for this user
if no order, allow to link an order
allow to refund an order from this page
link to gift cards





