<?=$this->display('layout/html.top')?>

<? if (c::config()->bundle) : ?>
	<script src="/assets/cockpit/js/bundle.js?v=<?=Cana_Util::gitVersion()?>&s=cockpit"></script>
<? else : ?>
	<?=$this->display('bundle/js', ['set' => ['scripts' => ['cockpit']]])?>
<? endif ; ?>

<?=$this->display('layout/html.bottom')?>

<script src="//maps.googleapis.com/maps/api/js?libraries=places&sensor=false"></script>
<? /* &key=***REMOVED*** */ ?>