<!doctype html>
<html lang="en" ng-app="NGApp">

<? if (!c::config()->bundle) : ?>
	<base href="/">
<? endif; ?>

<head>
	<title ng-bind="title ? title + ' | Cockpit' : 'Cockpit'">Cockpit</title>

	<meta name="fragment" content="!">
	<meta name="viewport" content="initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
	<meta name="format-detection" content="telephone=no">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">

	<link rel="apple-touch-icon-precomposed" href="/assets/images/micro/appicon.png">

	<? if( c::env() == 'local' ): ?>
		<link rel="shortcut icon" href="/assets/cockpit/images/favicon-dev.png">
	<? else : ?>
		<link rel="shortcut icon" href="/assets/cockpit/images/favicon.png">
	<? endif ; ?>

	<link href="https://netdna.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css" rel="stylesheet" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=Ruda:400,700,900" rel="stylesheet" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900" rel="stylesheet" type="text/css">

	<link rel="stylesheet" type="text/css" href="/assets/cockpit/css/preload.css">
</head>
