<div class="hide angular-hider" ng-class="{ show: angularLoaded }">
	<div class="snap-drawers static-nav-viewport loggedout-hideable">
		<div class="snap-drawer snap-drawer-left side-menu" id="side-menu" ng-controller="SideMenuCtrl">
			<div class="user-initials" ng-if="account.user.id"><span>{{account.user.initials}}</span></div>

			<ul>
				<? /*
				<li ng-click="navigation.link('/drivers/dashboard')" ng-class="{'nav-active': (navigation.page == 'drivers-dashboard')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-dashboard"></i></td>
							<td class="side-menu-label">Dashboard</a></td>
						</tr>
					</table>
				</li>
				*/ ?>
				<li ng-if="account.user.permissions.GLOBAL" ng-click="navigation.link('/profile')" ng-class="{'nav-active': (navigation.page == 'profile')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-user"></i></td>
							<td class="side-menu-label">Profile</a></td>
						</tr>
					</table>
				</li>
				<li ng-click="navigation.link('/drivers/orders')" ng-class="{'nav-active': (navigation.page == 'drivers-orders')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-car"></i></td>
							<td class="side-menu-label">Orders</a></td>
						</tr>
					</table>
				</li>

				<li ng-if="account.user.permissions.GLOBAL || account.isDriver" ng-click="navigation.link('/drivers/shifts')" ng-class="{'nav-active': (navigation.page == 'drivers-shifts')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-calendar"></i></td>
							<td class="side-menu-label">Shifts</a></td>
						</tr>
					</table>
				</li>

				<li ng-if="account.user.permissions.GLOBAL || account.isDriver" ng-click="navigation.link('/drivers/shifts/schedule')" ng-class="{'nav-active': (navigation.page == 'drivers-shift-preferences')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-calendar"></i></td>
							<td class="side-menu-label">Shift Preferences</a></td>
						</tr>
					</table>
				</li>

				<li ng-if="account.user.permissions.GLOBAL || account.isDriver" ng-click="navigation.link('/drivers/summary')" ng-class="{'nav-active': (navigation.page == 'drivers-summary')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-money"></i></td>
							<td class="side-menu-label">Payment Summary</a></td>
						</tr>
					</table>
				</li>

				<li ng-if="account.user.permissions.GLOBAL || account.isRestaurant" ng-click="navigation.link('/restaurant/order/placement/dashboard')" ng-class="{'nav-active': (navigation.page == 'restaurant-order-placement')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-credit-card"></i></td>
							<td class="side-menu-label">Order Placement</a></td>
						</tr>
					</table>
				</li>

				<?/* Permission GLOBAL hard coded for while | todo: remove it and apply the correct permission @pererinha */?>
				<li ng-if="account.user.permissions.GLOBAL" ng-click="navigation.link('/settlement/')" ng-class="{'nav-active': (navigation.page == 'settlement')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-bank"></i></td>
							<td class="side-menu-label">Settlement</a></td>
						</tr>
					</table>
				</li>

				<?/* Permission GLOBAL hard coded for while | todo: remove it and apply the correct permission @pererinha */?>
				<li ng-if="account.user.permissions.GLOBAL" ng-click="navigation.link('/staff/list')" ng-class="{'nav-active': (navigation.page == 'staff')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-users"></i></td>
							<td class="side-menu-label">Staff</a></td>
						</tr>
					</table>
				</li>

				<?/* Permission GLOBAL hard coded for while | todo: remove it and apply the correct permission @pererinha */?>
				<li ng-if="account.user.permissions.GLOBAL" ng-click="navigation.link('/customer')" ng-class="{'nav-active': (navigation.page == 'customer')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-smile-o"></i></td>
							<td class="side-menu-label">Customer</a></td>
						</tr>
					</table>
				</li>

				<?/* Permission GLOBAL hard coded for while | todo: remove it and apply the correct permission @pererinha */?>
				<li ng-if="account.user.permissions.GLOBAL" ng-click="navigation.link('/drivers/onboarding')" ng-class="{'nav-active': (navigation.page == 'drivers-onboarding')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-automobile"></i></td>
							<td class="side-menu-label">Driver Onboarding</a></td>
						</tr>
					</table>
				</li>

				<li ng-if="account.user.permissions.GLOBAL || account.isDriver" ng-click="navigation.link('/drivers/docs/')" ng-class="{'nav-active': (navigation.page == 'drivers-documents')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-briefcase"></i></td>
							<td class="side-menu-label">Documents</a></td>
						</tr>
					</table>
				</li>

				<li ng-if="account.isDriver" ng-click="navigation.link('/drivers/help')" ng-class="{'nav-active': (navigation.page == 'drivers-help')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-support"></i></td>
							<td class="side-menu-label">Help</a></td>
						</tr>
					</table>
				</li>
				<li ng-if="account.isRestaurant" ng-click="navigation.link('/restaurants/help')" ng-class="{'nav-active': (navigation.page == 'restaurants-help')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-support"></i></td>
							<td class="side-menu-label">Help</a></td>
						</tr>
					</table>
				</li>
				<li ng-if="!account.user.id" ng-click="navigation.link('/help')" ng-class="{'nav-active': (navigation.page == 'help')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-support"></i></td>
							<td class="side-menu-label">Help</a></td>
						</tr>
					</table>
				</li>
				<? /*
				<li ng-click="navigation.link('/splash')" ng-class="{'nav-active': (navigation.page == 'home')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-dashboard"></i></td>
							<td class="side-menu-label">Dashboard</a></td>
						</tr>
					</table>
				</li>
				<li ng-click="navigation.link('/help')" ng-class="{'nav-active': (navigation.page == 'help')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-smile-o"></i></td>
							<td class="side-menu-label">Customers</a></td>
						</tr>
					</table>
				</li>
				<li ng-click="navigation.signin()">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-road"></i></td>
							<td class="side-menu-label">Drivers</a></td>
						</tr>
					</table>
				</li>
				<li ng-click="signout.signout()">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-bar-chart-o"></i></td>
							<td class="side-menu-label">Reports</a></td>
						</tr>
					</table>
				</li>
				<li ng-click="signout.signout()">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-wrench"></i></td>
							<td class="side-menu-label">Tools</a></td>
						</tr>
					</table>
				</li>
				*/ ?>
				<li ng-click="account.logout()" ng-if="account.user.id_admin">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-sign-out"></i></td>
							<td class="side-menu-label">Sign Out</a></td>
						</tr>
					</table>
				</li>
				<li ng-click="navigation.link('/login')" ng-if="!account.user.id_admin">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-sign-in"></i></td>
							<td class="side-menu-label">Sign In</a></td>
						</tr>
					</table>
				</li>
			</ul>

		</div>
		<div class="snap-drawer snap-drawer-right side-menu" id="side-menu-right">
			<div ng-include="'assets/view/tickets-side-list.html'"></div>
		</div>
	</div>

	<div class="wrapper static-nav-viewport loggedout-hideable">

		<div id="snap-content" class="snap-content">
			<div class="navs fixed" data-position="fixed" ng-controller="MainHeaderCtrl" ng-show="account.user.id_admin">
				<div class="nav nav-top">
					<div class="content">

						<div title="Menu" class="menu side hide-before-init" ng-click="navigation.menu()" ng-hide="hasBack"></div>
						<div title="Back" class="nav-back hide-before-init" ng-click="back()" ng-show="hasBack"></div>

						<div class="notifications">

							<div class="flash-message {{flash.getLevel()}}" ng-show="flash.hasMessage()">
								<p>{{flash.getMessage()}}</p>
							</div>

							<div class="notification notification-orders" ng-click="navigation.link('/drivers/orders')">
								<div class="badge" ng-show="newDriverOrders.count">{{newDriverOrders.count}}</div>
								<i class="fa fa-truck"></i>
							</div>
							<div class="notification notification-support" ng-click="navigation.menu('right')">
								<div class="badge" ng-show="supportMessages.count">{{supportMessages.count}}</div>
								<i class="fa fa-comment"></i>
							</div>
							<? /*
							<div class="notification notification-alerts" ng-click="navigation.link('/alerts')">
								<i class="fa fa-bell"></i>
							</div>
							*/ ?>
						</div>

						<div class="logo">cockpit<span class="dot">.</span><span class="green">la</span></div>

					</div>
				</div>
			</div>

			<div class="snap-content-inner bg" ng-scroll-position>
				<div class="content" ng-scroll-spy>
					<div ng-view id="ng-view" class="view-animate"><?=$this->content?></div>
				</div>

				<div class="divider"></div>
			</div>

		</div>

		<div class="divider"></div>
	</div>

	<div id="fb-root"></div>

	<!-- Notification -->
	<div class="notification-alert-container zoom-anim-dialog mfp-hide dialog" ng-controller="NotificationAlertCtrl">
		<h1 ng-bind="title" ng-show="title"></h1>
		<p ng-bind-html-unsafe="message" class="small-message"></p>
		<button ng-click="complete()" class="button green">OK</button>
	</div>
</div>