<div class="hide angular-hider html-body" ng-class="{ show: angularLoaded, 'support-toggled': supportToggled, 'menu-toggled': !menuToggled }">
	<div class="snap-drawers static-nav-viewport loggedout-hideable">
		<div class="snap-drawer snap-drawer-left side-menu" id="side-menu" ng-controller="SideMenuCtrl">
			<div class="user-initials" ng-if="account.user.id"><span>{{account.user.initials}}</span></div>

			<div class="menu-tabs">
				<div class="menu-tab" ng-if="account.isDriver || account.user.permissions.GLOBAL" ng-class="{'menu-active': (menu.toggle == 'driver')}" ng-click="menu.toggle='driver'">
					<i class="fa fa-truck"></i>
				</div>
				<div class="menu-tab" ng-if="account.isMarketingRep || account.user.permissions.GLOBAL" ng-class="{'menu-active': (menu.toggle == 'marketing-rep')}" ng-click="menu.toggle='marketing-rep'">
					<i class="fa fa-male"></i>
				</div>

				<div class="menu-tab" ng-if="account.user.permissions.GLOBAL" ng-class="{'menu-active': (menu.toggle == 'admin')}" ng-click="menu.toggle='admin'">
					<i class="fa fa-dashboard"></i>
				</div>
			</div>
			<div class="divider"></div>
			<? /*
			<li ng-click="navigation.link('/drivers/dashboard')" ng-class="{'nav-active': (navigation.page == 'drivers-dashboard')}">
				<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
					<tr>
						<td class="side-menu-icon"><i class="fa fa-dashboard"></i></td>
						<td class="side-menu-label">Dashboard</a></td>
					</tr>
				</table>
			</li>
			*/ ?>

			<a href="/dashboard" ng-click="instant()" class="menu-link" ng-if="account.user.permissions.GLOBAL && menu.toggle=='admin'" ng-class="{'nav-active': (navigation.page == 'dashboard' )}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-dashboard"></i></td>
							<td class="side-menu-label">Dashboard CS</a></td>
						</tr>
					</table>
				</a>

				<a href="/dashboard/beta" ng-click="instant()" class="menu-link" ng-if="account.user.permissions.GLOBAL && menu.toggle=='admin'" ng-class="{'nav-active': (navigation.page == 'dashboard-beta' )}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-dashboard"></i></td>
							<td class="side-menu-label">Dashboard (beta) <i class="fa fa-flask"></i></a></td>
						</tr>
					</table>
				</a>



			<div ng-if="menu.toggle=='marketing-rep'">
				<a href="/profile" ng-click="instant()" class="menu-link" ng-class="{'nav-active': (navigation.page == 'profile'|| navigation.page == 'drivers-notification')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-user"></i></td>
							<td class="side-menu-label">Profile</a></td>
						</tr>
					</table>
				</a>

				<a href="/staff/marketing-rep/docs" ng-click="instant()" class="menu-link" ng-if="account.isMarketingRep && menu.toggle=='marketing-rep'" ng-class="{'nav-active': (navigation.page == 'marketing-rep-docs')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-briefcase"></i></td>
							<td class="side-menu-label">Documents</a></td>
						</tr>
					</table>
				</a>


				<a href="/drivers/summary" ng-click="instant()" class="menu-link" ng-if="(account.user.permissions.GLOBAL || account.isMarketingRep) && menu.toggle=='marketing-rep'" ng-class="{'nav-active': (navigation.page == 'drivers-summary')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-bank"></i></td>
							<td class="side-menu-label">Payments</a></td>
						</tr>
					</table>
				</a>

				<a href="/staff/marketing-rep/faq" ng-click="instant()" class="menu-link" ng-if="account.isMarketingRep && menu.toggle=='marketing-rep'" ng-class="{'nav-active': (navigation.page == 'marketing-rep-help')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-support"></i></td>
							<td class="side-menu-label">FAQ</a></td>
						</tr>
					</table>
				</a>

				<a href="/marketing/materials/refill" ng-click="instant()" class="menu-link" ng-class="{'nav-active': (navigation.page == 'marketing-rep-request-materials')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-cubes"></i></td>
							<td class="side-menu-label">Marketing Materials</a></td>
						</tr>
					</table>
				</a>

				<a href="/marketing/brand-reps" ng-click="instant()" class="menu-link" ng-if="account.isCampusManager && menu.toggle=='marketing-rep'" ng-class="{'nav-active': (navigation.page == 'brand-reps')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-users"></i></td>
							<td class="side-menu-label">Brand Reps</a></td>
						</tr>
					</table>
				</a>

				<a href="/marketing/drivers" ng-click="instant()" class="menu-link" ng-if="account.isCampusManager && menu.toggle=='marketing-rep'" ng-class="{'nav-active': (navigation.page == 'drivers')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-road"></i></td>
							<td class="side-menu-label">Drivers</a></td>
						</tr>
					</table>
				</a>

				<a href="/invite" ng-click="instant()" class="menu-link" ng-class="{'nav-active': (navigation.page == 'drivers-invite')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-usd"></i></td>
							<td class="side-menu-label">Earn More Money</a></td>
						</tr>
					</table>
				</a>

				<a href="/campus-manager/orders" ng-click="instant()" class="menu-link" ng-if="account.isCampusManager && menu.toggle=='marketing-rep'" ng-class="{'nav-active': (navigation.page == 'orders')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-car"></i></td>
							<td class="side-menu-label">Orders</a></td>
						</tr>
					</table>
				</a>


				<a href="/staff/activations" ng-click="instant()" class="menu-link" ng-if="account.isMarketingRep && menu.toggle=='marketing-rep' && !account.isCampusManager" ng-class="{'nav-active': (navigation.page == 'marketing-rep-activations')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-trophy"></i></td>
							<td class="side-menu-label">Your Activations</a></td>
						</tr>
					</table>
				</a>

        <a href="https://docs.google.com/forms/d/1TsYU7LKyi8AQhM317n1v-SEiP-8OuiQIReV6XZHd-HM/viewform" target="_system" ng-click="instant()" class="menu-link" ng-class="{'nav-active': (navigation.page == 'drivers-feedback')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-quote-left"></i></td>
							<td class="side-menu-label">Feedback</a></td>
						</tr>
					</table>
				</a>

				<a class="menu-link" ng-click="account.logout()" ng-if="account.user.id_admin">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-sign-out"></i></td>
							<td class="side-menu-label">Sign Out</a></td>
						</tr>
					</table>
				</a>

			</div>

			<div ng-if="menu.toggle=='driver'">
				<a href="/profile" ng-click="instant()" class="menu-link" ng-class="{'nav-active':(navigation.page == 'profile'|| navigation.page == 'drivers-notification')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-user"></i></td>
							<td class="side-menu-label">Profile</a></td>
						</tr>
					</table>
				</a>

				<a href="/drivers/community" ng-click="instant()" class="menu-link" ng-if="account.isDriver && menu.toggle=='driver' && account.user.permissions.GLOBAL && account.user.has_community_to_open" ng-class="{'nav-active': (navigation.page == 'drivers-community')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-slideshare"></i></td>
							<td class="side-menu-label">Community</a></td>
						</tr>
					</table>
				</a>

				<a href="/drivers/orders" ng-click="instant()" class="menu-link" ng-if="account.isDriver && menu.toggle=='driver'" ng-class="{'nav-active': (navigation.page == 'drivers-orders')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-car"></i></td>
							<td class="side-menu-label">Orders</a></td>
						</tr>
					</table>
				</a>

				<a href="/tickets" ng-click="instant()" class="menu-link" ng-if="account.user.permissions['COMMUNITY-CS'] && menu.toggle=='driver'" ng-class="{'nav-active': ( navigation.page == 'tickets' || navigation.page == 'ticket')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-comments-o"></i></td>
							<td class="side-menu-label">Tickets</a></td>
						</tr>
					</table>
				</a>

				<a href="/drivers/shifts" ng-click="instant()" class="menu-link" ng-if="account.isDriver && menu.toggle=='driver'" ng-class="{'nav-active': (navigation.page == 'drivers-shifts')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-calendar"></i></td>
							<td class="side-menu-label">Shifts</a></td>
						</tr>
					</table>
				</a>

				<a href="/drivers/shifts/schedule" ng-click="instant()" class="menu-link" ng-if="account.isDriver && menu.toggle=='driver'" ng-class="{'nav-active': (navigation.page == 'drivers-shift-preferences')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-thumbs-up"></i></td>
							<td class="side-menu-label">Shift Preferences</a></td>
						</tr>
					</table>
				</a>

				<a href="/invite" ng-click="instant()" class="menu-link" ng-if="account.isDriver && menu.toggle=='driver'" ng-class="{'nav-active': (navigation.page == 'drivers-invite')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-usd"></i></td>
							<td class="side-menu-label">Earn More Money</a></td>
						</tr>
					</table>
				</a>

				<a href="/marketing/materials/refill" ng-click="instant()" class="menu-link" ng-class="{'nav-active': (navigation.page == 'marketing-rep-request-materials')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-cubes"></i></td>
							<td class="side-menu-label">Marketing Materials</a></td>
						</tr>
					</table>
				</a>

				<a href="/staff/activations" ng-click="instant()" class="menu-link" ng-class="{'nav-active': (navigation.page == 'activations')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-trophy"></i></td>
							<td class="side-menu-label">Your Activations</a></td>
						</tr>
					</table>
				</a>

				<a href="/drivers/docs" ng-click="instant()" class="menu-link" ng-if="account.isDriver && menu.toggle=='driver'" ng-class="{'nav-active': (navigation.page == 'drivers-documents')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-briefcase"></i></td>
							<td class="side-menu-label">Documents</a></td>
						</tr>
					</table>
				</a>


				<a href="/drivers/summary" ng-click="instant()" class="menu-link" ng-if="(account.user.permissions.GLOBAL || account.isDriver) && menu.toggle=='driver'" ng-class="{'nav-active': (navigation.page == 'drivers-summary')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-bank"></i></td>
							<td class="side-menu-label">Payments</a></td>
						</tr>
					</table>
				</a>


				<a href="/drivers/help" ng-click="instant()" class="menu-link" ng-if="account.isDriver && menu.toggle=='driver'" ng-class="{'nav-active': (navigation.page == 'drivers-help')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-support"></i></td>
							<td class="side-menu-label">FAQ</a></td>
						</tr>
					</table>
				</a>

				<a href="https://docs.google.com/forms/d/1TsYU7LKyi8AQhM317n1v-SEiP-8OuiQIReV6XZHd-HM/viewform" target="_system" ng-click="instant()" class="menu-link" ng-class="{'nav-active': (navigation.page == 'drivers-feedback')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-quote-left"></i></td>
							<td class="side-menu-label">Feedback</a></td>
						</tr>
					</table>
				</a>
				<? /* hiding for now
				<a href="/drivers/drivers-locations" class="menu-link" ng-class="{'nav-active': (navigation.page == 'drivers-locations')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-location-arrow"></i></td>
							<td class="side-menu-label">Track Locations</a></td>
					</tr>
					</table>
				</a>
				*/ ?>

				<a href="/drivers/docs/pexcard" ng-click="instant()" class="menu-link" ng-if="account.isDriver && menu.toggle=='driver'" ng-class="{'nav-active': (navigation.page == 'drivers-pex-card')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-credit-card"></i></td>
							<td class="side-menu-label">Activate PEX Card</a></td>
						</tr>
					</table>
				</a>

				<a href="/resources/" ng-click="instant()" class="menu-link" ng-if="account.user.permissions.GLOBAL && account.isDriver && menu.toggle=='driver' && account.user.has_resource" ng-class="{'nav-active': (navigation.page == 'community-resources')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-files-o"></i></td>
							<td class="side-menu-label">Resources</a></td>
						</tr>
					</table>
				</a>

				<span ng-if="account.isDriver && menu.toggle=='driver'" ng-repeat="resource in account.user.side_resource">
					<a href="{{resource.url}}" ng-click="instant()" target="_system" class="menu-link">
						<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
							<tr>
								<td class="side-menu-icon"><i class="fa fa-files-o"></i></td>
								<td class="side-menu-label">{{resource.name}}</a></td>
							</tr>
						</table>
					</a>
				</span>

				<a class="menu-link" ng-click="instant(); account.logout()" ng-if="account.user.id_admin">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-sign-out"></i></td>
							<td class="side-menu-label">Sign Out</a></td>
						</tr>
					</table>
				</a>

			</div>

			<div ng-if="menu.toggle=='admin'">
<? /*
				<a href="/deploy" ng-click="instant()" class="menu-link" ng-if="(account.user.permissions.GLOBAL || account.user.permissions['SERVER-DEPLOY'] || account.user.permissions['SERVER-DEPLOY-ADMIN']) && menu.toggle=='admin'" ng-class="{'nav-active': (navigation.page == 'deploy' || navigation.page == 'deploy-server' || navigation.page == 'deploy-version')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-code"></i></td>
							<td class="side-menu-label">Code Deployment</a></td>
						</tr>
					</table>
				</a>
				*/ ?>

				<a href="/communities" ng-click="instant()" class="menu-link" ng-if="account.user.permissions.GLOBAL && menu.toggle=='admin'" ng-class="{'nav-active': (navigation.page == 'communities' || navigation.page == 'community')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-slideshare"></i></td>
							<td class="side-menu-label">Communities</a></td>
						</tr>
					</table>
				</a>

			<a href="/chains" ng-click="instant()" class="menu-link" ng-if="account.user.permissions.GLOBAL && menu.toggle=='admin'" ng-class="{'nav-active': (navigation.page == 'chains' )}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-link"></i></td>
							<td class="side-menu-label">Chains</a></td>
						</tr>
					</table>
				</a>

				<a href="/customers" ng-click="instant()" class="menu-link" ng-if="account.user.permissions.GLOBAL && menu.toggle=='admin'" ng-class="{'nav-active': (navigation.page == 'customers' || navigation.page == 'customer')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-smile-o"></i></td>
							<td class="side-menu-label">Customers</a></td>
						</tr>
					</table>
				</a>

				<a href="/drivers/onboarding" ng-click="instant()" class="menu-link" ng-if="account.user.permissions.GLOBAL && menu.toggle=='admin'" ng-class="{'nav-active': (navigation.page == 'drivers-onboarding')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-road"></i></td>
							<td class="side-menu-label">Driver Onboarding</a></td>
						</tr>
					</table>
				</a>

				<a href="/metrics" ng-click="instant()" class="menu-link" ng-if="account.user.permissions.GLOBAL && menu.toggle=='admin'" ng-class="{'nav-active': (navigation.page == 'metrics')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-bar-chart"></i></td>
							<td class="side-menu-label">Metrics</a></td>
						</tr>
					</table>
				</a>

				<a href="/orders" ng-click="instant()" class="menu-link" ng-if="account.user.permissions.GLOBAL && menu.toggle=='admin'" ng-class="{'nav-active': (navigation.page == 'orders' || navigation.page == 'order')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-car"></i></td>
							<td class="side-menu-label">Orders</a></td>
						</tr>
					</table>
				</a>

				<a href="/community/resources/" ng-click="instant()" class="menu-link" ng-if="account.user.permissions.GLOBAL && menu.toggle=='admin'" ng-class="{'nav-active': (navigation.page == 'resources')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-files-o"></i></td>
							<td class="side-menu-label">Resources</a></td>
						</tr>
					</table>
				</a>

				<a href="/restaurants" ng-click="instant()" class="menu-link" ng-if="account.user.permissions.GLOBAL && menu.toggle=='admin'" ng-class="{'nav-active': (navigation.page == 'restaurants' || navigation.page == 'restaurant')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-coffee"></i></td>
							<td class="side-menu-label">Restaurants</a></td>
						</tr>
					</table>
				</a>

				<a href="/settlement" ng-click="instant()" class="menu-link" ng-if="account.user.permissions.GLOBAL && menu.toggle=='admin'" ng-class="{'nav-active': (navigation.page == 'settlement')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-bank"></i></td>
							<td class="side-menu-label">Settlement</a></td>
						</tr>
					</table>
				</a>

				<a href="/shifts" ng-click="instant()" class="menu-link" ng-if="account.user.permissions.GLOBAL && menu.toggle=='admin'" ng-class="{'nav-active': (navigation.page == 'shift')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-calendar"></i></td>
							<td class="side-menu-label">Shifts</a></td>
						</tr>
					</table>
				</a>

				<a href="/staff" ng-click="instant()" class="menu-link" ng-if="account.user.permissions.GLOBAL && menu.toggle=='admin'" ng-class="{'nav-active': (navigation.page == 'staff')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-users"></i></td>
							<td class="side-menu-label">Staff</a></td>
						</tr>
					</table>
				</a>

				<a href="/support" ng-click="instant()" class="menu-link" ng-if="account.user.permissions.GLOBAL && menu.toggle=='admin'" ng-class="{'nav-active': (navigation.page == 'support' || navigation.page == 'calls' || navigation.page == 'ticket' || navigation.page == 'call')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-comments-o"></i></td>
							<td class="side-menu-label">Support</a></td>
						</tr>
					</table>
				</a>

				<a href="/tickets" ng-click="instant()" class="menu-link" ng-if="account.user.permissions.GLOBAL && menu.toggle=='admin'" ng-class="{'nav-active': ( navigation.page == 'tickets')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-comments-o"></i></td>
							<td class="side-menu-label">Tickets</a></td>
						</tr>
					</table>
				</a>

				<a href="/suggestions" ng-click="instant()" class="menu-link" ng-if="account.user.permissions.GLOBAL && menu.toggle=='admin'" ng-class="{'nav-active': (navigation.page == 'suggestions')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-bullhorn"></i></td>
							<td class="side-menu-label">Suggestions</a></td>
						</tr>
					</table>
				</a>

				<a href="/tools" ng-click="instant()" class="menu-link" ng-if="account.user.permissions.GLOBAL && menu.toggle=='admin'" ng-class="{'nav-active': (navigation.page == 'pexcard' || navigation.page == 'blasts' || navigation.page == 'tools' || navigation.page == 'config' || navigation.page == 'config-rewards' || navigation.page == 'config-rules' )}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-cogs"></i></td>
							<td class="side-menu-label">Tools &amp; Config</a></td>
						</tr>
					</table>
				</a>

				<a href="/promo" ng-click="instant()" class="menu-link" ng-if="account.user.permissions.GLOBAL && menu.toggle=='admin'" ng-class="{'nav-active': (navigation.page == 'giftcard' )}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-gift"></i></td>
							<td class="side-menu-label">GiftCard/Discount</a></td>
						</tr>
					</table>
				</a>

        <a href="https://docs.google.com/forms/d/1TsYU7LKyi8AQhM317n1v-SEiP-8OuiQIReV6XZHd-HM/viewform" target="_system" ng-click="instant()" class="menu-link" ng-class="{'nav-active': (navigation.page == 'drivers-feedback')}">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-quote-left"></i></td>
							<td class="side-menu-label">Feedback</a></td>
						</tr>
					</table>
				</a>


			</div>

<? /*
			<a href="/restaurant/order/placement/dashboard" class="menu-link" ng-if="(account.user.permissions.GLOBAL || account.isRestaurant) && menu.toggle=='admin'" ng-class="{'nav-active': (navigation.page == 'restaurant-order-placement')}">
				<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
					<tr>
						<td class="side-menu-icon"><i class="fa fa-credit-card"></i></td>
						<td class="side-menu-label">Order Placement</a></td>
					</tr>
				</table>
			</a>
*/ ?>



			<a href="/login" ng-click="instant()" class="menu-link" ng-if="!account.user.id_admin" ng-class="{'nav-active': (navigation.page == 'login')}">
				<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
					<tr>
						<td class="side-menu-icon"><i class="fa fa-sign-in"></i></td>
						<td class="side-menu-label">Sign In</a></td>
					</tr>
				</table>
			</a>
			<a href="/info" ng-click="instant()" class="menu-link" ng-if="!account.user.id_admin" ng-class="{'nav-active': (navigation.page == 'info')}">
				<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
					<tr>
						<td class="side-menu-icon"><i class="fa fa-support"></i></td>
						<td class="side-menu-label">More Info</a></td>
					</tr>
				</table>
			</a>
			<div class="menu-link">
				<br><br><br><br>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&copy;<?=date('Y')?> Youbeo, Inc.<br><br>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="/legal">Terms of Use</a>
				<br><br><br>
			</div>


		</div>
		<div class="left-menu-fix"></div>
		<div class="snap-drawer snap-drawer-right side-menu" id="side-menu-right">
			<div class="drawer-right-content scroll-tickets" ng-controller="SideSupportCtrl">
				<div class="drawer-right-content-list" ng-include="'/assets/view/tickets-side-list.html'" ng-if="!viewTicket"></div>
				<div class="drawer-right-content-view" ng-include="'/assets/view/tickets-side-view.html'" ng-if="viewTicket"></div>
			</div>
		</div>
	</div>

	<div class="wrapper static-nav-viewport loggedout-hideable">

		<div id="snap-content" class="snap-content">
			<div class="navs fixed" data-position="fixed" ng-controller="MainHeaderCtrl">
				<div class="nav nav-top">
					<div class="content">

						<div title="Menu" class="clickable menu side hide-before-init hide-desktop" ng-click="navigation.menu()" ng-hide="hasBack"></div>
						<div title="Back" class="clickable nav-back hide-before-init" ng-click="back()" ng-show="hasBack"></div>

						<div title="Menu" class="clickable menu side hide-before-init hide-mobile" ng-click="menuToggle()">
							<i class="fa fa-bars"></i>
						</div>

						<div class="notifications" ng-show="account.user.id_admin">

							<div class="flash-message {{flash.getLevel()}}" ng-show="flash.hasMessage()">
								<p>{{flash.getMessage()}}</p>
							</div>

							<div class="clickable hide-mobile notification notification-call" ng-class="{'blink' : callStatus == 'connecting'}" ng-click="twilio.hangup()" ng-if="callStatus == 'connecting' || callStatus == 'connected'">
								<i class="fa fa-phone"></i>
							</div>
							<div class="clickable hide-mobile notification notification-mute" ng-click="twilio.mute()" ng-if="callStatus == 'connected'">
								<i ng-if="!isMute" class="fa fa-microphone"></i>
								<i ng-if="isMute" class="fa fa-microphone-slash"></i>
							</div>
							<div class="clickable notification notification-support" ng-if="account.user.permissions.GLOBAL" ng-click="navigation.link('/support/phone', 'instant')">
								<i class="fa fa-phone-square"></i>
							</div>
							<div ng-if="account.isDriver" class="clickable notification notification-orders" ng-click="navigation.link('/drivers/orders', 'instant')">
								<div class="badge" ng-show="newDriverOrders.count">{{newDriverOrders.count}}</div>
								<i class="fa fa-truck"></i>
							</div>
							<div class="clickable hide-desktop notification notification-support" ng-class="{'notification-support-mobile': !account.user.permissions.GLOBAL}" ng-click="navigation.menu('right')">
								<div class="badge" ng-show="supportMessages.count && supportMessages.count != '0'">{{supportMessages.count}}</div>
								<i class="fa fa-comment"></i>
							</div>
							<div class="clickable hide-mobile notification notification-support" ng-class="{'notification-support-mobile': !account.user.permissions.GLOBAL}" ng-click="supportToggle()">
								<div class="badge" ng-show="supportMessages.count && supportMessages.count != '0'">{{supportMessages.count}}</div>
								<i class="fa fa-comment"></i>
							</div>
							<? /*
							<div class="notification notification-alerts" ng-click="navigation.link('/alerts')">
								<i class="fa fa-bell"></i>
							</div>
							*/ ?>
						</div>


						<div class="nav-account hide-mobile">
							<a href="/profile" class="user-name">{{account.user.name}}</a>
						</div>

						<div class="logo"><span class="logo-connection-status" ng-class="{'green': socketConnected}">{{navTitle || 'cockpit'}}</span></div>

					</div>
				</div>
			</div>
			<div ng-controller="DriversOrderNavCtrl">
				<div ng-include="'/assets/view/drivers-accept-nav.html'"></div>
			</div>

			<div class="snap-content-inner bg" ng-scroll-position>
				<div class="content" ng-class="{'support-side-open': supportToggled }" ng-scroll-spy>
					<div ng-view id="ng-view" class="view-animate"><?=$this->content?></div>
				</div>

				<div class="divider"></div>
			</div>

		</div>

		<div class="divider"></div>
	</div>

	<div id="fb-root"></div>



	<!-- Notification -->
	<div class="notification-alert-container zoom-anim-dialog mfp-hide dialog" ng-controller="NotificationAlertCtrl">
		<h1 ng-bind="alertTitle" ng-show="alertTitle"></h1>
		<p ng-class="{'unselectable': unselectable}" ng-bind-html-unsafe="message" class="small-message"></p>
		<button ng-click="complete()" class="button green">OK</button>
	</div>

	<!-- Confirmation Box -->
	<div class="notification-confirm-container zoom-anim-dialog mfp-hide dialog" ng-controller="NotificationConfirmCtrl">
		<h1 ng-bind="alertTitle" ng-show="alertTitle"></h1>
		<p ng-bind-html-unsafe="message" class="small-message"></p>
		<div class="double-cols">
			<button ng-click="complete()" class="button green">{{buttonOk}}</button>
			<button ng-click="cancel()" class="button orange">{{buttonCancel}}</button>
			<br>
		</div>
		<div class="divider"></div>
	</div>

	<div class="agreement-container zoom-anim-dialog mfp-hide dialog" ng-controller="AgreementBoxCtrl">
		<h1 ng-bind="confirmationTitle" ng-show="confirmationTitle"></h1>
		<p ng-bind-html-unsafe="message" class="small-message"></p>
		<div class="no-box-content-color">
			<ul class="ul-inputs">
				<li class="li-input divider-line">
					<label class="switch-wrap">
						<input type="checkbox" class="switch" ng-model="agree"/><div></div>
					</label>
					<div class="label">I agree!</div>
				</li>
				<li class="li-input" ng-show="agree">
					<button ng-show="agree" ng-click="complete()" class="button green">Ok</button>
				</li>
				<li class="li-input" ng-show="!agree">
					<a href="#" ng-click="cancel()">Cancel</a>
				</li>
			</ul>
		</div>
		<div class="divider"></div>
	</div>

	<!-- Notification new order -->
	<div class="notification-new-order-container zoom-anim-dialog mfp-hide dialog" ng-controller="NotificationNewOrderCtrl">
		<h1>New Order</h1>
		<p ng-bind-html-unsafe="message" class="small-message"></p>
		<div>
			<button ng-click="accept()" class="button green">Accept</button>
		</div>
		<br>
		<div class="double-cols">
			<button ng-click="view()" class="button lightorange">View</button>
			<button ng-click="close()" class="button light-gray">Close</button>
			<br>
		</div>
		<div class="divider"></div>
	</div>


	<!-- SMS vs Phone -->
	<div class="notification-call-text-container zoom-anim-dialog mfp-hide dialog" ng-controller="CallText">

		<h1 class="dialog-call-number" ng-if="!staffList">{{number | formatPhone}}</h1>

		<h1 class="dialog-call-number" ng-if="staffList">
			{{number.length}}
			<span ng-if="number.length > 1">Phone numbers</span>
			<span ng-if="number.length == 1">Phone</span>
			<span ng-if="number.length < 1">You should select at least one number</span>
		</h1>


		<ul class="drivers-list" ng-show="number.length" ng-if="staffList">
			<li ng-repeat="n in number track by $index">
				<label>
					Phone {{$index + 1}}: {{n}}
				</label>
			</li>
		</ul>

		<div class="hide-desktop">

			<a href="sms:{{number}}" class="number-action" target="_system">
				<button class="button green">Text</button>
			</a>

			<a href="tel:{{number}}" class="number-action" target="_system">
				<button class="button green">Call</button>
			</a>

		</div>

		<div class="hide-mobile" ng-show="hideSMSBox && hideCallBox">

			<a href="" ng-click="hideSMSBox = false" class="number-action">
				<button class="button green">Text</button>
			</a>

			<a href="" ng-click="hideCallBox = false" class="number-action">
				<button class="button green">Call</button>
			</a>

		</div>

		<ng-include src="'/assets/view/support-phone.html'"></ng-include>
		<ng-include src="'/assets/view/orders-order-refund.html'"></ng-include>

	</div>


	<!-- Gift card / credit -->
	<div class="credit-dialog zoom-anim-dialog mfp-hide dialog">
		<ng-include src="'/assets/view/credit-dialog.html'"></ng-include>
	</div>

	<ng-include src="'/assets/view/maps-dialog.html'"></ng-include>
	<ng-include src="'/assets/view/communities-community-add-note-form.html'"></ng-include>
	<ng-include src="'/assets/view/staff-add-note-form.html'"></ng-include>

</div>
