<?=$this->display('layout/html.servertime')?>

<? if ($_REQUEST['_bundle']) $this->display('layout/html.templates')?>

<script src="//media.twiliocdn.com/sdk/js/client/v1.3/twilio.min.js"></script>
<script src="https://www.google.com/jsapi"></script>
<script src="https://maps.googleapis.com/maps/api/js?libraries=places&sensor=false&key=AIzaSyDNJ0f3yxbeksuiQh0iG1_drBO1Mmhg_Bg"></script>
<script src="https://js.stripe.com/v2/" bundle="false"></script>
<script>
	Stripe.setPublishableKey( '<?=c::config()->stripe->{c::getEnv()}->{'public'}?>' );
</script>

<? /*if (c::config()->bundle) : ?>
	<? $js = c::config()->site->config('s3-bundle')->val() ? 'https://'.c::config()->s3->buckets->build->cache.'/'.getenv('HEROKU_SLUG_COMMIT').'/js/cockpit.js' : '/assets/cockpit/js/bundle.js?v='.getenv('HEROKU_SLUG_COMMIT').'&s=cockpit' ?>
	<script src="<?=$js?>"></script>
<? else : ?>
	<?=$this->display('bundle/js', ['set' => ['scripts' => ['cockpit']]])?>
<? endif ;*/ ?>
<?=$this->display('bundle/js', ['set' => ['scripts' => ['cockpit']]])?>