<?=$this->display('layout/html.top')?>

<? if (c::config()->bundle) : ?>
	<script src="/assets/cockpit/js/bundle.js?v=<?=Deploy_Server::currentVersion()?>&s=cockpit"></script>
<? else : ?>
	<?=$this->display('bundle/js', ['set' => ['scripts' => ['cockpit']]])?>
<? endif ; ?>

<?=$this->display('layout/html.bottom')?>

<script src="//static.twilio.com/libs/twiliojs/1.2/twilio.min.js"></script>
<script src="//maps.googleapis.com/maps/api/js?libraries=places&sensor=false"></script>
<script src="//js.stripe.com/v2/" bundle="false"></script>
<script type="text/javascript">
	Stripe.setPublishableKey( '<?=c::config()->stripe->{c::getEnv()}->{'public'}?>' );
</script>
<? /* &key=AIzaSyBSQXZPG5n_yRG4umquaDANsL62uhlgaE8 */ ?>