</head>
<? //  bgcolor="#202228" ?>
<body class="no-init">
<div class="loader-wrap">
	<div class="loader-frame"><div class="loader">&nbsp;</div></div>
</div>
<?=$this->display('layout/html.body')?>	
</body>


<script type="text/javascript">
$(function() {
	App.request( App.service + 'config?init=1', function(r) {
		App._remoteConfig = true;
		App.init(r);
	}, function() {
		App._remoteConfig = false;
		App.init({});
	});
});
</script>

<audio id="support-message-new">
	<source src="/assets/cockpit/audio/message-creation.wav"></source>
</audio>
<audio id="support-message-recieved">
	<source src="/assets/cockpit/audio/message-inbound.wav"></source>
</audio>

<? /*
<script type="text/javascript">
	$(function() {
		window.fbAsyncInit = function() {
			console.debug('Init facebook <?=Cana::config()->facebook->app?>');
			FB.init({
				appId: '<?=Cana::config()->facebook->app?>',
				cookie: true,
				xfbml: true,
				oauth: true
			});
			var facebookService = angular.element('html').injector().get('FacebookService');
			FB.Event.subscribe('auth.statusChange', facebookService.processStatus);
		};
		
		(function(d, s, id) {
		var js, fjs = d.getElementsByTagName(s)[0];
		if (d.getElementById(id)) return;
		js = d.createElement(s); js.id = id;
		js.src = '//connect.facebook.net/en_US/all<?=strpos($_SERVER['__HTTP_HOST'],'localhost') !== false ? '/debug' : ''?>.js';
		fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));
	});


</script>
*/?>
