</head>
<? //  bgcolor="#202228" ?>
<body class="no-init" ng-controller="AppController">
<div class="loader-wrap">
	<div class="loader-frame"><div class="loader">&nbsp;</div></div>
</div>
<?=$this->display('layout/html.body')?>
</body>

<audio id="support-message-new">
	<source src="/assets/cockpit/audio/message-creation.wav"></source>
</audio>
<audio id="support-message-recieved">
	<source src="/assets/cockpit/audio/message-inbound.wav"></source>
</audio>
