<?=$this->display('layout/html.top')?>

<script src="https://static.twilio.com/libs/twiliojs/1.2/twilio.min.js"></script>

<? if (c::config()->bundle) : ?>
	<? $js = c::config()->site->config('s3-bundle')->val() ? 'https://'.c::config()->s3->buckets->build->cache.'/'.Deploy_Server::currentVersion().'/js/cockpit.js' : '/assets/cockpit/js/bundle.js?v='.Deploy_Server::currentVersion().'&s=cockpit' ?>
	<script src="<?=$js?>"></script>
<? else : ?>
	<?=$this->display('bundle/js', ['set' => ['scripts' => ['cockpit']]])?>
<? endif ; ?>

<?=$this->display('layout/html.bottom')?>


<script src="//maps.googleapis.com/maps/api/js?libraries=places&sensor=false"></script>
<script src="//js.stripe.com/v2/" bundle="false"></script>
<script type="text/javascript">
	Stripe.setPublishableKey( '<?=c::config()->stripe->{c::getEnv()}->{'public'}?>' );
</script>
<? /* &key=***REMOVED*** */ ?>
