<div class="divider dots spacer-one-two" ng-show="order.info.subtotal && order.info.subtotal!='0.00' && restaurant._open"></div>

<div class="payment-total content-padding" ng-if="order.info.subtotal && order.info.subtotal!='0.00' && restaurant._open">
	<div class="restaurant-banana animated-resize"></div>

	<div class="payment-wrap">
		<div class="payment-ribbon" ng-class="{'backface':!isIOs}">
			<div class="payment-ribbon-content">
				<span class="restaurant-payment-item">Subtotal: <span ng-show="order.form.pay_type=='cash'">~</span>{{AB.dollar}}{{order.info.subtotal}}</span>
				<span class="restaurant-payment-item">Tax: {{AB.dollar}}{{order.info.taxes}}</span>
				<span class="restaurant-payment-item" ng-show="order.form.pay_type!='cash' && order.info.tip!='0.00'">Tip: {{AB.dollar}}{{order.info.tip}}</span>
				<span class="restaurant-payment-item" ng-show="order.info.delivery!='0.00' && order.info.delivery_service_fee!='0.00'">Delivery Fee: {{AB.dollar}}{{order.info.delivery_service_fee}}</span>
				<span class="restaurant-payment-item" ng-show="order.info.delivery=='0.00' && order.info.fee!='0.00'">Service Fee: {{AB.dollar}}{{order.info.fee}}</span>
				<span class="restaurant-payment-item" ng-show="credit.hasValue && order.form.pay_type == 'card'">Credit: -$
					<span ng-show="order.total() <= credit.number">{{order.info.total}}</span>
					<span ng-show="order.total() > credit.number">{{credit.value}}</span>
				</span>
				<span class="restaurant-payment-item">Bananas: 0</span>
				<span class="restaurant-payment-item">Total: <b>{{order.info.totalText}}</b></span>
			</div>
		</div>
		<div class="divider"></div>
	</div>
	<div class="divider"></div>

	<div ng-if="credit.hasValue && order.form.pay_type == 'cash' && order.total() >= credit.number">
		<div class="giftcard-payment-message">Pay with a card, NOT CASH, to use your {{AB.dollar}}{{credit.value}} gift card</div>
	</div>

	<div ng-show="restaurant.delivery == '1' && order.form.delivery_type=='delivery' && points.free_delivery_message">
		<p class="delivery-free restaurant-delivery-free">
			<strong ng-if="order.form.pay_type == 'card'">You have {{points.show}} points! This delivery fee is on us.</strong>
			<strong ng-if="order.form.pay_type == 'cash'">Pay with a card, NOT CASH, to get our delivery free.</strong>
			<br/>
		</p>
	</div>

</div>
