<div class="top-pad"></div>

<div class="content-padding">

	<h1 class="title box-title"><i class="fa fa-gift"></i>Gift Card / Discount Codes</h1>

	<div class="support-boxes">

		<div class="support-box-wrap box-content2">
			<div class="support-box-wrap-header">
				<h1><i class="fa fa-minus-circle"></i>Discount Codes</h1>
				<div class="divider"></div>
			</div>

			<div class="box-content-table">
				<table>
					<tr><td><a href="/promo/discount-codes">Discount Codes</a></td></tr>
					<tr><td><a href="/promo/discount-code/">Create Discount Code</a></td></tr>
				</table>
			</div>
		</div>

		<div class="support-box-wrap box-content2">
			<div class="support-box-wrap-header">
				<h1><i class="fa fa-gift"></i>Gift Card</h1>
				<div class="divider"></div>
			</div>

			<div class="box-content-table">
				<table>
					<tr><td><a href="/promo/gift-cards">Gift Cards</a></td></tr>
					<tr><td><a href="/promo/gift-card/generate">Generate Gift Cards</a></td></tr>
				</table>
			</div>
		</div>

	</div>

</div>
