<div class="top-pad"></div>

<div class="content-padding">
	<div class="page-title-wrap">
		<h1 class="title left"><i class="fa fa-gift"></i><span>Gift Cards</span></h1>
		<div class="page-title-nav">
			<a href="/promo/gift-card/generate"><button class="button button-green nav-button-green"><i class="fa fa-plus"></i><span>Add Gift Card</span></button></a>
		</div>
	</div>
	<div class="divider"></div>
	<div class="box-content2 box-content-table">
		<table>
			<tr>
				<td colspan="1"><i class="fa fa-search"></i>&nbsp;&nbsp;<input type="text" ng-model="query.search" id="search" tabindex="1"></td>
			</tr>
			<tr>
				<th>Redeemed</th>
				<td>
					<select ng-model="query.redeemed" name="searchRedeemed" tabindex="2">
						<option value="all">All</option>
						<option value="yes">Yes</option>
						<option value="no">No</option>
					</select>
				</td>
			</tr>
		</table>
	</div>
	<div class="bar-loader bar-loader-search" ng-class="{'bar-loader-loading': loading}"></div>
	<ng-include src="'assets/view/listview-promo-gift-card.html'"></ng-include>
	<ng-include src="'assets/view/listview-paging.html'"></ng-include>
</div>
