<div class="top-pad"></div>

<div class="content-padding">
	<div class="box-content2 box-content-table box-search-bar table-sticky-dependant">
		<table>
			<tr>
				<td colspan="2">
					<i class="fa fa-search"></i>&nbsp;&nbsp;<input type="text" ng-model="query.search" id="search" tabindex="1">
				</td>
				<td>
					<div class="page-title-nav">
						<a href="/promo/gift-card/create"><button class="button button-green nav-button-green"><i class="fa fa-send"></i><span>Add/Send a Gift Card</span></button></a>
						<a href="/promo/gift-card/generate"><button class="button button-green nav-button-green"><i class="fa fa-plus"></i><span>Generate Gift Cards</span></button></a>
					</div>
				</td>
			</tr>
			<tr>
				<th>Redeemed</th>
				<td>
					<select ng-model="query.redeemed" name="searchRedeemed" tabindex="2">
						<option value="all">All</option>
						<option value="yes">Yes</option>
						<option value="no">No</option>
					</select>
				</td>
			</tr>
		</table>
	</div>
	<div class="bar-loader bar-loader-search" ng-class="{'bar-loader-loading': loading}"></div>
	<ng-include src="'/assets/view/listview-promo-gift-card.html'"></ng-include>
	<div sticky-bottom="47" class="table-sticky-dependant" ng-show="pages > 1 || more || query.page > 1">
		<div class="no-box-content-color">
			<ng-include src="'/assets/view/listview-paging.html'"></ng-include>
		</div>
	</div>
</div>
