<?
/**
 * Exports the order information in a CSV file
 *
 * @package Crunchbutton.Admin.Order
 * @category view
 */

$headers = [
	'Restaurant Name',
	'Customer name',
	'Order Date',
	'Order Time',
	'Total',
	'Subtotal',
	'Tax',
	'Tip',
	'Delivery Fee',
	'Service Fee',
	'Customer Fee Percent',
	'Restaurant Fee Percent',
	'Cash or Card',
	'Refunded',
	'Payment Method',
	'Check address or bank info',
	'Payment frequency',
	'Last date paid',
	'Customer Phone',
	'Community',
	'Restaurant Fax',
	'Restaurant Email',
	'Gift Card Total',
	'Gift Card Crunchbutton',
	'Gift Card Restaurant',
	'Gift Card Promotional',
	'Gift Card Other restaurant',
	'Total Charged',
	'Notes',
];

echo implode(',', $headers)."\n";
?>
<? foreach ($this->orders as $order) :
	/* @var $order Crunchbutton_Order */
	$date = $order->date();
	if( $order->chargedByCredit() > 0 ){
		$credit = number_format($order->chargedByCredit(),2);
		$credit_crunchbutton = Crunchbutton_Credit::creditByOrderPaidBy( $order->id_order, Crunchbutton_Credit::PAID_BY_CRUNCHBUTTON );
		$credit_restaurant = Crunchbutton_Credit::creditByOrderPaidBy( $order->id_order, Crunchbutton_Credit::PAID_BY_RESTAURANT );
		$credit_promotional = Crunchbutton_Credit::creditByOrderPaidBy( $order->id_order, Crunchbutton_Credit::PAID_BY_PROMOTIONAL );
		$credit_other_restaurant = Crunchbutton_Credit::creditByOrderPaidBy( $order->id_order, Crunchbutton_Credit::PAID_BY_OTHER_RESTAURANT );
	} else {
		$credit = '';
		$credit_crunchbutton = '';
		$credit_restaurant = '';
		$credit_promotional = '';
		$credit_other_restaurant = '';
	}
	$charged = number_format($order->charged(),2);
	
	ob_start();
?>
		"<?=$order->restaurant()->name          // Restaurant Name?>",
		"<?=$order->name                        // Customer name?>",
		"<?=$date->format('M jS Y')             // Order Date?>",
		"<?=$date->format('g:i:s A')            // Order Time?>",
		<?=number_format($order->final_price,2) // Total?>,
		<?=number_format($order->price,2)       // Subtotal?>,
		<?=$order->tax()                        // Tax?>,
		<?=$order->tip()                        // Tip?>,
		<?=$order->deliveryFee()                // Delivery Fee?>,
		<?=$order->serviceFee()                 // Service Fee?>,
		<?=$order->service_fee                  // Customer Fee Percent?>,
		<?=$order->restaurant()->fee_restaurant // Restaurant Fee Percent?>,
		"<?=$order->pay_type                    // Cash or Card?>",
		"<?=$order->refunded ? 'yes' : ''       // Refunded?>",
		"<?=''                                  // Payment Method?>",
		"<?=''                                  // Check address or bank info?>",
		"<?=''                                  // Payment frequency?>",
		"<?=''                                  // Last date paid?>",
		<?=$order->phone?>,
		<?=$order->community()->name?>,
		"<?=$order->restaurant()->fax()         // Restaurant fax?>",
		"<?=$order->restaurant()->email()       // Restaurant email?>",
		"<?=$credit															// Credit total value?>",
		"<?=$credit_crunchbutton								// Credit paid by Crunchbutton?>",
		"<?=$credit_restaurant									// Credit paid by the restaurant?>",
		"<?=$credit_promotional									// Credit paid by promotional?>",
		"<?=$credit_other_restaurant						// Credit paid by other restaurant?>",
		"<?=$charged														// Total charged?>",
		"<?=$order->notes?>"
<?
	$output = ob_get_clean();
	$output = preg_replace('/\n|\r|\t/i', '', $output);
	echo "$output\n";
?>
<? endforeach ; ?>