<? if (!$this->giftcards->count()) : ?>
	No results found
<? else : ?>
	<table class="table table-normal">
		<thead>
			<td>Date</td>
			<td>Code</td>
			<td>Value</td>
			<td>Restaurant</td>
			<td>User</td>
			<td>Phone</td>
			<td>Email</td>
			<td>Note</td>
			<td>Issued as</td>
			<td>Status</td>
		</thead>
		<? foreach ($this->giftcards as $giftcard) : ?>
			<? 
				$date = $giftcard->date(); 
				$wasUsed = CrunchButton_Promo::giftWasAlreadyUsed( $giftcard->id_promo );
			?>
			<tr class="<?=strtolower($giftcard->type); ?>">
				<td> <?=$date->format('M jS Y')?><br /><?=$date->format('g:i:s A')?> </td>
				<td> 
					<?php if( !$wasUsed ) { ?>
						<a title="Print" target="_blank" href="/giftcards/print/<?=$giftcard->id_promo;?>"><i style="color:black;" class="icon-print"></i></a>
					<?php } ?>&nbsp;&nbsp;
					<a href="/giftcards/<?=$giftcard->id_promo;?>"><?=$giftcard->code; ?></a>
				</td>
				<td> $<?= Util::ceil($giftcard->value, 2); ?></td>
				<td> <? if( $giftcard->id_restaurant ){ echo $giftcard->restaurant()->name; } else { echo 'Any Restaurant'; } ?> </td>
				<td> <? if( $giftcard->user()->name != '' ){ echo $giftcard->user()->name; } else { echo '-'; } ?> </td>
				<td> <? if( $giftcard->phone ){ echo $giftcard->phone; } else { echo '-'; } ?> </td>
				<td> <? if( $giftcard->email ){ echo $giftcard->email; } else { echo '-'; } ?> </td>
				<td> <?=nl2br( $giftcard->note ); ?> </td>
				<td> 
					<? if ( $giftcard->issued == Promo::ISSUED_CREDIT ){ ?>
						<i class="icon-money"></i> Credit
					<?php } elseif ( $giftcard->issued == Promo::ISSUED_TEXT ){ ?>
						<i class="icon-mobile-phone"></i> Text
					<?php } elseif ( $giftcard->issued == Promo::ISSUED_EMAIL ){ ?>
						<i class="icon-envelope"></i> Email
					<?php } elseif ( $giftcard->issued == Promo::ISSUED_PRINT ){ ?>
						<i class="icon-print"></i> Paper (print)
					<?php } else { ?> - <?php } ?>
				</td>
				<td> 
					<?php if( $wasUsed ) { ?>
						<span class="badge badge-green">Redeemed</span>
					<?php } else { ?>
						<span class="badge badge-black">Not redeemed</span>
					<?php } ?>
			</tr>
		<? endforeach ; ?>
	</table>
<? endif ; ?>