<div class="admin-content-wrapper">
	<div class="admin-content admin-content-giftcards">
		<table class="admin-giftcards-filter">
			<tr>
				<td class="label-sub" nowrap="nowrap">Code</td>
				<td class="content-sub"><input name="id_order" type="text" style="width: 200px;" value="<?=strip_tags($_REQUEST['code'])?>"></td>
				<td style="width: 100%"></td>
				<td class="label-sub">DATE&nbsp;RANGE</td>
				<?
					$date = new DateTime('now');
					$start = $date->format('m/d/Y');
					$date->modify('14 days ago');
					$end = $date->format('m/d/Y');
				?> 
				<td class="content-sub"><input name="date-range" class="date-picker" type="text" style="width: 200px;" value="<?=$end?>,<?=$start?>"></td>
				<td class="giftcard-range-all" nowrap>&nbsp;&nbsp;<input type="checkbox" name="giftcard-range-all"><label>&nbsp;All Dates</label></td>
			</tr>
			<tr>
				<td class="label-sub">LIMIT</td>
				<td class="content-sub">
					<input type="number" name="limit" value="25" min="0">
				</td>
				<td style="width: 100%"></td>
				<td class="label-sub">RESTAURANT</td>
				<td class="content-sub" colspan="2">
					<select name="restaurant">
						<option value="" selected>[ All ]</option>
						<? foreach (Restaurant::q('SELECT DISTINCT(restaurant.id_restaurant), restaurant.name FROM restaurant INNER JOIN promo ON promo.id_restaurant = restaurant.id_restaurant ORDER BY name ') as $restaurant) : ?>
							<option value="<?=$restaurant->id_restaurant?>"><?=$restaurant->name?></option>
						<? endforeach ; ?>
					</select>
				</td>
			</tr>
			<tr>
				<td colspan="6">
					<table cellpadding="3" cellspacing="3" style="width: 100%; margin: 0 auto;">
						<tr>
							<td><div class="action-button green action-button-small admin-giftcard-search"><span>Search</span></div></td>
							<td>
							<div class="action-button green action-button-small admin-giftcard-email"><span>Promo code by EMAIL</span></div>
							<div class="action-button green action-button-small admin-giftcard-sms" style="margin:0 5px;"><span>Promo code by SMS</span></div>
							<div class="action-button green action-button-small admin-giftcard-new"><span>Create promo codes</span></div>
							</td>
						</tr>
					</table>
				</td>
				
			</tr>
		</table>
		<br /><br />
		<div class="divider dots"></div>
		<br />
		<div class="giftcards-loader"><img src="/assets/images/admin/loader.gif"></div>
		<div class="giftcards-content"></div>
	</div>
</div>		
<script>


	$(function() {		
		$(document).on('click', '.admin-giftcard-search', function() {
			App.giftcards.load();
		} );

		$(document).on('keyup', '[name="id_order"]', function( e ) {
			if (e.which == 13) {
				App.giftcards.load();
			}
		} );

		$(document).on('keyup', '[name="id_user"]', function( e ) {
			if (e.which == 13) {
				App.giftcards.load();
			}
		} );

		$(document).on('click', '.admin-giftcard-new', function() {
			location.href="/giftcards/new";
		} );

		$(document).on('click', '.admin-giftcard-sms', function() {
			location.href="/giftcards/sms";
		} );
		
		$(document).on('click', '.admin-giftcard-email', function() {
			location.href="/giftcards/email";
		} );
		

		$(document).on('change', 'input[name="giftcard-range-all"]', function( e ) {
			if ($(this).prop('checked')) {
				$('.date-picker').attr('disabled', 'disabled');
				$('.date-picker').val('');
			} else {
				$('.date-picker').removeAttr('disabled');
			}
		});
		App.giftcards.load();
	});
</script>