<?
	$this->title = 'Gift cards';
	$this->titleicon = 'gift';
	$this->titleLink = '/giftcards';
	
	$this->title2 = 'Create';
	$this->title2icon = 'file';
	

?>



<div class="container-fluid padded">
	<div class="row-fluid">
		<div class="box">
			<div class="box-content padded">


		
				<table class="admin-giftcard-form">
					<tr>
						<td class="label-primary">Promo code:</td>
						<td class="content-primary">
							<div class="check-wrap">
								<div class="check-content">
									<table style="width:100%;">
										<tbody>
											<tr>
												<td class="label-sub">Value:</td>
												<td class="content-sub"><input type="text" id="value" name="value"></td>
											</tr>
											<tr>
												<td class="label-sub">Number of giftcards:</td>
												<td class="content-sub"><input type="text" id="total" value="1" name="total"></td>
											</tr>
											<?php if( $this->user ) { ?>
											<tr>
												<td class="label-sub">User:</td>
												<td class="content-sub">
														<input type="text" readonly="readonly" id="user_name" name="user_name" value="<?php echo $this->user->name;?>">
														<input type="hidden" id="id_user" name="id_user" value="<?php echo $this->user->id_user;?>">
													</td>
											</tr>
											
											<tr>
												<td>Notify by</td>
												<td>
													<?php if( $this->user->email != '' ) { ?>
														<input type="checkbox" value="1" name="notify_by_email" id="notify_by_email"> Notify by email (<?php  echo $this->user->email; ?>).
													<?php } ?>
													<br/>
													<?php if( $this->user->phone != '' ) { ?>
														<input type="checkbox" value="1" name="notify_by_sms" id="notify_by_sms"> Notify by phone (<?php  echo $this->user->phone; ?>).
													<?php } ?>

												</td>
											</tr>
											
											<tr>
												<td>&nbsp;</td>
												<td>&nbsp;</td>
											</tr>
											<tr>
												<td class="label-sub" nowrap="nowrap">Order reference:</td>
												<td class="content-sub">
													<input type="text" id="id_order_reference" name="id_order_reference" value="<?php echo $this->id_order_reference;?>">
												</td>
											</tr>
											<?php } ?>
											<tr>
												<td class="label-sub">Restaurant:</td>
												<td class="content-sub">
													<select id="id_restaurant" class="chosen-select" multiple name="id_restaurant" data-placeholder="Choose a restaurant" style="width:350px;">
														<option value="" selected></option>
														<option value="*" <?php if( !$this->id_restaurant){ echo 'selected'; } ?>>** ANY RESTAURANT **</option>
														<? foreach (Restaurant::q('SELECT * FROM restaurant WHERE giftcard = 1 ORDER BY name') as $restaurant) : ?>
															<option value="<?=$restaurant->id_restaurant?>" <?php if( $this->id_restaurant == $restaurant->id_restaurant ){ echo 'selected="selected"'; } ?> ><?=$restaurant->name?></option>
														<? endforeach ; ?>
													</select>
												</td>
											</tr>
											<tr>
												<td>&nbsp;</td>
												<td>&nbsp;</td>
											</tr>
											<tr>
												<td class="label-sub" nowrap="nowrap">Paid by:</td>
												<td class="content-sub">
													<select name="paid_by" id="paid_by">
														<option value="crunchbutton">crunchbutton</option>
														<option value="restaurant">restaurant</option>
														<option value="promotional">promotional</option>
														<option value="other_restaurant">other_restaurant</option>
													</select>
												</td>
											</tr>
											<tr id="row_id_restaurant_paid_by" style="display:none;">
												<td class="label-sub">Restaurant that paid the credit:</td>
												<td class="content-sub">
													<select id="id_restaurant_paid_by" class="chosen-select" name="id_restaurant_paid_by" data-placeholder="Choose a restaurant" style="width:350px;">
														<option value="" selected></option>
														<? foreach (Restaurant::q('SELECT * FROM restaurant ORDER BY name') as $restaurant) : ?>
															<option value="<?=$restaurant->id_restaurant?>" <?php if( $this->id_restaurant == $restaurant->id_restaurant ){ echo 'selected="selected"'; } ?> ><?=$restaurant->name?></option>
														<? endforeach ; ?>
													</select>
												</td>
											</tr>
											<?php if( $this->user ) { ?>
											<tr>
												<td class="label-sub"></td>
												<td class="content-sub">
													<input type="checkbox" value="1" name="add_as_credit" id="add_as_credit">Add as credit.
													<span style="font-size:11px;display:block;">
														If you check this option the user will receive the credit without the need to redeem it. The user will not be notified.
													</span>
												</td>
											</tr>
											<?php } ?>
										</tbody>
									</table>
									
								</div>	
							</div>
						</td>
					</tr>
				</table>
		
				<table class="admin-giftcard-form">
					<tr>
						<td class="label-primary">More info:</td>
						<td class="content-primary">
							<div class="check-wrap">
								<div class="check-content">
									<table style="width:100%;">
										<tbody>
											<tr>
												<td class="label-sub">Created by:</td>
												<td class="content-sub"><input type="text" id="created_by" name="created_by" value="<?php echo $_SESSION['username']; ?>"></td>
											</tr>
											<tr>
												<td class="label-sub"></td>
												<td class="content-sub"><input type="checkbox" id="track" value="1" name="track"> Track this gift card</td>
											</tr>
											<tr class="track-fields">
												<td class="label-sub">Notify phone:</td>
												<td class="content-sub">
													<?php
													if ($_SESSION['admin'] && c::config()->testphone->{ $_SESSION[ 'username' ] } ) {
														$phone = c::config()->testphone->{ $_SESSION[ 'username' ] };
													}
													?>
													<input type="text" id="notify_phone" value="<?php echo $phone; ?>" name="notify_phone">
													<br />
													<span style="font-size:11px;">
														*Phone number that will receive a sms <br/>notification when this gift card is redeemed.
													</span>
												</td>
											</tr>
											<tr class="track-fields">
												<td class="label-sub">Customer Name:</td>
												<td class="content-sub"><input type="text" id="name" value="" name="name"></td>
											</tr>
											<tr class="track-fields">
												<td class="label-sub">Contact Info:</td>
												<td class="content-sub"><textarea name="contact" id="contact"></textarea></td>
											</tr>
											<tr>
												<td class="label-sub">Notes + Follow-up?</td>
												<td class="content-sub"><textarea name="note" id="note"></textarea></td>
											</tr>
										</tbody>
									</table>
									<div class="divisor"></div>

								</div>
							</div>
									<button type="submit" class="btn btn-blue admin-giftcard-save"><i class="icon-save"></i>&nbsp;&nbsp;&nbsp; Save </button> 
									<button type="submit" class="btn btn-blue admin-giftcard-print"><i class="icon-print"></i>&nbsp;&nbsp;&nbsp; Save &amp; Print </button> 

						</td>
					</tr>
				</table>
	</div>
</div>		
	</div>
</div>

<script>
$(function() {
	$( '#paid_by' ).change( function(){
		var self = $( this );
		$( '#row_id_restaurant_paid_by' ).hide();
		if( self.val() == 'other_restaurant' ){
			$( '#row_id_restaurant_paid_by' ).show();
		}
	} );
	App.giftcards.prepareForm();
	$(".chosen-select").chosen();
});
</script>