<link href='http://fonts.googleapis.com/css?family=Atomic+Age' rel='stylesheet' type='text/css'>
<style type="text/css">
	.giftcard{
		font-family: 'Atomic Age', cursive;
		height: 340px;
		margin: 0 auto;
		text-align: center;
		width: 770px;
	}	
		.giftcard img{
			height: 340px;
			width: 770px;
		}
		.value{
			color:#da0009;
			font-size: 150px;
			position: absolute;
			z-index: 10;
			letter-spacing: -10px;
			margin-left: 310px;
			margin-top: 60px;
			text-align: center;
			width: 220px;
		}
		.dollar{
			color:#da0009;
			font-size: 50px;
			font-weight: bold;
			position: absolute;
			z-index: 11;
			margin-left: 300px;
			margin-top: 135px;
			text-align: left;
			width: 220px;
		}
		.code{
			margin-left: 560px;
			margin-top: 105px;
			color:#d50000;
			font-family: 'InconsolataMedium', 'Courier New', Courier, monospace;
			font-size: 45px;
			position: absolute;
			width: 200px;
		}
		.place{
			color:#3f4c51;
			font-family: 'ArmataRegular', sans-serif;
			font-size: 28px;
			position: absolute;
			z-index: 10;
			margin-left: 310px;
			margin-top: 250px;
			text-align: center;
			width: 220px;
		}
			.page-break{
				page-break-after:always;
			}
@font-face {
		font-family: 'InconsolataMedium';
		src: url('/assets/fonts/Inconsolata-webfont.eot');
		src: url('/assets/fonts/Inconsolata-webfont.eot?#iefix') format('embedded-opentype'),
				 url('/assets/fonts/Inconsolata-webfont.woff') format('woff'),
				 url('/assets/fonts/Inconsolata-webfont.ttf') format('truetype'),
				 url('/assets/fonts/Inconsolata-webfont.svg#InconsolataMedium') format('svg');
		font-weight: normal;
		font-style: normal;
}
@font-face {
		font-family: 'ArmataRegular';
		src: url('/assets/fonts/Armata-Regular-webfont.eot');
		src: url('/assets/fonts/Armata-Regular-webfont.eot?#iefix') format('embedded-opentype'),
				 url('/assets/fonts/Armata-Regular-webfont.woff') format('woff'),
				 url('/assets/fonts/Armata-Regular-webfont.ttf') format('truetype'),
				 url('/assets/fonts/Armata-Regular-webfont.svg#ArmataRegular') format('svg');
		font-weight: normal;
		font-style: normal;

}
</style>
<?php 
$count = 0;
$giftcards = $this->giftcards;
if( $giftcards->count() > 0 ) {
	foreach( $giftcards as $giftcard ){
		$count++;
		if( $giftcard->id_restaurant ){
			$restaurant = $giftcard->restaurant();
			$restaurant_name = $restaurant->name;			
		} else {
			$restaurant_name = 'Crunchbutton';
			$local_description = 'Order the top local food.';
		}
	?>
	<div class="giftcard">
		<div class="dollar">$</div>
		<div class="value"><?php echo $giftcard->value;?></div>
		<div class="code"><?php echo $giftcard->code;?></div>
		<div class="place"><?php echo $restaurant_name; ?></div>
		<img src="/assets/images/giftcard_print.png"/>
	</div>
	<?php 
		if( $count % 3 == 0 ){
			?>
			<div class="page-break"></div>
			<?php
		}
	?>
	<?php } 
} ?>