<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,300,700" rel="stylesheet" type="text/css">
<style type="text/css">
	.dotted{
		border: 1px dotted #CCC;
		padding: 5px;
		width: 776px;
		margin: 20px auto;
	}
	.giftcard{
		font-family: 'Open Sans', 'Droid Sans', Helvetica, Arial, sans-serif;
		border: 2px solid #800000;
		height: 330px;
		margin: 0 auto;
		text-align: center;
		width: 770px;
	}
	.title{
		background: #800000;
		color:#FFF;
		font-size: 35px;
		padding: 15px;
	}
	.headline, .headline-link{
		font-weight: bold;
		margin: 15px;
	}
		.restaurant{
			font-style: italic;
			text-decoration: underline;
		}
		.headline-link{
			font-weight: normal;
		}
			.link{
				color:blue;
				text-decoration: underline;
			}
		.crunchbutton{
			margin-top: 15px;
			font-size: 14px;
		}
			.subtitle{
				font-size: 16px;
				margin: 5px;
			}
				.icon img{
					border: 1px solid #ae1500;
					border-radius: 2px;
					box-shadow: 0px 2px 5px 0px rgba(0, 0, 0, 0.72);
					width: 60px;
					margin: 10px;
				}
			.slogan{
				font-style: italic;
			}
			.page-break{
				page-break-after:always;
			}
</style>
<?php 
$count = 0;
$giftcards = $this->giftcards;

$env = c::env() == 'live' ? 'live' : 'dev';

if( $env == 'live' ){
	$serverUrl = 'crunchbutton.com';
} else {
	$serverUrl = 'beta.crunchbutton.com';
}
if( $giftcards->count() > 0 ) {
	foreach( $giftcards as $giftcard ){
		$count++;
		if( $giftcard->id_restaurant ){
			$restaurant = $giftcard->restaurant();
			$restaurant_name = $restaurant->name;

			$community = $restaurant->communities();
			if( $community->count() > 0 ){
				$community_name = $community->name;
				$community_prep = $community->prep;
				if( $community_name && $community_prep ){
					$local_description = 'Order the top food ' . $community_prep . ' ' . $community_name . '.';	
				} else {
					$local_description = 'Order the top local food.';	
				}
			} else {
				$local_description = 'Order the top local food.';	
			}
			
		} else {
			$restaurant_name = 'Crunchbutton';
			$local_description = 'Order the top local food.';
		}
	?>
	<div class="dotted">
		<div class="giftcard">
			<div class="title">Order Food, Get $<?php echo $giftcard->value;?></div>
			<div class="headline">Place any delivery or takeout order at <span class="restaurant"> <?php echo $restaurant_name; ?> </span> and receive $<?php echo $giftcard->value;?> off</div>
			<div class="headline-link">Go to <a href="http://<?php echo $serverUrl; ?>/giftcard/<?php echo $giftcard->code;?>"><span class="link">http://<?php echo $serverUrl; ?>/giftcard/<?php echo $giftcard->code;?></span></a> to redeem</div>
			<div class="crunchbutton">
				<div class="icon">
					<img src="/assets/images/facebook-like.png" />
				</div>
				<div class="subtitle">PUSH A BUTTON. GET FOOD.</div>
				<div class="slogan">
					<?php echo $local_description; ?> For free.
					<br/>
					After you order, everything is saved for future 1 click ordering.
				</div>
			</div>
		</div>
	</div>
	<?php 
		if( $count % 3 == 0 ){
			?>
			<div class="page-break"></div>
			<?php
		}
	?>
	<?php } 
} ?>