<center>


<img src="/assets/images/landing-logo.png" class="logo">
<br />
<img src="/assets/images/landing-tagline.png" class="tagline">
<br />
<p class="desc">We find the best-loved restaurants in your neighborhood. Then we make it easy to order the dishes you love most. Both you and your local restaurant owners end up happy.</p>
<img src="/assets/images/landing-cake.png" class="cake">

<br /><br />
<div class="dotted"></div>

<br /><br />
<a href="/yale">Yale area? Go this way&nbsp;&gt;</a>
<br /><br />
<a href="/brown">Brown area? Try this way&nbsp;&gt;</a>
</center>