<center>


<img src="/assets/images/landing-logo.png" class="logo">
<br />
<img src="/assets/images/landing-tagline.png" class="tagline">
<br />
<p class="desc">We choose the best food that local customers love. We make restaurants cemented as a local favorites, drive additional business, and make both restaurants and customers happy.</p>
<img src="/assets/images/landing-cake.png" class="cake">

<br /><br />
<div class="dotted"></div>

<br /><br />
<a href="http://crunchr.co/yale">Sample our Yale App&nbsp;&gt;</a>
</center>