<div class="top-pad"></div>

<div class="content-padding">
	<div class="page-title-wrap">
		<h1 class="title"><i class="fa fa-coffee"></i>Restaurants</h1>
		<div class="page-title-nav">
			<button ng-click="addRestaurant()" class="button button-green nav-button-green"><i class="fa fa-plus"></i></button>
		</div>
	</div>
	<div class="divider"></div>

	<div class="box-content2 box-content-table">
		<table>
			<tr>
				<td colspan="4" width="100%">
					<i class="fa fa-search"></i>&nbsp;&nbsp;<input type="text" ng-model="query.search" id="search" tabindex="1">
				</td>
				<td>
					<i title="More options" class="fa fa-search-plus link no-underline" ng-class="{'orange':show_more_options}" ng-click="moreOptions()">
				<td>
			</tr>
			<tr ng-if="show_more_options">
				<th>Community</th>
				<td>
					<ui-select ng-model="query.community" theme="select2" close-on-select="true" style="width: 300px;" title="Select a community">
						<ui-select-match placeholder="Select a community">{{$select.selected.name}}</ui-select-match>
						<ui-select-choices repeat="community.id_community as community in communities | propsFilter: {name: $select.search}">
							{{community.name}}
						</ui-select-choices>
					</ui-select>
					<a ng-show="query.community" ng-click="query.community=null" href=""><button class="button button-small button-empty button-green"><i class="fa fa-trash-o"></i></button></a>
				</td>
				<th>Payment method</th>
				<td>
					<ui-select ng-model="query.payment_method" theme="select2" close-on-select="true" style="width: 300px;" title="Select a payment method">
						<ui-select-match placeholder="Select a payment method">{{$select.selected.label}}</ui-select-match>
							<ui-select-choices repeat="payment.value as payment in payments | propsFilter: {label: $select.search}">
								{{payment.label}}
							</ui-select-choices>
					</ui-select>
					<a ng-show="query.payment_method" ng-click="query.payment_method=null" href=""><button class="button button-small button-empty button-green"><i class="fa fa-trash-o"></i></button></a>
				</td>
				<td></td>
			</tr>
		</table>
	</div>

	<div class="bar-loader bar-loader-search" ng-class="{'bar-loader-loading': loading}"></div>

	<ng-include src="'assets/view/listview-restaurants.html'"></ng-include>
	<ng-include src="'assets/view/listview-paging.html'"></ng-include>
</div>
