<div class="top-pad"></div>

<div class="content-padding" ng-show="ready">

	<h1 class="title" ng-show="order.id_order"><i class="fa fa-credit-card"></i><span>Order #{{order.id_order}}</span></h1>

	<h1 class="title" ng-show="error">
		Invalid order!
	</h1>

	<p class="order-message">
		The customer's card was successfully charged, and the driver has been notified of the order.
	</p>

	<div class="content" ng-show="order.id_order">
		<div class="box-content2">
			<div class="order-group">
				<div class="order-label">Name</div>
				<div class="order-data">{{order.name}}</div>
			</div>
			<div class="order-group">
				<div class="order-label">Phone</div>
				<div class="order-data">{{order.phone}}</div>
			</div>
			<div class="order-group">
				<div class="order-label">Address</div>
				<div class="order-data">{{order.address}}</div>
			</div>
			<div class="order-group" ng-show="order.notes">
				<div class="order-label">Notes</div>
				<div class="order-data">{{order.notes}}</div>
			</div>
			<div class="order-group" ng-show="order.card_ending">
				<div class="order-label">Card</div>
				<div class="order-data">XXXX-XXXX-XXXX-{{order.card_ending}}</div>
			</div>
		</div>
	</div>
	<div class="prices">
		<div class="box-price price">
			<div class="title">
				<span class="dollar">$</span> {{order.price | formatPrice}}
			</div>
			<div class="description">
				Price
			</div>
		</div>
		<div class="box-price total-price">
			<div class="title">
				<span class="dollar">$</span> {{order.final_price_plus_delivery_markup | formatPrice}}
			</div>
			<div class="description">
				Total Price
			</div>
		</div>
		<div class="divider"></div>
	</div>
	<a class="order-print" ng-href="/printorder/{{order.id}}" target="_blank"><i class="fa fa-print"></i> Print Receipt</a>
</div>

<spinner-loading></spinner-loading>
<hack-expand-content></hack-expand-content>