<div ng-controller="RestaurantEditHoursCtrl" class="tab-content">

	<form name="form" novalidate ng-show="!loading">

		<div class="support-boxes">

			<div class="support-box-wrap box-content2">
				<div class="support-box-wrap-header">
					<h1>Hours</h1>
					<div class="divider"></div>
				</div>

				<div class="no-box-content-color">

					<ul ng-class="{'submitted':submitted}" class="ul-inputs">

						<li class="li-input">
							<div class="label">Monday:</div>
							<div class="input"><input type="text" name="hoursMonday" ng-model="restaurant.hours.mon"></div>
						</li>
						<li class="li-input">
							<div class="label">Tuesday:</div>
							<div class="input"><input type="text" name="hoursTuesday" ng-model="restaurant.hours.tue"></div>
						</li>
						<li class="li-input">
							<div class="label">Wednesday:</div>
							<div class="input"><input type="text" name="hoursWednesday" ng-model="restaurant.hours.wed"></div>
						</li>
						<li class="li-input">
							<div class="label">Thursday:</div>
							<div class="input"><input type="text" name="hoursThursday" ng-model="restaurant.hours.thu"></div>
						</li>
						<li class="li-input">
							<div class="label">Friday:</div>
							<div class="input"><input type="text" name="hoursFriday" ng-model="restaurant.hours.fri"></div>
						</li>
						<li class="li-input">
							<div class="label">Saturday:</div>
							<div class="input"><input type="text" name="hoursSaturday" ng-model="restaurant.hours.sat"></div>
						</li>
						<li class="li-input">
							<div class="label">Sunday:</div>
							<div class="input"><input type="text" name="hoursSunday" ng-model="restaurant.hours.sun"></div>
						</li>


					</ul>

				</div>
				<div class="no-box-content-color">
					<ul ng-class="{'submitted':submitted}" class="ul-inputs">
						<li class="li-input">
							<div class="notes">
										e.g. “12 PM - 2:30 AM”
								<br>
								Use a comma for multiple time segments. e.g. “11 am - 1:30 PM, 2:15 PM - 1 AM”
								<br>
								If Crunchbutton drivers do the delivery, hours are the intersection of the restaurants hours and Crunchbutton delivery hours.
								<br>
								Don’t forget to include a buffer for closing, if appropriate.
							</div>
						</li>
					</ul>
				</div>
			</div>

		</div>

	</form>

	<div class="support-box-wrap box-content2">
		<div class="no-box-content-color">
			<ul class="ul-inputs">
				<li class="li-input" ng-show="!isSaving">
					<button class="button save" ng-click="save();">Save</button>
				</li>
				<li class="li-input" ng-show="isSaving">
					<i class="fa fa-circle-o-notch fa-spin"></i>
				</li>
			</ul>
		</div>
	</div>
</div>
