<div class="top-pad"></div>

<div class="content-padding" ng-show="ready">

	<form name="form" ng-show="restaurants">

		<ul class="ul-inputs box-content">
			<li class="li-input">
				<div class="label">Select a restaurant:</div>
				<div class="input">
					<select name="restaurantSelect" ng-model="id_restaurant" ng-change="load_restaurant()" ng-options="opt.id_restaurant as opt.name for opt in restaurants"></select>
				</div>
			</li>
		</ul>
	</form>

	<div class="dashboard-box pending">
		<div class="dashboard-count">
			{{status.accepted_orders}}
		</div>
		<div class="dashboard-content">
			<div class="title">
				order<span ng-if="status.accepted_orders > 1">s</span> pending
			</div>
			<div class="description">
				order<span ng-if="status.accepted_orders > 1">s</span> waiting to be picked up
			</div>
		</div>
		<div class="divider"></div>
	</div>

	<div class="dashboard-box transit">
		<div class="dashboard-count">
			{{status.pickedup_orders}}
		</div>
		<div class="dashboard-content">
			<div class="title">
				order<span ng-if="status.pickedup_orders > 1">s</span> in transit
			</div>
			<div class="description">
				order<span ng-if="status.pickedup_orders > 1">s</span> waiting to be picked up
			</div>
		</div>
		<div class="divider"></div>
	</div>

	<div class="dashboard-box place-order" ng-click="new()">
		<div>Place a new order</div>
	</div>

	<a class="dashboard-box call-support"  ng-href="tel:{{status.phone}}">
		<span>Call Crunchbutton Support</span>
	</a>

	<div class="dashboard-box phone">
		{{status.phone_formatted}}
	</div>

</div>

<spinner-loading></spinner-loading>
<hack-expand-content></hack-expand-content>