<div class="top-pad"></div>

<div class="content-padding">
	<h1 class="title"><i class="fa fa-coffee"></i>Restaurants</h1>

	<div class="box-content2 box-content-table">
		<table>
			<tr>
				<td><i class="fa fa-search"></i>&nbsp;&nbsp;<input type="text" ng-model="query.search" id="search" tabindex="1"></td>
			</tr>
		</table>
	</div>
	
	<div class="bar-loader bar-loader-search" ng-class="{'bar-loader-loading': loading}"></div>

	<ng-include src="'assets/view/listview-restaurants.html'"></ng-include>
	<ng-include src="'assets/view/listview-paging.html'"></ng-include>
</div>
