<div class="top-pad"></div>

<div class="content-padding">

	<h1 class="title"><i class="fa fa-coffee"></i>Restaurant</h1>

	<div class="support-boxes" ng-if="!loading">

		<div class="support-box-wrap box-content2">
			<br>
			<div class="no-box-content-color customer-content-box">
				<div class="restaurant-image-button-wrap">
					<div class="restaurant-image-upload-button" restaurant-image-upload id_restaurant="{{restaurant.id_restaurant}}">
						<button class="ladda-button ladda-button-nohover button button-empty button-small button-green" data-color="" data-style="zoom-in"><span class="ladda-label"><i class="fa fa-image"></i>&nbsp;&nbsp;Upload Image</span></button>
						<input ng-if="init" type="file" nv-file-select="" uploader="uploader" name="file" class="file file-hidden">
					</div>
				</div>

				<a href="{{restaurant.image.original}}" target="_blank">
					<div class="customer-image-crop customer-image-crop-large customer-image-updater restaurant-image-updater">
						<img ng-if="restaurant.image" class="customer-image-large" hasImage="{{ restaurant.image.thumb != '' }}" src="{{restaurant.image.thumb}}" id="restaurant-image-thumb"></img>
						<div ng-if="!restaurant.image" class="customer-image-large restaurant-image-null"></div>
					</div>
				</a>

				<h1 class="customer-name-large">{{restaurant.name}}</h1>
			</div>
		</div>

		<div class="support-box-wrap box-content2">
			<div class="support-box-wrap-header">
				<h1>{{restaurant.name}}</h1>
				<div class="divider"></div>
			</div>

			<div class="no-box-content-color">
				<div class="field-container">
					<div class="field-row">
						<div class="field-key">
							<a href="https://crunchbutton.com/food-delivery/{{restaurant.permalink}}" target="_blank">View on Live</a>
						</div>
					</div>
					<div class="field-row">
						<div class="field-key">
							<a href="http://live.ci.crunchbutton.crunchr.co/{{restaurant.permalink}}" target="_blank">View on Staging</a>
						</div>
					</div>
					<div class="field-row">
						<div class="field-key">
							<strong>Important:</strong> Each tab must to be save individually.
							<br> Make sure you've saved all changes before upload an image.
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="divider"></div>
	<div class="bar-loader bar-loader-search bar-loader-boxes-top" ng-class="{'bar-loader-loading': loading}"></div>

	<br>
	<div ng-if="!loading">
		<ui-tabs>
			<ui-tab title="Basic Information" default="true" icon="info" id="editBasic" path="assets/view/restaurants-edit-basic.html"></ui-tab>
			<ui-tab title="Delivery / Logistics" icon="truck" id="editDelivery" path="assets/view/restaurants-edit-delivery.html"></ui-tab>
			<ui-tab title="Hours" icon="clock-o" id="editHours" path="assets/view/restaurants-edit-hours.html"></ui-tab>
			<ui-tab title="Notes" icon="file" id="editNotes" path="assets/view/restaurants-edit-notes.html"></ui-tab>
			<ui-tab title="Notifications" icon="bell" id="editNotifications" path="assets/view/restaurants-edit-notifications.html"></ui-tab>
			<ui-tab title="Menu" icon="coffee" id="editMenu" path="assets/view/restaurants-edit-menu.html"></ui-tab>
		</ui-tabs>
	</div>

</div>

