<link rel="stylesheet" type="text/css" href="/assets/cockpit/scss/cockpit.scss?v=<?=Cana_Util::gitVersion()?>">
<link rel="stylesheet" type="text/css" href="/assets/cockpit/css/ladda.min.css?v=<?=Cana_Util::gitVersion()?>">
<link rel="stylesheet" type="text/css" href="/assets/css/magnific-popup.css?v=<?=Cana_Util::gitVersion()?>">

<? if ($this->export && $this->isIOS) : ?>
	<link rel="stylesheet" type="text/css" href="/assets/cockpit/css/phonegap.ios.css?v=<?=Cana_Util::gitVersion()?>">
<? endif ; ?>
<? /*
<link rel="stylesheet" type="text/css" href="/assets/cockpit/css/bootstrap.css?v=<?=Cana_Util::gitVersion()?>">
<link rel="stylesheet" type="text/css" href="/assets/cockpit/css/dashio.css?v=<?=Cana_Util::gitVersion()?>">
<link rel="stylesheet" type="text/css" href="/assets/cockpit/css/dashio.responsive.css?v=<?=Cana_Util::gitVersion()?>">
*/?>