<link rel="stylesheet" type="text/css" href="/assets/cockpit/scss/cockpit.scss?v=<?=getenv('HEROKU_SLUG_COMMIT')?>">
<link rel="stylesheet" type="text/css" href="/assets/cockpit/css/ladda.min.css?v=<?=getenv('HEROKU_SLUG_COMMIT')?>">
<link rel="stylesheet" type="text/css" href="/assets/css/magnific-popup.css?v=<?=getenv('HEROKU_SLUG_COMMIT')?>">
<link rel="stylesheet" type="text/css" href="/assets/cockpit/css/angular-chart.css?v=<?=getenv('HEROKU_SLUG_COMMIT')?>">
<link rel="stylesheet" type="text/css" href="/assets/cockpit/scss/select.scss?v=<?=getenv('HEROKU_SLUG_COMMIT')?>">
