<link rel="stylesheet" type="text/css" href="/assets/cockpit/scss/cockpit.scss?v=<?=$_ENV['HEROKU_SLUG_COMMIT']?>">
<link rel="stylesheet" type="text/css" href="/assets/cockpit/css/ladda.min.css?v=<?=$_ENV['HEROKU_SLUG_COMMIT']?>">
<link rel="stylesheet" type="text/css" href="/assets/css/magnific-popup.css?v=<?=$_ENV['HEROKU_SLUG_COMMIT']?>">
<link rel="stylesheet" type="text/css" href="/assets/cockpit/css/angular-chart.css?v=<?=$_ENV['HEROKU_SLUG_COMMIT']?>">
<link rel="stylesheet" type="text/css" href="/assets/cockpit/scss/select.scss?v=<?=$_ENV['HEROKU_SLUG_COMMIT']?>">
