<script src="/assets/js/snap.js"></script>
<script src="/assets/js/date.js"></script>
<script src="/assets/js/jquery.totalstorage.js"></script>
<script src="/assets/js/jquery.cookie.js"></script>
<script src="/assets/js/jquery.browser.mobile.js"></script>
<script src="/assets/js/jquery.magnific-popup.js"></script>
<script src="/assets/js/jquery.easing.js"></script>
<script src="/assets/js/jquery.scrollspy.js"></script>
<script src="/assets/js/fastclick.js"></script>
<script src="/assets/js/spin.js"></script>
<script src="/assets/js/ladda.js"></script>
<script src="/assets/js/jquery.autosize-min.js"></script>
<script src="/assets/js/howler-min.js"></script>
<? /* @sky-loader <script src="/assets/js/sky-loader_edgePreload.js"></script> */ ?>

<?
	if (!$scripts) {
		$scripts = ['cockpit'];
	}

?>
<? foreach ($scripts as $script) : ?>
	<script src="/assets/cockpit/js/<?=$script?>.js?v=<?=Cana_Util::gitVersion()?>"></script>
<? endforeach ; ?>

<script src="/assets/js/base.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/js/util.js?v=<?=Cana_Util::gitVersion()?>"></script>

<!-- AngularJS Controllers -->
<script src="/assets/cockpit/js/controllers.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/cockpit/js/controllers.drivers.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/cockpit/js/controllers.settlement.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/cockpit/js/controllers.restaurants.js?v=<?=Cana_Util::gitVersion()?>"></script>

<!-- AngularJS Filters -->
<script src="/assets/js/filters.js?v=<?=Cana_Util::gitVersion()?>"></script>

<!-- AngularJS Directives -->
<script src="/assets/js/directives.js?v=<?=Cana_Util::gitVersion()?>"></script>

<script src="/assets/cockpit/js/angular-file-upload.js?v=<?=Cana_Util::gitVersion()?>"></script>

<!-- AngularJS Services -->
<script src="/assets/cockpit/js/service.navigation.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/cockpit/js/service.account.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/cockpit/js/service.driverorders.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/cockpit/js/service.settlement.js?v=<?=Cana_Util::gitVersion()?>"></script>

<script src="/assets/cockpit/js/service.preonboarding.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/cockpit/js/service.driveronboarding.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/cockpit/js/service.drivershifts.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/cockpit/js/service.community.js?v=<?=Cana_Util::gitVersion()?>"></script>
<script src="/assets/cockpit/js/service.location.js?v=<?=Cana_Util::gitVersion()?>"></script>
