<?
	$angular = '1.4.6';
?>

<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

<script src="//ajax.googleapis.com/ajax/libs/angularjs/<?=$angular?>/angular.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/<?=$angular?>/angular-route.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/<?=$angular?>/angular-sanitize.js"></script>
<? /*
	// there is current an issue with the 1.3.x branch of angular and request canceling
	// https://github.com/angular/angular.js/issues/9332
	// https://github.com/crunchbutton/crunchbutton/issues/5603
	<script src="//ajax.googleapis.com/ajax/libs/angularjs/<?=$angular?>/angular-resource.min.js"></script>
*/ ?>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/<?=$angular?>/angular-animate.min.js"></script>

<script src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.5/socket.io.min.js"></script>

<script src="/assets/cockpit/js/moment.min.js"></script>
<script src="/assets/cockpit/js/moment-timezone.min.js"></script>
<script src="/assets/cockpit/js/angular-moment.min.js"></script>
<script src="/assets/cockpit/js/socket.min.js"></script>
<script src="/assets/cockpit/js/angular-hotkeys.min.js"></script>
<script src="/assets/cockpit/js/angular-google-maps.min.js"></script>
<script src="/assets/cockpit/js/favico.min.js"></script>
<script src="/assets/cockpit/js/Chart.js"></script>
<script src="/assets/cockpit/js/angular-chart.js"></script>
<script src="/assets/cockpit/js/angular-resource.js"></script>
<script src="/assets/cockpit/js/angular-bindonce.js"></script>
<script src="/assets/cockpit/js/mousetrap.min.js"></script>
<script src="/assets/cockpit/js/signature/jSignature.min.js"></script>

<?/*
<script src="/assets/cockpit/js/hammer.min.js"></script>
<script src="/assets/cockpit/js/angular-gestures.min.js"></script>
*/?>

<script src="/assets/js/snap.js"></script>
<script src="/assets/js/date.js"></script>
<script src="/assets/js/jquery.totalstorage.js"></script>
<script src="/assets/js/jquery.cookie.js"></script>
<script src="/assets/js/jquery.browser.mobile.js"></script>
<script src="/assets/js/jquery.magnific-popup.js"></script>
<script src="/assets/js/jquery.easing.js"></script>
<script src="/assets/js/jquery.scrollspy.js"></script>
<script src="/assets/js/fastclick.js"></script>
<script src="/assets/js/spin.js"></script>
<script src="/assets/js/ladda.js"></script>
<script src="/assets/js/jquery.autosize-min.js"></script>
<script src="/assets/js/location.js"></script>
<script src="/assets/js/howler-min.js"></script>

<script src="/assets/cockpit/js/cockpit.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>


<script src="/assets/js/base.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/js/util.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/js/tokenizeCard.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>

<!-- AngularJS Controllers -->
<script src="/assets/cockpit/js/controllers.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/controllers.quote.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/controllers.resource.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/controllers.drivers.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/controllers.staff.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/controllers.settlement.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/controllers.restaurant.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/controllers.customer.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/controllers.maps.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/controllers.support.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/controllers.ticket.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/controllers.call.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/controllers.deploy.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/controllers.order.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/controllers.config.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/controllers.community.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/controllers.pexcard.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/controllers.tools.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/controllers.marketing.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/controllers.blast.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/controllers.tv.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/controllers.report.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/controllers.metrics.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/controllers.promo.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/controllers.dashboard.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/controllers.credit.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/controllers.suggestion.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/controllers.permission.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/controllers.group.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/controllers.dispute.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/controllers.blocked.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/controllers.deliverysignup.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/controllers.shift.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/controllers.update.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/controllers.chain.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/controllers.marketingmaterials.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<!-- AngularJS Filters -->
<script src="/assets/js/filters.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>

<!-- AngularJS Directives -->
<script src="/assets/js/directives.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/directives.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/select.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>

<script src="/assets/cockpit/js/angular-file-upload.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>

<!-- AngularJS Services -->
<script src="/assets/cockpit/js/service.navigation.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.account.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.driverorders.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.settlement.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.driver.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.config.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>

<script src="/assets/cockpit/js/service.preonboarding.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.driveronboarding.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.drivershifts.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.staff.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.community.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.restaurant.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.location.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.customer.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.support.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.ticket.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.call.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.heartbeat.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.push.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.notification.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.deploy.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.call.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.datetime.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.socket.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.order.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.view.list.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.tabs.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.maps.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.pexcard.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.marketing.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.favico.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.blast.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.tv.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.report.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/angular-cached-resource.min.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.feedback.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.metrics.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.quote.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.resource.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.promo.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.giftcard.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.dashboard.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.credit.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.suggestion.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.permission.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.group.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.csv.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.twilio.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.dispute.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.blocked.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.profile.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.deliverysignup.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.shift.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.drivercommunity.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.appavailability.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.chain.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.marketingmaterials.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.customerserviceconfig.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script src="/assets/cockpit/js/service.fax.js?v=<?=getenv('HEROKU_SLUG_COMMIT')?>"></script>
<script type="text/javascript">
	var _current_bundle = '<?=getenv('HEROKU_SLUG_COMMIT')?>';
</script>
