<div class="top-pad"></div>

<div class="content-padding" ng-show="ready">

	<h1 class="title left"><i class="fa fa-slideshare"></i><span>Community</span></h1>

	<div class="divider"></div>

	<navigation-back></navigation-back>

	<h2 class="title">
		<span ng-if="!community.id_community">Add community</span>
		<span ng-if="community.id_community">Edit community</span>
	</h2>

	<form name="form" novalidate>

		<ul ng-class="{'submitted':submitted}" class="ul-inputs">

			<li class="li-input" ng-class="{'error':form.communityName.$invalid}">
				<div class="label">Name:</div>
				<div class="input"><input type="text" name="communityName" ng-model="community.name" required placeholder="Name" ng-minlength="2" ng-maxlength="255" ></div>
				<div class="box-error">
					<small ng-show="form.communityName.$error.required">Required.</small>
					<small ng-show="form.communityName.$error.minlength">Name is too short. Name is required to be at least 2 characters.</small>
					<small ng-show="form.communityName.$error.maxlength">Name cannot be longer than 255 characters.</small>
				</div>
			</li>

			<li class="li-input" ng-class="{'error':form.communityPermalink.$invalid}">
				<div class="label">Permalink:</div>
				<div class="input"><input type="text" name="communityPermalink" ng-model="community.permalink" required placeholder="Permalink" ng-minlength="2" ng-maxlength="255" ></div>
				<div class="box-error">
					<small ng-show="form.communityPermalink.$error.required">Required.</small>
					<small ng-show="form.communityPermalink.$error.minlength">Permalink is too short. Permalink is required to be at least 2 characters.</small>
					<small ng-show="form.communityPermalink.$error.maxlength">Permalink cannot be longer than 40 characters.</small>
				</div>
			</li>

			<li class="li-input" ng-class="{'error':form.communityPrep.$invalid}">
				<div class="label">Preposition:</div>
				<div class="input"><input type="text" name="communityPrep" ng-model="community.prep" required placeholder="Prep"></div>
				<div class="box-error">
					<small ng-show="form.communityPrep.$error.required">Required.</small>
				</div>
			</li>

			<li class="li-input" ng-class="{'error':form.communityAlternativeName.$invalid}">
				<div class="label">Alternative name:</div>
				<div class="input"><input type="text" name="communityAlternativeName" ng-model="community.name_alt" required placeholder="Alternative name"></div>
				<div class="box-error">
					<small ng-show="form.communityAlternativeName.$error.required">Required.</small>
				</div>
			</li>

			<li class="li-input" ng-class="{'error':form.communityActive.$invalid}">
				<div class="label">Active:</div>
				<div class="input">
					<select name="communityActive" required ng-model="community.active" ng-options="opt.value as opt.label for opt in yesNo" ></select>
				</div>
			</li>

			<li class="li-input" ng-class="{'error':form.communityPrivate.$invalid}">
				<div class="label">Private:</div>
				<div class="input">
					<select name="communityPrivate" required ng-model="community.private" ng-options="opt.value as opt.label for opt in yesNo" ></select>
				</div>
			</li>

			<li class="li-input" ng-class="{'error':form.communityImage.$invalid}">
				<div class="label">Custom image:</div>
				<div class="input">
					<select name="communityImage" required ng-model="community.image" ng-options="opt.value as opt.label for opt in yesNo" ></select>
				</div>
			</li>

		</ul>

		<br/><br/><br/>

		<h2 class="title">Delivery info</h2>

		<ul ng-class="{'submitted':submitted}" class="ul-inputs">

			<li class="li-input" ng-class="{'error':form.communityDriverGroup.$invalid}">
				<div class="label">Driver group name:</div>
				<div class="input"><input type="text" name="communityDriverGroup" ng-model="community.driver_group" readonly="readonly"></div>
			</li>

			<li class="li-input" ng-class="{'error':form.communityTimezone.$invalid}">
				<div class="label">Timezone:</div>
				<div class="input">
				<select name="communityTimezone" required ng-model="community.timezone" ng-options="opt.value as opt.label for opt in timezones" ></select>

				</div>
			</li>

			<li class="li-input" ng-class="{'error':form.communityLocLat.$invalid}">
				<div class="label">Latitude:</div>
				<div class="input"><input type="text" name="communityLocLat" ng-model="community.loc_lat" required placeholder="Latitude"></div>
				<div class="box-error">
					<small ng-show="form.communityLocLat.$error.required">Required.</small>
				</div>
			</li>

			<li class="li-input" ng-class="{'error':form.communityLocLong.$invalid}">
				<div class="label">Longitude:</div>
				<div class="input"><input type="text" name="communityLocLong" ng-model="community.loc_lon" required placeholder="Longitude"></div>
				<div class="box-error">
					<small ng-show="form.communityLocLong.$error.required">Required.</small>
				</div>
			</li>

			<li class="li-input" ng-class="{'error':form.communityRange.$invalid}">
				<div class="label">Range:</div>
				<div class="input"><input type="text" name="communityRange" ng-model="community.range" required placeholder="Range"></div>
				<div class="box-error">
					<small ng-show="form.communityRange.$error.required">Required.</small>
				</div>
			</li>

		</ul>

		<br/><br/><br/>

		<h2 class="title">Close</h2>

		<ul ng-class="{'submitted':submitted}" class="ul-inputs">

			<li class="li-input" ng-class="{'error':form.communityCloseAllRestaurants.$invalid}">
				<div class="label">Close All Restaurants:</div>
				<div class="input">
					<select name="communityCloseAllRestaurants" required ng-model="community.close_all_restaurants" ng-options="opt.value as opt.label for opt in yesNo" ></select>
				</div>
			</li>

			<li class="li-input" ng-show="community.close_all_restaurants" ng-class="{'error':form.communityCloseAllRestaurantsNote.$invalid}">
				<div class="label">Close All Restaurants Note:</div>
				<div class="input"><input type="text" name="communityCloseAllRestaurantsNote" ng-model="community.close_all_restaurants_note" ng-required="community.close_all_restaurants"></div>
				<div class="box-error">
					<small ng-show="form.communityCloseAllRestaurantsNote.$error.required">Required.</small>
				</div>
			</li>

			<br/>

			<li class="li-input" ng-class="{'error':form.communityClose3rdPartyRestaurants.$invalid}">
				<div class="label">Close 3rd Party Delivery Restaurants:</div>
				<div class="input">
					<select name="communityClose3rdPartyRestaurants" required ng-model="community.close_3rd_party_delivery_restaurants" ng-options="opt.value as opt.label for opt in yesNo" ></select>
				</div>
			</li>

			<li class="li-input" ng-show="community.close_3rd_party_delivery_restaurants" ng-class="{'error':form.communityClose3rdPartyRestaurantsNote.$invalid}">
				<div class="label">Close 3rd Party Delivery Restaurants Note:</div>
				<div class="input"><input type="text" name="communityClose3rdPartyRestaurantsNote" ng-model="community.close_3rd_party_delivery_restaurants_note" ng-required="community.close_3rd_party_delivery_restaurants"></div>
				<div class="box-error">
					<small ng-show="form.communityClose3rdPartyRestaurantsNote.$error.required">Required.</small>
				</div>
			</li>

		</ul>

	</form>

	<ul class="ul-inputs">
		<li class="li-input" ng-show="!isSaving">
			<button class="button save" ng-click="save();">Save</button>
			<button class="button cancel" ng-click="cancel()">Cancel</button>
		</li>
		<li class="li-input" ng-show="isSaving">
			<i class="fa fa-circle-o-notch fa-spin"></i>
		</li>
	</ul>

</div>

<spinner-loading></spinner-loading>
<hack-expand-content></hack-expand-content>