<div class="page-title-wrap">
	<div class="page-title-nav">
		<a href ng-click="openCommunityNoteContainer()"><button class="button button-green nav-button-green"><i class="fa fa-file"></i><span>Add Note</span></button></a>
	</div>
</div>
<div class="bar-loader bar-loader-title" ng-class="{'bar-loader-loading': loadingNotes}"></div>
<ng-include src="'/assets/view/listview-communities-notes.html'"></ng-include>