<div class="top-pad"></div>

<div class="content-padding">


	<h1 class="left title"><i class="fa fa-slideshare"></i>{{community.name}}<div class="title-loader" ng-if="loading"><i class="fa fa-refresh fa-spin"></i></div></h1>

<? /*
	<div class="ticket-status-top">
		<div class="ticket-status-open">{{order.status.status}}</div>
	</div>
*/ ?>

	<div class="divider"></div>
	<br>
	
	<div ng-if="!loading">
		
		<div class="support-boxes">
			<div ng-if="community.id_community" class="support-box-wrap">
				<h1>Details</h1>
				<div class="box-content-color">
					<div class="field-container">
						<div class="field-row">
							<div class="field-key">Name</div>
							<div class="field-value">{{community.name}}</div>
						</div>
						<div class="field-row">
							<div class="field-key">Loc</div>
							<div class="field-value">{{community.la}}, {{community.lon}}</div>
						</div>
						<div class="field-row">
							<div class="field-key">Timezone</div>
							<div class="field-value">{{community.timezone}}</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		
		<h1 class="title"><i class="fa fa-coffee"></i>Restaurants<div class="title-loader" ng-if="loading"><i class="fa fa-refresh fa-spin"></i></div></h1>		
		<ng-include src="'assets/view/listview-restaurants.html'"></ng-include>

		<h1 class="title"><i class="fa fa-car"></i>Orders<div class="title-loader" ng-if="loading"><i class="fa fa-refresh fa-spin"></i></div></h1>		
		<ng-include src="'assets/view/listview-orders.html'"></ng-include>
	</div>
</div>