<div class="top-pad"></div>

<div class="content-padding">


	<h1 class="left title"><i class="fa fa-slideshare"></i>{{community.name}}<div class="title-loader" ng-if="loading"><i class="fa fa-refresh fa-spin"></i></div></h1>

	<div class="ticket-status-top" ng-if="community.id_community">
		<div class="ticket-status-open" ng-if="community.active">Active</div>
		<div class="ticket-status-closed" ng-if="!community.active">Inactive</div>
	</div>


	<div class="divider"></div>
	<div class="bar-loader bar-loader-search" ng-class="{'bar-loader-loading': loading}"></div>
	<br>

	<div>
		<div class="support-boxes-column">
			<div class="support-box-wrap">
				<h1>Details</h1>
				<div class="box-content-color">
					<div class="field-container">
						<div class="field-row">
							<div class="field-key">Name</div>
							<div class="field-value">{{community.name}}<span ng-if="community.name_alt && community.name_alt != community.name"> / {{community.name_alt}}</span></div>
						</div>
						<div class="field-row">
							<div class="field-key">Permalink</div>
							<div class="field-value">{{community.permalink}}</div>
						</div>
						<div class="field-row">
							<div class="field-key">Loc</div>
							<div class="field-value">{{community.loc_lat}}, {{community.loc_lon}}</div>
						</div>
						<div class="field-row">
							<div class="field-key">Timezone</div>
							<div class="field-value">{{community.timezone}}</div>
						</div>
						<div class="field-row">
							<div class="field-key">
								<a href="/community/edit/{{community.permalink}}">Edit</a>
							</div>
							<div class="field-value"></div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="support-boxes-column">
			<div class="support-box-wrap">
				<h1>Location</h1>
				<map zoom="12" center="false" class="maps-map" map-type-control="false" style="height: 230px;" options="{streetViewControl: false}">

				</map>
			</div>
		</div>
	</div>

	<div class="divider"></div>

	<br><br>
	<h1 class="title"><i class="fa fa-coffee"></i>Restaurants<div class="title-loader" ng-if="loadingRestaurants"><i class="fa fa-refresh fa-spin"></i></div></h1>
	<div class="bar-loader bar-loader-title" ng-class="{'bar-loader-loading': loadingRestaurants}"></div>
	<ng-include src="'assets/view/listview-restaurants.html'"></ng-include>


	<br><br>
	<h1 class="title"><i class="fa fa-car"></i>Orders</h1>
	<div class="bar-loader bar-loader-title" ng-class="{'bar-loader-loading': loadingOrders}"></div>
	<ng-include src="'assets/view/listview-orders.html'"></ng-include>


	<div class="right">
		<p><a href="/orders?community={{community.id_community}}">View all orders</a></p>
	</div>

	<br><br>
	<h1 class="title"><i class="fa fa-road"></i>Drivers</h1>
	<div class="bar-loader bar-loader-drivers" ng-class="{'bar-loader-loading': loadingStaff}"></div>
	<ng-include src="'assets/view/listview-staff.html'"></ng-include>

	<br><br>

	<h1 class="title"><i class="fa fa-link"></i>Aliases</h1>

	<div class="box-content2 box-content-table">
		<table class="tb-zebra">
			<tr>
				<th>Alias</th>
				<th>Preposition</th>
				<th>Alternative name</th>
			</tr>
			<tr ng-repeat="a in aliases">
				<td>{{a.alias}}</td>
				<td>{{a.prep}}</td>
				<td>{{a.name_alt}}</td>
			</tr>
		</table>
	</div>

	<br><br>
	<h1 class="title"><i class="fa fa fa-list"></i>Open/Close Log</h1>
	<div class="box-content2 box-content-table">
		<table class="tb-zebra">
			<tr>
				<th>Type</th>
				<th>Closed at</th>
				<th>Closed By</th>
				<th>Closed Notes</th>
				<th>How long</th>
				<th>Opened at</th>
				<th>Opened by</th>
			</tr>
			<tr ng-repeat="c in closelogs">
				<td>{{c.type}}</td>
				<td>{{c.closed_at}}</td>
				<td>{{c.closed_by}}</td>
				<td>{{c.note}}</td>
				<td>{{c.how_long}}</td>
				<td>{{c.opened_at}}</td>
				<td>{{c.opened_by}}</td>
			</tr>
		</table>
	</div>


</div>