<div class="bar-loader bar-loader-title" ng-class="{'bar-loader-loading': loadingLogs}"></div>
<div class="box-content2 box-content-table">
	<table class="tb-zebra">
		<tr>
			<th>Type</th>
			<th>Closed at</th>
			<th>Closed By</th>
			<th>Closed Notes / Reason</th>
			<th>How long</th>
			<th>Opened at</th>
			<th>Opened by</th>
		</tr>
		<tr ng-repeat="c in closelogs">
			<td><span class="listview-smaller">{{c.type}}</span></td>
			<td nowrap=""><span class="listview-smallest">
				{{c.closed_at_utc | localtime:'MMM/DD/YY hh:mm:ss (Z)'}}
				<br>
				{{c.closed_at}}
			</span></td>
			<td><span class="listview-smaller">{{c.closed_by}}</span></td>
			<td>
				<span class="listview-smaller" ng-bind-html="c.note"></span>
				<span ng-if="c.reason" class="listview-smaller"><br>{{c.reason}}</span>
			</td>
			<td><span class="listview-smaller">{{c.how_long}}</span></td>
			<td nowrap=""><span class="listview-smallest" ng-if="c.opened_at_utc">
				{{c.opened_at_utc | localtime:'MMM/DD/YY hh:mm:ss (Z)'}}
				<br>
				{{c.opened_at}}
			</span></td>
			<td><span class="listview-smaller">{{c.opened_by}}</span></td>
		</tr>
	</table>
</div>
