<div class="top-pad"></div>

<div class="content-padding" ng-show="ready">

	<h1 class="title left"><i class="fa fa-slideshare"></i><span>Community</span></h1>

	<div class="divider"></div>

	<navigation-back></navigation-back>

	<h2 class="title">
		<span ng-if="!community.id_community">Add community</span>
		<span ng-if="community.id_community">Edit community</span>
	</h2>

	<form name="form" novalidate>

		<ul ng-class="{'submitted':submitted}" class="ul-inputs">

			<li class="li-input" ng-class="{'error':form.communityName.$invalid}">
				<div class="label">Name:</div>
				<div class="input"><input type="text" name="communityName" ng-model="community.name" required placeholder="Name" ng-minlength="2" ng-maxlength="255" ></div>
				<div class="box-error">
					<small ng-show="form.communityName.$error.required">Required.</small>
					<small ng-show="form.communityName.$error.minlength">Name is too short. Name is required to be at least 2 characters.</small>
					<small ng-show="form.communityName.$error.maxlength">Name cannot be longer than 255 characters.</small>
				</div>
			</li>

			<li class="li-input" ng-class="{'error':form.communityPermalink.$invalid}">
				<div class="label">Permalink (must be lowercase):</div>
				<div class="input"><input type="text" name="communityPermalink" ng-model="community.permalink" required placeholder="Permalink" ng-minlength="2" ng-maxlength="255" ></div>
				<div class="box-error">
					<small ng-show="form.communityPermalink.$error.required">Required.</small>
					<small ng-show="form.communityPermalink.$error.minlength">Permalink is too short. Permalink is required to be at least 2 characters.</small>
					<small ng-show="form.communityPermalink.$error.maxlength">Permalink cannot be longer than 40 characters.</small>
				</div>
			</li>

			<li class="li-input" ng-class="{'error':form.communityActive.$invalid}">
				<div class="label">Active:</div>
				<div class="input">
					<select name="communityActive" required ng-model="community.active" ng-options="opt.value as opt.label for opt in yesNo" ></select>
				</div>
			</li>

			<li class="li-input" ng-class="{'error':form.communityAutoClose.$invalid}">
				<div class="label">Enable Auto Close:</div>
				<div class="input">
					<select name="communityAutoClose" required ng-model="community.auto_close" ng-options="opt.value as opt.label for opt in yesNo" ></select>
				</div>
			</li>

			<li class="li-input" ng-class="{'error':form.communityImage.$invalid}">
				<div class="label">Custom image:</div>
				<div class="input">
					<select name="communityImage" required ng-model="community.image" ng-options="opt.value as opt.label for opt in yesNo" ></select>
				</div>
			</li>

		</ul>

		<br/><br/><br/>

		<h2 class="title">Delivery info</h2>

		<ul ng-class="{'submitted':submitted}" class="ul-inputs">

			<li class="li-input" ng-class="{'error':form.communityDriverRestaurant.$invalid}">
				<div class="label">Driver restaurant:</div>
				<div class="input">
					<select name="communityDriverRestaurant" ng-model="community.id_driver_restaurant" ng-options="opt.id_restaurant as opt.name for opt in restaurants" ></select>
				</div>
			</li>

			<li class="li-input" ng-show="community.driver_group">
				<div class="label">Driver group name:</div>
				<div class="input">{{community.driver_group}}</div>
			</li>

			<li class="li-input" ng-class="{'error':form.communityTimezone.$invalid}">
				<div class="label">Timezone:</div>
				<div class="input">
				<select name="communityTimezone" required ng-model="community.timezone" ng-options="opt.value as opt.label for opt in timezones" ></select>

				</div>
			</li>

			<li class="li-input">
				<div class="label">Address:</div>
				<div class="input">
					<textarea ng-model="community.address"></textarea>
				</div>
			</li>

			<li class="li-input" ng-class="{'error':form.communityLocLat.$invalid}">
				<div class="label">Latitude (automagically calculated):</div>
				<div class="input"><input type="text" name="communityLocLat" ng-model="community.loc_lat" required placeholder="Latitude"></div>
				<div class="box-error">
					<small ng-show="form.communityLocLat.$error.required">Required.</small>
				</div>
			</li>

			<li class="li-input" ng-class="{'error':form.communityLocLong.$invalid}">
				<div class="label">Longitude (automagically calculated):</div>
				<div class="input"><input type="text" name="communityLocLong" ng-model="community.loc_lon" required placeholder="Longitude"></div>
				<div class="box-error">
					<small ng-show="form.communityLocLong.$error.required">Required.</small>
				</div>
			</li>

			<li class="li-input" ng-class="{'error':form.communityRange.$invalid}">
				<div class="label">Range:</div>
				<div class="input"><input type="text" name="communityRange" ng-model="community.range" required placeholder="Range"></div>
				<div class="box-error">
					<small ng-show="form.communityRange.$error.required">Required.</small>
				</div>
			</li>

		</ul>

		<br/><br/><br/>

		<h2 class="title">Close</h2>

		<ul ng-class="{'submitted':submitted}" class="ul-inputs">

			<li class="li-input" ng-class="{'error':form.communityAutoClose.$invalid}">
				<div class="label">Is current Auto Closed:</div>
				<div class="input">
					<span ng-show="community.is_auto_closed">
						<select name="communityIsAutoClose" ng-model="community.is_auto_closed" ng-options="opt.value as opt.label for opt in yesNo" ></select>
					</span>
					<span ng-show="!community.is_auto_closed">No</span>
				</div>
			</li>

			<li class="li-input" ng-class="{'error':form.communityCloseAllRestaurants.$invalid}">
				<div class="label">Close All Restaurants:</div>
				<div class="input">
					<select name="communityCloseAllRestaurants" required ng-model="community.close_all_restaurants" ng-options="opt.value as opt.label for opt in yesNo" ></select>
				</div>
			</li>

			<li class="li-input" ng-show="community.close_all_restaurants" ng-class="{'error':form.communityCloseAllRestaurantsNote.$invalid}">
				<div class="label">Close All Restaurants Note (follow this same format. e.g. - "Launching Mon 2/2 6PM-12AM"):</div>
				<div class="input"><input type="text" name="communityCloseAllRestaurantsNote" ng-model="community.close_all_restaurants_note" ng-required="community.close_all_restaurants"></div>
				<div class="box-error">
					<small ng-show="form.communityCloseAllRestaurantsNote.$error.required">Required.</small>
				</div>
			</li>

			<li class="li-input" ng-show="community.close_all_restaurants">
				<div class="label">
					<span ng-show="community.close_all_restaurants_admin">Closed by {{community.close_all_restaurants_admin}} </span>
					<span ng-show="community.close_all_restaurants_date">at {{community.close_all_restaurants_date}}.</span>
				</div>
			</li>

			<li class="li-input" ng-class="{'error':form.communityClose3rdPartyRestaurants.$invalid}">
				<div class="label">Close 3rd Party Delivery Restaurants:</div>
				<div class="input">
					<select name="communityClose3rdPartyRestaurants" required ng-model="community.close_3rd_party_delivery_restaurants" ng-options="opt.value as opt.label for opt in yesNo" ></select>
				</div>
			</li>

			<li class="li-input" ng-show="community.close_3rd_party_delivery_restaurants || community.is_auto_closed" ng-class="{'error':form.communityClose3rdPartyRestaurantsNote.$invalid}">
				<div class="label">Close 3rd Party Delivery Restaurants Note (follow this same format. e.g. - "Launching Mon 2/2 6PM-12AM"):</div>
				<div class="input"><input type="text" name="communityClose3rdPartyRestaurantsNote" ng-model="community.close_3rd_party_delivery_restaurants_note" ng-required="community.close_3rd_party_delivery_restaurants || community.is_auto_closed"></div>
				<div class="box-error">
					<small ng-show="form.communityClose3rdPartyRestaurantsNote.$error.required">Required.</small>
				</div>
			</li>

			<li class="li-input" ng-show="community.close_3rd_party_delivery_restaurants">
				<div class="label">
					<span ng-show="community.close_3rd_party_delivery_restaurants_admin">Closed by {{community.close_3rd_party_delivery_restaurants_admin}} </span>
					<span ng-show="community.close_3rd_party_delivery_restaurants_date">at {{community.close_3rd_party_delivery_restaurants_date}}.</span>
				</div>
			</li>

			<li class="li-input" ng-show="community.close_all_restaurants || community.close_3rd_party_delivery_restaurants"  ng-class="{'error': form.dontWarnTill.$invalid}">
				<div class="label">If it is closed and it has drivers doesn't warn CS till (PST):</div>
				<div class="input">
					<select name="dontWarnTillEnabled" ng-model="community.dont_warn_till_enabled" ng-options="opt.value as opt.label for opt in yesNo" ></select>
					<br>
				</div>
				<div class="input" ng-show="community.dont_warn_till_enabled">
					<input type="datetime-local" ng-disabled="!community.dont_warn_till_enabled" ng-required="community.dont_warn_till_enabled" name="dontWarnTill" ng-model="community.dont_warn_till" placeholder="">
				</div>
			</li>

		</ul>

	</form>

	<ul class="ul-inputs">
		<li class="li-input" ng-show="!isSaving">
			<button class="button save" ng-click="save();">Save</button>
			<button class="button cancel" ng-click="cancel()">Cancel</button>
		</li>
		<li class="li-input" ng-show="isSaving">
			<i class="fa fa-circle-o-notch fa-spin"></i>
		</li>
	</ul>

	<br><br><br>

	<div ng-show="alias.id_community">

		<h2 class="title left"><span>Aliases</span></h2>

		<div class="divider"></div>

		<form name="formAlias" novalidate>

			<div class="ul-inputs">

				<ul ng-class="{'submitted':formAliasSubmitted}" class="box-content2">

					<li class="li-input" ng-class="{'error':formAlias.aliasAlias.$invalid}">
						<div class="label">Alias:</div>
						<div class="input"><input type="text" name="aliasAlias" ng-model="alias.alias" required placeholder="Alias"></div>
						<div class="box-error">
							<small ng-show="formAlias.aliasAlias.$error.required">Required.</small>
						</div>
					</li>

					<li class="li-input" ng-class="{'error':formAlias.aliasNameAlt.$invalid}">
						<div class="label">Alternative name:</div>
						<div class="input"><input type="text" name="aliasNameAlt" ng-model="alias.name_alt" required placeholder="Alternative name"></div>
						<div class="box-error">
							<small ng-show="formAlias.aliasNameAlt.$error.required">Required.</small>
						</div>
					</li>

					<li class="li-input" ng-class="{'error':formAlias.aliasPrep.$invalid}">
						<div class="label">Preposition (at, in, etc. e.g. "the best delivery at Yale"):</div>
						<div class="input"><input type="text" name="aliasPrep" ng-model="alias.prep" required placeholder="Preposition"></div>
						<div class="box-error">
							<small ng-show="formAlias.aliasPrep.$error.required">Required.</small>
						</div>
					</li>

					<li class="li-input" ng-class="{'error':formAlias.aliasTop.$invalid}">
						<div class="label">Display Location after preposition on Community Error Page? (only do this for one alias per community, and only when community has launched):</div>
						<div class="input">
							<select name="aliasTop" ng-model="alias.top" ng-options="opt.value as opt.label for opt in yesNo" ></select>
						</div>
						<div class="box-error">
							<small ng-show="formAlias.aliasTop.$error.required">Required.</small>
						</div>
					</li>

					<li class="li-input" ng-class="{'error':formAlias.aliasSort.$invalid}" ng-show="alias.top">
						<div class="label">Sort:</div>
						<div class="input">
							<input type="number" ignore-mouse-wheel name="aliasSort" ng-model="alias.sort" ng-required="alias.top">
						</div>
						<div class="box-error">
							<small ng-show="formAlias.aliasSort.$error.required">Required.</small>
						</div>
					</li>

					<li class="li-input" ng-show="!isSavingAlias">
						<button class="button green" ng-click="add_alias();">Add</button>
					</li>
					<li class="li-input" ng-show="isSavingAlias">
						<i class="fa fa-circle-o-notch fa-spin"></i>
					</li>
				</ul>
				<div class="box-content2 box-content-table">
					<table class="tb-zebra">
						<tr>
							<th>Alias</th>
							<th>Preposition</th>
							<th>Alternative name</th>
							<th>Top</th>
							<th>Sort</th>
							<th></th>
						</tr>
						<tr ng-repeat="a in aliases">
							<td>{{a.alias}}</td>
							<td>{{a.prep}}</td>
							<td>{{a.name_alt}}</td>
							<td>{{a.top}}</td>
							<td>{{a.sort}}</td>
							<td>
								<span class="orange link" ng-click="remove_alias(a.id_community_alias)">Remove</span>
							</td>
						</tr>
					</table>
				</div>
			</div>
		</form>

	</div>

</div>


<spinner-loading></spinner-loading>
<hack-expand-content></hack-expand-content>