<div class="admin-content-wrapper">
	<div class="admin-content admin-content-suggestions">
		<table class="admin-suggestions-filter">
			<tr>
				<td class="label-sub">SEARCH</td>
				<td class="content-sub"><input name="suggestion-search" type="text" style="width: 200px;" value="<?=strip_tags($_REQUEST['search'])?>"></td>
				<td style="width: 100%"></td>
				<td class="label-sub">DATE&nbsp;RANGE</td>
				<?
					$date = new DateTime('now');
					$start = $date->format('m/d/Y');
					$date->modify('14 days ago');
					$end = $date->format('m/d/Y');
				?>
				<td class="content-sub"><input name="date-range" class="date-picker" type="text" style="width: 200px;" value="<?=$end?>,<?=$start?>"></td>
				<td class="suggestion-range-all" nowrap>&nbsp;&nbsp;<input type="checkbox" name="suggestion-range-all"><label>&nbsp;All Dates</label></td>
			</tr>
			<tr>
				<td class="label-sub">TYPE</td>
				<td class="content-sub">
					<? $types = ['dish']; ?>
					<select name="type">
						<option value="" selected>[ All ]</option>
						<? foreach ($types as $type) : ?>
							<option value="<?=$type?>"><?=$type?></option>
						<? endforeach ; ?>
					</select>
				</td>
				<td style="width: 100%"></td>
				<td class="label-sub">STATUS</td>
				<td class="content-sub" colspan="2">
					<? $states = ['new','deleted','applied']; ?>
					<select name="status">
						<option value="" selected>[ All ]</option>
						<? foreach ($states as $status) : ?>
							<option value="<?=$status?>"><?=$status?></option>
						<? endforeach ; ?>
					</select>
				</td>
			</tr>
			<tr>
				<td class="label-sub">LIMIT</td>
				<td class="content-sub">
					<input type="number" name="limit" value="25" min="0">
				</td>
				<td style="width: 100%"></td>
				<td class="label-sub">RESTAURANT</td>
				<td class="content-sub" colspan="2">
					<select name="restaurant">
						<option value="" selected>[ All ]</option>
						<? foreach (Restaurant::q('SELECT * FROM restaurant ORDER BY name') as $restaurant) : ?>
							<option value="<?=$restaurant->id_restaurant?>"><?=$restaurant->name?></option>
						<? endforeach ; ?>
					</select>
				</td>
				
			</tr>
			
			<tr>
				<td class="label-sub"></td>
				<td class="content-sub">
				</td>
				<td style="width: 100%"></td>
				<td class="label-sub">COMMUNITY</td>
				<td class="content-sub" colspan="2">
					<select name="community">
						<option value="" selected>[ All ]</option>
						<? foreach (Community::q('SELECT * FROM community ORDER BY name') as $community) : ?>
							<option value="<?=$community->id_community?>"><?=$community->name?></option>
						<? endforeach ; ?>
					</select>
				</td>
			</tr>
			
			<tr>
				<td colspan="6">
					<table cellpadding="3" cellspacing="3" style="width: auto; margin: 0 auto;">
						<tr>
							<td><div class="action-button green action-button-small admin-suggestion-search"><span>Search</span></div></td>
						</tr>
					</table>
				</td>
				
			</tr>
		</table>
		<br /><br />
		<div class="divider dots"></div>
		<br />
		<div class="suggestions-loader"><img src="/assets/images/admin/loader.gif"></div>
		<div class="suggestions-content"></div>
	</div>
</div>		
<script>
	$(function() {		
		$('.admin-suggestion-search').live('click', function() {
			App.suggestions.load();
		});
		$('[name="suggestion-search"]').live('keyup', function(e) {
			if (e.which == 13) {
				App.suggestions.load();
			}
		});
		$('input[name="suggestion-range-all"]').live('change', function() {
			if ($(this).prop('checked')) {
				$('.date-picker').attr('disabled', 'disabled');
				$('.date-picker').val('');
			} else {
				$('.date-picker').removeAttr('disabled');
			}
		});
		App.suggestions.load();
	});
</script>