<!doctype html>
<html lang="en">
<head>
<base href="/">
<title><?=$this->title ? $this->title : 'Crunchbutton'?></title>
<meta name="fragment" content="!" />
<meta name="viewport" content="initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0" />
<meta name="format-detection" content="telephone=no">

<meta http-equiv="X-UA-Compatible" content="IE=edge" />

<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black">

<link rel="apple-touch-icon-precomposed" href="/assets/images/micro/appicon.png">
<?=$this->display('layout/html.servertime')?>

<? if (c::config()->bundle) : ?>
	<link rel="stylesheet" type="text/css" href="/assets/css/bundle.css?v=<?=Deploy_Server::currentVersion()?>&s=seven">
<? else : ?>
	<?=$this->display('bundle/css', ['set' => ['style' => ['seven']]])?>
<? endif ; ?>
<link rel="shortcut icon" href="/assets/images/micro/appicon.png">

<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
<link href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet" type="text/css">

<script type="text/javascript" src="https://www.google.com/jsapi"></script>

<?=$this->display('layout/html.templates')?>

<?=$this->display('layout/html.facebook')?>
