<?=$this->display('layout/html.top')?>

<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.1/angular.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.1/angular-route.min.js"></script>
<script src="//js.balancedpayments.com/v1/balanced.js"></script>

<? if (c::config()->bundle) : ?>
	<script src="/assets/js/bundle.js?v=<?=Cana_Util::gitVersion()?>&s=app"></script>
<? else : ?>
	<?=$this->display('bundle/js', ['set' => ['scripts' => ['app']]])?>
<? endif ; ?>

<?=$this->display('layout/html.bottom')?>

<script src="//maps.googleapis.com/maps/api/js?libraries=places&sensor=false"></script>