
<div class="snap-drawers static-nav-viewport" ng-controller="SideMenuCtrl">
	<div class="snap-drawer snap-drawer-left side-menu" id="side-menu">
		<div>
			<div class="pushabutton"></div>
			<ul>
				<li ng-instant="navigation.link('/food-delivery')">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-cutlery"></i></td>
							<td class="side-menu-label">Restaurants</a></td>
						</tr>
					</table>
				</li>
				<li ng-show="account.user.id_user" ng-instant="navigation.link('/orders')">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-truck"></i></td>
							<td class="side-menu-label">Previous Orders</a></td>
						</tr>
					</table>
				</li>
				<li ng-instant="navigation.link('/location')">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-map-marker"></i></td>
							<td class="side-menu-label">Change Location</a></td>
						</tr>
					</table>
				</li>
				<li ng-instant="navigation.link('/help')">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-heart"></i></td>
							<td class="side-menu-label">Help</a></td>
						</tr>
					</table>
				</li>
				<li ng-instant="navigation.link('/about')">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-lightbulb-o"></i></td>
							<td class="side-menu-label">About</a></td>
						</tr>
					</table>
				</li>
				<li ng-show="!account.user.id_user" ng-instant="navigation.signin()">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-sign-in"></i></td>
							<td class="side-menu-label">Log In</a></td>
						</tr>
					</table>
				</li>
				<li ng-show="account.user.id_user" ng-instant="signout.do()">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-sign-out"></i></td>
							<td class="side-menu-label">Logout</a></td>
						</tr>
					</table>
				</li>

				<li ng-instant="test.card()" ng-show="account.user.debug">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-circle-o"></i></td>
							<td class="side-menu-label">TEST: card</a></td>
						</tr>
					</table>
				</li>
				<li ng-instant="test.clearloc()" ng-show="account.user.debug">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-circle-o"></i></td>
							<td class="side-menu-label">TEST: clear loc</a></td>
						</tr>
					</table>
				</li>
				<li ng-instant="test.reload()" ng-show="account.user.debug">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-circle-o"></i></td>
							<td class="side-menu-label">TEST: reload page</a></td>
						</tr>
					</table>
				</li>
			</ul>
		</div>
	</div>
</div>

<div class="wrapper static-nav-viewport">
	
	<div id="snap-content" class="snap-content">
		<div class="navs" data-position="fixed" ng-controller="MainHeaderCtrl">
			<div class="nav nav-top">
				<div class="content">

					<div id="dropdown-menu" class="dropdown dropdown-tip">
						<ul class="dropdown-menu">
							<li><a ng-click="navigation.link('/food-delivery')">Restaurants</a></li>
							<li><a ng-click="navigation.link('/orders')" ng-show="account.user.id_user">Previous Orders</a></li>
							<li><a ng-click="navigation.link('/location')">Change Location</a></li>
							<li class="dropdown-divider"></li>
							<li><a ng-click="navigation.link('/help')">Help</a></li>
							<li><a ng-click="navigation.link('/about')">About</a></li>
							<li><a ng-click="navigation.signin()" ng-show="!account.user.id_user">Log In</a></li>
							<li><a ng-click="signout.do()" ng-show="account.user.id_user">Log Out</a></li>
							<li class="dropdown-divider" ng-show="account.user.debug"></li>
							<li><a ng-click="App.test.card()" ng-show="account.user.debug">TEST: card</a></li>
							<li><a ng-click="App.test.clearloc()" ng-show="account.user.debug">TEST: clear location</a></li>
							<li><a ng-click="navigation.link('/')" ng-show="account.user.debug">TEST: go home</a></li>
							<li><a ng-click="App.test.card()" ng-show="account.user.debug">TEST: card</a></li>
					    </ul>
					</div>
				
					<div title="Menu" class="menu side" ng-click="navigation.menu()" ng-show="navigation.buttons.menu"></div>
					<div title="Menu" class="menu drop" data-dropdown="#dropdown-menu" ng-show="navigation.buttons.menu"></div>
					<div title="Back" ng-show="navigation.buttons.back" class="nav-back hide-before-init" ng-instant="back()"></div>
					
					<div title="Cart" class="nav-cart hide-before-init" ng-click="cartScroll()" ng-show="order.info.totalItems">
						<div class="fa fa-shopping-cart"></div>
						<div class="nav-cart-count">{{order.info.totalItems}}</div>
					</div>

					<div title="Crunchbutton" class="logo animated-resize" ng-click="navigation.home()"></div>

				</div>
			</div>
		</div>


		<div ng-class="{'button-bottom-show': (navigation.page == 'restaurant' && navigation.restaurant._open && navigation.order.cart.hasItems() && !notificationBarStatus ), 'button-bottom-show-notification-bar-on': (navigation.page == 'restaurant' && navigation.restaurant._open && navigation.order.cart.hasItems() && notificationBarStatus )}" class="button-bottom-wrapper">
			<div class="button-pushable" ng-show="navigation.order.form.name || navigation.order.form.phone"><button class="button orange get-food ani-all" ng-click="navigation.order.submit();"><div>Get Food</div></button></div>
			<div class="button-pushable" ng-show="!navigation.order.form.name && !navigation.order.form.phone"><button class="button orange get-food ani-all" ng-click="navigation.order.checkout();"><div>Checkout</div></button></div>
		</div>

		<div class="snap-content-inner bg" ng-scroll-position>
			<div class="content<?=$e?>">
				<div ng-view><?=$this->content?></div>
			</div>

			<div class="divider"></div>

			<div class="footer">
				<div class="divider line"></div>
				<div class="content-padding">
					<? if (!$this->export) : ?>
						<div class="fb-like-box" data-width="200" data-href="https://www.facebook.com/crunchbutton" data-width="The pixel width of the plugin" data-height="The pixel height of the plugin" data-show-faces="false" data-header="false" data-stream="false" data-show-border="false"></div>
					<? endif ; ?>
	
					<div class="social">
						<a class="fa fa-facebook"></a>
						<a class="fa fa-twitter"></a>
						<a class="fa fa-linkedin"></a>
					</div>
					<div class="divider"></div>
					<span class="copyright">&copy; <?=date('Y')?> YouBeo, Inc.</span>
				</div>
			</div>

		</div>


	</div>

	<div class="divider"></div>
</div>

<div ng-include="'assets/view/notification.alert.html'"></div>
<div ng-include="'assets/view/restaurant.closed.html'"></div>
<div ng-include="'assets/view/account.html'"></div>
<div ng-include="'assets/view/account.reset.html'"></div>
<div ng-include="'assets/view/restaurant.closed.inline.html'"></div>
<div ng-include="'assets/view/giftcard.html'"></div>
<div ng-include="'assets/view/suggestion.html'"></div>
<div ng-include="'assets/view/support.html'"></div>
<div ng-include="'assets/view/connection.error.html'"></div>

<div id="fb-root"></div>
<div class="is-ui2"></div>