<?=$this->display('layout/html.top')?>
<script src="//use.typekit.net/qeo8tnt.js"></script>
<script>try{Typekit.load();}catch(e){}</script>
<? $angular = '1.4.6'; ?>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/<?=$angular?>/angular.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/<?=$angular?>/angular-route.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/<?=$angular?>/angular-animate.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/<?=$angular?>/angular-resource.min.js"></script>
<script>
window.twttr = ( function(d, s, id) {
	var js, fjs = d.getElementsByTagName(s)[0], t = window.twttr || {};
	if (d.getElementById(id)) return;
	js = d.createElement(s);
	js.id = id;
	js.src = "https://platform.twitter.com/widgets.js";
	fjs.parentNode.insertBefore(js, fjs);
	t._e = [];
	t.ready = function(f) { t._e.push(f); };
	return t;
	} (document, "script", "twitter-wjs") ) ;
</script>
<!-- Payment stuff -->
<script type="text/javascript" src="//js.stripe.com/v2/"></script>

<? if (c::config()->bundle) : ?>
	<? $js = c::config()->site->config('s3-bundle')->val() ? 'https://'.c::config()->s3->buckets->build->cache.'/'.Deploy_Server::currentVersion().'/js/crunchbutton.js' : '/assets/js/bundle.js?v='.Deploy_Server::currentVersion().'&s=app' ?>
	<script src="<?=$js?>"></script>
<? else : ?>
	<?=$this->display('bundle/js', ['set' => ['scripts' => ['app']]])?>
<? endif ; ?>

<?=$this->display('layout/html.bottom')?>

<script src="//maps.googleapis.com/maps/api/js?libraries=places&sensor=false"></script>
