
<div class="snap-drawers static-nav-viewport" ng-controller="SideMenuCtrl">
	<div class="snap-drawer snap-drawer-left side-menu" id="side-menu">
		<div>
			<div class="pushabutton"></div>
			<ul>
				<li ng-click="navigation.link('/splash')" ng-show="!account.user.id_user">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-rocket"></i></td>
							<td class="side-menu-label">Get Started</a></td>
						</tr>
					</table>
				</li>
				<li ng-click="navigation.link('/food-delivery')">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-cutlery"></i></td>
							<td class="side-menu-label">Restaurants</a></td>
						</tr>
					</table>
				</li>
				<li ng-show="account.user.id_user" ng-click="navigation.link('/orders')">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-truck"></i></td>
							<td class="side-menu-label">Previous Orders</a></td>
						</tr>
					</table>
				</li>
				<li ng-click="navigation.link('/location')">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-map-marker"></i></td>
							<td class="side-menu-label">Change Location</a></td>
						</tr>
					</table>
				</li>
				<li ng-click="navigation.link('/help')">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-heart"></i></td>
							<td class="side-menu-label">Help</a></td>
						</tr>
					</table>
				</li>
				<li ng-click="navigation.link('/about')">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-lightbulb-o"></i></td>
							<td class="side-menu-label">About</a></td>
						</tr>
					</table>
				</li>
				<li ng-click="navigation.link('/jobs')">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-beer"></i></td>
							<td class="side-menu-label">Free Beer</a></td>
						</tr>
					</table>
				</li>
				<li ng-show="!account.user.id_user" ng-click="navigation.signin()">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-sign-in"></i></td>
							<td class="side-menu-label">Log In</a></td>
						</tr>
					</table>
				</li>
				<li ng-show="account.user.id_user" ng-click="signout.do()">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-sign-out"></i></td>
							<td class="side-menu-label">Logout</a></td>
						</tr>
					</table>
				</li>
				
				<li>
					<a href="{{(isPhoneGap && 'fb://profile/372531956099058' || !isPhoneGap && 'http://facebook.com/crunchbutton')}}" target="_blank">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-facebook-square"></i></td>
							<td class="side-menu-label">Like!</a></td>
						</tr>
					</table>
					</a>
				</li>

				<li ng-click="test.card()" ng-show="account.user.debug">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-circle-o"></i></td>
							<td class="side-menu-label">TEST: card</a></td>
						</tr>
					</table>
				</li>
				<li ng-click="test.clearloc()" ng-show="account.user.debug">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-circle-o"></i></td>
							<td class="side-menu-label">TEST: clear loc</a></td>
						</tr>
					</table>
				</li>
				<li ng-click="test.reload()" ng-show="account.user.debug">
					<table cellpadding="0" cellspacing="0" class="side-menu-wrap">
						<tr>
							<td class="side-menu-icon"><i class="fa fa-circle-o"></i></td>
							<td class="side-menu-label">TEST: reload page</a></td>
						</tr>
					</table>
				</li>
			</ul>
		</div>
	</div>
	<div class="snap-drawer snap-drawer-right side-menu"></div>
</div>

<div class="wrapper static-nav-viewport">
	
	<div id="snap-content" class="snap-content">
		<div class="navs fixed" data-position="fixed" ng-controller="MainHeaderCtrl">
			<div class="nav nav-top">
				<div class="content">
					<div class="hide-before-init dropdown dropdown-tip" ng-show="menudropdown">
						<ul class="dropdown-menu">
							<li><a href="/splash" ng-click="navigation.link('/splash')" ng-show="!account.user.id_user"><i class="fa fa-rocket"></i>Get Started!</a></li>
							<li><a href="/food-delivery" ng-click="navigation.link('/food-delivery')"><i class="fa fa-cutlery"></i>Restaurants</a></li>
							<li><a href="/orders" ng-click="navigation.link('/orders')" ng-show="account.user.id_user"><i class="fa fa-truck"></i>Previous Orders</a></li>
							<li><a href="/location" ng-click="navigation.link('/location')"><i class="fa fa-map-marker"></i>Change Location</a></li>
							<li class="dropdown-divider"></li>
							<li><a href="/help" ng-click="navigation.link('/help')"><i class="fa fa-heart"></i>Help</a></li>
							<li><a href="/about" ng-click="navigation.link('/about')"><i class="fa fa-lightbulb-o"></i>About</a></li>
							<li><a href="/jobs" ng-click="navigation.link('/jobs')"><i class="fa fa-beer"></i>Free Beer</a></li>
							<li><a ng-click="navigation.signin()" ng-show="!account.user.id_user"><i class="fa fa-sign-in"></i>Log In</a></li>
							<li><a ng-click="signout.do()" ng-show="account.user.id_user"><i class="fa fa-sign-out"></i>Log Out</a></li>
							<li class="dropdown-divider" ng-show="account.user.debug"></li>
							<li><a ng-click="App.test.card()" ng-show="account.user.debug"><i class="fa fa-circle-o"></i>TEST: card</a></li>
							<li><a ng-click="App.test.clearloc()" ng-show="account.user.debug"><i class="fa fa-circle-o"></i>TEST: clear location</a></li>
							<li><a ng-click="navigation.link('/')" ng-show="account.user.debug"><i class="fa fa-circle-o"></i>TEST: go home</a></li>
							<li><a ng-click="App.test.card()" ng-show="account.user.debug"><i class="fa fa-circle-o"></i>TEST: card</a></li>
					    </ul>
					</div>
				
					<div title="Menu" class="menu side" ng-click="navigation.menu()" ng-show="navigation.buttons.menu"></div>
					<div title="Menu" class="menu drop" ng-show="navigation.buttons.menu" ng-toggle="menudropdown"></div>
					<div title="Back" ng-show="navigation.buttons.back" class="nav-back hide-before-init" ng-click="back()"></div>
					
					<div title="Cart" class="nav-cart hide-before-init" ng-click="cartScroll(order.restaurant.permalink)" ng-show="order.info.totalItems">
						<div class="fa fa-shopping-cart"></div>
						<div class="nav-cart-count">{{order.info.totalItems}}</div>
					</div>

					<div title="Crunchbutton" class="logo animated-resize" ng-click="navigation.home()"></div>

				</div>
			</div>
		</div>


		<div ng-class="{'button-bottom-show': (navigation.page == 'restaurant' && navigation.restaurant._open && navigation.order.cart.hasItems() && !notificationBarStatus ), 'button-bottom-show-notification-bar-on': (navigation.page == 'restaurant' && navigation.restaurant._open && navigation.order.cart.hasItems() && notificationBarStatus )}" class="button-bottom-wrapper fixed">
			<div class="button-pushable" ng-show="navigation.order.form.name || navigation.order.form.phone"><button class="button orange get-food ani-all" ng-click="navigation.order.submit();"><div>Get Food</div></button></div>
			<div class="button-pushable" ng-show="!navigation.order.form.name && !navigation.order.form.phone"><button class="button orange get-food ani-all" ng-click="navigation.order.checkout();"><div>Checkout</div></button></div>
		</div>

		<div class="snap-content-inner bg" ng-scroll-position>
			<div class="content" ng-scroll-spy>
				<div ng-view><?=$this->content?></div>
			</div>

			<div class="divider"></div>

			<div class="footer">
				<div class="divider line"></div>
				<div class="content-padding">
					<? if (!$this->export) : ?>
						<div class="fb-like-box" data-width="200" data-href="https://www.facebook.com/crunchbutton" data-width="The pixel width of the plugin" data-height="The pixel height of the plugin" data-show-faces="false" data-header="false" data-stream="false" data-show-border="false"></div>
					<? endif ; ?>
	
					<div class="social">
						<a href="http://facebook.com/crunchbutton" target="_blank" class="fa fa-facebook"></a>
						<a href="twitter.com/crunchbutton" target="_blank" class="fa fa-twitter"></a>
						<a href="http://www.linkedin.com/company/crunchbutton" target="_blank" class="fa fa-linkedin"></a>
					</div>
					<div class="divider"></div>
					<div class="copyright">&copy; <?=date('Y')?> <a href="/legal">Crunchbutton</a></div>
					<div class="divider"></div>
					<br>
				</div>
			</div>

		</div>


	</div>

	<div class="divider"></div>
</div>

<div ng-include="'assets/view/notification.alert.html'"></div>
<div ng-include="'assets/view/restaurant.closed.html'"></div>
<div ng-include="'assets/view/account.html'"></div>
<div ng-include="'assets/view/account.reset.html'"></div>
<div ng-include="'assets/view/restaurant.closed.inline.html'"></div>
<div ng-include="'assets/view/giftcard.html'"></div>
<div ng-include="'assets/view/suggestion.html'"></div>
<div ng-include="'assets/view/support.html'"></div>
<div ng-include="'assets/view/connection.error.html'"></div>

<div id="fb-root"></div>
<div class="is-ui2"></div>


<audio id="cafe-fail">
	<source src="assets/audio/fail.mp3"></source>
	<source src="assets/audio/fail.ogg"></source>
</audio>
<audio id="cafe-win">
	<source src="assets/audio/win.mp3"></source>
	<source src="assets/audio/win.ogg"></source>
</audio>
<audio id="cafe-loose">
	<source src="assets/audio/loose.mp3"></source>
	<source src="assets/audio/loose.ogg"></source>
</audio>
<audio id="cafe-good">
	<source src="assets/audio/good.mp3"></source>
	<source src="assets/audio/good.ogg"></source>
</audio>
<audio id="cafe-start">
	<source src="assets/audio/start.mp3"></source>
	<source src="assets/audio/start.ogg"></source>
</audio>